Repository DataDog/dd-trace-py, pull requests merged in 2018-12, with the labels that each got.

#652 [aiohttp] Add HTTP method to the root span resource
  ddtrace/contrib/aiohttp/middlewares.py
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/aiohttp/test_request.py
  tests/contrib/aiohttp/test_request_safety.py
Labels: community, enhancement

#747 [tests] Provide default implementation of patch test methods
  tests/contrib/patch.py
  tests/subprocesstest.py
Labels: dev/testing, enhancement

#748 [tests] have most tests use pytest test runner
  conftest.py
  docker-compose.yml
  tests/base/__init__.py
  tests/contrib/aiobotocore/py35/__init__.py
  tests/contrib/aiobotocore/py35/test.py
  tests/contrib/aiopg/py35/__init__.py
  tests/contrib/aiopg/py35/test.py
  tests/contrib/aiopg/test.py
  tests/contrib/pymemcache/autopatch/__init__.py
  tests/contrib/pymemcache/autopatch/test.py
  tests/test_global_config.py
  tox.ini
Labels: dev/testing

#714 [cassandra] Fix batched query leak
  ddtrace/contrib/cassandra/session.py
  tests/contrib/cassandra/test.py
Labels: enhancement

#764 [opentracer] Set global tags
  ddtrace/opentracer/tracer.py
  tests/opentracer/test_tracer.py
Labels: opentracer

#752 [tests] fix linting in test files
  tests/contrib/aiobotocore/test.py
  tests/contrib/aiopg/py35/test.py
  tests/contrib/aiopg/test.py
  tests/contrib/asyncio/test_helpers.py
  tests/contrib/asyncio/test_tracer.py
  tests/contrib/asyncio/test_tracer_safety.py
  tests/contrib/boto/test.py
  tests/contrib/bottle/test_autopatch.py
  tests/contrib/cassandra/test.py
  tests/contrib/dbapi/test_unit.py
  tests/contrib/django/app/views.py
  tests/contrib/django/compat.py
  tests/contrib/django/test_autopatching.py
  tests/contrib/django/test_cache_backends.py
  tests/contrib/django/test_cache_client.py
  tests/contrib/django/test_cache_views.py
  tests/contrib/django/test_instrumentation.py
  tests/contrib/django/test_templates.py
  tests/contrib/djangorestframework/app/exceptions.py
  tests/contrib/djangorestframework/app/views.py
  tests/contrib/djangorestframework/runtests.py
  tests/contrib/elasticsearch/test.py
  tests/contrib/falcon/test_distributed_tracing.py
  tests/contrib/flask/test_flask_helpers.py
  tests/contrib/flask/test_hooks.py
  tests/contrib/flask/test_template.py
  tests/contrib/flask_cache/test_utils.py
  tests/contrib/flask_cache/test_wrapper_safety.py
  tests/contrib/gevent/test_tracer.py
  tests/contrib/grpc/test_grpc.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/mongoengine/test.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/psycopg/test_psycopg.py
  tests/contrib/pylibmc/test.py
  tests/contrib/pymemcache/utils.py
  tests/contrib/pyramid/app/web.py
  tests/contrib/pyramid/test_pyramid.py
  tests/contrib/pyramid/test_pyramid_autopatch.py
  tests/contrib/sqlalchemy/mixins.py
  tests/contrib/sqlite3/test_sqlite3.py
  tests/contrib/test_utils.py
  tests/contrib/tornado/test_config.py
  tests/contrib/tornado/test_executor_decorator.py
  tests/contrib/vertica/test_vertica.py
  tests/opentracer/conftest.py
  tests/opentracer/test_dd_compatibility.py
  tests/opentracer/test_tracer.py
  tests/opentracer/test_tracer_asyncio.py
  tests/opentracer/test_tracer_gevent.py
  tests/opentracer/test_tracer_tornado.py
  tests/opentracer/utils.py
Labels: dev/testing

#760 [tests] remove unused monkey.py test file
  tests/monkey.py
Labels: dev/testing

#768 [aws]Flatten span tag names
  .circleci/config.yml
  ddtrace/contrib/aiobotocore/patch.py
  ddtrace/contrib/boto/patch.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/ext/aws.py
  ddtrace/utils/formats.py
  tests/contrib/aiobotocore/test.py
  tests/contrib/boto/test.py
  tests/contrib/botocore/test.py
  tests/test_utils.py
  tox.ini
Labels: enhancement

#751 [core] add six and replace custom compat functions
  ddtrace/compat.py
  ddtrace/compat_async.py
  ddtrace/utils/reraise.py
  setup.py
  tox.ini
Labels: core, dev/tooling

#774 Enable priority sampling by default
  ddtrace/tracer.py
  docs/advanced_usage.rst
  tests/contrib/grpc/test_grpc.py
  tests/contrib/pylons/test_pylons.py
  tests/test_integration.py
  tests/test_sampler.py
  tests/utils/tracer.py
Labels: core

#771 [opentracing] Fixing context provider imports for scope manager
  ddtrace/opentracer/utils.py
Labels: bug, opentracer

#781 [core] Add API to configure Trace Search
  ddtrace/constants.py
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/bottle/trace.py
  ddtrace/contrib/django/middleware.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/pyramid/trace.py
  ddtrace/contrib/tornado/handlers.py
  ddtrace/settings.py
  ddtrace/span.py
  tests/contrib/aiohttp/test_request.py
  tests/contrib/aiohttp/utils.py
  tests/contrib/bottle/test.py
  tests/contrib/bottle/test_distributed.py
  tests/contrib/django/test_instrumentation.py
  tests/contrib/django/test_middleware.py
  tests/contrib/falcon/test_autopatch.py
  tests/contrib/falcon/test_middleware.py
  tests/contrib/falcon/test_suite.py
  tests/contrib/flask/__init__.py
  tests/contrib/flask/test_request.py
  tests/contrib/molten/test_molten.py
  tests/contrib/pylons/test_pylons.py
  tests/contrib/pyramid/test_pyramid.py
  tests/contrib/pyramid/utils.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/tornado/utils.py
  tests/utils/span.py
  tox.ini
Labels: core

#783 0.19.0
  .circleci/config.yml
  ddtrace/__init__.py
  ddtrace/constants.py
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/bottle/trace.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/django/middleware.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/psycopg/patch.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/pyramid/trace.py
  ddtrace/contrib/tornado/handlers.py
  ddtrace/opentracer/utils.py
  ddtrace/settings.py
  ddtrace/span.py
  ddtrace/tracer.py
  docs/advanced_usage.rst
  tests/contrib/aiohttp/test_request.py
  tests/contrib/aiohttp/utils.py
  tests/contrib/bottle/test.py
  tests/contrib/bottle/test_distributed.py
  tests/contrib/dbapi/test_unit.py
  tests/contrib/django/test_cache_views.py
  tests/contrib/django/test_connection.py
  tests/contrib/django/test_instrumentation.py
  tests/contrib/django/test_middleware.py
  tests/contrib/django/utils.py
  tests/contrib/falcon/test_autopatch.py
  tests/contrib/falcon/test_middleware.py
  tests/contrib/falcon/test_suite.py
  tests/contrib/flask/__init__.py
  tests/contrib/flask/test_request.py
  tests/contrib/grpc/test_grpc.py
  tests/contrib/molten/test_molten.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysql.py
  tests/contrib/psycopg/test_psycopg.py
  tests/contrib/pylons/test_pylons.py
  tests/contrib/pymysql/test_pymysql.py
  tests/contrib/pyramid/test_pyramid.py
  tests/contrib/pyramid/utils.py
  tests/contrib/sqlite3/test_sqlite3.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/tornado/utils.py
  tests/test_integration.py
  tests/test_sampler.py
  tests/utils/span.py
  tests/utils/tracer.py
  tox.ini
Labels: release
