Repository DataDog/dd-trace-py, pull requests merged in 2018-09, with the labels that each got.

#556 [core] remove the root logger configuration within the library
  ddtrace/__init__.py
Labels: core

#558 [docs] Fix docs deploy
  .circleci/config.yml
  Rakefile
  docs/conf.py
Labels: docs

#585 [tests] Update docker compose file version and images tags
  .env
  docker-compose.yml
Labels: dev/testing

#584 [ci] Optimize circleci docker images
  .circleci/config.yml
Labels: dev/testing

#555 [docs] Doc improvement
  docs/advanced_usage.rst
Labels: docs

#592 [ci] Reduce django and djangorestframework test matrix
  .circleci/config.yml
  tox.ini
Labels: dev/testing

#594 Update elasticsearch docker image from 2.3 to 2.4
  docker-compose.yml
Labels: dev/testing

#595 [opentracer] Properly handle corrupted span context propagation
  ddtrace/opentracer/propagation/http.py
  tests/opentracer/test_tracer.py
Labels: opentracer

#605 Improve performance of tests execution
  .circleci/config.yml
  .circleci/images/runner/Dockerfile
  tests/contrib/cassandra/test.py
  tox.ini
Labels: dev/testing

#607 [tests] Update the integrations libraries versions to the latest possible.
  .circleci/config.yml
  tests/contrib/elasticsearch/test.py
  tests/contrib/falcon/test_autopatch.py
  tox.ini
Labels: dev/testing

#612 Fix docstring for `Tracer.set_tags`
  ddtrace/tracer.py
Labels: docs

#610 [docs] Clarify debug mode
  ddtrace/contrib/django/__init__.py
  docs/advanced_usage.rst
Labels: docs

#616 Fix "does not provide the extra opentracing"
  setup.py
Labels: opentracer

#609 [tests] Refactor tox.ini file
  .circleci/config.yml
  tox.ini
Labels: dev/testing

#615 [circleci] Improve python docs deployment strategy
  .circleci/config.yml
Labels: docs

#621 [docs] Add priority sampling to ddtrace-run usage
  ddtrace/commands/ddtrace_run.py
Labels: docs

#622 [ci] Handle flakiness of cassandra tests during keyspace drop
  tests/contrib/cassandra/test.py
Labels: dev/testing
