Repository DataDog/dd-trace-py, pull requests merged in 2018-10, with the labels that each got.

#626 Fix minimum Django version for user.is_authenticated property
  ddtrace/contrib/django/compat.py
Labels: enhancement

#533 Add rediscluster integration
  .circleci/config.yml
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/rediscluster/__init__.py
  ddtrace/contrib/rediscluster/patch.py
  ddtrace/ext/redis.py
  docker-compose.yml
  docs/db_integrations.rst
  docs/index.rst
  tests/contrib/config.py
  tests/contrib/rediscluster/__init__.py
  tests/contrib/rediscluster/test.py
  tox.ini
Labels: integrations

#629 Allow django cache to be seen as a different service.
  ddtrace/contrib/django/__init__.py
  ddtrace/contrib/django/cache.py
  ddtrace/contrib/django/conf.py
  tests/contrib/django/test_cache_client.py
Labels: enhancement

#625 [core] add Tracer API to retrieve the root Span
  ddtrace/context.py
  ddtrace/tracer.py
  tests/test_context.py
  tests/test_tracer.py
Labels: core

#637 [rediscluster] Add wait for services to start
  .circleci/config.yml
  tests/wait-for-services.py
  tox.ini
Labels: dev/testing, enhancement

#638 CircleCI run tests in the new alpine-based test runner defined in https://github.com/DataDog/docker-library
  .circleci/config.yml
  .circleci/images/runner/Dockerfile
Labels: dev/testing

#640 [tests] Add test cases for API._put
  tests/test_api.py
Labels: core, dev/testing

#630 [celery] add retry reason metadata to spans
  ddtrace/contrib/celery/app.py
  ddtrace/contrib/celery/constants.py
  ddtrace/contrib/celery/signals.py
  tests/contrib/celery/test_integration.py
Labels: enhancement

#600 Add support for gevent.pool.Pool and gevent.pool.Group
  ddtrace/contrib/gevent/greenlet.py
  ddtrace/contrib/gevent/patch.py
  tests/contrib/gevent/test_tracer.py
Labels: integrations

#643 [tests] Skip flaky TestWorkers.test_worker_multiple_traces test case
  tests/test_integration.py
Labels: dev/testing

#634 Add Vertica Integration
  .circleci/config.yml
  ddtrace/contrib/vertica/__init__.py
  ddtrace/contrib/vertica/constants.py
  ddtrace/contrib/vertica/patch.py
  ddtrace/ext/db.py
  ddtrace/monkey.py
  docker-compose.yml
  docs/db_integrations.rst
  docs/index.rst
  tests/contrib/config.py
  tests/contrib/vertica/__init__.py
  tests/contrib/vertica/fixtures.py
  tests/contrib/vertica/test_vertica.py
  tests/contrib/vertica/utils.py
  tests/wait-for-services.py
  tox.ini
Labels: integrations

#644 [tests] Remove tests for not supported gevent 1.3
  .circleci/config.yml
  docs/index.rst
  tox.ini
Labels: dev/testing

#623 Fix mysqldb monkey patch
  ddtrace/contrib/mysqldb/patch.py
Labels: community, integrations

#650 [core] Update config to allow configuration before patching
  ddtrace/settings.py
  ddtrace/utils/merge.py
  tests/test_global_config.py
Labels: bug, core

#654 Make CI faster by disabling dist and install in autopatching tests
  .circleci/config.yml
  tests/ddtrace_run.py
  tox.ini
Labels: dev/testing

#645 [django] Infer span resource name when internal error handler is used
  ddtrace/contrib/django/compat.py
  ddtrace/contrib/django/middleware.py
  tests/contrib/django/test_middleware.py
Labels: enhancement

#628 [elasticsearch] Make constant organization consistent with other integrations
  ddtrace/contrib/elasticsearch/patch.py
  ddtrace/contrib/elasticsearch/quantize.py
  ddtrace/contrib/elasticsearch/transport.py
  ddtrace/ext/elasticsearch.py
  tests/contrib/elasticsearch/test.py
Labels: enhancement

#641 [grpc] Add grpc client support.
  .circleci/config.yml
  ddtrace/contrib/grpc/__init__.py
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/contrib/grpc/patch.py
  ddtrace/contrib/grpc/propagation.py
  ddtrace/monkey.py
  docs/index.rst
  docs/other_integrations.rst
  tests/contrib/grpc/__init__.py
  tests/contrib/grpc/hello.proto
  tests/contrib/grpc/hello_pb2.py
  tests/contrib/grpc/hello_pb2_grpc.py
  tests/contrib/grpc/test_grpc.py
  tox.ini
Labels: integrations

#658 [django] Enabled by default
  ddtrace/contrib/django/patch.py
  ddtrace/monkey.py
  docs/index.rst
  tests/contrib/django/test_instrumentation.py
Labels: enhancement, integrations

#649 [jinja2] Add jinja2 integration
  .circleci/config.yml
  ddtrace/contrib/jinja2/__init__.py
  ddtrace/contrib/jinja2/constants.py
  ddtrace/contrib/jinja2/patch.py
  ddtrace/monkey.py
  docs/index.rst
  docs/other_integrations.rst
  tests/contrib/jinja2/templates/base.html
  tests/contrib/jinja2/templates/template.html
  tests/contrib/jinja2/test_jinja2.py
  tox.ini
Labels: community, integrations

#660 [falcon] Enabled by default
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/falcon/patch.py
  ddtrace/monkey.py
  docs/index.rst
  tests/contrib/falcon/test_suite.py
Labels: enhancement, integrations

#666 [requests] Enabled by default
  .circleci/config.yml
  ddtrace/monkey.py
  docs/index.rst
  tests/contrib/requests/test_requests_autopatch.py
  tox.ini
Labels: enhancement, integrations

#670 [ci] Reorganize autopatch test calls
  .circleci/config.yml
Labels: dev/testing

#675 [httplib] Enabled by default
  ddtrace/monkey.py
  tests/contrib/httplib/test_httplib.py
Labels: enhancement, integrations

#677 [bottle] Enabled by default
  ddtrace/monkey.py
  docs/index.rst
  tests/contrib/bottle/test_autopatch.py
Labels: enhancement, integrations

#673 [aiobotocore] Enabled by default
  ddtrace/monkey.py
  docs/index.rst
  tests/contrib/aiobotocore/test.py
Labels: enhancement, integrations

#663 [gevent] Support gevent 1.3
  .circleci/config.yml
  ddtrace/contrib/gevent/greenlet.py
  ddtrace/contrib/gevent/patch.py
  docs/index.rst
  tox.ini
Labels: enhancement, integrations
