Repository DataDog/dd-trace-py, pull requests merged in 2018-04, with the labels that each got.

#445 [core] provide an environment getter utility to ensure consistency between env vars
  ddtrace/util.py
  tests/test_utils.py
Labels: core

#443 [core] add a global configuration system
  ddtrace/__init__.py
  ddtrace/configuration.py
  tests/test_configuration.py
Labels: core

#452 Fixing typo in the doc
  docs/index.rst
Labels: docs

#454 [core] fix deprecation warning on `get_env()`
  ddtrace/utils/formats.py
Labels: core

#441 [core] add a Configuration system for integrations
  ddtrace/__init__.py
  ddtrace/pin.py
  ddtrace/settings.py
  tests/test_global_config.py
  tests/test_instance_config.py
  tests/test_pin.py
Labels: core

#433 [requests] provide a service name for the request Span
  ddtrace/contrib/requests/__init__.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/requests/constants.py
  ddtrace/contrib/requests/legacy.py
  ddtrace/contrib/requests/patch.py
  ddtrace/contrib/requests/session.py
  tests/contrib/requests/test_requests.py
  tests/contrib/requests/test_requests_distributed.py
Labels: integrations

#434 [requests] use the domain name as a service name
  ddtrace/compat.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/requests/patch.py
  tests/contrib/requests/test_requests.py
Labels: enhancement, integrations
