Repository DataDog/dd-trace-py, pull requests merged in 2018-03, with the labels that each got.

#429 [futures] provide context propagation for `concurrent` module
  .circleci/config.yml
  ddtrace/contrib/futures/__init__.py
  ddtrace/contrib/futures/patch.py
  ddtrace/contrib/futures/threading.py
  ddtrace/contrib/tornado/patch.py
  ddtrace/monkey.py
  tests/contrib/futures/__init__.py
  tests/contrib/futures/test_propagation.py
  tox.ini
Labels: integrations

#431 [tornado] better compatibility with `futures` instrumentation
  ddtrace/contrib/tornado/compat.py
  ddtrace/contrib/tornado/patch.py
  tests/contrib/tornado/test_executor_decorator.py
Labels: integrations

#439 [bottle] use the `route` argument in TracePlugin, to support Bottle 0.11.x
  .circleci/config.yml
  ddtrace/contrib/bottle/trace.py
  docs/index.rst
  tox.ini
Labels: integrations

#437 [falcon] Add distributed tracing
  ddtrace/contrib/falcon/__init__.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/falcon/patch.py
  tests/contrib/falcon/app/app.py
  tests/contrib/falcon/test_distributed_tracing.py
  tests/contrib/falcon/test_suite.py
  tox.ini
Labels: enhancement, integrations

#440 [docs] update docs format
  ddtrace/contrib/tornado/__init__.py
  ddtrace/filters.py
  docs/index.rst
Labels: docs

#319 Botocore, boto default True
  ddtrace/monkey.py
Labels: integrations

#442 [django] Fix gunicorn gevent worker causing database connection unpatch
  ddtrace/contrib/django/db.py
  tests/contrib/django/test_middleware.py
  tests/contrib/django/utils.py
Labels: integrations

#444 [django] Remove MIDDLEWARE_CLASSES deprecation warning from tests
  tests/contrib/django/app/settings.py
  tests/contrib/django/test_autopatching.py
  tests/contrib/djangorestframework/app/settings.py
Labels: dev/testing, integrations

#446 [django] Fix django test flake
  ddtrace/contrib/django/middleware.py
Labels: dev/testing

#432 [celery] Resolve multiple root span names
  ddtrace/contrib/celery/app.py
  ddtrace/contrib/celery/task.py
  ddtrace/contrib/celery/util.py
  tests/contrib/celery/test_integration.py
  tests/contrib/celery/test_task.py
Labels: bug, integrations

#296 add pymysql support
  .circleci/config.yml
  ddtrace/contrib/pymysql/__init__.py
  ddtrace/contrib/pymysql/patch.py
  ddtrace/contrib/pymysql/tracers.py
  ddtrace/monkey.py
  tests/contrib/pymysql/__init__.py
  tests/contrib/pymysql/test_backwards_compatibility.py
  tests/contrib/pymysql/test_pymysql.py
  tox.ini
Labels: integrations
