Repository DataDog/dd-trace-py, pull requests merged in 2018-11, with the labels that each got.

#684 [core] Add IntegrationConfig helper class
  ddtrace/__init__.py
  ddtrace/settings.py
Labels: core

#667 [flask] rewrite Flask integration
  .circleci/config.yml
  ddtrace/contrib/flask/__init__.py
  ddtrace/contrib/flask/helpers.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask/wrappers.py
  ddtrace/monkey.py
  ddtrace/pin.py
  tests/contrib/flask/__init__.py
  tests/contrib/flask/static/test.txt
  tests/contrib/flask/test_blueprint.py
  tests/contrib/flask/test_errorhandler.py
  tests/contrib/flask/test_flask_helpers.py
  tests/contrib/flask/test_hooks.py
  tests/contrib/flask/test_idempotency.py
  tests/contrib/flask/test_middleware.py
  tests/contrib/flask/test_request.py
  tests/contrib/flask/test_signals.py
  tests/contrib/flask/test_static.py
  tests/contrib/flask/test_template.py
  tests/contrib/flask/test_views.py
  tests/contrib/flask_autopatch/test_flask_autopatch.py
  tests/test_pin.py
  tests/util.py
  tox.ini
Labels: enhancement, integrations

#515 [kombu] Add Kombu tracing
  .circleci/config.yml
  ddtrace/contrib/kombu/__init__.py
  ddtrace/contrib/kombu/constants.py
  ddtrace/contrib/kombu/patch.py
  ddtrace/contrib/kombu/utils.py
  ddtrace/ext/kombu.py
  ddtrace/monkey.py
  docker-compose.yml
  tests/contrib/config.py
  tests/contrib/kombu/__init__.py
  tests/contrib/kombu/test.py
  tests/wait-for-services.py
  tox.ini
Labels: community, integrations

#688 [httplib, requests] Sanitize urls in span metadata
  ddtrace/compat.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/requests/connection.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/requests/test_requests.py
Labels: enhancement, integrations

#679 [core] add support for integration span hooks
  ddtrace/contrib/falcon/__init__.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/settings.py
  tests/contrib/falcon/test_suite.py
  tests/test_global_config.py
Labels: core, enhancement

#668 [core] initial support for partial flushes
  ddtrace/context.py
  tests/test_context.py
Labels: core, enhancement

#701 [elasticsearch] add support for elasticsearch{1,2,5} packages
  .circleci/config.yml
  ddtrace/contrib/elasticsearch/__init__.py
  ddtrace/contrib/elasticsearch/elasticsearch.py
  ddtrace/contrib/elasticsearch/patch.py
  ddtrace/contrib/elasticsearch/transport.py
  tests/contrib/elasticsearch/test.py
  tox.ini
Labels: enhancement, integrations

#712 [docs] Fix broken flask link
  ddtrace/contrib/flask/__init__.py
Labels: docs

#710 [ci] Use small circleci resource class for all jobs
  .circleci/config.yml
Labels: dev/testing

#702 [core] Add global tracer tags
  ddtrace/bootstrap/sitecustomize.py
  tests/commands/ddtrace_run_global_tags.py
  tests/commands/test_runner.py
Labels: core, enhancement

#664 [dbapi] Trace db fetch and session methods
  .circleci/config.yml
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/django/db.py
  tests/contrib/dbapi/__init__.py
  tests/contrib/dbapi/test_unit.py
  tests/contrib/django/test_cache_views.py
  tests/contrib/django/test_connection.py
  tests/contrib/django/test_middleware.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysql.py
  tests/contrib/psycopg/test_psycopg.py
  tests/contrib/pymysql/test_pymysql.py
  tests/contrib/sqlite3/test_sqlite3.py
  tox.ini
Labels: core

#713 [requests] Add another split_by_domain test
  tests/contrib/requests/test_requests.py
Labels: enhancement

#716 [redis] add support for redis 3.0.0
  .circleci/config.yml
  ddtrace/contrib/redis/patch.py
  docker-compose.yml
  tests/commands/ddtrace_run_integration.py
  tox.ini
Labels: enhancement, integrations

#718 [tests] Add rough patch test runner
  .circleci/config.yml
  tests/contrib/__init__.py
  tests/contrib/gevent/test_patch.py
  tests/contrib/requests/test_patch.py
  tests/contrib/test_patch_runner.py
  tox.ini
Labels: dev/testing

#722 [tests] fix broken redis check
  tests/commands/ddtrace_run_integration.py
Labels: bug, dev/testing

#689 [tests] add base test case classes and rewrite tracer tests
  tests/__init__.py
  tests/base.py
  tests/test_tracer.py
  tests/utils/__init__.py
  tests/utils/span.py
  tests/utils/tracer.py
Labels: dev/testing

#725 [tests] pin version of redis-py-cluster for 'tox -e wait'
  tox.ini
Labels: dev/testing

#537 [cassandra] Support unicode batched queries
  ddtrace/contrib/cassandra/session.py
  ddtrace/ext/cassandra.py
  tests/contrib/cassandra/test.py
  tests/test_compat.py
Labels: enhancement, integrations

#727 [tests] Pin pytest to 3.x.x and redis to 2.10.x for rediscluster
  .circleci/config.yml
  tox.ini
Labels: dev/testing

#726 [django] Use a set instead of list for cache_backends to avoid duplicates
  ddtrace/contrib/django/cache.py
Labels: community, enhancement

#729 [circleci] add missing resource class declarations
  .circleci/config.yml
Labels: dev/tooling

#728 Add long_description
  setup.py
Labels: docs

#734 [docs] add Flask configuration documentation
  ddtrace/contrib/flask/__init__.py
Labels: docs

#721 [tests] Add patch mixin and base test case
  tests/contrib/__init__.py
  tests/contrib/patch.py
Labels: dev/testing

#720 [tests] Add Subprocess TestCase
  tests/subprocesstest.py
Labels: dev/testing, enhancement

#737 [elasticsearch] add alias for default _perform_request
  ddtrace/contrib/elasticsearch/patch.py
Labels: bug, integrations

#741 [dbapi] return values for commit/rollback
  ddtrace/contrib/dbapi/__init__.py
Labels: enhancement, integrations

#743 [tests] upgrade flake8 to 3.5.0
  ddtrace/contrib/cassandra/session.py
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/contrib/pylons/middleware.py
  tox.ini
Labels: dev/testing

#735 [core] Make writing services a no-op
  ddtrace/writer.py
  tests/test_integration.py
Labels: core

#736 [psycopg2] Fix composable query tracing
  ddtrace/contrib/aiopg/connection.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/psycopg/patch.py
  tests/contrib/psycopg/test_psycopg.py
  tox.ini
Labels: bug, integrations

#749 [psycopg2] fix linting issues
  ddtrace/contrib/psycopg/patch.py
Labels: dev/testing

#742 [config] make IntegrationConfig an AttrDict
  ddtrace/settings.py
  ddtrace/utils/attrdict.py
  tests/contrib/vertica/fixtures.py
  tests/contrib/vertica/test_vertica.py
  tests/contrib/vertica/utils.py
  tests/unit/test_settings.py
Labels: core

#685 [molten] Add molten support
  .circleci/config.yml
  .gitignore
  ddtrace/contrib/molten/__init__.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/molten/wrappers.py
  ddtrace/monkey.py
  ddtrace/pin.py
  docs/index.rst
  docs/web_integrations.rst
  tests/contrib/molten/__init__.py
  tests/contrib/molten/test_molten.py
  tests/contrib/molten/test_molten_di.py
  tox.ini
Labels: do-not-merge/WIP, enhancement, integrations
