Repository DataDog/dd-trace-py, pull requests merged in 2018-02, with the labels that each got.

#417 [core] disable msgpack tests after the package split
  ddtrace/encoding.py
  tests/test_integration.py
Labels: core

#376 Add MySQLdb integration
  .circleci/config.yml
  ddtrace/contrib/mysql/__init__.py
  ddtrace/contrib/mysqldb/__init__.py
  ddtrace/contrib/mysqldb/patch.py
  ddtrace/monkey.py
  docs/index.rst
  tests/contrib/mysqldb/__init__.py
  tests/contrib/mysqldb/test_mysql.py
  tox.ini
Labels: integrations

#419 [pylons] rewrite Pylons test suite
  .gitignore
  tests/contrib/pylons/app/__init__.py
  tests/contrib/pylons/app/controllers/__init__.py
  tests/contrib/pylons/app/controllers/root.py
  tests/contrib/pylons/app/lib/__init__.py
  tests/contrib/pylons/app/lib/base.py
  tests/contrib/pylons/app/lib/helpers.py
  tests/contrib/pylons/app/router.py
  tests/contrib/pylons/app/web.py
  tests/contrib/pylons/test.ini
  tests/contrib/pylons/test_pylons.py
Labels: dev/testing, integrations

#420 [pylons] add tracing to Pylons render function
  ddtrace/contrib/pylons/compat.py
  ddtrace/contrib/pylons/constants.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/pylons/renderer.py
  tests/contrib/pylons/app/controllers/root.py
  tests/contrib/pylons/app/lib/helpers.py
  tests/contrib/pylons/app/router.py
  tests/contrib/pylons/app/templates/exception.mako
  tests/contrib/pylons/app/templates/template.mako
  tests/contrib/pylons/app/web.py
  tests/contrib/pylons/test.ini
  tests/contrib/pylons/test_pylons.py
Labels: enhancement, integrations

#421 [dbapi] remove `sql.query` tag so that the content is obfuscated in the Agent
  ddtrace/contrib/dbapi/__init__.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysql.py
  tests/contrib/psycopg/test_psycopg.py
  tests/contrib/sqlite3/test_sqlite3.py
Labels: integrations

#415 Django 2.0 compatibility: User.is_authenticated is now a property
  .circleci/config.yml
  ddtrace/contrib/django/compat.py
  ddtrace/contrib/django/middleware.py
  tests/contrib/django/app/settings.py
  tests/contrib/django/compat.py
  tests/contrib/django/test_cache_views.py
  tests/contrib/django/test_middleware.py
  tests/contrib/djangorestframework/app/settings.py
  tox.ini
Labels: enhancement, integrations

#424 [psycopg2] add support for version 2.4
  .circleci/config.yml
  ddtrace/contrib/psycopg/patch.py
  docs/index.rst
  tests/contrib/psycopg/test_psycopg.py
  tox.ini
Labels: integrations

#425 [pylons] add distributed tracing via kwarg and environment variable
  ddtrace/contrib/pylons/__init__.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/pylons/patch.py
  tests/contrib/pylons/test_pylons.py
Labels: integrations

#426 [ddtrace-run] enable Distributed Sampling via environment variable
  ddtrace/bootstrap/sitecustomize.py
  docs/index.rst
  tests/commands/ddtrace_run_priority_sampling.py
  tests/commands/test_runner.py
Labels: core
