Repository DataDog/dd-trace-py, pull requests merged in 2019-05, with the labels that each got.

#928 tests: always skip sdist, use develop mode
  .circleci/config.yml
  tox.ini
Labels: dev/testing

#938 [core] Add config to set hostname tag on trace root span
  ddtrace/constants.py
  ddtrace/context.py
  ddtrace/internal/hostname.py
  ddtrace/settings/config.py
  tests/base/__init__.py
  tests/internal/test_hostname.py
  tests/test_context.py
Labels: core

#875 Add contributing guidelines
  README.md
  docs/contributing.rst
  docs/index.rst
Labels: community
