Repository DataDog/dd-trace-py, pull requests merged in 2019-07, with the labels that each got.

#982 Fix a typo in AIOTracedCursor docstring
  ddtrace/contrib/aiopg/connection.py
  ddtrace/contrib/aiopg/patch.py
  ddtrace/contrib/psycopg/patch.py
Labels: bug, community

#984 Refs #983 - Make AIOTracedCursor an async generator
  ddtrace/contrib/aiopg/connection.py
  tests/contrib/aiopg/py37/__init__.py
  tests/contrib/aiopg/py37/test.py
Labels: bug, integrations

#985 [pymongo] Support newer msg requests
  ddtrace/contrib/pymongo/parse.py
  tox.ini
Labels: enhancement, integrations

#989 Upload wheels on release
  Rakefile
Labels: dev/tooling

#993 writer: fix deprecated log.warn use
  ddtrace/api.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/internal/runtime/collector.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/utils/hook.py
  ddtrace/writer.py
  tests/internal/runtime/test_metrics.py
  tests/test_hook.py
Labels: community, enhancement

#994 Use Python 3 for test_build job
  .circleci/config.yml
Labels: dev/testing

#1002 Improve Django docs
  ddtrace/contrib/django/__init__.py
Labels: community, docs

#997 [django] Move existing django tests
  tests/contrib/django_old/__init__.py
  tests/contrib/django_old/app/__init__.py
  tests/contrib/django_old/app/middlewares.py
  tests/contrib/django_old/app/settings.py
  tests/contrib/django_old/app/settings_untraced.py
  tests/contrib/django_old/app/templates/cached_list.html
  tests/contrib/django_old/app/templates/users_list.html
  tests/contrib/django_old/app/views.py
  tests/contrib/django_old/compat.py
  tests/contrib/django_old/conftest.py
  tests/contrib/django_old/runtests.py
  tests/contrib/django_old/test_autopatching.py
  tests/contrib/django_old/test_cache_backends.py
  tests/contrib/django_old/test_cache_client.py
  tests/contrib/django_old/test_cache_views.py
  tests/contrib/django_old/test_cache_wrapper.py
  tests/contrib/django_old/test_connection.py
  tests/contrib/django_old/test_instrumentation.py
  tests/contrib/django_old/test_middleware.py
  tests/contrib/django_old/test_templates.py
  tests/contrib/django_old/test_tracing_disabled.py
  tests/contrib/django_old/test_utils.py
  tests/contrib/django_old/utils.py
  tests/contrib/djangorestframework_old/__init__.py
  tests/contrib/djangorestframework_old/app/__init__.py
  tests/contrib/djangorestframework_old/app/exceptions.py
  tests/contrib/djangorestframework_old/app/settings.py
  tests/contrib/djangorestframework_old/app/views.py
  tests/contrib/djangorestframework_old/conftest.py
  tests/contrib/djangorestframework_old/test_djangorestframework.py
  tox.ini
Labels: dev/testing, integrations

#998 [django] Remove autopatching
  ddtrace/contrib/django/__init__.py
  ddtrace/contrib/django/patch.py
  tox.ini
Labels: dev/testing, integrations

#1006 [dev] Map .git into ddtest for setuptools_scm
  docker-compose.yml
Labels: dev/tooling
