Repository DataDog/dd-trace-py, pull requests merged in 2019-08, with the labels that each got.

#1010 [django] Update how we get the http.url
  ddtrace/contrib/django/middleware.py
  ddtrace/contrib/django/utils.py
Labels: bug, integrations

#1008 [tests] Adding in helpful default packages
  tox.ini
Labels: dev/tooling

#1004 [pylibmc] Fix client when tracer is disabled
  ddtrace/contrib/pylibmc/client.py
  tests/contrib/pylibmc/test.py
Labels: bug

#1009 [django] Only set sample rate if rate is set
  ddtrace/contrib/django/middleware.py
  tests/contrib/django/test_middleware.py
Labels: bug, integrations

#1007 [core] Parse and send container id with payloads to the agent
  ddtrace/api.py
  ddtrace/internal/runtime/container.py
  tests/internal/runtime/test_container.py
  tests/internal/runtime/utils.py
  tests/test_api.py
  tests/test_integration.py
Labels: core

#1017 documentation bugfix
  ddtrace/contrib/tornado/__init__.py
Labels: bug, docs

#1023 [pymongo] Add support for PyMongo 3.9
  ddtrace/contrib/pymongo/client.py
  tox.ini
Labels: integrations

#995 [django] Setup pytest-django
  tests/contrib/django/conftest.py
  tests/contrib/djangorestframework/app/settings.py
  tests/contrib/djangorestframework/conftest.py
  tests/contrib/djangorestframework/runtests.py
  tests/contrib/djangorestframework/test_djangorestframework.py
  tox.ini
Labels: dev/testing

#1027 [dev] Allow extra args to scripts/run-tox-scenario
  scripts/run-tox-scenario
Labels: dev/tooling

#1028 [dev] Update span test utils
  tests/utils/span.py
Labels: dev/testing

#1029 [internal] Add generic rate limiter
  ddtrace/internal/rate_limiter.py
  tests/internal/test_rate_limiter.py
Labels: internal

#1022 Create test for empty middleware
  ddtrace/contrib/django/middleware.py
  tests/contrib/django/test_autopatching.py
Labels: bug, community, integrations

#1016 Remove unused circle env vars for release
  .circleci/config.yml
Labels: dev/testing

#1019 Patch DBs in django app config
  ddtrace/contrib/django/apps.py
  ddtrace/contrib/django/patch.py
  tests/contrib/django/test_connection.py
Labels: community
