Repository DataDog/dd-trace-py, pull requests merged in 2019-04, with the labels that each got.

#863 [tests] Enable integration tests in docker-compose environment
  docker-compose.yml
Labels: dev/testing, dev/tooling

#873 [tests] Add support for aiohttp up to 3.5
  .circleci/config.yml
  tests/contrib/aiohttp/app/web.py
  tox.ini
Labels: integrations

#874 Remove confusing testing instructions from README
  README.md
Labels: docs

#877 [aiohttp] Fix race condition in testing
  tests/contrib/aiohttp/test_request_safety.py
Labels: dev/testing

#819 [core] Collect run-time metrics
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/internal/runtime/__init__.py
  ddtrace/internal/runtime/collector.py
  ddtrace/internal/runtime/constants.py
  ddtrace/internal/runtime/metric_collectors.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/internal/runtime/tag_collectors.py
  ddtrace/tracer.py
  ddtrace/utils/runtime.py
  ddtrace/vendor/__init__.py
  ddtrace/vendor/dogstatsd/__init__.py
  ddtrace/vendor/dogstatsd/base.py
  ddtrace/vendor/dogstatsd/compat.py
  ddtrace/vendor/dogstatsd/context.py
  ddtrace/vendor/dogstatsd/context_async.py
  ddtrace/vendor/dogstatsd/route.py
  setup.py
  tests/base/__init__.py
  tests/commands/ddtrace_run_dogstatsd.py
  tests/commands/test_runner.py
  tests/internal/runtime/__init__.py
  tests/internal/runtime/test_metric_collectors.py
  tests/internal/runtime/test_metrics.py
  tests/internal/runtime/test_runtime_metrics.py
  tests/test_tracer.py
  tests/utils/tracer.py
  tox.ini
Labels: core

#848 [core] Vendor msgpack dependency
  .circleci/config.yml
  ddtrace/encoding.py
  ddtrace/vendor/__init__.py
  ddtrace/vendor/msgpack/__init__.py
  ddtrace/vendor/msgpack/_cmsgpack.cpp
  ddtrace/vendor/msgpack/_cmsgpack.pyx
  ddtrace/vendor/msgpack/_packer.pyx
  ddtrace/vendor/msgpack/_unpacker.pyx
  ddtrace/vendor/msgpack/_version.py
  ddtrace/vendor/msgpack/buff_converter.h
  ddtrace/vendor/msgpack/exceptions.py
  ddtrace/vendor/msgpack/fallback.py
  ddtrace/vendor/msgpack/pack.h
  ddtrace/vendor/msgpack/pack_template.h
  ddtrace/vendor/msgpack/sysdep.h
  ddtrace/vendor/msgpack/unpack.h
  ddtrace/vendor/msgpack/unpack_define.h
  ddtrace/vendor/msgpack/unpack_template.h
  docker-compose.yml
  setup.py
  tests/test_encoders.py
  tests/test_integration.py
  tox.ini
Labels: core

#892 Type cast port number to avoid surprise unicode type
  ddtrace/api.py
  tests/test_api.py
Labels: bug, community

#882 [tests] Leverage tox environment listing to simplify CircleCI tox target list
  .circleci/config.yml
  README.md
  docker-compose.yml
  scripts/run-tox-scenario
Labels: dev/tooling

#862 [writer] Enhance Q implementation with a wait based one
  ddtrace/writer.py
  tests/test_integration.py
  tests/test_writer.py
Labels: core, internal

#849 [core] Add Span 'manual.keep' and 'manual.drop' tag support
  ddtrace/span.py
  tests/test_span.py
Labels: core

#901 [opentracer] Fix flaky test based on sleep
  tests/opentracer/test_tracer.py
Labels: dev/testing
