Repository DataDog/dd-trace-py, pull requests merged in 2019-01, with the labels that each got.

#779 [mako] Add Mako integration
  .circleci/config.yml
  ddtrace/contrib/mako/__init__.py
  ddtrace/contrib/mako/constants.py
  ddtrace/contrib/mako/patch.py
  ddtrace/monkey.py
  docs/index.rst
  docs/other_integrations.rst
  tests/contrib/mako/templates/template.html
  tests/contrib/mako/test_mako.py
  tox.ini
Labels: community, integrations

#777 [core] Tracer and logs integration
  .circleci/config.yml
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/logging/__init__.py
  ddtrace/contrib/logging/patch.py
  ddtrace/helpers.py
  ddtrace/monkey.py
  docs/advanced_usage.rst
  tests/commands/ddtrace_run_logs_injection.py
  tests/commands/test_runner.py
  tests/contrib/logging/__init__.py
  tests/contrib/logging/test_logging.py
  tests/test_helpers.py
  tox.ini
Labels: core, enhancement

#790 Merge 0.20-dev
  .circleci/config.yml
  ddtrace/__init__.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/logging/__init__.py
  ddtrace/contrib/logging/patch.py
  ddtrace/contrib/mako/__init__.py
  ddtrace/contrib/mako/constants.py
  ddtrace/contrib/mako/patch.py
  ddtrace/helpers.py
  ddtrace/monkey.py
  docs/advanced_usage.rst
  docs/index.rst
  docs/other_integrations.rst
  tests/commands/ddtrace_run_logs_injection.py
  tests/commands/test_runner.py
  tests/contrib/logging/__init__.py
  tests/contrib/logging/test_logging.py
  tests/contrib/mako/templates/template.html
  tests/contrib/mako/test_mako.py
  tests/test_helpers.py
  tox.ini
Labels: release

#787 [celery] Ensure `celery.run` span is closed when task is retried
  ddtrace/contrib/celery/signals.py
  ddtrace/contrib/celery/utils.py
  tests/contrib/celery/base.py
  tests/contrib/celery/test_utils.py
Labels: bug

#795 0.20.1
  ddtrace/__init__.py
  ddtrace/contrib/celery/signals.py
  ddtrace/contrib/celery/utils.py
  tests/contrib/celery/base.py
  tests/contrib/celery/test_utils.py
Labels: release

#802 [tests] limit grpcio version to >=1.8.0,<1.18.0
  tox.ini
Labels: dev/testing

#800 [core] Call HTTPResponse.read() before HTTPConnection.close()
  ddtrace/api.py
  ddtrace/writer.py
  tests/test_api.py
  tests/test_integration.py
Labels: bug, core

#804 Release 0.20.2
  Rakefile
  ddtrace/__init__.py
  ddtrace/api.py
  ddtrace/writer.py
  tests/test_api.py
  tests/test_integration.py
  tox.ini
Labels: release
