Repository DataDog/dd-trace-py, pull requests merged in 2019-09, with the labels that each got.

#1020 [core] Add new DatadogSampler
  ddtrace/compat.py
  ddtrace/constants.py
  ddtrace/internal/rate_limiter.py
  ddtrace/sampler.py
  ddtrace/tracer.py
  tests/internal/test_rate_limiter.py
  tests/test_sampler.py
Labels: core

#1053 [consul] Use consistent span name
  .gitignore
  ddtrace/contrib/consul/patch.py
  ddtrace/ext/consul.py
  tests/contrib/consul/test.py
Labels: integrations

#988 writer: tag as private, merge worker
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/internal/test_writer.py
  tests/test_integration.py
  tests/utils/tracer.py
Labels: internal
