Repository DataDog/dd-trace-py, pull requests merged in 2019-03, with the labels that each got.

#822 [internal] Add rate limited logger
  .circleci/config.yml
  ddtrace/api.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/commands/ddtrace_run.py
  ddtrace/context.py
  ddtrace/contrib/cassandra/session.py
  ddtrace/contrib/celery/signals.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/django/apps.py
  ddtrace/contrib/django/cache.py
  ddtrace/contrib/django/conf.py
  ddtrace/contrib/django/db.py
  ddtrace/contrib/django/middleware.py
  ddtrace/contrib/django/templates.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/pylibmc/client.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/pymemcache/client.py
  ddtrace/contrib/pymongo/client.py
  ddtrace/contrib/pymongo/parse.py
  ddtrace/contrib/pyramid/trace.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/vertica/patch.py
  ddtrace/encoding.py
  ddtrace/http/headers.py
  ddtrace/internal/README.md
  ddtrace/internal/__init__.py
  ddtrace/internal/logger.py
  ddtrace/monkey.py
  ddtrace/opentracer/propagation/http.py
  ddtrace/opentracer/tracer.py
  ddtrace/pin.py
  ddtrace/propagation/http.py
  ddtrace/sampler.py
  ddtrace/settings/config.py
  ddtrace/settings/hooks.py
  ddtrace/settings/http.py
  ddtrace/span.py
  ddtrace/tracer.py
  ddtrace/utils/hook.py
  ddtrace/writer.py
  tests/internal/__init__.py
  tests/internal/test_logger.py
  tox.ini
Labels: internal

#836 [core] fix wrapt wrappers sources
  setup.py
Labels: bug, core

#839 Fix for broken celery tests
  .circleci/config.yml
  tox.ini
Labels: community, dev/testing

#834 [core] Add Payload class helper
  ddtrace/api.py
  ddtrace/encoding.py
  ddtrace/payload.py
  tests/test_encoders.py
  tests/test_payload.py
Labels: core

#847 [dev/tooling] Use custom mkwheelhouse script to build/upload sdist packages
  .circleci/config.yml
  Rakefile
  scripts/mkwheelhouse
Labels: dev/tooling

#852 [core] Guard against when there is no current call context
  ddtrace/helpers.py
  ddtrace/tracer.py
  tests/test_helpers.py
  tests/test_tracer.py
Labels: bug, core

#854 [tests] Fix requests gevent tests
  .circleci/config.yml
  tests/contrib/requests_gevent/test_requests_gevent.py
Labels: dev/testing

#855 [tests] Use spotify cassandra image for tests
  .circleci/config.yml
  docker-compose.yml
Labels: dev/testing

#853 Add script to build wheels
  .circleci/config.yml
  Rakefile
  scripts/build-dist
  scripts/mkwheelhouse
Labels: dev/tooling
