Repository DataDog/dd-trace-py, pull requests merged in 2020-03, with the labels that each got.

#1276 Log exporter support
  ddtrace/encoding.py
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/internal/test_writer.py
  tests/test_encoders.py
Labels: do-not-merge/WIP

#1288 Fix tiny typo in Issue template
  .github/ISSUE_TEMPLATE.md
Labels: docs

#1294 aiobotocore: prioritize DD_SERVICE
  ddtrace/contrib/aiobotocore/patch.py
  tests/contrib/aiobotocore/test.py
Labels: integrations

#1296 aiohttp: prioritize DD_SERVICE
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/aiohttp/patch.py
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/aiohttp/test_request.py
  tests/contrib/aiohttp/test_request_safety.py
  tests/contrib/aiohttp/test_templates.py
  tests/contrib/aiohttp/utils.py
Labels: integrations

#1297 algoliasearch: prioritize DD_SERVICE
  ddtrace/contrib/algoliasearch/patch.py
  tests/contrib/algoliasearch/test.py
Labels: integrations

#1301 fix(profiling): fix Lock issue when stored in a class attribute
  ddtrace/profiling/collector/threading.py
  tests/profiling/collector/test_threading.py
Labels: bug

#1302 Update _dd.measured support
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/contrib/httplib/patch.py
  tests/base/__init__.py
  tests/contrib/grpc/test_grpc.py
  tests/contrib/httplib/test_httplib.py
  tests/utils/__init__.py
Labels: integrations

#1298 integrations: DD_SERVICE
  ddtrace/commands/ddtrace_run.py
  ddtrace/contrib/aiobotocore/patch.py
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/aiohttp/patch.py
  ddtrace/contrib/algoliasearch/patch.py
  ddtrace/contrib/bottle/patch.py
  ddtrace/contrib/bottle/trace.py
  ddtrace/contrib/celery/constants.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/falcon/patch.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask_cache/tracers.py
  ddtrace/contrib/grpc/patch.py
  ddtrace/contrib/kombu/patch.py
  ddtrace/contrib/mako/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/pylons/patch.py
  ddtrace/contrib/pyramid/patch.py
  ddtrace/contrib/tornado/application.py
  ddtrace/settings/config.py
  ddtrace/utils/deprecation.py
  tests/contrib/bottle/test.py
  tests/contrib/flask_cache/test.py
  tests/contrib/jinja2/test_jinja2.py
  tests/contrib/kombu/test.py
  tests/contrib/mako/test_mako.py
  tests/contrib/molten/test_molten.py
  tests/test_tracer.py
Labels: integrations
