Repository DataDog/dd-trace-py, pull requests merged in 2020-12, with the labels that each got.

#1814 tests: add async_mode flag to snapshot
  tests/__init__.py
Labels: changelog/no-changelog

#1823 sitecustomize: remove imp usage for python 3.3+
  ddtrace/bootstrap/sitecustomize.py
  tests/commands/test_runner.py
Labels: changelog/no-changelog

#1827 build(profiling): enable debug on != Linux and add -O0
  setup.py
Labels: changelog/no-changelog

#1832 feat(profiling): reduce memalloc default sampling rate to 64 events/s
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/profiler.py
Labels: changelog/no-changelog

#1811 Add span._set_str_tag
  ddtrace/contrib/trace_utils.py
  ddtrace/span.py
  ddtrace/tracer.py
  tests/tracer/test_encoders.py
  tests/tracer/test_span.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#1836 refactor(profiling/memalloc): reduce max number of events in memory to 65535
  ddtrace/profiling/collector/_memalloc.c
  tests/profiling/collector/test_memalloc.py
Labels: changelog/no-changelog

#1837 format ddtrace module
  ddtrace/_worker.py
  ddtrace/api.py
  ddtrace/constants.py
  ddtrace/context.py
  ddtrace/encoding.py
  ddtrace/filters.py
  ddtrace/payload.py
  ddtrace/pin.py
  ddtrace/provider.py
  ddtrace/sampler.py
  ddtrace/tracer.py
  ddtrace/util.py
  pyproject.toml
Labels: changelog/no-changelog

#1840 refactor(profiling): split memalloc in 2 parts
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_tb.c
  ddtrace/profiling/collector/_memalloc_tb.h
  ddtrace/profiling/collector/_pymacro.h
  setup.py
Labels: changelog/no-changelog

#1839 fix: don't spawn a _MainThread if in main thread
  ddtrace/compat.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#1842 chore(profiling/memalloc): remove unused number_one variable
  ddtrace/profiling/collector/_memalloc_tb.c
Labels: changelog/no-changelog

#1797 Add health metrics back
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/__init__.py
  tests/integration/test_integration.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#1802 docs: updates to quickstart
  docs/installation_quickstart.rst
Labels: changelog/no-changelog, docs

#1835 span: add ignored exceptions
  ddtrace/span.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#1845 Specify a release version pattern for reno
  releasenotes/config.yaml
Labels: changelog/no-changelog

#1844 Reference old changelog in new release notes
  docs/release_notes.rst
Labels: changelog/no-changelog

#1843 Add final entry to changelog
  CHANGELOG.md
Labels: changelog/no-changelog

#1800 docs: add troubleshooting section
  docs/index.rst
  docs/troubleshooting.rst
Labels: changelog/no-changelog

#1851 fix(aiohttp): format aiohttp & tests with black
  ddtrace/contrib/aiohttp/__init__.py
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/aiohttp/patch.py
  ddtrace/contrib/aiohttp/template.py
  pyproject.toml
  tests/contrib/aiohttp/app/web.py
Labels: changelog/no-changelog

#1852 fix(bottle): reformat bottle & tests with black
  ddtrace/contrib/bottle/__init__.py
  ddtrace/contrib/bottle/patch.py
  ddtrace/contrib/bottle/trace.py
  pyproject.toml
  tests/contrib/bottle/test.py
  tests/contrib/bottle/test_autopatch.py
  tests/contrib/bottle/test_distributed.py
Labels: changelog/no-changelog

#1853 fix(falcon): reformat falcon & tests with black
  ddtrace/contrib/falcon/__init__.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/falcon/patch.py
  pyproject.toml
  tests/contrib/falcon/app/app.py
  tests/contrib/falcon/app/resources.py
  tests/contrib/falcon/test_autopatch.py
  tests/contrib/falcon/test_distributed_tracing.py
  tests/contrib/falcon/test_middleware.py
  tests/contrib/falcon/test_suite.py
Labels: changelog/no-changelog

#1854 fix(flask): reformat flask & tests using black
  ddtrace/contrib/flask/__init__.py
  ddtrace/contrib/flask/helpers.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask/wrappers.py
  pyproject.toml
  tests/contrib/flask/test_blueprint.py
  tests/contrib/flask/test_errorhandler.py
  tests/contrib/flask/test_flask_helpers.py
  tests/contrib/flask/test_hooks.py
  tests/contrib/flask/test_idempotency.py
  tests/contrib/flask/test_middleware.py
  tests/contrib/flask/test_request.py
  tests/contrib/flask/test_signals.py
  tests/contrib/flask/test_static.py
  tests/contrib/flask/test_template.py
  tests/contrib/flask/test_views.py
  tests/contrib/flask/web.py
Labels: changelog/no-changelog

#1855 fix(httplib): reformat httplib & tests with black
  ddtrace/contrib/httplib/__init__.py
  ddtrace/contrib/httplib/patch.py
  pyproject.toml
  tests/contrib/httplib/test_httplib.py
  tests/contrib/httplib/test_httplib_distributed.py
Labels: changelog/no-changelog

#1856 fix(molten): reformat molten & tests with black
  ddtrace/contrib/molten/wrappers.py
  pyproject.toml
  tests/contrib/molten/test_molten.py
  tests/contrib/molten/test_molten_di.py
Labels: changelog/no-changelog

#1857 fix(pyramid): reformat pyramid tests with black (pyramid already formatted with black)
  pyproject.toml
  tests/contrib/pyramid/__init__.py
  tests/contrib/pyramid/app/web.py
  tests/contrib/pyramid/test_pyramid.py
  tests/contrib/pyramid/test_pyramid_autopatch.py
Labels: changelog/no-changelog

#1858 fix(requests): reformat requests & tests with black
  ddtrace/contrib/requests/__init__.py
  ddtrace/contrib/requests/constants.py
  ddtrace/contrib/requests/legacy.py
  ddtrace/contrib/requests/patch.py
  ddtrace/contrib/requests/session.py
  pyproject.toml
  tests/contrib/requests/test_requests.py
  tests/contrib/requests/test_requests_distributed.py
Labels: changelog/no-changelog

#1850 refactor(profiling/memalloc): track allocated ptr
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_tb.c
  ddtrace/profiling/collector/_memalloc_tb.h
Labels: changelog/no-changelog

#1859 tests: force env values in CI tests
  tests/tracer/test_ext.py
Labels: changelog/no-changelog, dev/testing

#1861 run boto(core) tests with riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#1828 ci: upgrade riotfile to 0.3
  .circleci/config.yml
  riotfile.py
  scripts/ddtest
Labels: changelog/no-changelog

#1863 ci: add helper to select venv 'pys'
  riotfile.py
Labels: changelog/no-changelog

#1865 ci: test with multiple agents
  .circleci/config.yml
  docker-compose.yml
  tests/integration/test_debug.py
  tests/integration/test_integration.py
  tox.ini
Labels: changelog/no-changelog

#1864 ci: remove tox/riot from docker image
  Dockerfile
Labels: changelog/no-changelog

#1873 Fix dependency issues
  tox.ini
Labels: changelog/no-changelog

#1833 http helper phase 2
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/bottle/trace.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/pyramid/trace.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/sanic/patch.py
  ddtrace/contrib/trace_utils.py
  pyproject.toml
  tests/contrib/sanic/test_sanic.py
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog

#1878 Use riot for mongoengine tests
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#1881 ci(pytest): only show deprecation warning once
  tox.ini
Labels: changelog/no-changelog

#1882 ci: run bash by default if no arg passed to ddtest
  scripts/ddtest
Labels: changelog/no-changelog

#1883 v0.45 documentation fixes
  docs/installation_quickstart.rst
  releasenotes/notes/current-span-reset-a860bbbad3acda5c.yaml
  releasenotes/notes/django-request-uri-safe-guards-fdd8bd664374ded1.yaml
  releasenotes/notes/django-view-mro-check-782374fb9c427305.yaml
  releasenotes/notes/fix-aiobotocore-9eeac808a3bf0f63.yaml
  releasenotes/notes/fix-elasticsearch-a3f89a915ccc36c4.yaml
  releasenotes/notes/fix-span-type-web-20122b5c57c50341.yaml
Labels: changelog/no-changelog

#1885 v0.45 documentation fixes
  docs/installation_quickstart.rst
  releasenotes/notes/current-span-reset-a860bbbad3acda5c.yaml
  releasenotes/notes/django-request-uri-safe-guards-fdd8bd664374ded1.yaml
  releasenotes/notes/django-view-mro-check-782374fb9c427305.yaml
  releasenotes/notes/fix-aiobotocore-9eeac808a3bf0f63.yaml
  releasenotes/notes/fix-elasticsearch-a3f89a915ccc36c4.yaml
  releasenotes/notes/fix-span-type-web-20122b5c57c50341.yaml
Labels: changelog/no-changelog

#1875 ext: remove invalid Jenkins job URL
  ddtrace/ext/ci.py
  tests/tracer/fixtures/ci/jenkins.json
Labels: changelog/no-changelog

#1884 tests: fix mysqlconnector dependency string
  tox.ini
Labels: changelog/no-changelog

#1872 Remove coverage as a dependency
  tox.ini
Labels: changelog/no-changelog

#1862 fix(profiling/memalloc): check memalloc_tb_init return code
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_tb.c
Labels: changelog/no-changelog

#1890 test: move internal to tracer
  tests/tracer/test_forksafe.py
Labels: changelog/no-changelog

#1892 Use riot for asgi test suite
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#1888 fix(profiling): use gevent time.sleep when join()ing thread
  ddtrace/profiling/_periodic.py
Labels: changelog/no-changelog

#1781 Writer refactor
  .gitignore
  ddtrace/contrib/django/conf.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/internal/_queue.pyx
  ddtrace/internal/buffer.py
  ddtrace/internal/debug.py
  ddtrace/internal/writer.py
  ddtrace/profiling/profiler.py
  ddtrace/tracer.py
  docker-compose.yml
  setup.py
  tests/__init__.py
  tests/benchmark.py
  tests/commands/ddtrace_run_hostname.py
  tests/contrib/django/test_django_migration.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/tornado/test_config.py
  tests/integration/test_integration.py
  tests/snapshots/tests.integration.test_integration.test_filters.snap
  tests/snapshots/tests.integration.test_integration.test_multiple_traces.snap
  tests/snapshots/tests.integration.test_integration.test_single_trace_single_span.snap
  tests/tracer/test_buffer.py
  tests/tracer/test_queue.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
  tox.ini
Labels: changelog/no-changelog

#1891 refactor(forksafe): hijack threading._after_fork on Python 2
  ddtrace/internal/forksafe.py
Labels: changelog/no-changelog

#1898 Skip mounting individual files in docker-compose
  docker-compose.yml
Labels: changelog/no-changelog

#1900 ci: update riot use for black and flake8
  .circleci/config.yml
  riotfile.py
Labels: changelog/no-changelog

#1899 Store JUnit XML test results from pytest
  .circleci/config.yml
  .gitignore
  scripts/run-tox-scenario
  tox.ini
Labels: changelog/no-changelog

#1901 Coverage ignore couldnt-parse errors
  .coveragerc
Labels: changelog/no-changelog

#1894 Combine/report coverage in CircleCI
  .circleci/config.yml
  .gitignore
Labels: changelog/no-changelog

#1841 refactor(profiling): split traceback_list_t in 2 objects
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_tb.c
  ddtrace/profiling/collector/_memalloc_tb.h
Labels: changelog/no-changelog

#1896 refactor(profiling): remove global periodic thread list
  ddtrace/profiling/_periodic.py
  ddtrace/profiling/collector/_threading.pyx
  ddtrace/profiling/collector/stack.pyx
  tests/profiling/test_periodic.py
Labels: changelog/no-changelog

#1905 test(profiling): fix potential failure in test_collect_truncate with gevent
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog

#1906 test(profiling): increase accuracy of test_collect_thread
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog

#1909 Dynamically set JUnit XML results filename
  conftest.py
  tox.ini
Labels: changelog/no-changelog

#1911 refactor(runtime): remove useless path check for container info
  ddtrace/internal/runtime/container.py
Labels: changelog/no-changelog

#1910 refactor(runtime): rewrite container with attrs
  ddtrace/internal/runtime/container.py
  pyproject.toml
  tests/tracer/runtime/test_container.py
Labels: changelog/no-changelog

#1908 refactor(profiling): allow to compare Profiler objects
  ddtrace/profiling/_service.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/recorder.py
  ddtrace/profiling/scheduler.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog

#1912 test(profiling): fix possible race condition in thread_id test
  tests/profiling/collector/test_memalloc.py
Labels: changelog/no-changelog

#1915 Use Riot to run benchmarks
  .circleci/config.yml
  riotfile.py
  tests/benchmarks/test_encoding.py
  tests/benchmarks/test_span_id.py
  tests/benchmarks/test_tracer.py
  tox.ini
Labels: changelog/no-changelog

#1913 chore(profiling): remove useless path in endpoint template
  ddtrace/profiling/profiler.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog

#1918 refactor(profiling): fix stop() flush argument
  ddtrace/profiling/profiler.py
  ddtrace/profiling/scheduler.py
  tests/commands/test_runner.py
  tests/profiling/simple_program_fork.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog
