Repository DataDog/dd-trace-py, pull requests merged in 2020-05, with the labels that each got.

#1405 algoliasearch: update tests to latest
  tox.ini
Labels: dev/testing

#1406 consul: update tests to latest
  tox.ini
Labels: dev/testing

#1407 molten: update tests to latest
  tox.ini
Labels: dev/testing

#1408 pylons: update tests to latest
  tox.ini
Labels: dev/testing

#1409 dogpile: update tests to latest
  tox.ini
Labels: dev/testing

#1410 django: update tests to latest
  tox.ini
Labels: dev/testing

#1411 mako: update tests to latest
  tox.ini
Labels: dev/testing

#1412 mongo: update tests to latest
  tox.ini
Labels: dev/testing

#1416 dbapi: update tests to latest python versions
  tox.ini
Labels: dev/testing

#1418 grpc: update tests to latest
  tox.ini
Labels: dev/testing

#1417 futures: update tests to latest
  tox.ini
Labels: dev/testing

#1424 mysql: update tests to latest
  tox.ini
Labels: dev/testing

#1422 kombu: update tests to latest
  tox.ini
Labels: dev/testing

#1420 sqlalchemy: update tests to latest
  tox.ini
Labels: dev/testing

#1423 pyramid: update tests to latest
  tox.ini
Labels: dev/testing

#1426 circleci: remove unused busybox
  .circleci/config.yml
Labels: dev/testing

#1434 bottle: update tests to latest
  tox.ini
Labels: dev/testing

#1433 pylibmc: update tests to latest
  tox.ini
Labels: dev/testing

#1421 jinja2: update tests to latest
  tox.ini
Labels: dev/testing

#1432 tornado: update tests to latest
  tox.ini
Labels: dev/testing

#1419 redis: update tests to latest
  tox.ini
Labels: dev/testing

#1043 Store span ids in profiling events
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/profiler.py
  ddtrace/settings/__init__.py
  ddtrace/settings/config.py
  ddtrace/settings/exceptions.py
  ddtrace/settings/http.py
  ddtrace/settings/integration.py
  ddtrace/tracer.py
  pyproject.toml
  tests/profiling/collector/test_stack.py
  tests/test_tracer.py
Labels: core, enhancement

#1450 chore: add _rand.c to gitignore
  .gitignore
Labels: dev/tooling

#1394 feat(opentracing): support for tracer interleaving
  ddtrace/opentracer/tracer.py
  ddtrace/opentracer/utils.py
  tests/opentracer/test_tracer.py
Labels: opentracer
