Repository DataDog/dd-trace-py, pull requests merged in 2020-11, with the labels that each got.

#1763 ci: fix deploy_master
  .circleci/config.yml
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog

#1761 readthedocs: update python version, don't fail on warning
  .readthedocs.yml
Labels: changelog/no-changelog

#1765 fix(docs): move VersionTagFilter to docs/conf.py
  docs/conf.py
  docs/ext/filters.py
Labels: changelog/no-changelog

#1751 update docs for TwL
  ddtrace/contrib/aiohttp/__init__.py
  ddtrace/contrib/asgi/__init__.py
  ddtrace/contrib/django/__init__.py
  ddtrace/contrib/falcon/__init__.py
  ddtrace/contrib/flask/__init__.py
  ddtrace/contrib/molten/__init__.py
  ddtrace/contrib/pyramid/__init__.py
  ddtrace/contrib/requests/__init__.py
  ddtrace/contrib/sanic/__init__.py
  ddtrace/contrib/tornado/__init__.py
  ddtrace/sampler.py
  docs/advanced_usage.rst
  docs/configuration.rst
Labels: changelog/no-changelog

#1770 ci: parallelism for celery
  .circleci/config.yml
  scripts/run-tox-scenario
Labels: changelog/no-changelog

#1772 ci: build base venvs in parallel
  .circleci/config.yml
Labels: changelog/no-changelog

#1771 ci: use riot for pymongo tests
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#1773 ci: enable parallelism for all integration jobs
  .circleci/config.yml
  scripts/ddtest
  scripts/run-tox-scenario
Labels: changelog/no-changelog

#1775 ci: don't require passing tests for dev deploys
  .circleci/config.yml
Labels: changelog/no-changelog

#1774 ci: remove build wheels job from circleci
  .circleci/config.yml
Labels: changelog/no-changelog

#1776 ci: bump profiling parallelism to 6
  .circleci/config.yml
Labels: changelog/no-changelog

#1778 tests: run snapshots in parallel mode
  tests/__init__.py
Labels: changelog/no-changelog

#1755 feat(starlette): trace starlette implementation of sqlalchemy
  .circleci/config.yml
  tests/contrib/starlette/app.py
  tests/contrib/starlette/test_starlette.py
  tests/snapshots/test_starlette.test_table_query_snapshot.snap
  tox.ini
Labels: changelog/no-changelog

#1760 chore: use riot for django tests
  .circleci/config.yml
  docker-compose.yml
  riotfile.py
  tests/contrib/django/test_django_snapshots.py
  tox.ini
Labels: changelog/no-changelog

#1783 use riot to test pynamodb
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#1784 ci: fix riot tests
  .circleci/config.yml
Labels: changelog/no-changelog

#1787 ci: bump celery parallelism
  .circleci/config.yml
Labels: changelog/no-changelog

#1789 ci: use riot for starlette tests
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#1788 docs: update integration PR template
  .github/PULL_REQUEST_TEMPLATE/integration.md
Labels: changelog/no-changelog, docs

#1790 docs: fix psycopg typo
  ddtrace/contrib/psycopg/__init__.py
Labels: changelog/no-changelog, docs

#1786 ci: use riot to run requests tests; delete unnecessary test suites
  .circleci/config.yml
  riotfile.py
  tests/contrib/requests_gevent/__init__.py
  tests/contrib/requests_gevent/run_test.py
  tests/contrib/requests_gevent/test_requests_gevent.py
  tox.ini
Labels: changelog/no-changelog

#1741 feat: pytest integration
  .circleci/config.yml
  conftest.py
  ddtrace/constants.py
  ddtrace/contrib/pytest/__init__.py
  ddtrace/contrib/pytest/constants.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/ext/__init__.py
  ddtrace/ext/ci.py
  ddtrace/ext/git.py
  ddtrace/ext/test.py
  docs/index.rst
  docs/integrations.rst
  docs/spelling_wordlist.txt
  releasenotes/notes/pytest-d174e595f0c8abd0.yaml
  setup.py
  tests/contrib/pytest/__init__.py
  tests/contrib/pytest/test_pytest.py
  tests/tracer/fixtures/ci/appveyor.json
  tests/tracer/fixtures/ci/azurepipelines.json
  tests/tracer/fixtures/ci/bitbucket.json
  tests/tracer/fixtures/ci/build_kite.json
  tests/tracer/fixtures/ci/circle_ci.json
  tests/tracer/fixtures/ci/github_actions.json
  tests/tracer/fixtures/ci/gitlab.json
  tests/tracer/fixtures/ci/jenkins.json
  tests/tracer/fixtures/ci/travis.json
  tests/tracer/test_ext.py
  tox.ini
Labels: integrations

#1804 core: set tags directly with str values
  ddtrace/context.py
  ddtrace/span.py
  ddtrace/tracer.py
Labels: changelog/no-changelog

#1809 fix(profiling): allow to build on Windows and Python 3.9
  .github/workflows/build_deploy.yml
  ddtrace/profiling/collector/_memalloc.c
Labels: changelog/no-changelog

#1793 update dogstatsd
  ddtrace/vendor/__init__.py
  ddtrace/vendor/dogstatsd/__init__.py
  ddtrace/vendor/dogstatsd/base.py
  ddtrace/vendor/dogstatsd/compat.py
  ddtrace/vendor/dogstatsd/context.py
  ddtrace/vendor/dogstatsd/context_async.py
  ddtrace/vendor/dogstatsd/format.py
  ddtrace/vendor/dogstatsd/route.py
  pyproject.toml
  tests/tracer/runtime/test_container.py
  tests/tracer/runtime/test_metric_collectors.py
  tests/tracer/runtime/test_metrics.py
  tests/tracer/runtime/test_runtime_metrics.py
  tests/tracer/runtime/utils.py
Labels: changelog/no-changelog

#1764 ci: add coverage job
  .circleci/config.yml
  .coveragerc
  riotfile.py
  tox.ini
Labels: changelog/no-changelog, dev/tooling

#1795 feat: http helper function
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/bottle/trace.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/pyramid/__init__.py
  ddtrace/contrib/pyramid/constants.py
  ddtrace/contrib/pyramid/patch.py
  ddtrace/contrib/pyramid/trace.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/sanic/patch.py
  ddtrace/contrib/trace_utils.py
  pyproject.toml
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog

#1824 [Misc] Documentation fix: env var starlette distributed tracing
  ddtrace/contrib/starlette/__init__.py
Labels: changelog/no-changelog

#1825 Fix flask documentation
  docs/index.rst
Labels: changelog/no-changelog

#1826 ci: pin riot version
  .circleci/config.yml
Labels: changelog/no-changelog

#1829 fix(ci): pin riot
  .circleci/config.yml
Labels: changelog/no-changelog

#1831 refactor(profiling): remove unused incref argument
  ddtrace/profiling/collector/_memalloc.c
Labels: changelog/no-changelog

#1801 docs: fix configuration.rst typo
  docs/configuration.rst
Labels: changelog/no-changelog

#1820 fix: Add span types to integrations that don't have them
  ddtrace/contrib/algoliasearch/__init__.py
  ddtrace/contrib/algoliasearch/patch.py
  ddtrace/contrib/consul/__init__.py
  ddtrace/contrib/consul/patch.py
  ddtrace/contrib/dogpile_cache/__init__.py
  ddtrace/contrib/dogpile_cache/lock.py
  ddtrace/contrib/dogpile_cache/patch.py
  ddtrace/contrib/dogpile_cache/region.py
  ddtrace/contrib/mongoengine/__init__.py
  ddtrace/contrib/mongoengine/patch.py
  ddtrace/contrib/mongoengine/trace.py
  ddtrace/contrib/mysql/__init__.py
  ddtrace/contrib/mysql/patch.py
  ddtrace/contrib/mysql/tracers.py
  ddtrace/contrib/mysqldb/__init__.py
  ddtrace/contrib/mysqldb/patch.py
  ddtrace/contrib/pymysql/__init__.py
  ddtrace/contrib/pymysql/patch.py
  ddtrace/contrib/pymysql/tracers.py
  ddtrace/contrib/sqlite3/__init__.py
  ddtrace/contrib/sqlite3/connection.py
  ddtrace/contrib/sqlite3/patch.py
  ddtrace/ext/consul.py
  pyproject.toml
  tests/contrib/algoliasearch/test.py
  tests/contrib/consul/test.py
  tests/contrib/dogpile_cache/test_tracing.py
  tests/contrib/mongoengine/test.py
  tests/contrib/mongoengine/test_backwards.py
  tests/contrib/mysql/test_backwards_compatibility.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysqldb.py
  tests/contrib/pymysql/test_backwards_compatibility.py
  tests/contrib/pymysql/test_pymysql.py
  tests/contrib/sqlite3/test_sqlite3.py
Labels: changelog/no-changelog
