Repository DataDog/dd-trace-py, pull requests merged in 2021-07, with the labels that each got.

#2605 fix(gevent): don't forget to call activate hooks on span activation
  ddtrace/contrib/gevent/provider.py
  tests/contrib/gevent/test_provider.py
Labels: changelog/no-changelog

#2608 chore(docs): fix formatting in pynamodb docs
  ddtrace/contrib/pynamodb/__init__.py
Labels: changelog/no-changelog

#2609 Add token override to snapshot decorator
  tests/utils.py
Labels: changelog/no-changelog

#2576 Logs for partial flushing
  ddtrace/internal/debug.py
  ddtrace/internal/processor/trace.py
  tests/integration/test_debug.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#2624 chore(rediscluster): format with black
  ddtrace/contrib/rediscluster/__init__.py
  ddtrace/contrib/rediscluster/patch.py
  pyproject.toml
  tests/contrib/rediscluster/test.py
Labels: changelog/no-changelog

#2616 chore(jinja2): format with black
  ddtrace/contrib/jinja2/__init__.py
  ddtrace/contrib/jinja2/constants.py
  ddtrace/contrib/jinja2/patch.py
  pyproject.toml
  tests/contrib/jinja2/test_jinja2.py
Labels: changelog/no-changelog

#2606 Added `ci.workspace_path` from git executable, not just CI env vars
  ddtrace/contrib/pytest/plugin.py
  ddtrace/ext/ci.py
  ddtrace/ext/git.py
  tests/tracer/test_ext.py
Labels: changelog/no-changelog

#2617 chore(tests): fix silent errors
  tests/tracer/test_ext.py
  tests/tracer/test_sampler.py
Labels: changelog/no-changelog

#2628 fix(docs): use gunicorn post_worker_init hook
  docs/advanced_usage.rst
Labels: changelog/no-changelog

#2623 chore(pylibmc): format with black
  ddtrace/contrib/pylibmc/__init__.py
  ddtrace/contrib/pylibmc/client.py
  ddtrace/contrib/pylibmc/patch.py
  tests/contrib/pylibmc/test.py
Labels: changelog/no-changelog

#2622 Chore(aiopg): format with black
  ddtrace/contrib/aiopg/__init__.py
  ddtrace/contrib/aiopg/connection.py
  ddtrace/contrib/aiopg/patch.py
  pyproject.toml
  tests/contrib/aiopg/py35/test.py
  tests/contrib/aiopg/py37/test.py
  tests/contrib/aiopg/test.py
Labels: changelog/no-changelog

#2597 perf(flask): small enhancements
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/flask/patch.py
Labels: changelog/no-changelog

#2627 Remove falcon autopatch test cases
  riotfile.py
  tests/contrib/falcon/test_autopatch.py
Labels: changelog/no-changelog

#2629 chore(perf): add sample scenario and docs
  benchmarks/README.rst
  benchmarks/base.Dockerfile
  benchmarks/common/benchmark
  benchmarks/common/entrypoint
  benchmarks/sample/meta.yaml
  benchmarks/sample/requirements.txt
Labels: changelog/no-changelog

#2626 chore(boto, contrib/config.py): Remove from black excludes
  ddtrace/contrib/boto/patch.py
  pyproject.toml
  tests/contrib/config.py
Labels: changelog/no-changelog

#2631 Add startup scenario
  benchmarks/startup/meta.yaml
  benchmarks/startup/requirements.txt
  benchmarks/startup/run.py
Labels: changelog/no-changelog

#2422 refactor(writer): move to a buffered encoder
  ddtrace/internal/_encoding.pyi
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/buffer.py
  ddtrace/internal/encoding.py
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/benchmarks/test_encoding.py
  tests/integration/test_integration.py
  tests/tracer/test_buffer.py
  tests/tracer/test_encoders.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog

#2638 Update CI provider env vars for circleci, jenkins
  ddtrace/ext/ci.py
  tests/tracer/fixtures/ci/circleci.json
  tests/tracer/fixtures/ci/jenkins.json
Labels: changelog/no-changelog

#2642 Remove unreferenced elasticsearch image
  .circleci/config.yml
Labels: changelog/no-changelog

#2647 Improve linting, formatting riot commands
  pyproject.toml
  riotfile.py
Labels: changelog/no-changelog

#2644 Add notice for gevent in docs
  ddtrace/contrib/gevent/__init__.py
  docs/installation_quickstart.rst
Labels: changelog/no-changelog

#2507 Added dd_origin tagging on every span in trace
  .dd-ci/ci-app-spec.json
  ddtrace/contrib/pytest/plugin.py
  ddtrace/ext/ci.py
  ddtrace/internal/_encoding.pyx
  riotfile.py
  tests/benchmarks/test_encoding.py
  tests/contrib/pytest/test_pytest.py
  tests/tracer/test_ci.py
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog

#2632 chore[docs]: Tornado 5/6 support for Python 3.7+
  ddtrace/contrib/tornado/__init__.py
Labels: changelog/no-changelog

#2643 Lint/format all Python sources in repo
  benchmarks/django_simple/config/settings/base.py
  benchmarks/django_simple/config/settings/production.py
  benchmarks/django_simple/config/urls.py
  benchmarks/django_simple/config/wsgi.py
  benchmarks/django_simple/ddtrace_django/contrib/sites/migrations/0001_initial.py
  benchmarks/django_simple/ddtrace_django/contrib/sites/migrations/0002_alter_domain_unique.py
  benchmarks/django_simple/ddtrace_django/users/admin.py
  benchmarks/django_simple/ddtrace_django/users/forms.py
  benchmarks/django_simple/ddtrace_django/users/migrations/0001_initial.py
  benchmarks/django_simple/ddtrace_django/users/urls.py
  benchmarks/django_simple/ddtrace_django/users/views.py
  benchmarks/django_simple/manage.py
  benchmarks/startup/run.py
  ddtrace/internal/_rand.pyx
  ddtrace/profiling/exporter/pprof.pyx
  docs/conf.py
  hooks/scripts/run-flake8.sh
  riotfile.py
  scripts/mkwheelhouse
  tox.ini
Labels: changelog/no-changelog

#2653 Use stable branch for Django tests
  .github/workflows/django.yml
Labels: changelog/no-changelog

#2650 Typecheck context equality method
  ddtrace/context.py
  tests/tracer/test_context.py
Labels: changelog/no-changelog

#2657 refactor(django): pull request/response tagging into helpers
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  tests/contrib/django/test_django.py
Labels: changelog/no-changelog

#2584 added mariadb build steps to dev image
  Dockerfile.buster
Labels: changelog/no-changelog

#2655 Mako ci integration test
  .github/workflows/mako.yml
Labels: changelog/no-changelog

#2526 perf(span): make `span_type` a slot attribute
  ddtrace/contrib/pytest/plugin.py
  ddtrace/ext/__init__.py
  ddtrace/profiling/exporter/pprof.pyx
  ddtrace/span.py
  releasenotes/notes/span-types-enum-5ca7cb35031a199e.yaml
  tests/contrib/pymongo/test.py
  tests/profiling/exporter/test_pprof.py
  tests/tracer/test_encoders.py
Labels: v1.0

#2666 ci(django): enable profiling
  .github/workflows/django.yml
Labels: changelog/no-changelog

#2668 ci: pass DD_TESTING_RAISE correctly for tox-based tests
  .github/workflows/flask.yml
  .github/workflows/mako.yml
Labels: changelog/no-changelog

#2670 Use explicit dependency in riotfile
  riotfile.py
Labels: changelog/no-changelog

#2677 Update mypy, codespell configurations
  benchmarks/django_simple.Dockerfile
  ddtrace/ext/sql.py
  ddtrace/internal/compat.py
  ddtrace/internal/nogevent.py
  ddtrace/internal/uwsgi.py
  ddtrace/profiling/collector/threading.py
  ddtrace/utils/config.py
  mypy.ini
  setup.cfg
Labels: changelog/no-changelog

#2680 ci: pin riot to 0.6
  .circleci/config.yml
  scripts/ddtest
Labels: changelog/no-changelog

#2682 mysql-connector-python 8.0.24 requires Python 3.6
  riotfile.py
Labels: changelog/no-changelog

#2652 Factorize BufferedEncoder
  ddtrace/internal/_encoding.pyi
  ddtrace/internal/_encoding.pyx
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog

#2665 Remove deprecated configs from tests and documentation
  docs/advanced_usage.rst
  tests/commands/test_runner.py
  tests/integration/test_debug.py
  tests/utils.py
Labels: changelog/no-changelog

#2646 feat(perf): add encoder scenario
  benchmarks/base.Dockerfile
  benchmarks/encoder/benchmark
  benchmarks/encoder/entrypoint
  benchmarks/encoder/requirements.txt
  benchmarks/encoder/scenario.py
Labels: changelog/no-changelog

#2681 ci: enable profiling in framework testing jobs
  .github/workflows/bottle.yml
  .github/workflows/fastapi.yml
  .github/workflows/flask.yml
  .github/workflows/mako.yml
  .github/workflows/starlette.yml
Labels: changelog/no-changelog

#2689 Add internal setting for additional writer headers
  ddtrace/internal/writer.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#2688 Add pytest snapshot fixture
  tests/conftest.py
  tests/utils.py
Labels: changelog/no-changelog

#2690 feat(perf): add base for scenarios
  benchmarks/README.rst
  benchmarks/base/Dockerfile
  benchmarks/base/benchmark
  benchmarks/base/entrypoint
  benchmarks/base/requirements.txt
  benchmarks/base/requirements_scenario.txt
  benchmarks/common/benchmark
  benchmarks/common/entrypoint
  benchmarks/common/util.jq
  benchmarks/encoder/benchmark
  benchmarks/encoder/entrypoint
  benchmarks/encoder/requirements.txt
Labels: changelog/no-changelog

#2634 feat(cassandra): add support for latest
  .circleci/config.yml
  ddtrace/contrib/cassandra/session.py
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#2683 Improving error handling for monkey.py 🐒
  ddtrace/monkey.py
  tests/tracer/test_monkey.py
Labels: changelog/no-changelog

#2640 Add integration tests for ASGI Django 3
  riotfile.py
  tests/contrib/django/asgi.py
  tests/contrib/django/django_app/settings.py
  tests/contrib/django/django_app/urls.py
  tests/contrib/django/test_django_snapshots.py
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_30.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_31.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_3x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_30.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_31.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_3x.snap
Labels: changelog/no-changelog

#2658 feat(perf): add span component scenarios
  benchmarks/span/scenario.py
  benchmarks/span/util.py
Labels: changelog/no-changelog

#2679 ci: fix riotfile to work with new riot 0.7 release
  riotfile.py
  tests/contrib/requests/test_requests.py
Labels: changelog/no-changelog

#2694 perf: add tracer benchmarks
  benchmarks/tracer/scenario.py
Labels: changelog/no-changelog

#2700 chore: add riot to gitignore
  .gitignore
Labels: changelog/no-changelog

#2703 fix: fix latest sanic release note
  releasenotes/notes/fix-sanic-non-str-args-4d1b0f506bee3436.yaml
Labels: changelog/no-changelog

#2687 Update gitlab CI env var extraction for commit author/date
  ddtrace/ext/ci.py
  tests/tracer/fixtures/ci/gitlab.json
Labels: changelog/no-changelog, manual merge

#2705 Updated bitrise CI environment var for ci.pipeline.name
  ddtrace/ext/ci.py
  tests/tracer/fixtures/ci/bitrise.json
Labels: changelog/no-changelog

#2707 ci: unpin riot
  .circleci/config.yml
  riotfile.py
  scripts/ddtest
Labels: changelog/no-changelog

#2715 Added py.typed for ddtrace
  ddtrace/py.typed
  setup.py
Labels: changelog/no-changelog

#2709 fix[flask]: ignore werkzeug.NotFound errors as server errors
  ddtrace/contrib/flask/patch.py
  releasenotes/notes/fix-flask-werkzeug-ignore-server-error-5131cbe28afca03a.yaml
  tests/contrib/flask/test_errorhandler.py
  tests/contrib/flask/test_request.py
Labels: manual merge

#2716 django: remove duplicate tracing header extraction
  ddtrace/contrib/django/utils.py
  tests/contrib/django/test_django.py
Labels: changelog/no-changelog

#2702 test(profiling): rewrite test_memory_collector_ignore_profile to be more robust
  tests/profiling/collector/test_memalloc.py
Labels: changelog/no-changelog

#2712 Add additional tests for distributed tracing enabled
  ddtrace/contrib/trace_utils.py
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog

#2468 ci(coverage): re-enable coverage
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#2718 chore(docs): add anchors to environment variables
  docs/configuration.rst
Labels: changelog/no-changelog

#2722 Add pytest fixture for snapshot_context with preconfigured test token
  tests/conftest.py
Labels: changelog/no-changelog
