Repository DataDog/dd-trace-py, pull requests merged in 2021-01, with the labels that each got.

#1860 http helper custom error codes
  ddtrace/contrib/trace_utils.py
  ddtrace/settings/config.py
  docs/advanced_usage.rst
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog

#1902 refactor(profiling/memalloc): add array handling macros
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_tb.c
  ddtrace/profiling/collector/_memalloc_tb.h
  ddtrace/profiling/collector/_utils.h
Labels: changelog/no-changelog

#1925 fix(ci): flake8 ignore B902
  tox.ini
Labels: changelog/no-changelog

#1919 refactor(profiling): add Scheduler.before_hook
  ddtrace/profiling/scheduler.py
  tests/profiling/test_scheduler.py
Labels: changelog/no-changelog

#1928 refactor(profiling): allow Collectors to run a function before flushing
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/profiler.py
  ddtrace/profiling/scheduler.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog

#1924 ext: update ci specs
  ddtrace/ext/ci.py
  tests/tracer/fixtures/ci/appveyor.json
  tests/tracer/fixtures/ci/azurepipelines.json
  tests/tracer/fixtures/ci/bitbucket.json
  tests/tracer/fixtures/ci/bitrise.json
  tests/tracer/fixtures/ci/buildkite.json
  tests/tracer/fixtures/ci/circleci.json
  tests/tracer/fixtures/ci/github.json
  tests/tracer/fixtures/ci/gitlab.json
  tests/tracer/fixtures/ci/jenkins.json
  tests/tracer/fixtures/ci/travisci.json
Labels: changelog/no-changelog

#1930 fix(profiling/memalloc): add missing pack(pop) on Windows
  ddtrace/profiling/collector/_memalloc_tb.h
Labels: changelog/no-changelog

#1933 ext: update ci specs
  ddtrace/ext/ci.py
  ddtrace/ext/git.py
  tests/tracer/fixtures/ci/appveyor.json
  tests/tracer/fixtures/ci/azurepipelines.json
  tests/tracer/fixtures/ci/bitbucket.json
  tests/tracer/fixtures/ci/bitrise.json
  tests/tracer/fixtures/ci/buildkite.json
  tests/tracer/fixtures/ci/circleci.json
  tests/tracer/fixtures/ci/github.json
  tests/tracer/fixtures/ci/gitlab.json
  tests/tracer/fixtures/ci/jenkins.json
  tests/tracer/fixtures/ci/travisci.json
Labels: changelog/no-changelog

#1937 ext: update ci specs - GitLab
  ddtrace/ext/ci.py
  tests/tracer/fixtures/ci/gitlab.json
Labels: changelog/no-changelog

#1940 format opentracing module
  ddtrace/opentracer/__init__.py
  ddtrace/opentracer/propagation/__init__.py
  ddtrace/opentracer/propagation/http.py
  ddtrace/opentracer/propagation/propagator.py
  ddtrace/opentracer/settings.py
  ddtrace/opentracer/span.py
  ddtrace/opentracer/span_context.py
  ddtrace/opentracer/tags.py
  ddtrace/opentracer/tracer.py
  ddtrace/opentracer/utils.py
  pyproject.toml
Labels: changelog/no-changelog

#1895 docs: update DD_VERSION configuration
  docs/configuration.rst
Labels: changelog/no-changelog

#1923 Remove unneeded compat utils from dogstatsd
  ddtrace/vendor/__init__.py
  ddtrace/vendor/dogstatsd/compat.py
Labels: changelog/no-changelog

#1939 PR template fix-ups
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/bugfix.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/integration.md
Labels: changelog/no-changelog, docs

#1917 Add arch64 wheel build support
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#1946 fix(core): handle failed encoding
  ddtrace/internal/writer.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#1949 tests: exclude py27 grpc 1.14, 1.18
  tox.ini
Labels: changelog/no-changelog

#1948 chore: use Mergify to automatically merge/update PR
  .mergify.yml
Labels: changelog/no-changelog

#1938 perf(grpc): avoid unnecessary checks for span tags
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/contrib/grpc/server_interceptor.py
Labels: automerge, changelog/no-changelog

#1954 chore: format tests/tracer/
  pyproject.toml
  tests/tracer/test_api.py
  tests/tracer/test_compat.py
  tests/tracer/test_context.py
  tests/tracer/test_context_manager.py
  tests/tracer/test_encoders.py
  tests/tracer/test_ext.py
  tests/tracer/test_filters.py
  tests/tracer/test_global_config.py
  tests/tracer/test_helpers.py
  tests/tracer/test_hook.py
  tests/tracer/test_hostname.py
  tests/tracer/test_http.py
  tests/tracer/test_import_hooks.py
  tests/tracer/test_instance_config.py
  tests/tracer/test_logger.py
  tests/tracer/test_payload.py
  tests/tracer/test_pin.py
  tests/tracer/test_rate_limiter.py
  tests/tracer/test_sampler.py
  tests/tracer/test_settings.py
  tests/tracer/test_span.py
  tests/tracer/test_tracer.py
  tests/tracer/test_utils.py
Labels: automerge, changelog/no-changelog

#1957 docs: fix release notes release_tag_re
  releasenotes/config.yaml
Labels: automerge, changelog/no-changelog

#1955 refactor sampling tests to be context independent
  ddtrace/sampler.py
  tests/integration/test_integration.py
  tests/snapshots/tests.integration.test_integration.test_sampling.snap
  tests/tracer/test_sampler.py
Labels: automerge, changelog/no-changelog

#1961 ci: fix flaky grpc tests
  tests/contrib/grpc/test_grpc.py
Labels: automerge, changelog/no-changelog

#1962 Revert "tests: exclude py27 grpc 1.14, 1.18"
  tox.ini
Labels: automerge, changelog/no-changelog

#1922 fix(profiling/stack): makes sure to ignore profiler gevent tasks
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/profiling-fix-ignore-profiler-gevent-stack-collector-3270d81c84080ccb.yaml
  tests/profiling/collector/conftest.py
  tests/profiling/collector/test_stack.py
Labels: automerge

#1950 fix propagation extract documentation
  ddtrace/propagation/http.py
Labels: automerge, changelog/no-changelog, docs

#1886 docs: update http tagging information
  ddtrace/contrib/aiohttp/__init__.py
  ddtrace/contrib/bottle/__init__.py
  ddtrace/contrib/flask/__init__.py
  ddtrace/contrib/molten/__init__.py
  ddtrace/contrib/pyramid/__init__.py
  docs/advanced_usage.rst
Labels: automerge, changelog/no-changelog

#1808 Add WSGI middleware
  .circleci/config.yml
  ddtrace/contrib/wsgi/__init__.py
  ddtrace/contrib/wsgi/wsgi.py
  docs/spelling_wordlist.txt
  releasenotes/notes/wsgi-30613a9c30834225.yaml
  riotfile.py
  tests/conftest.py
  tests/contrib/wsgi/__init__.py
  tests/contrib/wsgi/test_wsgi.py
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_200.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_500_py2.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_500_py3.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_chunked.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_generator_exit_ignored_in_top_level_span_snapshot_py2.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_generator_exit_ignored_in_top_level_span_snapshot_py3.snap
  tests/tracer/test_tracer.py
Labels: automerge

#1964 ci(mergify): add more conditions before trying to merge
  .mergify.yml
Labels: changelog/no-changelog

#1963 ci: lower max pool of workers for grpc server
  tests/contrib/grpc/test_grpc.py
Labels: automerge, changelog/no-changelog

#1951 Use cibuildwheel to build aarch64 wheels
  .github/workflows/build_deploy.yml
Labels: automerge, changelog/no-changelog
