Repository DataDog/dd-trace-py, pull requests merged in 2021-03, with the labels that each got.

#2072 tests: get_dummy_tracer -> DummyTracer
  tests/conftest.py
  tests/contrib/aiobotocore/py35/test.py
  tests/contrib/aiobotocore/test.py
  tests/contrib/aiopg/test.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/bottle/test_autopatch.py
  tests/contrib/cassandra/test.py
  tests/contrib/dogpile_cache/test_tracing.py
  tests/contrib/falcon/test_distributed_tracing.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/flask/test_middleware.py
  tests/contrib/flask_autopatch/test_flask_autopatch.py
  tests/contrib/gevent/test_tracer.py
  tests/contrib/jinja2/test_jinja2.py
  tests/contrib/mako/test_mako.py
  tests/contrib/molten/test_molten_di.py
  tests/contrib/mongoengine/test.py
  tests/contrib/mongoengine/test_backwards.py
  tests/contrib/mysql/test_backwards_compatibility.py
  tests/contrib/pymemcache/test_client.py
  tests/contrib/pymemcache/test_client_mixin.py
  tests/contrib/pymongo/test.py
  tests/contrib/pymysql/test_backwards_compatibility.py
  tests/contrib/redis/test_redis.py
  tests/contrib/rediscluster/test.py
  tests/contrib/sanic/conftest.py
  tests/contrib/starlette/test_starlette.py
  tests/contrib/vertica/test_vertica.py
  tests/opentracer/conftest.py
  tests/opentracer/core/test_span.py
  tests/tracer/test_context.py
  tests/tracer/test_global_config.py
  tests/tracer/test_propagation.py
  tests/tracer/test_sampler.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#2076 tests(sanic): pin pytest-sanic version
  tox.ini
Labels: automerge, changelog/no-changelog

#2061 grpc(tests): add older versions, ignore buggy versions, bump parallelism
  .circleci/config.yml
  docs/index.rst
  riotfile.py
Labels: automerge, changelog/no-changelog

#2075 fix: ensure empty middleware is caught in django
  ddtrace/contrib/django/patch.py
  releasenotes/notes/fix-django-empty-middleware-056f9c75ad963f1f.yaml
  tests/contrib/django/middleware.py
  tests/contrib/django/test_django.py
Labels: automerge, bug

#2068 chore: format http, propagation modules
  ddtrace/http/__init__.py
  ddtrace/http/headers.py
  ddtrace/propagation/http.py
  ddtrace/propagation/utils.py
  pyproject.toml
  tox.ini
Labels: automerge, changelog/no-changelog

#2027 chore(vendor): upgrade attrs to 20.3.0
  ddtrace/vendor/__init__.py
  ddtrace/vendor/attr/__init__.py
  ddtrace/vendor/attr/__init__.pyi
  ddtrace/vendor/attr/_compat.py
  ddtrace/vendor/attr/_funcs.py
  ddtrace/vendor/attr/_make.py
  ddtrace/vendor/attr/_next_gen.py
  ddtrace/vendor/attr/converters.py
  ddtrace/vendor/attr/converters.pyi
  ddtrace/vendor/attr/exceptions.py
  ddtrace/vendor/attr/exceptions.pyi
  ddtrace/vendor/attr/setters.py
  ddtrace/vendor/attr/setters.pyi
  ddtrace/vendor/attr/validators.py
Labels: automerge, changelog/no-changelog

#2074 Remove deprecated dogstatsd arguments to configure
  ddtrace/tracer.py
  releasenotes/notes/configure-6973c2ed2105a1c0.yaml
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#2019 refactor(profiling/memalloc): pass heap_sample_size at init + return bool
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_heap.c
  ddtrace/profiling/collector/_memalloc_heap.h
Labels: automerge, changelog/no-changelog

#2087 chore: format ext module
  ddtrace/ext/cassandra.py
  ddtrace/ext/db.py
  ddtrace/ext/elasticsearch.py
  ddtrace/ext/errors.py
  ddtrace/ext/http.py
  ddtrace/ext/kombu.py
  ddtrace/ext/memcached.py
  ddtrace/ext/mongo.py
  ddtrace/ext/net.py
  ddtrace/ext/sql.py
  ddtrace/ext/system.py
  pyproject.toml
Labels: automerge, changelog/no-changelog

#2090 fix(profiler): do not log error when a collector it not available
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/memory.py
  ddtrace/profiling/profiler.py
Labels: automerge, changelog/no-changelog

#2083 perf(http): Improve header extraction
  ddtrace/propagation/http.py
  releasenotes/notes/perf-improve-header-extraction-30f575d5034b7e20.yaml
  tests/benchmarks/test_propagation.py
Labels: automerge

#2088 chore: format flask-cache and tests
  ddtrace/contrib/flask_cache/__init__.py
  ddtrace/contrib/flask_cache/tracers.py
  ddtrace/contrib/flask_cache/utils.py
  pyproject.toml
  tests/contrib/flask_autopatch/test_flask_autopatch.py
  tests/contrib/flask_cache/test.py
  tests/contrib/flask_cache/test_utils.py
  tests/contrib/flask_cache/test_wrapper_safety.py
Labels: automerge, changelog/no-changelog

#2070 configure: fix dogstatsd configuration for existing writers
  ddtrace/tracer.py
  releasenotes/notes/configure-a39313ef4fed9028.yaml
  tests/tracer/test_tracer.py
Labels: automerge

#2095 chore: remove writer services
  ddtrace/internal/writer.py
  tests/__init__.py
  tests/contrib/aiopg/test.py
  tests/contrib/bottle/test.py
  tests/contrib/bottle/test_autopatch.py
  tests/contrib/flask/test_middleware.py
  tests/contrib/psycopg/test_psycopg.py
  tests/contrib/pymongo/test.py
  tests/contrib/pyramid/utils.py
  tests/contrib/sqlalchemy/mixins.py
  tests/contrib/sqlite3/test_sqlite3.py
Labels: automerge, changelog/no-changelog

#2102 refactor(writer): remove unneeded reraise usage
  ddtrace/internal/writer.py
Labels: automerge, changelog/no-changelog

#2100 perf(http): Further header extraction improvements
  ddtrace/propagation/http.py
Labels: automerge, changelog/no-changelog

#2089 feat(profiling/memalloc): use a geometric distribution to randomize heap samples
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_heap.c
  ddtrace/profiling/collector/_utils.h
  tests/profiling/collector/test_memalloc.py
Labels: automerge, changelog/no-changelog

#2097 Add TraceFilter abstract base class
  ddtrace/filters.py
  docs/advanced_usage.rst
  tests/tracer/test_filters.py
Labels: automerge, changelog/no-changelog

#2096 tests: remove explicit writer usage from opentracing tests
  tests/__init__.py
  tests/opentracer/conftest.py
  tests/opentracer/core/test_dd_compatibility.py
  tests/opentracer/core/test_span.py
  tests/opentracer/core/test_tracer.py
  tests/opentracer/test_tracer_asyncio.py
  tests/opentracer/test_tracer_gevent.py
  tests/opentracer/test_tracer_tornado.py
Labels: automerge, changelog/no-changelog

#2104 chore(botocore): Format botocore
  ddtrace/contrib/botocore/__init__.py
  ddtrace/contrib/botocore/patch.py
  pyproject.toml
  tests/contrib/botocore/test.py
Labels: automerge, changelog/no-changelog

#2108 chore(grpc): format grpc
  ddtrace/contrib/grpc/__init__.py
  ddtrace/contrib/grpc/constants.py
  ddtrace/contrib/grpc/patch.py
  ddtrace/contrib/grpc/server_interceptor.py
  ddtrace/contrib/grpc/utils.py
  pyproject.toml
  tests/contrib/grpc/hello_pb2.py
  tests/contrib/grpc/hello_pb2_grpc.py
  tests/contrib/grpc/test_grpc.py
  tests/contrib/grpc/test_grpc_utils.py
Labels: automerge, changelog/no-changelog

#2107 chore(celery): format celery
  ddtrace/contrib/celery/__init__.py
  ddtrace/contrib/celery/app.py
  ddtrace/contrib/celery/constants.py
  ddtrace/contrib/celery/patch.py
  ddtrace/contrib/celery/signals.py
  ddtrace/contrib/celery/task.py
  ddtrace/contrib/celery/utils.py
  pyproject.toml
Labels: automerge, changelog/no-changelog

#2110 chore(pylons): format pylons
  ddtrace/contrib/pylons/__init__.py
  ddtrace/contrib/pylons/constants.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/pylons/patch.py
  ddtrace/contrib/pylons/renderer.py
  pyproject.toml
  tests/contrib/pylons/app/controllers/root.py
  tests/contrib/pylons/app/lib/helpers.py
  tests/contrib/pylons/app/middleware.py
  tests/contrib/pylons/app/router.py
  tests/contrib/pylons/app/web.py
  tests/contrib/pylons/test_pylons.py
Labels: automerge, changelog/no-changelog

#2105 tests: remove left over services references
  tests/__init__.py
Labels: automerge, changelog/no-changelog

#2109 chore(kombu): format kombu
  ddtrace/contrib/kombu/__init__.py
  ddtrace/contrib/kombu/constants.py
  ddtrace/contrib/kombu/patch.py
  ddtrace/contrib/kombu/utils.py
  pyproject.toml
  tests/contrib/kombu/test.py
Labels: automerge, changelog/no-changelog

#2114 refactor(tests): testing utils
  tests/__init__.py
  tests/conftest.py
  tests/tracer/test_sampler.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#2117 fix(botocore) Ensure the presence of ResponseMetadata key in the result
  ddtrace/contrib/botocore/patch.py
  releasenotes/notes/fix-botocore-missing-response-meta-e80c1cfb34ec0881.yaml
  tests/contrib/botocore/test.py
Labels: automerge

#2115 flask: remove extra_error_codes
  ddtrace/contrib/flask/patch.py
  releasenotes/notes/flask-codes-f0841d78ec847807.yaml
  tests/contrib/flask/test_request.py
Labels: automerge

#2106 fix(dbapi): allow TracedCursor's callproc() to accept arbitrary args
  ddtrace/contrib/dbapi/__init__.py
  tests/contrib/dbapi/test_dbapi.py
Labels: automerge, bug, changelog/no-changelog

#2118 tests(a-e): use pytest fixtures, unittest helpers
  tests/contrib/aiobotocore/py35/test.py
  tests/contrib/aiobotocore/test.py
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/aiohttp/test_request.py
  tests/contrib/aiohttp/test_request_safety.py
  tests/contrib/aiohttp/test_templates.py
  tests/contrib/aiopg/py35/test.py
  tests/contrib/aiopg/py37/test.py
  tests/contrib/aiopg/test.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/asyncio/test_propagation.py
  tests/contrib/asyncio/test_tracer.py
  tests/contrib/asyncio/test_tracer_safety.py
  tests/contrib/boto/test.py
  tests/contrib/bottle/test.py
  tests/contrib/bottle/test_autopatch.py
  tests/contrib/bottle/test_distributed.py
  tests/contrib/cassandra/test.py
  tests/contrib/celery/test_integration.py
  tests/contrib/celery/test_old_style_task.py
  tests/contrib/celery/test_utils.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/dbapi/test_dbapi.py
  tests/contrib/django/conftest.py
  tests/contrib/django/test_django.py
  tests/contrib/dogpile_cache/test_tracing.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/flask/__init__.py
  tests/contrib/flask/test_middleware.py
  tests/contrib/flask/test_request.py
  tests/contrib/flask_autopatch/test_flask_autopatch.py
  tests/contrib/flask_cache/test_wrapper_safety.py
Labels: automerge, changelog/no-changelog

#2119 tests(f-o): use pytest fixtures, unittest helpers
  tests/contrib/gevent/test_tracer.py
  tests/contrib/grpc/test_grpc.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/httplib/test_httplib_distributed.py
  tests/contrib/jinja2/test_jinja2.py
  tests/contrib/mako/test_mako.py
  tests/contrib/molten/test_molten.py
  tests/contrib/molten/test_molten_di.py
  tests/contrib/mongoengine/test.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysqldb.py
Labels: automerge, changelog/no-changelog

#2120 tests(p-z): use pytest fixtures, unittest helpers
  tests/contrib/pylibmc/test.py
  tests/contrib/pylons/test_pylons.py
  tests/contrib/pymemcache/test_client.py
  tests/contrib/pymemcache/test_client_mixin.py
  tests/contrib/pymongo/test.py
  tests/contrib/pymysql/test_pymysql.py
  tests/contrib/pyodbc/test_pyodbc.py
  tests/contrib/pyramid/test_pyramid.py
  tests/contrib/pyramid/test_pyramid_autopatch.py
  tests/contrib/pyramid/utils.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/redis/test_redis.py
  tests/contrib/rediscluster/test.py
  tests/contrib/requests/test_requests.py
  tests/contrib/requests/test_requests_distributed.py
  tests/contrib/sanic/test_sanic.py
  tests/contrib/sanic/test_sanic_server.py
  tests/contrib/sqlalchemy/mixins.py
  tests/contrib/sqlalchemy/test_mysql.py
  tests/contrib/sqlalchemy/test_patch.py
  tests/contrib/sqlalchemy/test_postgres.py
  tests/contrib/sqlalchemy/test_sqlite.py
  tests/contrib/starlette/test_starlette.py
  tests/contrib/tornado/test_executor_decorator.py
  tests/contrib/tornado/test_safety.py
  tests/contrib/tornado/test_stack_context.py
  tests/contrib/tornado/test_tornado_template.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/tornado/test_wrap_decorator.py
  tests/contrib/vertica/test_vertica.py
  tests/contrib/wsgi/test_wsgi.py
Labels: automerge, changelog/no-changelog

#2122 ci(mergify): change label merge condition
  .mergify.yml
Labels: changelog/no-changelog

#2071 tests: use pytest fixtures, unittest helpers when possible
  tests/benchmarks/test_tracer.py
Labels: automerge, changelog/no-changelog

#2101 refactor(propagation): Make Propagator all static
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/bottle/trace.py
  ddtrace/contrib/celery/signals.py
  ddtrace/contrib/cherrypy/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/contrib/grpc/server_interceptor.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/kombu/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/pyramid/trace.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/sanic/patch.py
  ddtrace/contrib/tornado/handlers.py
  ddtrace/contrib/trace_utils.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/opentracer/propagation/http.py
  ddtrace/opentracer/propagation/propagator.py
  ddtrace/opentracer/tracer.py
  ddtrace/propagation/http.py
  tests/benchmarks/test_propagation.py
  tests/contrib/celery/test_integration.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#2128 Tweak wording
  docs/basic_usage.rst
Labels: changelog/no-changelog

#2098 Add TraceWriter abstract base class
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
Labels: automerge, changelog/no-changelog

#2124 refactor(runtime_metrics): update the tags on init
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/tracer.py
Labels: automerge, changelog/no-changelog

#2126 tests: add racing start test for writer
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#2127 docs: add test helpers to integration checklist
  .github/PULL_REQUEST_TEMPLATE/integration.md
Labels: changelog/no-changelog

#2135 test(profiling): reduce sample size for test_heap_collector
  tests/profiling/collector/test_memalloc.py
Labels: changelog/no-changelog

#2137 ci: build cp27 with older manylinux
  scripts/build-dist-cp27
  scripts/mkwheelhouse
Labels: automerge, changelog/no-changelog

#2123 fix(profiling): change default timeout to match tracer
  ddtrace/internal/agent.py
  ddtrace/internal/writer.py
  ddtrace/profiling/exporter/http.py
  releasenotes/notes/profiling-default-timeout-agent-43b19237a21fd337.yaml
Labels: automerge

#2143 Fix flask patch on import string
  ddtrace/monkey.py
Labels: changelog/no-changelog

#2112 ci(mypy): enable mypy check for profiling
  .circleci/config.yml
  ddtrace/profiling/_build.pyi
  ddtrace/profiling/_build.pyx
  ddtrace/profiling/_line2def.py
  ddtrace/profiling/_nogevent.py
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/_memalloc.pyi
  ddtrace/profiling/collector/_threading.pyi
  ddtrace/profiling/collector/_traceback.pyi
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyi
  ddtrace/profiling/collector/threading.py
  ddtrace/profiling/exporter/__init__.py
  ddtrace/profiling/exporter/file.py
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/exporter/pprof.pyi
  ddtrace/profiling/exporter/pprof.pyx
  ddtrace/profiling/profiler.py
  mypy.ini
  riotfile.py
  scripts/stubgen.sh
  tests/contrib/pylons/app/lib/helpers.py
Labels: automerge, changelog/no-changelog

#2141 elasticsearch: remove _perform_request method
  ddtrace/contrib/elasticsearch/elasticsearch.py
  ddtrace/contrib/elasticsearch/patch.py
  tests/contrib/elasticsearch/test.py
Labels: changelog/no-changelog

#2140 Remove unused line from circleci config
  .circleci/config.yml
Labels: changelog/no-changelog

#2144 refactor(profiling): remove line2def
  ddtrace/profiling/_line2def.py
  ddtrace/profiling/exporter/pprof.pyx
  setup.py
  tests/profiling/test_line2def.py
Labels: changelog/no-changelog

#2150 docs: update pytest supported scope
  docs/index.rst
Labels: changelog/no-changelog

#2153 format test files
  pyproject.toml
  tests/contrib/patch.py
  tests/ddtrace_run.py
  tests/profiling/_ast_test_file.py
  tests/subprocesstest.py
  tests/wait-for-services.py
Labels: changelog/no-changelog

#2086 tests(grpc): don't test 1.15, 1.17, 1.18
  riotfile.py
Labels: automerge, changelog/no-changelog

#2151 Cleanup DatadogSampler initialization
  ddtrace/sampler.py
  tests/tracer/test_sampler.py
Labels: changelog/no-changelog

#2152 Fix test_tracer_url test
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#2154 ci(flask): support for Flask 1.1 and Python > 3.6
  tests/contrib/flask/test_request.py
  tox.ini
Labels: changelog/no-changelog

#2134 Perform tracer initialization in initializer
  ddtrace/internal/agent.py
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/__init__.py
  tests/integration/test_integration.py
  tests/tracer/test_agent.py
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#2157 ci(pytest): test pytest integration with Python 3.9
  tox.ini
Labels: changelog/no-changelog

#2158 Refactor global config imports
  ddtrace/__init__.py
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/aiopg/connection.py
  ddtrace/contrib/algoliasearch/patch.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/bottle/trace.py
  ddtrace/contrib/cassandra/session.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/elasticsearch/patch.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/flask_cache/tracers.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/kombu/patch.py
  ddtrace/contrib/mako/patch.py
  ddtrace/contrib/pylibmc/client.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/pymemcache/client.py
  ddtrace/contrib/pymongo/client.py
  ddtrace/contrib/pyramid/trace.py
  ddtrace/contrib/sqlalchemy/engine.py
  ddtrace/contrib/sqlite3/patch.py
  ddtrace/contrib/tornado/handlers.py
  ddtrace/contrib/vertica/patch.py
  ddtrace/monkey.py
  ddtrace/settings/__init__.py
  ddtrace/tracer.py
Labels: automerge, changelog/no-changelog

#2149 Apply small optimizations to HTTPPropagator.extract
  ddtrace/propagation/http.py
  tests/benchmarks/test_propagation.py
  tests/tracer/test_propagation.py
Labels: automerge, changelog/no-changelog

#2160 Move Flask and Flask-Cache tests to riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#2161 Move ddtracerun, logging, and vendor from tox to riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#2168 refactor(profiling): move service module to tracer internal
  ddtrace/internal/service.py
  ddtrace/profiling/_periodic.py
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/profiler.py
  tests/profiling/collector/test_service.py
  tests/profiling/collector/test_stack.py
  tests/profiling/simple_program.py
  tests/profiling/simple_program_fork.py
  tests/profiling/test_periodic.py
  tests/tracer/test_service.py
Labels: changelog/no-changelog

#2172 Fix starlette tests
  riotfile.py
Labels: changelog/no-changelog

#2174 django: use _set_str_tag where possible
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
Labels: changelog/no-changelog

#2173 tests(tornado): use real tracer for configuration tests
  tests/contrib/tornado/test_config.py
Labels: changelog/no-changelog

#2177 trace_utils: handle non-integer error codes
  ddtrace/contrib/trace_utils.py
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog

#2121 Add TraceProcessor
  ddtrace/internal/processor.py
  ddtrace/tracer.py
  tests/tracer/test_processor.py
Labels: changelog/no-changelog

#2164 ci(mypy): make sure we don't leave useless comments nor config
  mypy.ini
Labels: changelog/no-changelog

#2163 Enable mypy for ddtrace core, add type hinting for tracer and filters
  ddtrace/_hooks.py
  ddtrace/compat.py
  ddtrace/filters.py
  ddtrace/internal/_encoding.pyi
  ddtrace/internal/_rand.pyi
  ddtrace/internal/writer.py
  ddtrace/provider.py
  ddtrace/sampler.py
  ddtrace/tracer.py
  mypy.ini
Labels: changelog/no-changelog

#2162 Make DummyWriter dumb
  tests/__init__.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#2166 refactor(profiling): add some typing on periodic
  ddtrace/profiling/_periodic.py
Labels: changelog/no-changelog

#2181 Fix: Explicitly cast span.duration_ns as int when setting
  ddtrace/span.py
  tests/tracer/test_span.py
Labels: automerge, bug, changelog/no-changelog

#2178 refactor(profiling): move nogevent to ddtrace.internal
  ddtrace/internal/nogevent.py
  ddtrace/profiling/_periodic.py
  ddtrace/profiling/collector/_threading.pyx
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/recorder.py
  tests/profiling/collector/test_memalloc.py
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog

#2094 fix: exception handling for user authentication in django
  ddtrace/contrib/django/patch.py
  tests/contrib/django/test_django.py
Labels: automerge, bug, changelog/no-changelog

#2180 Enable mypy for ddtrace core, add type hinting for context, monkey, span, provider, helpers
  ddtrace/context.py
  ddtrace/filters.py
  ddtrace/helpers.py
  ddtrace/internal/writer.py
  ddtrace/monkey.py
  ddtrace/provider.py
  ddtrace/span.py
  ddtrace/tracer.py
Labels: automerge, changelog/no-changelog

#2183 Black and Riot mako
  .circleci/config.yml
  ddtrace/contrib/mako/__init__.py
  ddtrace/contrib/mako/constants.py
  ddtrace/contrib/mako/patch.py
  pyproject.toml
  riotfile.py
  tests/contrib/mako/test_mako.py
  tox.ini
Labels: changelog/no-changelog

#2084 perf(django): patch connection on registration
  ddtrace/contrib/django/patch.py
  tests/contrib/django/test_django.py
  tests/contrib/django/test_django_patch.py
Labels: changelog/no-changelog

#2179 fix(profiling): use service lock to avoid race condition on start
  ddtrace/internal/service.py
  ddtrace/profiling/_periodic.py
  ddtrace/profiling/profiler.py
  tests/profiling/test_periodic.py
Labels: changelog/no-changelog

#2167 refactor(worker): remove atexit support
  ddtrace/_worker.py
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/tracer/test_worker.py
Labels: changelog/no-changelog

#2188 Added mypy type hinting to hooks, worker, encoding, payload, pin, sampler
  ddtrace/_hooks.py
  ddtrace/_worker.py
  ddtrace/encoding.py
  ddtrace/internal/_encoding.pyi
  ddtrace/payload.py
  ddtrace/pin.py
  ddtrace/sampler.py
Labels: automerge, changelog/no-changelog

#2182 feat(utils): introduce argument value getter
  ddtrace/utils/__init__.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog

#2193 Added explicit NoneType return for mypy in span.duration
  ddtrace/span.py
  tests/tracer/test_span.py
Labels: automerge, changelog/no-changelog

#2194 Fixed default sample_rates to be floats rather than int
  ddtrace/sampler.py
Labels: automerge, changelog/no-changelog

#2197 Added return type hint to compat.get_connection_response()
  ddtrace/compat.py
Labels: automerge, changelog/no-changelog

#2200 style(aiobotocore): format aiobotocore
  ddtrace/contrib/aiobotocore/__init__.py
  ddtrace/contrib/aiobotocore/patch.py
  pyproject.toml
  tests/contrib/aiobotocore/py35/test.py
  tests/contrib/aiobotocore/utils.py
Labels: changelog/no-changelog

#2201 style(boto): format boto
  ddtrace/contrib/boto/__init__.py
  ddtrace/contrib/boto/patch.py
  pyproject.toml
  tests/contrib/boto/test.py
Labels: changelog/no-changelog

#2199 style(aws): add type hints to ext.aws
  ddtrace/contrib/aiobotocore/patch.py
  ddtrace/contrib/boto/patch.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/ext/aws.py
  mypy.ini
Labels: changelog/no-changelog

#2184 refactor(profiling): move periodic to ddtrace.internal
  ddtrace/internal/periodic.py
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/_threading.pyx
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/scheduler.py
  tests/tracer/test_periodic.py
Labels: changelog/no-changelog

#2191 perf(aws): avoid flattening excluded arguments
  ddtrace/contrib/trace_utils.py
  ddtrace/ext/aws.py
  tests/benchmarks/test_trace_utils.py
  tests/tracer/test_ext.py
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog

#2207 Add agent url to writer logs
  ddtrace/internal/writer.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#2209 tests(integration): separate snapshot tests into own module
  tests/integration/test_integration.py
  tests/integration/test_integration_snapshots.py
  tests/snapshots/tests.integration.test_integration_snapshots.test_filters.snap
  tests/snapshots/tests.integration.test_integration_snapshots.test_multiple_traces.snap
  tests/snapshots/tests.integration.test_integration_snapshots.test_sampling.snap
  tests/snapshots/tests.integration.test_integration_snapshots.test_single_trace_single_span.snap
Labels: changelog/no-changelog

#2208 Instantiate new tracer instance for each snapshot
  tests/__init__.py
Labels: changelog/no-changelog

#2213 fix typo in filter debug line
  ddtrace/internal/processor.py
Labels: changelog/no-changelog

#2196 feat: support space separated DD_TAGS value
  ddtrace/utils/formats.py
  docs/configuration.rst
  releasenotes/notes/ddtags-space-82407d0d3f0426cd.yaml
  tests/tracer/test_utils.py
Labels: automerge, feature-request

#2206 Add sync mode to AgentWriter
  ddtrace/internal/writer.py
  tests/integration/test_integration.py
  tests/integration/test_integration_snapshots.py
  tests/snapshots/tests.integration.test_integration_snapshots.test_synchronous_writer.snap
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#2203 ci: run django test suite with ddtrace enabled
  .github/workflows/django.yml
Labels: changelog/no-changelog

#2190 ci: run flask test suite with ddtrace enabled
  .github/workflows/flask.yml
Labels: changelog/no-changelog

#2220 docs: add note about pip version requirement
  docs/installation_quickstart.rst
Labels: changelog/no-changelog

#2216 refactor: distributed_tracing_enabled usages to trace_utils helper
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/grpc/server_interceptor.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/sanic/patch.py
  ddtrace/contrib/trace_utils.py
Labels: automerge, changelog/no-changelog

#2221 Make tracer tests less noisy
  tests/tracer/test_ext.py
Labels: changelog/no-changelog

#2205 refactor(worker): replace regular thread by PeriodicThread
  ddtrace/_worker.py
  ddtrace/internal/writer.py
Labels: changelog/no-changelog

#2224 Disable known failing Django tests
  .github/workflows/django.yml
Labels: automerge, changelog/no-changelog

#2227 test(botocore): add test case for firehose args
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#2230 refactor: move ddtrace.profiling._attr to ddtrace.utils
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/collector/threading.py
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/scheduler.py
  ddtrace/utils/attr.py
Labels: changelog/no-changelog

#1148 Adding urllib3 integration
  .circleci/config.yml
  ddtrace/contrib/trace_utils.py
  ddtrace/contrib/urllib3/__init__.py
  ddtrace/contrib/urllib3/patch.py
  ddtrace/ext/http.py
  ddtrace/monkey.py
  docs/index.rst
  docs/integrations.rst
  releasenotes/notes/feature-urllib3-integration-ab30709c8a39934c.yaml
  riotfile.py
  tests/contrib/urllib3/__init__.py
  tests/contrib/urllib3/test_urllib3.py
  tests/contrib/urllib3/test_urllib3_patch.py
Labels: integrations

#2232 Revert writer.write argument change
  ddtrace/internal/writer.py
Labels: changelog/no-changelog

#2233 Make processor private on Tracer
  ddtrace/tracer.py
Labels: changelog/no-changelog

#2214 fix(profiling): make sure PeriodicCollector start withing service lock
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
Labels: changelog/no-changelog

#2222 refactor(forksafe): simplify code
  ddtrace/internal/forksafe.py
  tests/tracer/test_forksafe.py
Labels: changelog/no-changelog

#2237 chore: correct typing hints for span.meta
  ddtrace/span.py
Labels: automerge, changelog/no-changelog

#2243 fix(span): ensure ID args have the correct type
  ddtrace/span.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#2202 fix: only warn if using uwsgi with ddtrace-run
  ddtrace/commands/ddtrace_run.py
Labels: automerge, changelog/no-changelog

#2248 Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: automerge, changelog/no-changelog

#2249 Use multiproject pipeline to deploy to reliability env
  .gitlab-ci.yml
Labels: changelog/no-changelog, dev/testing

#2250 style(pymongo): format pymongo
  ddtrace/contrib/pymongo/__init__.py
  ddtrace/contrib/pymongo/client.py
  ddtrace/contrib/pymongo/parse.py
  ddtrace/contrib/pymongo/patch.py
  pyproject.toml
  tests/contrib/pymongo/test.py
  tests/contrib/pymongo/test_spec.py
Labels: changelog/no-changelog

#2218 fix: handle text types in _set_str_tag
  ddtrace/compat.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/trace_utils.py
  ddtrace/span.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#2238 Add type hints for internal.writer and internal.dogstatsd
  ddtrace/internal/dogstatsd.py
  ddtrace/internal/writer.py
  ddtrace/tracer.py
Labels: changelog/no-changelog

#2252 refactor: remove unused hook submodule
  ddtrace/utils/hook.py
  tests/tracer/test_hook.py
Labels: changelog/no-changelog

#2253 Refactor unnecessary NoneType check in parse_dogstatsd_url
  ddtrace/internal/dogstatsd.py
Labels: changelog/no-changelog

#2256 Remove unused import_hooks module
  ddtrace/internal/import_hooks.py
  tests/tracer/test_import_hooks.py
  tests/tracer/test_import_hooks_integration.py
Labels: automerge, changelog/no-changelog

#2251 fix(service): make sure the status is stopped on start failure
  ddtrace/internal/service.py
  tests/tracer/test_service.py
Labels: changelog/no-changelog

#2260 refactor(utils): remove unused get_module_name function
  ddtrace/utils/__init__.py
Labels: changelog/no-changelog

#2255 Remove unnecessary caching decorator
  ddtrace/internal/hostname.py
Labels: automerge, changelog/no-changelog

#2228 refactor(writer): replace _worker with PeriodicService
  ddtrace/internal/writer.py
  tests/profiling/collector/test_threading.py
  tests/tracer/test_sampler.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog
