Repository DataDog/dd-trace-py, pull requests merged in 2021-08, with the labels that each got.

#2726 Use dictionary for ASGI scope storage
  ddtrace/contrib/asgi/__init__.py
  ddtrace/contrib/asgi/middleware.py
  releasenotes/notes/asgi-span-19e772cb2f09ef4d.yaml
Labels: changelog/no-changelog

#2735 Pin elasticsearch version
  riotfile.py
Labels: changelog/no-changelog

#2738 ci: use a single workflow for framework tests
  .github/workflows/bottle.yml
  .github/workflows/django.yml
  .github/workflows/fastapi.yml
  .github/workflows/flask.yml
  .github/workflows/httpx.yml
  .github/workflows/mako.yml
  .github/workflows/starlette.yml
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#2731 chore(perf): use pyenv to install
  benchmarks/base/Dockerfile
Labels: changelog/no-changelog

#2721 chore(perf): add script to build perf images
  scripts/perf-build-push
Labels: changelog/no-changelog

#2736 ci: test library installation
  .circleci/config.yml
  .circleci/scripts/test_build.sh
  .github/workflows/build_deploy.yml
  tests/smoke_test.py
Labels: changelog/no-changelog

#2751 refactor[encoder]: extract pack_number, pack_text to module level
  ddtrace/internal/_encoding.pyx
Labels: changelog/no-changelog

#2757 ci: test library installation (backport #2736)
  .circleci/config.yml
  .circleci/scripts/test_build.sh
  .github/workflows/build_deploy.yml
  tests/smoke_test.py
Labels: changelog/no-changelog

#2758 ci: test library installation (backport #2736)
  .circleci/config.yml
  .circleci/scripts/test_build.sh
  .github/workflows/build_deploy.yml
  tests/smoke_test.py
Labels: changelog/no-changelog

#2335 ci: profile overheads in CI runs
  .github/workflows/django-overhead-profile.yml
  riotfile.py
  scripts/diff.py
  scripts/profiles/README.md
  scripts/profiles/django-simple/k6-load.js
  scripts/profiles/django-simple/run.sh
  scripts/profiles/django-simple/setup.sh
Labels: changelog/no-changelog

#2764 fix(ci): fix manual trigger of build job
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#2766 Ensure ca-certificates is installed for benchmark
  benchmarks/base/Dockerfile
Labels: changelog/no-changelog

#2767 fix(ci): fix manual trigger of build job (backport #2764)
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#2742 refactor(perf): scenario framework
  benchmarks/Dockerfile
  benchmarks/README.rst
  benchmarks/base/benchmark
  benchmarks/base/entrypoint
  benchmarks/base/requirements.txt
  benchmarks/base/run.py
  benchmarks/bm/__init__.py
  benchmarks/bm/_scenario.py
  benchmarks/encoder/config.yaml
  benchmarks/encoder/scenario.py
  benchmarks/encoder/utils.py
  docs/benchmarks.rst
  docs/index.rst
  scripts/perf-build-push
Labels: changelog/no-changelog

#2769 perf: update span scenario
  benchmarks/span/config.yaml
  benchmarks/span/scenario.py
  benchmarks/span/util.py
  benchmarks/span/utils.py
Labels: changelog/no-changelog

#2770 chore(perf): add scripts to build and run scenarios
  benchmarks/README.rst
  scripts/perf-build-push
  scripts/perf-build-scenario
  scripts/perf-run-scenario
Labels: changelog/no-changelog

#2771 refactor(perf): update tracer scenario
  benchmarks/tracer/config.yaml
  benchmarks/tracer/scenario.py
Labels: changelog/no-changelog

#2740 refactor[encoder]: Reuse single buffer
  benchmarks/encoder/scenario.py
  ddtrace/internal/_encoding.pyi
  ddtrace/internal/_encoding.pyx
  tests/benchmarks/test_encoding.py
  tests/contrib/pytest/test_pytest.py
  tests/integration/test_integration.py
  tests/tracer/test_encoders.py
  tests/utils.py
Labels: changelog/no-changelog

#2775 chore[mypy]: removed bootstrap from mypy ignores
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/utils/formats.py
  mypy.ini
Labels: changelog/no-changelog

#2776 Update pre commit hooks to run on changed files
  hooks/scripts/run-black.sh
  hooks/scripts/run-codespell.sh
  hooks/scripts/run-flake8.sh
  hooks/scripts/run-mypy.sh
Labels: changelog/no-changelog

#2774 refactor(perf): update django simple scenario to framework
  benchmarks/base/entrypoint
  benchmarks/django_simple/config.yaml
  benchmarks/django_simple/gunicorn.conf.py
  benchmarks/django_simple/install.sh
  benchmarks/django_simple/requirements_scenario.txt
  benchmarks/django_simple/scenario.py
  benchmarks/django_simple/utils.py
Labels: changelog/no-changelog

#2781 Faster CircleCI
  .circleci/config.yml
Labels: changelog/no-changelog

#2783 Fix for https://github.com/DataDog/dd-trace-py/pull/2776
  hooks/scripts/run-black.sh
  hooks/scripts/run-codespell.sh
  hooks/scripts/run-flake8.sh
  hooks/scripts/run-mypy.sh
Labels: changelog/no-changelog

#2768 [ci-app] Allow User to Define Git Metadata
  ddtrace/ext/ci.py
  ddtrace/ext/git.py
  docs/spelling_wordlist.txt
  releasenotes/notes/user-defined-git-metadata-c333300e16662551.yaml
  tests/tracer/test_ci.py
Labels: manual merge

#2785 Ensure git commit hash is extracted in CI
  tests/tracer/test_ci.py
Labels: changelog/no-changelog

#2787 perf: make artifacts dir optional for running a scenario
  scripts/perf-run-scenario
Labels: changelog/no-changelog

#2777 Optimize encoding dd_origin
  benchmarks/encoder/config.yaml
  benchmarks/encoder/scenario.py
  benchmarks/encoder/utils.py
  ddtrace/internal/_encoding.pyx
Labels: changelog/no-changelog

#2784 fix(perf): fix many-tags encoder scenario
  benchmarks/encoder/config.yaml
Labels: changelog/no-changelog

#2786 perf: Add flask_simple benchmark scenario
  benchmarks/flask_simple/app.py
  benchmarks/flask_simple/config.yaml
  benchmarks/flask_simple/gunicorn.conf.py
  benchmarks/flask_simple/requirements_scenario.txt
  benchmarks/flask_simple/scenario.py
  benchmarks/flask_simple/utils.py
  scripts/perf-build-push
Labels: changelog/no-changelog

#2780 chore(perf): remove sample
  benchmarks/sample/meta.yaml
  benchmarks/sample/requirements.txt
Labels: changelog/no-changelog

#2778 chore[mypy]: add type hinting to opentracer module
  ddtrace/opentracer/helpers.py
  ddtrace/opentracer/propagation/http.py
  ddtrace/opentracer/propagation/propagator.py
  ddtrace/opentracer/settings.py
  ddtrace/opentracer/span.py
  ddtrace/opentracer/span_context.py
  ddtrace/opentracer/tags.py
  ddtrace/opentracer/tracer.py
  ddtrace/opentracer/utils.py
  mypy.ini
Labels: changelog/no-changelog

#2790 chore: Update changelog link to legacy django documentation
  CHANGELOG.md
Labels: changelog/no-changelog

#2793 Update basic_usage.rst
  docs/basic_usage.rst
Labels: changelog/no-changelog

#2791 perf: Auto-register bm.Scenario sub-classes
  benchmarks/README.rst
  benchmarks/bm/__init__.py
  benchmarks/bm/_scenario.py
  benchmarks/django_simple/scenario.py
  benchmarks/encoder/scenario.py
  benchmarks/flask_simple/scenario.py
  benchmarks/span/scenario.py
  benchmarks/tracer/scenario.py
Labels: changelog/no-changelog

#2789 perf: add threading benchmark scenario
  benchmarks/README.rst
  benchmarks/threading/README.rst
  benchmarks/threading/config.yaml
  benchmarks/threading/scenario.py
  docs/spelling_wordlist.txt
  scripts/perf-build-push
Labels: changelog/no-changelog, manual merge

#2763 Add test to confirm system pid gets added in forked processes
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#2800 fix(pin): `get_from` type hint
  ddtrace/pin.py
Labels: changelog/no-changelog

#2813 [ci-app] Add `AUTO_KEEP` to All `pytest` Test Spans
  ddtrace/contrib/pytest/plugin.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog

#2811 perf(pin): avoid cloning newly created Pin object
  ddtrace/pin.py
Labels: changelog/no-changelog

#2820 [ci-app] Pytest – Fix Exception Information
  ddtrace/contrib/pytest/plugin.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog
