Repository DataDog/dd-trace-py, pull requests merged in 2021-02, with the labels that each got.

#1968 Integration PR template updates
  .github/PULL_REQUEST_TEMPLATE/integration.md
Labels: automerge, changelog/no-changelog, docs

#1965 Add and fix-up a few tracer tests
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#1970 flask: remove get_current_span helper
  ddtrace/contrib/flask/helpers.py
  ddtrace/contrib/flask/patch.py
Labels: automerge, changelog/no-changelog

#1969 Resolve keyerror in Django traced_get_response
  ddtrace/contrib/django/patch.py
  releasenotes/notes/django-key-error-be8812133f0ef920.yaml
Labels: automerge

#1974 logging: remove logging for parent closing before child
  ddtrace/context.py
  tests/contrib/logging/test_logging.py
  tests/tracer/test_context.py
Labels: automerge, changelog/no-changelog

#1975 format gevent
  ddtrace/contrib/gevent/greenlet.py
  ddtrace/contrib/gevent/provider.py
  pyproject.toml
  tests/contrib/gevent/monkeypatch.py
  tests/contrib/gevent/test_tracer.py
  tests/contrib/gevent/utils.py
Labels: automerge, changelog/no-changelog

#1929 feat(profiling): capture a sample of allocated heap
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_heap.c
  ddtrace/profiling/collector/_memalloc_heap.h
  ddtrace/profiling/collector/_memalloc_tb.h
  ddtrace/profiling/collector/memalloc.py
  setup.py
  tests/profiling/collector/test_memalloc.py
Labels: automerge, changelog/no-changelog

#1973 requests: remove context dependence from tests
  tests/contrib/requests/test_requests_distributed.py
Labels: automerge, changelog/no-changelog

#1977 aiohttp: remove context dependence in tests
  tests/contrib/aiohttp/test_request_safety.py
Labels: automerge, changelog/no-changelog

#1972 Add status_msg to set_http_meta()
  ddtrace/contrib/trace_utils.py
  ddtrace/ext/http.py
  tests/tracer/test_trace_utils.py
Labels: automerge, changelog/no-changelog

#1979 Update integration PR template
  .github/PULL_REQUEST_TEMPLATE/integration.md
Labels: automerge, changelog/no-changelog, docs

#1967 chore(profiling): decrease max CPU usage for stack profiling to 1%
  ddtrace/profiling/collector/stack.pyx
  docs/configuration.rst
  releasenotes/notes/profiling-lower-max-cpu-usage-default-59458d90e0d6d33d.yaml
  tests/profiling/collector/test_stack.py
Labels: automerge

#1976 format futures
  ddtrace/contrib/futures/__init__.py
  ddtrace/contrib/futures/patch.py
  pyproject.toml
  tests/contrib/futures/test_propagation.py
Labels: automerge, changelog/no-changelog

#1966 Introduce CherryPy Tracing
  .circleci/config.yml
  ddtrace/contrib/cherrypy/__init__.py
  ddtrace/contrib/cherrypy/middleware.py
  docs/index.rst
  docs/integrations.rst
  docs/spelling_wordlist.txt
  releasenotes/notes/cherrypy-first-version-89893f512b2fa083.yaml
  tests/contrib/cherrypy/__init__.py
  tests/contrib/cherrypy/test.conf
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/cherrypy/web.py
  tox.ini
Labels: automerge

#1984 tracer: move hostname tagging to start_span
  ddtrace/context.py
  ddtrace/tracer.py
  tests/tracer/test_context.py
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#1986 tests: make context independent
  tests/contrib/futures/test_propagation.py
  tests/tracer/test_propagation.py
Labels: automerge, changelog/no-changelog

#1987 gevent: remove implementation dependent tests
  tests/contrib/gevent/test_tracer.py
Labels: automerge, changelog/no-changelog

#1988 chore(mergify): warn on PR conflict
  .mergify.yml
Labels: changelog/no-changelog

#1982 context: _dd_origin -> dd_origin
  ddtrace/context.py
  ddtrace/propagation/http.py
  tests/tracer/test_context.py
  tests/tracer/test_propagation.py
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#1983 refactor(core): roll context manager into context provider
  ddtrace/contrib/asyncio/provider.py
  ddtrace/contrib/tornado/stack_context.py
  ddtrace/internal/context_manager.py
  ddtrace/provider.py
  tests/tracer/test_context_manager.py
Labels: automerge, changelog/no-changelog

#1981 span: make tests context independent
  tests/tracer/test_span.py
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#1985 asyncio: clean-up tests
  tests/contrib/asyncio/test_helpers.py
  tests/contrib/asyncio/test_tracer.py
  tests/contrib/asyncio/test_tracer_safety.py
Labels: automerge, changelog/no-changelog

#1991 httplib: enable distributed tracing by default
  ddtrace/contrib/httplib/__init__.py
  ddtrace/contrib/httplib/patch.py
  releasenotes/notes/httplib-3b8917c90d162170.yaml
Labels: automerge

#1953 feat(profiling): support most uwsgi modes
  ddtrace/internal/uwsgi.py
  ddtrace/profiling/profiler.py
  docs/spelling_wordlist.txt
  releasenotes/notes/profiling-uwsgi-faaeb38f11bd287b.yaml
  tests/profiling/conftest.py
  tests/profiling/test_uwsgi.py
  tests/profiling/uwsgi-app.py
  tox.ini
Labels: automerge

#1994 ci: disable output buffering
  .circleci/config.yml
  Dockerfile
Labels: automerge, changelog/no-changelog

#1997 django: add measured tag to root span
  ddtrace/contrib/django/patch.py
  releasenotes/notes/django-2ebd5565ee27d4d1.yaml
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_111x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_18x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_21x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_111x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_18x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_21x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_111x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_18x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_21x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_111x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_18x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_21x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include_21x.snap
Labels: automerge

#2002 Pin cryptography package to <3.4
  .circleci/scripts/test_build.sh
Labels: automerge, changelog/no-changelog

#1995 ci: move grpc to riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: automerge, changelog/no-changelog

#1999 test(profiling): make test_not_ignore_profiler_gevent_task more robust
  tests/profiling/collector/test_stack.py
Labels: automerge, changelog/no-changelog

#2004 Migrate elasticsearch from tox to riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: automerge, changelog/no-changelog

#1978 feat(profiling): allow to export memory heap to Python
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_heap.c
  ddtrace/profiling/collector/_memalloc_heap.h
  ddtrace/profiling/collector/_memalloc_tb.c
  ddtrace/profiling/collector/_memalloc_tb.h
  ddtrace/profiling/collector/_utils.h
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/profiler.py
  tests/profiling/collector/test_memalloc.py
Labels: automerge, changelog/no-changelog

#1996 Integration PR template updates
  .github/PULL_REQUEST_TEMPLATE/integration.md
Labels: automerge, changelog/no-changelog

#1767 ci: fix docker-compose port conflict
  .circleci/config.yml
  docker-compose.yml
  scripts/ddtest
  tests/integration/test_integration.py
  tox.ini
Labels: automerge, changelog/no-changelog

#1998 ci: fix flaky cherrypy tests, use riot, snapshots
  .circleci/config.yml
  riotfile.py
  tests/contrib/cherrypy/test_middleware.py
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_child.snap
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_error.snap
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_fatal.snap
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_success.snap
  tox.ini
Labels: automerge, changelog/no-changelog

#2006 flask: don't shortcut on sampling decision
  ddtrace/contrib/flask/middleware.py
  releasenotes/notes/flask-241a6dd8c17e2c12.yaml
Labels: automerge

#2013 ci: use riot for psycopg and sqlalchemy
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: automerge, changelog/no-changelog

#2015 docs: fix missing cython dependencies
  tox.ini
Labels: automerge, changelog/no-changelog

#2012 test(profiling): increase tolerance for accuracy testing
  tests/profiling/test_accuracy.py
Labels: automerge, changelog/no-changelog, dev/testing

#2011 test(profiling): fix test_fork failure
  tests/profiling/simple_program_fork.py
Labels: automerge, changelog/no-changelog, dev/testing

#2010 test(profiling): fix flaky test_ignore_profiler_gevent_task
  tests/profiling/collector/test_stack.py
Labels: automerge, changelog/no-changelog

#2007 chore: format tornado
  ddtrace/contrib/tornado/__init__.py
  ddtrace/contrib/tornado/application.py
  ddtrace/contrib/tornado/compat.py
  ddtrace/contrib/tornado/constants.py
  ddtrace/contrib/tornado/decorators.py
  ddtrace/contrib/tornado/handlers.py
  ddtrace/contrib/tornado/patch.py
  ddtrace/contrib/tornado/stack_context.py
  ddtrace/contrib/tornado/template.py
  pyproject.toml
  tests/contrib/tornado/test_config.py
  tests/contrib/tornado/test_executor_decorator.py
  tests/contrib/tornado/test_safety.py
  tests/contrib/tornado/test_stack_context.py
  tests/contrib/tornado/test_tornado_template.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/tornado/test_wrap_decorator.py
  tests/contrib/tornado/utils.py
  tests/contrib/tornado/web/app.py
  tests/contrib/tornado/web/compat.py
  tests/contrib/tornado/web/uimodules.py
Labels: automerge, changelog/no-changelog

#2014 test(profiling): make sure to wait for all valid events to be seen
  tests/profiling/collector/test_stack.py
Labels: automerge, changelog/no-changelog, dev/testing

#2005 cherrypy: don't shortcut on sampling decision
  ddtrace/contrib/cherrypy/middleware.py
Labels: automerge, changelog/no-changelog

#1803 docs: update basic usage
  docs/basic_usage.rst
Labels: automerge, changelog/no-changelog, docs

#2003 tests(psycopg2): add encoding test
  .circleci/config.yml
  tests/contrib/psycopg/test_psycopg.py
  tests/snapshots/tests.contrib.psycopg.test_psycopg.test_composed_query_encoding.snap
Labels: automerge, changelog/no-changelog

#2008 riot: specify cmdargs for all pytest commands
  riotfile.py
Labels: automerge, changelog/no-changelog

#2021 ci: remove Sanic support for Python 3.6
  tox.ini
Labels: automerge, changelog/no-changelog, dev/testing

#2020 test(profiling): fix flakyness for test_ignore_profiler_gevent_task
  tests/profiling/collector/test_stack.py
Labels: automerge, changelog/no-changelog, dev/testing

#2022 chore(docs): Update deprecated env variable name
  ddtrace/contrib/django/__init__.py
Labels: automerge, changelog/no-changelog

#2023 test(writer): test writer against real API endpoint
  ddtrace/internal/writer.py
  tests/tracer/test_writer.py
Labels: automerge, changelog/no-changelog, dev/testing

#2025 test(writer): remove useless class
  tests/tracer/test_writer.py
Labels: automerge, changelog/no-changelog

#2009 feat(pprof): export MemoryHeapSampleEvent
  ddtrace/profiling/exporter/pprof.pyx
  tests/profiling/exporter/test-pprof-exporter-py2.txt
  tests/profiling/exporter/test-pprof-exporter.txt
  tests/profiling/exporter/test_pprof.py
  tests/profiling/test_main.py
Labels: changelog/no-changelog

#2033 fix black formatting on riotfile.py
  pyproject.toml
  riotfile.py
Labels: automerge, changelog/no-changelog

#2032 fix(ci): pin rsa for python 2.7
  riotfile.py
Labels: automerge, changelog/no-changelog

#2028 fix(logger): Use standard DD_TRACE_LOGGING_RATE variable
  ddtrace/internal/logger.py
  releasenotes/notes/fix-logger-standard-logging-rate-envvar-155e113deea71e85.yaml
  tests/tracer/test_logger.py
Labels: automerge

#2036 refactor(profiling/uwsgi): reusable run uwsgi for tests
  tests/contrib/uwsgi/__init__.py
  tests/profiling/test_uwsgi.py
Labels: automerge, changelog/no-changelog

#2037 Add WSGI to integration docs
  docs/integrations.rst
Labels: automerge, changelog/no-changelog, docs

#2026 refactor(writer): use the PeriodicWorkerThread started attribute
  ddtrace/internal/writer.py
Labels: automerge, changelog/no-changelog

#1993 Report tracer drop rate.
  ddtrace/constants.py
  ddtrace/internal/sma.py
  ddtrace/internal/writer.py
  tests/snapshots/test_starlette.test_table_query_snapshot.snap
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_child.snap
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_error.snap
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_fatal.snap
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_success.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_111x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_18x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_404_exceptions_21x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_111x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_18x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_21x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_111x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_18x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_21x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_111x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_18x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_21x.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include.snap
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include_21x.snap
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_table_query_snapshot.snap
  tests/snapshots/tests.contrib.psycopg.test_psycopg.test_composed_query_encoding.snap
  tests/snapshots/tests.contrib.redis.test.test_analytics_with_rate.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_analytics_with_rate.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_analytics_without_rate.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_basics.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_env_user_specified_redis_service.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_long_command.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_meta_override.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_opentracing.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_pipeline_immediate.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_pipeline_traced.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_service_precedence.snap
  tests/snapshots/tests.contrib.redis.test_redis.test_user_specified_service.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_200.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_500_py2.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_500_py3.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_chunked.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_generator_exit_ignored_in_top_level_span_snapshot_py2.snap
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_generator_exit_ignored_in_top_level_span_snapshot_py3.snap
  tests/snapshots/tests.integration.test_integration.test_filters.snap
  tests/snapshots/tests.integration.test_integration.test_multiple_traces.snap
  tests/snapshots/tests.integration.test_integration.test_sampling.snap
  tests/snapshots/tests.integration.test_integration.test_single_trace_single_span.snap
  tests/tracer/test_sma.py
  tests/tracer/test_writer.py
Labels: automerge, changelog/no-changelog

#2029 fix(sampler): ensure negative sample rate raises error, ignore sample rate of 0
  ddtrace/internal/writer.py
  ddtrace/sampler.py
  releasenotes/notes/fix-sampler_sample_rate_bug-b93ffc6036982ba8.yaml
  tests/tracer/test_sampler.py
Labels: automerge

#2040 django: fix unpatching
  ddtrace/contrib/django/patch.py
Labels: automerge, changelog/no-changelog

#2043 Update advanced_usage.rst
  docs/advanced_usage.rst
Labels: automerge, changelog/no-changelog

#2031 feat: Add support for DD_SERVICE_MAPPING
  ddtrace/settings/config.py
  ddtrace/tracer.py
  docs/configuration.rst
  releasenotes/notes/feature-service-mapping-b1c6cf37a5ad6417.yaml
  tests/tracer/test_global_config.py
  tests/tracer/test_tracer.py
Labels: automerge

#2044 refactor: move agent variables to separate module
  ddtrace/internal/agent.py
  ddtrace/tracer.py
  releasenotes/notes/tracer-200a66ebb04f6cb0.yaml
  tests/profiling/test_profiler.py
  tests/tracer/test_agent.py
Labels: automerge, changelog/no-changelog

#2041 refactor(tracer): separate dogstatsd for AgentWriter and RuntimeWorker
  ddtrace/internal/dogstatsd.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/tracer.py
  tests/__init__.py
  tests/commands/ddtrace_run_dogstatsd.py
  tests/tracer/runtime/test_runtime_metrics.py
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#2056 django: use configure for agent settings
  ddtrace/contrib/django/conf.py
  tests/contrib/django/test_django_migration.py
Labels: automerge, changelog/no-changelog

#2055 agent: provide default constants
  ddtrace/internal/agent.py
Labels: automerge, changelog/no-changelog

#2049 writer: remove falsy spans check
  ddtrace/internal/writer.py
Labels: automerge, changelog/no-changelog

#2050 fix(writer): remove duplicate http.requests metric
  ddtrace/internal/writer.py
  tests/integration/test_integration.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#2051 writer: enable flush_queue to raise
  ddtrace/internal/writer.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#2052 refactor: use AgentWriter for debug info collecting
  ddtrace/internal/debug.py
  tests/integration/test_debug.py
Labels: changelog/no-changelog

#2054 tests: add partial configure test case
  tests/tracer/test_tracer.py
Labels: automerge, changelog/no-changelog

#2046 Add WSGI interface tests for Django integration
  tests/contrib/django/test_django.py
Labels: automerge, changelog/no-changelog

#2053 refactor: remove api module
  ddtrace/api.py
  ddtrace/internal/writer.py
  tests/tracer/test_api.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#2058 refactor: add distributed tracing context activator helper in trace_utils
  ddtrace/contrib/trace_utils.py
  tests/tracer/test_trace_utils.py
Labels: automerge, changelog/no-changelog

#2057 tests: remove usage of internal writer attributes
  tests/__init__.py
  tests/commands/ddtrace_run_hostname.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/tornado/test_config.py
  tests/integration/test_integration.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
Labels: automerge, changelog/no-changelog

#2059 refactor: use trace_utils distributed header extraction in django
  ddtrace/contrib/django/patch.py
Labels: automerge, changelog/no-changelog

#2060 dogpile: auto-instrument and add docs
  ddtrace/contrib/dogpile_cache/__init__.py
  ddtrace/monkey.py
  docs/index.rst
  docs/integrations.rst
  docs/spelling_wordlist.txt
  releasenotes/notes/dogpile-cc205f8abf149360.yaml
Labels: automerge, changelog/no-changelog

#2063 httplib: use agent_url instead of internal attributes
  ddtrace/contrib/httplib/patch.py
Labels: automerge, changelog/no-changelog

#1848 refactor: use url instead of hostname, port, uds, https
  ddtrace/internal/writer.py
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/profiler.py
  ddtrace/tracer.py
  tests/__init__.py
  tests/integration/test_integration.py
  tests/profiling/test_profiler.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#2062 fix(profiling): handle failed collectors
  ddtrace/profiling/profiler.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog

#2064 fix(writer): logging request timing
  ddtrace/internal/writer.py
  tests/__init__.py
  tests/integration/test_integration.py
Labels: automerge, changelog/no-changelog
