Repository DataDog/dd-trace-py, pull requests merged in 2022-08, with the labels that each got.

#4020 fix(tests/tox): updated gevent in tox config
  tox.ini
Labels: changelog/no-changelog

#4021 chore(ci): added python 3.11-dev to dev docker image
  docker/.python-version
  docker/Dockerfile.buster
Labels: changelog/no-changelog

#4023 chore(tracer): improve span sampling rules typing
  ddtrace/internal/sampling.py
  tests/tracer/test_processors.py
  tests/tracer/test_single_span_sampling_rule.py
Labels: changelog/no-changelog

#4027 chore(tests): remove typing_extensions version specification
  setup.py
Labels: changelog/no-changelog

#4024 fix(tests/django): update django snapshot test
  tests/contrib/django/test_django_snapshots.py
Labels: changelog/no-changelog

#3950 chore(internal): send span sampled payload
  ddtrace/internal/processor/trace.py
  ddtrace/internal/sampling.py
  tests/integration/test_trace_stats.py
  tests/snapshots/tests.integration.test_trace_stats.test_single_span_sampling[sampling_rule0].json
  tests/snapshots/tests.integration.test_trace_stats.test_single_span_sampling[sampling_rule0]_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_single_span_sampling[sampling_rule1].json
  tests/snapshots/tests.integration.test_trace_stats.test_single_span_sampling[sampling_rule1]_tracestats.json
Labels: changelog/no-changelog

#4016 chore(telemetry): move telemetry tests
  .circleci/config.yml
  riotfile.py
  tests/telemetry/__init__.py
  tests/telemetry/test_data.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#4031 chore(flask): update fix release note
  releasenotes/notes/fix-attribute-error-in-flask-2.2.0-94524c33b005d48a.yaml
Labels: changelog/no-changelog

#4014 fix(pytest): fix encoding of some objects in pytest test parameters
  ddtrace/contrib/pytest/plugin.py
  releasenotes/notes/fix-pytest-test-parameter-encoding-90f3806f19438ead.yaml
  tests/contrib/pytest/test_pytest.py
Labels: bug

#4035 chore(setup/pypi): update pypi.org Project links
  setup.py
Labels: changelog/no-changelog

#3977 feat(internal): environment config for span sampling
  ddtrace/internal/sampling.py
  ddtrace/tracer.py
  tests/tracer/test_single_span_sampling_rules.py
Labels: changelog/no-changelog

#4043 chore(mergify): auto-update approved PRs
  .mergify.yml
Labels: changelog/no-changelog

#4011 ci(profiles): reduce Django sampling exposure
  scripts/profiles/django-simple/run.sh
Labels: changelog/no-changelog

#4017 feat(graphql): add tags to graphql spans
  ddtrace/contrib/graphql/patch.py
  tests/contrib/graphql/test_graphql.py
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_error.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_execute_with_middleware.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_v2_with_document.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_with_traced_resolver.json
Labels: changelog/no-changelog

#3996 chore(internal): ensure module watchdog propagation
  ddtrace/internal/module.py
  tests/internal/test_module.py
Labels: changelog/no-changelog

#4029 feat(telemetry/appsec): add appsec to telemetry payload
  ddtrace/internal/telemetry/data.py
  tests/telemetry/test_data.py
Labels: changelog/no-changelog

#4034 test(debugging): mark flaky poller test on Python 2
  tests/debugging/probe/test_poller.py
Labels: changelog/no-changelog

#3982 chore(ci): refactor telemetry tests to use the test agent
  ddtrace/internal/telemetry/writer.py
  tests/conftest.py
  tests/telemetry/conftest.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog

#4053 fix(graphql): rename service entry span
  ddtrace/contrib/graphql/patch.py
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_error.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_v2_with_document.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_with_traced_resolver.json
Labels: changelog/no-changelog

#3696 chore(graphene): validate graphene support
  .circleci/config.yml
  docs/index.rst
  docs/spelling_wordlist.txt
  releasenotes/notes/add-graphene-support-b189f0265d629963.yaml
  riotfile.py
  tests/contrib/graphene/__init__.py
  tests/contrib/graphene/test_graphene.py
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_execute.json
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_execute_with_resolvers.json
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_failing_execute.json
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_failing_execute_v2.json
Labels: changelog/no-changelog

#3979 chore(telemetry): add support for app-heartbeat telemetry events
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#4063 test(telemetry): replace broken heartbeat test
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#4060 test(flask): run flask snapshot tests with werkzeug instead of uwsgi
  riotfile.py
  tests/contrib/flask/test_flask_snapshot.py
Labels: changelog/no-changelog

#4061 chore(context): update_tags only adds tags with new keys
  ddtrace/context.py
  tests/integration/test_integration_snapshots.py
  tests/snapshots/tests.integration.test_integration_snapshots.test_tracetagsprocessor_only_adds_new_tags.json
Labels: changelog/no-changelog

#4049 chore(internal): handle additional attributes in module watchdog
  ddtrace/internal/module.py
Labels: changelog/no-changelog

#4042 feat(internal): span sampling file config envar
  ddtrace/constants.py
  ddtrace/internal/sampling.py
  tests/tracer/test_single_span_sampling_rules.py
Labels: changelog/no-changelog

#4071 feat(asm/python): support xml content in body detection
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/pylons/middleware.py
  releasenotes/notes/feat-detect-attack-on-xml-body-878215f0d3d1a64d.yaml
  setup.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/pylons/test_pylons.py
Labels: ASM

#4047 feat(perf): add set_http_meta scenario
  .gitignore
  benchmarks/bm/utils.py
  benchmarks/set_http_meta/config.yaml
  benchmarks/set_http_meta/scenario.py
  benchmarks/span/scenario.py
Labels: changelog/no-changelog, ASM

#4085 ci: pin setuptools
  pyproject.toml
Labels: changelog/no-changelog

#4082 feat(asm): fix segmentation fault parsing JSON in Python2
  ddtrace/appsec/_ddwaf.pyx
  releasenotes/notes/asm-fix-python-2-error-reading-ddwaf-rules-d3653031f2ba84ba.yaml
  tests/appsec/test_processor.py
Labels: ASM

#3987 feat: collect user agent in normalized span tag `http.useragent`
  ddtrace/contrib/trace_utils.py
  ddtrace/ext/http.py
  releasenotes/notes/feat-collect-user-agent-630b2c10f83ac063.yaml
  tests/contrib/aiohttp_jinja2/test_aiohttp_jinja2.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_snapshots.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/flask/test_flask_snapshot.py
  tests/contrib/httpx/test_httpx.py
  tests/contrib/pylons/test_pylons.py
  tests/contrib/pyramid/test_pyramid.py
  tests/snapshots/tests.contrib.aiohttp_jinja2.test_aiohttp_jinja2.test_template_rendering_snapshot_patched_server[True].json
  tests/snapshots/tests.contrib.aiohttp_jinja2.test_aiohttp_jinja2.test_template_rendering_snapshot_patched_server[pyloop-True].json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_3x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_traced_simple_app.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_3x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_disabled_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_disabled_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_disabled_3x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_enabled_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_enabled_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_enabled_3x.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_subapp_no_aggregate_snapshot.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_subapp_snapshot.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_table_query_snapshot.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200_220.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream_220.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_configure_global_service_name_env.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_configure_service_name.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_configure_service_name_env.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_get_200.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_get_500.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_request_headers.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_split_by_domain.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_trace_query_string.json
  tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint.json
  tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint[ddtrace-run_pserve_tests_contrib_pyramid_pserve_app_development.ini].json
  tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint[ddtrace-run_python_tests_contrib_pyramid_app_app.py].json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http_pre_21.9.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors_pre_21.9.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_subapp_no_aggregate_snapshot.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_subapp_snapshot.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_table_query_snapshot.json
  tests/tracer/test_trace_utils.py
Labels: ASM

#4059 feat(rediscluster): rediscluster adding service name config option
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/rediscluster/__init__.py
  ddtrace/contrib/rediscluster/patch.py
  releasenotes/notes/rediscluster-add-service-name-config-option-cebcd5d2c408f65b.yaml
  tests/contrib/rediscluster/test.py
Labels: changelog/no-changelog

#4083 chore(internal): better support for Python legacy versions in ModuleWatchdog
  ddtrace/internal/module.py
  tests/internal/test_module.py
Labels: changelog/no-changelog

#4081 test(debugging): reduce uploader test flakiness
  tests/debugging/test_uploader.py
Labels: changelog/no-changelog

#4064 chore(span_sampling): add jsonschema for span sampling
  ddtrace/internal/sampling.py
  setup.py
  tests/internal/test_packages.py
  tests/tracer/test_single_span_sampling_rules.py
Labels: changelog/no-changelog

#4080 feat(tests/httplib): use local httpbin container
  .circleci/config.yml
  riotfile.py
  tests/contrib/httplib/test_httplib.py
  tox.ini
Labels: changelog/no-changelog, ASM

#4057 chore(perf): add set_http_meta with obfuscation data benchmark scenario
  benchmarks/set_http_meta/config.yaml
  benchmarks/set_http_meta/scenario.py
Labels: changelog/no-changelog, ASM

#4109 chore(tracer): remove redundant slot in DatadogSampler
  ddtrace/sampler.py
Labels: changelog/no-changelog

#4098 chore: enable ModuleWatchdog globally
  ddtrace/__init__.py
  tests/internal/test_module.py
  tests/profiling/collector/test_threading.py
  tests/profiling/collector/test_traceback.py
Labels: changelog/no-changelog

#4119 fix(profiling): fix potential crash in frame converter
  ddtrace/profiling/collector/_memalloc_tb.c
Labels: changelog/no-changelog

#4070 chore(gevent): run after-in-child hooks after reinit
  ddtrace/internal/forksafe.py
  riotfile.py
  tests/tracer/test_forksafe.py
Labels: changelog/no-changelog

#4120 ci: update github action runner image to ubuntu-latest
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#4114 fix(asm): fix reading wsgi input
  benchmarks/bm/utils.py
  benchmarks/flask_simple/app.py
  benchmarks/flask_simple/config.yaml
  benchmarks/flask_simple/gunicorn.conf.py
  benchmarks/flask_simple/scenario.py
  benchmarks/flask_simple/utils.py
  benchmarks/set_http_meta/scenario.py
  ddtrace/contrib/flask/patch.py
  releasenotes/notes/asm-fix-reset-wsgi-input-035e0a7d917af2b2.yaml
  tests/contrib/django/django1_app/urls.py
  tests/contrib/django/django_app/urls.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/views.py
  tests/contrib/flask/app.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/pylons/app/controllers/root.py
  tests/contrib/pylons/app/router.py
  tests/contrib/pylons/test_pylons.py
Labels: ASM

#4066 feat(asm/python): add user information to traces
  ddtrace/contrib/trace_utils.py
  ddtrace/ext/user.py
  releasenotes/notes/asm-add-user-information-to-traces-27658759829e7782.yaml
  tests/contrib/django/django1_app/urls.py
  tests/contrib/django/django_app/urls.py
  tests/contrib/django/test_django.py
  tests/contrib/django/views.py
  tests/contrib/flask/app.py
  tests/contrib/flask/test_flask_snapshot.py
  tests/contrib/pylons/app/controllers/root.py
  tests/contrib/pylons/app/router.py
  tests/contrib/pylons/test_pylons.py
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_get_user.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_get_user_220.json
  tests/tracer/test_tracer.py
Labels: ASM

#4134 fix(logging): account for placeholder in get_logger
  ddtrace/internal/logger.py
  tests/tracer/test_logger.py
Labels: changelog/no-changelog

#4140 chore(debugging): fix ejection
  ddtrace/debugging/_debugger.py
  ddtrace/internal/injection.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog

#4051 chore(debugging): clean up snapshot duration field
  ddtrace/debugging/_async.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_snapshot/collector.py
  ddtrace/debugging/_snapshot/model.py
  tests/debugging/py35/test_async.py
  tests/debugging/test_debugger.py
  tests/submod/stuff.py
Labels: changelog/no-changelog

#3409 fix(aiohttp_jinja2): pass app_key to get_env
  ddtrace/contrib/aiohttp_jinja2/patch.py
  releasenotes/notes/aiohttp_jinja2-fa35ccf6fc42814c.yaml
Labels: Stale

#4132 feat(asm/python): propagate user ID
  ddtrace/constants.py
  ddtrace/context.py
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/asm-propagate-user-id-1b1f596f7442fd34.yaml
  tests/tracer/test_tracer.py
Labels: ASM

#4146 chore(debugging): ignore functions with no __code__
  ddtrace/debugging/_function/discovery.py
Labels: changelog/no-changelog

#4068 feat(ddtrace): add container auto injection
  .github/workflows/lib-injection.yml
  .github/workflows/system-tests.yml
  lib-injection/Dockerfile
  lib-injection/copy-lib.sh
  lib-injection/sitecustomize.py
  tests/lib-injection/Dockerfile
  tests/lib-injection/django_app.py
Labels: changelog/no-changelog
