Repository DataDog/dd-trace-py, pull requests merged in 2022-09, with the labels that each got.

#4144 feat(asm): configure ddwaf data obfuscator
  ddtrace/appsec/CMakeLists.txt
  ddtrace/appsec/_ddwaf.pyx
  ddtrace/appsec/_libddwaf.pxd
  ddtrace/appsec/processor.py
  docs/configuration.rst
  docs/spelling_wordlist.txt
  releasenotes/notes/asm-configure-sensitive-data-obfuscator-4bf70dcccb9f6350.yaml
  tests/appsec/test_processor.py
Labels: ASM

#4128 feat(telemetry): heartbeat optimization
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog

#4147 refactor(profiling): remove lock from _ThreadLink
  ddtrace/profiling/_threading.pyx
Labels: changelog/no-changelog

#4154 chore(lib-injection): update system-tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#4093 chore(internal): resolve incorrect import resolution from Cython
  ddtrace/internal/_encoding.pyx
  pyproject.toml
Labels: changelog/no-changelog

#4148 feat(ASM): support in-app WAF metrics report
  ddtrace/appsec/_ddwaf.pyx
  ddtrace/appsec/_libddwaf.pxd
  ddtrace/appsec/processor.py
  ddtrace/constants.py
  releasenotes/notes/asm-support-in-app-waf-metrics-report-4528e2b2574268cd.yaml
  tests/appsec/rules-with-2-errors.json
  tests/appsec/rules-with-3-errors.json
  tests/appsec/test_processor.py
  tests/contrib/django/test_django_snapshots.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors_py2.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors_py3.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled_attack.json
Labels: ASM

#4156 chore: move forksafe tests to the internal test suite
  riotfile.py
  tests/internal/test_forksafe.py
Labels: changelog/no-changelog

#4133 chore(internal): add RCM client
  ddtrace/internal/remoteconfig/__init__.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
  ddtrace/internal/utils/time.py
  setup.py
  tests/internal/test_remoteconfig.py
Labels: changelog/no-changelog

#4160 chore(refactor): improve performance set_http_meta
  ddtrace/internal/_context.py
  ddtrace/span.py
Labels: changelog/no-changelog, ASM

#4145 feat(asm): collect http.client_ip
  benchmarks/bm/utils.py
  benchmarks/set_http_meta/config.yaml
  benchmarks/set_http_meta/scenario.py
  ddtrace/constants.py
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/trace_utils.py
  ddtrace/ext/http.py
  docs/spelling_wordlist.txt
  releasenotes/notes/asm-collect-header-ip-494f489b1778b6ed.yaml
  setup.py
  tests/appsec/test_processor.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
  tests/tracer/test_trace_utils.py
Labels: ASM

#4171 chore: update lib injection system-tests branch
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#4162 chore(refactor): memoize get header tag name
  ddtrace/internal/utils/http.py
  ddtrace/settings/config.py
Labels: changelog/no-changelog, ASM

#4158 chore(debugging): register with RCM
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/poller.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_remoteconfig.py
  riotfile.py
  tests/debugging/mocking.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/test_debugger.py
  tests/debugging/test_remoteconfig.py
Labels: changelog/no-changelog

#4172 chore(asm): refactor tests
  tests/appsec/test_processor.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors_py3.json
Labels: changelog/no-changelog, ASM

#4176 chore(lib-injection): use busybox as base image
  lib-injection/Dockerfile
Labels: changelog/no-changelog

#3991 ci(debugging): add exploration testing
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/__init__.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
  tests/debugging/exploration/preload.py
  tests/debugging/exploration/sitecustomize.py
Labels: changelog/no-changelog

#4041 chore(ci): enabling partial flushing by default
  ddtrace/tracer.py
  docs/configuration.rst
  tests/commands/test_runner.py
  tests/contrib/asyncio/test_tracer_safety.py
  tests/integration/test_integration.py
Labels: do-not-merge, changelog/no-changelog

#4174 test(profiling): increase verbosity and assert debug data
  tests/profiling/collector/test_stack_asyncio.py
  tox.ini
Labels: changelog/no-changelog

#4159 feat(lib-injection): add image deploy jobs
  .github/workflows/lib-injection.yml
  .gitlab-ci.yml
Labels: changelog/no-changelog

#4178 chore(mergifyio): use consistent conflict label
  .mergify.yml
Labels: changelog/no-changelog

#4175 test(profiling): make sure we have sample before terminating process
  tests/profiling/_test_multiprocessing.py
Labels: changelog/no-changelog

#4163 fix(asm/refactor): avoid store context data if appsec is disabled
  ddtrace/contrib/trace_utils.py
  tests/appsec/test_processor.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/pylons/test_pylons.py
Labels: changelog/no-changelog, ASM

#4180 chore(debugging): fix exploration debugger import
  tests/debugging/exploration/debugger.py
  tests/debugging/exploration/test_bootstrap.py
Labels: changelog/no-changelog

#4185 ci(boto): remove test_kinesis_put_records_base64_exceeds_max_size
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#3980 feat(asm): redact sensitive querystrings in http.url
  ddtrace/contrib/aiohttp/patch.py
  ddtrace/contrib/trace_utils.py
  ddtrace/internal/utils/http.py
  ddtrace/settings/config.py
  docs/advanced_usage.rst
  docs/configuration.rst
  releasenotes/notes/redact-sensitive-querystrings-in-http-url-522461022535a1e2.yaml
  tests/contrib/asgi/test_asgi.py
  tests/contrib/bottle/test.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/molten/test_molten.py
  tests/contrib/pyramid/utils.py
  tests/contrib/sanic/test_sanic.py
  tests/contrib/starlette/test_starlette.py
  tests/contrib/tornado/test_tornado_web.py
  tests/tracer/test_env_vars.py
  tests/tracer/test_http.py
  tests/tracer/test_trace_utils.py
  tests/utils.py
Labels: ASM

#4191 chore(telemetry): add telemetry release note
  releasenotes/notes/telemetry-release-note-1-5-2376710f62cba11b.yaml
Labels: changelog/no-changelog

#4184 ci(system-tests): add python integration unit tests to ci
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#4190 feat(django): set `usr.id` tag by default if `request.user` is authenticated
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/django-set-usr-id-by-default-b99c0f3e6cf530a2.yaml
  tests/contrib/django/test_django.py
  tests/tracer/test_tracer.py
Labels: ASM

#4206 refactor(profiling): remove unused import from stack collector
  ddtrace/profiling/collector/stack.pyx
Labels: changelog/no-changelog

#4208 fix(flask): revert trace streamed responses
  ddtrace/contrib/flask/patch.py
  releasenotes/notes/flask-support-response-streamig-d3aafc8fa1e3605d.yaml
  tests/contrib/flask/test_errorhandler.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/flask/test_hooks.py
  tests/contrib/flask/test_request.py
  tests/contrib/flask/test_static.py
  tests/contrib/flask/test_views.py
  tests/contrib/flask_autopatch/test_flask_autopatch.py
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200_220.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_get_user.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_get_user_220.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream_220.json
Labels: changelog/no-changelog

#4213 chore(docs): clarify django in-code docs
  ddtrace/contrib/django/__init__.py
Labels: changelog/no-changelog

#4221 fix(asm): change ipaddress backport library
  docs/spelling_wordlist.txt
  releasenotes/notes/asm-fix-ipaddress-backport-lib-4684ce71e63459e7.yaml
  setup.py
  tests/tracer/test_trace_utils.py
Labels: ASM

#4157 feat(asm): bump libddwaf to 1.5.1
  ddtrace/appsec/CMakeLists.txt
  ddtrace/appsec/_ddwaf.pyx
  ddtrace/appsec/_libddwaf.pxd
  ddtrace/appsec/processor.py
  ddtrace/appsec/rules.json
  releasenotes/notes/asm-upgrade-libddwaf-4a9eb4b59afef8d9.yaml
  setup.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled_attack.json
Labels: ASM

#4230 chore(asm): disable libddwaf tests compilation at build time
  ddtrace/appsec/CMakeLists.txt
Labels: changelog/no-changelog

#4238 fix(starlette): updated snapshot tests with latest starlette version
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#4239 chore(asm): revert bump libddwaf to 1.5.1
  ddtrace/appsec/CMakeLists.txt
  ddtrace/appsec/_ddwaf.pyx
  ddtrace/appsec/_libddwaf.pxd
  ddtrace/appsec/processor.py
  ddtrace/appsec/rules.json
  releasenotes/notes/asm-upgrade-libddwaf-4a9eb4b59afef8d9.yaml
  setup.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog

#4218 chore(telemetry): update telemetry writer interval
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#4229 feat(asm): 1-click activation with RCM
  ddtrace/appsec/remoteconfiguration.py
  ddtrace/constants.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/constants.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  releasenotes/notes/asm-1-click-activation-with-RCM-6a2431949768b73b.yaml
  riotfile.py
  setup.py
  tests/appsec/test_remoteconfiguration.py
  tests/internal/test_remoteconfig.py
Labels: ASM

#4245 chore(ci): pin sanic and sanic-testing version
  riotfile.py
Labels: changelog/no-changelog

#4244 chore(asm): make remoteconfiguration module internal
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/tracer.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#4243 feat(attrs): pin attrs dependency to version `>=20`
  docs/spelling_wordlist.txt
  releasenotes/notes/pin-attrs-v20-76e8beccac964920.yaml
  riotfile.py
  setup.py
Labels: ASM

#4200 feat(tracing): send redacted query strings by default in http.url with env vars to disable it
  ddtrace/contrib/aiohttp/patch.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/httpx/patch.py
  ddtrace/contrib/requests/patch.py
  ddtrace/contrib/trace_utils.py
  ddtrace/contrib/urllib3/patch.py
  ddtrace/settings/config.py
  ddtrace/settings/integration.py
  docs/configuration.rst
  releasenotes/notes/asm-tag-http-query-string-c7faba44b1402215.yaml
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/bottle/test.py
  tests/contrib/dbapi/test_dbapi.py
  tests/contrib/falcon/test_suite.py
  tests/contrib/flask/test_request.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/pyramid/utils.py
  tests/contrib/sanic/test_sanic.py
  tests/contrib/tornado/test_safety.py
  tests/contrib/tornado/test_tornado_web.py
  tests/snapshots/tests.contrib.httpx.test_httpx.test_request_headers.json
  tests/tracer/test_env_vars.py
  tests/tracer/test_trace_utils.py
  tests/utils.py
Labels: ASM
