Repository DataDog/dd-trace-py, pull requests merged in 2022-03, with the labels that each got.

#3347 docs: fix deprecation guide in release notes
  docs/advanced_usage.rst
  releasenotes/notes/release-1.0-758fc917e40d7eb3.yaml
Labels: changelog/no-changelog, v1.0

#3357 chore(aiohttp): add snapshot test
  .circleci/config.yml
  tests/contrib/aiohttp/test_templates.py
  tests/snapshots/tests.contrib.aiohttp.test_templates.test_template_rendering_snapshot.json
  tests/snapshots/tests.contrib.aiohttp.test_templates.test_template_rendering_snapshot[pyloop].json
Labels: changelog/no-changelog

#3359 docs: fix missing ref
  docs/advanced_usage.rst
Labels: changelog/no-changelog, v1.0

#3344 feat(tracing/internal): add shutdown method
  ddtrace/internal/processor/__init__.py
  ddtrace/internal/processor/trace.py
Labels: changelog/no-changelog

#3350 chore!: remove deprecated constants
  ddtrace/constants.py
  ddtrace/internal/compat.py
  releasenotes/notes/remove-constants-deprecations-023fbd010e7c767c.yaml
  setup.py
  tests/pep562_test/__init__.py
  tests/tracer/test_compat.py
  tests/tracer/test_constants.py
Labels: v1.0

#3363 fix(docs): fix broken docs builds for 1.0 branch
  docs/_release_notes_all.rst
  docs/release_notes.rst
  releasenotes/config.yaml
  releasenotes/notes/deprecate-span-get-set-meta-c6fb2528d198414c.yaml
  releasenotes/notes/remove-span-get-set-meta-c6fb2528d198414d.yaml
Labels: changelog/no-changelog, v1.0

#3361 refactor(tracer): use span processor factory
  ddtrace/tracer.py
  tests/appsec/test_processor.py
Labels: changelog/no-changelog

#3375 chore(ci): run nightly builds of 0.x and 1.x branches
  .circleci/config.yml
Labels: changelog/no-changelog

#3382 chore(vendor): fix psutil getpagesize() for newer macos
  ddtrace/vendor/psutil/_psutil_osx.c
Labels: changelog/no-changelog

#3412 docs(aioredis): fix aioredis typo
  ddtrace/contrib/aioredis/__init__.py
Labels: changelog/no-changelog

#3400 chore: deprecate Span.to_dict
  ddtrace/span.py
  releasenotes/notes/deprecate-span-todict-9fc94985c82f12c5.yaml
Labels: v1.0

#3402 feat(tracing): add Span.get_tags and Span.get_metrics
  ddtrace/span.py
  releasenotes/notes/add-span-get-tags-metrics-7969ba7843dcc24d.yaml
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/aredis/test_aredis.py
  tests/contrib/bottle/test.py
  tests/contrib/celery/test_utils.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/django/test_django.py
  tests/contrib/falcon/test_suite.py
  tests/contrib/flask/test_blueprint.py
  tests/contrib/flask/test_errorhandler.py
  tests/contrib/flask/test_flask_helpers.py
  tests/contrib/flask/test_hooks.py
  tests/contrib/flask/test_middleware.py
  tests/contrib/flask/test_request.py
  tests/contrib/flask/test_signals.py
  tests/contrib/flask/test_template.py
  tests/contrib/flask/test_views.py
  tests/contrib/flask_autopatch/test_flask_autopatch.py
  tests/contrib/flask_cache/test.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/mariadb/test_mariadb.py
  tests/contrib/molten/test_molten.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysqldb.py
  tests/contrib/pylons/test_pylons.py
  tests/contrib/pymysql/test_pymysql.py
  tests/contrib/pyramid/utils.py
  tests/contrib/redis/test_redis.py
  tests/contrib/requests/test_requests.py
  tests/contrib/sqlalchemy/test_patch.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/urllib3/test_urllib3.py
  tests/contrib/yaaredis/test_yaaredis.py
  tests/tracer/test_encoders.py
  tests/tracer/test_global_config.py
  tests/tracer/test_processors.py
  tests/tracer/test_span.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
  tests/utils.py
Labels: v1.0

#3416 fix(mypy): fix a couple of mypy issues
  ddtrace/internal/compat.py
  ddtrace/internal/utils/cache.py
Labels: changelog/no-changelog

#3268 refactor(profiling): split lock profiling in two parts
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/threading.py
  ddtrace/profiling/exporter/pprof.pyi
  ddtrace/profiling/exporter/pprof.pyx
  ddtrace/profiling/profiler.py
  tests/profiling/collector/test_threading.py
  tests/profiling/collector/test_threading_asyncio.py
  tests/profiling/exporter/test_pprof.py
  tests/profiling/simple_program_fork.py
Labels: changelog/no-changelog

#3424 chore: keep source for python
  Dockerfile.buster
Labels: changelog/no-changelog

#3411 chore!: remove Span.to_dict
  ddtrace/internal/encoding.py
  ddtrace/span.py
  releasenotes/notes/remove-span-todict-98117485031335cd.yaml
  tests/benchmarks/test_encoding.py
  tests/tracer/test_encoders.py
  tests/tracer/test_span.py
Labels: v1.0

#3430 chore(tests): update brittle warning log assertion
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#3437 fix(celery): remove deprecated Pin.app
  ddtrace/contrib/celery/app.py
  releasenotes/notes/remove-app-arg-from-celery-instrumentation-4742d04f4e6474d2.yaml
Labels: v1.0

#3440 fix(tracing): disable connection reuse by default
  ddtrace/internal/writer.py
  releasenotes/notes/keep-alive-b5ec5febb435daad.yaml
Labels: changelog/no-changelog

#3449 fix(tracing/aiohttp): catch errors when trying to patch aiohttp_jinja2
  ddtrace/contrib/aiohttp/patch.py
Labels: changelog/no-changelog

#3451 chore: remove sirun
  Dockerfile.buster
Labels: changelog/no-changelog

#3383 test: add marker for running tests in subprocess
  conftest.py
  tests/conftest.py
  tests/contrib/gevent/test_monkeypatch.py
  tests/contrib/httpx/test_httpx.py
  tests/contrib/mariadb/test_mariadb.py
  tests/contrib/snowflake/test_snowflake.py
  tests/integration/test_debug.py
  tests/integration/test_integration.py
  tests/runtime/test_runtime_metrics_api.py
  tests/tracer/telemetry/test_data.py
  tests/tracer/test_atexit.py
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog

#3468 revert(tracer): reusing connections (#2999, #3440)
  ddtrace/internal/writer.py
  releasenotes/notes/keep-alive-b5ec5febb435daad.yaml
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#3368 chore(docs): add custom directive to dynamically generate release notes
  docs/conf.py
  docs/release_notes.rst
  mypy.ini
  riotfile.py
Labels: changelog/no-changelog

#3469 revert(tracer): reusing connections (#2999)
  ddtrace/internal/writer.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#3461 docs: clarify asyncio support
  ddtrace/contrib/asyncio/__init__.py
  docs/advanced_usage.rst
Labels: changelog/no-changelog

#3470 fix(telemetry): update compatible field in telemetry payload
  ddtrace/internal/telemetry/writer.py
  tests/tracer/telemetry/test_writer.py
Labels: changelog/no-changelog

#3460 chore(profiling): remove unused import in collector._task
  ddtrace/profiling/collector/_task.pyx
Labels: changelog/no-changelog

#3438 chore: bump python versions to 3.10.3 3.9.11 3.8.13 3.7.13
  Dockerfile.buster
Labels: changelog/no-changelog

#3471 fix(telemetry): ensure integrations are queued on startup
  ddtrace/internal/telemetry/writer.py
  tests/tracer/telemetry/test_data.py
  tests/tracer/telemetry/test_writer.py
Labels: changelog/no-changelog

#3472 feat(telemetry): add integrations to app-started payload
  ddtrace/internal/telemetry/writer.py
  tests/tracer/telemetry/test_writer.py
Labels: changelog/no-changelog

#3478 test: pin MarkupSafe dependency
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#3490 chore: pin click to fix incompatibility
  riotfile.py
Labels: changelog/no-changelog

#3484 fix(profiling): copy greenlet list before iterating
  ddtrace/profiling/collector/_task.pyx
Labels: changelog/no-changelog

#3454 ci: add .python-version for pyenv
  docker/.python-version
  docker/Dockerfile.buster
Labels: changelog/no-changelog

#3488 ci: dockerfile optimizations
  docker/Dockerfile.buster
Labels: changelog/no-changelog

#3491 chore: fix __slots__ inheritance
  .circleci/config.yml
  ddtrace/internal/logger.py
  ddtrace/sampler.py
  hooks/pre-commit/run-slotscheck.sh
  hooks/scripts/run-slotscheck.sh
  pyproject.toml
  riotfile.py
Labels: changelog/no-changelog

#3508 fix(tracing): add span processors shutdown
  ddtrace/internal/processor/__init__.py
  ddtrace/internal/processor/trace.py
  ddtrace/tracer.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog
