Repository DataDog/dd-trace-py, pull requests merged in 2022-10, with the labels that each got.

#4252 chore(gevent): disable gevent hub reinit
  ddtrace/internal/forksafe.py
  tests/internal/test_forksafe.py
Labels: changelog/no-changelog

#4233 docs(versioning): outline bug/security fix backporting
  docs/versioning.rst
Labels: changelog/no-changelog

#4271 ci(codespell): ignore ddwaf header
  riotfile.py
Labels: changelog/no-changelog

#4277 chore(spelling): add backported to spelling_wordlist
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog

#4262 ci(sanic): update test suite to run with sanic v22.9
  riotfile.py
  tests/contrib/sanic/run_server.py
  tests/contrib/sanic/test_sanic_server.py
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http_pre_21.9.json
Labels: changelog/no-changelog

#4257 fix(ci): pin importlib_metadata<5.0.0
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#4232 test(debugging): include-list and collect elusive modules in exploration tests
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
Labels: changelog/no-changelog

#4285 chore(ci): dynamic listing of python interpreters for riot test suites in circleci
  .circleci/config.yml
  scripts/tested_pythons
Labels: changelog/no-changelog

#4295 Revert "feat: support w3c trace context"
  ddtrace/internal/constants.py
  ddtrace/propagation/http.py
  docs/spelling_wordlist.txt
  releasenotes/notes/add-w3c-traceparent-propagation-789324b2e1326f0e.yaml
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#4248 chore(debugging): evaluate condition before rate limiter
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_snapshot/collector.py
  tests/debugging/snapshot/test_collector.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog

#4301 chore(coverage): exclude TYPE_CHECKING from coverage
  ddtrace/appsec/processor.py
  ddtrace/context.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/asyncpg/patch.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/flask_cache/tracers.py
  ddtrace/contrib/graphql/patch.py
  ddtrace/contrib/httpx/patch.py
  ddtrace/contrib/trace_utils.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/ext/aws.py
  ddtrace/filters.py
  ddtrace/internal/_context.py
  ddtrace/internal/debug.py
  ddtrace/internal/encoding.py
  ddtrace/internal/processor/stats.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/internal/sampling.py
  ddtrace/internal/writer.py
  ddtrace/opentracer/helpers.py
  ddtrace/opentracer/span.py
  ddtrace/pin.py
  ddtrace/profiling/exporter/__init__.py
  ddtrace/sampler.py
  tests/contrib/sqlite3/test_sqlite3.py
  tests/tracer/test_memory_leak.py
Labels: changelog/no-changelog, ASM

#4290 chore(debugging): include container ID in payload header
  ddtrace/debugging/_uploader.py
Labels: changelog/no-changelog

#4300 fix(deps): only require ipaddress on python<3.7
  setup.py
Labels: changelog/no-changelog

#4302 chore(internal): add callonce decorator in cache utils
  ddtrace/internal/utils/cache.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog

#4310 chore(dbm): vendor sqlcommenter generate
  ddtrace/vendor/__init__.py
  ddtrace/vendor/sqlcommenter/__init__.py
Labels: changelog/no-changelog

#4316 fix(asm): only report actor.ip on attack
  ddtrace/appsec/processor.py
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/asm-fix-ipaddress-actorip-only-on-attack-c118a0560c0c0119.yaml
  tests/appsec/test_processor.py
  tests/contrib/flask/test_flask_appsec.py
  tests/tracer/test_trace_utils.py
Labels: bug, ASM

#4306 chore(dbm): add injection mode environment variable
  ddtrace/settings/database_monitoring.py
  tests/internal/test_database_monitoring.py
Labels: changelog/no-changelog

#4323 chore(ci): pin PasteDeploy for pylons, pyramid tests
  .github/workflows/test_frameworks.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#4315 feat(iast): overhead control engine (OCE) skeleton
  ddtrace/appsec/iast/__init__.py
  ddtrace/appsec/iast/overhead_control_engine.py
  ddtrace/appsec/iast/processor.py
  ddtrace/appsec/iast/reporter.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/appsec/iast/taint_sinks/weak_hash.py
  docs/configuration.rst
  tests/appsec/iast/conftest.py
  tests/appsec/iast/test_overhead_control_engine.py
  tests/appsec/iast/test_weak_hash.py
Labels: changelog/no-changelog

#4322 chore(utils): make cache utils `callonce()` compatible with py 3.11
  ddtrace/internal/compat.py
  ddtrace/internal/utils/cache.py
Labels: changelog/no-changelog

#4321 chore(dbm): generate sql comments for DBM
  ddtrace/context.py
  ddtrace/settings/database_monitoring.py
  tests/internal/test_database_monitoring.py
  tests/tracer/test_context.py
Labels: changelog/no-changelog

#4333 chore(asm): enable ip collection if not disabled and appsec is enabled
  ddtrace/contrib/trace_utils.py
  docs/spelling_wordlist.txt
  releasenotes/notes/asm-ipaddress-consider-appsec-value-9a0948896645a4b1.yaml
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
Labels: ASM

#4334 chore: update ci-app owners
  .github/CODEOWNERS
Labels: changelog/no-changelog

#4336 chore(dbm): internalize database_monitoring module
  ddtrace/settings/_database_monitoring.py
  tests/internal/test_database_monitoring.py
Labels: changelog/no-changelog

#4311 refactor(django): import from psycopg2 lazily
  ddtrace/contrib/django/patch.py
Labels: changelog/no-changelog

#4304 refactor(profiling): implement reentrant barrier to avoid loops
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_heap.c
  ddtrace/profiling/collector/_memalloc_reentrant.h
Labels: changelog/no-changelog

#4332 chore(lib-injection): add more test apps
  .github/workflows/lib-injection.yml
  .github/workflows/system-tests.yml
  tests/lib-injection/dd-lib-python-init-test-django-gunicorn/Dockerfile
  tests/lib-injection/dd-lib-python-init-test-django-gunicorn/django_app.py
  tests/lib-injection/dd-lib-python-init-test-django-uvicorn/Dockerfile
  tests/lib-injection/dd-lib-python-init-test-django-uvicorn/django_app.py
  tests/lib-injection/dd-lib-python-init-test-django/Dockerfile
  tests/lib-injection/dd-lib-python-init-test-django/django_app.py
Labels: changelog/no-changelog

#4324 chore: make issue template easier to triage
  .github/ISSUE_TEMPLATE.md
Labels: changelog/no-changelog

#4328 chore: add asm-python to CODEOWNERS
  .github/CODEOWNERS
Labels: changelog/no-changelog

#4255 ci: run pre checks and coverage with Python 3.10
  .circleci/config.yml
  ddtrace/debugging/_function/discovery.py
  riotfile.py
Labels: changelog/no-changelog

#4335 chore: remove milestone from checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#4354 chore(docs): remove unnecessary checklist items
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#4346 chore: add owner for dynamic instrumentation
  .github/CODEOWNERS
Labels: changelog/no-changelog

#4366 fix(ci): add py as a dependency
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#4369 chore(ci): add python 3.11.0 to dev docker image
  docker/.python-version
Labels: changelog/no-changelog

#4247 chore(debugging): evaluate probe condition on exit
  ddtrace/debugging/_snapshot/collector.py
  tests/debugging/test_debugger.py
  tests/submod/stuff.py
Labels: changelog/no-changelog

#4362 chore(pylons): migrate pylons tests to riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog, ASM

#4329 chore(dbm): add dbm injection tag to database spans
  ddtrace/settings/_database_monitoring.py
  tests/internal/test_database_monitoring.py
Labels: changelog/no-changelog

#4370 fix(ci): pin pynamodb to 5.2.3
  riotfile.py
Labels: changelog/no-changelog

#4375 fix(ci): pin py-cpuinfo to 8.0.0
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#4342 chore(asm): implement updated version of the ipaddress reporting RFC
  ddtrace/contrib/trace_utils.py
  docs/advanced_usage.rst
  releasenotes/notes/asm-ipaddress-rfc-part-two-a546e8453cc8163a.yaml
  tests/contrib/django/test_django_appsec.py
  tests/tracer/test_trace_utils.py
Labels: ASM

#4374 fix(ci): wait for traces to be sent in snapshot tests
  tests/contrib/httpx/test_httpx.py
  tests/utils.py
Labels: changelog/no-changelog

#4361 feat(iast): avoid duplications when report vulnerabilities
  ddtrace/appsec/iast/overhead_control_engine.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  tests/appsec/iast/test_overhead_control_engine.py
  tests/appsec/iast/test_weak_hash.py
Labels: changelog/no-changelog, ASM

#4400 chore(asm): set the DD_REMOTE_CONFIGURATION_ENABLED to false default for the beta of RCM
  ddtrace/appsec/utils.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#4388 chore(releasenotes): fix release note entries for 1.6.0
  releasenotes/notes/asm-1-click-activation-with-RCM-6a2431949768b73b.yaml
  releasenotes/notes/asm-add-http-route-for-flask-8b13c721e2f7543b.yaml
  releasenotes/notes/asm-fix-ipaddress-backport-lib-4684ce71e63459e7.yaml
  releasenotes/notes/asm-tag-http-query-string-c7faba44b1402215.yaml
  releasenotes/notes/feat-dynamic-instrumentation-4c46bb86482438c1.yaml
  releasenotes/notes/iast-weak-hash-2fe50c2c7da2289d.yaml
  releasenotes/notes/ipaddress-dep-3.7-b2bf42719e5f99ec.yaml
  releasenotes/notes/wsgi-span-parenting-fix-22908787ac7ee6a6.yaml
Labels: changelog/no-changelog

#4406 ci(starlette/fastapi): pin SQLAlchemy to fix framework tests
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#4330 chore(dbm): add dbm comment to database queries
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/settings/_database_monitoring.py
  tests/contrib/dbapi/test_dbapi.py
  tests/internal/test_database_monitoring.py
Labels: changelog/no-changelog

#4410 fix(releasenotes): add prelude for ASM one click feature
  releasenotes/notes/asm-1-click-activation-with-RCM-6a2431949768b73b.yaml
Labels: changelog/no-changelog

#4319 fix(telemetry): register after fork hooks on initialization
  ddtrace/internal/telemetry/writer.py
Labels: bug, changelog/no-changelog

#4337 chore(wheels): add build wheels for Python 3.11
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#4364 feat(iast): keep span if vulnerability is reported
  ddtrace/appsec/iast/processor.py
  ddtrace/appsec/processor.py
  ddtrace/constants.py
  tests/appsec/iast/test_processor.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#4409 fix(releasenotes): highlight note regarding 3.11 support
  releasenotes/notes/python311-tracer-a7077c0e461622d2.yaml
Labels: changelog/no-changelog

#4418 ci(mariadb): add missing snapshot tests
  tests/contrib/mariadb/test_mariadb.py
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_mariadb_service_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_mariadb_service_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_service_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_service_snapshot_pre_1_1.json
Labels: changelog/no-changelog

#4417 chore(docs): reformat configuration page
  docs/conf.py
  docs/configuration.rst
Labels: changelog/no-changelog
