Repository DataDog/dd-trace-py, pull requests merged in 2022-02, with the labels that each got.

#3210 fix(internal): use correct max item size variable in log warning
  ddtrace/internal/writer.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#3027 feat(appsec): ddwaf extension
  .circleci/config.yml
  .github/workflows/build_deploy.yml
  .gitignore
  ddtrace/appsec/CMakeLists.txt
  ddtrace/appsec/__init__.py
  ddtrace/appsec/_ddwaf.pyx
  ddtrace/appsec/_libddwaf.pxd
  ddtrace/appsec/processor.py
  ddtrace/appsec/rules.json
  ddtrace/tracer.py
  pyproject.toml
  riotfile.py
  setup.cfg
  setup.py
  tests/appsec/__init__.py
  tests/appsec/rules-bad.json
  tests/appsec/rules-good.json
  tests/appsec/test_ddwaf_fuzz.py
  tests/appsec/test_processor.py
  tests/smoke_test.py
  tox.ini
Labels: changelog/no-changelog

#3218 fix(types): remove unused type ignore in pprof.pyx
  ddtrace/profiling/exporter/pprof.pyx
Labels: changelog/no-changelog

#3219 ci: bump httpx framework tests
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#3222 fix: readthedocs build
  docs/requirements.txt
Labels: changelog/no-changelog

#3220 fix(appsec): ddtrace.ext.SpanTypes not an Enum
  ddtrace/appsec/processor.py
  tests/appsec/test_processor.py
Labels: changelog/no-changelog, v1.0

#3211 fix(docs): update writer buffer and payload limits
  docs/configuration.rst
Labels: changelog/no-changelog

#3187 refactor: get environment tag from span instead of span.tracer
  ddtrace/sampler.py
Labels: changelog/no-changelog, v1.0

#3165 chore!: remove HTTPServerConfig from the public api
  ddtrace/settings/config.py
  releasenotes/notes/internalize_http_server-06721b67e63dde1d.yaml
Labels: v1.0

#3213 chore(span): deprecate Span.pprint
  ddtrace/span.py
  ddtrace/tracer.py
  releasenotes/notes/deprecate-span-pprint-master-101afa039a6bbaee.yaml
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/flask/test_middleware.py
  tests/contrib/pymongo/test.py
  tests/tracer/test_span.py
  tests/utils.py
Labels: v1.0

#3226 chore(flake): ignore .ddriot directory
  tox.ini
Labels: changelog/no-changelog

#3227 ci: pin pytest < 7.0.0
  riotfile.py
Labels: changelog/no-changelog

#3212 chore(span): deprecate Span.meta
  ddtrace/appsec/processor.py
  ddtrace/context.py
  ddtrace/contrib/aiobotocore/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/span.py
  ddtrace/tracer.py
  releasenotes/notes/deprecate-span-meta-ad1c96ba55acaac9.yaml
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/aiopg/test.py
  tests/contrib/aredis/test_aredis.py
  tests/contrib/bottle/test.py
  tests/contrib/celery/test_utils.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/dbapi/test_dbapi.py
  tests/contrib/django/test_django.py
  tests/contrib/dogpile_cache/test_tracing.py
  tests/contrib/falcon/test_suite.py
  tests/contrib/flask/test_blueprint.py
  tests/contrib/flask/test_errorhandler.py
  tests/contrib/flask/test_flask_helpers.py
  tests/contrib/flask/test_hooks.py
  tests/contrib/flask/test_middleware.py
  tests/contrib/flask/test_request.py
  tests/contrib/flask/test_signals.py
  tests/contrib/flask/test_template.py
  tests/contrib/flask/test_views.py
  tests/contrib/flask_autopatch/test_flask_autopatch.py
  tests/contrib/flask_cache/test.py
  tests/contrib/flask_cache/test_wrapper_safety.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/mariadb/test_mariadb.py
  tests/contrib/molten/test_molten.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysqldb.py
  tests/contrib/pylons/test_pylons.py
  tests/contrib/pymongo/test.py
  tests/contrib/pymysql/test_pymysql.py
  tests/contrib/pynamodb/test_pynamodb.py
  tests/contrib/pyramid/utils.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/redis/test_redis.py
  tests/contrib/requests/test_requests.py
  tests/contrib/sanic/test_sanic_server.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/urllib3/test_urllib3.py
  tests/contrib/yaaredis/test_yaaredis.py
  tests/integration/test_integration_snapshots.py
  tests/tracer/test_encoders.py
  tests/tracer/test_global_config.py
  tests/tracer/test_span.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
  tests/utils.py
Labels: v1.0

#3206 ci: add system tests in CI
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#3230 chore(docs): update supported aiopg version
  docs/index.rst
Labels: changelog/no-changelog

#3223 chore(tracer): deprecate Tracer.writer
  benchmarks/threading/scenario.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/rq/__init__.py
  ddtrace/internal/debug.py
  ddtrace/internal/writer.py
  ddtrace/profiling/profiler.py
  ddtrace/tracer.py
  docs/spelling_wordlist.txt
  releasenotes/notes/deprecate-tracer-writer-b4921987ad47a832.yaml
  tests/benchmarks/test_encoding.py
  tests/commands/ddtrace_run_dogstatsd.py
  tests/commands/ddtrace_run_hostname.py
  tests/contrib/dbapi/test_dbapi.py
  tests/contrib/falcon/test_distributed_tracing.py
  tests/contrib/httplib/test_httplib.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/redis/test_redis.py
  tests/contrib/requests/test_requests.py
  tests/contrib/tornado/test_config.py
  tests/integration/test_debug.py
  tests/integration/test_integration.py
  tests/integration/test_integration_snapshots.py
  tests/tracer/test_encoders.py
  tests/tracer/test_sampler.py
  tests/tracer/test_tracer.py
  tests/utils.py
Labels: v1.0

#3204 fix(internal): allow tagset values to contain equal signs
  ddtrace/internal/_tagset.pyx
  tests/tracer/test_tagset.py
Labels: changelog/no-changelog

#3217 chore(tracer)!: remove Tracer.writer
  ddtrace/tracer.py
  releasenotes/notes/remove-tracer-writer-b1875a1fa3230236.yaml
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/falcon/test_suite.py
  tests/integration/test_integration.py
  tests/integration/test_integration_snapshots.py
  tests/utils.py
Labels: v1.0

#3201 chore(span): deprecate span.metrics
  ddtrace/context.py
  ddtrace/contrib/aiobotocore/patch.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  ddtrace/internal/_encoding.pyx
  ddtrace/span.py
  ddtrace/tracer.py
  releasenotes/notes/deprecate-span-metrics-89e72fb008a567d6.yaml
  tests/contrib/aiopg/test.py
  tests/contrib/celery/test_utils.py
  tests/contrib/flask_cache/test.py
  tests/contrib/flask_cache/test_wrapper_safety.py
  tests/contrib/pymongo/test.py
  tests/contrib/sqlalchemy/test_patch.py
  tests/integration/test_integration_snapshots.py
  tests/tracer/test_encoders.py
  tests/tracer/test_global_config.py
  tests/tracer/test_processors.py
  tests/tracer/test_span.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
  tests/utils.py
Labels: v1.0

#3232 chore: deprecate Span.set_meta and Span.set_metas
  ddtrace/contrib/aiohttp/template.py
  ddtrace/contrib/pylibmc/client.py
  ddtrace/contrib/tornado/template.py
  ddtrace/propagation/http.py
  ddtrace/span.py
  docs/advanced_usage.rst
  releasenotes/notes/deprecate-span-get-set-meta-c6fb2528d198414c.yaml
  tests/tracer/test_span.py
Labels: v1.0

#3216 chore(span): deprecate span.tracer
  ddtrace/opentracer/span.py
  ddtrace/span.py
  ddtrace/tracer.py
  releasenotes/notes/deprecate-span-tracer-master-6c8666cf49ee4f4a.yaml
  tests/contrib/aiohttp/app/web.py
  tests/tracer/test_encoders.py
  tests/tracer/test_sampler.py
  tests/tracer/test_span.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
Labels: v1.0

#2996 chore!: remove deprecated environment variables
  ddtrace/appsec/processor.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/commands/ddtrace_run.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/bottle/patch.py
  ddtrace/contrib/celery/patch.py
  ddtrace/contrib/cherrypy/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/falcon/patch.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/httpx/patch.py
  ddtrace/contrib/jinja2/patch.py
  ddtrace/contrib/kombu/patch.py
  ddtrace/contrib/mariadb/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/mysql/patch.py
  ddtrace/contrib/mysqldb/patch.py
  ddtrace/contrib/psycopg/patch.py
  ddtrace/contrib/pylons/patch.py
  ddtrace/contrib/pymysql/patch.py
  ddtrace/contrib/pyodbc/patch.py
  ddtrace/contrib/pyramid/patch.py
  ddtrace/contrib/pytest/__init__.py
  ddtrace/contrib/requests/patch.py
  ddtrace/contrib/snowflake/patch.py
  ddtrace/contrib/sqlite3/patch.py
  ddtrace/contrib/tornado/patch.py
  ddtrace/contrib/urllib3/patch.py
  ddtrace/internal/agent.py
  ddtrace/internal/logger.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/utils/formats.py
  ddtrace/internal/writer.py
  ddtrace/sampler.py
  ddtrace/settings/config.py
  ddtrace/settings/integration.py
  ddtrace/tracer.py
  ddtrace/utils/formats.py
  releasenotes/notes/remove_deprecated_environment_variables-3ed446513ab21409.yaml
  riotfile.py
  tests/commands/test_runner.py
  tests/tracer/test_logger.py
  tests/tracer/test_settings.py
  tests/tracer/test_tracer.py
  tests/tracer/test_utils.py
Labels: v1.0

#3249 chore!: remove Span.tracer property
  benchmarks/encoder/utils.py
  benchmarks/sampling_rule_matches/scenario.py
  ddtrace/opentracer/span.py
  ddtrace/span.py
  ddtrace/tracer.py
  releasenotes/notes/remove-span-tracer-ddtrace-1-0-bc0ced48b2806e3c.yaml
  tests/contrib/celery/test_utils.py
  tests/contrib/grpc/test_grpc.py
  tests/tracer/test_context.py
  tests/tracer/test_encoders.py
  tests/tracer/test_filters.py
  tests/tracer/test_processors.py
  tests/tracer/test_rand.py
  tests/tracer/test_sampler.py
  tests/tracer/test_span.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
Labels: v1.0

#3254 chore: move flake8 configuration
  setup.cfg
  tox.ini
Labels: changelog/no-changelog

#3258 chore(tracing): internalize Tracer.sampler and Tracer.priority_sampler
  ddtrace/internal/debug.py
  ddtrace/tracer.py
  releasenotes/notes/deprecate-tracer-sampler-attribute-c7c9d0523a8162a7.yaml
  tests/commands/ddtrace_run_priority_sampling.py
  tests/contrib/aiohttp/test_middleware.py
  tests/integration/test_integration_snapshots.py
  tests/tracer/test_sampler.py
Labels: v1.0

#3259 chore(riotfile): remove double entry for mysql-connector-python version
  riotfile.py
Labels: changelog/no-changelog

#3257 chore(tracing): deprecate Tracer.tags
  ddtrace/internal/debug.py
  ddtrace/internal/runtime/tag_collectors.py
  ddtrace/tracer.py
  releasenotes/notes/deprecate-tracer-tags-attribute-e1b3706820110a09.yaml
  tests/commands/ddtrace_run_env.py
  tests/commands/ddtrace_run_global_tags.py
  tests/contrib/tornado/test_config.py
  tests/tracer/test_tracer.py
Labels: v1.0

#3271 fix(appsec): remove SpanType Enum
  tests/appsec/test_processor.py
Labels: changelog/no-changelog, v1.0

#3266 chore(profiling): add some typing to the http exporter
  ddtrace/profiling/exporter/__init__.py
  ddtrace/profiling/exporter/file.py
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/exporter/pprof.pyi
  ddtrace/profiling/exporter/pprof.pyx
  ddtrace/profiling/profiler.py
Labels: changelog/no-changelog

#3261 chore: deprecate constants
  ddtrace/constants.py
  ddtrace/contrib/logging/patch.py
  ddtrace/opentracer/tracer.py
  ddtrace/span.py
  ddtrace/tracer.py
  releasenotes/notes/deprecate-constants-e6ea6706d38b186f.yaml
  tests/tracer/test_constants.py
Labels: v1.0

#3256 chore(tracer): deprecate Tracer.log attribute
  ddtrace/internal/debug.py
  ddtrace/tracer.py
  releasenotes/notes/deprecate-tracer-log-attribute-a7fb4c9c23d5b7b4.yaml
  tests/commands/ddtrace_run_debug.py
  tests/commands/ddtrace_run_no_debug.py
  tests/integration/test_debug.py
  tests/tracer/test_tracer.py
Labels: v1.0

#3269 chore(dbapi): deprecate Pin.app
  ddtrace/contrib/aiopg/connection.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/mariadb/patch.py
  ddtrace/contrib/mysql/patch.py
  ddtrace/contrib/mysqldb/patch.py
  ddtrace/contrib/psycopg/patch.py
  ddtrace/contrib/pymysql/patch.py
  ddtrace/contrib/pyodbc/patch.py
  ddtrace/contrib/snowflake/patch.py
  ddtrace/contrib/sqlite3/patch.py
  ddtrace/contrib/vertica/constants.py
  ddtrace/contrib/vertica/patch.py
  tests/contrib/dbapi/test_dbapi.py
Labels: changelog/no-changelog, v1.0

#3265 chore: deprecate Pin.app
  ddtrace/contrib/aiobotocore/patch.py
  ddtrace/contrib/aiohttp/patch.py
  ddtrace/contrib/algoliasearch/patch.py
  ddtrace/contrib/aredis/patch.py
  ddtrace/contrib/boto/patch.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/cassandra/session.py
  ddtrace/contrib/consul/patch.py
  ddtrace/contrib/dogpile_cache/patch.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/httpx/patch.py
  ddtrace/contrib/kombu/patch.py
  ddtrace/contrib/mako/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/pymemcache/patch.py
  ddtrace/contrib/pymongo/client.py
  ddtrace/contrib/pymongo/patch.py
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/rediscluster/patch.py
  ddtrace/contrib/requests/patch.py
  ddtrace/contrib/sqlalchemy/engine.py
  ddtrace/contrib/tornado/application.py
  ddtrace/pin.py
  releasenotes/notes/deprecate-pin-app-de153348b61a9905.yaml
  tests/tracer/test_pin.py
Labels: v1.0

#3285 chore(tracing)!: Remove deprecated install excepthook
  ddtrace/__init__.py
  releasenotes/notes/remove-ddtrace-install-excepthooks-8107b679a9f51ef3.yaml
Labels: v1.0

#3281 chore(tracing/grpc): add patch/unpatch tests for grpc integration
  tests/contrib/grpc/test_grpc_patch.py
Labels: changelog/no-changelog

#3283 chore(tracing/context)!: remove Context.clone
  ddtrace/context.py
  releasenotes/notes/remove-clone-context-3cc6f3d73f15345e.yaml
Labels: v1.0

#3264 chore!: remove Pin.app and Pin.app_type
  ddtrace/contrib/celery/app.py
  ddtrace/contrib/celery/constants.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/molten/patch.py
  ddtrace/pin.py
  releasenotes/notes/remove-pin-app-apptype-8d0addd243deb7f9.yaml
  tests/contrib/requests/test_requests.py
  tests/tracer/test_pin.py
Labels: v1.0

#3286 chore(tracing/integrations)!: remove deprecated manual instrumentation helpers
  ddtrace/contrib/flask/__init__.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/pymongo/__init__.py
  ddtrace/contrib/pymongo/patch.py
  ddtrace/contrib/pymysql/__init__.py
  ddtrace/contrib/pymysql/tracers.py
  ddtrace/contrib/redis/__init__.py
  ddtrace/contrib/redis/tracers.py
  releasenotes/notes/update-deprecated-contrib-removal-version-ca920d9e1d91b6e0.yaml
  tests/contrib/flask/test_middleware.py
  tests/contrib/pymongo/test.py
  tests/contrib/pymysql/test_backwards_compatibility.py
  tests/contrib/redis/test_redis.py
  tests/utils.py
Labels: v1.0

#3294 fix(ci): pin itsdangerous and markupsafe to avoid breaking change
  riotfile.py
Labels: changelog/no-changelog

#3291 chore: update build scripts for new default branch
  .circleci/config.yml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/system-tests.yml
  .github/workflows/test_frameworks.yml
  benchmarks/README.rst
  scripts/check-releasenotes
Labels: changelog/no-changelog, v1.0

#3298 chore(docs): remove references to master branch
  CHANGELOG.md
  README.md
  docs/contributing.rst
Labels: changelog/no-changelog

#3300 chore: use psycopg2-binary for django test env
  riotfile.py
Labels: changelog/no-changelog

#3309 chore(tracer)!: remove tracer.write
  ddtrace/tracer.py
  releasenotes/notes/tracer-write-dc2f9d95c0e4d11f.yaml
Labels: v1.0

#3278 chore: use debtcollector instead of internal deprecation module
  ddtrace/__init__.py
  ddtrace/_monkey.py
  ddtrace/compat.py
  ddtrace/context.py
  ddtrace/contrib/cassandra/session.py
  ddtrace/contrib/celery/task.py
  ddtrace/contrib/flask/middleware.py
  ddtrace/contrib/mongoengine/patch.py
  ddtrace/contrib/mysql/tracers.py
  ddtrace/contrib/psycopg/connection.py
  ddtrace/contrib/pymongo/patch.py
  ddtrace/contrib/pymysql/tracers.py
  ddtrace/contrib/redis/tracers.py
  ddtrace/contrib/requests/legacy.py
  ddtrace/contrib/sqlite3/connection.py
  ddtrace/contrib/util.py
  ddtrace/encoding.py
  ddtrace/ext/errors.py
  ddtrace/ext/priority.py
  ddtrace/ext/system.py
  ddtrace/helpers.py
  ddtrace/http/__init__.py
  ddtrace/http/headers.py
  ddtrace/internal/logger.py
  ddtrace/internal/utils/deprecation.py
  ddtrace/internal/utils/formats.py
  ddtrace/internal/utils/wrappers.py
  ddtrace/monkey.py
  ddtrace/propagation/utils.py
  ddtrace/settings/config.py
  ddtrace/span.py
  ddtrace/tracer.py
  ddtrace/util.py
  ddtrace/utils/__init__.py
  ddtrace/utils/attr.py
  ddtrace/utils/attrdict.py
  ddtrace/utils/cache.py
  ddtrace/utils/config.py
  ddtrace/utils/deprecation.py
  ddtrace/utils/formats.py
  ddtrace/utils/http.py
  ddtrace/utils/importlib.py
  ddtrace/utils/time.py
  ddtrace/utils/version.py
  ddtrace/utils/wrappers.py
  tests/tracer/test_logger.py
  tests/tracer/test_span.py
  tests/tracer/test_tracer.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog, v1.0

#3314 chore(tracing/rq): refactor rq test parameter matrix
  tests/contrib/rq/test_rq.py
  tests/snapshots/tests.contrib.rq.test_rq.test_enqueue_distributed_tracing_enabled_False_worker_service_custom-worker-service.json
  tests/snapshots/tests.contrib.rq.test_rq.test_enqueue_distributed_tracing_enabled_None_worker_service_None.json
Labels: changelog/no-changelog

#3308 chore(tracer): deprecate tracer.write method
  ddtrace/tracer.py
  releasenotes/notes/tracer-write-5d46dc5c4e870b9b.yaml
Labels: v1.0

#3315 chore: fix coverage report in 0.59 branch
  .circleci/config.yml
Labels: changelog/no-changelog

#3279 chore(ci): fail fast when integration tests fail
  .circleci/config.yml
Labels: changelog/no-changelog

#3325 fix: set_meta and set_metas deprecation warnings
  ddtrace/span.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog, v1.0

#3297 chore: add v0.59 to release_notes.rst
  docs/release_notes.rst
Labels: changelog/no-changelog, manual merge

#3337 docs: fix warning filter for v1 deprecations
  releasenotes/notes/release-1.0-758fc917e40d7eb3.yaml
  releasenotes/notes/remove-v1deprecationwarning-2c251ca219182b97.yaml
Labels: changelog/no-changelog

#3343 chore(trace/utils): type set_http_meta
  ddtrace/contrib/trace_utils.py
Labels: changelog/no-changelog

#3341 refactor(tracer): maintain agent url state
  ddtrace/tracer.py
Labels: changelog/no-changelog

#3340 chore(trace/encoding): add packb type interface
  ddtrace/internal/_encoding.pyi
Labels: changelog/no-changelog

#3342 fix(tests): use non-local task functions in multiprocessing tests
  tests/tracer/test_rand.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#3346 fix: update aiopg-0160-67bac7e073e4bbf9.yaml
  releasenotes/notes/aiopg-0160-67bac7e073e4bbf9.yaml
Labels: changelog/no-changelog
