Repository DataDog/dd-trace-py, pull requests merged in 2022-12, with the labels that each got.

#4689 ci(algoliasearch): move algoliasearch tests to riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#4687 chore(ci): move molten test suite to riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#4686 chore(ci): increase parallelization of pytest tests on CI
  .circleci/config.yml
Labels: changelog/no-changelog

#4685 chore(ci): increase parallelization for mongoengine tests on CI
  .circleci/config.yml
Labels: changelog/no-changelog

#4688 chore(ci): increase parallelization for httpx tests on CI
  .circleci/config.yml
Labels: changelog/no-changelog

#4681 chore(framework tests): add uwsgi framework test suite
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#4694 chore(sanic): replace set_tag usages to set_str_tag
  ddtrace/contrib/sanic/patch.py
Labels: changelog/no-changelog

#4702 chore(sqlalchemy): replace set_tag usages with set_tag_str
  ddtrace/contrib/sqlalchemy/engine.py
Labels: changelog/no-changelog

#4701 chore(rq): replace set_tag usages with set_tag_str
  ddtrace/contrib/rq/__init__.py
Labels: changelog/no-changelog

#4706 chore(kombu): replace set_tag usages with set_tag_str
  ddtrace/contrib/kombu/patch.py
Labels: changelog/no-changelog

#4709 chore(jinja2): replace set_tag usages with set_tag_str
  ddtrace/contrib/jinja2/patch.py
Labels: changelog/no-changelog

#4703 chore(wsgi): replace set_tag usage with set_tag_str
  ddtrace/contrib/wsgi/wsgi.py
Labels: changelog/no-changelog

#4711 chore(pyramid): replace set_tag usage with set_tag_str
  ddtrace/contrib/pyramid/trace.py
Labels: changelog/no-changelog

#4707 chore(consul): replace set_tag usages with set_tag_str
  ddtrace/contrib/consul/patch.py
Labels: changelog/no-changelog

#4708 chore(molten): replace set_tag usage with set_tag_str
  ddtrace/contrib/molten/patch.py
Labels: changelog/no-changelog

#4696 chore(cassandra): replace set_tag usages with set_tag_str
  ddtrace/contrib/cassandra/session.py
Labels: changelog/no-changelog

#4695 chore(boto): replace set_tag usages to set_tag_str
  ddtrace/contrib/boto/patch.py
Labels: changelog/no-changelog

#4713 chore(pylibmc): replace set_tag usage with set_tag_str
  ddtrace/contrib/pylibmc/client.py
Labels: changelog/no-changelog

#4698 chore(redis): replace set_tag usages with set_tag_str
  ddtrace/contrib/redis/util.py
Labels: changelog/no-changelog

#4697 chore(mako): replace set_tag usages with set_tag_str
  ddtrace/contrib/mako/patch.py
Labels: changelog/no-changelog

#4714 chore(aiomysql): replace set_tag usage with set_tag_str
  ddtrace/contrib/aiomysql/patch.py
Labels: changelog/no-changelog

#4716 chore(pylons): replace set_tag usage with set_tag_str
  ddtrace/contrib/pylons/renderer.py
Labels: changelog/no-changelog

#4617 chore(w3c): modify traceparent property and add tracestate property to context
  ddtrace/context.py
  ddtrace/internal/constants.py
  ddtrace/internal/utils/http.py
  ddtrace/propagation/http.py
  tests/tracer/test_context.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog

#4566 chore(ci): use riot list --hash-only to parallelize tests
  .circleci/config.yml
Labels: changelog/no-changelog

#4705 chore(opentracing): replace set_tag usages with set_tag_str
  ddtrace/opentracer/span.py
Labels: changelog/no-changelog

#4732 chore(celery): replace set_tag usage with set_tag_str
  ddtrace/contrib/celery/signals.py
Labels: changelog/no-changelog

#4729 chore(aiohttp): replace set_tag usage with set_tag_str
  ddtrace/contrib/aiohttp/middlewares.py
Labels: changelog/no-changelog

#4725 chore(flask_cache): replace set_tag usage with set_tag_str
  ddtrace/contrib/flask_cache/tracers.py
Labels: changelog/no-changelog

#4731 chore(dogpile_cache): replace set_tag usage with set_tag_str
  ddtrace/contrib/dogpile_cache/region.py
Labels: changelog/no-changelog

#4730 chore(aiohttp-jinja2): replace set_tag usage with set_tag_str
  ddtrace/contrib/aiohttp_jinja2/patch.py
Labels: changelog/no-changelog

#4724 chore(rediscluster): replace set_tag usage with set_tag_str
  ddtrace/contrib/rediscluster/patch.py
Labels: changelog/no-changelog

#4721 chore(tornado): replace set_tag usage with set_tag_str
  ddtrace/contrib/tornado/template.py
Labels: changelog/no-changelog

#4718 chore(flask): replace set_tag usage with set_tag_str
  ddtrace/contrib/flask/wrappers.py
Labels: changelog/no-changelog

#4720 chore(aiopg): replace set_tag usage with set_tag_str
  ddtrace/contrib/aiopg/connection.py
Labels: changelog/no-changelog

#4723 chore(cassandra): replace set_tag usage with set_tag_str
  ddtrace/contrib/cassandra/session.py
Labels: changelog/no-changelog

#4722 chore(pymemcache): replace set_tag usage with set_tag_str
  ddtrace/contrib/pymemcache/client.py
Labels: changelog/no-changelog

#4712 chore(pymongo): replace set_tag usage with set_tag_str
  ddtrace/contrib/pymongo/client.py
Labels: changelog/no-changelog

#4742 revert: "chore(mako): replace set_tag usages with set_tag_str"
  ddtrace/contrib/mako/patch.py
Labels: changelog/no-changelog

#4743 revert: "chore(dogpile_cache): replace set_tag usage with set_tag_str"
  ddtrace/contrib/dogpile_cache/region.py
Labels: changelog/no-changelog

#4741 chore(w3c): allow colons in datadog tags propagated in tracestate
  ddtrace/internal/utils/http.py
  ddtrace/propagation/http.py
  tests/tracer/test_context.py
  tests/tracer/test_propagation.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog

#4750 chore(encoders): update package tool before installing packages
  scripts/profiles/encoders/setup.sh
Labels: changelog/no-changelog

#4751 ci(tox): avoid running ddtrace with tox v4.0
  .circleci/config.yml
Labels: changelog/no-changelog

#4752 chore(packaging): support version parsing in packaging v22
  ddtrace/internal/utils/version.py
  riotfile.py
Labels: changelog/no-changelog

#4717 chore(w3c): add injection for tracecontext propagation
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#4755 fix(docs): fix usage of version_added in configuration.rst
  docs/configuration.rst
Labels: changelog/no-changelog

#4727 chore(algoliasearch): replace set_tag usage with set_tag_str
  ddtrace/contrib/algoliasearch/patch.py
Labels: changelog/no-changelog

#4753 ci(tox): avoid running ddtrace with tox v4.0 (#4751) [backport to 1.6]
  .circleci/config.yml
Labels: changelog/no-changelog

#4761 ci(tox): avoid running ddtrace with tox v4.0 [backport #4751 to 1.5]
  .circleci/config.yml
Labels: changelog/no-changelog

#4762 ci(tox): avoid running ddtrace with tox v4.0 [backport #4751 0.61]
  .circleci/config.yml
Labels: changelog/no-changelog

#4764 chore(encoders): update package tool before installing packages [backport #4750 to 1.5]
  scripts/profiles/encoders/setup.sh
Labels: changelog/no-changelog

#4754 ci(encoders): fix encoders framework test [backport #4750 to 1.6]
  scripts/profiles/encoders/setup.sh
Labels: changelog/no-changelog

#4756 chore(W3C): cover tracecontext header value edge cases
  ddtrace/propagation/http.py
Labels: changelog/no-changelog

#4773 chore(ci): remove test_nightly scheduled workflow
  .circleci/config.yml
Labels: changelog/no-changelog

#4609 chore(tracing): change error.msg span tag to error.message
  ddtrace/constants.py
  tests/contrib/aiobotocore/test.py
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/aiohttp_jinja2/test_aiohttp_jinja2.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/asyncio/test_tracer.py
  tests/contrib/asyncpg/test_asyncpg.py
  tests/contrib/celery/test_integration.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/djangorestframework/test_djangorestframework.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/flask/test_errorhandler.py
  tests/contrib/flask/test_request.py
  tests/contrib/flask/test_static.py
  tests/contrib/flask/test_views.py
  tests/contrib/gevent/test_tracer.py
  tests/contrib/graphql/test_graphql.py
  tests/contrib/pylons/test_pylons.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest_bdd/test_pytest_bdd.py
  tests/contrib/sqlalchemy/test_mysql.py
  tests/contrib/sqlalchemy/test_postgres.py
  tests/contrib/sqlalchemy/test_sqlite.py
  tests/contrib/starlette/test_starlette.py
  tests/contrib/tornado/test_executor_decorator.py
  tests/contrib/tornado/test_tornado_template.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/tornado/test_wrap_decorator.py
  tests/opentracer/test_tracer_asyncio.py
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_queries.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_bad_connect.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_bad_query.json
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_error.json
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_fatal.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_3x.json
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_failing_execute.json
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_failing_execute_v2.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_error.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_simple_malformed_query_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_simple_malformed_query_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.rq.test_rq.test_queue_failing_job.json
  tests/snapshots/tests.contrib.rq.test_rq.test_queue_failing_job_pre_1_10_1.json
  tests/snapshots/tests.contrib.rq.test_rq.test_worker_failing_job.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors.json
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_500_py2.json
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_500_py3.json
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_base_exception_in_wsgi_app_py2.json
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_base_exception_in_wsgi_app_py3.json
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_wsgi_base_middleware_500.json
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#4775 chore(upstream issues): upgrade upstream notifier version to keep closed issues closed
  .github/workflows/upstream-issues.yml
Labels: changelog/no-changelog

#4770 ci: disable broken windows profiling jobs [backport 4579 to 1.5]
  .circleci/config.yml
Labels: changelog/no-changelog

#4765 chore(packaging): support version parsing in packaging v22 [backport #4752 to 1.6]
  ddtrace/internal/utils/version.py
  riotfile.py
Labels: changelog/no-changelog

#4766 chore(packaging): support version parsing in packaging v22 [backport #4752 to 1.5]
  ddtrace/internal/utils/version.py
  riotfile.py
Labels: changelog/no-changelog

#4474 refactor(stack): do not try to account CPU time on gevent tasks
  ddtrace/profiling/collector/stack.pyx
  tests/profiling/collector/test_stack_asyncio.py
Labels: changelog/no-changelog

#4704 chore(tracing): replace set_tag usages with set_tag_str
  ddtrace/contrib/trace_utils.py
  ddtrace/filters.py
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog

#4627 chore(ci): pin package versions in test workflow and add separate workflow for latest test
  .circleci/config.yml
  .circleci/dependencies.py
  riotfile.py
  scripts/ddtest
  scripts/manage_dependencies.py
Labels: changelog/no-changelog

#4734 chore(debugger): compile expression lambda with access locals variables
  ddtrace/debugging/_expressions.py
  tests/debugging/test_debugger.py
  tests/submod/stuff.py
Labels: changelog/no-changelog

#4784 chore(upstream issue notifier): upgrade upstream issue notifier to 0.1.3
  .github/workflows/upstream-issues.yml
Labels: changelog/no-changelog

#4790 chore(docs): add troubleshooting note when installation says Cython is not available
  docs/troubleshooting.rst
Labels: changelog/no-changelog

#4787 test(debugging): slow down test uploader to allow buffer to fill
  tests/debugging/test_uploader.py
Labels: changelog/no-changelog

#4759 ci: disable RCM in debugger exploration tests
  tests/debugging/exploration/debugger.py
Labels: changelog/no-changelog

#4779 chore(logging): fix noisy rq patching log
  ddtrace/_monkey.py
Labels: changelog/no-changelog

#4699 chore(debugger): support for all metric kinds with value expression
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/internal/metrics.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#4796 chore(releasenotes): ignore 1.6 changes in 1.7 release notes
  docs/release_notes.rst
Labels: changelog/no-changelog

#4799 Revert "chore(w3c): allow colons in datadog tags propagated in tracestate"
  ddtrace/internal/utils/http.py
  ddtrace/propagation/http.py
  tests/tracer/test_context.py
  tests/tracer/test_propagation.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog

#4801 fix(starlette framework tests): unpin sqlalchemy
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#4791 fix(w3c): fix traceparent validation
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#4804 Revert "chore(w3c): allow colons in datadog tags propagated in tracestate" (backport #4799 to 1.7)
  ddtrace/internal/utils/http.py
  ddtrace/propagation/http.py
  tests/tracer/test_context.py
  tests/tracer/test_propagation.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog

#4803 fix(w3c): fix traceparent validation (backport #4791 to 1.7)
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#4802 feat(celery): flatten context `delivery_info` tags (backport #4772)
  ddtrace/contrib/celery/utils.py
  releasenotes/notes/celery-flatten-context-dicts-bc5c33b72bd72ac2.yaml
  tests/contrib/celery/test_utils.py
Labels: changelog/no-changelog

#4776 chore(gunicorn): add tests
  .circleci/config.yml
  .circleci/dependencies.py
  conftest.py
  ddtrace/contrib/gunicorn/__init__.py
  docs/advanced_usage.rst
  docs/index.rst
  docs/integrations.rst
  docs/spelling_wordlist.txt
  riotfile.py
  tests/contrib/gunicorn/__init__.py
  tests/contrib/gunicorn/simple_app.py
  tests/contrib/gunicorn/test_gunicorn.py
  tests/contrib/gunicorn/wsgi_mw_app.py
  tests/snapshots/tests.contrib.gunicorn.test_gunicorn.test_traced_basic[gunicorn_server_settings0].json
Labels: changelog/no-changelog

#4808 chore(ci): evenly distribute tox scenarios on test runners
  scripts/run-tox-scenario
Labels: changelog/no-changelog

#4809 chore(ci): move vertica tests to riot
  .circleci/config.yml
  riotfile.py
  tox.ini
Labels: changelog/no-changelog

#4749 chore(iast): remote config thread workaround for gevent
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/writer.py
  ddtrace/tracer.py
Labels: changelog/no-changelog, ASM

#4792 chore(ci): remove test_latest workflow
  .circleci/config.yml
  riotfile.py
Labels: changelog/no-changelog

#4700 fix(botocore): keep newlines in json data for kinesis records
  ddtrace/contrib/botocore/patch.py
  releasenotes/notes/fix-kinesis-newline-strip-issue-3a2419b6f29fcab8.yaml
  tests/contrib/botocore/test.py
Labels: bug, Tracing

#4811 chore(internal): remove side-effects from origin [backport #4435 to 1.6]
  ddtrace/internal/module.py
  tests/internal/test_module.py
Labels: changelog/no-changelog

#4816 fix(tests): pin attrs<22.2.0 for Python 3.6 in integration tests
  riotfile.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#4806 fix(starlette framework tests): unpin sqlalchemy [backport #4801 to 1.6]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#4821 fix(tests): pin attrs<22.2.0 for Python 3.6 in integration tests [backport #4816 to 1.7]
  riotfile.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#4820 fix(tests): pin attrs<22.2.0 for Python 3.6 in integration tests [backport #4816 to 1.6]
  riotfile.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#4769 ci(httpx): pin tested version to v0.22.0 [0.61 branch]
  riotfile.py
Labels: changelog/no-changelog

#4833 ci(starlette): unpin sqlalchemy in framework tests [backport #4801 to 1 7]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#4832 fix(internal): catch possible OSError when calling platform.libc_ver() (backport #4828)
  ddtrace/internal/telemetry/data.py
  releasenotes/notes/fix-telemetry-platform-libc-ver-call-8872bde91bcc8765.yaml
  tests/telemetry/test_data.py
Labels: changelog/no-changelog

#4831 fix(internal): catch possible OSError when calling platform.libc_ver() (backport #4828)
  ddtrace/internal/telemetry/data.py
  releasenotes/notes/fix-telemetry-platform-libc-ver-call-8872bde91bcc8765.yaml
  tests/telemetry/test_data.py
Labels: changelog/no-changelog

#4236 docs(debugging): add dynamic instrumentation API
  ddtrace/debugging/_debugger.py
  docs/api.rst
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog, Dynamic Instrumentation

#4827 chore(w3c): update tracestate tag regex
  ddtrace/internal/utils/http.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog

#4826 chore(ci): remove test_latest workflow (backport #4792)
  .circleci/config.yml
  riotfile.py
Labels: changelog/no-changelog

#4830 fix(tracing): disallow v0.5 api usage for windows machines
  ddtrace/internal/writer.py
  releasenotes/notes/v05-encoding-eac70f23850a445e.yaml
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#4824 chore(iast): remote config thread workaround for gevent [backport #4749 to 1.7]
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/writer.py
  ddtrace/tracer.py
Labels: changelog/no-changelog, ASM

#4835 chore(asm): change default value for remote config env var [backport #4813 to 1.7]
  ddtrace/appsec/utils.py
  releasenotes/notes/asm-1-click-activation-with-RCM-by-default-92233ac7f60292e0.yaml
  tests/appsec/test_remoteconfiguration.py
Labels: ASM

#4837 fix(tracing): disallow v0.5 api usage for windows machines (backports #4830 to 1.7)
  ddtrace/internal/writer.py
  releasenotes/notes/v05-encoding-eac70f23850a445e.yaml
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#4836 chore(w3c): update tracestate tag regex (backport #4827 to 1.7)
  ddtrace/internal/utils/http.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog

#4778 perf(tracer): remove redundant DD_ENV logic
  ddtrace/bootstrap/sitecustomize.py
  tests/commands/ddtrace_run_env.py
  tests/commands/ddtrace_run_service.py
  tests/commands/test_runner.py
  tests/integration/test_integration_snapshots.py
  tests/snapshots/tests.integration.test_integration_snapshots.test_env_vars.json
Labels: changelog/no-changelog
