Repository DataDog/dd-trace-py, pull requests merged in 2023-02, with the labels that each got.

#5012 fix: fix backport action PR labels template
  .github/workflows/backport.yml
Labels: changelog/no-changelog

#5015 chore(reno): add known issues to release notes template
  releasenotes/config.yaml
Labels: changelog/no-changelog

#4997 chore(ciapp): keep both branch and tag if present
  ddtrace/ext/ci.py
  ddtrace/ext/git.py
  tests/tracer/fixtures/ci/appveyor.json
  tests/tracer/fixtures/ci/buddy.json
Labels: changelog/no-changelog

#5025 chore: assign ownership of appsec framework tests to asm
  .github/CODEOWNERS
Labels: changelog/no-changelog, ASM

#5007 chore(tracing): add gevent patch guard
  ddtrace/contrib/gevent/patch.py
Labels: changelog/no-changelog, Tracing

#5020 feat(telemetry): debug environment variable
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#5017 chore(rcm): refactor semver format in agent requests
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/utils/version.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/test_utils_version.py
Labels: changelog/no-changelog, ASM

#5023 feat(asm): add RCM capabilities support
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/processor.py
  ddtrace/appsec/utils.py
  ddtrace/internal/compat.py
  ddtrace/internal/remoteconfig/__init__.py
  ddtrace/internal/remoteconfig/constants.py
  ddtrace/tracer.py
  releasenotes/notes/asm-rcm-feature-registration-21d79315c7a0feb7.yaml
  setup.cfg
  tests/appsec/test_remoteconfiguration.py
  tests/internal/remoteconfig/test_remoteconfig.py
Labels: ASM

#4973 fix(rcm): ensure proper validation of responses from the agent [backport #4970 to 1.7]
  ddtrace/internal/remoteconfig/client.py
  releasenotes/notes/rcm-validations-162716c50ea90f1b.yaml
  tests/internal/remoteconfig/rc_mocked_responses_asm_features.json
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
Labels: ASM

#5030 feat(asm): add new ASM context manager
  ddtrace/appsec/_asm_request_context.py
  tests/appsec/test_asm_request_context.py
Labels: enhancement, changelog/no-changelog, ASM

#5008 ci(debugging): expose tests folder as submodule to exploration tests
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/preload.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5026 chore(gunicorn): clarify gunicorn tests
  ddtrace/contrib/gunicorn/__init__.py
  tests/contrib/gunicorn/post_fork.py
  tests/contrib/gunicorn/test_gunicorn.py
Labels: changelog/no-changelog

#5033 chore(asm): move weak algorithms fixtures
  tests/appsec/iast/fixtures/__init__.py
  tests/appsec/iast/fixtures/weak_algorithms.py
  tests/appsec/iast/test_weak_cipher.py
  tests/appsec/iast/test_weak_hash.py
Labels: changelog/no-changelog, ASM

#5035 chore(asm): ddwaf bindings improve performances
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/ddwaf/ddwaf_types.py
  tests/appsec/test_ddwaf_fuzz.py
Labels: changelog/no-changelog

#4502 chore(rcm): add tags to client tracer requests
  ddtrace/internal/remoteconfig/client.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
Labels: changelog/no-changelog

#5003 chore(wsgi): replace string with predefined constant
  ddtrace/contrib/wsgi/wsgi.py
Labels: changelog/no-changelog

#4854 feat: add Python 3.11 support to Dynamic Instrumentation
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_expressions.py
  ddtrace/internal/injection.py
  ddtrace/internal/utils/inspection.py
  ddtrace/internal/wrapping.py
  releasenotes/notes/feat-debugging-py311-support-2160a5590048c7c3.yaml
  riotfile.py
  tests/debugging/test_expressions.py
  tests/internal/py35/test_wrapping.py
  tests/internal/py36/test_wrapping.py
  tests/internal/test_injection.py
  tests/internal/test_wrapping.py
Labels: Dynamic Instrumentation

#5021 chore(internal): update trace writer debug log to include the status of the writer
  ddtrace/internal/writer.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#5037 feat(graphql,graphene): add support for Python 3.11
  releasenotes/notes/feat-graphql-graphene-py-3-11-c7706304dfe18cd4.yaml
  riotfile.py
Labels: changelog/no-changelog

#5039 fix(ci/lib-injection): add missing runs_on value
  .github/workflows/build-and-publish-image.yml
  .github/workflows/build_deploy.yml
  .github/workflows/lib-injection.yml
Labels: changelog/no-changelog

#5055 fix(ci/lib-injection): add missing runs_on value [backport #5039 to 1.7]
  .github/workflows/build-and-publish-image.yml
  .github/workflows/build_deploy.yml
  .github/workflows/lib-injection.yml
Labels: changelog/no-changelog

#5050 fix(asm): fix unicode decode errors in pylons [backport #5029 to 1.7]
  ddtrace/contrib/pylons/middleware.py
  releasenotes/notes/fix-unicode-decode-errors-pylons-52d28b22f82e184a.yaml
  tests/contrib/pylons/test_pylons.py
Labels: ASM

#5062 test(lib-injection): fix the version of tests used
  .github/workflows/lib-injection.yml
Labels: changelog/no-changelog

#5041 fix: fix the backport GitHub Action's labels_template lodash template
  .github/workflows/backport.yml
Labels: changelog/no-changelog

#5022 chore(benchmarks): setup benchmark platform integration
  .github/PULL_REQUEST_TEMPLATE.md
  .gitlab-ci.yml
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#5060 chore(benchmarks): remove outdated decorator in threading scenario
  benchmarks/threading/scenario.py
Labels: changelog/no-changelog

#5072 test(asm): small improvement for tests django appsec
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5059 chore(asm): iast chapter 1 asm side
  ddtrace/appsec/iast/_ast/__init__.py
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_ast/ast_patching.py
  ddtrace/appsec/iast/_ast/visitor.py
  ddtrace/appsec/iast/_util.py
  tests/appsec/iast/aspects/__init__.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/ast/test_ast_patching.py
  tests/appsec/iast/fixtures/aspects/str/__init__.py
  tests/appsec/iast/fixtures/aspects/str/class_no_str.py
  tests/appsec/iast/fixtures/aspects/str/class_str.py
  tests/appsec/iast/fixtures/aspects/str/empty_file.py
  tests/appsec/iast/fixtures/aspects/str/function_no_str.py
  tests/appsec/iast/fixtures/aspects/str/function_str.py
  tests/appsec/iast/fixtures/aspects/str/future_import_class_str.py
  tests/appsec/iast/fixtures/aspects/str/future_import_function_str.py
  tests/appsec/iast/fixtures/aspects/str/invented_extension.cppy
  tests/appsec/iast/fixtures/aspects/str/non_utf8_content.py
  tests/appsec/iast/fixtures/integration/__init__.py
  tests/appsec/iast/fixtures/integration/main.py
  tests/appsec/iast/fixtures/integration/print_str.py
Labels: changelog/no-changelog, ASM

#5067 chore(cassandra): improve imports
  ddtrace/contrib/cassandra/__init__.py
  ddtrace/contrib/cassandra/session.py
Labels: changelog/no-changelog, Tracing

#5064 test(lib-injection): fix the version of tests used [backport #5062 to 1.8]
  .github/workflows/lib-injection.yml
Labels: changelog/no-changelog

#5069 chore(django): avoid cross-import from psycopg
  ddtrace/contrib/django/patch.py
Labels: changelog/no-changelog, Tracing

#5070 chore(snowflake): improve imports
  ddtrace/contrib/snowflake/patch.py
Labels: changelog/no-changelog, Tracing

#5068 chore(dogpile_cache): improve imports
  ddtrace/contrib/dogpile_cache/patch.py
Labels: changelog/no-changelog, Tracing

#5036 chore(internal): replace ddtracerun fixture with subprocess decorator in integration tests
  tests/integration/test_debug.py
Labels: changelog/no-changelog

#5082 docs: update theme to prevent overlap on configuration
  docs/conf.py
Labels: changelog/no-changelog

#5040 chore(benchmarks): run multiple benchmark scenarios in parallel
  .gitlab-ci.yml
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#5083 docs: refactor to use Furo
  .circleci/dependencies.py
  .gitignore
  docs/_templates/navigation.html
  docs/conf.py
  docs/favicon.ico
  docs/requirements.txt
  riotfile.py
Labels: changelog/no-changelog

#4478 fix(fastapi): apply tracing to user middlewares in fastapi
  ddtrace/contrib/fastapi/patch.py
  releasenotes/notes/fastapi-fix-middlewares-705975a535daaea8.yaml
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/fastapi/test_fastapi_patch.py
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_tracing_in_middleware.json
Labels: backport 1.8

#4470 refactor(dbm): decouple dbm propagation from dbapi
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/psycopg/patch.py
  ddtrace/propagation/_database_monitoring.py
  ddtrace/settings/_database_monitoring.py
  tests/contrib/dbapi/test_dbapi.py
  tests/internal/test_database_monitoring.py
Labels: changelog/no-changelog

#5075 chore(asm): add astunparse dependency to improve tests
  .circleci/dependencies.py
  riotfile.py
  tests/appsec/iast/ast/test_ast_patching.py
Labels: changelog/no-changelog, ASM

#5076 chore(asm): update code owners for appsec snapshots files
  .github/CODEOWNERS
Labels: changelog/no-changelog, ASM

#5073 chore(asm): update rules.json with version 1.5.0 from appsec-event-rules
  ddtrace/appsec/rules.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#5058 fix(asm): fix unicode decode errors in pylons [backport #5029 to 1.8]
  ddtrace/contrib/pylons/middleware.py
  releasenotes/notes/fix-unicode-decode-errors-pylons-52d28b22f82e184a.yaml
  tests/contrib/pylons/test_pylons.py
Labels: ASM

#5044 chore(asm): update asm remote config to handle new products
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/remoteconfig/constants.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog

#5074 fix(tracing): ensure correct string table content with optimisation option
  ddtrace/internal/_encoding.pyx
  releasenotes/notes/fix-msgpack-string-table-no-index-assert-620c0b0a1b363e86.yaml
  riotfile.py
  tests/tracer/test_encoders.py
Labels: Tracing

#4294 refactor(tracing): patch all integrations on import
  ddtrace/_monkey.py
  ddtrace/contrib/tornado/compat.py
  ddtrace/contrib/tornado/patch.py
  ddtrace/ext/sql.py
  tests/contrib/django/test_django.py
  tests/contrib/gevent/test_tracer.py
  tests/contrib/patch.py
  tests/contrib/tornado/test_executor_decorator.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog, Tracing

#5092 chore(asm): add known issue for RCM Gevent workers
  releasenotes/notes/add_known_issue_rcm_gevent_releasenote-1658a344a9aaf1b5.yaml
Labels: backport 1.8, backport 1.7

#5071 docs: add DD_TRACE_RATE_LIMIT
  docs/configuration.rst
Labels: changelog/no-changelog

#5100 chore(asm): fix tests and refactor for remote configuration
  ddtrace/appsec/_remoteconfiguration.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#5096 chore: fix writer log typo
  ddtrace/internal/writer.py
Labels: changelog/no-changelog

#5103 chore(testing): make tests slightly more readable
  tests/contrib/logging/test_tracer_logging.py
  tests/profiling/test_accuracy.py
  tests/profiling/test_main.py
  tests/webclient.py
Labels: changelog/no-changelog

#5102 chore(internal): make some internal modules play nicer with tests that create threads
  ddtrace/debugging/_debugger.py
  ddtrace/internal/compat.py
  ddtrace/internal/debug.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/profiling/profiler.py
Labels: changelog/no-changelog

#5081 chore(internal): ensure all frames reported when wrapping
  ddtrace/internal/wrapping.py
  tests/internal/test_wrapping.py
Labels: changelog/no-changelog

#5032 feat(asm): add blocking scaffolding
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/processor.py
  ddtrace/appsec/utils.py
  ddtrace/constants.py
  ddtrace/contrib/trace_utils.py
  ddtrace/internal/constants.py
  tests/appsec/blocking_template_html.html
  tests/appsec/blocking_template_json.json
  tests/appsec/rules-good.json
  tests/appsec/test_appsec_utils.py
  tests/appsec/test_processor.py
  tests/appsec/test_remoteconfiguration.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/tracer/test_trace_utils.py
Labels: enhancement, changelog/no-changelog, ASM

#5115 fix(rcm): fix RCM tests
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/ddwaf/__init__.py
Labels: changelog/no-changelog, ASM

#5113 feat(ci): test merge queues: conflict, A side
  merge.json
Labels: changelog/no-changelog

#5108 docs: clarify configuration env vars
  docs/configuration.rst
Labels: changelog/no-changelog

#5056 fix(lib-injection): wait and publish release tag of image [backport #4931, #5039 to 1.8]
  .github/workflows/build-and-publish-image.yml
  .github/workflows/build_deploy.yml
  .github/workflows/lib-injection.yml
  .gitlab-ci.yml
  releasenotes/notes/lib-injection-0041b50a263e1c19.yaml
  scripts/get_install_version.py
Labels: changelog/no-changelog

#5045 feat(asm): add IP blocking support for Flask
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/internal/remoteconfig/client.py
  releasenotes/notes/asm-flask-ip-blocking-a2416d04cacf71f3.yaml
  tests/contrib/flask/test_flask_snapshot.py
  tests/contrib/wsgi/test_wsgi.py
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200[flask_default_env].json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_200[flask_default_env]_220.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_get_user[flask_default_env].json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_get_user[flask_default_env]_220.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream[flask_default_env].json
  tests/snapshots/tests.contrib.flask.test_flask_snapshot.test_flask_stream[flask_default_env]_220.json
Labels: ASM

#4746 feat(debugger): add support for dynamic log line probe
  ddtrace/debugging/_async.py
  ddtrace/debugging/_capture/__init__.py
  ddtrace/debugging/_capture/collector.py
  ddtrace/debugging/_capture/metric_sample.py
  ddtrace/debugging/_capture/model.py
  ddtrace/debugging/_capture/snapshot.py
  ddtrace/debugging/_capture/utils.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_probe/status.py
  ddtrace/debugging/_snapshot/collector.py
  ddtrace/debugging/_snapshot/model.py
  releasenotes/notes/add-debugger-log-probe-2eaadf0e5df1c437.yaml
  tests/debugging/capture/__init__.py
  tests/debugging/capture/test_collector.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/debugger.py
  tests/debugging/mocking.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/py35/test_async.py
  tests/debugging/snapshot/test_collector.py
  tests/debugging/test_debugger.py
  tests/debugging/test_encoding.py
  tests/debugging/test_uploader.py
  tests/debugging/utils.py
Labels: Dynamic Instrumentation

#5121 chore(iast): add operator replacement capacity for the ast to iast
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_ast/visitor.py
  tests/appsec/iast/ast/test_ast_patching.py
  tests/appsec/iast/fixtures/aspects/add_operator/basic.py
Labels: changelog/no-changelog, ASM

#4903 docs: span component tag
  docs/contributing.rst
Labels: changelog/no-changelog

#5117 chore(ci): remove backport action
  .github/workflows/backport.yml
Labels: changelog/no-changelog

#5038 refactor(telemetry): improve maintainability and performance
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/conftest.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#5002 chore: add guild as codeowners of shared files
  .github/CODEOWNERS
Labels: changelog/no-changelog

#5129 chore(tests): add iast add operator aspect tests
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  tests/appsec/iast/aspects/test_add_aspect.py
Labels: changelog/no-changelog, ASM

#5127 feat(ci): test merge queues: move non-conflicting data around
  merge.json
Labels: changelog/no-changelog

#5128 feat(ci): test merge queues: change some data around
  merge.json
Labels: changelog/no-changelog

#5110 ci(debugger): automatic demo service deployment
  .gitlab-ci.yml
Labels: changelog/no-changelog, Dynamic Instrumentation

#5137 fix(telemetry): debug field should be set to a boolean
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#5141 chore(asm): rules update 1.5.1
  ddtrace/appsec/rules.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#5136 chore(asm): refactor and add callback in appsec span processor for suspicious request blocking
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/processor.py
  tests/appsec/test_processor.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
Labels: changelog/no-changelog, ASM

#5135 fix(gevent): unload time but not typing modules for module cloning
  ddtrace/bootstrap/sitecustomize.py
Labels: changelog/no-changelog

#5138 chore(benchmarks): remove threading, http-propagation scenarios from benchmark platform
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#5077 chore(asm): enable ast patching at module import
  ddtrace/appsec/iast/_ast/ast_patching.py
  ddtrace/appsec/iast/_loader.py
  ddtrace/appsec/iast/_util.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/internal/module.py
  tests/appsec/iast/ast/test_ast_patching.py
  tests/appsec/iast/fixtures/aspects/str/future_import_class_str.py
  tests/appsec/iast/fixtures/aspects/str/future_import_function_str.py
  tests/appsec/iast/fixtures/integration/main_gevent.py
  tests/appsec/iast/test_env_var.py
Labels: changelog/no-changelog, ASM

#5133 chore(asm): iast chapter 1 taint tracking skeleton
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_taint_tracking/_taint_tracking.cpp
  hooks/pre-commit/05-run-clang-format
  hooks/scripts/run-clang-format.sh
  setup.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM

#5078 chore(tracing): add `db.system` tag to memcached integrations
  ddtrace/contrib/pylibmc/client.py
  ddtrace/contrib/pymemcache/client.py
  ddtrace/ext/memcached.py
  tests/contrib/pylibmc/test.py
  tests/contrib/pymemcache/test_client_mixin.py
Labels: changelog/no-changelog, Tracing

#5150 test: improve stream checks for subprocess tests
  tests/conftest.py
Labels: changelog/no-changelog

#5145 chore(asm): move ASM Django snapshot tests to specific appsec test file
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/contrib/django/test_django_snapshots.py
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
Labels: changelog/no-changelog, ASM

#5153 chore(profiler): remove resolved known issue for profiler on Python 3.11
  releasenotes/notes/prof-3-11-traceback-issue-20e06214d4a3879b.yaml
Labels: changelog/no-changelog

#5154 chore(profiler): remove resolved known issue for profiler on Python 3.11 [backport #5153 to 1.8]
  releasenotes/notes/prof-3-11-traceback-issue-20e06214d4a3879b.yaml
Labels: changelog/no-changelog

#5161 chore(ci): update fastapi framework test suite to latest version 0.92.0
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5160 chore(ci): update uwsgi framework test from ubuntu-18.04 to ubuntu-latest
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5149 chore(asm): update to libddwaf 1.8.2
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/ddwaf/ddwaf_types.py
  ddtrace/appsec/processor.py
  setup.py
  tests/appsec/test_processor.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#5158 chore(asm): small refactor of waf_callback
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/processor.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#5156 chore(asm): iast chapter 1 taint tracking ranges
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_taint_tracking/_taint_tracking.cpp
  ddtrace/appsec/iast/input_info.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM

#5151 chore(ci): ensure we wait on graphene and internal for code coverage
  .circleci/config.yml
Labels: changelog/no-changelog

#5079 chore(tracing): add `db.system` tag to mysql integrations
  ddtrace/contrib/aiomysql/patch.py
  ddtrace/contrib/mysql/patch.py
  ddtrace/contrib/mysqldb/patch.py
  ddtrace/contrib/pymysql/patch.py
  ddtrace/ext/db.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysqldb.py
  tests/contrib/pymysql/test_pymysql.py
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_async_with_usage.json
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_pin_override[True].json
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_queries.json
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_user_specified_service.json
Labels: changelog/no-changelog, Tracing

#5097 chore(ciapp): print stack trace for git errors only in debug
  ddtrace/ext/ci.py
  ddtrace/ext/git.py
Labels: changelog/no-changelog, CI App

#5169 chore(asm): keep handle even if they are errors at initialisation
  ddtrace/appsec/ddwaf/__init__.py
Labels: changelog/no-changelog, ASM

#5168 chore(asm): iast chapter 1 avoid string interning for tainted objects
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_taint_tracking/_taint_tracking.cpp
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM

#5134 chore(asm): store block callable into ASM context
  ddtrace/appsec/_asm_request_context.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/flask/patch.py
  tests/appsec/test_asm_request_context.py
  tests/contrib/django/django1_app/urls.py
  tests/contrib/django/django_app/urls.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/views.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM

#5170 fix(rcm): error in capabilities
  ddtrace/appsec/utils.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#5171 chore(asm): keep waf context during request
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/processor.py
Labels: changelog/no-changelog, ASM

#5175 fix(asm): skip compilation of _taint_tracking for Windows OS
  setup.py
Labels: changelog/no-changelog

#5178 ci(graphql): reduce test runs from 16mins to 3mins
  .circleci/config.yml
Labels: changelog/no-changelog

#5174 chore(asm): make input_info module private
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_input_info.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM

#5180 chore(rcm): cyclomatic complexity in remote config client
  ddtrace/internal/remoteconfig/client.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
Labels: changelog/no-changelog, ASM

#5080 chore(tracing): add `db.system` tag to postgres-specific integrations
  ddtrace/contrib/aiopg/connection.py
  ddtrace/contrib/asyncpg/patch.py
  ddtrace/contrib/psycopg/connection.py
  ddtrace/contrib/psycopg/patch.py
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_bad_connect.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_bad_query.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_configure_service_name_env.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_connect.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_connection_methods.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_cursor.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_cursor_manual.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_parenting.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_select.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_service_override_pin.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_psycopg_query_default.json
  tests/snapshots/tests.contrib.psycopg.test_psycopg.test_composed_query_encoding.json
  tests/snapshots/tests.contrib.psycopg.test_psycopg.test_postgres_dbm_propagation_tag.json
  tests/snapshots/tests.contrib.psycopg.test_psycopg_snapshot.test_connect_traced.json
Labels: changelog/no-changelog, Tracing

#5186 chore(asm): make input_info private [backport #5174 to 1.9]
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_input_info.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog

#5187 ci(asm): fix failing django system test
  ddtrace/contrib/django/patch.py
Labels: changelog/no-changelog, ASM

#5142 chore(debugging): drop `active` attribute from probe model
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/registry.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/internal/remoteconfig/client.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/utils.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5165 ci(profiling): fix deque mutated during iteration error
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog

#5182 fix(profiling): ignore race condition during process shutdown
  ddtrace/profiling/collector/memalloc.py
  releasenotes/notes/fix-profiler-shutdown-race-a4540e18ce2af993.yaml
Labels: Profiling

#5192 fix(rcm): fix flaky rcm test
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#5143 chore(debugging): ensure correct log probe configuration handling
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/remoteconfig.py
  tests/debugging/probe/test_remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5144 chore(docs): clarify a few things about local testing in the readme
  README.md
Labels: changelog/no-changelog

#5189 chore(lib-injection): use provided delay, retry options
  .gitlab-ci.yml
Labels: changelog/no-changelog

#5087 chore(tracing): add `db.system` tag to remaining integrations
  ddtrace/contrib/cassandra/session.py
  ddtrace/contrib/mariadb/patch.py
  ddtrace/contrib/sqlite3/patch.py
  tests/contrib/cassandra/test.py
  tests/contrib/mariadb/test_mariadb.py
  tests/contrib/sqlite3/test_sqlite3.py
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_analytics_with_rate_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_analytics_with_rate_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_analytics_without_rate_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_analytics_without_rate_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_commit_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_commit_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_query_many_fetchall_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_query_many_fetchall_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_query_proc_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_query_proc_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_query_with_several_rows_fetchall_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_query_with_several_rows_fetchall_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_query_with_several_rows_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_query_with_several_rows_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_simple_malformed_query_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_simple_malformed_query_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_simple_query_fetchall_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_simple_query_fetchall_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_simple_query_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_simple_query_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_mariadb_service_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_mariadb_service_snapshot_pre_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_service_snapshot_post_1_1.json
  tests/snapshots/tests.contrib.mariadb.test_mariadb.test_user_specified_dd_service_snapshot_pre_1_1.json
Labels: changelog/no-changelog, Tracing

#5196 feat(asm): suspicious request blocking
  ddtrace/appsec/utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  releasenotes/notes/suspicious_request_blocking-dd220e9cc860c3ca.yaml
  tests/appsec/test_remoteconfiguration.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/contrib/flask/test_flask_appsec.py
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: ASM

#5211 chore(asm): use parsable body for django srb tests
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5066 test(lib-injection): fix the version of tests used [backport to 1.6]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#5086 chore(tracing): add `db.system` tag to vendor-specific integrations
  ddtrace/contrib/pynamodb/patch.py
  ddtrace/contrib/snowflake/patch.py
  ddtrace/contrib/vertica/patch.py
  tests/contrib/pynamodb/test_pynamodb.py
  tests/contrib/vertica/test_vertica.py
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_analytics_with_rate.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_analytics_without_rate.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_commit.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_executemany_insert.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_fetchall.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_fetchall_multiple_rows.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_fetchone.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_ot_executemany_insert.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_ot_fetchall.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_ot_fetchall_multiple_rows.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_ot_fetchone.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_rollback.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_service_env.json
  tests/snapshots/tests.contrib.snowflake.test_snowflake.test_snowflake_settings_override.json
Labels: changelog/no-changelog, Tracing

#5179 ci(integrations): bump the parallelism of tests
  .circleci/config.yml
Labels: changelog/no-changelog

#5197 chore(docs): add a contributing section about how to generate test snapshots
  docs/contributing.rst
Labels: changelog/no-changelog

#5177 ci(celery): wait 500ms before attempting to flush async spans
  tests/contrib/celery/test_integration.py
Labels: changelog/no-changelog

#5053 feat(tracing): add db.row_count to pymongo integration
  .circleci/dependencies.py
  ddtrace/contrib/pymongo/client.py
  ddtrace/ext/mongo.py
  releasenotes/notes/deprecate-mongodb-rows-constant-16e2c043bfdbca9b.yaml
  tests/contrib/pymongo/test.py
Labels: changelog/no-changelog

#5216 chore(asm): fix loaded rules metric
  ddtrace/appsec/processor.py
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#5200 chore(debugger): update metric name to match dynamic instrumentation web-ui
  ddtrace/debugging/_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5089 chore(tracing): add `db.system` tag to mongodb integrations
  ddtrace/contrib/pymongo/client.py
  ddtrace/contrib/pymongo/patch.py
  tests/contrib/mongoengine/test.py
  tests/contrib/pymongo/test.py
Labels: changelog/no-changelog, Tracing

#5052 chore: adding db.row_count for caching integrations
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/dogpile_cache/region.py
  ddtrace/contrib/flask_cache/tracers.py
  ddtrace/contrib/pylibmc/client.py
  ddtrace/contrib/pymemcache/client.py
  ddtrace/internal/compat.py
  tests/contrib/django/test_django.py
  tests/contrib/dogpile_cache/test_tracing.py
  tests/contrib/flask_cache/test.py
  tests/contrib/pylibmc/test.py
  tests/contrib/pymemcache/test_client.py
  tests/contrib/pymemcache/test_client_mixin.py
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_111x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_18x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_21x.json
Labels: changelog/no-changelog

#5193 chore(ci): increase the system tests coverage
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, ASM

#5191 feat(telemetry): telemetry metrics support
  benchmarks/flask_simple/config.yaml
  benchmarks/flask_simple/gunicorn.conf.py
  benchmarks/flask_simple/scenario.py
  benchmarks/flask_simple/utils.py
  ddtrace/internal/telemetry/__init__.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/metrics.py
  ddtrace/internal/telemetry/metrics_namespaces.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/utils/version.py
  ddtrace/internal/writer.py
  ddtrace/settings/config.py
  tests/internal/test_module.py
  tests/telemetry/conftest.py
  tests/telemetry/test_telemetry_metrics.py
  tests/telemetry/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#5123 chore(ci): refactor testrunner workflow
  .github/workflows/docker.yml
  .github/workflows/testrunner.yml
  docker/Dockerfile
Labels: changelog/no-changelog

#5225 chore(ci): timeout django test suite after 30 minutes
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5222 docs: fix DD_TAGS example in doc
  docs/configuration.rst
Labels: changelog/no-changelog

#5226 chore(telemetry): add enabled field to application.products
  ddtrace/internal/telemetry/data.py
  tests/telemetry/test_data.py
Labels: changelog/no-changelog
