Repository DataDog/dd-trace-py, pull requests merged in 2023-09, with the labels that each got.

#6798 fix(profiling): ensure correct thread link
  ddtrace/profiling/_threading.pyx
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-profiler-thread-link-cbe14bf53e6071db.yaml
Labels: Profiling, backport 1.17, backport 1.18

#6805 feat(asm): add trusted ips feature
  ddtrace/appsec/_capabilities.py
  releasenotes/notes/asm_trusted_ips-cd37d9c4cab70c24.yaml
  tests/appsec/rules-good.json
  tests/appsec/test_processor.py
  tests/appsec/test_remoteconfiguration.py
  tests/appsec/test_telemetry.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/flask/test_flask_appsec_telemetry.py
Labels: ASM

#6760 chore(asm): force compliance and improve regex for query strings
  .github/workflows/system-tests.yml
  ddtrace/internal/telemetry/constants.py
  ddtrace/settings/config.py
  docs/advanced_usage.rst
  docs/configuration.rst
  releasenotes/notes/querystring_improved_sensitive_data_information-b055d0cda09da1c5.yaml
  tests/telemetry/test_writer.py
  tests/tracer/test_env_vars.py
Labels: manual merge, ASM

#6816 fix(profiling): ensure correct thread link [backport #6798 to 1.17]
  ddtrace/profiling/_threading.pyx
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-profiler-thread-link-cbe14bf53e6071db.yaml
Labels: Profiling

#6819 chore(asm): update test dependencies for flask and django
  tests/.suitespec.json
Labels: changelog/no-changelog

#6612 chore(logging): remove DD_CALL_BASIC_CONFIG
  ddtrace/_logger.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  docs/configuration.rst
  lib-injection/docker-compose.yml
  releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
  releasenotes/notes/remove-deprecated-items-2.0-89eac06472c59554.yaml
  tests/commands/ddtrace_run_logs_injection.py
  tests/commands/test_runner.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/logging/test_tracer_logging.py
  tests/integration/test_debug.py
  tests/integration/test_integration.py
  tests/lib-injection/dd-lib-python-init-test-django-gunicorn-alpine/django_app.py
  tests/lib-injection/dd-lib-python-init-test-django-gunicorn/django_app.py
  tests/lib-injection/dd-lib-python-init-test-django-no-perms/django_app.py
  tests/lib-injection/dd-lib-python-init-test-django-pre-installed/django_app.py
  tests/lib-injection/dd-lib-python-init-test-django-uvicorn/django_app.py
  tests/lib-injection/dd-lib-python-init-test-django/django_app.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#6681 chore(telemetry): track remote config values
  ddtrace/appsec/_capabilities.py
  ddtrace/appsec/utils.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/debugging/_debugger.py
  ddtrace/internal/debug.py
  ddtrace/internal/remoteconfig/utils.py
  ddtrace/internal/remoteconfig/worker.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  tests/appsec/test_remoteconfiguration.py
  tests/commands/test_runner.py
  tests/internal/remoteconfig/__init__.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
  tests/internal/remoteconfig/test_remoteconfig_subscriber.py
  tests/telemetry/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog

#6818 ci: use pagination to retrieve complete list of changed files
  scripts/needs_testrun.py
Labels: changelog/no-changelog, backport 1.18

#6808 fix(ci-visibility): use unicode strings and values for spans payload so msgpack is correct
  ddtrace/internal/ci_visibility/encoder.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix_civisibility_py27-62e8bb558f4c6e47.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: backport 1.17, backport 1.18

#6826 chore(dev): fix version for trunk branch
  pyproject.toml
  setup.py
Labels: changelog/no-changelog

#6832 chore(tracer): unpin system-tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#6809 chore: remove priority sampler
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/debug.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  tests/commands/ddtrace_run_priority_sampling.py
  tests/integration/test_debug.py
  tests/integration/test_integration_snapshots.py
  tests/integration/test_priority_sampling.py
  tests/integration/test_sampling.py
  tests/tracer/test_sampler.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#6814 chore(telemetry): avoid unregistering TelemetryWriter.stop
  ddtrace/internal/telemetry/writer.py
Labels: changelog/no-changelog

#6817 chore(ci-visibility): add session-level and module-level ITR-related tags
  ddtrace/contrib/pytest/plugin.py
  ddtrace/ext/test.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog

#6825 chore(devex): use hatch lint:style instead of individual scripts in commit hooks
  hatch.toml
  hooks/pre-commit/01-run-black
  hooks/pre-commit/01-style
  hooks/pre-commit/03-run-codespell
  hooks/pre-commit/03-run-flake8
  hooks/pre-commit/04-run-clang-format
  hooks/scripts/run-fmt.sh
  hooks/scripts/run-style.sh
Labels: changelog/no-changelog

#6841 fix(iast): memory leak on propagation functions
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.cpp
  tests/appsec/iast/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#6842 docs: pin furo in readthedocs
  docs/requirements.txt
  hatch.toml
Labels: changelog/no-changelog, backport 1.17, backport 1.18

#6669 fix: avoid crashing when asm env doesnt exist during finalise()
  ddtrace/appsec/_asm_request_context.py
  releasenotes/notes/missing-asm-env-9a2eaa4936c35e0d.yaml
Labels: backport 1.17, backport 1.18

#6837 docs: how to use the core api
  ddtrace/internal/core.py
  docs/contributing-integrations.rst
  docs/contributing-tracing.rst
  docs/contributing.rst
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog

#6834 chore(ci-visibility): add pytest Intelligent Test Runner support for unskippable tests and suites
  ddtrace/contrib/pytest/plugin.py
  ddtrace/ext/test.py
  ddtrace/internal/ci_visibility/constants.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog

#6840 chore(asm): update libddwaf to 1.14.0
  ddtrace/appsec/_api_security/processors.json
  ddtrace/appsec/_constants.py
  ddtrace/appsec/processor.py
  setup.py
  tests/appsec/api_security/test_schema_fuzz.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#6844 ci: ignore flapping attribute in django snapshot tests
  tests/contrib/django/test_django_snapshots.py
Labels: changelog/no-changelog

#6855 chore(asm): add cookies support for api_security
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_api_security/processors.json
  ddtrace/appsec/_constants.py
  tests/contrib/django/test_django_appsec_api_security.py
  tests/contrib/flask/test_appsec_api_security.py
Labels: changelog/no-changelog, ASM

#6851 chore(ci-visibility): update ci_visibility and unittest suite dependencies
  tests/.suitespec.json
Labels: changelog/no-changelog

#6852 chore(tracer): fix setup.py for pre-commit scripts
  setup.py
Labels: changelog/no-changelog

#6829 ci: use pagination to retrieve complete list of changed files [backport #6818 to 1.18]
  scripts/needs_testrun.py
Labels: changelog/no-changelog, backport 1.18

#6862 fix(lib-inject): use alpine base image
  lib-injection/Dockerfile
  releasenotes/notes/lib-inject-8dcd6537312fddf3.yaml
Labels: backport 1.18

#6833 ci: make configuration generation script fail on error
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog, backport 1.18

#6781 docs(debugging): improve enablement docs wording
  ddtrace/debugging/__init__.py
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog, Dynamic Instrumentation

#6820 chore(telemetry): track partial flushing configurations
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  tests/opentracer/core/test_tracer.py
  tests/telemetry/test_writer.py
  tests/tracer/test_tracer.py
  tests/utils.py
Labels: changelog/no-changelog

#6867 ci: use single resource to decrease benchmark memory usage
  benchmarks/sampling_rule_matches/config.yaml
Labels: changelog/no-changelog

#6869 chore(sampling): remove config and release note for resource matching
  docs/configuration.rst
  releasenotes/notes/resource-sampling-f80db0b13d995c83.yaml
Labels: changelog/no-changelog, backport 1.19

#6178 refactor(writer): handle agent responses in the tracer
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/__init__.py
  ddtrace/internal/writer/writer.py
  ddtrace/tracer.py
Labels: changelog/no-changelog

#6849 chore(iast): refactor cpp code
  ddtrace/appsec/iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/iast/_taint_tracking/Context/Context.cpp
  ddtrace/appsec/iast/_taint_tracking/Context/Context.h
  ddtrace/appsec/iast/_taint_tracking/Context/GlobalContext.cpp
  ddtrace/appsec/iast/_taint_tracking/Context/GlobalContext.h
  ddtrace/appsec/iast/_taint_tracking/Context/_context.h
  ddtrace/appsec/iast/_taint_tracking/Exceptions/_exceptions.h
  ddtrace/appsec/iast/_taint_tracking/Exceptions/exceptions.h
  ddtrace/appsec/iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintedObject.h
  ddtrace/appsec/iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/_taint_tracking/_native.cpp
  ddtrace/appsec/iast/processor.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_common_replace_aspects.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/test_iast_mem_check.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6874 chore(asm): security scanners for api security
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_api_security/processors.json
  ddtrace/appsec/_constants.py
  ddtrace/appsec/processor.py
  tests/appsec/api_security/test_schema_fuzz.py
Labels: changelog/no-changelog, ASM

#6823 feat(tracing): allow sampling based on tags
  benchmarks/sampling_rule_matches/config.yaml
  benchmarks/sampling_rule_matches/scenario.py
  ddtrace/sampler.py
  ddtrace/sampling_rule.py
  docs/configuration.rst
  tests/integration/test_debug.py
  tests/integration/test_sampling.py
  tests/snapshots/test_extended_sampling_tags.json
  tests/snapshots/test_extended_sampling_tags_and_resource.json
  tests/snapshots/test_extended_sampling_tags_glob.json
  tests/tracer/test_sampler.py
Labels: changelog/no-changelog

#6813 chore(kafka): migrate kafka datastreams to Core API
  ddtrace/contrib/kafka/patch.py
  ddtrace/internal/datastreams/__init__.py
  ddtrace/internal/datastreams/kafka.py
  tests/contrib/kafka/test_kafka.py
Labels: changelog/no-changelog

#6877 chore(ci): fix sdist build
  .github/workflows/build_deploy.yml
  setup.py
Labels: changelog/no-changelog

#6879 ci(sqlalchemy/starlette): add back missing constant
  ddtrace/ext/sql.py
  tests/.suitespec.json
Labels: changelog/no-changelog

#6824 chore(telemetry): track agent connection configurations
  ddtrace/internal/agent.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/constants.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/utils/http.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  tests/profiling/test_profiler.py
  tests/telemetry/test_writer.py
  tests/tracer/test_agent.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#6876 feat(iast): private beta release notes
  releasenotes/notes/iast-private-beta-20fe19c2dff7862e.yaml
Labels: ASM, Custom Code Private Beta

#6873 chore(iast): address compilation warnings
  ddtrace/appsec/iast/_stacktrace.c
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/Source.cpp
Labels: changelog/no-changelog, ASM

#6882 chore(ci): fix precheck
  tests/suitespec.py
Labels: changelog/no-changelog, CI

#6860 feat(iast): cmdi and path traversal redaction
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/Source.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/Source.h
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/appsec/iast/taint_sinks/command_injection.py
  ddtrace/appsec/iast/taint_sinks/path_traversal.py
  ddtrace/appsec/iast/taint_sinks/sql_injection.py
  ddtrace/appsec/iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/iast/taint_sinks/weak_hash.py
  setup.cfg
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/taint_sinks/redaction_fixtures/evidence-redaction-suite.json
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/taint_sinks/test_command_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_path_traversal_redacted.py
  tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py
  tests/appsec/iast/test_reporter.py
  tests/appsec/iast/test_taint_tracking.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6886 chore(internal): reduce log volume from core api
  ddtrace/internal/core.py
Labels: changelog/no-changelog, backport 1.19

#6881 chore: delay the generation of start up logs
  ddtrace/bootstrap/sitecustomize.py
Labels: changelog/no-changelog

#6884 feat(asm): redirect requests for custom blocking
  ddtrace/appsec/_constants.py
  ddtrace/appsec/processor.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/tracing/trace_handlers.py
  releasenotes/notes/custom_blocking_redirect_request-fcd032a01ed10894.yaml
  tests/appsec/rules-suspicious-requests-custom-actions.json
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
Labels: ASM

#6887 fix(iast): invalid line number on insecure cookie report
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/_utils.py
  ddtrace/appsec/iast/processor.py
  ddtrace/appsec/iast/reporter.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  tests/appsec/iast/taint_sinks/test_insecure_cookie.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6899 refactor(iast): refactor imports to make them local
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/iast/__init__.py
  ddtrace/appsec/iast/_ast/ast_patching.py
  ddtrace/appsec/iast/_ast/visitor.py
  ddtrace/appsec/iast/_metrics.py
  ddtrace/appsec/iast/_patch.py
  ddtrace/appsec/iast/_patches/json_tainting.py
  ddtrace/appsec/iast/_taint_dict.py
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/_taint_tracking/aspects.py
  ddtrace/appsec/iast/_taint_utils.py
  ddtrace/appsec/iast/processor.py
  ddtrace/appsec/iast/taint_sinks/__init__.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/appsec/iast/taint_sinks/command_injection.py
  ddtrace/appsec/iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/iast/taint_sinks/path_traversal.py
  ddtrace/appsec/iast/taint_sinks/sql_injection.py
  ddtrace/appsec/iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/iast/taint_sinks/weak_hash.py
Labels: changelog/no-changelog, ASM

#6896 chore(ci): fix precheck (#6882) [backport 1.19]
  tests/suitespec.py
Labels: changelog/no-changelog

#6898 fix(benchmark/iast): fix import error in propagation scenario
  benchmarks/appsec_iast_propagation/scenario.py
Labels: changelog/no-changelog, ASM

#6878 fix(kafka): ensures Consumer.poll is called with the expected arguments
  ddtrace/contrib/kafka/patch.py
  releasenotes/notes/fix-kafka-poll-default-31627d2fc9a83d95.yaml
Labels: backport 1.18, backport 1.19

#6810 refactor(debugging): make safety module internal
  ddtrace/debugging/_expressions.py
  ddtrace/debugging/_safety.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_signal/snapshot.py
  ddtrace/debugging/_signal/utils.py
  tests/debugging/test_safety.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6839 test(debugging): make RCM data flow synchronous
  tests/debugging/probe/test_remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation, backport 1.18, backport 1.19

#6835 chore(debugging): add RESUME to functions generated by DSL
  ddtrace/debugging/_expressions.py
Labels: changelog/no-changelog, Dynamic Instrumentation, backport 1.16, backport 1.17, backport 1.18, backport 1.19

#6891 fix(openai): ensure streamed spans with error are manually finished
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/contrib/openai/patch.py
  releasenotes/notes/fix-openai-stream-error-unfinished-span-d62df398912b0f56.yaml
  tests/contrib/openai/cassettes/completion_stream_wrong_api_key.yaml
  tests/contrib/openai/test_openai.py
  tests/snapshots/tests.contrib.openai.test_openai.test_span_finish_on_stream_error.json
Labels: backport 1.17, backport 1.18, backport 1.19

#6889 chore(internal): reduce log volume from core api (#6886) [backport 1.19]
  ddtrace/internal/core.py
Labels: changelog/no-changelog

#6927 test(debugger): synchronous probe status generation
  tests/debugging/mocking.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation, backport 1.19

#6931 chore(debugging): general coding improvements
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/remoteconfig.py
  tests/debugging/exception/test_auto_instrument.py
  tests/debugging/probe/test_remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6935 ci(tracer): ensure only one tracer instance is used per span sampling test
  tests/tracer/test_single_span_sampling_rules.py
Labels: changelog/no-changelog, backport 1.19, backport 1.x

#6926 chore(ci): upload results to BP UI even when some benchmarks fail
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#6912 feat(iast): weak randomness vulnerability
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/taint_sinks/__init__.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/weak_randomness.py
  ddtrace/appsec/iast/_ast/__init__.py
  releasenotes/notes/iast-feat-weak-randomness-3c095863b2fddee8.yaml
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_random.py
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_random_module.py
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_random_secure_module.py
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_secrets.py
  tests/appsec/iast/taint_sinks/test_weak_randomness.py
Labels: ASM, Custom Code Private Beta

#6675 fix(profiling): detect and correct non-string Location fields
  ddtrace/internal/datadog/profiling/_ddup.pyx
  ddtrace/internal/datadog/profiling/ddup.py
  ddtrace/internal/datadog/profiling/utils.py
  ddtrace/profiling/exporter/pprof.pyx
  releasenotes/notes/fix-profiler-frame-strings-24a10dad43f25bc7.yaml
Labels: Profiling, backport 1.18, backport 1.19

#6933 chore(asm): api security sampling update
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_api_security/processors.json
  ddtrace/appsec/_constants.py
  tests/contrib/django/test_django_appsec_api_security.py
  tests/contrib/flask/test_appsec_api_security.py
Labels: changelog/no-changelog, ASM

#6946 chore(ci): don't delete Python 3.12 wheels when publishing to PyPI
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#6956 chore(release): update version to upgrade to
  releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
Labels: changelog/no-changelog

#6964 ci(docs): update deprecated interface anchor
  docs/upgrading.rst
  releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
Labels: changelog/no-changelog

#6957 chore(patching): fix monkey patching logs
  ddtrace/_monkey.py
Labels: changelog/no-changelog

#6970 chore(botocore): don't log an error when kinesis payload isn't json
  ddtrace/contrib/botocore/patch.py
Labels: changelog/no-changelog

#6940 chore(iast): add propagation for str aspect join
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.h
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
Labels: changelog/no-changelog, ASM

#6977 chore(iast): ast patching pass original callable
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  tests/appsec/iast/_ast/__init__.py
  tests/appsec/iast/_ast/fixtures/misleading_methods.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/_ast/test_proper_patching.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/contrib/django/django_app/appsec_urls.py
Labels: changelog/no-changelog, ASM

#6972 ci: fix build release actions
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, backport 2.0

#6941 ci: use pipe mode when calling riot run in run-test-suite
  scripts/run-test-suite
  tests/.suitespec.json
Labels: changelog/no-changelog, backport 1.17, backport 1.18, backport 1.19, backport 1.x

#6980 chore(docs): fix ref by turning it into a simple link
  docs/upgrading.rst
  releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
Labels: changelog/no-changelog

#6983 fix(docs): fix broken link to release note anchor
  docs/spelling_wordlist.txt
  docs/upgrading.rst
  releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
Labels: changelog/no-changelog

#6958 chore(release): update version to upgrade to (backport #6956 to 2.0)
  releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
Labels: changelog/no-changelog

#6984 ci: fix build release actions [backport 2.0]
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog

#6963 ci: fix readthedocs
  .readthedocs.yml
  docs/requirements.txt
  hatch.toml
  scripts/docs/install.sh
Labels: changelog/no-changelog, backport 1.20, backport 2.0

#6960 fix(graphql): resolves errors raised while parsing graphql asts
  ddtrace/contrib/graphql/patch.py
  releasenotes/notes/graphql-document-fix-ef580e19ff2c4db4.yaml
  tests/contrib/graphql/test_graphql.py
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_with_document_with_no_location.json
Labels: backport 1.19, backport 1.20, backport 2.0

#6988 feat(iast): weak randomness vulnerability [backport #6912 to 2.0]
  .github/workflows/system-tests.yml
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/taint_sinks/__init__.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/weak_randomness.py
  ddtrace/appsec/iast/_ast/__init__.py
  releasenotes/notes/iast-feat-weak-randomness-3c095863b2fddee8.yaml
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_random.py
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_random_module.py
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_random_secure_module.py
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_secrets.py
  tests/appsec/iast/taint_sinks/test_weak_randomness.py
Labels: changelog/no-changelog

#6975 chore(iast): expand path traversal functions
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  tests/appsec/iast/fixtures/taint_sinks/path_traversal.py
  tests/appsec/iast/fixtures/taint_sinks/weak_randomness_random_module.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6998 ci: use pipe mode when calling riot run in run-test-suite [backport 1.17]
  .circleci/config.yml
Labels: changelog/no-changelog

#6976 fix(kafka): avoid overriding methods in Producers and Consumers
  ddtrace/contrib/kafka/patch.py
  ddtrace/internal/utils/__init__.py
  releasenotes/notes/fix-kafka-commit-offsets-d86039c29e04259e.yaml
  tests/contrib/kafka/test_kafka.py
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_offset.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_only_async_arg.json
Labels: backport 1.19, backport 2.0

#7005 chore: pin setuptools_scm
  pyproject.toml
  setup.py
Labels: changelog/no-changelog, backport 1.18, backport 1.19, backport 1.20

#7012 chore: pin setuptools_scm [backport #7005 to 1.18]
  pyproject.toml
  setup.py
Labels: changelog/no-changelog

#6995 chore(kinesis): don't log an error when kinesis payload isn't json [backport to 1.19]
  ddtrace/contrib/botocore/patch.py
Labels: changelog/no-changelog

#6994 fix(redis): don't use unbound variable
  ddtrace/contrib/redis/asyncio_patch.py
  ddtrace/contrib/trace_utils_redis.py
  releasenotes/notes/fix-redis-exception-handling-32964d6cc673c7bc.yaml
  tests/contrib/redis/test_redis.py
  tests/contrib/redis/test_redis_asyncio.py
  tests/snapshots/tests.contrib.redis.test_redis_asyncio.test_connection_error.json
Labels: backport 1.20, backport 2.0

#7018 chore: update circleci badge
  README.md
Labels: changelog/no-changelog, backport 2.0

#7023 ci: add pipe mode to more CI utils using riot
  .circleci/config.templ.yml
  .circleci/config.yml
  scripts/compile-and-prune-test-requirements
Labels: changelog/no-changelog, backport 1.18, backport 1.19, backport 1.20, backport 2.0

#6962 chore(dbm): use peer.service precursor when enabled
  ddtrace/propagation/_database_monitoring.py
  releasenotes/notes/dbm-fix-for-peer-service-ea46572a0daa08ec.yaml
  tests/internal/test_database_monitoring.py
Labels: backport 1.17, backport 1.18, backport 1.19

#7017 chore(release): make script support 1.x and 2.x releases
  scripts/release.py
Labels: changelog/no-changelog

#7022 fix(internal): bytecode wrapping for Python 3.11
  ddtrace/internal/wrapping.py
  ddtrace/internal/wrapping/__init__.py
  ddtrace/internal/wrapping/asyncs.py
  ddtrace/internal/wrapping/generators.py
  pyproject.toml
  releasenotes/notes/fix-py311-wrapping-50ad976978cc315e.yaml
  tests/internal/test_wrapping.py
Labels: backport 1.20, backport 2.0

#7036 ci: reflect scripts/run-test-suite fix harness dependency in suitespec test [backport 1.18]
  scripts/gen_circleci_config.py
  tests/suitespec.py
Labels: changelog/no-changelog

#7035 chore(testing): add 3.12-dev testing
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#7042 fix(dbm): ensure peer service is str for py2.7
  ddtrace/propagation/_database_monitoring.py
Labels: changelog/no-changelog

#7037 chore(asm): improve waf interface
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_processor.py
Labels: changelog/no-changelog, ASM

#6924 chore: login info retriever refactor
  ddtrace/appsec/_utils.py
  ddtrace/contrib/django/patch.py
Labels: changelog/no-changelog, ASM

#7044 fix(internal): closure bytecode wrapping for Python 3.11
  ddtrace/internal/wrapping/__init__.py
  releasenotes/notes/fix-py311-closure-wrapping-fed33b584d65a844.yaml
  tests/internal/test_wrapping.py
Labels: backport 1.20, backport 2.0

#7045 ci: add pipe mode to more CI utils using riot [backport 1.18]
  .circleci/config.templ.yml
  .circleci/config.yml
  scripts/compile-and-prune-test-requirements
Labels: changelog/no-changelog

#7046 ci: add pipe mode to more CI utils using riot [backport 1.19]
  .circleci/config.templ.yml
  .circleci/config.yml
  scripts/compile-and-prune-test-requirements
Labels: changelog/no-changelog

#7047 ci: add pipe mode to more CI utils using riot [backport 1.20]
  .circleci/config.templ.yml
  .circleci/config.yml
  scripts/compile-and-prune-test-requirements
Labels: changelog/no-changelog

#7039 chore(iast): debug mode doesn't require abseil compilation
  ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  setup.py
Labels: changelog/no-changelog, ASM

#7043 fix(telemetry): support python3.12
  ddtrace/internal/processor/trace.py
  ddtrace/internal/telemetry/__init__.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  tests/appsec/conftest.py
  tests/telemetry/app.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, backport 2.0

#7057 ci(redis): fix python<3.7 support
  ddtrace/internal/compat.py
  tests/contrib/redis/test_redis.py
Labels: changelog/no-changelog

#7053 chore(ci): fix scheduled system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#7038 fix(profiling): avoid possible circular import
  ddtrace/profiling/exporter/pprof.pyx
Labels: changelog/no-changelog, backport 1.19, backport 1.20, backport 2.0

#6932 test(debugger): synchronous probe status generation [backport #6927 to 1.19]
  tests/debugging/mocking.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation, backport 1.19

#6929 feat(tracer): collect and report multiple service names
  ddtrace/internal/remoteconfig/client.py
  ddtrace/pin.py
  ddtrace/settings/config.py
  releasenotes/notes/collect_extra_service_names-453190f684d62070.yaml
  tests/contrib/flask/test_flask_appsec.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
  tests/internal/service_name/test_extra_services_names.py
Labels: enhancement

#6948 chore(debugging): quote query string in uploader URL
  ddtrace/debugging/_uploader.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#7050 feat(iast): index propagation
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.h
  ddtrace/appsec/_iast/_taint_tracking/README.txt
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
Labels: changelog/no-changelog, ASM

#7049 fix(internal): bytecode wrapping for Python 3.11 [backport #7022 to 1.20]
  ddtrace/internal/wrapping.py
  ddtrace/internal/wrapping/__init__.py
  ddtrace/internal/wrapping/asyncs.py
  ddtrace/internal/wrapping/generators.py
  pyproject.toml
  releasenotes/notes/fix-py311-wrapping-50ad976978cc315e.yaml
  tests/internal/test_wrapping.py
Labels: backport 1.18, backport 1.19

#7060 chore(tracer): limit memory usage for extra services reports
  ddtrace/settings/config.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog

#6925 fix(internal): do not replace sys.modules
  ddtrace/internal/module.py
  releasenotes/notes/fix-module-watchdog-no-sys-module-replacement-0e019c59ad745244.yaml
  tests/contrib/patch.py
  tests/debugging/test_debugger.py
  tests/internal/test_module.py
Labels: backport 1.19, backport 1.20, backport 2.0

#7048 ci: add circle CI directory to harness suite
  tests/.suitespec.json
  tests/suitespec.py
Labels: changelog/no-changelog

#7051 ci: error out if no riot hashes are found when running test suites
  scripts/run-test-suite
Labels: changelog/no-changelog

#7065 fix(internal): closure bytecode wrapping for Python 3.11 [backport #7044 to 1.20]
  ddtrace/internal/wrapping/__init__.py
  releasenotes/notes/fix-py311-closure-wrapping-fed33b584d65a844.yaml
  tests/internal/test_wrapping.py
Labels: backport 1.18, backport 1.19

#7074 chore(tracer): revert "limit memory usage for extra services reports"
  ddtrace/settings/config.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog

#7076 chore(rcm): fix remote config extra service name test
  ddtrace/settings/config.py
  tests/contrib/flask/test_flask_appsec.py
  tests/internal/service_name/test_extra_services_names.py
Labels: changelog/no-changelog, ASM

#6858 fix(wsgi): handle django wsgi app being an iterator
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/tracing/trace_handlers.py
  docs/spelling_wordlist.txt
  releasenotes/notes/wsgi-iter-cca70a8d4429e925.yaml
  tests/.suitespec.json
  tests/contrib/django/test_django_wsgi.py
Labels: backport 1.16, backport 1.17, backport 1.18

#7054 fix(openai): safely tag potentially null chat completion message
  ddtrace/contrib/openai/_endpoint_hooks.py
  releasenotes/notes/fix-openai-chat-completion-empty-message-fdd7c70643cf366f.yaml
  tests/contrib/openai/cassettes/chat_completion_function_call.yaml
  tests/contrib/openai/test_openai.py
  tests/snapshots/tests.contrib.openai.test_openai.test_chat_completion_function_calling.json
Labels: backport 1.19, backport 1.20, backport 2.0

#7078 chore(propagation): deprecate b3 single header, use b3 instead
  ddtrace/internal/constants.py
  ddtrace/propagation/http.py
  ddtrace/settings/config.py
  releasenotes/notes/release-2.0-3af0045e2261bd02.yaml
  tests/tracer/test_global_config.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog, backport 2.0

#7064 chore(asm): rc logs to debug level
  ddtrace/internal/remoteconfig/worker.py
  releasenotes/notes/rc_logs_to_debug_level-13534746d9759332.yaml
Labels: backport 1.19, backport 1.x, backport 1.20, backport 2.0

#6611 feat(unittest): add full test suite level visibility for unittest
  .circleci/config.templ.yml
  ddtrace/contrib/unittest/__init__.py
  ddtrace/contrib/unittest/constants.py
  ddtrace/contrib/unittest/patch.py
  ddtrace/ext/test.py
  ddtrace/internal/ci_visibility/encoder.py
  ddtrace/settings/config.py
  releasenotes/notes/add-tslv-unittest-support-f2967051df9aa9aa.yaml
  riotfile.py
  tests/contrib/unittest_plugin/test_unittest.py
Labels: CI App

#7091 chore(asm): migrate ddwaf_types to drop python2 compatibility
  ddtrace/appsec/_ddwaf/ddwaf_types.py
Labels: changelog/no-changelog, ASM

#7093 feat(iast): slice propagation
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.h
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast/test_iast_mem_check.py
  tests/appsec/iast/test_iast_propagation_path.py
Labels: changelog/no-changelog, ASM

#7098 docs: append timestamp awareness to logs docs and example code
  ddtrace/contrib/logging/__init__.py
Labels: changelog/no-changelog

#7096 chore(tracer): defuse osx thread bomb
  ddtrace/settings/config.py
Labels: changelog/no-changelog

#7105 chore(ci): rollback simplification made on #7053
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#7103 chore(iast): remove new_pyobject_id param
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/taint_sinks/test_command_injection_redacted.py
Labels: changelog/no-changelog, ASM

#7102 chore(asm): migrate ddwaf_types to drop python2 compatibility
  ddtrace/appsec/_ddwaf/__init__.py
Labels: changelog/no-changelog, ASM

#7108 chore(ci): remove forgotten if at job level in system tests ci
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, backport 1.20, backport 2.0

#7089 fix(git): fix git version extraction
  ddtrace/ext/git.py
  releasenotes/notes/fix-git-version-extraction-8db3a639976e725c.yaml
  tests/tracer/test_ci.py
Labels: enhancement, CI App

#6978 fix(lib-injection): log only to stderr when in debug mode
  docs/spelling_wordlist.txt
  lib-injection/sitecustomize.py
  releasenotes/notes/lib-inject-logs-1b56f004763853f7.yaml
Labels: backport 1.20
