Repository DataDog/dd-trace-py, pull requests merged in 2023-04, with the labels that each got.

#5457 chore: better stop iteration handling in wrapping
  ddtrace/internal/wrapping.py
  tests/internal/py36/test_wrapping.py
  tests/internal/py37/__init__.py
  tests/internal/py37/test_wrapping.py
Labels: changelog/no-changelog

#5433 chore(tracing): adds support for logging the lower 64bit component of 128bit trace ids
  ddtrace/contrib/logging/patch.py
  ddtrace/settings/config.py
  tests/contrib/logging/test_logging.py
Labels: changelog/no-changelog

#5451 refactor(debugging): simplify line capture event API
  ddtrace/debugging/_capture/metric_sample.py
  ddtrace/debugging/_capture/model.py
  ddtrace/debugging/_capture/snapshot.py
  ddtrace/debugging/_capture/tracing.py
  ddtrace/debugging/_debugger.py
  tests/debugging/capture/test_collector.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5456 fix(opentelemetry): fix timestamps on otel spans
  ddtrace/_opentelemetry/span.py
  ddtrace/span.py
  tests/opentelemetry/test_span.py
Labels: changelog/no-changelog

#5421 fix(profiling): memalloc cleanup after final export
  ddtrace/profiling/collector/memalloc.py
  releasenotes/notes/fix-profiler-memory-collector-shutdown-118642abe59f8ae3.yaml
Labels: Profiling

#5446 feat(ci-visibility): refactor CI Visibility into its own namespace
  .circleci/config.yml
  .riot/requirements/13c6f3e.txt
  .riot/requirements/13ca984.txt
  .riot/requirements/1b48add.txt
  .riot/requirements/1ed39a3.txt
  .riot/requirements/67db025.txt
  .riot/requirements/8658621.txt
  .riot/requirements/a2e48a3.txt
  .riot/requirements/f3ece5d.txt
  ddtrace/contrib/pytest/plugin.py
  ddtrace/contrib/pytest_bdd/plugin.py
  ddtrace/filters.py
  ddtrace/internal/ci_visibility/__init__.py
  ddtrace/internal/ci_visibility/filters.py
  ddtrace/internal/ci_visibility/recorder.py
  riotfile.py
  tests/ci_visibility/__init__.py
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/asynctest/test_asynctest.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest_bdd/test_pytest_bdd.py
  tests/tracer/test_filters.py
Labels: changelog/no-changelog

#5430 chore(debugging): discover all functions but line-map by module
  ddtrace/debugging/_function/discovery.py
  tests/debugging/exploration/_profiler.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5437 chore(debugging): add timeout to context capturing
  ddtrace/debugging/_capture/snapshot.py
  ddtrace/debugging/_capture/utils.py
  ddtrace/internal/utils/time.py
  tests/debugging/test_encoding.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5463 chore(asm): update waf rules to last version
  ddtrace/appsec/rules.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#5434 chore(tracing): adds 128 bit trace id support for b3 and w3c trace headers
  ddtrace/propagation/http.py
  releasenotes/notes/128bit-trace-id-support-b3-w3c-b5746f84a509fa24.yaml
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#5426 chore(docs): readme.md and contributing doc updates
  README.md
  docs/contributing-integrations.rst
Labels: changelog/no-changelog

#5470 chore(pre-commit hooks): remove slotscheck from pre-commit hooks
  README.md
  docs/contributing.rst
  docs/spelling_wordlist.txt
  hooks/pre-commit/run-slotscheck.sh
  hooks/scripts/run-slotscheck.sh
Labels: changelog/no-changelog

#5462 chore(asm): improving the asm context
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/iast/_overhead_control_engine.py
  ddtrace/appsec/iast/_taint_dict.py
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/processor.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/test_asm_request_context.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5466 chore(pytest): move CI visibility initialization to start of pytest command
  ddtrace/contrib/pytest/plugin.py
  ddtrace/contrib/pytest_bdd/plugin.py
  tests/contrib/asynctest/test_asynctest.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest_bdd/test_pytest_bdd.py
Labels: changelog/no-changelog

#5472 chore(lib-inject): fix build_deploy
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#5475 chore(tracing): encapsulate agent-specific writer functionality
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#5483 fix(tracing): avoid dropping extra headers passed to AgentWriter constructor
  ddtrace/internal/writer.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#5482 chore(lib-inject): fix build_deploy [backport #5472 to 1.11]
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#5486 chore(ci): add special branches for testing build_deploy, fix lib-inject job
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#5487 chore(ci): add special branches for testing build_deploy, fix lib-injection [backport #5486 to 1.11]
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#5476 chore(opentelemetry): add status description to otel spans
  ddtrace/_opentelemetry/span.py
  tests/opentelemetry/test_span.py
Labels: changelog/no-changelog

#5484 fix(ci): pin websockets in sanic tests
  riotfile.py
Labels: changelog/no-changelog

#5471 feat(tracing): introduce ci visibility agentless writer/encoder
  ddtrace/internal/ci_visibility/encoder.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer.py
  tests/tracer/test_encoders.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#5490 chore(opentelemtry): set trace state and trace flags on local root spans
  ddtrace/_opentelemetry/span.py
  ddtrace/_opentelemetry/trace.py
  tests/opentelemetry/test_span.py
  tests/snapshots/tests.opentelemetry.test_context.test_otel_trace_across_fork.json
  tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_opentelemetry_instrument].json
Labels: changelog/no-changelog

#5496 fix(ci/lib-inject): pin buildx
  .github/workflows/build-and-publish-image.yml
Labels: changelog/no-changelog

#5505 ci(django): ensure tests are compatible with django 4.2
  .circleci/config.yml
  .riot/requirements/11304ce.txt
  .riot/requirements/145d12f.txt
  .riot/requirements/15eed6c.txt
  .riot/requirements/1666b9d.txt
  .riot/requirements/168056a.txt
  .riot/requirements/16d9484.txt
  .riot/requirements/1747910.txt
  .riot/requirements/1bf9ccc.txt
  .riot/requirements/1e3fff3.txt
  .riot/requirements/1ed0e35.txt
  .riot/requirements/1f61f0f.txt
  .riot/requirements/1f99b32.txt
  .riot/requirements/227eb61.txt
  .riot/requirements/a178330.txt
  .riot/requirements/aeb635b.txt
  .riot/requirements/b335fe2.txt
  .riot/requirements/bd1ac0d.txt
  .riot/requirements/bdbe5d0.txt
  .riot/requirements/c7f001b.txt
  .riot/requirements/cc92558.txt
  .riot/requirements/db2eaee.txt
  .riot/requirements/f433975.txt
  docker-compose.yml
Labels: changelog/no-changelog

#5503 ci(sanic): pin websockets in sanic tests [backports #5484 to 1.10]
  riotfile.py
Labels: changelog/no-changelog

#5506 ci(django): ensure tests are compatible with django 4.2 [backport #5505 to 1.10]
  .circleci/config.yml
  docker-compose.yml
Labels: changelog/no-changelog

#5510 fix(tracing): ensure 128 trace ids are propagated by datadog headers
  ddtrace/propagation/http.py
  releasenotes/notes/fix-128bit-trace-id-propagation-b0e262f0fdf45044.yaml
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#5469 fix(futures): unload futures submodule during module cleanup [backport #5402 to 1.10]
  ddtrace/_monkey.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/futures/patch.py
  ddtrace/contrib/futures/threading.py
  releasenotes/notes/fix-futures-module-unload-e84900affff06152.yaml
  riotfile.py
  tests/conftest.py
  tests/contrib/futures/test_futures_patch_generated.py
  tests/contrib/futures/test_propagation.py
  tests/utils.py
Labels: changelog/no-changelog

#5513 fix(tracing): ensure propagating errors are set correctly
  ddtrace/propagation/http.py
Labels: changelog/no-changelog

#5514 fix(tracing): ensure 128 trace ids are propagated by datadog headers [backports #5510 to 1.11]
  ddtrace/propagation/http.py
  releasenotes/notes/fix-128bit-trace-id-propagation-b0e262f0fdf45044.yaml
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#5511 fix(ci/lib-inject): pin buildx [backport #5496 to 1.11]
  .github/workflows/build-and-publish-image.yml
Labels: changelog/no-changelog

#5507 ci(django): ensure tests are compatible with django 4.2 [backport #5505 to 1.9]
  .circleci/config.yml
  docker-compose.yml
Labels: changelog/no-changelog

#5468 fix(futures): unload futures submodule during module cleanup [backport #5402 to 1.9]
  ddtrace/_monkey.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/futures/patch.py
  ddtrace/contrib/futures/threading.py
  releasenotes/notes/fix-futures-module-unload-e84900affff06152.yaml
  riotfile.py
  tests/conftest.py
  tests/contrib/futures/test_futures_patch_generated.py
  tests/contrib/futures/test_propagation.py
  tests/utils.py
Labels: changelog/no-changelog

#5515 chore(testing/agent): enable stats to be sent
  docker-compose.yml
Labels: changelog/no-changelog

#5517 fix(asm): update capabilities logic
  ddtrace/appsec/utils.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#5502 chore(ci): only collect coverage data when requested
  .circleci/config.yml
  .riot/requirements/4797e24.txt
  riotfile.py
Labels: changelog/no-changelog

#5518 ci(boto): add wait timeout when testing receiving request
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#5520 chore(asm): update libddwaf to 1.9.0
  ddtrace/appsec/_remoteconfiguration.py
  setup.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#5509 fix(tracing): avoid truncating b3 and w3c trace ids to 64bits
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#5539 chore(ci): pin debugger packaging dependency
  riotfile.py
Labels: changelog/no-changelog

#5535 chore(6to7): add microbenchmarks
  benchmarks/span/config.yaml
  benchmarks/span/scenario.py
Labels: changelog/no-changelog

#5526 fix(telemetry): python 2.7 memory leak
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry_metrics.py
Labels: changelog/no-changelog, ASM

#5530 chore(asm): iast fix vulnerability report hash
  ddtrace/appsec/iast/reporter.py
  tests/appsec/iast/test_weak_hash.py
Labels: changelog/no-changelog, ASM

#5498 chore(profiling): fix flaky test_asyncio test
  tests/profiling/collector/test_stack_asyncio.py
Labels: changelog/no-changelog, Profiling, Testing

#5541 fix(ci-visibility): add dd_origin propagation to CIVisibilityEncoder
  ddtrace/internal/ci_visibility/encoder.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog

#5544 chore(grpc): wait for traces in flaky snapshot test
  tests/contrib/grpc/test_grpc.py
Labels: changelog/no-changelog

#5527 chore(asm): iast oce request sampling
  ddtrace/appsec/iast/_overhead_control_engine.py
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/processor.py
  riotfile.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/test_taint_tracking.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM

#5504 chore(ci): remove hypothesis usage in test_http.py, migrate tracer tests to riot
  .circleci/config.yml
  riotfile.py
  tests/tracer/fixtures/urls.txt
  tests/tracer/test_http.py
  tox.ini
Labels: changelog/no-changelog

#5474 chore(debugging): try to undecorate functions
  ddtrace/debugging/_function/discovery.py
  tests/debugging/function/test_discovery.py
  tests/debugging/function/test_store.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5547 chore(asm): refactor appsec django tests
  .github/CODEOWNERS
  tests/contrib/django/django1_app/urls.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/django_app/urls.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/views.py
Labels: changelog/no-changelog, ASM

#5501 fix(monkey): handle non-ImportError exceptions on `patch()`
  ddtrace/_monkey.py
  releasenotes/notes/monkey-import-exceptions-eb9557ea85a921fe.yaml
  tests/tracer/test_monkey.py
Labels: Tracing

#5531 chore(tracing): let a writer hold multiple clients
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/__init__.py
  ddtrace/internal/writer/writer.py
  ddtrace/internal/writer/writer_client.py
  tests/integration/test_encoding.py
  tests/integration/test_integration.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#5555 feat: add more scenarios to benchmark tests
  .gitlab/benchmarks.yml
  benchmarks/flask_simple/gunicorn.conf.py
Labels: changelog/no-changelog, ASM

#5554 chore(flake8): exclude ddtrace/__init__.py [backport #5428 to 1.9]
  setup.cfg
Labels: changelog/no-changelog

#5542 chore(asm): add sqli django unit test
  ddtrace/appsec/iast/_taint_utils.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5553 chore(flake8): exclude ddtrace/__init__.py [backport #5428 to 1.10]
  setup.cfg
Labels: changelog/no-changelog

#5562 chore(ci): add DD_SNAPSHOT_ENABLED to skip snapshots
  tests/conftest.py
Labels: changelog/no-changelog

#5543 feat(pytest): verify git metadata span tags
  ddtrace/internal/ci_visibility/recorder.py
  tests/contrib/pytest/test_pytest.py
  tests/tracer/test_ci.py
  tests/utils.py
Labels: changelog/no-changelog

#5572 fix(benchmark): tracer error, add otel_span to scenarios list
  .gitlab/benchmarks.yml
  benchmarks/tracer/scenario.py
Labels: changelog/no-changelog, ASM

#5551 fix(profiling): accounting of time for gevent tasks [backport #5338 to 1.9]
  ddtrace/__init__.py
  ddtrace/profiling/_threading.pyx
  ddtrace/profiling/collector/_task.pyx
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/fix-profiler-gevent-tasks-76ed862362210cb7.yaml
  tests/profiling/collector/test_stack.py
  tests/profiling/simple_program_gevent.py
Labels: Profiling

#5519 chore(asm): migrate waf data to asm context
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/processor.py
  ddtrace/contrib/trace_utils.py
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog, ASM

#5564 chore(internal/dogstatsd): add constant tags
  ddtrace/internal/dogstatsd.py
Labels: changelog/no-changelog

#5427 chore(service name): initial schema for span attributes (service name)
  ddtrace/contrib/redis/patch.py
  ddtrace/internal/schema/__init__.py
  ddtrace/internal/schema/span_attribute_schema.py
  ddtrace/settings/config.py
  tests/contrib/redis/test_redis.py
  tests/contrib/redis/test_redis_cluster.py
Labels: changelog/no-changelog

#5550 fix(profiling): accounting of time for gevent tasks [backport #5338 to 1.10]
  ddtrace/__init__.py
  ddtrace/profiling/_threading.pyx
  ddtrace/profiling/collector/_task.pyx
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/fix-profiler-gevent-tasks-76ed862362210cb7.yaml
  tests/profiling/collector/test_stack.py
  tests/profiling/simple_program_gevent.py
Labels: Profiling

#5587 chore(asm): activate asm context only in asm
  ddtrace/appsec/_asm_request_context.py
  tests/appsec/test_asm_request_context.py
Labels: changelog/no-changelog, ASM

#5571 chore(asm): iast taint Flask path parameters
  ddtrace/contrib/flask/wrappers.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM

#5583 chore(ci): allow coverage reporting on CircleCI
  .circleci/config.yml
  riotfile.py
Labels: changelog/no-changelog

#5592 fix(ci): sort riot venv hashes instead of shuffling them when splitting tests
  .circleci/config.yml
Labels: changelog/no-changelog

#5591 chore(pytest): civisibility adjustments from integration testing
  ddtrace/internal/ci_visibility/encoder.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/writer.py
  tests/contrib/pytest/test_pytest.py
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog

#5478 chore(tracing): allow registering extra span processors
  ddtrace/internal/processor/__init__.py
  ddtrace/tracer.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog, Tracing

#5593 chore(ci): separate tracer riot hashes, increase parallelism
  .circleci/config.yml
  riotfile.py
Labels: changelog/no-changelog

#5603 chore(ci): bump riot to 0.17.2
  .circleci/config.yml
  scripts/ddtest
Labels: changelog/no-changelog

#5586 fix(profiling): memalloc clean restart after fork
  ddtrace/profiling/collector/memalloc.py
  releasenotes/notes/fix-profiler-memory-collector-reinit-after-fork-2e6fa30cb75e03a6.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5604 chore(ci): bump riot to 0.17.2 [backport #5603 to 1.11]
  .circleci/config.yml
  scripts/ddtest
Labels: changelog/no-changelog

#5606 chore(ci): bump riot to 0.17.2 [backport #5603 to 1.9]
  .circleci/config.yml
  scripts/ddtest
Labels: changelog/no-changelog

#5614 fix(profiling): memalloc clean restart after fork [backport #5586 to 1.12]
  ddtrace/profiling/collector/memalloc.py
  releasenotes/notes/fix-profiler-memory-collector-reinit-after-fork-2e6fa30cb75e03a6.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5407 feat: add ASM config values to ddtrace-run --info
  ddtrace/internal/debug.py
  releasenotes/notes/asm-ddtracerun-info-bf2380675fe1c721.yaml
  tests/commands/test_runner.py
Labels: ASM

#5559 chore(profiling): refactor test_stack_asyncio tests
  tests/profiling/collector/test_stack_asyncio.py
Labels: changelog/no-changelog

#5625 chore(dev): improvements to backporting script
  scripts/backport
Labels: changelog/no-changelog

#5602 chore(asm): safer extract_body
  ddtrace/contrib/django/utils.py
Labels: changelog/no-changelog, ASM

#5622 chore(asm): add truncation information to ddwaf_result
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/ddwaf/ddwaf_types.py
  tests/appsec/test_ddwaf_fuzz.py
Labels: changelog/no-changelog, ASM

#5620 feat(asm): update telemetry metrics tags
  ddtrace/appsec/_metrics.py
  tests/appsec/test_telemety.py
Labels: changelog/no-changelog, ASM

#5552 chore(flake8): exclude ddtrace/__init__.py [backport #5428 to 1.11]
  setup.cfg
Labels: changelog/no-changelog

#5566 fix: dont raise a ValueError on set_user when no span [backport #5548 to 1.10]
  ddtrace/appsec/trace_utils.py
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/fix-block-request-without-span-c5ea72a06bd389b3.yaml
Labels: manual merge

#5590 chore(ci): pin debugger packaging dependency [backport #5539 to 1.11]
  riotfile.py
Labels: changelog/no-changelog

#5615 fix(profiling): memalloc clean restart after fork [backport #5586 to 1.11]
  ddtrace/profiling/collector/memalloc.py
  releasenotes/notes/fix-profiler-memory-collector-reinit-after-fork-2e6fa30cb75e03a6.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5599 chore(asm): iast avoid leaking exceptions
  ddtrace/appsec/iast/_loader.py
  ddtrace/appsec/iast/_patch.py
  ddtrace/appsec/iast/_taint_utils.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/flask/patch.py
Labels: changelog/no-changelog, ASM

#5497 feat(pytest): send payloads to agent EVP proxy endpoint when available
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/writer.py
  docs/configuration.rst
  docs/spelling_wordlist.txt
  tests/integration/test_integration.py
  tests/utils.py
Labels: changelog/no-changelog

#5619 refactor(debugging): handle location in probe factory
  ddtrace/debugging/_probe/remoteconfig.py
  tests/debugging/probe/test_remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5634 chore(ci): coverage and integration test fix [backport #5502, #5521, #5583 to 1.11]
  .circleci/config.yml
  .riot/requirements/4797e24.txt
  riotfile.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#5623 docs(debugging): update configuration documentation
  ddtrace/settings/dynamic_instrumentation.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5616 fix(profiling): memalloc clean restart after fork [backport #5586 to 1.10]
  ddtrace/profiling/collector/memalloc.py
  releasenotes/notes/fix-profiler-memory-collector-reinit-after-fork-2e6fa30cb75e03a6.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5617 fix(profiling): memalloc clean restart after fork [backport #5586 to 1.9]
  ddtrace/profiling/collector/memalloc.py
  releasenotes/notes/fix-profiler-memory-collector-reinit-after-fork-2e6fa30cb75e03a6.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5600 ci(debugging): reduce exploration limits
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5549 fix(profiling): accounting of time for gevent tasks [backport #5338 to 1.11]
  ddtrace/__init__.py
  ddtrace/profiling/_threading.pyx
  ddtrace/profiling/collector/_task.pyx
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/fix-profiler-gevent-tasks-76ed862362210cb7.yaml
  tests/profiling/collector/test_stack.py
  tests/profiling/simple_program_gevent.py
Labels: Profiling

#5588 chore(ci): add pipeline parameter to toggle using latest package versions
  .circleci/config.yml
  scripts/ddtest
Labels: changelog/no-changelog

#5621 docs: define envier directive
  docs/conf.py
  docs/configuration.rst
Labels: changelog/no-changelog, Dynamic Instrumentation

#5644 chore(release_script): fix patch version
  scripts/release.py
Labels: changelog/no-changelog

#5633 chore(ci): move profile tests to riot
  .circleci/config.yml
  .riot/requirements/102cf0a.txt
  .riot/requirements/10625b5.txt
  .riot/requirements/10bb56b.txt
  .riot/requirements/12b8829.txt
  .riot/requirements/139c624.txt
  .riot/requirements/14e4d18.txt
  .riot/requirements/16068e5.txt
  .riot/requirements/1661781.txt
  .riot/requirements/16f0303.txt
  .riot/requirements/1782352.txt
  .riot/requirements/183e924.txt
  .riot/requirements/1873aad.txt
  .riot/requirements/18e17a2.txt
  .riot/requirements/1900b00.txt
  .riot/requirements/197d9d9.txt
  .riot/requirements/1ab945a.txt
  .riot/requirements/1b15a30.txt
  .riot/requirements/1c96ce3.txt
  .riot/requirements/1ce356c.txt
  .riot/requirements/1ed9e02.txt
  .riot/requirements/1f0a448.txt
  .riot/requirements/1fe2085.txt
  .riot/requirements/3b00ce5.txt
  .riot/requirements/43cfbc2.txt
  .riot/requirements/48059c6.txt
  .riot/requirements/506d536.txt
  .riot/requirements/58981a6.txt
  .riot/requirements/5d58358.txt
  .riot/requirements/5d6f54d.txt
  .riot/requirements/5f096ae.txt
  .riot/requirements/65c8aef.txt
  .riot/requirements/6ff9aaa.txt
  .riot/requirements/74a75c9.txt
  .riot/requirements/8fe2e58.txt
  .riot/requirements/9b9a7f4.txt
  .riot/requirements/a08dd70.txt
  .riot/requirements/a157848.txt
  .riot/requirements/a6117d3.txt
  .riot/requirements/b4bf279.txt
  .riot/requirements/b7d4b65.txt
  .riot/requirements/cc86ab5.txt
  .riot/requirements/cd4c4a1.txt
  .riot/requirements/cedb415.txt
  .riot/requirements/db592df.txt
  .riot/requirements/e28ff1d.txt
  .riot/requirements/e2a460f.txt
  .riot/requirements/f7bbb08.txt
  .riot/requirements/f884c2b.txt
  README.md
  riotfile.py
  scripts/ddtest
  scripts/run-tox-scenario
  setup.py
  tox.ini
Labels: changelog/no-changelog

#5613 feat(pytest): fetch and set CIVIsibility feature enablement flags from DD api
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog

#5594 feat(pytest): add envvar CI_VISIBILITY_AGENTLESS_URL
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/settings/config.py
  docs/configuration.rst
  tests/ci_visibility/test_ci_visibility.py
  tests/utils.py
Labels: changelog/no-changelog

#5563 chore(tests/subprocess): add tests module to python path
  tests/conftest.py
Labels: changelog/no-changelog

#5647 ci(snapshot): allow snapshots to be skipped
  conftest.py
  tests/conftest.py
  tests/integration/test_integration_snapshots.py
  tests/snapshots/tests.integration.test_integration_snapshots.test_snapshot_skip.json
Labels: changelog/no-changelog

#5444 test(celery): avoid celery app init for unit testing
  tests/contrib/celery/test_utils.py
Labels: changelog/no-changelog

#5648 feat(asm): remove telemetry tag
  ddtrace/appsec/_metrics.py
  tests/appsec/test_telemety.py
Labels: changelog/no-changelog, ASM

#5649 feat(telemetry): remove redundant headers
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#5652 chore(otel/span): reduce noise in start span benchmarks
  benchmarks/otel_span/scenario.py
  benchmarks/span/scenario.py
Labels: changelog/no-changelog

#5642 fix(tests): ignore gpg signing when running git commit from tests
  tests/conftest.py
Labels: changelog/no-changelog

#5657 ci: switch reliability env deployments to be scheduled
  .gitlab-ci.yml
Labels: changelog/no-changelog

#5569 chore(asm): iast taint Django path parameters
  ddtrace/appsec/_constants.py
  ddtrace/contrib/django/patch.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5664 fix(profiler): support for latest protobuf versions
  ddtrace/profiling/exporter/pprof.pyx
  ddtrace/profiling/exporter/pprof_312_pb2.py
  ddtrace/profiling/exporter/pprof_319_pb2.py
  ddtrace/profiling/exporter/pprof_3_pb2.py
  ddtrace/profiling/exporter/pprof_421_pb2.py
  ddtrace/profiling/exporter/releasenotes/notes/profiler-protobuf-421-bf20b8e42ba3ad4c.yaml
  mypy.ini
  pyproject.toml
  setup.cfg
Labels: Profiling

#5639 chore(asm): iast flask taint request headers (keys and values)
  ddtrace/appsec/iast/_patch.py
  ddtrace/contrib/flask/patch.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM

#5522 feat(pytest): coverage reporting
  ddtrace/contrib/pytest/plugin.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/coverage.py
  ddtrace/internal/ci_visibility/encoder.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  riotfile.py
  tests/contrib/pytest/test_pytest.py
  tests/integration/test_integration.py
  tests/tracer/test_encoders.py
  tests/utils.py
Labels: changelog/no-changelog

#5667 chore(testing): validate requirements lockfiles with a github action
  .github/workflows/requirements-locks.yml
  scripts/compile-and-prune-test-requirements
Labels: changelog/no-changelog

#5643 refactor(profiling): use envier for configuration
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/exporter/_packages.py
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/profiler.py
  ddtrace/profiling/recorder.py
  ddtrace/profiling/scheduler.py
  ddtrace/settings/profiling.py
  docs/configuration.rst
  tests/profiling/collector/test_memalloc.py
  tests/profiling/collector/test_task.py
  tests/profiling/collector/test_threading_asyncio.py
  tests/profiling/exporter/test_http.py
  tests/profiling/test_accuracy.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog, Profiling

#5677 ci(openai): allow installation of deprecated sklearn package
  riotfile.py
Labels: changelog/no-changelog

#5668 fix(profiler): support for latest protobuf versions [backport #5664 to 1.13]
  ddtrace/profiling/exporter/pprof.pyx
  ddtrace/profiling/exporter/pprof_312_pb2.py
  ddtrace/profiling/exporter/pprof_319_pb2.py
  ddtrace/profiling/exporter/pprof_3_pb2.py
  ddtrace/profiling/exporter/pprof_421_pb2.py
  ddtrace/profiling/exporter/releasenotes/notes/profiler-protobuf-421-bf20b8e42ba3ad4c.yaml
  mypy.ini
  pyproject.toml
  setup.cfg
Labels: Profiling

#5669 fix(profiler): support for latest protobuf versions [backport #5664 to 1.12]
  ddtrace/profiling/exporter/pprof.pyx
  ddtrace/profiling/exporter/pprof_312_pb2.py
  ddtrace/profiling/exporter/pprof_319_pb2.py
  ddtrace/profiling/exporter/pprof_3_pb2.py
  ddtrace/profiling/exporter/pprof_421_pb2.py
  ddtrace/profiling/exporter/releasenotes/notes/profiler-protobuf-421-bf20b8e42ba3ad4c.yaml
  mypy.ini
  pyproject.toml
  setup.cfg
Labels: Profiling

#5673 fix(testing): detect new lockfiles in workflow
  .github/workflows/requirements-locks.yml
  scripts/check-diff
Labels: changelog/no-changelog

#5670 fix(profiler): support for latest protobuf versions [backport #5664 to 1.11]
  ddtrace/profiling/exporter/pprof.pyx
  ddtrace/profiling/exporter/pprof_312_pb2.py
  ddtrace/profiling/exporter/pprof_319_pb2.py
  ddtrace/profiling/exporter/pprof_3_pb2.py
  ddtrace/profiling/exporter/pprof_421_pb2.py
  ddtrace/profiling/exporter/releasenotes/notes/profiler-protobuf-421-bf20b8e42ba3ad4c.yaml
  mypy.ini
  pyproject.toml
  setup.cfg
Labels: Profiling

#5681 fix(asm): body parsing for django asm [backport #5665 to 1.13]
  ddtrace/appsec/utils.py
  ddtrace/contrib/django/utils.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-extract-django-body-185084700323dce6.yaml
  tests/appsec/test_tools.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/djangorestframework/app/views.py
  tests/contrib/djangorestframework/test_appsec.py
  tests/contrib/djangorestframework/test_djangorestframework.py
Labels: bug, ASM

#5683 fix(testing): make diff checker script more generic
  .github/workflows/requirements-locks.yml
  scripts/check-diff
Labels: changelog/no-changelog

#5578 feat(pytest): upload git packfiles from civisibility service
  ddtrace/ext/git.py
  ddtrace/internal/agent.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/compat.py
  ddtrace/internal/utils/http.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  docs/configuration.rst
  docs/spelling_wordlist.txt
  tests/ci_visibility/test_ci_visibility.py
  tests/conftest.py
  tests/contrib/pytest/test_pytest.py
  tests/tracer/test_agent.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#5688 feat(pytest): put real suite and session ID onto encoded coverage spans
  ddtrace/internal/ci_visibility/encoder.py
  tests/ci_visibility/test_encoder.py
Labels: changelog/no-changelog

#5650 chore(asm): iast taint django headers
  ddtrace/appsec/iast/_taint_utils.py
  ddtrace/contrib/django/patch.py
  tests/appsec/iast/test_taint_utils.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5690 ci: don't deploy to debugger backend nightly
  .gitlab-ci.yml
Labels: changelog/no-changelog

#5679 ci(openai): flaky sampling test
  tests/contrib/openai/test_openai.py
Labels: changelog/no-changelog

#5656 fix(telemetry): metric tags to lowercase
  ddtrace/internal/telemetry/metrics.py
  ddtrace/internal/telemetry/writer.py
  tests/appsec/test_telemety.py
  tests/telemetry/test_telemetry_metrics.py
Labels: changelog/no-changelog, ASM

#5655 fix(telemetry): collect metrics in gunicorn apps
  .riot/requirements/10f90a0.txt
  .riot/requirements/115358e.txt
  .riot/requirements/1158f26.txt
  .riot/requirements/12b1643.txt
  .riot/requirements/12f760b.txt
  .riot/requirements/1324fb2.txt
  .riot/requirements/142ea1e.txt
  .riot/requirements/1d84a29.txt
  .riot/requirements/1f6511d.txt
  .riot/requirements/1fa3a1c.txt
  .riot/requirements/3a13f7b.txt
  .riot/requirements/78a356f.txt
  .riot/requirements/c632a66.txt
  ddtrace/internal/telemetry/writer.py
  riotfile.py
  tests/telemetry/app.py
  tests/telemetry/conftest.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#5702 fix: move protobuf release note to correct dir for 5664
  releasenotes/notes/profiler-protobuf-421-bf20b8e42ba3ad4c.yaml
Labels: changelog/no-changelog

#5703 chore(telemetry): disable telemetry metrics when telemetry envar is False
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
Labels: changelog/no-changelog

#5700 chore(pytest): add docstring about pytest plugin design
  ddtrace/contrib/pytest/plugin.py
Labels: changelog/no-changelog

#5704 fix: move protobuf release note to correct dir for 5664 [backport #5702 to 1.12]
  releasenotes/notes/profiler-protobuf-421-bf20b8e42ba3ad4c.yaml
Labels: changelog/no-changelog

#5676 refactor(debugging): replace capture with signal
  ddtrace/debugging/_async.py
  ddtrace/debugging/_capture/collector.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_probe/status.py
  ddtrace/debugging/_signal/__init__.py
  ddtrace/debugging/_signal/collector.py
  ddtrace/debugging/_signal/metric_sample.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_signal/snapshot.py
  ddtrace/debugging/_signal/tracing.py
  ddtrace/debugging/_signal/utils.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/debugger.py
  tests/debugging/mocking.py
  tests/debugging/py35/test_async.py
  tests/debugging/signal/__init__.py
  tests/debugging/signal/test_collector.py
  tests/debugging/test_debugger.py
  tests/debugging/test_encoding.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5672 docs: add code block and explanation of how to create new requirements files
  docs/contributing.rst
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog

#5692 chore(ci): specify platform linux/amd64 for rediscluster container
  docker-compose.yml
Labels: changelog/no-changelog

#5537 chore(ci): tar all build artifacts and add to GitHub release
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#5666 docs(tracing): add tracecontext to http header documentation
  ddtrace/settings/config.py
  docs/configuration.rst
Labels: changelog/no-changelog

#5608 chore(redis): extract redis common helpers to contrib utils
  ddtrace/contrib/aioredis/patch.py
  ddtrace/contrib/aredis/patch.py
  ddtrace/contrib/flask_cache/utils.py
  ddtrace/contrib/redis/asyncio_patch.py
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/trace_utils_redis.py
  ddtrace/contrib/yaaredis/patch.py
Labels: changelog/no-changelog

#5560 chore(ci): add cython-lint checker for ddtrace internal cython files
  .circleci/config.yml
  .riot/requirements/27854ee.txt
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/_rand.pyx
  ddtrace/internal/_tagset.pyx
  pyproject.toml
  riotfile.py
Labels: changelog/no-changelog
