Repository DataDog/dd-trace-py, pull requests merged in 2023-08, with the labels that each got.

#6542 chore(asm): fix 2 subprocess integration tests
  tests/contrib/subprocess/test_subprocess.py
Labels: changelog/no-changelog

#6544 chore(asm): fix unused var
  tests/contrib/subprocess/test_subprocess.py
Labels: changelog/no-changelog, ASM

#6541 ci: do not use pip cache
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#6520 chore: set the name of the RCM subscriber threads
  ddtrace/internal/remoteconfig/_subscribers.py
Labels: changelog/no-changelog

#6491 chore(django): remove iast code from django contrib
  ddtrace/appsec/handlers.py
  ddtrace/contrib/django/patch.py
Labels: changelog/no-changelog, ASM

#6546 chore(ci-visibility): python2 compatibility issue
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
Labels: changelog/no-changelog, CI App

#6545 refactor(ci-visibility): tests refactor
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/test_coverage_per_suite.py
  tests/ci_visibility/test_encoder.py
  tests/ci_visibility/util.py
  tests/contrib/asynctest/test_asynctest.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest_bdd/test_pytest_bdd.py
  tests/integration/test_integration.py
  tests/integration/test_integration_civisibility.py
Labels: changelog/no-changelog, CI App

#6554 ci: undo change that appears to have broken suite selection
  tests/.suitespec.json
Labels: changelog/no-changelog

#6442 chore: add hatch
  .circleci/config.templ.yml
  .github/workflows/build_python_3.yml
  docs/contributing-testing.rst
  docs/spelling_wordlist.txt
  hatch.toml
  hooks/scripts/run-black.sh
  hooks/scripts/run-codespell.sh
  hooks/scripts/run-flake8.sh
  hooks/scripts/run-mypy.sh
  pyproject.toml
  riotfile.py
  scripts/docs/build.sh
  scripts/docs/install.sh
  scripts/gen_circleci_config.py
  tests/.suitespec.json
  tests/suitespec.py
Labels: changelog/no-changelog

#6486 chore(docs): update contribution docs with service naming
  docs/contributing-integrations.rst
  templates/integration/patch.py
Labels: changelog/no-changelog

#6548 chore(ci-visibility): decouple from tracer
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/provider.py
  ddtrace/tracer.py
  tests/utils.py
Labels: changelog/no-changelog, CI App

#6543 chore(tests): fix pytest hooks
  tests/conftest.py
Labels: changelog/no-changelog

#6550 ci: diff against merge base
  scripts/needs_testrun.py
Labels: changelog/no-changelog

#6478 ci: run framework tests only when necessary
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#6558 ci: run profile jobs when needed
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
Labels: changelog/no-changelog

#6557 ci: build docs only if necessary
  .circleci/config.templ.yml
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#6560 ci: validate suitespec JSON
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#6510 chore(tracing): deduplicate some test code about sampling
  tests/tracer/test_sampler.py
  tests/tracer/test_sampling_decision.py
  tests/tracer/test_single_span_sampling_rule.py
  tests/tracer/test_single_span_sampling_rules.py
Labels: changelog/no-changelog

#6547 chore(ci-visibility): run git set safe directory
  ddtrace/ext/git.py
  tests/tracer/test_ci.py
Labels: changelog/no-changelog, CI App

#6556 feat(iast): django integration
  ddtrace/appsec/handlers.py
  tests/contrib/django/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#6553 chore(ci-visibility): don't collect coverage data for skipped tests
  ddtrace/contrib/pytest/plugin.py
  ddtrace/internal/ci_visibility/coverage.py
  tests/ci_visibility/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog, CI App

#6526 chore: clean and deduplicate integration tests
  tests/integration/test_integration.py
  tests/integration/test_integration_civisibility.py
  tests/integration/test_integration_snapshots.py
  tests/integration/test_priority_sampling.py
  tests/integration/utils.py
  tests/snapshots/tests.integration.test_context_snapshots.test_context_multiprocess.json
  tests/snapshots/tests.integration.test_integration.test_span_tags[v0.4].json
  tests/snapshots/tests.integration.test_integration_snapshots.test_env_vars.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_filters.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_multiple_traces.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_sampling.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_setting_span_tags_and_metrics_generates_no_error_logs[v0.4].json
  tests/snapshots/tests.integration.test_integration_snapshots.test_setting_span_tags_and_metrics_generates_no_error_logs[v0.5].json
  tests/snapshots/tests.integration.test_integration_snapshots.test_single_trace_single_span.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_synchronous_writer.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_trace_with_wrong_meta_types_not_sent.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_trace_with_wrong_metrics_types_not_sent.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_tracer_trace_across_fork.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_tracer_trace_across_multiple_forks.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_tracetagsprocessor_only_adds_new_tags.json
  tests/snapshots/tests.integration.test_integration_snapshots.test_wrong_span_name_type_not_sent.json
  tests/snapshots/tests.integration.test_propagation.test_sampling_decision_downstream.json
  tests/snapshots/tests.integration.test_propagation.test_trace_tags_multispan[tracer0].json
  tests/snapshots/tests.integration.test_propagation.test_trace_tags_multispan[tracer1].json
  tests/snapshots/tests.integration.test_propagation.test_trace_tags_multispan[tracer2].json
  tests/snapshots/tests.integration.test_trace_stats.test_measured_span_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_sampling_rate[0.0]_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_sampling_rate[1.0].json
  tests/snapshots/tests.integration.test_trace_stats.test_sampling_rate[1.0]_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_single_span_sampling[sampling_rule0].json
  tests/snapshots/tests.integration.test_trace_stats.test_single_span_sampling[sampling_rule0]_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_single_span_sampling[sampling_rule1].json
  tests/snapshots/tests.integration.test_trace_stats.test_single_span_sampling[sampling_rule1]_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_stats_100_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_stats_aggrs_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_stats_errors_tracestats.json
  tests/snapshots/tests.integration.test_trace_stats.test_top_level_tracestats.json
Labels: changelog/no-changelog

#6370 chore(wsgi): remove private tracing logic from wsgi contrib
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/tracing/__init__.py
  ddtrace/tracing/trace_handlers.py
  tests/.suitespec.json
Labels: changelog/no-changelog

#6539 chore(framework tests): skip failing sanic test
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#6537 chore(subprocess): add patch tests, enable running tests on CI
  .circleci/config.templ.yml
  .riot/requirements/10a7d4d.txt
  .riot/requirements/10bb56b.txt
  .riot/requirements/12b8829.txt
  .riot/requirements/135581c.txt
  .riot/requirements/1661781.txt
  .riot/requirements/16f0303.txt
  .riot/requirements/1782352.txt
  .riot/requirements/1873aad.txt
  .riot/requirements/18e17a2.txt
  .riot/requirements/18e71e7.txt
  .riot/requirements/1900b00.txt
  .riot/requirements/1ab945a.txt
  .riot/requirements/1b09496.txt
  .riot/requirements/1ef4439.txt
  .riot/requirements/3b00ce5.txt
  .riot/requirements/45f53a2.txt
  .riot/requirements/5d58358.txt
  .riot/requirements/63f6f54.txt
  .riot/requirements/cc86ab5.txt
  .riot/requirements/e30a737.txt
  .riot/requirements/f7bbb08.txt
  riotfile.py
  tests/contrib/patch.py
  tests/contrib/subprocess/test_subprocess_patch.py
Labels: changelog/no-changelog

#6561 chore(dev): add hatch to scripts/ddtest testrunner
  scripts/ddtest
Labels: changelog/no-changelog, CI App

#6552 chore(asm): move patch_iast to iast directory
  ddtrace/_monkey.py
  ddtrace/appsec/iast/__init__.py
  ddtrace/appsec/iast/_patch_modules.py
  tests/appsec/iast/test_processor.py
  tests/appsec/iast/test_telemetry.py
  tests/contrib/django/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#6564 chore(iast): multiple errors
  ddtrace/appsec/iast/_ast/visitor.py
  ddtrace/appsec/iast/_metrics.py
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/processor.py
  ddtrace/appsec/iast/reporter.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/appsec/iast/taint_sinks/command_injection.py
  ddtrace/appsec/iast/taint_sinks/path_traversal.py
  ddtrace/contrib/subprocess/patch.py
  tests/appsec/iast/test_command_injection.py
  tests/appsec/iast/test_path_traversal.py
Labels: changelog/no-changelog, ASM

#6565 feat(pytest): add option to disable ddtrace plugin
  ddtrace/contrib/pytest/__init__.py
  ddtrace/contrib/pytest/plugin.py
  releasenotes/notes/feat-pytest-add-no-ddtrace-option-fcbda62fe37723f9.yaml
  tests/contrib/pytest/test_pytest.py
Labels: CI App

#6267 chore(asm): add taint tracking for json.loads
  ddtrace/appsec/iast/_patch.py
  ddtrace/appsec/iast/_patch_modules.py
  ddtrace/appsec/iast/_patches/json_tainting.py
  ddtrace/appsec/iast/_taint_utils.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/test_json_tainting.py
  tests/contrib/subprocess/test_subprocess_patch.py
Labels: changelog/no-changelog, ASM

#6570 chore(profiling): resolve bandit warnings
  ddtrace/profiling/collector/_lock.py
  pyproject.toml
Labels: changelog/no-changelog

#6571 ci: run lib-injection workflow only when needed on PRs
  .github/workflows/lib-injection.yml
Labels: changelog/no-changelog

#6576 ci: fix readthedocs build
  .readthedocs.yml
Labels: changelog/no-changelog

#6519 chore(ci): itr on ddtrace
  .circleci/config.templ.yml
  .coveragerc
  riotfile.py
  scripts/ddtest
Labels: changelog/no-changelog, CI

#6443 feat(ci-visibility): pytest ITR support, make ITR enabled by API, overridable by env var
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/settings/config.py
  docs/configuration.rst
  releasenotes/notes/fix-e8168413eeec1e85.yaml
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
Labels: CI App

#6574 chore(asm): support fast tainting by using 24 low order bits of the hash in python3.9+
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.cpp
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
Labels: changelog/no-changelog, ASM

#6581 ci: fix pytest --ddtrace for forks
  .circleci/config.templ.yml
Labels: changelog/no-changelog, CI

#6582 chore(tests): make sure pytest tests run with a clean environment
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/pytest/test_pytest.py
  tests/utils.py
Labels: changelog/no-changelog, CI App, CI

#6487 chore(ci-visibility): rename fixture filenames in tests
  tests/ci_visibility/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog, CI App

#6462 docs: add correct default for propagation style
  docs/configuration.rst
Labels: changelog/no-changelog

#6586 ci: disable civisibility for integration tests
  riotfile.py
Labels: changelog/no-changelog, CI

#6392 chore(flask): remove APM logic from flask request wrapper
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/handlers.py
  ddtrace/contrib/flask/patch.py
  ddtrace/internal/constants.py
  ddtrace/tracing/trace_handlers.py
Labels: changelog/no-changelog, ASM

#6508 chore(telemetry): track configurations that set trace sampling rates
  ddtrace/internal/constants.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/sampler.py
  ddtrace/settings/config.py
  tests/telemetry/test_writer.py
  tests/tracer/test_sampler.py
  tests/utils.py
Labels: changelog/no-changelog

#6375 feat(pytest-benchmark): implement pytest-benchmark support
  .circleci/config.templ.yml
  .riot/requirements/1740ff3.txt
  .riot/requirements/316cce8.txt
  .riot/requirements/4d7c6fc.txt
  .riot/requirements/8bae4f8.txt
  ddtrace/contrib/pytest_benchmark/__init__.py
  ddtrace/contrib/pytest_benchmark/constants.py
  ddtrace/contrib/pytest_benchmark/plugin.py
  pyproject.toml
  releasenotes/notes/add-pytest-benchmark-support-71c6505ca4b202f3.yaml
  riotfile.py
  setup.py
  tests/contrib/pytest_benchmark/__init__.py
  tests/contrib/pytest_benchmark/test_pytest_benchmark.py
Labels: enhancement

#6309 feat(pytest): add codefresh unit-test helper function and fix buildkite unit-tests
  ddtrace/ext/ci.py
  releasenotes/notes/fix-codefresh-integration-563b8075e71881e4.yaml
  tests/tracer/fixtures/ci/azurepipelines.json
  tests/tracer/fixtures/ci/bitbucket.json
  tests/tracer/fixtures/ci/bitrise.json
  tests/tracer/fixtures/ci/buddy.json
  tests/tracer/fixtures/ci/buildkite.json
  tests/tracer/fixtures/ci/circleci.json
  tests/tracer/fixtures/ci/codefresh.json
  tests/tracer/fixtures/ci/gitlab.json
  tests/tracer/fixtures/ci/jenkins.json
  tests/tracer/fixtures/ci/teamcity.json
  tests/tracer/fixtures/ci/travisci.json
  tests/tracer/test_ci.py
Labels: enhancement, CI App

#6597 ci: system-tests steps conditional so the job can be required and skipped
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#6572 ci: run C checks only if needed
  .circleci/config.templ.yml
  scripts/cppcheck.sh
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#6583 fix(ci-visibility): do not enable CIVisibility service in agentless mode if DD_API_KEY is not set
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/fix-civisibility-dont-enable-if-agentless-without-api-f57875b2477862f7.yaml
  tests/integration/test_integration_civisibility.py
Labels: CI App, backport 1.16, backport 1.17

#6608 ci: fix dynamic config on default branch
  scripts/needs_testrun.py
Labels: changelog/no-changelog

#6609 ci: make PR match patterns if unable to get changed files
  scripts/needs_testrun.py
Labels: changelog/no-changelog

#6598 ci(pre-check): fix failing hatch check
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#6601 chore(asm): raw body django tainting for IAST
  ddtrace/appsec/handlers.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#6599 chore: optional build testrunner
  .github/workflows/testrunner.yml
Labels: changelog/no-changelog

#6610 ci: fix tornado flakyness
  tests/contrib/tornado/utils.py
Labels: changelog/no-changelog, CI

#6605 fix(profiling): add (one of?) the correct classes to lock profiling exporting
  ddtrace/profiling/exporter/pprof.pyx
Labels: changelog/no-changelog, backport 1.14, backport 1.15, backport 1.16, backport 1.17, backport 1.18

#6600 ci: skip riot runs based on diff from last successful run
  .circleci/config.templ.yml
  scripts/needs_testrun.py
  scripts/run-test-suite
Labels: changelog/no-changelog

#6625 ci: remove erroneously committed breakpoint
  tests/contrib/psycopg/test_psycopg_async.py
Labels: changelog/no-changelog, backport 1.18

#6569 chore(lib-inject): allow all users to read and modify installed packages
  .github/workflows/lib-injection.yml
  docs/spelling_wordlist.txt
  lib-injection/Dockerfile
  releasenotes/notes/lib-injection-pkg-dir-permissions-aaac0059b6c21f30.yaml
Labels: backport 1.17

#6607 chore(asm): blocking behavior configuration status for Django
  ddtrace/appsec/_constants.py
  ddtrace/appsec/processor.py
  ddtrace/contrib/django/patch.py
  tests/appsec/response-custom.html
  tests/appsec/response-custom.json
  tests/appsec/rules-suspicious-requests-custom-actions.json
  tests/appsec/test_processor.py
  tests/appsec/test_telemetry.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec_telemetry.py
Labels: changelog/no-changelog, manual merge, ASM

#6627 test(debugging): reduce flakiness in status logger
  tests/debugging/mocking.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6630 ci: fail the job when tests fail
  scripts/run-test-suite
Labels: changelog/no-changelog, backport 1.18

#6632 ci: revert broken changes to CI harness
  .circleci/config.templ.yml
  scripts/needs_testrun.py
  scripts/run-test-suite
Labels: changelog/no-changelog

#6637 ci: clean up code in needs_testrun script
  scripts/needs_testrun.py
Labels: changelog/no-changelog

#6393 chore(flask): remove tracing logic from some flask wrapper functions
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/handlers.py
  ddtrace/contrib/flask/patch.py
  ddtrace/tracing/trace_handlers.py
Labels: changelog/no-changelog, ASM

#6642 test(profiling): unset DD_SITE variable in agentless URL check
  tests/conftest.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog, Profiling, backport 1.16, backport 1.17, backport 1.18

#6624 ci: fix subprocess wrapper
  .riot/requirements/1c84c16.txt
  riotfile.py
  scripts/gen_circleci_config.py
  tests/conftest.py
  tests/meta/__init__.py
  tests/meta/test_conftest.py
Labels: changelog/no-changelog, CI, backport 1.18

#6633 chore(asm): tracer must report appsec as the decision maker for manual keep in appsec events
  ddtrace/appsec/iast/processor.py
  ddtrace/appsec/processor.py
  ddtrace/appsec/trace_utils.py
  releasenotes/notes/fix_decision_manager-952c44f0560c3ad1.yaml
  tests/appsec/test_appsec_trace_utils.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: bug, ASM

#6648 chore(tests): make sure pytest tests run with a clean environment (backport #6582 to 1.17)
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/pytest/test_pytest.py
  tests/utils.py
Labels: changelog/no-changelog, CI App

#6649 chore(ci suitespec): default to diffing against base branch if exactly 30 changed files returned
  scripts/needs_testrun.py
Labels: changelog/no-changelog

#6635 fix(httplib): avoid tracing requests made by trace writers
  ddtrace/contrib/httplib/patch.py
  ddtrace/internal/constants.py
  ddtrace/internal/writer/writer.py
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/httplib/test_httplib.py
  tests/utils.py
Labels: changelog/no-changelog, CI

#6640 chore: migrate prechecks from riot
  .circleci/config.templ.yml
  hatch.toml
  riotfile.py
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#6655 chore(ci): add meta-testing to hatch
  hatch.toml
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#6654 chore(ci): pin circleCI images
  .circleci/config.templ.yml
  .circleci/config.yml
Labels: changelog/no-changelog

#6639 fix(lib-inject): allow all users to read and modify installed packages [backport #6569 to 1.17]
  .github/workflows/lib-injection.yml
  docs/spelling_wordlist.txt
  lib-injection/Dockerfile
  releasenotes/notes/lib-injection-pkg-dir-permissions-aaac0059b6c21f30.yaml
Labels: backport 1.17

#6656 chore(asm): add exponential backoff and more retries to prevent flakiness in appsec test
  tests/appsec/test_remoteconfiguration_e2e.py
Labels: changelog/no-changelog, ASM

#6529 fix(profiling): ddup support arm, fix import on osx/windows
  ddtrace/internal/datadog/profiling/_ddup.pyi
  ddtrace/internal/datadog/profiling/_ddup.pyx
  ddtrace/internal/datadog/profiling/ddup.py
  ddtrace/internal/datadog/profiling/src/exporter.cpp
  ddtrace/internal/datadog/profiling/src/interface.cpp
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc.pyi
  ddtrace/profiling/collector/_memalloc_tb.c
  ddtrace/profiling/collector/_memalloc_tb.h
  ddtrace/profiling/collector/_traceback.pyi
  ddtrace/profiling/collector/_traceback.pyx
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/event.py
  ddtrace/profiling/exporter/pprof.pyx
  pyproject.toml
  setup.py
Labels: changelog/no-changelog, backport 1.18

#6660 chore(telemetry): track service naming configurations
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  ddtrace/settings/peer_service.py
  ddtrace/tracer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#6615 chore(asm): blocking behavior configuration status for Flask
  ddtrace/appsec/_constants.py
  ddtrace/appsec/utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/internal/constants.py
  ddtrace/tracing/trace_handlers.py
  releasenotes/notes/blocking_behaviour_configuration-158d1ed1d85dd7d9.yaml
  tests/appsec/test_remoteconfiguration.py
  tests/contrib/flask/test_flask_appsec.py
Labels: ASM

#6394 chore(flask): remove APM logic from Flask WSGI middleware
  ddtrace/appsec/handlers.py
  ddtrace/contrib/flask/patch.py
  ddtrace/tracing/trace_handlers.py
Labels: changelog/no-changelog, ASM

#6682 fix: don't crash when mariadb connection string doesn't include port or user
  ddtrace/contrib/mariadb/patch.py
  releasenotes/notes/maria-missing-port-e30630b4f5a5ee33.yaml
  tests/contrib/mariadb/test_mariadb.py
Labels: backport 1.16, backport 1.17, backport 1.18

#6683 ci: use check diff arguments in black and isort checks
  ddtrace/appsec/iast/_taint_utils.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/ext/ci.py
  ddtrace/internal/datadog/profiling/ddup.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/exporter/pprof.pyx
  hatch.toml
  pyproject.toml
  tests/contrib/httplib/test_httplib.py
  tests/contrib/pytest_benchmark/test_pytest_benchmark.py
  tests/contrib/tornado/utils.py
Labels: changelog/no-changelog

#6629 ci(framework tests): skip failing sanic test [backport #6539 to 1.16]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 1.16, backport 1.17

#6628 ci(framework tests): skip failing sanic test [backport #6539 to 1.17]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#6685 feat(iast): report telemetry error logs
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/handlers.py
  ddtrace/appsec/iast/_metrics.py
  ddtrace/appsec/iast/_taint_tracking/aspects.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/appsec/utils.py
  tests/appsec/test_telemetry.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6686 docs(asgi): clarify python version requirements for AsyncioContextProvider
  ddtrace/contrib/asgi/__init__.py
  ddtrace/contrib/fastapi/__init__.py
  ddtrace/contrib/sanic/__init__.py
  ddtrace/contrib/starlette/__init__.py
Labels: changelog/no-changelog

#6674 fix(django): populate span.resource on forced exit
  .gitignore
  ddtrace/contrib/django/utils.py
  releasenotes/notes/fix-django-span-resource-on-unexpected-terminate-fbc5ce27d503d635.yaml
  tests/contrib/django/test_django.py
Labels: backport 1.16, backport 1.17, backport 1.18

#6684 fix(ci-visibility): revert ITR to using DD_CIVISIBILITY_ITR_ENABLED env var
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/settings/config.py
  docs/configuration.rst
  releasenotes/notes/fix-itr-use-enabled-env-var-ef043a640843baff.yaml
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
Labels: backport 1.18

#6702 ci: use a fake key for system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, backport 1.16, backport 1.17, backport 1.18

#6700 chore: move some functions to a new appsec/_capabilities.py file to avoid cyclic imports
  ddtrace/appsec/_capabilities.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/processor.py
  ddtrace/appsec/utils.py
  ddtrace/internal/remoteconfig/client.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#6704 ci: use a fake key for system tests [backport #6702 to 1.17]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, backport 1.16, backport 1.17, backport 1.18

#6678 fix(ci-visibility): make ITR enable properly in EVP mode
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-itr-in-evp-mode-e66fa0ef8a6ffe72.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: CI App, backport 1.17, backport 1.18

#6673 docs: pin furo version used to generate ddtrace docs
  hatch.toml
  releasenotes/notes/pin-furo-ddtrace-docs-1ceb42ce17f7a1db.yaml
Labels: changelog/no-changelog, backport 1.16, backport 1.17, backport 1.18

#6707 chore(asm): upgrade libddwaf to 1.13.1
  ddtrace/appsec/ddwaf/ddwaf_types.py
  setup.py
  tests/appsec/test_ddwaf_fuzz.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#6672 test(debugging): make simple Flask scenario
  benchmarks/bm/di_utils.py
  benchmarks/bm/flask_utils.py
  benchmarks/flask_simple/app.py
  benchmarks/flask_simple/config.yaml
  benchmarks/flask_simple/gunicorn.conf.py
  benchmarks/flask_simple/scenario.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6719 chore: rename _iast._util to _iast._utils
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/handlers.py
  ddtrace/appsec/iast/_loader.py
  ddtrace/appsec/iast/_patch.py
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/_utils.py
  ddtrace/appsec/iast/processor.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/appsec/iast/taint_sinks/sql_injection.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/dbapi_async/__init__.py
  ddtrace/contrib/trace_utils.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/ast/test_ast_patching.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/iast/test_json_tainting.py
  tests/appsec/iast/test_path_traversal.py
  tests/appsec/iast/test_processor.py
  tests/appsec/iast/test_reporter.py
  tests/appsec/iast/test_taint_tracking.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/iast/test_weak_hash.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#6728 ci: rename lib-injection job name
  .github/workflows/lib-injection.yml
Labels: changelog/no-changelog, backport 1.16, backport 1.17, backport 1.18

#6667 chore(debugging): use maxFieldCount snapshot probe property
  ddtrace/debugging/_probe/remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6714 fix(debugging): emit probe status updates unconditionally
  ddtrace/debugging/_probe/remoteconfig.py
  releasenotes/notes/fix-di-probe-status-emit-on-no-data-eb9b13d0343f92c7.yaml
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation, backport 1.16, backport 1.17, backport 1.18

#6668 chore(debugging): improve serialisation logic
  ddtrace/debugging/_signal/utils.py
  tests/debugging/test_encoding.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6680 chore(telemetry): track trace sampling rules
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/sampler.py
  ddtrace/settings/config.py
  tests/telemetry/test_writer.py
  tests/tracer/test_sampler.py
  tests/utils.py
Labels: changelog/no-changelog

#6730 fix(benchmark/iast): fix attribute error exception
  benchmarks/flask_sqli/config.yaml
  benchmarks/flask_sqli/scenario.py
Labels: changelog/no-changelog, ASM

#6725 chore(iast): propagation benchmark tests
  .gitlab/benchmarks.yml
  benchmarks/appsec_iast_propagation/config.yaml
  benchmarks/appsec_iast_propagation/scenario.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6726 chore(iast): remove iast setup from python code
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/iast/_taint_tracking/README.txt
  ddtrace/appsec/iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintedOps/TaintedOps.h
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/_taint_tracking/_native.cpp
  ddtrace/appsec/iast/taint_sinks/command_injection.py
  ddtrace/appsec/iast/taint_sinks/path_traversal.py
  ddtrace/bootstrap/sitecustomize.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_common_replace_aspects.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
  tests/appsec/iast/test_command_injection.py
  tests/appsec/iast/test_json_tainting.py
  tests/appsec/iast/test_path_traversal.py
  tests/appsec/iast/test_taint_tracking.py
  tests/appsec/iast/test_taint_utils.py
  tests/appsec/iast/test_telemetry.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6395 chore(flask): use non-trace-specific naming in Flask contrib
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/handlers.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask/wrappers.py
  ddtrace/internal/compat.py
  ddtrace/tracing/trace_handlers.py
Labels: changelog/no-changelog, ASM

#6718 chore(ci-visibility): fix env for _check_enabled_features test
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, backport 1.17, backport 1.18

#6566 fix: address incompatibilities between ddtrace and the builtin multiprocessing library
  ddtrace/internal/remoteconfig/_connectors.py
  releasenotes/notes/fix-monkey-patch-on-import-5cfb79bf2eea7c7e.yaml
  tests/appsec/test_remoteconfiguration_e2e.py
Labels: backport 1.17, backport 1.18

#6746 chore(iast): bytes and bytearray propagation
  ddtrace/appsec/iast/_taint_tracking/aspects.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6748 chore(iast): repr propagation
  ddtrace/appsec/iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6747 chore(iast): zfill propagation
  ddtrace/appsec/iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6623 chore(asm): adds function to ensure the Flask entrypoint file is patched for IAST
  ddtrace/appsec/_deduplications.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/iast/__init__.py
  ddtrace/appsec/iast/_ast/ast_patching.py
  ddtrace/appsec/iast/_ast/visitor.py
  ddtrace/appsec/iast/_metrics.py
  ddtrace/appsec/iast/_taint_tracking/aspects.py
  ddtrace/appsec/utils.py
  ddtrace/contrib/flask/__init__.py
  docs/spelling_wordlist.txt
  releasenotes/notes/asm-iast-flask-patch-95c5358926e8e5ed.yaml
  tests/appsec/iast/fixtures/entrypoint/__init__.py
  tests/appsec/iast/fixtures/entrypoint/app.py
  tests/appsec/iast/fixtures/entrypoint/app_patched.py
  tests/appsec/iast/test_iast_entrypoint_patches.py
  tests/appsec/iast/test_taint_utils.py
  tests/appsec/test_telemetry.py
Labels: ASM, Custom Code Private Beta

#6751 fix(benchmark/iast): fix import error in propagation scenario
  benchmarks/appsec_iast_propagation/scenario.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6753 chore(rcm): get connection on every request
  ddtrace/internal/remoteconfig/client.py
Labels: changelog/no-changelog

#6740 fix(debugging): emit probe status updates unconditionally [backport #6714 to 1.18]
  ddtrace/debugging/_probe/remoteconfig.py
  releasenotes/notes/fix-di-probe-status-emit-on-no-data-eb9b13d0343f92c7.yaml
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation

#6742 fix(debugging): emit probe status updates unconditionally [backport #6714 to 1.16]
  ddtrace/debugging/_probe/remoteconfig.py
  releasenotes/notes/fix-di-probe-status-emit-on-no-data-eb9b13d0343f92c7.yaml
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation, backport 1.16, backport 1.17, backport 1.18

#6741 fix(debugging): emit probe status updates unconditionally [backport #6714 to 1.17]
  ddtrace/debugging/_probe/remoteconfig.py
  releasenotes/notes/fix-di-probe-status-emit-on-no-data-eb9b13d0343f92c7.yaml
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation, backport 1.16, backport 1.17, backport 1.18

#6749 chore(iast): fstrings propagation and fix format aspect errors
  ddtrace/appsec/iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/fixtures/aspects/str_methods_py3.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6761 fix(debugging): handle multiple injection points [backport #6759 to 1.18]
  ddtrace/internal/injection.py
  ddtrace/internal/utils/inspection.py
  releasenotes/notes/fix-debugger-multiple-inject-locs-2dd1d33810cf6405.yaml
  tests/internal/test_injection.py
  tests/submod/stuff.py
Labels: Dynamic Instrumentation

#6618 fix(debugging): ensure dynamic instrumentation enabled
  ddtrace/debugging/_debugger.py
  releasenotes/notes/fix-di-enable-programmatic-api-2dd583ac87af5451.yaml
  tests/debugging/test_api.py
Labels: Dynamic Instrumentation, backport 1.18

#6732 fix(debugging): use millisecond for duration in expression DSL
  ddtrace/debugging/_signal/model.py
  releasenotes/notes/fix-debugger-duration-ms-in-dsl-aad91c0b730bbdf0.yaml
  tests/debugging/signal/test_model.py
Labels: Dynamic Instrumentation, backport 1.18

#6712 chore(telemetry): ensure metrics are aggegated every 10 secs but sent after 60 secs
  ddtrace/internal/processor/trace.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  tests/telemetry/conftest.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#6396 chore(flask): remove APM logic from Flask contrib
  ddtrace/contrib/flask/helpers.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask/wrappers.py
  ddtrace/tracing/trace_handlers.py
Labels: changelog/no-changelog

#6770 chore(ci-visibility): add docstrings to pytest fixtures
  ddtrace/contrib/pytest/plugin.py
Labels: changelog/no-changelog, CI App

#6764 chore(codeowners): update codeowners
  .github/CODEOWNERS
Labels: changelog/no-changelog, mergequeue-status: error

#6771 fix(iast): command injection skipped
  ddtrace/appsec/iast/taint_sinks/command_injection.py
  ddtrace/contrib/subprocess/patch.py
  tests/appsec/iast/test_command_injection.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6559 feat(unittest): add unittest support for test visibility
  .circleci/config.templ.yml
  .riot/requirements/10b31b2.txt
  .riot/requirements/16b3d1d.txt
  .riot/requirements/1b0a62d.txt
  .riot/requirements/1bd6f1c.txt
  .riot/requirements/1cf1760.txt
  .riot/requirements/3013656.txt
  .riot/requirements/d6a02a4.txt
  .riot/requirements/d75c291.txt
  ddtrace/_monkey.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/contrib/unittest/__init__.py
  ddtrace/contrib/unittest/constants.py
  ddtrace/contrib/unittest/patch.py
  ddtrace/internal/ci_visibility/encoder.py
  ddtrace/settings/config.py
  docs/integrations.rst
  releasenotes/notes/add-unittest-support-024c4664f6546c21.yaml
  riotfile.py
  tests/.suitespec.json
  tests/contrib/unittest_plugin/__init__.py
  tests/contrib/unittest_plugin/test_unittest.py
Labels: enhancement, CI App

#6774 chore(telemetry): track startup logs configuration
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#6172 fix(remoteconfig): handle process fork inside remote config client
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
  tests/internal/remoteconfig/test_remoteconfig.py
Labels: changelog/no-changelog, backport 1.15, mergequeue-status: error

#6418 chore(flask): remove span knowledge from flask wsgi middleware
  ddtrace/appsec/handlers.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/tracing/trace_handlers.py
Labels: changelog/no-changelog

#6779 ci(telemetry): fix failing instrumentation telemetry test [backport to 1.18]
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#6727 chore(asm): api security using libddwaf
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_api_security/preprocessors.json
  ddtrace/appsec/_api_security/schema.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/ddwaf/ddwaf_types.py
  ddtrace/appsec/processor.py
  tests/appsec/api_security/test_schema_fuzz.py
  tests/appsec/rules-suspicious-requests.json
  tests/contrib/django/test_django_appsec_api_security.py
  tests/contrib/flask/test_appsec_api_security.py
Labels: changelog/no-changelog, ASM

#6750 test(debugging): remove flakiness in test suite
  tests/debugging/exception/test_auto_instrument.py
  tests/debugging/function/test_discovery.py
  tests/debugging/mocking.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/test_debugger.py
  tests/debugging/test_uploader.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6758 ci: backport of conditional system tests configuration
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, backport 1.16

#6772 chore(rq): pass command arguments to rq test suite from riotfile
  riotfile.py
Labels: changelog/no-changelog

#6773 docs: write guide on adding new test suites to circleci
  docs/contributing-integrations.rst
  docs/contributing-testing.rst
Labels: changelog/no-changelog, CI App

#6785 chore(iast): add propagation and taint sink tests
  ddtrace/appsec/iast/_taint_tracking/aspects.py
  ddtrace/appsec/iast/reporter.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_sql_injection.py
  tests/appsec/iast/test_iast_propagation_path.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6425 chore(internal): appsec core API use cleanups
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/handlers.py
Labels: changelog/no-changelog

#6796 chore(release): fix typo
  scripts/release.py
Labels: changelog/no-changelog

#6790 fix(docs): fix more broken links still pointing to .rst files
  docs/contributing-integrations.rst
  docs/contributing-testing.rst
  docs/contributing.rst
  docs/releasenotes.rst
Labels: changelog/no-changelog

#6795 chore(iast): add memory tests
  tests/appsec/iast/test_iast_mem_check.py
  tests/appsec/iast/test_iast_propagation_path.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6735 fix(datastreams): support datastream propagation with raw message delivery enabled
  ddtrace/contrib/botocore/patch.py
  releasenotes/notes/datastreams-fix-sns-raw-delivery-044e514a84e132be.yaml
  tests/contrib/botocore/test.py
Labels: backport 1.17, backport 1.18

#6789 test(debugging): remove flakiness in RCM tests
  ddtrace/debugging/_probe/remoteconfig.py
  tests/debugging/probe/test_remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6792 fix(setup): out-of-memory error
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
  .github/workflows/system-tests.yml
  .github/workflows/test_frameworks.yml
  .gitlab/benchmarks.yml
  docs/spelling_wordlist.txt
  releasenotes/notes/setup-oom-errors-426c9951d5c9ed57.yaml
  riotfile.py
  setup.py
Labels: ASM, backport 1.18

#6768 fix: fix memleaks from the native module
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/Source.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintedObject.h
  ddtrace/appsec/iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/conftest.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM, Custom Code Private Beta

#6787 chore(telemetry): refactor and track trace writer configurations
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/constants.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/__init__.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  tests/integration/test_integration.py
  tests/integration/test_integration_snapshots.py
  tests/integration/test_priority_sampling.py
  tests/integration/utils.py
  tests/telemetry/test_writer.py
  tests/tracer/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog
