Repository DataDog/dd-trace-py, pull requests merged in 2023-10, with the labels that each got.

#7090 chore(tests): tracer test relaxed
  tests/tracer/runtime/test_metric_collectors.py
Labels: changelog/no-changelog, CI

#7107 chore(iast): update parameters type and naming
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.h
Labels: changelog/no-changelog, ASM

#7117 chore(asm): migrate appsec constants to drop python2 compatibility
  ddtrace/appsec/_constants.py
Labels: changelog/no-changelog, ASM

#6930 chore(benchmarks): fix import of samplingrule
  benchmarks/sampling_rule_matches/scenario.py
Labels: changelog/no-changelog

#6917 chore: fix wrong version in the docs for automatic login events
  docs/configuration.rst
Labels: changelog/no-changelog, ASM

#7071 ci: add settings/config.py to core in suitespec
  tests/.suitespec.json
Labels: changelog/no-changelog

#7118 chore(asm): migrate appsec trace_utils to drop python2 compatibility
  ddtrace/appsec/_trace_utils.py
Labels: changelog/no-changelog, ASM

#7067 chore(ci_visibility): remove app key requirement for ITR
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App, backport 2.0

#6890 chore(kafka): use core api for data streams monitoring
  ddtrace/contrib/kafka/patch.py
  ddtrace/internal/datastreams/__init__.py
  ddtrace/internal/datastreams/kafka.py
  ddtrace/internal/datastreams/processor.py
  ddtrace/tracer.py
  pyproject.toml
  releasenotes/notes/dsm-fix-offsets-and-metrics-7e34b2734667e986.yaml
  tests/contrib/kafka/test_kafka.py
  tests/datastreams/test_processor.py
  tests/utils.py
Labels: changelog/no-changelog, backport 1.20

#7121 chore(asm): migrate appsec processor to drop python2 compatibility
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
Labels: changelog/no-changelog, ASM

#7135 chore(asm): migrate appsec capabilities to drop python2 compatibility
  ddtrace/appsec/_capabilities.py
Labels: changelog/no-changelog, ASM

#7136 chore(asm): migrate appsec utils to drop python2 compatibility
  ddtrace/appsec/_utils.py
Labels: changelog/no-changelog, ASM

#7137 chore(asm): migrate appsec handlers to drop python2 compatibility
  ddtrace/appsec/_handlers.py
Labels: changelog/no-changelog, ASM

#7126 chore(asm): fix win32 fork usage error
  ddtrace/settings/config.py
Labels: changelog/no-changelog

#7124 fix(profiling): import protobuf only if needed
  ddtrace/profiling/profiler.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-profiler-protobuf-if-needed-9c64068ab27e7352.yaml
Labels: Profiling

#7112 fix: reference leaks and incorrect C-API usage in _stacktrace.c
  ddtrace/appsec/_iast/_stacktrace.c
  releasenotes/notes/fix-iast-mem-leak-25b7ae83cea24bd6.yaml
Labels: bug, changelog/no-changelog, ASM, backport 1.20, backport 2.0

#7140 ci: force setuptools_scm to use guess-next-dev scheme in 2.0
  pyproject.toml
Labels: changelog/no-changelog

#7119 fix(rcm): add git metadata to requests
  ddtrace/internal/gitmetadata.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/settings/dynamic_instrumentation.py
  releasenotes/notes/fix-rc-git-metadata-in-request-bc95d730be17831a.yaml
Labels: backport 1.20, backport 2.0

#7150 chore(asm): migrate appsec deduplication to drop python2 compatibility
  ddtrace/appsec/_deduplications.py
Labels: changelog/no-changelog, ASM

#7111 chore(ci): fix scheduled system tests (backport #7105 to 2.0)
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#7158 fix: revert restriction on psutil and wrapt versions
  docs/spelling_wordlist.txt
  pyproject.toml
  releasenotes/notes/deps-pin-5d4111479a0cc33b.yaml
  setup.py
Labels: backport 2.0, backport 2.1

#7151 fix(internal): no lazy bytecode imports
  ddtrace/internal/wrapping/__init__.py
  ddtrace/internal/wrapping/asyncs.py
  ddtrace/internal/wrapping/generators.py
  releasenotes/notes/fix-bytecode-no-lazy-imports-fc229b23e60fca53.yaml
Labels: backport 2.0, backport 2.1

#7131 chore(pyodbc): set db.system and db.user span tags
  ddtrace/contrib/pyodbc/patch.py
  tests/contrib/pyodbc/test_pyodbc.py
Labels: changelog/no-changelog

#7099 chore(tracing): improve debug logging for v05 encoding errors
  ddtrace/internal/_encoding.pyi
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/writer/writer.py
  tests/integration/test_integration.py
  tests/tracer/test_encoders.py
  tests/utils.py
Labels: changelog/no-changelog, backport 1.20

#7177 fix(iast): decouple executed sink metric call [backport 2.0]
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/_iast/taint_sinks/weak_hash.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/dbapi_async/__init__.py
  releasenotes/notes/fix-executed-sink-telemetry-metric-1d961a4e618a4843.yaml
Labels: ASM

#7095 fix(debugging): report error info on every probe error
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/registry.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_probe/status.py
  releasenotes/notes/fix-debugger-probe-error-details-c2650877a6dae670.yaml
  tests/debugging/probe/test_registry.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/probe/test_status.py
Labels: Dynamic Instrumentation, backport 1.20, backport 2.0, backport 2.1

#7185 docs: do not include compiled release notes in readthedocs builds
  docs/_release_notes_all.rst
  docs/index.rst
  docs/release_notes.rst
Labels: changelog/no-changelog

#7178 fix(ci_visibility): git metadata fallback commands
  ddtrace/ext/git.py
  ddtrace/internal/ci_visibility/git_client.py
  tests/ci_visibility/test_ci_visibility.py
  tests/tracer/test_ci.py
Labels: changelog/no-changelog, backport 1.20, backport 2.0, backport 2.1

#6928 chore(internal): include complex among simple builtin types
  ddtrace/internal/compat.py
Labels: changelog/no-changelog

#7192 fix(iast): slice propagation ranges error
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#7182 fix(tracing): fix type signature on span.set_tags to allow non-text values
  ddtrace/span.py
  releasenotes/notes/set-tags-hint-0f3d2e5665c595df.yaml
Labels: backport 2.0, backport 2.1

#7199 docs: update default value for trace api configurations
  docs/configuration.rst
Labels: changelog/no-changelog, backport 1.20

#7207 chore(tests): add fastapi new variant to github workflow
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#7116 chore: introduce assembly language support
  ddtrace/internal/assembly.py
  ddtrace/internal/injection.py
  ddtrace/internal/wrapping/__init__.py
  ddtrace/internal/wrapping/asyncs.py
  ddtrace/internal/wrapping/generators.py
  tests/internal/test_assembly.py
  tests/internal/test_injection.py
Labels: changelog/no-changelog

#7129 chore(tornado): add http.route tags to tornado requests
  ddtrace/contrib/tornado/handlers.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/tornado/web/app.py
Labels: changelog/no-changelog

#7204 fix(signals): only handle signals if in main thread
  ddtrace/internal/atexit.py
  releasenotes/notes/signals-fix-import-in-thread-error-1d68cb76472268d7.yaml
  tests/datastreams/test_processor.py
  tests/tracer/test_tracer.py
Labels: backport 1.19, backport 1.20, backport 2.0, backport 2.1

#7210 fix(ci_visibility): fix distributed tracing when using CIVisibility
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci_visibility-fix-distributed_tracing-733103ba3a19f3f7.yaml
  riotfile.py
Labels: CI App, backport 1.20, backport 2.0, backport 2.1

#7226 chore: fix typo in release note
  releasenotes/notes/ci_visibility-fix-distributed_tracing-733103ba3a19f3f7.yaml
Labels: changelog/no-changelog

#7215 fix(langchain): avoid direct root imports from langchain
  ddtrace/contrib/langchain/constants.py
  ddtrace/contrib/langchain/patch.py
  releasenotes/notes/langchain-fix-imports-dddd44cd581e6baa.yaml
  tests/contrib/langchain/test_langchain_patch.py
Labels: backport 1.20, backport 2.0, backport 2.1

#7198 docs: fix documentation of DD_TRACE_SAMPLE_RATE to reflect the actual default behavior
  docs/configuration.rst
Labels: changelog/no-changelog

#7229 docs: correct dogstatsd example configuration
  docs/configuration.rst
Labels: changelog/no-changelog

#6922 chore(django): remove some appsec code from django integration
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/internal/utils/http.py
Labels: changelog/no-changelog

#7242 fix(asm): fix segfault in IAST for f-string formatting of non-text values
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/iast-fix-fstring-format-d8f0fc1533c75cdb.yaml
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/fixtures/aspects/str_methods_py3.py
Labels: ASM, backport 1.19, backport 1.20, backport 2.0, backport 2.1

#7211 chore(tracer): activate query string tagging in url by default for fastapi
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/fastapi/patch.py
Labels: changelog/no-changelog

#7191 chore(rcm): unexpected debug logs
  ddtrace/settings/config.py
Labels: changelog/no-changelog, ASM

#7239 fix(lib-inject): set correct permissions on package files
  .github/workflows/lib-injection.yml
  .gitlab/build-deb-rpm.sh
  lib-injection/Dockerfile
  releasenotes/notes/lib-inject-permissions-8222a09585eb5350.yaml
Labels: backport 1.20, backport 2.0, backport 2.1

#7228 chore: update pypi changelog link
  pyproject.toml
Labels: changelog/no-changelog

#7146 chore(tracing): introduce a Datadog API api for span links
  ddtrace/context.py
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/constants.py
  ddtrace/span.py
  ddtrace/tracing/_span_link.py
  tests/tracer/test_encoders.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#7264 fix(iast): ssrf telemetry metrics
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
Labels: changelog/no-changelog, ASM

#7268 chore: revert structlog integration
  .circleci/config.templ.yml
  .riot/requirements/18d2bc2.txt
  .riot/requirements/3d8f535.txt
  .riot/requirements/90951b8.txt
  .riot/requirements/ae90d37.txt
  .riot/requirements/f69275d.txt
  .riot/requirements/ff6f3c2.txt
  ddtrace/_monkey.py
  ddtrace/contrib/logging/constants.py
  ddtrace/contrib/logging/patch.py
  ddtrace/contrib/structlog/__init__.py
  ddtrace/contrib/structlog/patch.py
  releasenotes/notes/structlog_integration-91b212bc8e416219.yaml
  riotfile.py
  tests/.suitespec.json
  tests/contrib/logging/test_logging.py
  tests/contrib/structlog/__init__.py
  tests/contrib/structlog/test_structlog_logging.py
  tests/contrib/structlog/test_structlog_patch.py
Labels: changelog/no-changelog

#7263 fix(tracing): fix msgpack import error
  ddtrace/internal/_encoding.pyi
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/writer/writer.py
  releasenotes/notes/fix-msgpack-errors-3fcf9f77a77c9786.yaml
  tests/integration/test_integration.py
  tests/tracer/test_encoders.py
  tests/utils.py
Labels: backport 1.20

#7262 chore(openai): refactor patch wrapping code
  ddtrace/contrib/openai/patch.py
Labels: changelog/no-changelog

#7276 chore: skip reliably failing test
  tests/contrib/logging/test_logging.py
Labels: changelog/no-changelog

#7225 fix(ci_visibility): add flag to show class in test name
  ddtrace/contrib/pytest/constants.py
  ddtrace/contrib/pytest/plugin.py
  releasenotes/notes/ci_visibility-fix-pytest-class-names-option-8675b04e442425a4.yaml
  tests/contrib/pytest/test_pytest.py
Labels: CI App, backport 1.20, backport 2.0, backport 2.1

#7283 chore: add prepend spelling
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog

#7266 fix(appsec): flask hangs on empty body requests
  ddtrace/appsec/_handlers.py
  releasenotes/notes/asm-fix-flask-body-blocking-aa4836d70f8e1ea8.yaml
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/test_handlers.py
  tests/appsec/test_remoteconfiguration_e2e.py
Labels: ASM, backport 1.18, backport 1.19, backport 1.20, backport 2.0, backport 2.1

#7290 fix(appsec): flask hangs on empty body requests [backport 2.0]
  ddtrace/appsec/_handlers.py
  releasenotes/notes/asm-fix-flask-body-blocking-aa4836d70f8e1ea8.yaml
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/test_handlers.py
  tests/appsec/test_remoteconfiguration_e2e.py
Labels: ASM

#7291 fix(appsec): flask hangs on empty body requests [backport 1.20]
  ddtrace/appsec/handlers.py
  releasenotes/notes/asm-fix-flask-body-blocking-aa4836d70f8e1ea8.yaml
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/test_handlers.py
  tests/appsec/test_remoteconfiguration_e2e.py
Labels: ASM

#7296 fix(asm): fix manual keep for user event
  ddtrace/appsec/trace_utils.py
  releasenotes/notes/fix_manual_keep_for_users_events-3b4b37a9ef9e50ea.yaml
  tests/appsec/test_appsec_trace_utils.py
Labels: bug, ASM, backport 1.16, backport 1.17

#7293 fix(appsec): flask hangs on empty body requests [backport 1.19]
  ddtrace/appsec/handlers.py
  releasenotes/notes/asm-fix-flask-body-blocking-aa4836d70f8e1ea8.yaml
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/test_handlers.py
  tests/appsec/test_remoteconfiguration_e2e.py
Labels: ASM

#7221 feat(ci_visibility): add pytest hooks for module, suite, and test naming
  ddtrace/contrib/pytest/newhooks.py
  ddtrace/contrib/pytest/plugin.py
  releasenotes/notes/ci_visibility-feature-pytest_naming_hooks-757f90c20b5b882b.yaml
  tests/contrib/pytest/test_pytest.py
Labels: CI App

#7292 fix(ci_visibility): fixes unittest enabling the CI VIsibility plugin
  ddtrace/contrib/unittest/patch.py
  releasenotes/notes/fix-unittest-git-patch-887a3963d4f58d8b.yaml
Labels: CI App, backport 2.0, backport 2.1

#7297 chore(opentelemetry): avoid using opentelemetry api internals
  ddtrace/opentelemetry/_context.py
Labels: changelog/no-changelog

#7275 fix(ci_visibility): fix adding test.skipped_by_itr tag
  ddtrace/contrib/pytest/plugin.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog, backport 1.20, backport 2.0, backport 2.1

#7302 chore(ci): moto package drops and delete all versions <= 1.0
  .riot/requirements/1312080.txt
  .riot/requirements/16f9188.txt
  .riot/requirements/43cbf74.txt
  .riot/requirements/6703ac7.txt
  .riot/requirements/737d2bb.txt
  .riot/requirements/ab0352c.txt
  .riot/requirements/b14f4a0.txt
  docs/spelling_wordlist.txt
  riotfile.py
Labels: changelog/no-changelog, ASM, backport 1.14, backport 1.13, backport 1.12, backport 1.11, backport 1.15, backport 1.10, backport 1.16, backport 1.17

#7298 fix(appsec): flask hangs on empty body requests [backport 1.17] (#7266)
  ddtrace/contrib/flask/patch.py
  releasenotes/notes/asm-fix-flask-body-blocking-aa4836d70f8e1ea8.yaml
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/test_handlers.py
  tests/appsec/test_remoteconfiguration_e2e.py
Labels: ASM

#7286 fix(debugging): function probes on same lazy module
  ddtrace/debugging/_debugger.py
  releasenotes/notes/fix-debugger-same-module-wrapping-5fa0653ca015874c.yaml
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation, backport 2.0, backport 2.1

#7308 chore(ci): moto package drops and delete all versions <= 1.0 [backport 1.15]
  .riot/requirements/1312080.txt
  .riot/requirements/16f9188.txt
  .riot/requirements/43cbf74.txt
  .riot/requirements/6703ac7.txt
  .riot/requirements/737d2bb.txt
  .riot/requirements/ab0352c.txt
  .riot/requirements/b14f4a0.txt
  docs/spelling_wordlist.txt
  riotfile.py
Labels: changelog/no-changelog, ASM

#7317 chore(asm): tests, change telemetry service interval to 120 seconds to avoid flakyness
  tests/appsec/conftest.py
Labels: changelog/no-changelog, ASM

#7258 fix(various): strip debuginfo on release
  setup.py
Labels: changelog/no-changelog, backport 1.20, backport 2.0, backport 2.1

#7318 fix(iast): potential string id collisions
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  releasenotes/notes/iast-fix-id-collisions-87da1c4229876398.yaml
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
Labels: ASM, backport 1.x, backport 2.0, backport 2.1

#7326 fix(iast): potential string id collisions [backport 1.x]
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.h
  releasenotes/notes/iast-fix-id-collisions-87da1c4229876398.yaml
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
Labels: ASM, backport 1.19, backport 1.20

#7333 fix(sampling): revert "refactor(writer): handle agent responses in the tracer (#6178)"
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/__init__.py
  ddtrace/internal/writer/writer.py
  ddtrace/tracer.py
  releasenotes/notes/fix-make-tracer-acknowledge-agent-sampling-decisions-2919150951ed1b81.yaml
Labels: backport 1.19, backport 1.20, backport 2.0, backport 2.1

#7348 fix(iast): patch json.encoder to encode LazyTaintDict as dict
  ddtrace/appsec/_iast/_patches/json_tainting.py
  releasenotes/notes/iast-fix-lazy-taint-json-encoder-89cdd9aba0351d96.yaml
  tests/appsec/iast/test_taint_utils.py
Labels: bug, ASM, backport 1.x, backport 2.0, backport 2.1

#7294 ci: run build job on more paths
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog, backport 1.19, backport 1.20, backport 2.0, backport 2.1

#6584 chore(debugging): convert type comments to annotations
  ddtrace/debugging/_async.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_exception/auto_instrument.py
  ddtrace/debugging/_expressions.py
  ddtrace/debugging/_function/discovery.py
  ddtrace/debugging/_function/store.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/registry.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_probe/status.py
  ddtrace/debugging/_safety.py
  ddtrace/debugging/_signal/collector.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_signal/snapshot.py
  ddtrace/debugging/_signal/tracing.py
  ddtrace/debugging/_signal/utils.py
  ddtrace/debugging/_uploader.py
  ddtrace/internal/module.py
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
  tests/debugging/mocking.py
  tests/debugging/test_async.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#7346 fix(profiling): numeric type exception in memalloc
  ddtrace/profiling/collector/memalloc.py
  releasenotes/notes/fix-numeric-exception-profiling-memalloc-5ad925dbb60ad078.yaml
Labels: Profiling

#7357 fix(iast): patch json.encoder to encode LazyTaintDict as dict [backport 1.x]
  ddtrace/appsec/iast/_patches/json_tainting.py
  releasenotes/notes/iast-fix-lazy-taint-json-encoder-89cdd9aba0351d96.yaml
  tests/appsec/iast/test_taint_utils.py
Labels: bug, ASM, backport 1.18, backport 1.19, backport 1.20

#7345 test(confluent-kafka): assert current confluent-kafka propagation behavior for DSM and traces
  tests/contrib/kafka/test_kafka.py
Labels: changelog/no-changelog

#7340 chore(iast): store hash and id separately in tx_taint_map
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
Labels: changelog/no-changelog, ASM

#7334 chore(tracer): update obfuscation query string regex
  ddtrace/settings/config.py
Labels: changelog/no-changelog

#7260 chore: remove compiled sources from wheels
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, manual merge

#7329 fix(ci_visibility): use custom configurations when querying ITR skippable tests endpoint
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App, backport 1.20, backport 2.0, backport 2.1

#7366 ci(sanic): skip sanic framework test
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 1.18, backport 1.19

#7281 chore(asm): django automatic login events updates
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/trace_utils.py
  tests/appsec/test_appsec_trace_utils.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask_login/test_flask_login_appsec.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog, ASM

#7379 ci: run framework tests if frameworks.yml modified
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 1.19, backport 1.20, backport 2.0, backport 2.1

#7367 chore(iast): add collision tests for bytes and bytearray
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
Labels: changelog/no-changelog, ASM

#7197 chore(debugging): support more decorators
  ddtrace/debugging/_function/discovery.py
  tests/debugging/function/test_discovery.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#7380 ci(sanic): disable sanic framework test
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 2.0, backport 2.1

#7378 fix(appsec): transfer-encoding chunked requests are dropped
  .riot/requirements/11c167a.txt
  .riot/requirements/13790d2.txt
  .riot/requirements/1483961.txt
  .riot/requirements/15bb169.txt
  .riot/requirements/162a088.txt
  .riot/requirements/194b700.txt
  .riot/requirements/1961d96.txt
  .riot/requirements/1ba9802.txt
  .riot/requirements/1f1bd7d.txt
  .riot/requirements/1ff2b07.txt
  .riot/requirements/2b46598.txt
  .riot/requirements/5bb1431.txt
  .riot/requirements/5ea5e85.txt
  .riot/requirements/5ee9ded.txt
  .riot/requirements/840df3c.txt
  .riot/requirements/8b732cf.txt
  .riot/requirements/9821cdd.txt
  .riot/requirements/c9b99a0.txt
  .riot/requirements/e368746.txt
  .riot/requirements/f00ead8.txt
  ddtrace/appsec/_handlers.py
  releasenotes/notes/asm-fix-chunked-requests-1f703ab103c1e65f.yaml
  riotfile.py
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast/fixtures/taint_sinks/not_exists.txt
  tests/appsec/test_handlers.py
Labels: ASM, backport 1.16, backport 1.18, backport 1.19, backport 1.20, backport 2.0, backport 2.1

#7389 ci: run framework tests if frameworks.yml modified [backport #7379 to 1.20]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 1.19, backport 1.20, backport 2.0, backport 2.1

#7384 chore(ci): move slotscheck and conftests
  .circleci/config.templ.yml
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#7376 fix(ci): filter user credentials from SSH git repo URLs
  ddtrace/ext/ci.py
  releasenotes/notes/filter-sensititive-ssh-git-repo-url-cc4ca37227b4e602.yaml
  tests/tracer/test_ci.py
Labels: enhancement, backport 1.16, backport 1.17, backport 1.18, backport 1.19, backport 1.20, backport 2.0, backport 2.1

#7368 chore(telemetry/test): move testagent fixture to global conftest
  tests/conftest.py
  tests/runtime/conftest.py
  tests/telemetry/conftest.py
Labels: changelog/no-changelog, ASM

#7395 fix(appsec): transfer-encoding chunked requests are dropped [backport 1.19]
  .riot/requirements/11c167a.txt
  .riot/requirements/13790d2.txt
  .riot/requirements/1483961.txt
  .riot/requirements/15bb169.txt
  .riot/requirements/162a088.txt
  .riot/requirements/194b700.txt
  .riot/requirements/1961d96.txt
  .riot/requirements/1ba9802.txt
  .riot/requirements/1f1bd7d.txt
  .riot/requirements/1ff2b07.txt
  .riot/requirements/2b46598.txt
  .riot/requirements/5bb1431.txt
  .riot/requirements/5ea5e85.txt
  .riot/requirements/5ee9ded.txt
  .riot/requirements/840df3c.txt
  .riot/requirements/8b732cf.txt
  .riot/requirements/c9b99a0.txt
  .riot/requirements/e368746.txt
  .riot/requirements/f00ead8.txt
  ddtrace/appsec/handlers.py
  releasenotes/notes/asm-fix-chunked-requests-1f703ab103c1e65f.yaml
  riotfile.py
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast/fixtures/taint_sinks/not_exists.txt
  tests/appsec/test_handlers.py
Labels: ASM

#7396 fix(appsec): transfer-encoding chunked requests are dropped [backport 1.18]
  .riot/requirements/11c167a.txt
  .riot/requirements/13790d2.txt
  .riot/requirements/1483961.txt
  .riot/requirements/15bb169.txt
  .riot/requirements/162a088.txt
  .riot/requirements/194b700.txt
  .riot/requirements/1961d96.txt
  .riot/requirements/1ba9802.txt
  .riot/requirements/1f1bd7d.txt
  .riot/requirements/1ff2b07.txt
  .riot/requirements/2b46598.txt
  .riot/requirements/5bb1431.txt
  .riot/requirements/5ea5e85.txt
  .riot/requirements/5ee9ded.txt
  .riot/requirements/840df3c.txt
  .riot/requirements/8b732cf.txt
  .riot/requirements/c9b99a0.txt
  .riot/requirements/e368746.txt
  .riot/requirements/f00ead8.txt
  ddtrace/appsec/handlers.py
  releasenotes/notes/asm-fix-chunked-requests-1f703ab103c1e65f.yaml
  riotfile.py
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/test_handlers.py
Labels: ASM

#7387 fix(unittest): fix unittest data not initialized
  ddtrace/contrib/unittest/patch.py
  releasenotes/notes/fix-unittest-data-not-initialized-4c08983165adcfc1.yaml
Labels: CI App, backport 2.1

#7415 test(profiling): collector log tests
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog, Profiling

#7247 chore(asm): add remote config support for API Security sample rate
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_capabilities.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/_utils.py
  ddtrace/settings/config.py
  tests/appsec/test_remoteconfiguration.py
  tests/contrib/django/test_django_appsec_api_security.py
  tests/contrib/flask/test_appsec_api_security.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#7369 fix(ci_visibility): add safety checks and exception handling around _fetch_tests_to_skip
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App, backport 1.20, backport 2.0, backport 2.1

#7410 chore: revert CI server subprocess config
  tests/appsec/appsec_utils.py
Labels: changelog/no-changelog, ASM

#6192 refactor(config): add support for config sources, subscription
  ddtrace/sampler.py
  ddtrace/settings/config.py
  tests/internal/test_settings.py
  tests/telemetry/test_writer.py
  tests/tracer/test_sampler.py
  tests/utils.py
Labels: changelog/no-changelog

#7422 chore(asm): asm configuration as a standalone config file
  .github/CODEOWNERS
  ddtrace/_monkey.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_capabilities.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_utils.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/flask_login/patch.py
  ddtrace/contrib/pylons/middleware.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/subprocess/patch.py
  ddtrace/contrib/trace_utils.py
  ddtrace/internal/debug.py
  ddtrace/internal/telemetry/data.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/asm.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  tests/appsec/appsec/test_asm_request_context.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_appsec_api_security.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/djangorestframework/test_appsec.py
  tests/contrib/flask/test_appsec_api_security.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_telemetry.py
  tests/contrib/flask_login/test_flask_login_appsec.py
  tests/contrib/pylons/test_pylons.py
  tests/contrib/subprocess/test_subprocess.py
  tests/contrib/subprocess/test_subprocess_patch.py
  tests/telemetry/test_data.py
  tests/tracer/test_trace_utils.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#7417 ci: use the latest Austin in profiling workflow scripts
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
  .riot/requirements/59df9d0.txt
  scripts/profiles/django-simple/run.sh
  scripts/profiles/django-simple/setup.sh
  scripts/profiles/encoders/run.sh
  scripts/profiles/encoders/setup.sh
  scripts/profiles/flask-simple/run.sh
  scripts/profiles/flask-simple/setup.sh
Labels: changelog/no-changelog

#7431 ci: delete .github/dependabot.yml
  .github/dependabot.yml
Labels: changelog/no-changelog

#7354 feat(iast): include as iast telemetry metrics tags in the root span of the trace
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/_iast/taint_sinks/weak_hash.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/dbapi_async/__init__.py
  tests/.suitespec.json
  tests/appsec/appsec_utils.py
  tests/appsec/iast/test_taint_tracking.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/app.py
  tests/appsec/integrations/test_remoteconfiguration_e2e.py
  tests/appsec/integrations/test_telemetry.py
Labels: changelog/no-changelog, ASM

#7397 ci: run framework tests on 2.x push
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 2.0, backport 2.1

#7420 fix(ci_visibility): add safety checks and exception handling around ... [backport 1.20]
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App

#7277 Revert "fix(tracing): fix msgpack import error"
  ddtrace/internal/_encoding.pyi
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/writer/writer.py
  releasenotes/notes/fix-msgpack-errors-3fcf9f77a77c9786.yaml
  tests/integration/test_integration.py
  tests/tracer/test_encoders.py
  tests/utils.py
Labels: changelog/no-changelog

#7423 chore(tests): add initial delay to appsec_utils web client
  ddtrace/internal/utils/retry.py
  tests/appsec/appsec_utils.py
  tests/webclient.py
Labels: changelog/no-changelog, ASM, CI
