Repository DataDog/dd-trace-py, pull requests merged in 2023-12, with the labels that each got.

#7663 feat(openai): enable sending llmobs payloads
  ddtrace/contrib/_trace_utils_llm.py
  ddtrace/contrib/langchain/patch.py
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/contrib/openai/patch.py
  ddtrace/internal/llmobs/writer.py
  tests/contrib/openai/conftest.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/internal/llmobs_cassettes/tests.internal.test_llmobs.test_send_chat_completion.yaml
  tests/internal/llmobs_cassettes/tests.internal.test_llmobs.test_send_completion.yaml
  tests/internal/llmobs_cassettes/tests.internal.test_llmobs.test_send_completion_bad_api_key.yaml
  tests/internal/llmobs_cassettes/tests.internal.test_llmobs.test_send_completion_bad_app_key.yaml
  tests/internal/llmobs_cassettes/tests.internal.test_llmobs.test_send_on_exit.yaml
  tests/internal/llmobs_cassettes/tests.internal.test_llmobs.test_send_timed_records.yaml
  tests/internal/test_llmobs.py
Labels: changelog/no-changelog

#7733 fix(openai): avoid attribute errors when parsing raw APIResponse objects
  ddtrace/contrib/openai/_endpoint_hooks.py
  releasenotes/notes/fix-openai-raw-response-c56359c484914fd5.yaml
  tests/contrib/openai/test_openai_v1.py
Labels: backport 2.2, backport 2.3

#7788 fix(iast): iast leak for python 3.11
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/taint_sinks/test_insecure_cookie.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_sql_injection.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/appsec/iast/taint_sinks/test_weak_cipher.py
  tests/appsec/iast/taint_sinks/test_weak_hash.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#7427 fix(tracing_utils): resolves RuntimeError dictionary changed size during iteration
  ddtrace/internal/utils/__init__.py
  releasenotes/notes/fix-runtimeerror-on-get-metas-to-propagate-25f9c44ac4137fb9.yaml
Labels: backport 1.20, backport 2.1

#7782 chore(tracing): add typing for `FilterRequestOnUrl`
  ddtrace/filters.py
Labels: changelog/no-changelog

#7816 docs: add instructions documentation on how to update venv locks to latest
  docs/contributing-testing.rst
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog

#7805 chore(tracer): add agent sample rate regression test
  .circleci/config.templ.yml
  docker-compose.yml
  tests/integration/test_priority_sampling.py
  tests/snapshots/tests.integration.test_priority_sampling.test_agent_sample_rate_keep.json
  tests/snapshots/tests.integration.test_priority_sampling.test_agent_sample_rate_reject.json
  tests/utils.py
Labels: changelog/no-changelog

#7828 ci: test against the latest minor release of Mako [backport 2.1]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#7829 ci: test against the latest minor release of Mako [backport 2.2]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#7787 feat(asm): report only imported dependencies
  ddtrace/internal/module.py
  ddtrace/internal/packages.py
  ddtrace/internal/telemetry/__init__.py
  ddtrace/internal/telemetry/data.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  releasenotes/notes/asm-dependencies-metrics-0f357e2613452be2.yaml
  tests/contrib/celery/test_integration.py
  tests/internal/test_module.py
  tests/telemetry/test_data.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#7830 ci: test against the latest minor release of Mako [backport 2.3]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#7838 chore(ci): fix skipping test if chat completion not available
  tests/contrib/openai/test_openai_v0.py
Labels: changelog/no-changelog, backport 2.2, backport 2.3

#7836 chore(perf): add microbenchmarks for the internal core api
  .gitlab-ci.yml
  .gitlab/benchmarks.yml
  benchmarks/core_api/config.yaml
  benchmarks/core_api/scenario.py
Labels: changelog/no-changelog

#7822 fix(profiling): thread lock segfault with 3.12
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/fix-profiling-thread-lock-d18f104a9f479be3.yaml
Labels: Profiling, backport 2.1, backport 2.2, backport 2.3

#7827 ci: test against the latest minor release of Mako [backport 1.20]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#7820 fix(iast): fix memory leak error [backport #7788 to 1.20]
  ddtrace/appsec/iast/_stacktrace.c
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectExtend.h
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectFormat.h
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectJoin.h
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/iast/_taint_tracking/Aspects/AspectOperatorAdd.h
  ddtrace/appsec/iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/iast/_taint_tracking/Aspects/_aspects_exports.h
  ddtrace/appsec/iast/_taint_tracking/Constants.h
  ddtrace/appsec/iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/TaintedObject.h
  ddtrace/appsec/iast/_taint_tracking/TaintTracking/_taint_tracking.h
  ddtrace/appsec/iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintedOps/TaintedOps.h
  ddtrace/appsec/iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/_taint_tracking/_native.cpp
  ddtrace/appsec/iast/_taint_tracking/aspects.py
  tests/appsec/iast/_ast/test_proper_patching.py
  tests/appsec/iast/aspects/test_common_aspects.py
  tests/appsec/iast/aspects/test_common_aspects_generator.py
  tests/appsec/iast/aspects/test_empty_arg_aspects.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_modulo_aspect_fixtures.py
  tests/appsec/iast/taint_sinks/test_command_injection_redacted.py
Labels: changelog/no-changelog, ASM

#7839 ci: mark logger test as flaky
  tests/tracer/test_logger.py
Labels: changelog/no-changelog, backport 2.3

#7848 fix(openai): change llmobs request duration from milliseconds to seconds
  ddtrace/contrib/openai/patch.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/internal/test_llmobs.py
Labels: changelog/no-changelog

#7853 fix(django): fix decode query strings in asgi middleware
  ddtrace/contrib/asgi/middleware.py
Labels: changelog/no-changelog

#7843 docs: add a clarification to the documentation of DD_TRACE_METHODS [APMS-10881]
  docs/configuration.rst
Labels: changelog/no-changelog

#7819 fix(asm): fix asgi core dispatch call
  ddtrace/contrib/asgi/middleware.py
  tests/contrib/fastapi/test_fastapi_appsec.py
Labels: bug, changelog/no-changelog, ASM

#7780 ci: use 3.12.0 release in testrunner
  docker/.python-version
  docker/Dockerfile
Labels: changelog/no-changelog, backport 2.1, backport 2.2, backport 2.3

#7834 fix(tracer): apply agent sampling tags
  ddtrace/sampler.py
  releasenotes/notes/agent-sample-rate-39e5ad8039c675b9.yaml
  tests/integration/test_priority_sampling.py
  tests/snapshots/tests.integration.test_priority_sampling.test_agent_sample_rate_keep.json
  tests/snapshots/tests.integration.test_priority_sampling.test_agent_sample_rate_reject.json
Labels: backport 1.20, backport 2.1, backport 2.2, backport 2.3

#7860 docs: add docs section on log level customization [APMS-10916]
  docs/advanced_usage.rst
Labels: changelog/no-changelog

#7750 chore(asm): add non lazy tainting for dicts and lists by default in iast
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_utils.py
  ddtrace/settings/asm.py
  tests/appsec/iast/test_json_tainting.py
  tests/appsec/iast/test_taint_utils.py
Labels: changelog/no-changelog, ASM

#7532 chore(ci_visibility): add telemetry metrics for git operations
  ddtrace/contrib/pytest/plugin.py
  ddtrace/ext/git.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/telemetry/__init__.py
  ddtrace/internal/ci_visibility/telemetry/constants.py
  ddtrace/internal/ci_visibility/telemetry/git.py
  ddtrace/internal/ci_visibility/telemetry/utils.py
  docs/spelling_wordlist.txt
  tests/ci_visibility/test_ci_visibility.py
  tests/tracer/test_ci.py
Labels: changelog/no-changelog

#7832 ci: use lts version of mariadb container
  docker-compose.yml
Labels: changelog/no-changelog

#7835 chore: don't mark issues as stale that are about to be closed
  .github/workflows/stale.yml
Labels: changelog/no-changelog

#7842 chore(ci): fix skipping test if chat completion not available [backport #7838 to 2.3]
  tests/contrib/openai/test_openai_v0.py
Labels: changelog/no-changelog

#7837 docs: make the example riot command work on a fresh system
  docs/contributing-testing.rst
Labels: changelog/no-changelog

#7699 refactor(writer): handle agent responses in the tracer
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/__init__.py
  ddtrace/internal/writer/writer.py
  ddtrace/tracer.py
Labels: changelog/no-changelog

#7771 ci: build testrunner for maintained branches
  .github/workflows/testrunner.yml
Labels: changelog/no-changelog

#7876 ci(perf): enable more benchmarks to run on every PR
  .gitlab/benchmarks.yml
  benchmarks/base/requirements.txt
  benchmarks/flask_simple/requirements_scenario.txt
  benchmarks/flask_sqli/requirements_scenario.txt
  benchmarks/sampling_rule_matches/scenario.py
Labels: changelog/no-changelog

#7877 fix(openai): use request model instead of response model for llmobs payloads
  ddtrace/contrib/openai/patch.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog

#7881 docs: fix typo in release note
  releasenotes/notes/trace-api-v05-encoding-reset-string-table-17ee19c026b22af9.yaml
Labels: changelog/no-changelog

#7869 chore(internal): refactor core api event hub
  benchmarks/core_api/config.yaml
  benchmarks/core_api/scenario.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask/wrappers.py
  ddtrace/contrib/kafka/patch.py
  ddtrace/contrib/starlette/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/internal/core/__init__.py
  ddtrace/internal/core/event_hub.py
  tests/contrib/fastapi/test_fastapi_appsec.py
  tests/internal/test_context_events_api.py
Labels: changelog/no-changelog

#7588 refactor: make undecorated a general utility
  ddtrace/debugging/_function/discovery.py
  ddtrace/internal/utils/inspection.py
  tests/debugging/function/test_discovery.py
  tests/debugging/function/test_store.py
  tests/internal/test_utils_inspection.py
Labels: changelog/no-changelog

#6072 feat(propagation): add baggage support to http propagation
  ddtrace/context.py
  ddtrace/opentracer/propagation/http.py
  ddtrace/propagation/http.py
  ddtrace/settings/config.py
  ddtrace/span.py
  docs/configuration.rst
  releasenotes/notes/baggage-support-with-http-propagation-e00d106eefff67f1.yaml
  tests/tracer/test_propagation.py
  tests/tracer/test_span.py
  tests/utils.py
Labels: feature-request, Tracing

#7886 test(profiling): import and patching order
  tests/profiling/simple_program_gevent.py
Labels: changelog/no-changelog, Profiling

#7884 fix(iast): format aspect propagation error
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  releasenotes/notes/iast-fix-propagation-error-b59b1b0db93c0f23.yaml
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_format_map_aspect_fixtures.py
Labels: ASM, backport 1.20

#7863 chore(tracer): core interface improvement
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask/wrappers.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/internal/core/__init__.py
  ddtrace/internal/core/event_hub.py
  ddtrace/tracing/trace_handlers.py
  tests/contrib/fastapi/test_fastapi_appsec.py
  tests/internal/test_context_events_api.py
Labels: enhancement, changelog/no-changelog

#7873 fix(asm): improve cookies management for fastapi by using starlette parser
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/starlette/patch.py
  tests/contrib/fastapi/test_fastapi_appsec.py
Labels: changelog/no-changelog, ASM

#7856 chore(iast): packages tests
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast_packages/__init__.py
  tests/appsec/iast_packages/packages/__init__.py
  tests/appsec/iast_packages/packages/pkg_requests.py
  tests/appsec/iast_packages/packages/template.py.tpl
  tests/appsec/iast_packages/test_packages.py
  tests/appsec/integrations/test_handlers.py
  tests/appsec/integrations/test_psycopg2.py
Labels: changelog/no-changelog, ASM

#7890 fix(iast): fix memory leak error [backport #7788 to 2.3]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_stacktrace.c
  ddtrace/appsec/_iast/_taint_dict.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/_aspects_exports.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/_utils.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/sql_injection.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/_iast/taint_sinks/weak_hash.py
Labels: changelog/no-changelog, ASM

#7891 chore(asm): update appsec event rule static file to 1.10
  ddtrace/appsec/rules.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#7895 ci: bump absl dependency
  ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt
Labels: changelog/no-changelog, backport 1.20, backport 2.1, backport 2.2, backport 2.3

#7899 ci: bump absl dependency [backport 1.20]
  ddtrace/appsec/iast/_taint_tracking/CMakeLists.txt
Labels: changelog/no-changelog, ASM

#7892 chore(asm): update libddwaf to 1.15.1
  setup.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#7893 fix(iast): insecure cookies error
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/iast-fix-cookies-error-2084dea1413104bd.yaml
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/tracer/test_trace_utils.py
Labels: ASM, backport 1.20, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#7901 test(asm): improve fastapi srb query test
  tests/contrib/fastapi/test_fastapi_appsec.py
Labels: changelog/no-changelog, ASM, CI

#7902 fix(iast): insecure cookies error [backport #7893 to 2.3]
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/iast-fix-cookies-error-2084dea1413104bd.yaml
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/tracer/test_trace_utils.py
Labels: ASM

#7904 fix(iast): insecure cookies error [backport #7893 to 2.2]
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/iast-fix-cookies-error-2084dea1413104bd.yaml
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog, ASM

#7518 feat(asm): add RC support for API sec
  ddtrace/appsec/_api_security/processors.json
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_remoteconfiguration.py
  tests/contrib/django/test_django_appsec_api_security.py
  tests/contrib/flask/test_appsec_api_security.py
Labels: changelog/no-changelog, ASM

#7885 refactor: make ddtrace-run runnable as module
  ddtrace/commands/ddtrace_run.py
Labels: changelog/no-changelog

#7908 fix: make Psycopg3TracedAsyncCursor implementation conform to its type hints
  ddtrace/contrib/psycopg/async_cursor.py
  releasenotes/notes/psycopg3-aexit-808941eef6191d86.yaml
Labels: backport 1.20, backport 2.1, backport 2.2, backport 2.3

#7906 fix(iast): insecure cookies error [backport #7893 to 1.20]
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/iast-fix-cookies-error-2084dea1413104bd.yaml
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/tracer/test_trace_utils.py
Labels: ASM

#7923 fix(asm): remove import and dependency to avoid circular import
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_utils.py
  releasenotes/notes/less_imports_for_iast_tainting-d38a2ad26ad98f40.yaml
Labels: bug, ASM, backport 2.4

#7927 fix(iast): report cookie name
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  releasenotes/notes/iast-fix-cookies-name-report-d5c3381d8c951bab.yaml
  tests/appsec/iast/taint_sinks/test_insecure_cookie.py
Labels: ASM, backport 1.20, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#7930 fix(iast): report cookie name [backport 1.20]
  ddtrace/appsec/iast/taint_sinks/insecure_cookie.py
  releasenotes/notes/iast-fix-cookies-name-report-d5c3381d8c951bab.yaml
  riotfile.py
  tests/appsec/iast/taint_sinks/test_insecure_cookie.py
Labels: ASM

#7921 chore: dont import telemetry writer from module.py
  ddtrace/internal/module.py
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry_metrics.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#7751 refactor(debugging): simplify super()
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_exception/auto_instrument.py
  ddtrace/debugging/_expressions.py
  ddtrace/debugging/_function/discovery.py
  ddtrace/debugging/_probe/registry.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_uploader.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#7936 chore: use a ModuleWatchdog for the Telemetry imports
  ddtrace/internal/module.py
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#7911 chore(iast): packages tests
  .circleci/config.templ.yml
  .riot/requirements/181d5c9.txt
  .riot/requirements/1b13449.txt
  .riot/requirements/1e69c0e.txt
  .riot/requirements/85d8125.txt
  .riot/requirements/ab1be63.txt
  riotfile.py
  tests/.suitespec.json
  tests/appsec/app.py
  tests/appsec/iast_packages/packages/pkg_idna.py
  tests/appsec/iast_packages/packages/pkg_requests.py
  tests/appsec/iast_packages/packages/utils.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#7932 chore: updates default branch and fixes syntax errors
  scripts/release.py
Labels: changelog/no-changelog

#7933 fix(tracer): handle deleted remote configurations
  ddtrace/settings/config.py
  tests/internal/test_settings.py
Labels: changelog/no-changelog, backport 2.4

#7925 chore(iast): add missing modules to iast deny list
  ddtrace/appsec/_python_info/stdlib/module_names_py310.py
  ddtrace/appsec/_python_info/stdlib/module_names_py311.py
  ddtrace/appsec/_python_info/stdlib/module_names_py36.py
  ddtrace/appsec/_python_info/stdlib/module_names_py37.py
  ddtrace/appsec/_python_info/stdlib/module_names_py38.py
  ddtrace/appsec/_python_info/stdlib/module_names_py39.py
Labels: changelog/no-changelog, ASM

#7943 fix(asm): remove import and dependency to avoid circular import [backport 2.4]
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_utils.py
  releasenotes/notes/less_imports_for_iast_tainting-d38a2ad26ad98f40.yaml
Labels: bug, ASM

#7935 chore: update to envier 0.5.0
  .riot/requirements/103e4a0.txt
  .riot/requirements/1492115.txt
  .riot/requirements/18f2aec.txt
  .riot/requirements/1dfb2b8.txt
  .riot/requirements/1eb0d77.txt
  .riot/requirements/243af71.txt
  hatch.toml
Labels: changelog/no-changelog

#7937 chore(internal): only import Span when typechecking to avoid circular imports
  ddtrace/internal/core/__init__.py
Labels: changelog/no-changelog

#7894 feat(ci_visibility): optionally wait for git metadata upload to complete
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/telemetry/git.py
  ddtrace/vendor/dogstatsd/__init__.py
  releasenotes/notes/ci_visibility-feat-optionally_wait_for_git_metadata_upload-e418fc2f94e846ba.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: CI App

#7934 refactor(debugging): implement isUndefined in DSL
  ddtrace/debugging/_expressions.py
  tests/debugging/test_expressions.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#7833 feat(civis): add code coverage v0 support for pytest and unittest
  .circleci/config.templ.yml
  ddtrace/_monkey.py
  ddtrace/contrib/coverage/__init__.py
  ddtrace/contrib/coverage/constants.py
  ddtrace/contrib/coverage/data.py
  ddtrace/contrib/coverage/patch.py
  ddtrace/contrib/coverage/utils.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/contrib/unittest/patch.py
  ddtrace/ext/test.py
  ddtrace/internal/ci_visibility/utils.py
  releasenotes/notes/add-code-coverage-tag-ef5c183d3f29d5c3.yaml
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest/test_pytest_snapshot.py
  tests/contrib/unittest/test_unittest_snapshot.py
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot.test_pytest_will_include_lines_pct.json
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot.test_pytest_wont_include_lines_pct_if_report_empty.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_lines_pct.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_not_include_lines_pct_if_report_empty.json
Labels: enhancement, CI App

#7888 ci: update hatch to v1.8.0
  .circleci/config.templ.yml
  .readthedocs.yml
  docker/Dockerfile
  docs/contributing-testing.rst
  hatch.toml
  scripts/ddtest
  scripts/gen_circleci_config.py
  tests/.suitespec.json
  tests/suitespec.py
Labels: changelog/no-changelog

#7844 chore(tracing): add first trace telemetry
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  docker-compose.yml
  tests/telemetry/test_writer.py
  tests/tracer/test_tracer.py
  tests/utils.py
Labels: changelog/no-changelog

#7944 ci: set pytest-memray fork
  .riot/requirements/139d04f.txt
  .riot/requirements/1b5d605.txt
  .riot/requirements/1bfac7c.txt
  .riot/requirements/1d0a022.txt
  .riot/requirements/1d0c392.txt
  .riot/requirements/ce19caf.txt
  riotfile.py
Labels: changelog/no-changelog, CI, backport 2.2, backport 2.3, backport 2.4

#7953 chore(iast): packages tests
  tests/appsec/app.py
  tests/appsec/iast_packages/packages/pkg_chartset_normalizer.py
  tests/appsec/iast_packages/packages/pkg_google_api_core.py
  tests/appsec/iast_packages/packages/pkg_idna.py
  tests/appsec/iast_packages/packages/pkg_numpy.py
  tests/appsec/iast_packages/packages/pkg_python_dateutil.py
  tests/appsec/iast_packages/packages/pkg_pyyaml.py
  tests/appsec/iast_packages/packages/pkg_requests.py
  tests/appsec/iast_packages/packages/pkg_urllib3.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#7954 feat(asm): api security support
  ddtrace/appsec/_asm_request_context.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/starlette/patch.py
  releasenotes/notes/api_security_for_fastapi-4fc37050ed19ed6d.yaml
  tests/contrib/fastapi/test_fastapi_appsec_api_security.py
Labels: ASM

#7931 chore: add ancestor runtime ID
  ddtrace/internal/runtime/__init__.py
  tests/tracer/runtime/test_runtime_id.py
Labels: changelog/no-changelog

#7961 ci: fix macos builds
  .github/workflows/build_python_3.yml
  pyproject.toml
  setup.py
Labels: changelog/no-changelog, CI, backport 1.20, backport 2.2, backport 2.3, backport 2.4

#7971 chore(asm): upgrade test to avoid flakyness
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/utils.py
Labels: changelog/no-changelog, ASM, CI

#7976 Revert "chore(tracing): add first trace telemetry (#7844)"
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  docker-compose.yml
  tests/telemetry/test_writer.py
  tests/tracer/test_tracer.py
  tests/utils.py
Labels: changelog/no-changelog

#7903 chore(ci): migrate dd-trace-py benchmarking pipeline to benchmarking-platform repo
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#7987 chore(iast): fix flaky tests
  tests/appsec/appsec/test_processor.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
  tests/appsec/integrations/test_remoteconfiguration_e2e.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
Labels: changelog/no-changelog, ASM

#7990 ci: configure parametric test to get the python tracer in same way as system-tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#7993 chore(telemetry): track ddtrace installations
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog
