Repository DataDog/dd-trace-py, pull requests merged in 2023-06, with the labels that each got.

#5990 chore(test): molten test fix
  .riot/requirements/132a135.txt
  .riot/requirements/1381045.txt
  .riot/requirements/16222a9.txt
  .riot/requirements/1959556.txt
  .riot/requirements/19e1fdd.txt
  .riot/requirements/1ad4627.txt
  .riot/requirements/1e19e73.txt
  .riot/requirements/27f29b8.txt
  .riot/requirements/2ddc7a2.txt
  .riot/requirements/7ff9aca.txt
  .riot/requirements/8b393bf.txt
  .riot/requirements/e55b906.txt
  riotfile.py
Labels: changelog/no-changelog, Testing

#5987 chore(cpp): update clang format
  .gitignore
  ddtrace/appsec/iast/_taint_tracking/TaintedObject/TaintedObject.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintedObject/TaintedObject.h
  ddtrace/appsec/iast/_taint_tracking/_native.cpp
  ddtrace/internal/_utils.h
  ddtrace/internal/buff_converter.h
  ddtrace/internal/pack.h
  ddtrace/internal/pack_template.h
  ddtrace/internal/sysdep.h
  ddtrace/profiling/collector/_memalloc_heap.h
  ddtrace/profiling/collector/_memalloc_reentrant.h
  ddtrace/profiling/collector/_memalloc_tb.h
  ddtrace/profiling/collector/_utils.h
  hooks/scripts/run-clang-format.sh
  mypy.ini
  scripts/cformat.sh
  scripts/cppcheck.sh
  setup.cfg
Labels: changelog/no-changelog, ASM

#5464 fix(rcm): publisher subscriber system
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_signal/collector.py
  ddtrace/debugging/_uploader.py
  ddtrace/internal/remoteconfig/__init__.py
  ddtrace/internal/remoteconfig/_connectors.py
  ddtrace/internal/remoteconfig/_publishers.py
  ddtrace/internal/remoteconfig/_pubsub.py
  ddtrace/internal/remoteconfig/_subscribers.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
  ddtrace/internal/writer/writer.py
  tests/appsec/test_remoteconfiguration.py
  tests/appsec/test_remoteconfiguration_e2e.py
  tests/conftest.py
  tests/contrib/gunicorn/test_gunicorn.py
  tests/debugging/exploration/debugger.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/test_debugger.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
  tests/internal/remoteconfig/test_remoteconfig_publisher.py
  tests/profiling/_test_multiprocessing.py
Labels: changelog/no-changelog, ASM

#5808 chore(service_name): add service schema grpc
  ddtrace/contrib/grpc/patch.py
  tests/contrib/grpc/test_grpc.py
Labels: changelog/no-changelog

#5991 docs(futures): add more documentation for the futures integration
  ddtrace/contrib/futures/__init__.py
  docs/advanced_usage.rst
  docs/conf.py
Labels: changelog/no-changelog

#5996 chore(test): molten test fix [backport #5990 to 1.14]
  .riot/requirements/132a135.txt
  .riot/requirements/1381045.txt
  .riot/requirements/16222a9.txt
  .riot/requirements/1959556.txt
  .riot/requirements/19e1fdd.txt
  .riot/requirements/1ad4627.txt
  .riot/requirements/1e19e73.txt
  .riot/requirements/27f29b8.txt
  .riot/requirements/2ddc7a2.txt
  .riot/requirements/7ff9aca.txt
  .riot/requirements/8b393bf.txt
  .riot/requirements/e55b906.txt
  riotfile.py
Labels: changelog/no-changelog, Testing

#5979 chore(ci-visibility): fix flaky test
  tests/ci_visibility/test_encoder.py
Labels: changelog/no-changelog, CI App

#5994 chore(test): molten test fix [backport #5990 to 1.12]
  .riot/requirements/132a135.txt
  .riot/requirements/1381045.txt
  .riot/requirements/16222a9.txt
  .riot/requirements/1959556.txt
  .riot/requirements/19e1fdd.txt
  .riot/requirements/1ad4627.txt
  .riot/requirements/1e19e73.txt
  .riot/requirements/27f29b8.txt
  .riot/requirements/2ddc7a2.txt
  .riot/requirements/7ff9aca.txt
  .riot/requirements/8b393bf.txt
  .riot/requirements/e55b906.txt
  riotfile.py
Labels: changelog/no-changelog, Testing

#5945 docs(tracing): adds DD_TRACE_PARTIAL_FLUSH_MIN_SPANS to configurations
  docs/configuration.rst
Labels: changelog/no-changelog

#6021 chore(test): molten test fix [backport #5990 to 1.9]
  .riot/requirements/132a135.txt
  .riot/requirements/1381045.txt
  .riot/requirements/16222a9.txt
  .riot/requirements/1959556.txt
  .riot/requirements/19e1fdd.txt
  .riot/requirements/1ad4627.txt
  .riot/requirements/1e19e73.txt
  .riot/requirements/27f29b8.txt
  .riot/requirements/2ddc7a2.txt
  .riot/requirements/7ff9aca.txt
  .riot/requirements/8b393bf.txt
  .riot/requirements/e55b906.txt
  riotfile.py
Labels: changelog/no-changelog, Testing

#6020 chore(test): molten test fix [backport #5990 to 1.10]
  .riot/requirements/132a135.txt
  .riot/requirements/1381045.txt
  .riot/requirements/16222a9.txt
  .riot/requirements/1959556.txt
  .riot/requirements/19e1fdd.txt
  .riot/requirements/1ad4627.txt
  .riot/requirements/1e19e73.txt
  .riot/requirements/27f29b8.txt
  .riot/requirements/2ddc7a2.txt
  .riot/requirements/7ff9aca.txt
  .riot/requirements/8b393bf.txt
  .riot/requirements/e55b906.txt
  riotfile.py
Labels: changelog/no-changelog, Testing

#6019 chore(test): molten test fix [backport #5990 to 1.11]
  .riot/requirements/132a135.txt
  .riot/requirements/1381045.txt
  .riot/requirements/16222a9.txt
  .riot/requirements/1959556.txt
  .riot/requirements/19e1fdd.txt
  .riot/requirements/1ad4627.txt
  .riot/requirements/1e19e73.txt
  .riot/requirements/27f29b8.txt
  .riot/requirements/2ddc7a2.txt
  .riot/requirements/7ff9aca.txt
  .riot/requirements/8b393bf.txt
  .riot/requirements/e55b906.txt
  riotfile.py
Labels: changelog/no-changelog, Testing

#6013 chore(ci): add backporting action to ease effort of backporting PRs
  .github/workflows/backport.yml
Labels: changelog/no-changelog

#5997 chore(asm): remove some flakyness in appsec tests
  tests/appsec/test_remoteconfiguration_e2e.py
Labels: changelog/no-changelog, ASM

#6005 chore(asm): uri raw must not contains scheme and netloc
  ddtrace/appsec/_asm_request_context.py
  tests/appsec/rules-suspicious-requests.json
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#6003 chore(ci-visibility): fix evp proxy endpoint
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App

#5940 chore(setup): add support for downloading libdatadog FFI artifacts during build
  setup.py
Labels: changelog/no-changelog

#6027 chore: add login event mode argument and tag
  ddtrace/appsec/_constants.py
  ddtrace/appsec/trace_utils.py
  tests/appsec/test_appsec_trace_utils.py
Labels: changelog/no-changelog

#5454 feat(debugger): span decoration probes
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_signal/snapshot.py
  ddtrace/debugging/_signal/tracing.py
  releasenotes/notes/feat-span-decoration-c04a7aa0c98d52f6.yaml
  tests/debugging/mocking.py
  tests/debugging/test_debugger_span_decoration.py
  tests/debugging/utils.py
  tests/submod/traced_stuff.py
Labels: Dynamic Instrumentation

#6026 ci(debugging): delete triggered probes in Django runs
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_profiler.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6028 fix(openai): pin scikit-learn for openai==0.26 test suite
  .riot/requirements/1235562.txt
  .riot/requirements/13647c8.txt
  .riot/requirements/1373e34.txt
  .riot/requirements/1693d4a.txt
  .riot/requirements/1778cfe.txt
  .riot/requirements/190b91b.txt
  .riot/requirements/1918f2f.txt
  .riot/requirements/1bbd49f.txt
  .riot/requirements/1d28d3c.txt
  .riot/requirements/1d8a7f0.txt
  .riot/requirements/2e374e1.txt
  .riot/requirements/597a5ad.txt
  .riot/requirements/5af1339.txt
  .riot/requirements/64b1a96.txt
  .riot/requirements/a05fce9.txt
  .riot/requirements/ae9a00b.txt
  .riot/requirements/b05d8e6.txt
  .riot/requirements/d040b06.txt
  .riot/requirements/ddce34f.txt
  .riot/requirements/ec4a132.txt
  riotfile.py
Labels: changelog/no-changelog

#6034 chore(test): rename system-tests scenario
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#6024 chore(debugging): relax safe dict retrieval
  ddtrace/debugging/safety.py
  tests/debugging/test_safety.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5973 ci(build-deploy): build python deb/rpm for autoinjection
  .gitlab-ci.yml
  .gitlab/build-deb-rpm.sh
Labels: changelog/no-changelog

#6011 test(integrations): limit number of logs printed when assertions fail
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#5999 chore(ci-visibility): improve segments algorithm
  ddtrace/internal/ci_visibility/coverage.py
  tests/ci_visibility/test_coverage.py
Labels: changelog/no-changelog, CI App

#6050 ci(debugging): delete triggered probes in Django runs [backport #6026 to 1.10]
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_profiler.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6049 ci(debugging): delete triggered probes in Django runs [backport #6026 to 1.11]
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_profiler.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6051 ci(debugging): delete triggered probes in Django runs [backport #6026 to 1.9]
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_profiler.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6035 chore(rcm/di): disable multiple target files
  ddtrace/internal/remoteconfig/_connectors.py
  tests/debugging/probe/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig_connector.py
Labels: changelog/no-changelog, ASM

#6006 chore(tracing): adds `out.host` tag for celery
  ddtrace/contrib/celery/signals.py
  releasenotes/notes/celery-precursor-peer.service-d3b1bc05f1ca59ab.yaml
  tests/contrib/celery/test_integration.py
Labels: changelog/no-changelog, backport 1.14, backport 1.13

#6038 fix(pymemcache): allow service name overriding on hashclients
  ddtrace/contrib/pymemcache/__init__.py
  tests/contrib/pymemcache/test_client.py
Labels: changelog/no-changelog

#6059 chore(docs): ensures python3.11 is set as default version
  README.md
Labels: changelog/no-changelog

#6069 chore(asm): update appsec rules to 1.7.1
  ddtrace/appsec/rules.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#6045 chore(service.naming): add flag for v0
  ddtrace/internal/schema/__init__.py
  tests/internal/service_name/__init__.py
  tests/internal/service_name/test_imports.py
Labels: changelog/no-changelog

#6060 chore(docs): update and fix formatting gunicorn docs
  ddtrace/contrib/gunicorn/__init__.py
Labels: changelog/no-changelog, backport 1.15

#6076 chore(tracing): adds `out.host` tag for consul
  ddtrace/contrib/consul/patch.py
  tests/contrib/consul/test.py
Labels: changelog/no-changelog

#6022 chore: updates PR checklist to include backport policy
  .github/PULL_REQUEST_TEMPLATE.md
  docs/contributing.rst
Labels: changelog/no-changelog

#6082 chore(service.naming): peerServiceProcessor to use set_tag_str
  ddtrace/internal/processor/trace.py
Labels: changelog/no-changelog

#6086 chore(asm): small improvement to waf interface
  ddtrace/appsec/ddwaf/__init__.py
  tests/appsec/rules-bad_version.json
  tests/appsec/test_processor.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM

#6064 ci(celery): test compatibility with Django 4.0 and error message
  tests/contrib/django_celery/app/proj/urls.py
  tests/contrib/django_celery/test_django_celery.py
Labels: changelog/no-changelog

#6085 test: fix parametrisation support in subprocess marker
  tests/conftest.py
Labels: changelog/no-changelog, backport 1.14, backport 1.13, backport 1.12, backport 1.11, backport 1.15, backport 1.10, backport 1.9

#6070 fix(rcm): remote config payloads error
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_uploader.py
  ddtrace/internal/remoteconfig/_subscribers.py
  ddtrace/internal/remoteconfig/client.py
  releasenotes/notes/rcm-fix-payload-errors-808e827b978c829a.yaml
  tests/appsec/test_remoteconfiguration.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_subscriber.py
Labels: ASM, backport 1.15

#6101 ci(telemetry): use a helper to join agent url to the telemetry endpoint
  ddtrace/internal/telemetry/writer.py
Labels: changelog/no-changelog

#6103 docs(fastapi): add note about fastapi middleware
  ddtrace/contrib/fastapi/__init__.py
Labels: changelog/no-changelog

#6029 chore(debugging): allow all valid Python identifiers in EL
  ddtrace/debugging/_expressions.py
  tests/debugging/test_expressions.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6102 fix(botocore): allow non-url SQS "queue urls"
  ddtrace/ext/aws.py
  releasenotes/notes/botocore-sqs-queue-nonurl-b11745018c92ea1b.yaml
  tests/contrib/botocore/test.py
Labels: backport 1.14, backport 1.15

#6099 chore(asm): refactor iast Django tests
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#6114 chore: make FI team members co-owners of folders containing integrations and tests
  .github/CODEOWNERS
Labels: changelog/no-changelog

#6084 fix(pymemcache): allow hashclient integration to override pin when use_pooling=True
  ddtrace/contrib/pymemcache/client.py
  ddtrace/contrib/pymemcache/patch.py
  releasenotes/notes/pymemcache-hashclient-usepooling-83f63f7014367b48.yaml
  tests/contrib/pymemcache/test_client.py
Labels: backport 1.14, backport 1.13, backport 1.15

#5728 chore(otel): track the adoption of the datadog opentelemetry api
  benchmarks/bm/utils.py
  benchmarks/otel_span/config.yaml
  benchmarks/otel_span/scenario.py
  benchmarks/span/config.yaml
  benchmarks/span/scenario.py
  benchmarks/tracer/scenario.py
  ddtrace/internal/constants.py
  ddtrace/internal/processor/trace.py
  ddtrace/opentelemetry/_trace.py
  ddtrace/opentracer/span.py
  ddtrace/opentracer/tracer.py
  ddtrace/span.py
  ddtrace/tracer.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog

#6113 fix(graphql): mark graphql.execute spans as measured
  ddtrace/contrib/graphql/patch.py
  releasenotes/notes/graphql-measured-d512e43de27d7ae3.yaml
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_execute.json
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_execute_with_resolvers.json
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_failing_execute.json
  tests/snapshots/tests.contrib.graphene.test_graphene.test_schema_failing_execute_v2.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_error.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_execute_with_middleware.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_v2_with_document.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_with_traced_resolver.json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_span_schematization[None-None].json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_span_schematization[None-v0].json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_span_schematization[None-v1].json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_span_schematization[my-service-None].json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_span_schematization[my-service-v0].json
  tests/snapshots/tests.contrib.graphql.test_graphql.test_span_schematization[my-service-v1].json
Labels: backport 1.14, backport 1.13, backport 1.12, backport 1.15

#5830 chore(release_script): improve documentation around github token
  scripts/release.py
Labels: changelog/no-changelog

#6119 ci(integrations): makes test_single_trace_too_large less flaky
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#6133 fix(tracing): disallow the propagation of negative trace IDs
  ddtrace/propagation/http.py
  releasenotes/notes/negative-trace-id-813bd867c1c8553e.yaml
  tests/tracer/test_propagation.py
Labels: backport 1.14, backport 1.13, backport 1.15

#6037 fix: avoid importing asyncio
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/internal/compat.py
  ddtrace/profiling/_asyncio.py
  ddtrace/vendor/dogstatsd/compat.py
  releasenotes/notes/fix-gevent-asyncio-13ed3a9411ed8088.yaml
  tests/commands/test_runner.py
Labels: backport 1.14, backport 1.13, backport 1.15

#6129 chore(ci-visibility): improve intake_cov_url logic
  ddtrace/internal/ci_visibility/writer.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App

#6130 chore(ci-visibility): git repo url: use env vars over git output
  ddtrace/internal/ci_visibility/git_client.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App

#6115 fix: re-add py.typed package data, which had been erroneously removed
  releasenotes/notes/pytyped-1a3fed96165afef1.yaml
  setup.py
Labels: backport 1.15

#6128 chore(peer.service): report hostname for elasticsearch
  ddtrace/contrib/aiohttp/patch.py
  ddtrace/contrib/elasticsearch/patch.py
  ddtrace/contrib/trace_utils.py
  tests/contrib/aiohttp/test_aiohttp_client.py
  tests/contrib/elasticsearch/test_elasticsearch.py
  tests/snapshots/tests.contrib.elasticsearch.test_elasticsearch_multi.test_elasticsearch.json
  tests/snapshots/tests.contrib.elasticsearch.test_elasticsearch_multi.test_elasticsearch6.json
  tests/snapshots/tests.contrib.elasticsearch.test_elasticsearch_multi.test_elasticsearch7.json
Labels: changelog/no-changelog

#6104 chore(peer.service): add peer.service remap logic
  ddtrace/internal/processor/trace.py
  ddtrace/settings/peer_service.py
  ddtrace/tracer.py
  tests/internal/peer_service/test_processor.py
Labels: changelog/no-changelog

#6117 test(grpc_aio): modify skips for version of 3.11 that fixes crash
  tests/contrib/grpc_aio/test_grpc_aio.py
Labels: changelog/no-changelog

#6052 ci(release): remove tar and upload of files to GitHub releases
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#6116 chore: update release note requirement in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#6145 chore(telemetry): update configurations to send booleans instead of strings
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#6150 chore: update codeowners for internal/ci_visibility
  .github/CODEOWNERS
Labels: changelog/no-changelog, CI App

#6151 chore(debugging): fix dynamic span tags to be _dd.di
  ddtrace/debugging/_signal/tracing.py
  tests/debugging/test_debugger_span_decoration.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#6154 ci(asm): adjust test assertions to match CI behavior
  ddtrace/appsec/ddwaf/__init__.py
  tests/contrib/pylons/test_pylons.py
  tests/profiling/exporter/test_packages.py
  tests/profiling/exporter/test_pprof.py
Labels: changelog/no-changelog, ASM, backport 1.14, backport 1.13, backport 1.15

#6147 ci(pytest): ensure span tags are set in a consistent format
  ddtrace/contrib/pytest/plugin.py
Labels: changelog/no-changelog

#6144 chore(telemetry): simplify otel configurations and add otel configs to app_started
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/opentelemetry/__init__.py
  ddtrace/settings/config.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#6167 fix(ci): use container to run Python 2.7 in pylons framework test
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 1.14, backport 1.13, backport 1.15

#5967 chore(profiling): add libdatadog and wrapper library
  .gitignore
  ddtrace/internal/datadog/__init__.py
  ddtrace/internal/datadog/profiling/ddup.pyi
  ddtrace/internal/datadog/profiling/ddup.pyx
  ddtrace/internal/datadog/profiling/include/exporter.hpp
  ddtrace/internal/datadog/profiling/include/interface.hpp
  ddtrace/internal/datadog/profiling/src/exporter.cpp
  ddtrace/internal/datadog/profiling/src/interface.cpp
  pyproject.toml
  setup.py
Labels: changelog/no-changelog

#6174 fix(ci): use container to run Python 2.7 in pylons framework test [backport #6167 to 1.13]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#6175 fix(ci): use container to run Python 2.7 in pylons framework test [backport #6167 to 1.14]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#6176 fix(ci): use container to run Python 2.7 in pylons framework test [backport #6167 to 1.15]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#6182 chore(asm): small import fix in api security
  ddtrace/appsec/utils.py
Labels: changelog/no-changelog, ASM

#6183 ci(integration): increase timeout to make integration_agent tests less flaky
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#6155 chore(telemetry): fix os values set in host fields
  ddtrace/internal/telemetry/data.py
  tests/telemetry/test_data.py
Labels: changelog/no-changelog

#6179 refactor(sampler): various improvements
  ddtrace/sampler.py
Labels: changelog/no-changelog

#6186 ci: update pyenv in testrunner
  docker/Dockerfile
Labels: changelog/no-changelog, backport 1.14, backport 1.15

#6146 chore(ci-visibility): improve coverage performance
  ddtrace/internal/ci_visibility/coverage.py
  tests/ci_visibility/test_coverage.py
Labels: changelog/no-changelog, CI App

#6190 refactor: move V2 logwriter into internal module
  ddtrace/contrib/openai/patch.py
  ddtrace/internal/log_writer.py
  tests/contrib/openai/test_logger.py
Labels: changelog/no-changelog

#6187 ci: bump parallelism of long running tests
  .circleci/config.yml
Labels: changelog/no-changelog

#6198 chore(ci): update pip cache path
  .circleci/config.yml
Labels: changelog/no-changelog

#5981 feat(debugging): exception debugging
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/debugging/_config.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_exception/__init__.py
  ddtrace/debugging/_exception/auto_instrument.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_probe/status.py
  ddtrace/debugging/_signal/collector.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_uploader.py
  ddtrace/settings/exception_debugging.py
  docs/configuration.rst
  releasenotes/notes/feat-exception-debugging-d4d73e95d37f914a.yaml
  tests/debugging/exception/__init__.py
  tests/debugging/exception/test_auto_instrument.py
  tests/debugging/exploration/debugger.py
  tests/debugging/mocking.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation

#6194 fix(ci): add write permissions for prune workflows
  .github/workflows/prune_workflow.yml
Labels: changelog/no-changelog

#6131 chore(bandit): fix and enable ddtrace/internal/schema
  ddtrace/internal/schema/__init__.py
  ddtrace/internal/schema/span_attribute_schema.py
  pyproject.toml
Labels: changelog/no-changelog

#6201 chore(telemetry): remove unnecessary fields from metrics payloads
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry_metrics.py
Labels: changelog/no-changelog

#6163 chore(asm): api security in the tracer
  ddtrace/contrib/trace_utils.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
Labels: changelog/no-changelog, ASM

#6196 chore(peer.service): perf - process traces instead of spans
  ddtrace/internal/processor/trace.py
  ddtrace/tracer.py
  tests/internal/peer_service/test_processor.py
Labels: changelog/no-changelog

#6195 refactor(openai): make OpenAI Integration derived from generic base class
  ddtrace/contrib/_trace_utils_llm.py
  ddtrace/contrib/openai/patch.py
  tests/contrib/openai/test_openai.py
Labels: changelog/no-changelog

#6180 chore(asm): add api security flask support
  ddtrace/contrib/flask/patch.py
  tests/contrib/flask/test_appsec_api_security.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#6193 chore(asm): add api security django support
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec_api_security.py
Labels: changelog/no-changelog, ASM

#6208 chore(dsm): handle when dd header not present for consuming service
  ddtrace/contrib/botocore/patch.py
  ddtrace/internal/datastreams/processor.py
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#6215 docs: flesh out contribution guidelines
  docs/contributing.rst
  docs/spelling_wordlist.txt
  docs/versioning.rst
Labels: changelog/no-changelog

#6220 fix(ci): update django framework test image
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 1.14, backport 1.15

#6223 docs: fix broken links in pr checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#6206 feat(ci-visibility): change how test module and suite names are reported
  ddtrace/contrib/pytest/plugin.py
  releasenotes/notes/feat-pytest-changes-in-modules-and-suites-bbdda83c3c40bfee.yaml
  tests/contrib/pytest/test_pytest.py
Labels: CI App, backport 1.15

#6224 ci: fix failing spellcheck in release note
  releasenotes/notes/fix-pytest-skip-fail-information-if-testcase-used-f8ccd7bf90615d78.yaml
Labels: changelog/no-changelog

#6185 feat(asm): add support for cookie vulnerability reporting
  ddtrace/appsec/iast/_util.py
  ddtrace/appsec/iast/constants.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/appsec/iast/taint_sinks/insecure_cookie.py
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/asm-insecure-cookies-bcf4d3268408b079.yaml
  tests/appsec/iast/test_insecure_cookie.py
  tests/tracer/test_trace_utils.py
Labels: ASM

#6238 docs: how to write snapshot tests
  docs/contributing-integrations.rst
Labels: changelog/no-changelog

#6243 chore(lib-injection): change the print statements in sitecustomize.py to print to stderr
  lib-injection/sitecustomize.py
Labels: changelog/no-changelog

#6227 feat(iast): iast telemetry metrics base
  ddtrace/appsec/_constants.py
  ddtrace/appsec/iast/_metrics.py
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/constants.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/internal/telemetry/constants.py
  tests/appsec/iast/test_telemety.py
Labels: changelog/no-changelog, ASM

#6237 chore: pin test agent release
  .circleci/config.yml
  docker-compose.yml
Labels: changelog/no-changelog

#6225 chore(peer.service): add mongodb.db as precursor for mongo
  ddtrace/settings/peer_service.py
  tests/contrib/mongoengine/test.py
  tests/contrib/pymongo/test.py
Labels: changelog/no-changelog
