Repository DataDog/dd-trace-py, pull requests merged in 2023-05, with the labels that each got.

#5705 fix(ci): fix check-releasenotes script to ensure only root releasenotes dir is checked
  scripts/check-releasenotes
Labels: changelog/no-changelog

#5707 chore(redis): extract redis common helpers to contrib utils [backport #5608 to 1.11]
  ddtrace/contrib/aioredis/patch.py
  ddtrace/contrib/aredis/patch.py
  ddtrace/contrib/flask_cache/utils.py
  ddtrace/contrib/redis/asyncio_patch.py
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/trace_utils_redis.py
  ddtrace/contrib/yaaredis/patch.py
Labels: changelog/no-changelog

#5709 chore(redis): extract redis common helpers to contrib utils [backport #5608 to 1.13]
  ddtrace/contrib/aioredis/patch.py
  ddtrace/contrib/aredis/patch.py
  ddtrace/contrib/flask_cache/utils.py
  ddtrace/contrib/redis/asyncio_patch.py
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/trace_utils_redis.py
  ddtrace/contrib/yaaredis/patch.py
Labels: changelog/no-changelog

#5698 chore(profiling): add native ID to user threads
  ddtrace/profiling/_threading.pyx
  tests/profiling/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#5706 refactor(internal): after module import decorator
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/internal/module.py
  tests/internal/test_module.py
Labels: changelog/no-changelog

#5717 chore(celery): fix flaky 'test_beat_scheduler_tracing'
  tests/contrib/celery/test_integration.py
Labels: changelog/no-changelog

#5701 chore(testing): fail the build if the git tree is dirty
  .circleci/config.yml
  .gitignore
  docker-compose.yml
  scripts/check-diff
  scripts/ddtest
Labels: changelog/no-changelog

#5708 chore(redis): extract redis common helpers to contrib utils [backport #5608 to 1.12]
  ddtrace/contrib/aioredis/patch.py
  ddtrace/contrib/aredis/patch.py
  ddtrace/contrib/flask_cache/utils.py
  ddtrace/contrib/redis/asyncio_patch.py
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/trace_utils_redis.py
  ddtrace/contrib/yaaredis/patch.py
Labels: changelog/no-changelog

#5733 refactor(tracer): remove redundant parent check in _start_span
  ddtrace/tracer.py
Labels: changelog/no-changelog

#5632 chore(service_name): enable service naming schema for multiple contribs
  ddtrace/contrib/aiomysql/patch.py
  ddtrace/contrib/aiopg/connection.py
  ddtrace/contrib/algoliasearch/patch.py
  ddtrace/contrib/asyncpg/patch.py
  ddtrace/contrib/cassandra/session.py
  ddtrace/contrib/elasticsearch/patch.py
  ddtrace/contrib/mongoengine/trace.py
  ddtrace/contrib/mysql/patch.py
  ddtrace/contrib/mysqldb/patch.py
  ddtrace/contrib/psycopg/patch.py
  ddtrace/contrib/pymemcache/patch.py
  ddtrace/contrib/pymongo/client.py
  ddtrace/contrib/pymysql/patch.py
  ddtrace/contrib/sqlite3/patch.py
  tests/contrib/aiomysql/test_aiomysql.py
  tests/contrib/aiopg/test.py
  tests/contrib/algoliasearch/test.py
  tests/contrib/asyncpg/test_asyncpg.py
  tests/contrib/cassandra/test.py
  tests/contrib/elasticsearch/test_elasticsearch.py
  tests/contrib/mongoengine/test.py
  tests/contrib/mysql/test_mysql.py
  tests/contrib/mysqldb/test_mysqldb.py
  tests/contrib/psycopg/test_psycopg.py
  tests/contrib/psycopg/test_psycopg_async.py
  tests/contrib/psycopg2/test_psycopg.py
  tests/contrib/pymemcache/test_client.py
  tests/contrib/pymongo/test.py
  tests/contrib/pymysql/test_pymysql.py
  tests/contrib/redis/test_redis.py
  tests/contrib/redis/test_redis_cluster.py
  tests/contrib/sqlite3/test_sqlite3.py
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_unspecified_service_v1.json
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_user_specified_service_v0.json
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_user_specified_service_v1.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_configure_service_name_env_v0.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_configure_service_name_env_v1.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_unspecified_service_name_env_v0.json
  tests/snapshots/tests.contrib.asyncpg.test_asyncpg.test_unspecified_service_name_env_v1.json
Labels: changelog/no-changelog

#5737 fix: move protobuf release note to correct dir for 5664 [backport #5702 to 1.13]
  releasenotes/notes/profiler-protobuf-421-bf20b8e42ba3ad4c.yaml
Labels: changelog/no-changelog

#5730 chore(telemetry): rename telemetry_writer
  benchmarks/ddtrace_run/scenario.py
  ddtrace/_monkey.py
  ddtrace/internal/telemetry/__init__.py
  ddtrace/internal/writer/writer.py
  tests/telemetry/conftest.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#5736 fix: move protobuf release note to correct dir for 5664 [backport #5702 to 1.11]
  releasenotes/notes/profiler-protobuf-421-bf20b8e42ba3ad4c.yaml
Labels: changelog/no-changelog

#5744 chore(ci): update Python versions in testrunner docker file
  docker/.python-version
  docker/Dockerfile.buster
Labels: changelog/no-changelog

#5748 fix(profiler): do not unload google.protobuf in module clean-up [backport #5747 to 1.13]
  ddtrace/bootstrap/sitecustomize.py
  releasenotes/notes/fix-profiler-segfault-in-protobuf-apps-032558829864cdfe.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5732 chore(profiling): map loops to threads without custom policy
  ddtrace/profiling/_asyncio.py
  ddtrace/profiling/collector/_task.pyx
  ddtrace/profiling/profiler.py
Labels: changelog/no-changelog, Profiling

#5749 fix(profiler): do not unload google.protobuf in module clean-up [backport #5747 to 1.12]
  ddtrace/bootstrap/sitecustomize.py
  releasenotes/notes/fix-profiler-segfault-in-protobuf-apps-032558829864cdfe.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5425 chore: release script ease of use and create notebook
  scripts/release.py
Labels: changelog/no-changelog

#5761 chore(ci): fix python interpreter versions in lockfile github action
  .github/workflows/requirements-locks.yml
Labels: changelog/no-changelog

#5766 ci: pin urllib3 to 1.26.15 for starlette to fix failing CI
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5740 chore(telemetry): ensure implementation is compatible with v1 and v2
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#5756 fix(telemetry): resolve unboundlocalerror raised by get_connection
  ddtrace/internal/telemetry/writer.py
Labels: changelog/no-changelog

#5741 feat(asm): waf metrics over telemetry
  benchmarks/bm/flask_utils.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  releasenotes/notes/asm-send-waf-metrics-over-telemetry-4208c7412e55cccd.yaml
  tests/appsec/test_telemety.py
  tests/telemetry/test_telemetry_metrics_e2e.py
Labels: ASM

#5455 fix(django): patch components on import
  .circleci/config.yml
  .riot/requirements/19ba70f.txt
  .riot/requirements/1a16fc1.txt
  .riot/requirements/1c6d4cc.txt
  .riot/requirements/4a79f8d.txt
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  releasenotes/notes/fix-django-patch-on-import-1c0344c171afcab2.yaml
  riotfile.py
  setup.cfg
  tests/contrib/django/test_django_patch.py
  tests/contrib/django_celery/app/demoapp/__init__.py
  tests/contrib/django_celery/app/demoapp/migrations/0001_initial.py
  tests/contrib/django_celery/app/demoapp/migrations/__init__.py
  tests/contrib/django_celery/app/demoapp/models.py
  tests/contrib/django_celery/app/demoapp/tasks.py
  tests/contrib/django_celery/app/demoapp/views.py
  tests/contrib/django_celery/app/manage.py
  tests/contrib/django_celery/app/proj/__init__.py
  tests/contrib/django_celery/app/proj/celery.py
  tests/contrib/django_celery/app/proj/settings.py
  tests/contrib/django_celery/app/proj/urls.py
  tests/contrib/django_celery/app/proj/wsgi.py
  tests/contrib/django_celery/test_django_celery.py
Labels: Tracing

#5779 ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.12]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5778 ci(openai): pin urllib3 for vcrpy testing dependency
  .riot/requirements/1030214.txt
  .riot/requirements/128f142.txt
  .riot/requirements/13a735a.txt
  .riot/requirements/13e7ae6.txt
  .riot/requirements/1ae41e7.txt
  .riot/requirements/1c841d4.txt
  .riot/requirements/1f75ee9.txt
  .riot/requirements/1f7a7e3.txt
  .riot/requirements/1fc9b0e.txt
  .riot/requirements/22c4774.txt
  .riot/requirements/33083b0.txt
  .riot/requirements/373147d.txt
  .riot/requirements/5853a9a.txt
  .riot/requirements/5f7eaed.txt
  .riot/requirements/a39f801.txt
  .riot/requirements/c112300.txt
  .riot/requirements/d1dc259.txt
  .riot/requirements/d1f6817.txt
  .riot/requirements/d50524d.txt
  .riot/requirements/e12f298.txt
  riotfile.py
Labels: changelog/no-changelog

#5783 ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.13]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5784 ci(openai): pin urllib3 for vcrpy testing dependency [backport #5778 to 1.13]
  .riot/requirements/1030214.txt
  .riot/requirements/128f142.txt
  .riot/requirements/13a735a.txt
  .riot/requirements/13e7ae6.txt
  .riot/requirements/1ae41e7.txt
  .riot/requirements/1c841d4.txt
  .riot/requirements/1f75ee9.txt
  .riot/requirements/1f7a7e3.txt
  .riot/requirements/1fc9b0e.txt
  .riot/requirements/22c4774.txt
  .riot/requirements/33083b0.txt
  .riot/requirements/373147d.txt
  .riot/requirements/5853a9a.txt
  .riot/requirements/5f7eaed.txt
  .riot/requirements/a39f801.txt
  .riot/requirements/c112300.txt
  .riot/requirements/d1dc259.txt
  .riot/requirements/d1f6817.txt
  .riot/requirements/d50524d.txt
  .riot/requirements/e12f298.txt
  riotfile.py
Labels: changelog/no-changelog

#5787 fix(profiler): do not unload google.protobuf in module clean-up [backport #5747 to 1.9]
  ddtrace/bootstrap/sitecustomize.py
  releasenotes/notes/fix-profiler-segfault-in-protobuf-apps-032558829864cdfe.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5765 chore(telemetry): enables telemetry without a periodic worker thread (in tests)
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/conftest.py
  tests/telemetry/test_telemetry_metrics.py
Labels: changelog/no-changelog

#5782 ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.9]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5785 fix(profiler): do not unload google.protobuf in module clean-up [backport #5747 to 1.11]
  ddtrace/bootstrap/sitecustomize.py
  releasenotes/notes/fix-profiler-segfault-in-protobuf-apps-032558829864cdfe.yaml
  tests/profiling/test_main.py
Labels: Profiling

#5781 ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.10]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5780 ci: pin urllib3 to 1.26.15 for starlette to fix failing CI [backport #5766 to 1.11]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#5536 feat(serverless): spawn serverless mini agent child process
  ddtrace/internal/serverless/__init__.py
  ddtrace/internal/serverless/mini_agent.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  ddtrace/tracer.py
  tests/internal/test_serverless.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#5764 chore(coverage): civisibility send coverage payload as multipart-form
  ddtrace/internal/ci_visibility/encoder.py
  tests/ci_visibility/test_encoder.py
Labels: changelog/no-changelog, CI App

#5773 fix(django): patch components on import [backport #5455 to 1.12]
  .circleci/config.yml
  .riot/requirements/19ba70f.txt
  .riot/requirements/1a16fc1.txt
  .riot/requirements/1c6d4cc.txt
  .riot/requirements/4a79f8d.txt
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  releasenotes/notes/fix-django-patch-on-import-1c0344c171afcab2.yaml
  riotfile.py
  setup.cfg
  tests/contrib/django/test_django_patch.py
  tests/contrib/django_celery/app/demoapp/__init__.py
  tests/contrib/django_celery/app/demoapp/migrations/0001_initial.py
  tests/contrib/django_celery/app/demoapp/migrations/__init__.py
  tests/contrib/django_celery/app/demoapp/models.py
  tests/contrib/django_celery/app/demoapp/tasks.py
  tests/contrib/django_celery/app/demoapp/views.py
  tests/contrib/django_celery/app/manage.py
  tests/contrib/django_celery/app/proj/__init__.py
  tests/contrib/django_celery/app/proj/celery.py
  tests/contrib/django_celery/app/proj/settings.py
  tests/contrib/django_celery/app/proj/urls.py
  tests/contrib/django_celery/app/proj/wsgi.py
  tests/contrib/django_celery/test_django_celery.py
Labels: Tracing

#5775 fix(django): patch components on import [backport #5455 to 1.10]
  .circleci/config.yml
  .riot/requirements/19ba70f.txt
  .riot/requirements/1a16fc1.txt
  .riot/requirements/1c6d4cc.txt
  .riot/requirements/4a79f8d.txt
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  releasenotes/notes/fix-django-patch-on-import-1c0344c171afcab2.yaml
  riotfile.py
  setup.cfg
  tests/contrib/django/test_django_patch.py
  tests/contrib/django_celery/app/demoapp/__init__.py
  tests/contrib/django_celery/app/demoapp/migrations/0001_initial.py
  tests/contrib/django_celery/app/demoapp/migrations/__init__.py
  tests/contrib/django_celery/app/demoapp/models.py
  tests/contrib/django_celery/app/demoapp/tasks.py
  tests/contrib/django_celery/app/demoapp/views.py
  tests/contrib/django_celery/app/manage.py
  tests/contrib/django_celery/app/proj/__init__.py
  tests/contrib/django_celery/app/proj/celery.py
  tests/contrib/django_celery/app/proj/settings.py
  tests/contrib/django_celery/app/proj/urls.py
  tests/contrib/django_celery/app/proj/wsgi.py
  tests/contrib/django_celery/test_django_celery.py
Labels: Tracing

#5774 fix(django): patch components on import [backport #5455 to 1.11]
  .circleci/config.yml
  .riot/requirements/19ba70f.txt
  .riot/requirements/1a16fc1.txt
  .riot/requirements/1c6d4cc.txt
  .riot/requirements/4a79f8d.txt
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  releasenotes/notes/fix-django-patch-on-import-1c0344c171afcab2.yaml
  riotfile.py
  setup.cfg
  tests/contrib/django/test_django_patch.py
  tests/contrib/django_celery/app/demoapp/__init__.py
  tests/contrib/django_celery/app/demoapp/migrations/0001_initial.py
  tests/contrib/django_celery/app/demoapp/migrations/__init__.py
  tests/contrib/django_celery/app/demoapp/models.py
  tests/contrib/django_celery/app/demoapp/tasks.py
  tests/contrib/django_celery/app/demoapp/views.py
  tests/contrib/django_celery/app/manage.py
  tests/contrib/django_celery/app/proj/__init__.py
  tests/contrib/django_celery/app/proj/celery.py
  tests/contrib/django_celery/app/proj/settings.py
  tests/contrib/django_celery/app/proj/urls.py
  tests/contrib/django_celery/app/proj/wsgi.py
  tests/contrib/django_celery/test_django_celery.py
Labels: Tracing

#5772 fix(django): patch components on import [backport #5455 to 1.13]
  .circleci/config.yml
  .riot/requirements/19ba70f.txt
  .riot/requirements/1a16fc1.txt
  .riot/requirements/1c6d4cc.txt
  .riot/requirements/4a79f8d.txt
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  releasenotes/notes/fix-django-patch-on-import-1c0344c171afcab2.yaml
  riotfile.py
  setup.cfg
  tests/contrib/django/test_django_patch.py
  tests/contrib/django_celery/app/demoapp/__init__.py
  tests/contrib/django_celery/app/demoapp/migrations/0001_initial.py
  tests/contrib/django_celery/app/demoapp/migrations/__init__.py
  tests/contrib/django_celery/app/demoapp/models.py
  tests/contrib/django_celery/app/demoapp/tasks.py
  tests/contrib/django_celery/app/demoapp/views.py
  tests/contrib/django_celery/app/manage.py
  tests/contrib/django_celery/app/proj/__init__.py
  tests/contrib/django_celery/app/proj/celery.py
  tests/contrib/django_celery/app/proj/settings.py
  tests/contrib/django_celery/app/proj/urls.py
  tests/contrib/django_celery/app/proj/wsgi.py
  tests/contrib/django_celery/test_django_celery.py
Labels: Tracing

#5793 ci(debugging): reduce exploration limits [backport #5600 to 1.9]
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5759 fix(asm): remove new line characters in asm blocked response
  ddtrace/internal/constants.py
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#5729 chore(testing): mark performance benchmark checklist item as optional
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#5796 ci(debugging): reduce exploration limits [backport #5600 to 1.12]
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5795 ci(debugging): reduce exploration limits [backport #5600 to 1.11]
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5794 ci(debugging): reduce exploration limits [backport #5600 to 1.10]
  .github/workflows/test_frameworks.yml
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5752 chore(ci): add diff path to scripts/check-diff
  .circleci/config.yml
  .github/workflows/requirements-locks.yml
  scripts/check-diff
Labels: changelog/no-changelog

#5659 chore(service_name): schemas for operation names
  ddtrace/contrib/pylibmc/client.py
  ddtrace/contrib/pymongo/client.py
  ddtrace/internal/schema/__init__.py
  ddtrace/internal/schema/span_attribute_schema.py
  tests/contrib/pylibmc/test.py
  tests/contrib/pymongo/test.py
Labels: changelog/no-changelog

#5743 refactor(internal): use get_connection in connector
  ddtrace/internal/utils/http.py
  tests/internal/test_utils_http.py
Labels: changelog/no-changelog

#5801 chore(ci): increase flask-simple timeout
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#5809 fix(openai): update metric names in docs
  ddtrace/contrib/openai/__init__.py
Labels: changelog/no-changelog

#5500 chore(telemetry): send event startup errors
  ddtrace/__init__.py
  ddtrace/_monkey.py
  ddtrace/internal/logger.py
  ddtrace/internal/telemetry/__init__.py
  ddtrace/internal/telemetry/data.py
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_data.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#5724 chore(ci): integrate test agent to handle all integration test traces
  .circleci/config.yml
  tests/contrib/openai/test_openai.py
  tests/utils.py
Labels: changelog/no-changelog

#5812 chore(ci-app): only upload .pack files
  ddtrace/internal/ci_visibility/git_client.py
Labels: changelog/no-changelog, CI App

#5811 chore(ci-app): ensure revisions as bytes
  ddtrace/ext/git.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App

#5816 chore(asm): django support on asm for multipart body
  ddtrace/appsec/utils.py
  ddtrace/contrib/django/utils.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5822 chore(asm): simplify asm request context span registration
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/processor.py
  tests/appsec/test_processor.py
Labels: changelog/no-changelog, ASM

#5827 fix(asm): simplify asm request context span registration [backport #5822 to 1.12]
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/processor.py
  releasenotes/notes/fix-asm-request-context-partial-flushing-7c45aaf55e836261.yaml
  tests/appsec/test_processor.py
Labels: ASM

#5826 fix(asm): simplify asm request context span registration [backport #5822 to 1.13]
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/processor.py
  releasenotes/notes/fix-asm-request-context-partial-flushing-7c45aaf55e836261.yaml
  tests/appsec/test_processor.py
Labels: ASM

#5798 chore(asm): iast taint django cookies
  ddtrace/appsec/_constants.py
  ddtrace/contrib/django/patch.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5831 chore(ci): remove unnused Dockerfile.buster file
  docker/Dockerfile.buster
Labels: changelog/no-changelog

#5745 chore(ci): add bandit security checking to CI
  .circleci/config.yml
  .riot/requirements/1aae4cb.txt
  pyproject.toml
  riotfile.py
Labels: changelog/no-changelog

#5824 chore(asm): update libddwaf to last version
  ddtrace/appsec/processor.py
  setup.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#5849 chore(asgi): revert regression that removed support for background tasks
  ddtrace/contrib/asgi/middleware.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5853 chore(asgi): revert regression that removed support for background tasks (backport #5849 to 1.12)
  ddtrace/contrib/asgi/middleware.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5851 chore(asgi): revert regression [backport #5849 to 1.13]
  ddtrace/contrib/asgi/middleware.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5854 chore(asgi): revert regression that removed support for background tasks (backport #5849 to 1.10)
  ddtrace/contrib/asgi/middleware.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5848 chore(ci): update system test scenarios
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, ASM

#5860 chore(asm): iast taint django path
  ddtrace/appsec/_constants.py
  ddtrace/contrib/django/patch.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5835 docs(psycopg): fix errors in integration documentation
  ddtrace/contrib/psycopg/__init__.py
  tests/contrib/django/test_django_snapshots.py
Labels: changelog/no-changelog

#5760 refactor(debugging): add LogSignal subclass
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_signal/collector.py
  ddtrace/debugging/_signal/metric_sample.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_signal/snapshot.py
  tests/debugging/exploration/debugger.py
  tests/debugging/signal/test_collector.py
  tests/debugging/test_debugger.py
  tests/debugging/test_encoding.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5855 ci: fix scheduled deployment
  .gitlab-ci.yml
Labels: changelog/no-changelog

#5802 chore(asm): iast taint flask cookies
  ddtrace/appsec/iast/_patch.py
  ddtrace/appsec/iast/_taint_utils.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask/wrappers.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM

#5871 fix(ci-visibility): discover service before calling setting
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/fix-ci-app-discover-service-name-3efc4032b0b68544.yaml
Labels: CI App

#5870 chore(iast): move functions to new folder, add cmakelist
  ddtrace/appsec/iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/iast/_taint_tracking/README.txt
  ddtrace/appsec/iast/_taint_tracking/TaintedObject/TaintedObject.cpp
  ddtrace/appsec/iast/_taint_tracking/TaintedObject/TaintedObject.h
  ddtrace/appsec/iast/_taint_tracking/_native.cpp
  ddtrace/appsec/iast/_taint_tracking/clean.sh
Labels: changelog/no-changelog, ASM

#5872 fix(ci-visibility): remove extra requests performed if env var not set
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/fix-ci-app-api-call-12f848d25f93d02d.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: CI App

#5879 refactor(internal): tidy up versioning in wrapping submodule
  ddtrace/internal/wrapping.py
Labels: changelog/no-changelog

#5881 fix(ci-visibility): remove extra requests performed if env var not set [backport #5872 to 1.13]
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/settings/config.py
  releasenotes/notes/fix-ci-app-api-call-12f848d25f93d02d.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: CI App

#5894 chore(ci-visibility): use `citestcov-intake` subdomain for coverage upload
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/writer.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App

#5194 chore(typing): avoid runtime errors in Python 3.5
  ddtrace/_hooks.py
  ddtrace/debugging/_debugger.py
  ddtrace/internal/logger.py
  ddtrace/internal/module.py
  ddtrace/internal/processor/trace.py
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog

#5869 chore(ci-visibility): fix recorder debug call
  ddtrace/internal/ci_visibility/recorder.py
Labels: changelog/no-changelog, CI App

#5865 refactor(openai): move endpoint hooks to new internal file, add utils file
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/contrib/openai/patch.py
  ddtrace/contrib/openai/utils.py
  tests/contrib/openai/test_openai.py
Labels: changelog/no-changelog

#5910 fix(openai): allow token inputs for Embeddings endpoint [backport #5890 to 1.14]
  ddtrace/contrib/openai/patch.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-openai-embeddings-input-7feb1198fabac31b.yaml
  tests/contrib/openai/test_openai.py
  tests/snapshots/tests.contrib.openai.test_openai.test_embedding_array_of_token_arrays.json
  tests/snapshots/tests.contrib.openai.test_openai.test_embedding_string_array.json
  tests/snapshots/tests.contrib.openai.test_openai.test_embedding_token_array.json
Labels: changelog/no-changelog

#5913 ci(benchmarks): disable unstable benchmarks
  .github/PULL_REQUEST_TEMPLATE.md
  benchmarks/flask_simple/config.yaml
Labels: changelog/no-changelog

#5922 ci(gunicorn): ensure tests are correctly parallelized
  .circleci/config.yml
Labels: changelog/no-changelog

#5924 ci(gunicorn): ensure tests are correctly parallelized [backport #5922 to 1.14]
  .circleci/config.yml
Labels: changelog/no-changelog

#5914 chore(profiling): use new module watchdog decorator
  ddtrace/profiling/_threading.pyx
Labels: changelog/no-changelog, Profiling

#5868 feat(iast): path traversal vulnerability
  ddtrace/_monkey.py
  ddtrace/appsec/iast/constants.py
  ddtrace/appsec/iast/taint_sinks/path_traversal.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/fixtures/path_traversal.py
  tests/appsec/iast/fixtures/path_traversal_test_file.txt
  tests/appsec/iast/test_path_traversal.py
Labels: changelog/no-changelog, ASM

#5931 docs: fix formatting and spelling in kafka release note
  releasenotes/notes/pass-args-kwargs-to-kafka-f3ca8128a2c4d612.yaml
Labels: changelog/no-changelog

#5915 ci(integrations): address flakiness in test_single_trace_too_large
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#5934 docs: fix formatting and spelling in kafka release note [backport #5931 to 1.12]
  releasenotes/notes/pass-args-kwargs-to-kafka-f3ca8128a2c4d612.yaml
Labels: changelog/no-changelog

#5933 docs: fix formatting and spelling in kafka release note [backport #5931 to 1.13]
  releasenotes/notes/pass-args-kwargs-to-kafka-f3ca8128a2c4d612.yaml
Labels: changelog/no-changelog

#5925 ci(gunicorn): ensure tests are correctly parallelized [backport #5922 to 1.13]
  .circleci/config.yml
Labels: changelog/no-changelog

#5929 chore(dependabot): updates directory
  .github/dependabot.yml
Labels: changelog/no-changelog

#5927 fix(sql): use psycopg's parse_dsn when available
  ddtrace/ext/sql.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-tracer-parse-pg-dsn-take2-7ef89362545b2721.yaml
  tests/contrib/psycopg/test_psycopg.py
  tests/contrib/psycopg2/test_psycopg.py
Labels: Tracing

#5908 ci(build-deploy): fix incorrect glob for uploading artifact to GitHub release
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#5930 fix(asm): rc must not modify rule file specified by env var
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/processor.py
  ddtrace/appsec/utils.py
  releasenotes/notes/asm_fix_rc_capabilities_with_rule_file_set_in_env-3c24b75abbdf003c.yaml
  tests/appsec/test_remoteconfiguration.py
Labels: bug, ASM

#5911 chore(ci-visibility): use agentless or evp proxy for all requests
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/writer.py
  tests/ci_visibility/test_ci_visibility.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog, CI App

#5903 ci(rc): fix subscriber flaky test
  tests/internal/remoteconfig/test_remoteconfig_subscriber.py
Labels: changelog/no-changelog, ASM

#5965 fix(sql): use psycopg's parse_dsn when available (backport #5927 to 1.14)
  ddtrace/ext/sql.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-tracer-parse-pg-dsn-take2-7ef89362545b2721.yaml
  tests/contrib/psycopg/test_psycopg.py
  tests/contrib/psycopg2/test_psycopg.py
Labels: changelog/no-changelog

#5689 feat(pytest): skip tests marked by the intelligent test runner
  ddtrace/contrib/pytest/plugin.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog, CI App

#5966 ci(build-deploy): fix incorrect glob for uploading artifact.. [backport #5908 to 1.14]
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#5942 fix(ci-visibility): remove gitlab pipeline url processing
  ddtrace/ext/ci.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-gitlab-ci-16.0-compatibility-1b77cb41e647b584.yaml
  tests/tracer/fixtures/ci/gitlab.json
Labels: CI App

#5984 fix(asm): rc must not modify rule file specified by env var [backport #5930 to 1.12]
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/processor.py
  ddtrace/appsec/utils.py
  releasenotes/notes/asm_fix_rc_capabilities_with_rule_file_set_in_env-3c24b75abbdf003c.yaml
  tests/appsec/test_remoteconfiguration.py
Labels: bug, ASM

#5978 chore(ci-visibility): fix exception for empty traces
  ddtrace/internal/ci_visibility/encoder.py
  tests/ci_visibility/test_encoder.py
Labels: changelog/no-changelog, CI App
