Repository DataDog/dd-trace-py, pull requests merged in 2023-03, with the labels that each got.

#5184 feat(rcm): aggregate remote config payloads
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/internal/remoteconfig/client.py
  tests/appsec/test_remoteconfiguration.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
Labels: changelog/no-changelog, ASM

#5232 feat(asm): add telemetry metrics support
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/processor.py
  tests/appsec/rules-good.json
  tests/appsec/test_processor.py
  tests/appsec/test_telemety.py
  tests/contrib/flask/test_flask_appsec_telemetry.py
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#5238 chore(asm): update rcm log messages
  ddtrace/appsec/_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#5221 chore(asm): define LazyTaintDict datastructure
  ddtrace/appsec/iast/_taint_utils.py
  tests/appsec/iast/test_taint_utils.py
Labels: changelog/no-changelog, ASM

#5047 chore(rcm): enable client into intermediate agent check state
  ddtrace/internal/agent.py
  ddtrace/internal/remoteconfig/__init__.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
  riotfile.py
  tests/appsec/test_remoteconfiguration.py
  tests/debugging/test_debugger.py
  tests/internal/remoteconfig/__init__.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
  tests/tracer/test_agent.py
Labels: changelog/no-changelog

#5219 chore: improve debugging CODEOWNERS section
  .github/CODEOWNERS
Labels: changelog/no-changelog

#5049 fix(asm): fix unicode decode errors in pylons [backport #5029 to 1.6]
  ddtrace/contrib/pylons/middleware.py
  releasenotes/notes/fix-unicode-decode-errors-pylons-52d28b22f82e184a.yaml
  tests/contrib/pylons/test_pylons.py
Labels: ASM

#5125 chore(debugger): respect default and custom rate for log probes
  ddtrace/debugging/_probe/remoteconfig.py
  tests/debugging/probe/test_remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5223 feat(rcm): update remote config warning message
  ddtrace/internal/remoteconfig/worker.py
Labels: changelog/no-changelog, ASM

#5244 chore(asm): add missing methods to WAF mockup
  ddtrace/appsec/ddwaf/__init__.py
Labels: changelog/no-changelog, ASM

#5247 chore(asm): free old waf handle after remote config update
  ddtrace/appsec/ddwaf/__init__.py
Labels: changelog/no-changelog, ASM

#5240 fix(asm): update ddwaf rules response
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/processor.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#5249 fix(rcm): check if the product callback exists
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/remoteconfig/client.py
  releasenotes/notes/rcm-fix-product-callback-d4d33b56ed8e17b4.yaml
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#5224 fix(aws_lambda): warn when impending timeout but all traces have been finished
  ddtrace/contrib/aws_lambda/patch.py
  releasenotes/notes/fix-aws-lambda-crashing-when-timeout-has-no-root-span-4a0fdacf707709a9.yaml
  tests/contrib/aws_lambda/handlers.py
  tests/contrib/aws_lambda/test_aws_lambda.py
  tests/snapshots/tests.contrib.aws_lambda.test_aws_lambda.test_continue_on_early_trace_ending.json
Labels: Tracing

#5237 chore: assign remote-config team to RCM sources
  .github/CODEOWNERS
Labels: changelog/no-changelog

#5185 chore(asm): update the list of IP headers to the latest RFC
  ddtrace/appsec/processor.py
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/asm-update-ip-resolution-04c9d92ea3138051.yaml
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/contrib/django/test_django_snapshots.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/flask/test_flask_appsec_telemetry.py
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/tracer/test_trace_utils.py
Labels: ASM

#5259 fix(rcm): check if the product callback exists [backport to 1.9]
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/remoteconfig/client.py
  releasenotes/notes/rcm-fix-product-callback-d4d33b56ed8e17b4.yaml
Labels: ASM

#5118 chore: add local backporting script
  scripts/backport
Labels: changelog/no-changelog

#5265 fix(aws_lambda): warn when impending timeout but all traces have been finished [backport #5224]
  ddtrace/contrib/aws_lambda/patch.py
  releasenotes/notes/fix-aws-lambda-crashing-when-timeout-has-no-root-span-4a0fdacf707709a9.yaml
  tests/contrib/aws_lambda/handlers.py
  tests/contrib/aws_lambda/test_aws_lambda.py
  tests/snapshots/tests.contrib.aws_lambda.test_aws_lambda.test_continue_on_early_trace_ending.json
Labels: Tracing

#5260 fix(asm): fix memory corruption in waf interface
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/ddwaf/ddwaf_types.py
  ddtrace/appsec/processor.py
  releasenotes/notes/fix-memory-leaks-and-segfaults-9fbdc8d66b32fb4f.yaml
  tests/appsec/test_processor.py
  tests/appsec/test_remoteconfiguration.py
Labels: ASM

#5231 chore(ci): cleanup riotfile by reducing tested contrib versions
  .circleci/config.yml
  .circleci/dependencies.py
  ddtrace/contrib/tornado/stack_context.py
  docs/contributing.rst
  riotfile.py
  tests/contrib/django/test_django_snapshots.py
  tests/contrib/elasticsearch/test_elasticsearch_multi.py
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_500_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_callable_view_18x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view_18x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_18x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_safe_string_encoding_21x.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_disabled_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_disabled_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_enabled_30.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_templates_enabled_31.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include_21x.json
Labels: changelog/no-changelog

#5267 fix(asm): fix memory corruption in waf interface [backport #5260 to 1.9]
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/ddwaf/ddwaf_types.py
  ddtrace/appsec/processor.py
  releasenotes/notes/fix-memory-leaks-and-segfaults-9fbdc8d66b32fb4f.yaml
  tests/appsec/test_processor.py
Labels: bug, ASM

#5262 fix(rcm): split ASM_FEATURES callback
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/remoteconfig/client.py
  tests/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#5274 chore(asm): update dd appsec rules to 1.5.2
  ddtrace/appsec/rules.json
  tests/appsec/rules-good.json
  tests/appsec/test_processor.py
  tests/snapshots/tests.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#5264 fix(asm): blocking response fixes post RC1
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/trace_utils.py
  ddtrace/contrib/wsgi/wsgi.py
  releasenotes/notes/asm-blocking-fixes-fce3bb6a81a2d186.yaml
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: ASM

#5270 fix(rcm): store payloads target files content
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/remoteconfig/client.py
  tests/appsec/test_remoteconfiguration.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
Labels: changelog/no-changelog, ASM

#5272 fix: use psycopg2 DSN parser to parse DSN
  ddtrace/contrib/psycopg/connection.py
  ddtrace/contrib/psycopg/patch.py
  releasenotes/notes/fix-psycopg-parse-dsn-f645bc9f056305c7.yaml
Labels: Tracing

#5283 fix: use psycopg2 DSN parser to parse DSN [backport #5272 to 1.9]
  ddtrace/contrib/psycopg/connection.py
  ddtrace/contrib/psycopg/patch.py
  releasenotes/notes/fix-psycopg-parse-dsn-f645bc9f056305c7.yaml
Labels: Tracing

#5239 chore(asm): avoid bundling unneeded ddwaf lib builds for other architectures
  setup.py
Labels: changelog/no-changelog, ASM

#5278 chore(rcm): update warning message (backport #5223 to 1.9)
  ddtrace/internal/remoteconfig/__init__.py
Labels: changelog/no-changelog

#5235 chore(agent_writer): replace report_metrics property with health_metrics_enabled config
  ddtrace/internal/writer.py
  ddtrace/tracer.py
  tests/integration/test_integration.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog, ASM

#5282 fix(debugging): handle disabled probes via RCM
  ddtrace/debugging/_probe/remoteconfig.py
  releasenotes/notes/fix-debugger-rcm-disable-events-8e5797d5d0606f50.yaml
Labels: Dynamic Instrumentation

#5293 chore(rcm): improve logs message
  ddtrace/internal/remoteconfig/client.py
Labels: changelog/no-changelog, ASM

#5281 chore(rcm): add ``apply_state`` and ``apply_error`` to RC response
  ddtrace/internal/remoteconfig/client.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
Labels: changelog/no-changelog, ASM

#5296 chore(docs): add instructions on compiling release notes
  docs/releasenotes.rst
Labels: changelog/no-changelog

#5304 ci: pin riot and update starlette tests to pass with non-semvar versions
  .circleci/config.yml
  scripts/ddtest
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5140 chore(opentelemetry): add initial support for the open telemetry trace api
  .circleci/config.yml
  .circleci/dependencies.py
  ddtrace/_opentelemetry/__init__.py
  ddtrace/_opentelemetry/_context.py
  ddtrace/_opentelemetry/span.py
  ddtrace/_opentelemetry/trace.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/span.py
  riotfile.py
  setup.py
  tests/contrib/celery/test_integration.py
  tests/opentelemetry/__init__.py
  tests/opentelemetry/conftest.py
  tests/opentelemetry/flask_app.py
  tests/opentelemetry/test_context.py
  tests/opentelemetry/test_span.py
  tests/opentelemetry/test_trace.py
  tests/snapshots/tests.opentelemetry.test_context.test_otel_ddtrace_mixed_parenting.json
  tests/snapshots/tests.opentelemetry.test_context.test_otel_multithreading.json
  tests/snapshots/tests.opentelemetry.test_context.test_otel_span_parenting.json
  tests/snapshots/tests.opentelemetry.test_context.test_otel_trace_across_fork.json
  tests/snapshots/tests.opentelemetry.test_context.test_otel_trace_multiple_coroutines.json
  tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes.json
  tests/snapshots/tests.opentelemetry.test_span.test_otel_span_kind.json
  tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_ddtrace_run].json
  tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_opentelemetry_instrument].json
  tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_current_span_with_default_args.json
  tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_current_span_without_default_args.json
  tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_span_ignore_exceptions.json
  tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_span_with_default_args.json
  tests/snapshots/tests.opentelemetry.test_trace.test_otel_start_span_without_default_args.json
Labels: changelog/no-changelog

#5299 feat(asm): update telemetry metrics
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/processor.py
  tests/appsec/test_telemety.py
Labels: changelog/no-changelog, ASM

#5241 fix(rcm): validate remote config is enabled
  ddtrace/debugging/_debugger.py
  ddtrace/internal/remoteconfig/__init__.py
  releasenotes/notes/rcm-fix-disable-f45787a4e6576f53.yaml
  tests/contrib/gunicorn/test_gunicorn.py
  tests/internal/remoteconfig/test_remoteconfig.py
Labels: ASM

#5307 ci: pin riot and fix starlette tests [backport 5304 to 1.10]
  .circleci/config.yml
  scripts/ddtest
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5316 chore(asm): iast sql injection vulnerability
  ddtrace/appsec/iast/_taint_utils.py
  ddtrace/appsec/iast/constants.py
  ddtrace/appsec/iast/taint_sinks/sql_injection.py
  tests/appsec/iast/test_taint_utils.py
Labels: changelog/no-changelog, ASM

#5308 ci: pin riot and fix starlette tests [backport #5304 to 1.9]
  .circleci/config.yml
  scripts/ddtest
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5312 fix(asm): ensure platform can compile taint tracking sources [backport #5289 to 1.9]
  releasenotes/notes/fix-asm-taint-tracking-compilation-8c740752bd9df137.yaml
  setup.py
Labels: changelog/no-changelog, ASM

#5309 ci: pin riot and fix starlette tests [backport #5304 to 1.8]
  .circleci/config.yml
  scripts/ddtest
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5311 fix(asm): ensure platform can compile taint tracking sources [backport #5289 to 1.10]
  releasenotes/notes/fix-asm-taint-tracking-compilation-8c740752bd9df137.yaml
  setup.py
Labels: changelog/no-changelog, ASM

#5301 fix(debugging): handle disabled probes via RCM [backport #5282 to 1.10]
  ddtrace/debugging/_probe/remoteconfig.py
  releasenotes/notes/fix-debugger-rcm-disable-events-8e5797d5d0606f50.yaml
Labels: Dynamic Instrumentation

#5318 chore(asm): iast sql injection sink point
  .github/CODEOWNERS
  ddtrace/contrib/dbapi/__init__.py
  tests/contrib/dbapi/test_dbapi_appsec.py
Labels: changelog/no-changelog, ASM

#5319 fix(rcm): validate remote config is enabled [backport #5241 to 1.10]
  ddtrace/debugging/_debugger.py
  ddtrace/internal/remoteconfig/__init__.py
  releasenotes/notes/rcm-fix-disable-f45787a4e6576f53.yaml
  tests/contrib/gunicorn/test_gunicorn.py
  tests/internal/remoteconfig/test_remoteconfig.py
Labels: ASM

#5250 chore(docs): ignore dbm fix note in 1.10.0 release
  docs/release_notes.rst
Labels: changelog/no-changelog

#5280 chore(asm): move the user blocking check at the end of `set_user`
  ddtrace/contrib/trace_utils.py
  tests/appsec/test_appsec_trace_utils.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog, ASM

#5328 fix(asm): fix 403 response being inadequatly replaced by datadog response block response (1.9)
  ddtrace/contrib/django/patch.py
  releasenotes/notes/asm_fix_403_django_body-9adabde1f2f95c98.yaml
Labels: bug, ASM

#5302 chore: infer remote name in backport script
  scripts/backport
Labels: changelog/no-changelog

#5332 fix(botocore): fix kinesis typeerror [backports #5317 to 1.10]
  ddtrace/contrib/botocore/patch.py
  releasenotes/notes/fix-botocore-newline-str-issues-fab81e395207b0ed.yaml
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#5329 chore(asm): add encode and decode aspects to iast
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_ast/visitor.py
  ddtrace/appsec/iast/_taint_tracking/_taint_tracking.cpp
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
Labels: changelog/no-changelog, ASM

#5341 chore(asm): add env var for modules to be patched by iast
  ddtrace/appsec/_constants.py
  ddtrace/appsec/iast/_ast/ast_patching.py
  tests/appsec/iast/ast/test_ast_patching.py
  tests/appsec/iast/test_env_var.py
Labels: changelog/no-changelog, ASM

#5227 fix(tests): create and reuse requirements lockfiles during tests
  .circleci/config.yml
  .circleci/dependencies.py
  docs/contributing.rst
  docs/spelling_wordlist.txt
  riotfile.py
  scripts/compile-and-prune-test-requirements
  scripts/ddtest
  tests/integration/test_debug.py
Labels: changelog/no-changelog

#5334 fix(botocore): fix kinesis typeerror [backports #5317 to 1.8]
  ddtrace/contrib/botocore/patch.py
  releasenotes/notes/fix-botocore-newline-str-issues-fab81e395207b0ed.yaml
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#5346 chore(asm): use _iast_enabled in config for tests in override_global_config
  ddtrace/_monkey.py
  tests/appsec/iast/test_processor.py
  tests/contrib/django/test_django_appsec.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#5349 ci(aws_lambda): run aws lambda tests in circleci
  .circleci/config.yml
Labels: changelog/no-changelog

#5230 chore(testrunner): add latest tag
  .github/workflows/testrunner.yml
Labels: changelog/no-changelog

#5363 Revert "chore(deps): bump mysql-connector-python from 8.0.5 to 8.0.14 in /.riot/requirements"
  .riot/requirements/106972e.txt
  .riot/requirements/10d623a.txt
  .riot/requirements/1133f63.txt
  .riot/requirements/1230ff8.txt
  .riot/requirements/129b0f2.txt
  .riot/requirements/12db871.txt
  .riot/requirements/137147e.txt
  .riot/requirements/147a097.txt
  .riot/requirements/16025dc.txt
  .riot/requirements/16bac29.txt
  .riot/requirements/1a1c1fa.txt
  .riot/requirements/1ab28fe.txt
  .riot/requirements/1cdb1c5.txt
  .riot/requirements/1d614be.txt
  .riot/requirements/1e72d9c.txt
  .riot/requirements/270f95a.txt
  .riot/requirements/2d6d58d.txt
  .riot/requirements/2eb00ea.txt
  .riot/requirements/543c254.txt
  .riot/requirements/729b5a8.txt
Labels: changelog/no-changelog

#5369 chore(asm): add form parameter extraction to django
  ddtrace/contrib/django/utils.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#3809 fix(tracing): make tracing work with coroutines of streaming response RPC
  ddtrace/contrib/grpc/aio_server_interceptor.py
  tests/contrib/grpc_aio/test_grpc_aio.py
Labels: changelog/no-changelog

#5371 chore(ci): improve remote detection for scripts/backport
  scripts/backport
Labels: changelog/no-changelog

#5214 chore(asm): taint request support for django framework
  ddtrace/appsec/iast/_patch.py
  ddtrace/contrib/django/patch.py
  tests/contrib/django/django_app/urls.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/views.py
Labels: changelog/no-changelog, ASM

#5378 fix(telemetry): call platform.platform once on import and save the result
  ddtrace/internal/telemetry/data.py
Labels: changelog/no-changelog

#5367 ci(aws_lambda): run aws lambda tests in circleci [backport #5349 to 1.10]
  .circleci/config.yml
Labels: changelog/no-changelog

#5377 fix(docs): stop using deprecated python.version readthedocs configuration
  .readthedocs.yml
Labels: changelog/no-changelog

#5379 fix(docs): fix incorrect default note in configuration docs
  docs/configuration.rst
Labels: changelog/no-changelog

#5355 chore(lib-injection): add unit tests
  .github/workflows/lib-injection.yml
Labels: changelog/no-changelog

#5366 chore(asm): improve test coverage for flask srb
  ddtrace/contrib/flask/patch.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM

#5295 chore(debugging): do not warn about missing RCM metadata
  ddtrace/debugging/_probe/remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5381 fix(celery): remove reference to github issue
  ddtrace/contrib/celery/signals.py
Labels: changelog/no-changelog

#5210 chore(asm): taint request support for flask framework
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/flask/patch.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM

#5380 fix(falcon): remove reference to github issue
  ddtrace/contrib/falcon/middleware.py
Labels: changelog/no-changelog

#5383 fix(iast): add hash and spanid values to Vulnerability
  ddtrace/appsec/iast/reporter.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  tests/appsec/iast/test_reporter.py
Labels: changelog/no-changelog, ASM

#5131 feat(debugger): add dynamic span function probes
  ddtrace/debugging/_capture/dynamic_span.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/remoteconfig.py
  releasenotes/notes/feat-debugging-span-probes-c441d7eb186f5f20.yaml
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/test_debugger.py
  tests/debugging/utils.py
  tests/submod/stuff.py
Labels: Dynamic Instrumentation

#5368 ci(aws_lambda): run aws lambda tests in circleci [backport #5349 to 1.9]
  .circleci/config.yml
  tests/contrib/aws_lambda/test_aws_lambda.py
Labels: changelog/no-changelog

#5288 chore: update generate patch test source to log failures
  scripts/contrib-patch-tests.py
Labels: changelog/no-changelog

#5386 chore(asm): deprecate private appsec constants from public API
  ddtrace/constants.py
  releasenotes/notes/remove-API_appsec_private_constants-ec4b05f7bf5f6c29.yaml
  tests/appsec/test_constants.py
Labels: ASM

#5313 test(celery): fix failing opentracing test
  tests/contrib/celery/test_integration.py
Labels: changelog/no-changelog

#5388 fix(system-tests): setup python 3.9 for system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#5396 chore(asm): waf_timeout in global config
  ddtrace/appsec/_constants.py
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/ddwaf/ddwaf_types.py
  ddtrace/appsec/processor.py
  ddtrace/settings/config.py
  tests/appsec/test_telemety.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#5400 ci: pin riot and update starlette tests to pass with non-semvar versions [backport #5304 to 1.7]
  .circleci/config.yml
  scripts/ddtest
  tests/contrib/starlette/test_starlette.py
Labels: changelog/no-changelog

#5297 chore: add release notes script
  scripts/release.py
Labels: changelog/no-changelog

#5411 chore(ci): use testrunner for ddtest
  .circleci/config.yml
  docker-compose.yml
Labels: changelog/no-changelog

#5405 fix(debugging): continue after first function probe failure
  ddtrace/debugging/_debugger.py
  releasenotes/notes/fix-debugger-continue-wrapping-07c38a6e7dbe497f.yaml
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation

#5406 test(debugging): mark buffer full test as flaky on Python 2
  tests/debugging/test_uploader.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5402 fix(futures): unload futures submodule during module cleanup
  ddtrace/_monkey.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/futures/patch.py
  ddtrace/contrib/futures/threading.py
  releasenotes/notes/fix-futures-module-unload-e84900affff06152.yaml
  riotfile.py
  tests/conftest.py
  tests/contrib/futures/test_futures_patch_generated.py
  tests/contrib/futures/test_propagation.py
  tests/utils.py
Labels: Tracing

#5419 chore(asm): change waf log level to debug
  ddtrace/appsec/ddwaf/__init__.py
  ddtrace/appsec/ddwaf/ddwaf_types.py
Labels: changelog/no-changelog, ASM

#5417 chore(asm): move span id from vulnerability to location
  ddtrace/appsec/iast/reporter.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  tests/appsec/iast/test_reporter.py
Labels: changelog/no-changelog, ASM

#5397 chore(asm): move iast taint tracking dict to asm context
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/iast/_ast/aspects/__init__.py
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/_taint_tracking/_native.cpp
  ddtrace/appsec/iast/_taint_tracking/_taint_tracking.cpp
  ddtrace/appsec/iast/_taint_utils.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/flask/patch.py
  setup.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/test_taint_utils.py
  tests/contrib/dbapi/test_dbapi_appsec.py
Labels: changelog/no-changelog, ASM

#5399 ci(boto): update the version of localstack used in tests
  docker-compose.yml
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#5303 feat(kafka): add confluent_kafka integration
  .circleci/config.yml
  .riot/requirements/e376a11.txt
  ddtrace/_monkey.py
  ddtrace/contrib/kafka/__init__.py
  ddtrace/contrib/kafka/patch.py
  ddtrace/ext/kafka.py
  ddtrace/internal/constants.py
  docker-compose.yml
  docs/index.rst
  docs/integrations.rst
  docs/spelling_wordlist.txt
  releasenotes/notes/feat-confluent-kafka-support-3715cd9476e03c7f.yaml
  riotfile.py
  tests/contrib/config.py
  tests/contrib/kafka/__init__.py
  tests/contrib/kafka/test_kafka.py
  tests/contrib/kafka/test_kafka_patch.py
  tests/snapshots/tests.contrib.kafka.test_kafka.test_analytics_with_rate.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_analytics_without_rate.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_message[False].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_message[True].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_service_override.json
Labels: Tracing

#5389 chore(debugging): support probe mutability
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/registry.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_probe/status.py
  tests/debugging/mocking.py
  tests/debugging/probe/test_model.py
  tests/debugging/probe/test_registry.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/test_debugger.py
  tests/debugging/utils.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#5422 chore(asm): handle any object passed to the waf as str
  ddtrace/appsec/ddwaf/ddwaf_types.py
  tests/appsec/test_ddwaf_fuzz.py
Labels: changelog/no-changelog, ASM

#5195 feat: add missing component tag to aiohttp connection patch
  ddtrace/contrib/aiohttp/patch.py
  releasenotes/notes/add-missing-component-tag-on-aiohttp-tcp-spans-8c9fe55d4e8f9085.yaml
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_200_request.json
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_200_request_post.json
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_500_request.json
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_auth_200_request.json
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_configure_global_service_name_env.json
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_configure_service_name_pin.json
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_trace_multiple.json
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_trace_parenting.json
  tests/snapshots/tests.contrib.aiohttp.test_aiohttp_client.test_trace_query_string.json
Labels: changelog/no-changelog

#5326 feat(tracing): support 128-bit trace ids [does not include support for b3 and w3c]
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/_rand.pyi
  ddtrace/internal/_rand.pyx
  ddtrace/internal/constants.py
  ddtrace/internal/encoding.py
  ddtrace/internal/processor/trace.py
  ddtrace/propagation/http.py
  ddtrace/sampler.py
  ddtrace/settings/config.py
  ddtrace/span.py
  docs/configuration.rst
  releasenotes/notes/add-dd-128bit-traceid-releasenote-dae1a746134859bb.yaml
  riotfile.py
  tests/tracer/test_encoders.py
  tests/tracer/test_processors.py
  tests/tracer/test_propagation.py
  tests/tracer/test_rand.py
  tests/tracer/test_sampler.py
  tests/tracer/test_span.py
  tests/tracer/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog

#5432 chore: fix dynamic instrumentation release note
  releasenotes/notes/fix-debugger-rcm-disable-events-8e5797d5d0606f50.yaml
Labels: changelog/no-changelog

#5429 fix(debugging): evaluate metric values
  ddtrace/debugging/_expressions.py
  ddtrace/debugging/_probe/model.py
  releasenotes/notes/fix-debugger-callable-dd-expressions-71bbb3769e13ae29.yaml
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation

#5436 chore(asm): iast remove evidence type from json
  ddtrace/appsec/iast/reporter.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  tests/appsec/iast/test_reporter.py
  tests/appsec/iast/test_weak_hash.py
Labels: changelog/no-changelog, ASM

#5435 chore(asm): iast send value parts information in the evidence
  ddtrace/appsec/iast/_input_info.py
  ddtrace/appsec/iast/_taint_tracking/__init__.py
  ddtrace/appsec/iast/processor.py
  ddtrace/appsec/iast/reporter.py
  ddtrace/appsec/iast/taint_sinks/_base.py
  ddtrace/appsec/iast/taint_sinks/sql_injection.py
  tests/appsec/iast/test_taint_tracking.py
Labels: changelog/no-changelog, ASM

#5390 chore(docs): modify PR checklist to explicitly acknowledge performance implications
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#5447 chore(asm): add specific test for case sensitive security rule
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#5428 chore(flake8): exclude ddtrace/__init__.py
  setup.cfg
Labels: changelog/no-changelog

#5442 fix(aws_lambda): fix circular dependency when user handler patches modules [backport #5401 to 1.10]
  ddtrace/contrib/aws_lambda/patch.py
  releasenotes/notes/fix-aws-lambda-circular-dep-when-patching-in-handler-320de20015a8d5cd.yaml
Labels: changelog/no-changelog

#5423 chore(codeowners): assign profiling sources to profiling team
  .github/CODEOWNERS
Labels: changelog/no-changelog

#5424 chore(opentelemetry): add trace state and trace flags to SpanContext
  ddtrace/_opentelemetry/span.py
  tests/opentelemetry/test_span.py
Labels: changelog/no-changelog
