Repository DataDog/dd-trace-py, pull requests merged in 2024-11, with the labels that each got.

#11258 fix(profiling): call before_flush() before calling ddup.upload()
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/scheduler.py
  releasenotes/notes/profiling-live-heap-libdd-49ff3a5d6405fd7e.yaml
  tests/profiling_v2/collector/test_memalloc.py
Labels: Profiling, backport 2.14, backport 2.15, backport 2.16

#11261 refactor(profiling): remove pytest.mark.subprocess from v2/test_stack.py [backport 2.14]
  ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  tests/profiling/collector/pprof_utils.py
  tests/profiling_v2/collector/test_stack.py
Labels: changelog/no-changelog, Profiling

#11260 refactor(profiling): remove pytest.mark.subprocess from v2/test_stack.py [backport 2.15]
  ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  tests/profiling/collector/pprof_utils.py
  tests/profiling_v2/collector/test_stack.py
Labels: changelog/no-changelog, Profiling

#11247 fix(iast): add google.auth to the IAST denylist [backport 2.13]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/iast-fi-import-error-google-37815bda58036c08.yaml
  tests/appsec/iast_packages/packages/pkg_google_api_core.py
  tests/appsec/iast_packages/test_packages.py
Labels: ASM

#11277 chore(ci): stop using macos 12
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog

#11206 fix(profiling): remove usage of `ensure_binary_or_empty` from ddup
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  releasenotes/notes/profiling-reduce-memory-allocs-7b3d80adf0d2d0e7.yaml
  tests/profiling/collector/pprof_utils.py
  tests/profiling_v2/collector/test_memalloc.py
  tests/profiling_v2/collector/test_stack.py
Labels: Profiling, backport 2.14, backport 2.15, backport 2.16

#11282 test: enable crashtracking during all tests
  tests/conftest.py
Labels: changelog/no-changelog

#11257 chore(ci_visibility): don't rely on TestShortLogReport in pytest v2 plugin
  ddtrace/contrib/pytest/_atr_utils.py
  ddtrace/contrib/pytest/_efd_utils.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_types.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog

#11289 ci: make fastapi test framework use newer cache action
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#11136 chore(asm): configuration endpoint as private env var
  ddtrace/constants.py
  ddtrace/settings/asm.py
  ddtrace/settings/config.py
  ddtrace/settings/endpoint_config.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/fixtures/integration/http_config_server.py
  tests/appsec/iast/test_env_var.py
  tests/tracer/test_endpoint_config.py
Labels: changelog/no-changelog, ASM, backport 2.16

#11292 test: only auto-enable crashtracking in tests on linux
  tests/conftest.py
Labels: changelog/no-changelog

#11278 chore(iast): restore, update and improve the native import smoke_test
  tests/smoke_test.py
Labels: changelog/no-changelog, ASM

#11279 chore(llmobs): fix telemetry namespace for ragas
  ddtrace/llmobs/_evaluators/ragas/faithfulness.py
  ddtrace/llmobs/_evaluators/runner.py
  ddtrace/llmobs/_evaluators/sampler.py
Labels: changelog/no-changelog, backport 2.16

#11254 chore: update changelog for version 2.15.1
  CHANGELOG.md
Labels: changelog/no-changelog

#11242 chore(llmobs): call periodic for runner when flushing
  ddtrace/llmobs/_llmobs.py
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog

#11305 fix(iast): add google.auth and googlecloudsdk to the IAST denylist
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/google-sdk-denylist-0619f1734507019a.yaml
Labels: ASM, backport 2.14, backport 2.15, backport 2.16

#11300 fix(profiling): stack v2 tracks threads in gunicorn workers
  ddtrace/profiling/collector/threading.py
  releasenotes/notes/profiling-gunicorn-track-06a211fc1e2643e1.yaml
  tests/profiling/collector/pprof_utils.py
  tests/profiling/gunicorn-app.py
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/test_gunicorn.py
Labels: Profiling, backport 2.14, backport 2.15, backport 2.16

#11291 ci: add stack v2 profiling to Django profiling
  .github/workflows/django-overhead-profile.yml
Labels: changelog/no-changelog, CI

#11095 refactor: use telemetry in product protocol
  ddtrace/debugging/_debugger.py
  ddtrace/internal/products.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/utils/version.py
Labels: changelog/no-changelog

#11307 chore(asm): improve logs in asm_request_context
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_utils.py
  tests/appsec/appsec/test_asm_request_context.py
Labels: changelog/no-changelog, ASM, backport 2.14, backport 2.15, backport 2.16

#11234 chore(llmobs): add context & query variable helper fields for helper prompt
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/_utils.py
  ddtrace/llmobs/utils.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog

#11288 fix(asm): put back email/login/name in traces for django user
  .github/workflows/system-tests.yml
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/django/__init__.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/django/utils.py
  ddtrace/settings/asm.py
  releasenotes/notes/ato_fix__feature_flag_for_optional_user_info-28a1ce33eeb6a275.yaml
  tests/contrib/django/test_django_appsec.py
  tests/telemetry/test_writer.py
Labels: ASM, mergequeue-status: waiting, backport 2.14, backport 2.15, backport 2.16

#11302 chore(asm): endpoint configuration with retries and timeout
  ddtrace/constants.py
  ddtrace/settings/endpoint_config.py
  tests/appsec/iast/fixtures/integration/http_config_server.py
  tests/appsec/iast/test_env_var.py
  tests/tracer/test_endpoint_config.py
Labels: changelog/no-changelog, ASM, backport 2.16

#11321 chore(ci): disable macrobenchmark crash tracking to avoid signaling irrelevant crashes
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI, mergequeue-status: waiting

#11327 chore(ci): remove unused type ignore comments
  ddtrace/llmobs/_evaluators/ragas/faithfulness.py
  ddtrace/llmobs/_evaluators/runner.py
  ddtrace/llmobs/_evaluators/sampler.py
Labels: changelog/no-changelog, mergequeue-status: removed

#11293 chore: update changelog for version 2.16.0, 2.15.2, 2.14.6
  CHANGELOG.md
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11317 fix(lib-injection): do not import user installed ddtrace
  lib-injection/sources/sitecustomize.py
  releasenotes/notes/fix-lib-injection-import-f0e5e2715854d3e0.yaml
Labels: mergequeue-status: rejected, backport 2.16

#11296 fix(lib-injection): increase coverage of Python lib-injection denylist
  lib-injection/sources/denied_executables.txt
  releasenotes/notes/fix-lib-injection-denylist-d5478ecfef90fbcd.yaml
Labels: mergequeue-status: rejected, backport 2.16

#11294 fix: update libdatadog to v14, which fixes crashtracking
  ddtrace/internal/core/crashtracking.py
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/libdatadog_checksums.txt
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyi
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyx
  ddtrace/internal/datadog/profiling/dd_wrapper/include/constants.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker_interface.cpp
  ddtrace/settings/crashtracker.py
  releasenotes/notes/fix-crashtracking-zombies-7d84bc2e0b4d366e.yaml
  tests/internal/crashtracker/test_crashtracker.py
  tests/internal/crashtracker/utils.py
  tests/telemetry/test_writer.py
Labels: mergequeue-status: removed, backport 2.16

#11209 chore(ci): update codespell
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_utils.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/internal/django/utils.py
  ddtrace/contrib/internal/rediscluster/patch.py
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/ci_visibility/api/_module.py
  ddtrace/internal/datadog/profiling/dd_wrapper/dd_wrapper.md
  ddtrace/internal/opentelemetry/context.py
  ddtrace/profiling/profiler.py
  ddtrace/settings/asm.py
  ddtrace/settings/config.py
  docs/spelling_wordlist.txt
  hatch.toml
  releasenotes/notes/reconcile-sampling-decsions-otel-21c6aae6ccbcfa31.yaml
  tests/contrib/boto/test.py
  tests/contrib/botocore/test_bedrock_llmobs.py
  tests/contrib/dramatiq/test_integration.py
  tests/contrib/graphql/test_graphql.py
  tests/integration/test_sampling.py
  tests/internal/test_module.py
  tests/internal/test_tracer_flare.py
  tests/opentracer/core/test_tracer.py
  tests/tracer/test_propagation.py
  tests/tracer/test_sampler.py
Labels: changelog/no-changelog

#11334 fix(asm): put back email/login/name in traces for django user (#11288) [backport 2.15]
  .github/workflows/system-tests.yml
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/django/__init__.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/django/utils.py
  ddtrace/settings/asm.py
  releasenotes/notes/ato_fix__feature_flag_for_optional_user_info-28a1ce33eeb6a275.yaml
  tests/contrib/django/test_django_appsec.py
  tests/telemetry/test_writer.py
Labels: ASM, mergequeue-status: rejected

#11306 feat(lib-injection): add SSI denylist using requirements.json
  .gitlab-ci.yml
  .gitlab/requirements_allow.json
  .gitlab/requirements_block.json
  lib-injection/sources/requirements.json
  releasenotes/notes/add-requirements-json-038073d722697e32.yaml
Labels: mergequeue-status: rejected

#11330 fix(llmobs): ensure non-ascii characters are not encoded into raw unicode
  ddtrace/llmobs/_utils.py
  releasenotes/notes/fix-llmobs-non-ascii-langchain-eb3263c79ad83ffb.yaml
  tests/contrib/langchain/cassettes/langchain_community/openai_completion_non_ascii.yaml
  tests/contrib/langchain/test_langchain_llmobs.py
Labels: backport 2.15, backport 2.16

#11315 fix(profiling): stack v2 tracks threads in gunicorn workers [backport 2.15]
  ddtrace/profiling/collector/threading.py
  releasenotes/notes/profiling-gunicorn-track-06a211fc1e2643e1.yaml
  tests/profiling/collector/pprof_utils.py
  tests/profiling/gunicorn-app.py
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/test_gunicorn.py
Labels: Profiling

#11316 fix(profiling): stack v2 tracks threads in gunicorn workers [backport 2.14]
  ddtrace/profiling/collector/threading.py
  releasenotes/notes/profiling-gunicorn-track-06a211fc1e2643e1.yaml
  tests/profiling/collector/pprof_utils.py
  tests/profiling/gunicorn-app.py
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/test_gunicorn.py
Labels: Profiling

#11324 docs: code origin configuration
  docs/configuration.rst
Labels: changelog/no-changelog

#11348 chore(ci): remove pinned versions of gevent from profile, opentracer tests [backport 2.15]
  .riot/requirements/125c1e6.txt
  .riot/requirements/12a4316.txt
  .riot/requirements/1413039.txt
  .riot/requirements/1452073.txt
  .riot/requirements/172dc1d.txt
  .riot/requirements/197de71.txt
  .riot/requirements/19a43a5.txt
  .riot/requirements/1edf426.txt
  .riot/requirements/1ef2187.txt
  .riot/requirements/1f989f6.txt
  .riot/requirements/ac92a08.txt
  .riot/requirements/de95112.txt
  riotfile.py
Labels: changelog/no-changelog, CI

#11347 chore(ci): remove pinned versions of gevent from profile, opentracer tests [backport 2.14]
  .riot/requirements/125c1e6.txt
  .riot/requirements/12a4316.txt
  .riot/requirements/1413039.txt
  .riot/requirements/1452073.txt
  .riot/requirements/172dc1d.txt
  .riot/requirements/197de71.txt
  .riot/requirements/19a43a5.txt
  .riot/requirements/1edf426.txt
  .riot/requirements/1ef2187.txt
  .riot/requirements/1f989f6.txt
  .riot/requirements/ac92a08.txt
  .riot/requirements/de95112.txt
  riotfile.py
Labels: changelog/no-changelog, CI

#11350 fix(profiling): clear sample pool after fork
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample_manager.cpp
  releasenotes/notes/profiling-sample-pool-461a108e068dea5b.yaml
Labels: Profiling, backport 2.14, backport 2.15, backport 2.16

#11337 chore(profiling): bump libdatadog version
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/libdatadog_checksums.txt
Labels: changelog/no-changelog, mergequeue-status: rejected

#11336 chore(profiling): add profiling configuration to crashtracking tags
  ddtrace/profiling/profiler.py
Labels: changelog/no-changelog, mergequeue-status: removed

#11271 chore(llmobs): add metadata to the ragas evaluation metric
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_evaluators/ragas/faithfulness.py
  tests/llmobs/_utils.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_faithfulness_evaluator.test_ragas_faithfulness_submits_evaluation_on_span_with_custom_keys.yaml
  tests/llmobs/test_llmobs_evaluator_runner.py
  tests/llmobs/test_llmobs_ragas_faithfulness_evaluator.py
Labels: changelog/no-changelog

#11322 chore(ci_visibility): fixes for v2 pytest plugin
  ddtrace/contrib/pytest/_plugin_v2.py
  riotfile.py
  tests/ci_visibility/api/test_internal_test_visibility_api.py
  tests/ci_visibility/api_client/_util.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, mergequeue-status: rejected

#11361 ci(profiling): v1/v2 matrix in Django overhead job
  .github/workflows/django-overhead-profile.yml
Labels: changelog/no-changelog, Profiling

#11359 chore(ci_visibility): fix telemetry name for manual api events
  ddtrace/internal/ci_visibility/telemetry/events.py
Labels: changelog/no-changelog, mergequeue-status: rejected

#11362 chore(ci_visibility): fix itr_skipped tag in settings_response telemetry
  ddtrace/internal/ci_visibility/telemetry/git.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11364 fix(lib-injection): fix guardrail check when sys.argv is not available
  lib-injection/sources/sitecustomize.py
  releasenotes/notes/fix-lib-injection-sys-argv-fefc775a4a262d86.yaml
Labels: backport 2.16

#11378 chore: fix codespell errors in changelog
  CHANGELOG.md
Labels: changelog/no-changelog

#11377 fix(profiling): reduce lock profiler log spam
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-reduce-lock-profiler-log-spam-5931d957ff1becd4.yaml
Labels: Profiling, mergequeue-status: rejected, backport 2.15, backport 2.16, backport 2.17

#11370 chore(lib-injection): fix tracer_version reported with ssi telemetry
  lib-injection/sources/sitecustomize.py
Labels: changelog/no-changelog

#11076 chore(docs): organize configurations.rst
  docs/configuration.rst
Labels: changelog/no-changelog

#11373 ci: reduce API requests in download wheel job
  .gitlab/download-wheels-from-gh-actions.sh
Labels: changelog/no-changelog, backport 2.14, backport 2.15, backport 2.16, backport 2.17

#10877 ci: add suitespec to GitLab
  .circleci/config.templ.yml
  .github/workflows/requirements-locks.yml
  .gitignore
  .gitlab-ci.yml
  .gitlab/package.yml
  .gitlab/testrunner.yml
  .gitlab/tests.yml
  .gitlab/tests/appsec.yml
  .gitlab/tests/ci_visibility.yml
  .gitlab/tests/contrib.yml
  .gitlab/tests/core.yml
  .gitlab/tests/debugging.yml
  .gitlab/tests/llmobs.yml
  .gitlab/tests/profiling.yml
  .gitlab/tests/tracer.yml
  .riot/requirements/196755b.txt
  docker-compose.yml
  riotfile.py
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  scripts/needs_testrun.py
  tests/.suitespec.json
  tests/README.md
  tests/appsec/jobspec.yml
  tests/ci_visibility/jobspec.yml
  tests/contrib/jobspec.yml
  tests/debugging/jobspec.yml
  tests/jobspec.yml
  tests/llmobs/jobspec.yml
Labels: changelog/no-changelog

#11386 chore(llmobs): add tracer version field to llmobs span payload
  ddtrace/llmobs/_writer.py
Labels: changelog/no-changelog

#11341 chore: remove compat.stringify usage from gunicorn test
  tests/contrib/gunicorn/test_gunicorn.py
Labels: changelog/no-changelog

#11393 chore(profiling): fix flaky gunicorn test
  tests/profiling/collector/pprof_utils.py
  tests/profiling_v2/test_gunicorn.py
Labels: changelog/no-changelog, Profiling

#11390 chore(profiling): stack collector tests for libdd and stack v2
  tests/profiling_v2/collector/test_stack.py
Labels: changelog/no-changelog, Profiling, mergequeue-status: in_progress

#11269 chore(ci): add retries for flaky tests
  .gitlab/tests.yml
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11375 chore(ci_visibility): fix line numbers in Python 3.10 code coverage instrumentation
  ddtrace/internal/coverage/instrumentation_py3_10.py
  tests/ci_visibility/test_ci_visibility.py
  tests/coverage/included_path/async_code.py
  tests/coverage/test_coverage_async.py
Labels: changelog/no-changelog

#11374 chore(tracer): remove x-forwarded from ip resolution
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/remove_x-forwarded_from_ip_resolution-d63292c0fda42dd9.yaml
  tests/tracer/test_trace_utils.py
Labels: Tracing

#11272 fix(celery): handle upstream celery patch and propagation during an e…
  ddtrace/contrib/celery/__init__.py
  ddtrace/contrib/internal/celery/constants.py
  ddtrace/contrib/internal/celery/signals.py
  ddtrace/contrib/internal/celery/utils.py
  releasenotes/notes/fix-celery-context-propagation-aa904d748362f2d1.yaml
  tests/contrib/celery/base.py
  tests/contrib/celery/test_integration.py
Labels: mergequeue-status: removed

#11411 ci(asm): appsec_integrations suite improvments
  .circleci/config.templ.yml
  tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
Labels: changelog/no-changelog, CI

#11368 chore(ci): add retry to the run test step for circleci
  .circleci/config.templ.yml
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11246 chore(ci): check if target branch is too old
  .github/workflows/check_old_target_branch.yml
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11352 chore(ci): update description of generate package workflow
  .github/workflows/generate-package-versions.yml
Labels: changelog/no-changelog

#11379 ci: switch repo to use pytest plugin v2
  .gitlab/tests.yml
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/coverage/code.py
  riotfile.py
  tests/internal/test_module.py
Labels: changelog/no-changelog

#11399 chore: extend flaky `until` timestamp for grpc
  tests/contrib/grpc/test_grpc.py
Labels: changelog/no-changelog

#11410 chore: update changelog for version 2.16.2
  CHANGELOG.md
Labels: changelog/no-changelog

#11353 fix(botocore): [SVLS-5973] less noisy span pointers
  ddtrace/_trace/_span_pointer.py
  ddtrace/_trace/telemetry.py
  ddtrace/_trace/utils_botocore/span_pointers/__init__.py
  ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py
  ddtrace/_trace/utils_botocore/span_pointers/s3.py
  ddtrace/_trace/utils_botocore/span_pointers/telemetry.py
  releasenotes/notes/reduce-span-pointer-noise-e1cf01ec581a409c.yaml
  tests/tracer/test_telemetry.py
  tests/tracer/utils_botocore/test_span_pointers.py
Labels: backport 2.16, backport 2.17

#11405 chore(debugger): better no local error message
  ddtrace/debugging/_expressions.py
  tests/debugging/test_debugger.py
  tests/debugging/test_debugger_span_decoration.py
  tests/debugging/test_expressions.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11424 chore(profiling): fix sanitizers on Linux
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
Labels: changelog/no-changelog, Profiling, mergequeue-status: in_progress

#11418 fix(iast): add some modules to the denylist
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/umap-learn-denylist-b7c55f42f2408c24.yaml
Labels: ASM, backport 2.15, backport 2.16, backport 2.17

#11381 fix(lib-injection): ensure sitecustomize.py supports Python 2.7+
  .github/workflows/test_lib_injection.yml
  lib-injection/sources/sitecustomize.py
  releasenotes/notes/fix-lib-injection-version-support-ae2ff3a79ac1f6f2.yaml
Labels: backport 2.16, backport 2.17

#11400 ci: set ulimit -c unlimited for gitlab tests
  .gitlab/testrunner.yml
Labels: changelog/no-changelog, CI

#11187 chore: update Docker Hub reference
  docs/contributing-integrations.rst
Labels: changelog/no-changelog

#11442 chore(ci_visibility): don't incorrectly report tests as new
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_faulty_session.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_mix_pass.json
Labels: changelog/no-changelog

#11420 fix: [SVLS-5953] pointers for deserialized DynamoDB requests
  .riot/requirements/116ff5f.txt
  .riot/requirements/1308524.txt
  .riot/requirements/159f4bb.txt
  .riot/requirements/15e6ff4.txt
  .riot/requirements/15e8745.txt
  .riot/requirements/1793deb.txt
  .riot/requirements/17a3ee7.txt
  .riot/requirements/18d037c.txt
  .riot/requirements/19065a8.txt
  .riot/requirements/1a4f181.txt
  .riot/requirements/1aa24de.txt
  .riot/requirements/1b85047.txt
  .riot/requirements/469c997.txt
  .riot/requirements/58df0ac.txt
  .riot/requirements/64d7755.txt
  .riot/requirements/921bc6c.txt
  ddtrace/_trace/_span_pointer.py
  ddtrace/_trace/utils_botocore/span_pointers/__init__.py
  ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py
  ddtrace/_trace/utils_botocore/span_pointers/s3.py
  releasenotes/notes/fix-span-pointer-deserialized-dynamodb-requests-39b1235a102dab7c.yaml
  riotfile.py
  tests/tracer/utils_botocore/test_span_pointers.py
Labels: backport 2.16, backport 2.17

#11340 chore(ci): order test suite names in jobspec
  tests/contrib/jobspec.yml
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11351 chore(otel): collect telemetry for otel configurations
  ddtrace/settings/_otel_remapper.py
  tests/.suitespec.json
  tests/opentelemetry/test_config.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#11415 fix(grpc.aio): resolve distributed tracing concurrency bug
  ddtrace/contrib/internal/grpc/aio_server_interceptor.py
  releasenotes/notes/grpc-use-ServicerContext-context-to-get-metadata-84c144a247267893.yaml
Labels: backport 2.17

#11408 chore(ci): make the GitLab `testrunner` definition interruptible
  .gitlab-ci.yml
Labels: changelog/no-changelog, mergequeue-status: rejected, backport 2.15, backport 2.16, backport 2.17

#11427 chore: automate updating `version_scheme` in pyproject.toml
  scripts/create_new_release_branch.py
Labels: changelog/no-changelog, mergequeue-status: removed

#11409 chore: use guess-next-dev instead of release-branch-semver [2.17]
  pyproject.toml
Labels: changelog/no-changelog, mergequeue-status: rejected

#11437 ci: use fixtures to reset dd-trace-debug and caplog level
  tests/tracer/test_endpoint_config.py
Labels: changelog/no-changelog

#11200 chore(ci): add more re tests
  benchmarks/bm/iast_fixtures/str_methods_py3.py
  tests/appsec/iast/aspects/test_re_aspects.py
Labels: changelog/no-changelog, ASM

#11453 chore(asm): updates waf and security rules
  ddtrace/appsec/rules.json
  releasenotes/notes/waf_update_to_1.21.0-2f77adaf9ecce679.yaml
  setup.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: ASM

#11414 chore(tests): turn off dogweb CI runs
  .gitlab-ci.yml
  .gitlab/dogfood.yml
Labels: changelog/no-changelog, backport 2.15, backport 2.16, backport 2.17

#11463 chore: update changelog for version 2.16.4
  CHANGELOG.md
Labels: changelog/no-changelog

#11369 chore: extend pyramid flaky test timestamp
  tests/contrib/pyramid/test_pyramid.py
  tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint[ddtrace-run_python_tests_contrib_pyramid_app_app.py].json
Labels: changelog/no-changelog

#11458 chore(service-naming): improve inferred service naming algorithm
  ddtrace/settings/_inferred_base_service.py
  tests/conftest.py
  tests/contrib/gunicorn/test_gunicorn.py
  tests/internal/service_name/test_inferred_base_service.py
  tests/snapshots/tests.contrib.gunicorn.test_gunicorn.test_span_schematization[None-None].json
  tests/snapshots/tests.contrib.gunicorn.test_gunicorn.test_span_schematization[None-v0].json
  tests/snapshots/tests.contrib.gunicorn.test_gunicorn.test_span_schematization[None-v1].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_analytics_with_rate.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_analytics_without_rate.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_single_message.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_with_error[False].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_with_multiple_messages.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_offset.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_only_async_arg.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_message[False].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_message[True].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_service_override.json
Labels: changelog/no-changelog, mergequeue-status: removed, backport 2.17

#11471 chore(profiling): gunicorn test improvements
  tests/profiling_v2/test_gunicorn.py
Labels: changelog/no-changelog, Profiling

#11445 feat: iast execute source metric
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/test_telemetry.py
Labels: changelog/no-changelog, ASM

#11468 chore(iast): add tool to debug iast patched code
  scripts/iast/print_patched_code.py
Labels: changelog/no-changelog, ASM

#11470 chore: upgrade ddsketch/libdatadog to v14.1.0
  src/core/Cargo.lock
  src/core/Cargo.toml
Labels: changelog/no-changelog

#11457 chore(profiling): cmake clean ups
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
Labels: changelog/no-changelog, Profiling, mergequeue-status: rejected

#11452 fix(asm): standalone missing tag
  ddtrace/_trace/processor/__init__.py
  releasenotes/notes/fix_asm_standalone_span_tag-60b38c1d9d2efbaa.yaml
Labels: bug, ASM, backport 2.14, backport 2.15, backport 2.16, backport 2.17

#11485 chore(profiling): make gunicorn app to run shorter
  tests/profiling/gunicorn-app.py
Labels: changelog/no-changelog, Profiling

#11481 chore(profiling): use raw allocator free for traceback buffers
  ddtrace/profiling/collector/_utils.h
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11236 feat(vertexai): [MLOB-1803] add apm tracing for vertex ai
  .github/CODEOWNERS
  .riot/requirements/23eab38.txt
  .riot/requirements/59e23ef.txt
  .riot/requirements/692fe7a.txt
  .riot/requirements/f12fa99.txt
  ddtrace/_monkey.py
  ddtrace/contrib/internal/google_generativeai/_utils.py
  ddtrace/contrib/internal/google_generativeai/patch.py
  ddtrace/contrib/internal/vertexai/_utils.py
  ddtrace/contrib/internal/vertexai/patch.py
  ddtrace/contrib/vertexai/__init__.py
  ddtrace/llmobs/_integrations/__init__.py
  ddtrace/llmobs/_integrations/utils.py
  ddtrace/llmobs/_integrations/vertexai.py
  riotfile.py
  tests/.suitespec.json
  tests/contrib/vertexai/__init__.py
  tests/contrib/vertexai/conftest.py
  tests/contrib/vertexai/test_vertexai.py
  tests/contrib/vertexai/test_vertexai_patch.py
  tests/contrib/vertexai/utils.py
  tests/llmobs/jobspec.yml
  tests/snapshots/tests.contrib.vertexai.test_vertexai.test_vertexai_completion.json
  tests/snapshots/tests.contrib.vertexai.test_vertexai.test_vertexai_completion_error.json
  tests/snapshots/tests.contrib.vertexai.test_vertexai.test_vertexai_completion_multiple_messages.json
  tests/snapshots/tests.contrib.vertexai.test_vertexai.test_vertexai_completion_stream.json
  tests/snapshots/tests.contrib.vertexai.test_vertexai.test_vertexai_completion_stream_error.json
  tests/snapshots/tests.contrib.vertexai.test_vertexai.test_vertexai_completion_stream_tool.json
  tests/snapshots/tests.contrib.vertexai.test_vertexai.test_vertexai_completion_system_prompt.json
  tests/snapshots/tests.contrib.vertexai.test_vertexai.test_vertexai_completion_tool.json
Labels: changelog/no-changelog

#11492 chore(ci): run framework tests nightly instead of on PRs
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, mergequeue-status: removed, backport 2.15, backport 2.16, backport 2.17

#11478 fix(ci_visibility): get default environment from agent when DD_ENV is not set
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci_visibility-get_agent_default_env-bf4a11283dccdf87.yaml
  tests/ci_visibility/api_client/test_ci_visibility_api_client.py
Labels: CI App, mergequeue-status: rejected

#11480 chore(ci_visibility): reset tmppath_result_key fixture if need be
  ddtrace/contrib/pytest/_retry_utils.py
  ddtrace/contrib/pytest/_types.py
Labels: changelog/no-changelog, mergequeue-status: rejected

#11490 fix(iast): add code to filter out ddtrace stuff from dir() on patched modules
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_loader.py
  releasenotes/notes/code-security-patch-dir-54cc85f18e31f45c.yaml
  tests/appsec/appsec_utils.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_add_inplace_aspect_fixtures.py
  tests/appsec/iast/fixtures/ast/other/with_implemented_dir.py
  tests/appsec/iast/fixtures/ast/other/without_implemented_dir.py
  tests/appsec/iast_packages/inside_env_runner.py
Labels: ASM, backport 2.15, backport 2.16, backport 2.17

#11430 chore(crashtracker): add profiler_config tag if profiler enabled
  ddtrace/internal/core/crashtracking.py
  ddtrace/profiling/profiler.py
  ddtrace/settings/profiling.py
  tests/internal/crashtracker/test_crashtracker.py
Labels: changelog/no-changelog, Profiling

#11446 feat(asm): standalone code security
  .github/workflows/system-tests.yml
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  releasenotes/notes/feat-code-security-standalone-0fc5993ded38e83e.yaml
  tests/appsec/appsec/test_asm_standalone.py
  tests/tracer/test_propagation.py
  tests/tracer/test_tracer.py
Labels: ASM

#11505 chore(ci): update rust min version
  setup.py
Labels: changelog/no-changelog, CI

#11469 fix(lib-injection): ensure any user defined sitecustomize.py is loaded after injection
  lib-injection/sources/sitecustomize.py
  releasenotes/notes/fix-lib-injection-user-sitecustomize-4ebc76e1b722490f.yaml
Labels: mergequeue-status: rejected

#11506 chore(telemetry): fix namespace on otel metrics
  ddtrace/settings/_otel_remapper.py
Labels: changelog/no-changelog

#11499 fix(botocore): ensure streamed bedrock spans finish
  ddtrace/contrib/internal/botocore/services/bedrock.py
  releasenotes/notes/fix-bedrock-early-stream-exit-81da39d97fb1b26e.yaml
  tests/contrib/botocore/test_bedrock.py
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_cohere_invoke_stream_multiple_output.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_read_stream_error.json
Labels: backport 2.15, backport 2.16, backport 2.17

#11319 feat(profiling): support dynamic agent url
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/profiler.py
  ddtrace/profiling/utils.py
  releasenotes/notes/profiling-dynamic-agent-url-1f285029201620b8.yaml
  tests/profiling/exporter/test_http.py
  tests/profiling/test_profiler.py
  tests/profiling_v2/exporter/test_ddup.py
Labels: Profiling, mergequeue-status: rejected

#11450 ci: add suitespec to GitLab [backport 2.16]
  .circleci/config.templ.yml
  .github/workflows/requirements-locks.yml
  .gitignore
  .gitlab-ci.yml
  .gitlab/package.yml
  .gitlab/testrunner.yml
  .gitlab/tests.yml
  .gitlab/tests/appsec.yml
  .gitlab/tests/ci_visibility.yml
  .gitlab/tests/contrib.yml
  .gitlab/tests/core.yml
  .gitlab/tests/debugging.yml
  .gitlab/tests/llmobs.yml
  .gitlab/tests/profiling.yml
  .gitlab/tests/tracer.yml
  .riot/requirements/196755b.txt
  docker-compose.yml
  riotfile.py
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  scripts/needs_testrun.py
  tests/.suitespec.json
  tests/README.md
  tests/appsec/jobspec.yml
  tests/ci_visibility/jobspec.yml
  tests/contrib/jobspec.yml
  tests/debugging/jobspec.yml
  tests/jobspec.yml
  tests/llmobs/jobspec.yml
Labels: changelog/no-changelog

#11521 fix(iast): add code to filter out ddtrace stuff from dir() on patched modules [backport 2.15]
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_loader.py
  releasenotes/notes/code-security-patch-dir-54cc85f18e31f45c.yaml
  tests/appsec/appsec_utils.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_add_inplace_aspect_fixtures.py
  tests/appsec/iast/fixtures/ast/other/with_implemented_dir.py
  tests/appsec/iast/fixtures/ast/other/without_implemented_dir.py
  tests/appsec/iast_packages/inside_env_runner.py
Labels: ASM

#11520 chore(iast): check the return value of astpatch_module
  ddtrace/appsec/_iast/__init__.py
  tests/appsec/iast_packages/inside_env_runner.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM, backport 2.15, backport 2.16, backport 2.17

#11507 ci: enable iast standalone system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, ASM, CI

#11413 fix(llmobs): sync and async generators can be decorated
  ddtrace/llmobs/decorators.py
  releasenotes/notes/llmobs-generators-decorating-6b1c4bcf2462d218.yaml
  tests/llmobs/test_llmobs_decorators.py
Labels: backport 2.17

#11522 fix(asm): add global states to ensure patching once
  ddtrace/_monkey.py
  ddtrace/appsec/__init__.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_remoteconfiguration.py
  releasenotes/notes/exploit_prevention_patch_fix-1bdd7540e1d085d8.yaml
  tests/appsec/integrations/test_flask_telemetry.py
  tests/utils.py
Labels: ASM, backport 2.15, backport 2.16, backport 2.17

#11483 chore(tracing): fix some service naming tests that were failing silently
  ddtrace/contrib/internal/bottle/trace.py
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#10750 fix(celery): change out.host tags to point to celery broker
  .riot/requirements/118ee6f.txt
  .riot/requirements/138c2b7.txt
  .riot/requirements/1509aa1.txt
  .riot/requirements/1df4aa0.txt
  .riot/requirements/654f8c0.txt
  .riot/requirements/91a1ee4.txt
  ddtrace/contrib/internal/celery/signals.py
  releasenotes/notes/update-celery-out-host-tag-be8da4f2ab88b4cf.yaml
  riotfile.py
  tests/contrib/celery/base.py
  tests/contrib/celery/test_integration.py
  tests/contrib/celery/test_tagging.py
  tests/contrib/jobspec.yml
Labels: mergequeue-status: in_progress, backport 2.17

#11545 chore(ci_visibility): fix telemetry for events and API requests
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/telemetry/early_flake_detection.py
  ddtrace/internal/ci_visibility/telemetry/events.py
  ddtrace/internal/ci_visibility/telemetry/git.py
  ddtrace/internal/ci_visibility/utils.py
Labels: changelog/no-changelog

#11527 perf(cos): cache user code checks
  ddtrace/debugging/_origin/span.py
  ddtrace/internal/packages.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11549 chore(ci_visibility): fix API telemetry and make ordering stable with better logging
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/telemetry/git.py
Labels: changelog/no-changelog

#11497 chore(tests): fix tz warning
  tests/utils.py
Labels: changelog/no-changelog

#11401 ci: merge suitespec and jobspec
  .circleci/config.templ.yml
  .github/CODEOWNERS
  .gitlab/tests.yml
  docs/contributing-integrations.rst
  docs/contributing-testing.rst
  docs/spelling_wordlist.txt
  hatch.toml
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  scripts/needs_testrun.py
  tests/.suitespec.json
  tests/README.md
  tests/appsec/jobspec.yml
  tests/appsec/suitespec.yml
  tests/ci_visibility/jobspec.yml
  tests/ci_visibility/suitespec.yml
  tests/contrib/jobspec.yml
  tests/contrib/suitespec.yml
  tests/debugging/jobspec.yml
  tests/debugging/suitespec.yml
  tests/jobspec.yml
  tests/llmobs/jobspec.yml
  tests/llmobs/suitespec.yml
  tests/suitespec.py
  tests/suitespec.yml
Labels: changelog/no-changelog

#11552 chore: update changelog for version 2.13 - 2.17 patch releases
  CHANGELOG.md
Labels: changelog/no-changelog

#11451 ci: add suitespec to GitLab [backport 2.15]
  .circleci/config.templ.yml
  .github/workflows/requirements-locks.yml
  .gitignore
  .gitlab-ci.yml
  .gitlab/package.yml
  .gitlab/testrunner.yml
  .gitlab/tests.yml
  .gitlab/tests/appsec.yml
  .gitlab/tests/ci_visibility.yml
  .gitlab/tests/contrib.yml
  .gitlab/tests/core.yml
  .gitlab/tests/debugging.yml
  .gitlab/tests/llmobs.yml
  .gitlab/tests/profiling.yml
  .gitlab/tests/tracer.yml
  .riot/requirements/196755b.txt
  docker-compose.yml
  riotfile.py
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  scripts/needs_testrun.py
  tests/.suitespec.json
  tests/README.md
  tests/appsec/jobspec.yml
  tests/ci_visibility/jobspec.yml
  tests/contrib/jobspec.yml
  tests/debugging/jobspec.yml
  tests/jobspec.yml
  tests/llmobs/jobspec.yml
Labels: changelog/no-changelog

#11566 chore: improve dynamodb pointer config discoverability
  ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py
Labels: changelog/no-changelog

#11421 chore: add support for max items in baggage
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#11565 chore(telemetry): fixes namespace for span pointer metric
  ddtrace/_trace/telemetry.py
Labels: changelog/no-changelog, backport 2.17

#11546 chore(asm): add env var to control stack trace report depth crop
  .github/CODEOWNERS
  .gitlab/benchmarks.yml
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_exploit_prevention/stack_traces.py
  ddtrace/settings/asm.py
  docs/configuration.rst
  releasenotes/notes/max_stack_trace_depth_top_percent-a840b8487674c046.yaml
  tests/telemetry/test_writer.py
Labels: ASM

#11572 test(asm): mark test_cmdi as flaky
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: changelog/no-changelog, ASM

#11580 ci(asm): fix fastapi tests
  hatch.toml
Labels: changelog/no-changelog, ASM, CI, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17

#11588 chore(iast): benchmarks for modulo bytes
  benchmarks/appsec_iast_aspects/config.yaml
  benchmarks/appsec_iast_aspects/functions.py
Labels: changelog/no-changelog, ASM

#11589 chore(iast): benchmarks for modulo bytes
  benchmarks/appsec_iast_aspects/config.yaml
Labels: changelog/no-changelog, ASM

#11563 fix(iast): ssrf vulnerability redacts the url query parameters correctly
  ddtrace/appsec/_iast/_evidence_redaction/_sensitive_handler.py
  ddtrace/appsec/_iast/_evidence_redaction/url_sensitive_analyzer.py
  releasenotes/notes/iast-fix-ssrf-queryparam-redaction-78834d2fedfa6bdf.yaml
  tests/appsec/iast/taint_sinks/test_command_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_header_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_ssrf_redacted.py
Labels: ASM, backport 2.14, backport 2.15, backport 2.16, backport 2.17
