Repository DataDog/dd-trace-py, pull requests merged in 2024-10, with the labels that each got.

#10530 chore(dev): add commit hash to backporting script PR description
  scripts/backport
Labels: changelog/no-changelog

#10880 ci: add system-tests finished job (#10699)
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, backport 2.11, backport 2.12

#10705 chore: update changelog for version 2.13.0
  CHANGELOG.md
Labels: changelog/no-changelog

#10676 fix(celery): close `celery.apply` spans even without after_task_publish, when using apply_async
  ddtrace/contrib/internal/celery/app.py
  ddtrace/contrib/internal/celery/signals.py
  releasenotes/notes/fix-celery-apply-async-span-close-b7a8db188459f5b5.yaml
  tests/contrib/celery/test_integration.py
Labels: backport 2.12, backport 2.13, backport 2.14

#10888 chore: update changelog for version 2.12.1
  CHANGELOG.md
Labels: changelog/no-changelog

#10889 chore: update changelog for version 2.12.2
  CHANGELOG.md
Labels: changelog/no-changelog

#10890 chore: update changelog for version 2.14.1
  CHANGELOG.md
Labels: changelog/no-changelog

#10862 chore: introduce product plugin interface
  ddtrace/bootstrap/preload.py
  ddtrace/internal/products.py
  tests/internal/test_products.py
Labels: changelog/no-changelog

#10820 chore(various): add cmake-format
  ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/_iast/_taint_tracking/tests/CMakeLists.txt
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
  ddtrace/internal/datadog/profiling/cmake/FindClangtidy.cmake
  ddtrace/internal/datadog/profiling/cmake/FindCppcheck.cmake
  ddtrace/internal/datadog/profiling/cmake/FindInfer.cmake
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  hatch.toml
  scripts/.cmake-format
  scripts/cmake-format.sh
Labels: changelog/no-changelog

#10721 chore(telemetry): fix flaky tests
  tests/conftest.py
  tests/telemetry/test_data.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog

#10896 chore: ignore crashtracker binary in git
  .gitignore
Labels: changelog/no-changelog

#10797 chore(otel): fix flakies
  riotfile.py
  tests/opentelemetry/flask_app.py
  tests/opentelemetry/test_config.py
  tests/opentelemetry/test_context.py
  tests/opentelemetry/test_span.py
  tests/opentelemetry/test_trace.py
  tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_ddtrace_run].json
  tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_opentelemetry_instrument].json
Labels: changelog/no-changelog

#10867 ci: add and rename macrobenchmark scenarios
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, ASM, CI

#10898 chore(iast): cformat test file
  ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
Labels: changelog/no-changelog, ASM

#10879 fix(iast): context rework
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_common.hpp
  ddtrace/appsec/_iast/processor.py
  releasenotes/notes/iast-fix-context-rework-3b0f1b54ab4f4156.yaml
  scripts/iast/README
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/test_grpc_iast.py
  tests/appsec/integrations/test_flask_iast_patching.py
  tests/appsec/integrations/test_flask_remoteconfig.py
  tests/appsec/integrations/utils.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: ASM, backport 2.13, backport 2.14

#10894 fix(profiling): code provenance using libdatadog exporter [backport-2.12]
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/code_provenance.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/code_provenance_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/libdatadog_helpers.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/code_provenance.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/code_provenance_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/test/code_provenance.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/test_utils.hpp
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/profiling/profiler.py
  releasenotes/notes/profiling-libdd-code-provenance-37f9e3451b0c532c.yaml
Labels: Profiling

#10895 ci: enable dd merge queue
  repository.datadog.yml
Labels: changelog/no-changelog

#10883 chore(iast): add extra pyobject checks on is_text and new_pyobject_id
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/clean.sh
  ddtrace/appsec/_iast/_taint_tracking/tests/test_index_aspect.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_other.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_stringutils.cpp
Labels: changelog/no-changelog, ASM

#10882 fix(profiling): endpoint profiling for stack v2
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/__init__.py
  ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml
  tests/profiling_v2/collector/test_stack.py
Labels: Profiling, backport 2.12, backport 2.13, backport 2.14

#10839 chore: update changelog for version 2.12.1, 2.12.2, 2.14.0, and 2.14.1
  CHANGELOG.md
Labels: changelog/no-changelog

#10905 chore: update changelog for version 2.14.2
  CHANGELOG.md
Labels: changelog/no-changelog

#10904 fix(iast): context rework [Backport 2.14]
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_common.hpp
  ddtrace/appsec/_iast/processor.py
  releasenotes/notes/iast-fix-context-rework-3b0f1b54ab4f4156.yaml
  scripts/iast/README
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/test_grpc_iast.py
  tests/appsec/integrations/test_flask_iast_patching.py
  tests/appsec/integrations/test_flask_remoteconfig.py
  tests/appsec/integrations/utils.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: ASM

#10913 ci: update the circleci `pre_check` job to run style checks on `.cpp` and `.h` file changes
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/tests/test_other.cpp
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog, mergequeue-status: removed

#10923 chore: change release note type from feature to fix
  releasenotes/notes/iast-feat-iast-telemetry-error-f6ba4a6aadf96ec9.yaml
Labels: changelog/no-changelog, backport 2.13, backport 2.14

#10911 fix(profiling): endpoint profiling for stack v2 [backport-2.14]
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/__init__.py
  ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml
  tests/profiling_v2/collector/test_stack.py
Labels: Profiling

#10909 fix(profiling): endpoint profiling for stack v2 [backport-2.12]
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/__init__.py
  ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml
Labels: Profiling

#10910 fix(profiling): endpoint profiling for stack v2 [backport-2.13]
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/__init__.py
  ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp
  ddtrace/profiling/collector/stack.pyx
  releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml
Labels: Profiling

#10807 chore(profiling): improve SSI behavior and error messages for profiling
  ddtrace/profiling/profiler.py
  releasenotes/notes/profiling-fix-autoinject-failure-48cc7d9a18cd70b9.yaml
Labels: backport 2.11, backport 2.12, backport 2.13, backport 2.14

#10920 chore(ci_visibility): add Early Flake Detection retry logic to core API
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_utils.py
  ddtrace/ext/test_visibility/__init__.py
  ddtrace/ext/test_visibility/_constants.py
  ddtrace/ext/test_visibility/api.py
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/api/_base.py
  ddtrace/internal/ci_visibility/api/_module.py
  ddtrace/internal/ci_visibility/api/_session.py
  ddtrace/internal/ci_visibility/api/_suite.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/telemetry/events.py
  ddtrace/internal/test_visibility/_efd_mixins.py
  ddtrace/internal/test_visibility/_internal_item_ids.py
  ddtrace/internal/test_visibility/_itr_mixins.py
  ddtrace/internal/test_visibility/api.py
  ddtrace/settings/config.py
  tests/ci_visibility/api/README.md
  tests/ci_visibility/api/fake_runner_all_fail.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_suite_level.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_test_level.py
  tests/ci_visibility/api/fake_runner_all_pass.py
  tests/ci_visibility/api/fake_runner_all_skip.py
  tests/ci_visibility/api/fake_runner_efd_all_pass.py
  tests/ci_visibility/api/fake_runner_efd_faulty_session.py
  tests/ci_visibility/api/fake_runner_efd_mix_fail.py
  tests/ci_visibility/api/fake_runner_efd_mix_pass.py
  tests/ci_visibility/api/fake_runner_mix_fail.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_suite_level.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_test_level.py
  tests/ci_visibility/api/fake_runner_mix_pass.py
  tests/ci_visibility/api/test_api_fake_runners.py
  tests/ci_visibility/api/test_internal_test_visibility_api.py
  tests/ci_visibility/api_client/_util.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client_setting_responses.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client_skippable_real_world_responses.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client_skippable_responses.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/test_efd.py
  tests/ci_visibility/util.py
  tests/contrib/pytest/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_faulty_session.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_mix_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_test_level.json
Labels: changelog/no-changelog, CI App, mergequeue-status: removed

#10931 docs: use `$HOME/.asdf/bin` instead of `/usr/local/bin` for installing hatch
  .readthedocs.yml
Labels: changelog/no-changelog

#10937 docs: use `$HOME/.asdf/bin` instead of `/usr/local/bin` for installing hatch [backport 2.12]
  .readthedocs.yml
Labels: changelog/no-changelog

#10936 chore: update changelog for version 2.13.1
  CHANGELOG.md
Labels: changelog/no-changelog

#10938 docs: use `$HOME/.asdf/bin` instead of `/usr/local/bin` for installing hatch [backport 2.10]
  .readthedocs.yml
Labels: changelog/no-changelog

#10939 docs: use `$HOME/.asdf/bin` instead of `/usr/local/bin` for installing hatch [backport 2.11]
  .readthedocs.yml
Labels: changelog/no-changelog

#10887 chore: prefix system tests env var
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#10813 chore(profiling): upgrade libdatadog to v13.1.0
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/libdatadog_checksums.txt
Labels: changelog/no-changelog, Profiling

#10900 refactor: migrate RCM to the product interface
  ddtrace/bootstrap/preload.py
  ddtrace/internal/remoteconfig/product.py
  ddtrace/internal/remoteconfig/worker.py
  pyproject.toml
  tests/internal/remoteconfig/test_remoteconfig.py
Labels: changelog/no-changelog

#10944 chore(ci_visibility): fix module path collection
  ddtrace/contrib/pytest/_utils.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog, curse

#10945 chore: update changelog for version 2.12.3
  CHANGELOG.md
Labels: changelog/no-changelog

#10924 ci: clean up github mq configs and add dd mq configs
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
  .github/workflows/pypa_musllinux_1_2_i686.yml
  .github/workflows/requirements-locks.yml
  .github/workflows/rust-ci.yml
  .github/workflows/system-tests.yml
  .github/workflows/test_frameworks.yml
  .github/workflows/testrunner.yml
  .github/workflows/unit_tests.yml
Labels: changelog/no-changelog

#10951 chore: mypy ignores `dd_wrapper/_deps` directory
  mypy.ini
Labels: changelog/no-changelog, Profiling

#10952 chore(ci): set build parallel level for hatch ddtrace_unit_tests
  hatch.toml
Labels: changelog/no-changelog, CI

#10947 chore(iast): fix all known memleaks in the native module + safety fixes
  .gitignore
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/tests/test_add_aspect.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_common.hpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_index_aspect.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_other.cpp
  scripts/iast/mod_leak_functions.py
Labels: changelog/no-changelog, ASM, backport 2.13, backport 2.14

#10954 chore(ci): parallelize unittest github actions
  .github/workflows/unit_tests.yml
Labels: changelog/no-changelog, CI

#10950 chore(profiling): use FindPython3 with Python3_ROOT_DIR hint from setup.py
  ddtrace/internal/datadog/profiling/build_standalone.sh
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  setup.py
Labels: changelog/no-changelog, Profiling

#10917 chore(pymongo): service name override in pymongo
  ddtrace/contrib/internal/pymongo/client.py
  ddtrace/contrib/internal/pymongo/patch.py
  tests/contrib/pymongo/test.py
Labels: changelog/no-changelog

#10960 chore(ci_visibility): separate pytest outcome processing into its own function
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/test_visibility/api.py
  static-analysis.datadog.yml
Labels: changelog/no-changelog, CI App

#10959 chore(iast): fix all known memleaks in the native module + safety fixes [backport 2.14]
  .gitignore
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/tests/test_add_aspect.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_common.hpp
  scripts/iast/mod_leak_functions.py
Labels: changelog/no-changelog, ASM

#10949 fix(botocore): bedrock cross-region inference model name does not throw
  ddtrace/contrib/internal/botocore/services/bedrock.py
  releasenotes/notes/botocore-bedrock-cross-region-inference-model-fix-179b7f1ddd6e8e02.yaml
  tests/contrib/botocore/bedrock_cassettes/anthropic_message_invoke.yaml
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/botocore/test_bedrock_llmobs.py
Labels: backport 2.13, backport 2.14

#10955 ci: enable code origin for spans in django profile
  .github/workflows/django-overhead-profile.yml
Labels: changelog/no-changelog

#10964 chore(ci): fix alpine test
  .gitlab-ci.yml
Labels: changelog/no-changelog, CI

#10961 chore(iast): remove IAST deny list elements
  ddtrace/appsec/_iast/_ast/ast_patching.py
Labels: changelog/no-changelog, ASM

#10841 chore(di): guard against mutable module container
  ddtrace/debugging/_function/discovery.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#10902 chore(iast): improve iast scripts
  .gitlab/tests/appsec.yml
  ddtrace/appsec/_iast/__init__.py
  ddtrace/internal/module.py
  hatch.toml
  scripts/iast/README
  scripts/iast/leak_functions.py
  scripts/iast/mod_leak_functions.py
  scripts/iast/requirements.txt
  scripts/iast/run_memory.sh
  scripts/iast/run_memray.sh
  scripts/iast/run_references.sh
  scripts/iast/test_references.py
  tests/appsec/iast_aggregated_memcheck/test_aggregated_memleaks.py
Labels: changelog/no-changelog, ASM

#10962 chore(profiling): update relnote for endpoint stack v2
  releasenotes/notes/profiling-fix-stack-v2-endpoint-82a1e26366166b8d.yaml
Labels: changelog/no-changelog, Profiling, backport 2.12, backport 2.13, backport 2.14

#10863 chore(telemetry): decouple telemetry writer from global config
  ddtrace/_monkey.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/internal/agent.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/data.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/_core.py
  ddtrace/settings/asm.py
  ddtrace/settings/config.py
  ddtrace/settings/crashtracker.py
  ddtrace/settings/dynamic_instrumentation.py
  ddtrace/settings/exception_replay.py
  ddtrace/settings/peer_service.py
  ddtrace/settings/profiling.py
  ddtrace/settings/symbol_db.py
  tests/conftest.py
  tests/integration/test_settings.py
  tests/telemetry/test_writer.py
  tests/tracer/test_global_config.py
Labels: changelog/no-changelog

#10940 chore(profiling): apple silicon mac builds for libdatadog
  .github/workflows/unit_tests.yml
  .gitignore
  ddtrace/internal/datadog/profiling/build_standalone.sh
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/fetch_libdatadog.sh
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/include/stack_renderer.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  setup.py
Labels: changelog/no-changelog, Profiling

#10719 chore(llmobs): add sampling for ragas skeleton code
  ddtrace/llmobs/_evaluators/runner.py
  ddtrace/llmobs/_evaluators/sampler.py
  ddtrace/llmobs/_trace_processor.py
  tests/llmobs/_utils.py
  tests/llmobs/conftest.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_evaluator_runner.send_score_metric.yaml
  tests/llmobs/test_llmobs_evaluator_runner.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog

#10943 refactor(di): migrate to the product interface
  ddtrace/bootstrap/preload.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_products/__init__.py
  ddtrace/debugging/_products/code_origin/__init__.py
  ddtrace/debugging/_products/code_origin/span.py
  ddtrace/debugging/_products/dynamic_instrumentation.py
  ddtrace/debugging/_products/exception_replay.py
  ddtrace/internal/symbol_db/__init__.py
  ddtrace/internal/symbol_db/product.py
  pyproject.toml
  tests/debugging/exploration/debugger.py
  tests/debugging/test_api.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#10899 chore(asm): refactor replacing old asm_request context by core.context
  ddtrace/_trace/trace_handlers.py
  ddtrace/appsec/__init__.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/contrib/internal/asgi/middleware.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/flask/patch.py
  ddtrace/contrib/internal/starlette/patch.py
  ddtrace/contrib/internal/wsgi/wsgi.py
  ddtrace/internal/core/__init__.py
  ddtrace/internal/utils/__init__.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_appsec_trace_utils.py
  tests/appsec/appsec/test_asm_request_context.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/utils.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/contrib/fastapi/test_fastapi_appsec.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog, ASM

#10850 chore: [SVLS-5265] add span links to encoded spans
  ddtrace/internal/encoding.py
  tests/integration/test_encoding.py
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog

#10978 chore(iast): native str aspect
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectStr.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectStr.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/_aspects_exports.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/_taint_tracking/tests/test_common.hpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_str_aspect.cpp
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM

#10919 ci: always run system tests [backport 2.13]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#10992 ci: add timeout minutes to `sanic` and `starlette` suites
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#10994 fix(profiling): explicitly link with thread library
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Labels: Profiling, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11001 fix(profiling): explicitly link with thread library [backport-2.15]
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Labels: Profiling

#11002 fix(profiling): explicitly link with thread library [backport-2.14]
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Labels: Profiling

#11003 fix(profiling): explicitly link with thread library [backport-2.13]
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Labels: Profiling

#11004 fix(profiling): explicitly link with thread library [backport-2.12]
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  releasenotes/notes/profiling-pthread-aarch64-d4548fd1842d0665.yaml
Labels: Profiling

#11005 test(asm): add priority test
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#11007 chore(asm): update security rules
  ddtrace/appsec/rules.json
  releasenotes/notes/security_rule_update_1.13.1-374c18e4f0a8c338.yaml
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: ASM

#11008 chore: rearrange botocore span pointer code
  ddtrace/_trace/utils_botocore/span_pointers/__init__.py
  ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py
  ddtrace/_trace/utils_botocore/span_pointers/s3.py
  tests/tracer/utils_botocore/test_span_pointers.py
Labels: changelog/no-changelog

#10948 chore(configurations): reduce the size of the programatic api
  ddtrace/_monkey.py
  ddtrace/_trace/tracer.py
  ddtrace/bootstrap/preload.py
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/contrib/internal/aiohttp/middlewares.py
  ddtrace/contrib/internal/pyramid/trace.py
  ddtrace/contrib/internal/tornado/handlers.py
  ddtrace/contrib/trace_utils.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/utils.py
  ddtrace/internal/debug.py
  ddtrace/internal/processor/stats.py
  ddtrace/internal/writer/writer.py
  ddtrace/propagation/http.py
  ddtrace/settings/config.py
  ddtrace/settings/integration.py
  releasenotes/notes/deprecate-public-config-attrs-744b806a66d96da4.yaml
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/pyramid/utils.py
  tests/integration/test_integration.py
  tests/integration/test_settings.py
  tests/integration/test_trace_stats.py
  tests/internal/test_settings.py
  tests/tracer/test_env_vars.py
  tests/tracer/test_propagation.py
  tests/tracer/test_settings.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog

#11015 fix(iast): partial matches on function names should not be patched
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/iast-aspects-partial-matches-f43dc04584ca6788.yaml
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/fixtures/ast/other/globals_builtin.py
Labels: ASM, backport 2.11, backport 2.12, backport 2.13, backport 2.14

#11016 chore(asm): waf update to 1.20.0
  setup.py
  tests/appsec/appsec/test_processor.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#11022 chore(iast): simplify test, add comment
  tests/appsec/iast/_ast/test_ast_patching.py
Labels: changelog/no-changelog, ASM

#11027 fix(iast): re.finditer aspect error
  benchmarks/bm/iast_fixtures/str_methods.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/iast-fix-re-finditer-aspect-8925b30073169222.yaml
  tests/appsec/app.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast_packages/packages/pkg_python_multipart.py
  tests/appsec/iast_packages/test_packages.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: ASM, backport 2.13, backport 2.14, backport 2.15

#11009 chore(tracing): disallow multiple storage of spans on executioncontext objects in _start_span
  ddtrace/_trace/trace_handlers.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/contrib/internal/flask/patch.py
Labels: changelog/no-changelog

#11025 chore(profiling): pass python3 root dir from standalone build script
  ddtrace/internal/datadog/profiling/build_standalone.sh
Labels: changelog/no-changelog, Profiling

#11017 fix(iast): partial matches on function names should not be patched [backport 2.11]
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/iast-aspects-partial-matches-f43dc04584ca6788.yaml
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/fixtures/ast/other/globals_builtin.py
Labels: ASM

#11037 chore(profiling): mypy ignores python files in native build dir
  mypy.ini
Labels: changelog/no-changelog, Profiling

#11024 fix(profiling): stack v2 properly tracks asyncio tasks
  ddtrace/internal/datadog/profiling/stack_v2/include/sampler.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/profiling/_asyncio.py
  releasenotes/notes/profiling-stack-v2-asyncio-task-4f9ead040829f2f5.yaml
  tests/profiling_v2/collector/test_stack_asyncio.py
  tests/profiling_v2/collector/test_threading.py
Labels: Profiling

#10953 chore: update changelog for version 2.14.3
  CHANGELOG.md
Labels: changelog/no-changelog

#11035 chore: fix notebook bug with release script
  scripts/release.py
Labels: changelog/no-changelog

#11036 fix(ci): manual backport of the new codeowners github actions definition
  .github/workflows/codeowners.yml
Labels: changelog/no-changelog

#11013 ci: exception replay benchmark scenario
  benchmarks/django_simple/app.py
  benchmarks/django_simple/config.yaml
  benchmarks/django_simple/gunicorn.conf.py
  benchmarks/django_simple/scenario.py
  benchmarks/django_simple/utils.py
Labels: changelog/no-changelog

#11044 fix(llmobs): don't drop IO annotations equal to zero
  ddtrace/llmobs/_llmobs.py
  releasenotes/notes/fix-numeric-annotations-7cf06b5ceb615282.yaml
  tests/llmobs/test_llmobs_service.py
Labels: backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11042 chore(iast): fix some range offsets in some aspects
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#11031 chore(iast): remove DD_IAST_ENABLED env var usage
  ddtrace/_monkey.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_utils.py
  ddtrace/bootstrap/preload.py
  tests/appsec/iast/test_loader.py
Labels: changelog/no-changelog, ASM, backport 2.15

#11000 fix(elasticsearch): set tags on span, regardless of sampling
  ddtrace/contrib/internal/elasticsearch/patch.py
  releasenotes/notes/fix-elasticsearch-always-populate-span-tags-c2a212ec706b3f4b.yaml
Labels: backport 2.13, backport 2.14, backport 2.15

#10985 fix(flare): handle non-dict AGENT_CONFIG products from RC
  ddtrace/internal/flare/_subscribers.py
  ddtrace/internal/flare/flare.py
  ddtrace/internal/flare/handler.py
  releasenotes/notes/fix-tracer-flare-e4003d01b434267a.yaml
  tests/internal/test_tracer_flare.py
Labels: backport 2.10, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11012 chore(core): core update for span management
  ddtrace/_trace/trace_handlers.py
  ddtrace/_trace/utils_redis.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/contrib/internal/asgi/middleware.py
  ddtrace/contrib/internal/botocore/patch.py
  ddtrace/contrib/internal/botocore/services/bedrock.py
  ddtrace/contrib/internal/botocore/services/kinesis.py
  ddtrace/contrib/internal/botocore/services/sqs.py
  ddtrace/contrib/internal/botocore/services/stepfunctions.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/flask/patch.py
  ddtrace/contrib/internal/flask/wrappers.py
  ddtrace/contrib/internal/wsgi/wsgi.py
  ddtrace/contrib/rq/__init__.py
  ddtrace/internal/core/__init__.py
  tests/internal/test_context_events_api.py
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog

#11038 chore: update changelog for version 2.11.7
  CHANGELOG.md
Labels: changelog/no-changelog

#10987 chore(telemetry): update config names and values
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  tests/integration/test_settings.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#11053 chore(iast): separate iast and asm listens
  ddtrace/appsec/__init__.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/contrib/internal/fastapi/patch.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/test_grpc_iast.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/test_flask_telemetry.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#11085 chore(ci): bump riot version for 3.7 compatibility issues
  .circleci/config.templ.yml
  .circleci/config.yml
  .github/workflows/generate-package-versions.yml
  .github/workflows/requirements-locks.yml
  .gitlab/package.yml
  .gitlab/tests.yml
  hatch.toml
  scripts/ddtest
Labels: changelog/no-changelog, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11084 chore(iast): propagate python executable
  setup.py
Labels: changelog/no-changelog, ASM, backport 2.15

#11079 chore(iast): report iast enabled metric based on environment variable
  ddtrace/appsec/_iast/_iast_request_context.py
Labels: changelog/no-changelog, ASM

#11097 test(ci): iast prechecks
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#11077 chore(asm): add metadata to rc data pass to the WAF
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_remoteconfiguration.py
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#11082 chore(di): clean up run module logic
  ddtrace/debugging/_debugger.py
  ddtrace/internal/module.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11099 chore(iast): restore Match
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#11091 chore(ci): bump riot version for 3.7 compatibility issues [backport 2.13]
  .circleci/config.templ.yml
  .circleci/config.yml
  .github/workflows/generate-package-versions.yml
  .github/workflows/requirements-locks.yml
  .gitlab/package.yml
  .gitlab/tests.yml
  hatch.toml
  scripts/ddtest
Labels: changelog/no-changelog

#11092 chore(ci): bump riot version for 3.7 compatibility issues [backport 2.14]
  .circleci/config.templ.yml
  .circleci/config.yml
  .github/workflows/generate-package-versions.yml
  .github/workflows/requirements-locks.yml
  .gitlab/package.yml
  .gitlab/tests.yml
  hatch.toml
  scripts/ddtest
Labels: changelog/no-changelog

#11103 chore(asm): add small fix for span in IASTEnvironment
  ddtrace/appsec/_iast/_iast_request_context.py
Labels: changelog/no-changelog, ASM

#11104 docs: pin envier dependency
  hatch.toml
Labels: changelog/no-changelog

#11102 chore(asm): update libddwaf to 1.20.1
  setup.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM, backport 2.15

#11055 chore(iast): add stringio read aspect test
  tests/appsec/iast/aspects/test_stringio.py
Labels: changelog/no-changelog, ASM

#11106 chore(ci): bump riot version and pin virtualenv==20.26.6 for hatch use with python3.7 [2.11]
  .circleci/config.templ.yml
  .circleci/config.yml
  .github/workflows/requirements-locks.yml
  .github/workflows/unit_tests.yml
  hatch.toml
  scripts/ddtest
Labels: changelog/no-changelog

#11101 chore(onboarding): fix condition to enable SSI telemetry
  lib-injection/sources/sitecustomize.py
Labels: changelog/no-changelog

#11107 chore(iast): restore Match tests
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#11110 chore(asm): finalize refactor
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_handlers.py
  ddtrace/contrib/internal/asgi/middleware.py
  tests/appsec/appsec/test_appsec_trace_utils.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/utils.py
Labels: changelog/no-changelog, ASM

#11096 chore(iast): disable test packages tests
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#11120 chore(iast): propagation error in replace aspect
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_replace_aspect.py
Labels: changelog/no-changelog, ASM, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11052 chore(telemetry): fix flaky tests round 2
  tests/conftest.py
  tests/integration/test_settings.py
  tests/runtime/test_runtime_metrics_api.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#11018 fix(iast): partial matches on function names should not be patched [backport 2.12]
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/iast-aspects-partial-matches-f43dc04584ca6788.yaml
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/fixtures/ast/other/globals_builtin.py
Labels: ASM

#11019 fix(iast): partial matches on function names should not be patched [backport 2.13]
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/iast-aspects-partial-matches-f43dc04584ca6788.yaml
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/fixtures/ast/other/globals_builtin.py
Labels: ASM

#11126 chore(ci): iast, reduce the number iterations in test_aggregated_leaks
  tests/appsec/iast_aggregated_memcheck/test_aggregated_memleaks.py
Labels: changelog/no-changelog, ASM

#11111 chore(iast): update header injection exclusions
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#11132 chore(ci): update `beautifulsoup` framework test to use local `ddtrace` not PyPI latest
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 2.13, backport 2.14, backport 2.15

#11140 chore: unbreak moved private function imports
  ddtrace/_trace/utils_botocore/span_pointers/__init__.py
Labels: changelog/no-changelog, backport 2.15

#11134 chore(profiling): add gunicorn test for stack v2
  tests/profiling_v2/test_gunicorn.py
Labels: changelog/no-changelog, Profiling

#11114 chore(iast): restore Match tests
  scripts/iast/leak_functions.py
  scripts/iast/mod_leak_functions.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#11137 chore(asm): move waf info report to asm_context and add return code in ddwaf_result
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_processor.py
  tests/appsec/appsec/test_processor.py
Labels: changelog/no-changelog, ASM

#11100 fix(di): use enum value for evaluate_at property
  ddtrace/debugging/_probe/remoteconfig.py
  releasenotes/notes/fix-span-decoration-probe-timing-dc4ce0664fa645b9.yaml
Labels: Dynamic Instrumentation, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11135 chore(iast): fix stringio and bytesio aspects range offsets
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_io_aspects.py
  tests/appsec/iast/aspects/test_stringio.py
Labels: changelog/no-changelog, ASM

#11118 perf(di): no path resolution in code origin for spans
  ddtrace/debugging/_origin/span.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11143 chore(asm): change deprecation logic for default settings
  ddtrace/settings/asm.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#11123 chore(ci): add env vars to control macrobenchmark warm up
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI, mergequeue-status: removed

#11061 chore(tracing): add kafka cluster id to spans and DSM metrics
  .gitlab/services.yml
  ddtrace/contrib/internal/kafka/patch.py
  ddtrace/ext/kafka.py
  ddtrace/internal/datastreams/kafka.py
  docker-compose.yml
  tests/contrib/kafka/meta.properties
  tests/contrib/kafka/test_kafka.py
  tests/snapshots/tests.contrib.kafka.test_kafka.test_analytics_with_rate.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_analytics_without_rate.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_single_message.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_with_error[False].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_consume_with_multiple_messages.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_offset.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_commit_with_only_async_arg.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_message[False].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_message[True].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_schematized_span_service_and_operation[None-None].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_schematized_span_service_and_operation[None-mysvc].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_schematized_span_service_and_operation[v0-None].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_schematized_span_service_and_operation[v0-mysvc].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_schematized_span_service_and_operation[v1-None].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_schematized_span_service_and_operation[v1-mysvc].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_service_override.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_service_override_env_var.json
Labels: changelog/no-changelog

#11154 chore(ci): remove python 3.9 from appsec_aggregated_leak_testing
  .gitlab/tests/appsec.yml
  hatch.toml
Labels: changelog/no-changelog, ASM

#11138 chore(ci): fix django snapshot timeouts
  tests/appsec/appsec_utils.py
  tests/contrib/django/test_django_snapshots.py
  tests/internal/test_module.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/utils.py
  tests/webclient.py
Labels: changelog/no-changelog

#11164 fix(profiling): handle `Span`s with `None` span type for stack v2 endpoint profiling
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  releasenotes/notes/profiling-stack-v2-endpoint-span-type-none-48a1196296be3742.yaml
  tests/profiling_v2/collector/test_stack.py
Labels: Profiling, backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11139 refactor(profiling): remove pytest.mark.subprocess from v2/test_stack.py
  ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  tests/profiling/collector/pprof_utils.py
  tests/profiling_v2/collector/test_stack.py
Labels: changelog/no-changelog, Profiling

#11071 chore: update changelog for version 2.11.8, 2.12.4, 2.13.2, and 2.14.4
  CHANGELOG.md
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11170 chore(iast): copy_ranges_to_string errors
  .gitignore
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#11155 chore(iast): remove DD_IAST_TELEMETRY_VERBOSITY env var usage
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/settings/asm.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#11173 fix(ci_visibility): strip out comments in codeowners
  ddtrace/internal/codeowners.py
  releasenotes/notes/ci_visibility-fix_codeowners_including_comments-82d9cb733a2c7285.yaml
  tests/internal/test_codeowners.py
Labels: backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11175 fix(ci_visibility): avoid git tracebacks when .git dir is absent
  ddtrace/internal/ci_visibility/git_client.py
  releasenotes/notes/ci_visibility-fix_logged_errors_when_gitless-66a6cb3245314f3e.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: backport 2.12, backport 2.13, backport 2.14, backport 2.15

#11112 chore(ci_visibility): add Early Flake Detection to pytest v2 plugin
  ddtrace/contrib/pytest/_efd_utils.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_retry_utils.py
  ddtrace/contrib/pytest/_utils.py
  ddtrace/contrib/pytest/constants.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/internal/ci_visibility/api/_base.py
  ddtrace/internal/ci_visibility/api/_session.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/test_visibility/_efd_mixins.py
  hatch.toml
  tests/ci_visibility/api/fake_runner_efd_all_pass.py
  tests/ci_visibility/api/fake_runner_efd_faulty_session.py
  tests/ci_visibility/api/fake_runner_efd_mix_fail.py
  tests/ci_visibility/api/fake_runner_efd_mix_pass.py
  tests/ci_visibility/test_efd.py
  tests/ci_visibility/util.py
  tests/contrib/pytest/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest/test_pytest_efd.py
Labels: changelog/no-changelog, CI App

#11153 refactor(di): encapsulate common signal code
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_exception/replay.py
  ddtrace/debugging/_expressions.py
  ddtrace/debugging/_origin/span.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_signal/collector.py
  ddtrace/debugging/_signal/metric_sample.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_signal/snapshot.py
  ddtrace/debugging/_signal/tracing.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/signal/test_collector.py
  tests/debugging/signal/test_model.py
  tests/debugging/test_debugger.py
  tests/debugging/test_debugger_span_decoration.py
  tests/debugging/test_encoding.py
  tests/debugging/utils.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11174 fix(profiling): handle `Span`s with `None` span type for stack v2 endpoint profiling [backport 2.12]
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  releasenotes/notes/profiling-stack-v2-endpoint-span-type-none-48a1196296be3742.yaml
Labels: Profiling

#11181 chore(asm): refactor for waf telemetry logs
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/contrib_appsec/conftest.py
Labels: changelog/no-changelog, ASM

#11176 fix(profiling): handle `Span`s with `None` span type for stack v2 endpoint profiling [backport 2.13]
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  releasenotes/notes/profiling-stack-v2-endpoint-span-type-none-48a1196296be3742.yaml
Labels: Profiling

#11201 chore(ci_visibility): fix inadequate pytest test and fix broken git check
  ddtrace/internal/ci_visibility/git_client.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog

#11180 chore(iast): make debug propagation tool work in propagation on tests
  tests/appsec/appsec_utils.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#11167 fix(profiling): fix data race when accessing span for thread
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/include/thread_span_links.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp
  ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/test/thread_span_links.cpp
  releasenotes/notes/profiling-fix-data-race-segfault-b14f59c06c6bf9ed.yaml
Labels: Profiling, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16

#11220 chore(ci): remove django circleci test suite
  .circleci/config.templ.yml
Labels: changelog/no-changelog, backport 2.13, backport 2.14, backport 2.15, backport 2.16

#11199 chore(ci): iast packages tests error
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#11203 feat(asm): add session fingerprinting support
  ddtrace/appsec/_capabilities.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_trace_utils.py
  releasenotes/notes/session_fingerprint-b20cefb1ae3e24dc.yaml
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM
