Repository DataDog/dd-trace-py, pull requests merged in 2024-01, with the labels that each got.

#7998 chore(iast): cmdi performance
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
Labels: changelog/no-changelog, ASM

#8002 fix(asm): fix boolean property reporting for appsec
  ddtrace/appsec/_trace_utils.py
  releasenotes/notes/fix_bool_report_for_appsec_custom_event-da5503b0fbb78c95.yaml
Labels: bug, ASM

#7975 ci: randomize the execution order of some internal test suites
  .riot/requirements/1182da4.txt
  .riot/requirements/11eae4e.txt
  .riot/requirements/12bdba7.txt
  .riot/requirements/12e2d81.txt
  .riot/requirements/132e262.txt
  .riot/requirements/1334ce5.txt
  .riot/requirements/1648e81.txt
  .riot/requirements/1658f56.txt
  .riot/requirements/16b5f25.txt
  .riot/requirements/16c1c69.txt
  .riot/requirements/17148ee.txt
  .riot/requirements/17a868e.txt
  .riot/requirements/17ab061.txt
  .riot/requirements/1855290.txt
  .riot/requirements/1ab1452.txt
  .riot/requirements/1cfc8b7.txt
  .riot/requirements/1d5f061.txt
  .riot/requirements/1d8045a.txt
  .riot/requirements/1e08b64.txt
  .riot/requirements/2ccc283.txt
  .riot/requirements/2d78510.txt
  .riot/requirements/2f90c77.txt
  .riot/requirements/35260a3.txt
  .riot/requirements/4dc1bf8.txt
  .riot/requirements/5567735.txt
  .riot/requirements/68d8bc6.txt
  .riot/requirements/79f2ab7.txt
  .riot/requirements/99b3832.txt
  .riot/requirements/bceb0bd.txt
  .riot/requirements/c74560f.txt
  .riot/requirements/d0355c2.txt
  .riot/requirements/d812b5f.txt
  .riot/requirements/dbc507c.txt
  .riot/requirements/e45d6bf.txt
  .riot/requirements/e98519b.txt
  .riot/requirements/ee0b75a.txt
  .riot/requirements/f220563.txt
  .riot/requirements/f65661f.txt
  .riot/requirements/fd2d2d1.txt
  ddtrace/internal/core/__init__.py
  riotfile.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_connector.py
  tests/internal/service_name/test_extra_services_names.py
  tests/internal/test_context_events_api.py
Labels: changelog/no-changelog

#7997 chore(iast): redundant logs
  ddtrace/appsec/_iast/_loader.py
  ddtrace/bootstrap/preload.py
Labels: changelog/no-changelog, ASM

#7957 chore: deprecate the span= arguments on ExecutionContext methods
  .github/workflows/test_frameworks.yml
  ddtrace/internal/core/__init__.py
Labels: changelog/no-changelog

#8007 fix(ci): telemetry test
  .riot/requirements/1153ad9.txt
  .riot/requirements/118cb50.txt
  .riot/requirements/135aac0.txt
  .riot/requirements/15235b0.txt
  .riot/requirements/17a929f.txt
  .riot/requirements/427c22a.txt
  riotfile.py
Labels: changelog/no-changelog, CI

#8010 fix(pytest): --no-cov precedence
  ddtrace/contrib/pytest/plugin.py
  releasenotes/notes/pytest-nocov-7f79128e1562e033.yaml
  tests/contrib/pytest/test_pytest.py
Labels: backport 2.2, backport 2.3, backport 2.4

#8012 docs: fix broken release notes link in changelog document
  CHANGELOG.md
Labels: changelog/no-changelog

#7786 refactor(debugging): support @exception in expressions
  ddtrace/debugging/_signal/model.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8009 chore(botocore): refactor botocore integration
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/sqs.py
  ddtrace/contrib/botocore/utils.py
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#8022 ci: fix a few broken tests
  tests/contrib/aws_lambda/test_aws_lambda.py
  tests/contrib/redis/test_redis_cluster_asyncio.py
Labels: changelog/no-changelog

#8023 ci: fix a few broken tests
  tests/contrib/redis/test_redis_cluster_asyncio.py
Labels: changelog/no-changelog

#8026 ci: fix missed version lock in grpc_aio tests
  .riot/requirements/1ec1f44.txt
  .riot/requirements/2a84086.txt
  .riot/requirements/46621c4.txt
  .riot/requirements/ed2f19c.txt
  .riot/requirements/ede4798.txt
  riotfile.py
Labels: changelog/no-changelog

#8025 ci: avoid testing with an unsupported version of urllib3
  .riot/requirements/171fa34.txt
  .riot/requirements/1ba4b57.txt
  riotfile.py
Labels: changelog/no-changelog

#8020 chore(appsec): reorganize integration tests
  tests/appsec/appsec_utils.py
  tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
  tests/appsec/integrations/test_flask_remoteconfig.py
  tests/appsec/integrations/test_flask_telemetry.py
  tests/appsec/integrations/test_gunicorn_handlers.py
Labels: changelog/no-changelog, ASM

#8018 chore(asm): remove flakyness for a telemetry test
  tests/conftest.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, CI

#8030 ci(iast): temporary fix for flaky test
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM, CI

#8031 refactor(iast): fix asm request context usage for iast
  ddtrace/appsec/_asm_request_context.py
Labels: changelog/no-changelog, ASM, backport 2.4

#8033 ci(flaky): add flaky decorator to failing tests
  tests/contrib/asyncpg/test_asyncpg.py
  tests/contrib/aws_lambda/test_aws_lambda.py
  tests/contrib/django/test_django.py
  tests/contrib/django/test_django_snapshots.py
  tests/contrib/httpx/test_httpx.py
  tests/contrib/kafka/test_kafka.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/redis/test_redis_asyncio.py
  tests/contrib/wsgi/test_wsgi.py
  tests/opentelemetry/test_context.py
  tests/opentelemetry/test_span.py
  tests/opentelemetry/test_trace.py
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog, CI

#8027 ci: ignore flaky field in django snapshots
  tests/contrib/django/test_django_snapshots.py
Labels: changelog/no-changelog

#8013 docs: tell typecheckers like pyright that Config.__getattr__ returns Any type
  ddtrace/settings/config.py
Labels: changelog/no-changelog

#8038 chore(ci): add itr:noskip check in needs_testrun.py
  scripts/needs_testrun.py
Labels: changelog/no-changelog, CI

#8037 ci: mark httpx flaky test
  tests/contrib/httpx/test_httpx.py
Labels: changelog/no-changelog

#8021 chore(asm): remove appsec from trace utils
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/trace_utils/__init__.py
  ddtrace/contrib/trace_utils.py
Labels: changelog/no-changelog, ASM

#8024 ci: mark a test that sporadically causes others in the suite to fail
  tests/contrib/wsgi/test_wsgi.py
Labels: changelog/no-changelog, CI

#8044 ci: remove a bunch of flaky marks by fixing tests
  tests/contrib/asyncio/test_tracer_safety.py
  tests/contrib/logging/test_logging.py
  tests/contrib/pytest_bdd/test_pytest_bdd.py
  tests/contrib/snowflake/test_snowflake.py
  tests/internal/test_utils_http.py
  tests/utils.py
Labels: changelog/no-changelog

#8052 ci(wsgi): actually skip executing the problematic test instead of just xpassing it
  tests/contrib/wsgi/test_wsgi.py
Labels: changelog/no-changelog

#7949 fix(context): ensures all fields in Context are picklable
  ddtrace/context.py
  releasenotes/notes/make-span-links-pickable-d57b92508f5d3a74.yaml
  tests/tracer/test_context.py
  tests/tracer/test_propagation.py
Labels: backport 2.3, backport 2.4

#8041 chore(llmobs): refactor log/llmobs writer startup, configuration options
  ddtrace/contrib/_trace_utils_llm.py
  ddtrace/contrib/langchain/patch.py
  ddtrace/contrib/openai/patch.py
Labels: changelog/no-changelog

#8036 ci(flaky): skip more flaky tests
  tests/appsec/appsec/test_processor.py
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/httpx/test_httpx.py
  tests/contrib/kafka/test_kafka.py
  tests/contrib/redis/test_redis_asyncio.py
  tests/contrib/vertica/test_vertica.py
  tests/opentelemetry/test_span.py
  tests/opentelemetry/test_trace.py
Labels: changelog/no-changelog, CI

#8005 ci: delay expiration for flaky tests
  tests/appsec/integrations/test_flask_remoteconfig.py
  tests/appsec/integrations/test_flask_telemetry.py
  tests/contrib/asyncio/test_tracer_safety.py
  tests/contrib/django/test_django_snapshots.py
  tests/contrib/flask/test_flask_snapshot.py
  tests/contrib/gunicorn/test_gunicorn.py
  tests/contrib/kafka/test_kafka.py
  tests/contrib/pyramid/test_pyramid.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/test_debugger.py
  tests/telemetry/test_writer.py
  tests/tracer/runtime/test_metric_collectors.py
Labels: changelog/no-changelog, CI

#7992 chore(iast): add sqli integration tests
  .circleci/config.templ.yml
  .riot/requirements/1ce36b6.txt
  riotfile.py
  tests/.suitespec.json
  tests/appsec/appsec_utils.py
  tests/appsec/iast_tdd_propagation/flask_orm_app.py
  tests/appsec/iast_tdd_propagation/peewee_impl.py
  tests/appsec/iast_tdd_propagation/pony_impl.py
  tests/appsec/iast_tdd_propagation/sqlalchemy_impl.py
  tests/appsec/iast_tdd_propagation/sqlite_impl.py
  tests/appsec/iast_tdd_propagation/sqliteframe_impl.py
  tests/appsec/iast_tdd_propagation/test_flask_orm.py
  tests/appsec/iast_tdd_propagation/tortoise_impl.py
  tests/appsec/iast_tdd_propagation/tortoise_models.py
Labels: changelog/no-changelog, ASM

#7972 ci: fix macos builds [backport 1.20]
  .github/workflows/build_python_3.yml
  pyproject.toml
  setup.py
Labels: changelog/no-changelog, CI

#8057 chore(asm): less appsec imports
  ddtrace/appsec/_utils.py
Labels: changelog/no-changelog, ASM

#8070 ci: pin trio for starlette (#8058) [backport 2.4]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#8072 ci: pin trio for starlette (#8058) [backport 2.2]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#8071 ci: pin trio for starlette (#8058) [backport 2.3]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#8074 fix(asm): do not imply the callback is registered
  ddtrace/contrib/django/patch.py
Labels: changelog/no-changelog, ASM

#8076 ci: skip some test_stack.py tests on 3.12
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog, backport 2.3, backport 2.4, backport 2.5

#8048 fix(internal): support for namespace packages
  ddtrace/appsec/_iast/_loader.py
  ddtrace/internal/module.py
  releasenotes/notes/fix-module-namespace-package-support-90b326382951be19.yaml
  tests/internal/test_module.py
Labels: backport 2.4, backport 2.5

#8035 chore(ci): remove more flakyness in telemetry
  tests/conftest.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, CI

#8088 fix(iast): handle value error thrown by numpy
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  releasenotes/notes/iast-fix-valueerror-on-ast-function-a06975ec55afc26b.yaml
  tests/appsec/iast/taint_sinks/test_ast_taint.py
Labels: bug, ASM, backport 1.20, backport 2.2, backport 2.3, backport 2.4

#8042 fix(otel): support tag flattening [AIT-9352]
  ddtrace/internal/utils/formats.py
  ddtrace/opentelemetry/_span.py
  ddtrace/tracing/_span_link.py
  tests/opentelemetry/test_span.py
  tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes.json
  tests/tracer/test_encoders.py
  tests/tracer/test_span.py
  tests/tracer/test_utils.py
Labels: changelog/no-changelog, backport 2.5

#8066 chore(llmobs): move llmobs integration code to internal/llmobs
  ddtrace/contrib/langchain/constants.py
  ddtrace/contrib/langchain/patch.py
  ddtrace/contrib/openai/patch.py
  ddtrace/internal/llmobs/integrations/__init__.py
  ddtrace/internal/llmobs/integrations/base.py
  ddtrace/internal/llmobs/integrations/langchain.py
  ddtrace/internal/llmobs/integrations/openai.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/openai/conftest.py
  tests/suitespec.py
Labels: changelog/no-changelog

#8098 fix(ci): remove deleted file from suitespec
  tests/.suitespec.json
Labels: changelog/no-changelog

#8097 fix(span_links): revert regression in v04 encoding
  ddtrace/internal/_encoding.pyx
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog, backport 2.3, backport 2.4, backport 2.5

#8102 fix(ci): pin versions of sphinx dependencies to unlock ci
  hatch.toml
Labels: changelog/no-changelog, CI, backport 1.20, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#8096 fix: avoid changing the AST assign node since it's not needed for propagation
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/disable-multiple-assign-02565491d5d74083.yaml
  tests/appsec/iast/aspects/test_other_patching.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
Labels: ASM, backport 1.20, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#8095 chore(asm): implementing nest events rfc
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_processor.py
  tests/appsec/appsec/test_processor.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/contrib/flask/test_flask_appsec.py
Labels: enhancement, changelog/no-changelog, ASM

#7912 refactor(debugging): use new probe status endpoint
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_probe/status.py
  ddtrace/debugging/_uploader.py
  ddtrace/internal/utils/http.py
  tests/debugging/mocking.py
  tests/debugging/probe/test_registry.py
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/probe/test_status.py
  tests/debugging/test_encoding.py
  tests/debugging/test_uploader.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8113 fix(internal): support for pkg_resources
  ddtrace/internal/module.py
  releasenotes/notes/fix-module-loader-pkg-resources-support-2bed675a1e1f793b.yaml
  tests/internal/test_module.py
Labels: backport 2.4, backport 2.5

#8079 chore(release): always make patch version 0 for release candidates
  scripts/release.py
Labels: changelog/no-changelog

#8115 chore(tests): move asm overridable config keys for tests into asm config
  ddtrace/settings/asm.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#8114 chore(asm): add new api security env var support
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/settings/asm.py
  tests/contrib/django/test_django_appsec_api_security.py
  tests/contrib/fastapi/test_fastapi_appsec_api_security.py
  tests/contrib/flask/test_appsec_api_security.py
Labels: changelog/no-changelog, ASM

#8123 fix(otel): ensure booleans have json compatible representation
  ddtrace/tracing/_span_link.py
  releasenotes/notes/otel-span-links-json-encoding-b91b3923d19e78fb.yaml
  tests/tracer/test_encoders.py
Labels: backport 2.5

#8122 docs: add caveat note for DD_TRACE_SAMPLING_RULES
  docs/configuration.rst
Labels: changelog/no-changelog

#8077 docs: clean up and update checklist wording for pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#8053 ci: remove some flaky test markers
  tests/tracer/runtime/test_metric_collectors.py
  tests/tracer/test_logger.py
Labels: changelog/no-changelog

#8133 chore(pymongo): ran `compile-and-prune-test-requirements` for `pymongo`
  .riot/requirements/13015fd.txt
  .riot/requirements/13fe884.txt
  .riot/requirements/185fc1c.txt
  .riot/requirements/19aba18.txt
  .riot/requirements/1ba8c21.txt
  .riot/requirements/1dbb110.txt
  .riot/requirements/1e60db0.txt
  .riot/requirements/1eb9abd.txt
  .riot/requirements/3390a6b.txt
  .riot/requirements/5a48bdf.txt
  .riot/requirements/6cb445e.txt
  .riot/requirements/8f46789.txt
  .riot/requirements/a0454b7.txt
  .riot/requirements/a98b986.txt
  .riot/requirements/b0a5cc3.txt
  .riot/requirements/b1f6b59.txt
  .riot/requirements/d0fc014.txt
  .riot/requirements/de7d3ce.txt
Labels: changelog/no-changelog

#8126 fix(tracing): enable settings to be unset
  ddtrace/settings/config.py
  releasenotes/notes/tracer-rc-unset-361dc5080cd4a112.yaml
  tests/internal/test_settings.py
Labels: backport 2.5

#8139 docs: updated `contributing.rst` with small note about merge option
  docs/contributing.rst
Labels: changelog/no-changelog

#8137 chore(ci): no error on ls
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#8134 chore(botocore): make codeowner file more specific for bedrock/ml-obs
  .github/CODEOWNERS
Labels: changelog/no-changelog

#8140 ci: avoid skipping tests on main
  scripts/run-test-suite
  scripts/run-test-suite-hatch
Labels: changelog/no-changelog

#8131 fix(openai): add version gate to patch _process_response
  ddtrace/contrib/openai/patch.py
  releasenotes/notes/fix-openai-patch-process-response-b52430a78751de24.yaml
Labels: backport 2.3, backport 2.4, backport 2.5

#8011 feat(iast): detect CMDi on langchain
  .riot/requirements/1147cef.txt
  .riot/requirements/173e759.txt
  .riot/requirements/195f6e3.txt
  .riot/requirements/1b0d603.txt
  .riot/requirements/1e2d655.txt
  .riot/requirements/1fb9968.txt
  .riot/requirements/6b35ef3.txt
  .riot/requirements/af0a803.txt
  .riot/requirements/b9aa094.txt
  .riot/requirements/c650a62.txt
  ddtrace/contrib/langchain/constants.py
  ddtrace/contrib/langchain/patch.py
  releasenotes/notes/iast-cmdi-langchain-863be95c1160e50f.yaml
  riotfile.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/integrations/fixtures/patch_langchain.py
  tests/appsec/integrations/test_langchain.py
Labels: ASM, LLM

#8141 ci(flaky): mark `test_configure_service_name` as flaky
  tests/contrib/httpx/test_httpx.py
Labels: changelog/no-changelog

#8145 fix(span_links): set highest order bit in traceflag encoding
  ddtrace/internal/_encoding.pyx
  releasenotes/notes/fix-traceflag-serialization-e9d3e0d6a7c40ef1.yaml
  tests/tracer/test_encoders.py
Labels: backport 2.4, backport 2.5

#8117 chore(di): add @exception to the locals
  ddtrace/debugging/_signal/snapshot.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8138 fix(setup): bytecode constraint for Python 3.12
  releasenotes/notes/fix-bytecode-dependency-b71d1a8a84f52845.yaml
  setup.py
Labels: backport 2.4, backport 2.5

#8120 fix(internal): make caching thread-safe
  ddtrace/internal/utils/cache.py
  releasenotes/notes/fix-thread-safe-cache-b3ccf646feb364c6.yaml
Labels: backport 2.4, backport 2.5

#8124 chore(datastreams): botocore - dsm core API refactor
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/sqs.py
  ddtrace/contrib/botocore/utils.py
  ddtrace/internal/datastreams/__init__.py
  ddtrace/internal/datastreams/botocore.py
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#8153 refactor(internal): move `is_module_installed` for better reusability
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/internal/module.py
  tests/appsec/integrations/test_langchain.py
Labels: changelog/no-changelog

#8166 docs: document use of the flaky decorator
  docs/contributing-testing.rst
Labels: changelog/no-changelog

#8167 chore(tests): remove dependencies between appsec tests
  tests/appsec/appsec/test_appsec_trace_utils.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/rules.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/contrib/fastapi/test_fastapi_appsec.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/flask/test_flask_appsec_telemetry.py
Labels: changelog/no-changelog, ASM, CI

#8161 fix(asm): avoid logging exception on flask empty body
  ddtrace/appsec/_handlers.py
  releasenotes/notes/asm-fix-json-decode-error-none-af2c99becf9041a4.yaml
  tests/contrib/flask/test_flask_appsec.py
Labels: ASM, backport 1.20, backport 2.3, backport 2.4, backport 2.5

#8051 ci: update github actions to run on main
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
  .github/workflows/requirements-locks.yml
Labels: changelog/no-changelog

#8014 chore: remove unused riot env
  .riot/requirements/aa4751c.txt
  riotfile.py
Labels: changelog/no-changelog

#8168 ci(ci_visibility): increase parallelism for pytest suite
  .circleci/config.templ.yml
Labels: changelog/no-changelog, backport 1.20, backport 2.2, backport 2.3, backport 2.4, backport 2.5

#8116 refactor: multipart utilities
  ddtrace/debugging/_probe/status.py
  ddtrace/internal/utils/http.py
  tests/debugging/probe/test_status.py
Labels: changelog/no-changelog

#8175 chore(profiling): handle startup errors
  ddtrace/bootstrap/preload.py
Labels: changelog/no-changelog, Profiling

#8169 feat(tracing): handle the format in which the RC backend sends http header tag config
  ddtrace/settings/config.py
  tests/integration/test_settings.py
  tests/internal/test_settings.py
Labels: changelog/no-changelog

#8176 fix: incomplete pkg_resources support
  ddtrace/internal/module.py
  releasenotes/notes/fix-incomplete-pkg_resources-support-58baf819ea8705ef.yaml
  tests/internal/test_module.py
Labels: backport 2.5

#7963 chore(ci_visibility): improve logging of CIVisibility and pytest ddtrace plugin
  ddtrace/ext/git.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/utils.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/unittest/test_unittest_snapshot.py
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly_with_skipped.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_multiple_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_custom_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped.json
Labels: changelog/no-changelog

#8184 fix(profiling): handle SystemError in class name extraction
  ddtrace/profiling/collector/_traceback.pyx
  releasenotes/notes/fix-profiling-class-name-system-error-75df13d59d9974ee.yaml
Labels: Profiling, backport 2.3, backport 2.4, backport 2.5

#8174 chore(uwsgi): better threading options check
  ddtrace/internal/uwsgi.py
  tests/profiling/test_uwsgi.py
Labels: changelog/no-changelog

#8182 chore(openai): change llmobs tag names
  ddtrace/internal/llmobs/integrations/openai.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog, MLObs

#8177 feat(span): add span link getters and setters
  ddtrace/internal/_encoding.pyx
  ddtrace/opentelemetry/_trace.py
  ddtrace/span.py
  releasenotes/notes/span-link-getter-setters-08ff8b2e476091ae.yaml
  tests/opentelemetry/test_trace.py
  tests/tracer/test_encoders.py
  tests/tracer/test_propagation.py
  tests/tracer/test_span.py
Labels: manual merge

#8179 ci: parallelize appsec integrations
  .circleci/config.templ.yml
Labels: changelog/no-changelog, CI

#8193 chore(span): remove span link getter
  ddtrace/span.py
  releasenotes/notes/span-link-getter-setters-08ff8b2e476091ae.yaml
  tests/opentelemetry/test_trace.py
  tests/tracer/test_encoders.py
  tests/tracer/test_propagation.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#8178 chore(dependencies): update envier version pin
  .riot/requirements/132f882.txt
  .riot/requirements/1e6bfcb.txt
  .riot/requirements/1f540f4.txt
  .riot/requirements/4b04687.txt
  .riot/requirements/6498eb0.txt
  .riot/requirements/c23a971.txt
  hatch.toml
  riotfile.py
Labels: changelog/no-changelog

#8192 test(di): fix flaky tests
  tests/debugging/probe/test_remoteconfig.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8183 chore(openai): llmobs unified metrics
  ddtrace/contrib/openai/patch.py
  ddtrace/internal/llmobs/integrations/openai.py
  tests/contrib/openai/cassettes/v0/chat_completion_tool_call.yaml
  tests/contrib/openai/cassettes/v0/embedding_array_of_token_arrays.yaml
  tests/contrib/openai/cassettes/v0/embedding_token_array.yaml
  tests/contrib/openai/cassettes/v1/chat_completion_tool_call.yaml
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_integration.json
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_service_name[None-None].json
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_service_name[None-v0].json
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_service_name[None-v1].json
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_service_name[mysvc-None].json
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_service_name[mysvc-v0].json
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_service_name[mysvc-v1].json
  tests/snapshots/tests.contrib.openai.test_openai.test_acompletion.json
  tests/snapshots/tests.contrib.openai.test_openai.test_atranscribe.json
  tests/snapshots/tests.contrib.openai.test_openai.test_atranslate.json
  tests/snapshots/tests.contrib.openai.test_openai.test_chat_completion.json
  tests/snapshots/tests.contrib.openai.test_openai.test_chat_completion_function_calling.json
  tests/snapshots/tests.contrib.openai.test_openai.test_chat_completion_image_input.json
  tests/snapshots/tests.contrib.openai.test_openai.test_completion.json
  tests/snapshots/tests.contrib.openai.test_openai.test_edit.json
  tests/snapshots/tests.contrib.openai.test_openai.test_embedding.json
  tests/snapshots/tests.contrib.openai.test_openai.test_embedding_array_of_token_arrays.json
  tests/snapshots/tests.contrib.openai.test_openai.test_embedding_string_array.json
  tests/snapshots/tests.contrib.openai.test_openai.test_embedding_token_array.json
  tests/snapshots/tests.contrib.openai.test_openai.test_integration_async.json
  tests/snapshots/tests.contrib.openai.test_openai.test_integration_sync.json
  tests/snapshots/tests.contrib.openai.test_openai.test_transcribe.json
  tests/snapshots/tests.contrib.openai.test_openai.test_translate.json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[None-None].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[None-v0].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[None-v1].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[mysvc-None].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[mysvc-v0].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[mysvc-v1].json
  tests/snapshots/tests.contrib.openai.test_openai_v1.test_integration_service_name[None-None].json
  tests/snapshots/tests.contrib.openai.test_openai_v1.test_integration_service_name[None-v0].json
  tests/snapshots/tests.contrib.openai.test_openai_v1.test_integration_service_name[None-v1].json
  tests/snapshots/tests.contrib.openai.test_openai_v1.test_integration_service_name[mysvc-None].json
  tests/snapshots/tests.contrib.openai.test_openai_v1.test_integration_service_name[mysvc-v0].json
  tests/snapshots/tests.contrib.openai.test_openai_v1.test_integration_service_name[mysvc-v1].json
  tests/snapshots/tests.contrib.openai.test_openai_v1.test_integration_sync.json
Labels: changelog/no-changelog, manual merge, MLObs

#8075 fix: pin importlib to 6.5.0
  pyproject.toml
  releasenotes/notes/pin-importlib-to-6.5.0-to-avoid-importlib-issue-455-d098894f7a29591b.yaml
  setup.py
Labels: ASM, backport 2.3, backport 2.4, backport 2.5

#8185 chore(di): trigger context-creating probes first
  ddtrace/debugging/_async.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/model.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#7861 chore(tracer): report configuration origin
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#8211 ci: temporarily disable opentelemetry tests on 3.7 because they are broken
  .riot/requirements/133c686.txt
  .riot/requirements/140af01.txt
  .riot/requirements/194eaa9.txt
  .riot/requirements/1f141fb.txt
  .riot/requirements/953e989.txt
  .riot/requirements/d53c7cb.txt
  .riot/requirements/e839854.txt
  riotfile.py
Labels: changelog/no-changelog, backport 2.3, backport 2.4, backport 2.5

#8210 feat(asm): remove experimental status from api sec
  ddtrace/appsec/_constants.py
  releasenotes/notes/api_security_available-63d8f7829e512405.yaml
Labels: ASM

#8155 chore(asm): move threats tests to appsec and use hatch
  .circleci/config.templ.yml
  hatch.toml
  scripts/ddtest
  setup.py
  tests/.suitespec.json
  tests/appsec/contrib_appsec/__init__.py
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/django_app/__init__.py
  tests/appsec/contrib_appsec/django_app/settings.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/__init__.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/test_django.py
  tests/appsec/contrib_appsec/test_fastapi.py
  tests/appsec/contrib_appsec/test_flask.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM, CI

#8222 chore(asm): api security activated by default
  ddtrace/appsec/_utils.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#8050 ci(kafka): make test suite more resilient to randomization
  .circleci/config.templ.yml
  tests/contrib/kafka/test_kafka.py
  tests/snapshots/tests.contrib.kafka.test_kafka.test_analytics_with_rate.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_analytics_without_rate.json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_message[False].json
  tests/snapshots/tests.contrib.kafka.test_kafka.test_message[True].json
Labels: changelog/no-changelog

#8225 docs: remove confusing -s from example riot command
  docs/contributing-testing.rst
Labels: changelog/no-changelog

#8032 ci: clean parametric tests pipeline
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#8130 fix(trace_stats): ensures stats respect the report_hostname configuration
  ddtrace/internal/processor/stats.py
  releasenotes/notes/use-report-hostname-in-stats-c60c5a6cb96d2481.yaml
  tests/integration/test_trace_stats.py
Labels: backport 2.4, backport 2.5

#8215 chore(ci_visibility): properly mark update suite spans as skipped when using class-based tests
  ddtrace/contrib/pytest/plugin.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog

#8226 fix(tracer): do not try to load asm if libddwaf unavailable
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/settings/asm.py
  ddtrace/tracer.py
Labels: changelog/no-changelog, ASM

#8231 ci: temporarily disable opentelemetry tests on 3.7 because they are broken [backport 2.4] (#8214)
  .riot/requirements/10cab33.txt
  .riot/requirements/11efb5e.txt
  .riot/requirements/1435ffd.txt
  .riot/requirements/180bfac.txt
  .riot/requirements/1c404c3.txt
  .riot/requirements/abbe0b5.txt
  .riot/requirements/b2acf57.txt
  riotfile.py
Labels: changelog/no-changelog

#8232 ci: temporarily disable opentelemetry tests on 3.7 because they are broken [backport 2.3] (#8214)
  .riot/requirements/10cab33.txt
  .riot/requirements/11efb5e.txt
  .riot/requirements/1435ffd.txt
  .riot/requirements/180bfac.txt
  .riot/requirements/1c404c3.txt
  .riot/requirements/abbe0b5.txt
  .riot/requirements/b2acf57.txt
  riotfile.py
Labels: changelog/no-changelog

#8188 chore(di): implement EMITTING probe status
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_probe/registry.py
  ddtrace/debugging/_probe/status.py
  tests/debugging/exploration/debugger.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8241 ci(profiling): skip failing tests
  tests/profiling/collector/test_task.py
  tests/profiling/collector/test_threading.py
Labels: changelog/no-changelog

#8240 ci: bump cibuildwheel
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, CI, backport 1.20, backport 2.3, backport 2.4, backport 2.5

#8152 docs: update riot command breakdown in `contributing-testing.rst` docs
  docs/contributing-testing.rst
Labels: changelog/no-changelog

#8245 ci: mark and adjust a few unreliable tests
  tests/contrib/fastapi/test_fastapi.py
  tests/profiling/collector/test_stack.py
  tests/tracer/test_logger.py
Labels: changelog/no-changelog

#8237 test(asm): refactor tests and improve hatch threat tests
  tests/appsec/appsec/rules-suspicious-requests-response.json
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/test_django.py
  tests/appsec/contrib_appsec/test_fastapi.py
  tests/appsec/contrib_appsec/test_flask.py
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/fastapi/test_fastapi_appsec.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM, CI

#8181 chore: remove unused trace processor
  ddtrace/internal/processor/truncator.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog

#8246 ci: mark some flaky tests
  .circleci/config.templ.yml
  tests/contrib/httpx/test_httpx.py
  tests/contrib/redis/test_redis_asyncio.py
  tests/debugging/test_debugger.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
  tests/tracer/test_logger.py
Labels: changelog/no-changelog

#8235 fix(openai): ensure logs and llmobs records are submitted for errors
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/internal/llmobs/integrations/openai.py
  tests/contrib/openai/cassettes/v0/chat_completion_error.yaml
  tests/contrib/openai/cassettes/v0/completion_error.yaml
  tests/contrib/openai/cassettes/v1/chat_completion_error.yaml
  tests/contrib/openai/cassettes/v1/completion_error.yaml
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog

#8224 chore(tracer): improve fastapi headers management
  ddtrace/contrib/asgi/middleware.py
Labels: enhancement, changelog/no-changelog
