Repository DataDog/dd-trace-py, pull requests merged in 2024-03, with the labels that each got.

#8534 feat(llmobs): add function decorators to LLMObs SDK
  ddtrace/llmobs/decorators.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/contrib/openai/utils.py
  tests/llmobs/_utils.py
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_writer.py
  tests/llmobs/test_logger.py
  tests/llmobs/utils.py
Labels: changelog/no-changelog, MLObs

#8459 chore(asm): update api sec sampling mechanism
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/_utils.py
  ddtrace/settings/asm.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#8480 ci(sqlalchemy): upgrade tests to support latest versions of sqlalchemy
  .riot/requirements/1420734.txt
  .riot/requirements/16653b8.txt
  .riot/requirements/16711f6.txt
  .riot/requirements/1b75c2c.txt
  .riot/requirements/1e17b32.txt
  .riot/requirements/2849a6e.txt
  .riot/requirements/30cfea5.txt
  .riot/requirements/3cdaaae.txt
  .riot/requirements/6c1588c.txt
  .riot/requirements/74b9848.txt
  .riot/requirements/dc69f1e.txt
  .riot/requirements/f348277.txt
  riotfile.py
  tests/contrib/sqlalchemy/mixins.py
  tests/contrib/sqlalchemy/test_mysql.py
  tests/contrib/sqlalchemy/test_patch.py
  tests/contrib/sqlalchemy/test_postgres.py
  tests/contrib/sqlalchemy/test_sqlite.py
Labels: changelog/no-changelog

#8582 ci: remove ``pytest_ignore_collect`` hook
  conftest.py
Labels: changelog/no-changelog, CI, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8573 chore(tracing): remove atexit dead code and forksafe dead code
  ddtrace/internal/atexit.py
  ddtrace/internal/forksafe.py
Labels: changelog/no-changelog

#8588 ci: pin pytest
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI, backport 1.20, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8593 chore(tracing): check that register at fork is available on os
  ddtrace/internal/forksafe.py
Labels: changelog/no-changelog

#8565 fix(iast): remove unneeded atexit handler
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  releasenotes/notes/iast-fix-remove-unneeded-atexit-handler-2a2f7e193c457666.yaml
Labels: bug, ASM, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8564 fix(iast): avoid native module import if iast disabled
  benchmarks/appsec_iast_propagation/scenario.py
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  releasenotes/notes/iast-fix-avoid-native-module-load-ccb79bd350dc3621.yaml
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_native_taint_source.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
  tests/appsec/iast_packages/packages/template.py.tpl
  tests/appsec/iast_packages/packages/utils.py
  tests/appsec/iast_tdd_propagation/flask_orm_app.py
  tests/appsec/integrations/test_langchain.py
  tests/appsec/integrations/test_psycopg2.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/smoke_test.py
Labels: bug, ASM, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8590 chore: normalize importlib.metadata package name
  ddtrace/internal/packages.py
  tests/internal/test_packages.py
Labels: changelog/no-changelog

#8600 feat(llmobs): add tracer version as `ddtrace.version` tag
  ddtrace/llmobs/_llmobs.py
  tests/llmobs/_utils.py
Labels: changelog/no-changelog, MLObs

#8570 chore(tracer): remove BaseException catching
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_taint_utils.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/aioredis/patch.py
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/subprocess/patch.py
  ddtrace/internal/compat.py
  ddtrace/internal/core/event_hub.py
  ddtrace/internal/wrapping/asyncs.py
  ddtrace/internal/wrapping/generators.py
  ddtrace/settings/config.py
Labels: changelog/no-changelog

#8578 chore(asm): use sample delay env var for api sec sampling
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_constants.py
  ddtrace/settings/asm.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#8559 fix(ci_visibility): use ||| as git show format separator when fetching user info
  ddtrace/ext/git.py
  releasenotes/notes/ci_visibility-fix-comma_separation_issue_in_git_format-76bf32d68ba6c164.yaml
  tests/tracer/test_ci.py
Labels: backport 1.20, backport 2.5, backport 2.6, backport 2.7

#8380 ci: fix missing paths in suitespec for CI Visibility-related jobs [backport 1.20]
  tests/.suitespec.json
Labels: changelog/no-changelog

#8581 chore(di): add application key to redacted keywords
  ddtrace/debugging/_redaction.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8587 chore: strip slashes from cgroup path
  ddtrace/internal/runtime/container.py
Labels: changelog/no-changelog

#8601 feat(llmobs): change default ml-app name to service before default value
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_llmobs.py
  tests/contrib/botocore/test_bedrock.py
  tests/llmobs/_utils.py
Labels: changelog/no-changelog, MLObs

#8618 fix(profiling): serialisable stack key [backport #8435 to 2.7]
  ddtrace/profiling/exporter/pprof.pyx
  releasenotes/notes/fix-profiling-stack-event-data-dc50c8e7663718cc.yaml
Labels: Profiling, backport 2.5, backport 2.6, backport 2.7

#8620 fix(profiling): serialisable stack key [backport #8435 to 2.5]
  ddtrace/profiling/exporter/pprof.pyx
  releasenotes/notes/fix-profiling-stack-event-data-dc50c8e7663718cc.yaml
Labels: Profiling, backport 2.5, backport 2.6, backport 2.7

#8603 fix(internal): chained namespace loader
  ddtrace/internal/module.py
  docs/spelling_wordlist.txt
  releasenotes/notes/fix-chained-namespace-loader-1701e040d7b3af9b.yaml
  tests/internal/test_module.py
Labels: backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8531 feat(tracer): initial boilerplate for enabling tracer flares
  ddtrace/settings/config.py
  tests/internal/remoteconfig/test_remoteconfig.py
Labels: changelog/no-changelog

#8614 fix(starlette): fixes starlette path/root_path handling
  .riot/requirements/1185813.txt
  .riot/requirements/12bc9cf.txt
  .riot/requirements/135e6d3.txt
  .riot/requirements/1406f3b.txt
  .riot/requirements/16c5a53.txt
  .riot/requirements/179c00c.txt
  .riot/requirements/17ed83b.txt
  .riot/requirements/18d8776.txt
  .riot/requirements/1ef0c35.txt
  .riot/requirements/1f12892.txt
  .riot/requirements/36231be.txt
  .riot/requirements/3fbc610.txt
  .riot/requirements/60ac461.txt
  .riot/requirements/675a702.txt
  .riot/requirements/7a59aa8.txt
  .riot/requirements/95f1208.txt
  .riot/requirements/9c022dd.txt
  .riot/requirements/be21fe1.txt
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/starlette/patch.py
  releasenotes/notes/starlette-root-path-bugfix-ad372cc320f384dd.yaml
  riotfile.py
  tests/contrib/starlette/app.py
  tests/contrib/starlette/test_starlette.py
  tests/snapshots/tests.contrib.starlette.test_starlette.test_background_task.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_schematization[service_schema0]_rest.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_schematization[service_schema2]_rest.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_schematization[service_schema3]_rest.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_schematization[service_schema5]_rest.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_subapp_nested_call_snapshot.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_subapp_nested_snapshot.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_subapp_no_aggregate_snapshot.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_subapp_snapshot.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_subapp_two_snapshot.json
  tests/snapshots/tests.contrib.starlette.test_starlette.test_table_query_snapshot.json
Labels: backport 2.6, backport 2.7

#8479 ci(fastapi): upgrade tests to support latest versions of fastapi
  .riot/requirements/121f3e0.txt
  .riot/requirements/1483567.txt
  .riot/requirements/148692c.txt
  .riot/requirements/15aa558.txt
  .riot/requirements/1683094.txt
  .riot/requirements/171b20f.txt
  .riot/requirements/1b3efb5.txt
  .riot/requirements/1ca5ab3.txt
  .riot/requirements/35e4d8d.txt
  .riot/requirements/45b92b9.txt
  .riot/requirements/51442dd.txt
  .riot/requirements/7faa8e0.txt
  .riot/requirements/958996c.txt
  .riot/requirements/a7d2dc1.txt
  .riot/requirements/dcf90ee.txt
  .riot/requirements/eb3b2f1.txt
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_500_error_raised.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_background_task.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples0]_6_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples0]_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples1]_6_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples1]_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples2]_6_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples2]_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples3]_6_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples3]_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples4]_6_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples4]_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples5]_6_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_schematization[schema_tuples5]_9.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_subapp_snapshot.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_table_query_snapshot.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_traced_websocket.json
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_tracing_in_middleware.json
Labels: changelog/no-changelog

#8632 fix(llmobs): set parentID for root spans to be "undefined" in llmobs payloads
  ddtrace/llmobs/_llmobs.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog, MLObs

#8615 fix(profiling): make stack_v2 and ddup more robust against failure
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
  ddtrace/internal/datadog/profiling/ddup/__init__.py
  ddtrace/internal/datadog/profiling/stack_v2/__init__.py
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/scheduler.py
  setup.py
Labels: changelog/no-changelog

#8567 fix(setup): remove metadata redundancy
  pyproject.toml
  releasenotes/notes/fix-metadata-redundancy-afc4dca3c5bb4a5a.yaml
  setup.py
Labels: changelog/no-changelog, backport 2.6, backport 2.7

#8629 fix(asm): fix cpu leak
  ddtrace/appsec/_asm_request_context.py
  releasenotes/notes/fix_incident_25768-043ae458e46c9620.yaml
  tests/appsec/contrib_appsec/utils.py
Labels: bug, ASM, backport 2.5, backport 2.6, backport 2.7

#8569 fix(tracing): ensure p is on the tracestate of active spans
  ddtrace/_trace/context.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/span.py
  ddtrace/_trace/tracer.py
  ddtrace/internal/constants.py
  ddtrace/internal/utils/http.py
  ddtrace/opentelemetry/_span.py
  ddtrace/propagation/http.py
  releasenotes/notes/always-add-p-to-ts-ff6c6c68c3cb9bfc.yaml
  tests/opentelemetry/test_context.py
  tests/opentelemetry/test_span.py
  tests/tracer/test_propagation.py
Labels: backport 2.7

#8634 feat(llmobs): add error stack to LLMObs span event
  ddtrace/llmobs/_llmobs.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog, MLObs

#8641 chore(asm): improve api security import condition (#8609) [backport 2.6]
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_utils.py
  ddtrace/settings/asm.py
  ddtrace/tracer.py
Labels: enhancement, changelog/no-changelog, ASM

#8650 fix(asm): fix cpu leak (#8629) [backport 2.5]
  ddtrace/appsec/_asm_request_context.py
  releasenotes/notes/fix_incident_25768-043ae458e46c9620.yaml
Labels: ASM

#8646 fix: asm None env
  ddtrace/appsec/_asm_request_context.py
  releasenotes/notes/missing-asm-env-again-bab2f6a06c6f366d.yaml
Labels: ASM, backport 2.5, backport 2.6, backport 2.7

#8655 chore(ci): clean-up old init and test app images
  .github/workflows/lib-inject-prune.yml
Labels: changelog/no-changelog

#8656 fix(tracing): fix context cloning
  ddtrace/_trace/context.py
  tests/tracer/test_context.py
  tests/tracer/test_propagation.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog, backport 2.7

#8638 chore(asm): improve api security import condition (#8609) [backport 2.7]
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_utils.py
  ddtrace/settings/asm.py
Labels: enhancement, changelog/no-changelog, ASM

#8658 chore: fix system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#8659 chore: add gdb to testrunner image
  docker/Dockerfile
Labels: changelog/no-changelog

#8660 fix(asm): fix comment about waf timeout in asm settings
  ddtrace/settings/asm.py
Labels: changelog/no-changelog, ASM

#8617 chore(asm): improve telemetry for waf
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
Labels: enhancement, changelog/no-changelog, ASM

#8610 fix(kafka): do identity checks on kafka messages to work around __len__ issue
  ddtrace/contrib/kafka/patch.py
  releasenotes/notes/kafka-none-2-4f9e600e115eb44c.yaml
Labels: backport 2.5, backport 2.6, backport 2.7

#8664 ci: fix amd64 testrunner build
  docker/Dockerfile
Labels: changelog/no-changelog

#8668 fix(profiling): tighten ddup types
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
Labels: changelog/no-changelog

#8673 fix(propagation): never clobber extracted decisionmaker tags [AIT-9945]
  ddtrace/propagation/http.py
  releasenotes/notes/clobber-dm-b494dc48a3217371.yaml
  tests/tracer/test_propagation.py
Labels: backport 2.5, backport 2.6, backport 2.7

#8661 chore(asm): improve deduplication for telemetry
  ddtrace/appsec/_deduplications.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_weak_hash.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#8678 chore(asm): less flakyness in fastapi tests
  tests/appsec/contrib_appsec/test_fastapi.py
Labels: changelog/no-changelog, ASM, CI

#8680 chore(di): implement instanceof operator
  ddtrace/debugging/_expressions.py
  tests/debugging/test_expressions.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8683 chore(asm): return all waf results from the waf callback
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_processor.py
Labels: changelog/no-changelog, ASM

#8684 chore(asm): improve logic of api security manager
  ddtrace/appsec/_api_security/api_manager.py
Labels: changelog/no-changelog, ASM

#8690 ci: resolve failing flask framework tests [backport 2.5]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#8682 fix(profiling): remove use of static C++
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader_builder.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader_builder.cpp
  releasenotes/notes/profiling-fix-static-cxx-invalid-free-9450db447e16b250.yaml
Labels: backport 2.7

#8640 fix(setup): remove metadata redundancy [backport #8567 to 2.6]
  pyproject.toml
  releasenotes/notes/fix-metadata-redundancy-afc4dca3c5bb4a5a.yaml
  setup.py
Labels: changelog/no-changelog, backport 2.6, backport 2.7

#8639 fix(setup): remove metadata redundancy [backport #8567 to 2.7]
  pyproject.toml
  releasenotes/notes/fix-metadata-redundancy-afc4dca3c5bb4a5a.yaml
  setup.py
Labels: changelog/no-changelog

#8693 ci: add greenlet dependency to riot lockfiles
  .riot/requirements/1185813.txt
  .riot/requirements/135e6d3.txt
  .riot/requirements/1420734.txt
  .riot/requirements/16653b8.txt
  .riot/requirements/16711f6.txt
  .riot/requirements/16c5a53.txt
  .riot/requirements/17ed83b.txt
  .riot/requirements/1b75c2c.txt
  .riot/requirements/1ef0c35.txt
  .riot/requirements/36231be.txt
  .riot/requirements/3cdaaae.txt
  .riot/requirements/60ac461.txt
  .riot/requirements/7a59aa8.txt
  .riot/requirements/9c022dd.txt
  .riot/requirements/dc69f1e.txt
Labels: changelog/no-changelog, CI

#8702 fix(asm): fix receive wrapper for asgi [backport 2.5]
  ddtrace/appsec/_handlers.py
  releasenotes/notes/fix_asgi_receive_wrapper-685522a1af75d59d.yaml
Labels: ASM

#8701 fix(asm): fix receive wrapper for asgi [backport 2.6]
  ddtrace/appsec/_handlers.py
  releasenotes/notes/fix_asgi_receive_wrapper-685522a1af75d59d.yaml
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/utils.py
Labels: ASM

#8698 fix(asm): improve django login events logic
  ddtrace/appsec/_trace_utils.py
  releasenotes/notes/appsec-django-login-anonymous-user-fix-3c1faae6df4106e9.yaml
  tests/contrib/django/test_django_appsec.py
Labels: ASM, backport 2.5, backport 2.6, backport 2.7

#8706 chore(asm): catch all exceptions
  ddtrace/appsec/_handlers.py
Labels: changelog/no-changelog, ASM

#8681 fix(langchain): addresses compatibility issues with langchains vision API
  ddtrace/contrib/langchain/patch.py
  releasenotes/notes/fix-langchain-vision-apis-58e4de9b52198e43.yaml
  tests/contrib/langchain/cassettes/langchain_community/openai_chat_completion_image_input_sync_generate.yaml
  tests/contrib/langchain/test_langchain_community.py
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_chat_model_vision_generate.json
Labels: backport 2.6, backport 2.7

#8671 chore(asyncio): parent spans on task creation
  ddtrace/_monkey.py
  ddtrace/contrib/asyncio/__init__.py
  ddtrace/contrib/asyncio/compat.py
  ddtrace/contrib/asyncio/helpers.py
  ddtrace/contrib/asyncio/patch.py
  releasenotes/notes/deprecate-asyncontext-provider-f72ea7035a630063.yaml
  tests/contrib/asyncio/test_tracer.py
Labels: changelog/no-changelog

#8721 feat(llmobs): add ML App override option to LLMObs SDK span methods
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/decorators.py
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog, MLObs

#8724 fix(asm): clear ddwaf contexts on span finish
  ddtrace/appsec/_processor.py
  releasenotes/notes/asm-clear-ddwaf-ctx-on-span-finish-4d8b7c7e818ae5d7.yaml
  tests/appsec/appsec/test_processor.py
Labels: ASM, backport 2.5, backport 2.6, backport 2.7

#8674 chore: update references to the testrunner image
  .circleci/config.templ.yml
  docker-compose.yml
Labels: changelog/no-changelog

#8722 chore(tracer): make tracer.sampler private and add tracer.sample()
  ddtrace/_trace/tracer.py
  ddtrace/internal/debug.py
  releasenotes/notes/deprecate_tracer_sampler-69c81b7ccf8fb6f9.yaml
  tests/tracer/test_sampler.py
Labels: changelog/no-changelog

#8679 chore(di): make the and/or operators lazy
  ddtrace/debugging/_expressions.py
  tests/debugging/test_expressions.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8730 ci: fetch main branch when not in a pull request build
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#8732 fix(asm): clear ddwaf contexts on span finish [backport 2.5]
  ddtrace/appsec/_processor.py
  releasenotes/notes/asm-clear-ddwaf-ctx-on-span-finish-4d8b7c7e818ae5d7.yaml
  tests/appsec/appsec/test_processor.py
Labels: ASM

#8723 feat(llmobs): add error.type to llmobs spans
  ddtrace/llmobs/_trace_processor.py
  tests/llmobs/_utils.py
Labels: changelog/no-changelog, MLObs

#8740 chore(tracing): remove span_links from context._with_span
  ddtrace/_trace/context.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#8711 chore(ci_visibility): experimental CI Visibility manual testing API
  .circleci/config.templ.yml
  ddtrace/ext/ci_visibility/__init__.py
  ddtrace/ext/ci_visibility/_ci_visibility_base.py
  ddtrace/ext/ci_visibility/api.py
  ddtrace/ext/ci_visibility/util.py
  ddtrace/internal/ci_visibility/__init__.py
  ddtrace/internal/ci_visibility/api/__init__.py
  ddtrace/internal/ci_visibility/api/ci_base.py
  ddtrace/internal/ci_visibility/api/ci_module.py
  ddtrace/internal/ci_visibility/api/ci_session.py
  ddtrace/internal/ci_visibility/api/ci_suite.py
  ddtrace/internal/ci_visibility/api/ci_test.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/errors.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/.suitespec.json
  tests/ci_visibility/api/fake_runner_all_fail.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_suite_level.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_test_level.py
  tests/ci_visibility/api/fake_runner_all_pass.py
  tests/ci_visibility/api/fake_runner_all_skip.py
  tests/ci_visibility/api/test_api_fake_runners.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/util.py
  tests/integration/test_integration_civisibility.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_skip.json
Labels: changelog/no-changelog, CI App

#8742 fix(asm): login failure events `user exists` field optional
  ddtrace/appsec/_trace_utils.py
  releasenotes/notes/asm-fix-login-failure-events-4c79ea4b5c6f5e29.yaml
  tests/contrib/django/test_django_appsec.py
Labels: ASM, backport 2.5, backport 2.6, backport 2.7

#8739 chore(dsm): processor retries now fail as debug, unless retry limit is exceeded
  ddtrace/internal/datastreams/processor.py
  releasenotes/notes/dsm-error-logs-to-debug-1b3322c4a8790b72.yaml
Labels: backport 2.6, backport 2.7

#8738 ci: automate changelog additions
  scripts/release.py
Labels: changelog/no-changelog

#8731 ci: update starlette environments
  .riot/requirements/112dc22.txt
  .riot/requirements/1250d61.txt
  .riot/requirements/156e3cc.txt
  .riot/requirements/17a0f7f.txt
  .riot/requirements/18392ae.txt
  .riot/requirements/1b846e9.txt
  .riot/requirements/1c489e9.txt
  .riot/requirements/2c855a9.txt
  .riot/requirements/4b1629e.txt
  .riot/requirements/7b8e50e.txt
  .riot/requirements/7f7863d.txt
  .riot/requirements/7ff8c97.txt
  .riot/requirements/91a3315.txt
  .riot/requirements/b06b6cb.txt
  .riot/requirements/c52f9f6.txt
  .riot/requirements/d6ceb22.txt
  .riot/requirements/d88b3ac.txt
  .riot/requirements/ec338d4.txt
  riotfile.py
Labels: changelog/no-changelog, backport 2.6, backport 2.7

#8735 ci: upgrade the checkout action used in the system tests workflow
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, backport 2.6, backport 2.7

#8733 chore(tracing): remove outdated sampling release note
  releasenotes/notes/sampler_public-0570e2ce18bc604b.yaml
Labels: changelog/no-changelog

#8758 chore(asm): upgrade waf timeout to 5 seconds for threat tests on the CI
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/test_fastapi.py
Labels: changelog/no-changelog, ASM, CI

#8737 chore: update changelog for version 2.6.9
  CHANGELOG.md
Labels: changelog/no-changelog

#8736 ci: upgrade sqlalchemy venv dependencies
  .riot/requirements/1353f0b.txt
  .riot/requirements/162f3c3.txt
  .riot/requirements/1809449.txt
  .riot/requirements/1a692b1.txt
  .riot/requirements/1b67e71.txt
  .riot/requirements/1bc2c36.txt
  .riot/requirements/1efd2cc.txt
  .riot/requirements/1f1570a.txt
  .riot/requirements/2b30eed.txt
  .riot/requirements/573ce40.txt
  .riot/requirements/edd1c7f.txt
  .riot/requirements/fd74210.txt
  riotfile.py
Labels: changelog/no-changelog, backport 2.6, backport 2.7

#8741 ci: update graphql envs [APMS-11607]
  .riot/requirements/10d33c9.txt
  .riot/requirements/11c18f0.txt
  .riot/requirements/133d1be.txt
  .riot/requirements/15ad8d9.txt
  .riot/requirements/17e1939.txt
  .riot/requirements/19f9d82.txt
  .riot/requirements/1abf4f4.txt
  .riot/requirements/1ff1638.txt
  .riot/requirements/4ccd5e8.txt
  .riot/requirements/6041a51.txt
  .riot/requirements/688e35d.txt
  .riot/requirements/723defa.txt
  .riot/requirements/912dbf5.txt
  .riot/requirements/c08cf9c.txt
  .riot/requirements/d54aa74.txt
  .riot/requirements/dcf994d.txt
  .riot/requirements/f3d54b7.txt
  .riot/requirements/f64307d.txt
  riotfile.py
Labels: changelog/no-changelog, backport 2.6, backport 2.7

#8748 feat(llmobs): add session ID tag
  ddtrace/llmobs/_trace_processor.py
  tests/llmobs/_utils.py
Labels: changelog/no-changelog, MLObs

#8568 feat(asm): add exploit prevention LFI support
  ddtrace/_monkey.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_exploit_prevention/stack_traces.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_processor.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/rules-rasp.json
  tests/appsec/appsec/test_processor.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/rules.py
Labels: changelog/no-changelog, ASM

#8766 ci: only attempt to compress artifact from parametric tests if it was created
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, backport 2.5, backport 2.6, backport 2.7

#8765 fix: add `__init__.py` to `peer_service` module
  ddtrace/internal/peer_service/__init__.py
  releasenotes/notes/fix-import-peer-service-69d57a595b54a109.yaml
Labels: backport 2.7

#8773 ci(telemetry): expect observed test result
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog

#8781 ci: make pytest output verbose during profile suite
  riotfile.py
Labels: changelog/no-changelog

#8772 fix(iast): ensure context is created for current span
  ddtrace/appsec/_iast/processor.py
  releasenotes/notes/iast-fix-context-creation-2d0dee033723514c.yaml
Labels: ASM, backport 2.5, backport 2.6, backport 2.7

#8790 fix(llmobs): correctly cast bedrock token/temperature parameters
  ddtrace/contrib/botocore/services/bedrock.py
  ddtrace/llmobs/_integrations/bedrock.py
Labels: changelog/no-changelog, MLObs

#8789 fix(llmobs): add type checking to the chat completions endpoint
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/contrib/openai/utils.py
  ddtrace/llmobs/_integrations/openai.py
Labels: changelog/no-changelog, MLObs

#8779 feat(dramatiq): add `dramatiq` integration
  .circleci/config.templ.yml
  .riot/requirements/14116fa.txt
  .riot/requirements/16f33ce.txt
  .riot/requirements/19508cd.txt
  .riot/requirements/638973a.txt
  .riot/requirements/a9dcb3f.txt
  .riot/requirements/ee62ebe.txt
  ddtrace/_monkey.py
  ddtrace/contrib/dramatiq/__init__.py
  ddtrace/contrib/dramatiq/patch.py
  releasenotes/notes/init-dramatiq-integration-8b882a3e9921208e.yaml
  riotfile.py
  tests/.suitespec.json
  tests/contrib/dramatiq/__init__.py
  tests/contrib/dramatiq/autopatch.py
  tests/contrib/dramatiq/conftest.py
  tests/contrib/dramatiq/test_integration.py
  tests/contrib/dramatiq/test_patch_auto.py
  tests/contrib/dramatiq/test_patch_manual.py
  tests/snapshots/tests.contrib.dramatiq.test_integration.test_fn_exception_no_retries.json
  tests/snapshots/tests.contrib.dramatiq.test_integration.test_fn_retry_exception.json
  tests/snapshots/tests.contrib.dramatiq.test_integration.test_fn_task_send.json
  tests/snapshots/tests.contrib.dramatiq.test_integration.test_fn_task_send_with_params.json
  tests/snapshots/tests.contrib.dramatiq.test_integration.test_idempotent_patch.json
  tests/snapshots/tests.contrib.dramatiq.test_integration.test_send_exception.json
Labels: integrations

#8791 ci: parallel system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI, backport 2.5, backport 2.6, backport 2.7

#8802 chore(setuptools_scm): add comment explaining version scheme
  pyproject.toml
Labels: changelog/no-changelog

#8806 ci: skip forkserver multiprocessing profiling test because it is unreliable
  tests/profiling/test_main.py
Labels: changelog/no-changelog

#8805 chore: update changelog for version 2.7.5
  CHANGELOG.md
Labels: changelog/no-changelog

#8807 ci(telemetry): expect observed test result
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog
