Repository DataDog/dd-trace-py, pull requests merged in 2024-04, with the labels that each got.

#8812 fix(starlette): don't crash on functions without `__name__`
  ddtrace/contrib/starlette/patch.py
  releasenotes/notes/fix-starlette-background-67d4822042028d6b.yaml
  tests/contrib/starlette/app.py
  tests/snapshots/tests.contrib.starlette.test_starlette.test_background_task.json
Labels: backport 2.5, backport 2.6, backport 2.7

#8811 chore(serverless): add more upstream variables for benchmark notification
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#8813 ci: parallel system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI, backport 2.5, backport 2.6, backport 2.7

#8810 chore: depend on ddsketch 3
  .riot/requirements/1b57ac2.txt
  hatch.toml
  pyproject.toml
  riotfile.py
Labels: changelog/no-changelog, backport 2.7

#8820 ci(telemetry): only allow get_events to return each event one time
  tests/conftest.py
  tests/telemetry/test_telemetry_metrics.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#8816 fix(iast): set iast instrumented metrics at runtime, not at request time
  ddtrace/appsec/_handlers.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/test_flask_telemetry.py
Labels: changelog/no-changelog, ASM

#8792 chore(ci_visibility): flesh out support for ITR in manual API
  ddtrace/ext/ci_visibility/_ci_visibility_base.py
  ddtrace/ext/ci_visibility/api.py
  ddtrace/internal/ci_visibility/api/ci_base.py
  ddtrace/internal/ci_visibility/api/ci_module.py
  ddtrace/internal/ci_visibility/api/ci_session.py
  ddtrace/internal/ci_visibility/api/ci_suite.py
  ddtrace/internal/ci_visibility/api/ci_test.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/api/fake_runner_all_fail.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_suite_level.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_test_level.py
  tests/ci_visibility/api/fake_runner_all_pass.py
  tests/ci_visibility/api/fake_runner_all_skip.py
  tests/ci_visibility/api/fake_runner_mix_fail.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_suite_level.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_test_level.py
  tests/ci_visibility/api/fake_runner_mix_pass.py
  tests/ci_visibility/api/test_api_fake_runners.py
  tests/ci_visibility/test_ci_visibility.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_skip.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_pass.json
Labels: changelog/no-changelog

#8809 chore(tracer): use importlib metadata to infer flask version as the old method is deprecated
  ddtrace/contrib/flask/patch.py
  ddtrace/internal/packages.py
  tests/appsec/contrib_appsec/test_flask.py
Labels: changelog/no-changelog

#8825 ci: parallel system tests [backport 2.7]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#8808 chore(core): memoize executioncontext span deprecation warnings
  ddtrace/internal/core/__init__.py
Labels: changelog/no-changelog

#8827 ci: parallel system tests [backport 2.5]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#8826 ci: parallel system tests [backport 2.6]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#8799 chore(ci_visibility): manual api: enforce absolute paths for sessions and source files
  ddtrace/ext/ci_visibility/_ci_visibility_base.py
  ddtrace/ext/ci_visibility/api.py
  ddtrace/internal/ci_visibility/api/ci_base.py
  tests/ci_visibility/api/test_ext_ci_visibility_api.py
  tests/ci_visibility/api/test_internal_ci_visibility_api.py
Labels: changelog/no-changelog

#8831 ci(tracer): mark unreliable test as flaky
  tests/tracer/runtime/test_metric_collectors.py
Labels: changelog/no-changelog

#8822 fix(profiling): default to libdatadog if autoinject/SSI is enabled
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/profiler.py
  ddtrace/profiling/scheduler.py
  ddtrace/settings/profiling.py
  lib-injection/dl_wheels.py
  lib-injection/sitecustomize.py
  releasenotes/notes/profiling-fix-protobuf-injection-d94f7c152681795c.yaml
Labels: backport 2.7

#8843 ci: fix telemetry test
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, backport 2.7

#8841 fix(iast): remove native exceptions
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  releasenotes/notes/iast-fix-native-exceptions-e6299dc2b9ad54d3.yaml
  tests/appsec/iast/aspects/test_add_aspect.py
Labels: ASM, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8845 chore(asm): remove WAF timeout & WAF error log metric
  ddtrace/appsec/_processor.py
  tests/appsec/appsec/test_telemetry.py
Labels: changelog/no-changelog, ASM, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8848 ci: trigger telemetry tests on settings changes
  tests/.suitespec.json
Labels: changelog/no-changelog, CI, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#8842 feat(asm): telemetry sends appsec sca env var
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  docs/configuration.rst
  releasenotes/notes/appsec-sca-env-var-telemetry-1f46bea88a86fc39.yaml
  tests/telemetry/test_writer.py
Labels: ASM

#8804 chore(ci_visibility): remove core from CI Visibilty ownership
  .github/CODEOWNERS
Labels: changelog/no-changelog

#8837 chore(dev): remove reference to SDG from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#8858 ci: mark unreliable tests as flaky
  tests/contrib/kafka/test_kafka.py
  tests/opentelemetry/test_trace.py
Labels: changelog/no-changelog

#8836 chore: update changelog for version 2.7.6
  CHANGELOG.md
Labels: changelog/no-changelog

#8829 ci: k8s lib injection: migration
  .github/workflows/lib-injection.yml
Labels: changelog/no-changelog, CI, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#8870 refactor(profiling): patch for native ID if necessary
  ddtrace/profiling/_threading.pyx
Labels: changelog/no-changelog, Profiling

#8864 fix: support all valid package version specifiers in version checks
  ddtrace/contrib/aioredis/patch.py
  ddtrace/contrib/algoliasearch/patch.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/starlette/patch.py
  releasenotes/notes/versions-arent-just-ints-909349433f58b79b.yaml
  tests/contrib/algoliasearch/test.py
Labels: backport 2.6, backport 2.7, backport 2.8

#8859 fix(kafka): handle empty message lists
  ddtrace/contrib/kafka/patch.py
  releasenotes/notes/kafka-empty-message-list-d4358af8f4b72567.yaml
  tests/contrib/kafka/test_kafka.py
Labels: backport 2.6, backport 2.7, backport 2.8

#8880 ci: checkout PR head instead of merge branch when running system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, backport 2.6, backport 2.7, backport 2.8

#8883 ci: disable appsec_iast_tdd_propagation suite temporarily
  tests/.suitespec.json
Labels: changelog/no-changelog, CI, backport 2.6, backport 2.7, backport 2.8

#8877 chore: release script make create_pull all kwargs, better file adding for changelog
  scripts/release.py
Labels: changelog/no-changelog

#8890 chore(serverless): add user email for benchmark notification
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#8814 feat(llmobs): support langchain expression language invocation and batching
  ddtrace/contrib/langchain/patch.py
  releasenotes/notes/support-lcel-378960fbe6b670bc.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_acall.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_batch.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_batch_311.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_batch_async.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_batch_py311.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_call.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_call_complicated.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_nested.yaml
  tests/contrib/langchain/conftest.py
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/langchain/test_langchain_patch.py
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_batch.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_batch_311.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_batch_async.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_complicated.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_nested.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_simple.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_simple_async.json
Labels: MLObs

#8675 ci: display backtrace from core dumps
  .circleci/config.templ.yml
  scripts/bt
  scripts/run-test-suite
Labels: changelog/no-changelog

#8895 chore: update changelog for version 2.7.7
  CHANGELOG.md
Labels: changelog/no-changelog

#8874 docs: update changelog for version 2.8.0 via release script
  CHANGELOG.md
Labels: changelog/no-changelog

#8872 fix: enable iast with `patch_all` function (APPSEC-52389)
  ddtrace/_monkey.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/iast/__init__.py
  ddtrace/bootstrap/preload.py
  ddtrace/internal/module.py
  releasenotes/notes/iast-feat-iast-patch-all-d7c67efc374338dd.yaml
  tests/appsec/iast/fixtures/entrypoint/app_create_app_enable_ddtrace_iast.py
  tests/appsec/iast/fixtures/entrypoint/app_create_app_patch_all.py
  tests/appsec/iast/fixtures/entrypoint/app_create_app_patch_all_enable_iast_propagation.py
  tests/appsec/iast/fixtures/entrypoint/app_main_patched.py
  tests/appsec/iast/fixtures/entrypoint/views.py
  tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
Labels: ASM, backport 2.8

#8868 fix(ci_visibility): add specific 20s timeout for ITR skippable tests request
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/fix-ci_visibility-increase-itr-skippable-tests-timeout-c92111aeec8624a9.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: CI App, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#8906 fix(asm): remove datadog.api_security metrics
  ddtrace/appsec/_api_security/api_manager.py
  releasenotes/notes/removing_api_security_metrics-4b6a6ba8643b5ab3.yaml
Labels: enhancement, ASM, backport 2.5, backport 2.6, backport 2.7, backport 2.8

#8913 fix(asm): remove datadog.api_security metrics [backport 2.7]
  ddtrace/appsec/_api_security/api_manager.py
  releasenotes/notes/removing_api_security_metrics-4b6a6ba8643b5ab3.yaml
Labels: ASM, backport 2.5, backport 2.6

#8916 chore(asm): add support for headers always sent when ASM enabled
  ddtrace/appsec/_processor.py
  tests/appsec/contrib_appsec/utils.py
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
Labels: changelog/no-changelog, ASM

#8905 fix(iast): aes cipher functions break applications if iast is enabled
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  releasenotes/notes/iast-fix-cipher-error-48882bb289eb4353.yaml
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast/fixtures/taint_sinks/weak_algorithms.py
  tests/appsec/iast/taint_sinks/test_weak_cipher.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/iast_tdd_propagation/flask_orm_app.py
  tests/appsec/iast_tdd_propagation/flask_taint_sinks_app.py
  tests/appsec/iast_tdd_propagation/flask_taint_sinks_views.py
  tests/appsec/iast_tdd_propagation/test_flask.py
Labels: ASM, backport 2.6, backport 2.7, backport 2.8

#8919 chore(asm): changes so ssrf+cmdi work
  ddtrace/_monkey.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
Labels: changelog/no-changelog, ASM

#8884 fix(iast): taint_structure setting wrong source on map elements
  ddtrace/appsec/_iast/_taint_utils.py
  releasenotes/notes/asm-fix-wrong-source-on-taint_structure-20372c6974c70313.yaml
  tests/appsec/iast/test_taint_utils.py
Labels: ASM, backport 2.6, backport 2.7, backport 2.8

#8931 chore(langchain): mark flaky chain test
  tests/contrib/langchain/test_langchain_community.py
Labels: changelog/no-changelog

#8925 chore(asm): add waf integration headers to be reported always with asm
  ddtrace/appsec/_processor.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#8934 chore(langchain): cleanup unused test cassettes
  tests/contrib/langchain/cassettes/langchain/_openai_pinecone_similarity_search.yaml
  tests/contrib/langchain/cassettes/langchain/openai_math_chain.yaml
  tests/contrib/langchain/cassettes/langchain/openai_paraphrase_39.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_batch_py311.yaml
Labels: changelog/no-changelog

#8776 chore(asm): add ssrf support for urllib.request
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_processor.py
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#8941 chore(langchain): mark additional tests as flaky
  tests/contrib/langchain/test_langchain_community.py
Labels: changelog/no-changelog

#8926 fix(iast): aes cipher functions break applications if iast is enabled [backport 2.5]
  .riot/requirements/1221a04.txt
  .riot/requirements/131666a.txt
  .riot/requirements/16ed652.txt
  .riot/requirements/17b5eda.txt
  .riot/requirements/195f6e3.txt
  .riot/requirements/1a1ddb4.txt
  .riot/requirements/1b20bb6.txt
  .riot/requirements/1e81527.txt
  .riot/requirements/2b94418.txt
  .riot/requirements/6b35ef3.txt
  .riot/requirements/af0a803.txt
  .riot/requirements/b9aa094.txt
  .riot/requirements/c650a62.txt
  .riot/requirements/e53ccba.txt
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  releasenotes/notes/iast-fix-cipher-error-48882bb289eb4353.yaml
  riotfile.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast/fixtures/taint_sinks/weak_algorithms.py
  tests/appsec/iast/taint_sinks/test_weak_cipher.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/iast_tdd_propagation/flask_orm_app.py
  tests/appsec/iast_tdd_propagation/flask_taint_sinks_app.py
  tests/appsec/iast_tdd_propagation/flask_taint_sinks_views.py
  tests/appsec/iast_tdd_propagation/test_flask.py
Labels: ASM

#8930 ci: fix iast integration flaky tests
  .riot/requirements/1147cef.txt
  .riot/requirements/1221a04.txt
  .riot/requirements/131666a.txt
  .riot/requirements/16ed652.txt
  .riot/requirements/173e759.txt
  .riot/requirements/17b5eda.txt
  .riot/requirements/1a1ddb4.txt
  .riot/requirements/1b0d603.txt
  .riot/requirements/1e2d655.txt
  .riot/requirements/1e81527.txt
  .riot/requirements/1fb9968.txt
  .riot/requirements/2b94418.txt
  .riot/requirements/60a424f.txt
  .riot/requirements/e53ccba.txt
  riotfile.py
  tests/appsec/iast_tdd_propagation/test_flask.py
Labels: changelog/no-changelog, ASM, backport 2.7, backport 2.8

#8953 fix(setuptools_scm): backport setuptools_scm version scheme to guess-next-dev [backport 2.8]
  pyproject.toml
Labels: changelog/no-changelog, CI

#8955 chore(iast): metrics order
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
Labels: changelog/no-changelog, ASM

#8958 chore(iast): update type checking
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
Labels: changelog/no-changelog, ASM

#8959 ci: partially revert "ci: fix iast integration flaky tests (#8930)"
  .riot/requirements/1147cef.txt
  .riot/requirements/1221a04.txt
  .riot/requirements/131666a.txt
  .riot/requirements/16ed652.txt
  .riot/requirements/173e759.txt
  .riot/requirements/17b5eda.txt
  .riot/requirements/1a1ddb4.txt
  .riot/requirements/1b0d603.txt
  .riot/requirements/1e2d655.txt
  .riot/requirements/1e81527.txt
  .riot/requirements/1fb9968.txt
  .riot/requirements/2b94418.txt
  .riot/requirements/e53ccba.txt
Labels: changelog/no-changelog, ASM, CI, backport 2.7, backport 2.8

#8947 docs: update sampling rule configuration
  docs/configuration.rst
Labels: changelog/no-changelog, backport 2.8

#8960 chore(langchain): change batch tests to be less flaky
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_batch.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_batch_311.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_batch_async.yaml
  tests/contrib/langchain/test_langchain_community.py
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_batch.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_batch_311.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_batch_async.json
Labels: changelog/no-changelog

#8945 ci: fix starlette framework test
  .github/workflows/test_frameworks.yml
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/starlette/patch.py
Labels: changelog/no-changelog

#8966 feat(llmobs): change error field to status
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog

#8961 feat(tracer): isolated tracer flare logic
  ddtrace/_logger.py
  ddtrace/internal/flare.py
  ddtrace/internal/logger.py
  docker-compose.yml
  riotfile.py
  tests/.suitespec.json
  tests/internal/test_tracer_flare.py
Labels: changelog/no-changelog

#8950 feat(llmobs): add openai tool function names in captured messages
  ddtrace/contrib/openai/utils.py
  ddtrace/llmobs/_integrations/openai.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog

#8938 fix(pymongo): fix client validation issue
  ddtrace/contrib/pymongo/client.py
  ddtrace/contrib/pymongo/patch.py
  releasenotes/notes/pymongo-fix-session-validation-error-1a05f8ad45bbbc35.yaml
  tests/contrib/pymongo/test.py
Labels: backport 2.6, backport 2.7, backport 2.8

#8956 chore(asm): exploit prevention ssrf support for requests
  ddtrace/appsec/_common_module_patches.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/requests/patch.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#8973 fix(iast): `None` as `module_path` at `astpatch_module`
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/fix-ast-patching-none-module_path-4f66c1e35169d5e4.yaml
  tests/appsec/iast/_ast/test_ast_patching.py
Labels: bug, ASM, backport 2.6, backport 2.7, backport 2.8

#8975 chore: fix grpc contrib codeowners
  .github/CODEOWNERS
Labels: changelog/no-changelog, ASM

#8876 chore(internal): third-party path inference
  ddtrace/internal/packages.py
  ddtrace/internal/third-party.tar.gz
  tests/.suitespec.json
  tests/internal/test_packages.py
Labels: changelog/no-changelog

#8968 fix(llmobs): add error handling if span is malformed
  ddtrace/llmobs/_trace_processor.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog, MLObs

#8983 chore(kafka): return/raise after resolving try/finally
  ddtrace/contrib/kafka/patch.py
  tests/contrib/kafka/test_kafka.py
Labels: changelog/no-changelog

#8948 chore(internal): add agentless mode for telemetry writer
  ddtrace/internal/ci_visibility/telemetry/coverage.py
  ddtrace/internal/ci_visibility/telemetry/events.py
  ddtrace/internal/ci_visibility/telemetry/git.py
  ddtrace/internal/ci_visibility/telemetry/itr.py
  ddtrace/internal/ci_visibility/telemetry/utils.py
  ddtrace/internal/telemetry/writer.py
  tests/conftest.py
  tests/integration/test_settings.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
  tests/telemetry/utils.py
Labels: changelog/no-changelog

#8984 chore: update changelog for version 2.6.10
  CHANGELOG.md
Labels: changelog/no-changelog

#8901 chore(botocore): abstract integration from products in patch entrypoint
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/utils.py
Labels: changelog/no-changelog

#8937 chore(botocore): refactor kinesis module
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/stepfunctions.py
Labels: changelog/no-changelog

#8989 chore(botocore): decouple kinesis integration from tracing and datastreams monitoring
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/internal/datastreams/botocore.py
Labels: changelog/no-changelog

#8954 chore(iast): improve taint tracking logs
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_replace_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM

#8993 chore(botocore): refactor sqs integration
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/botocore/services/sqs.py
  ddtrace/contrib/botocore/utils.py
  ddtrace/internal/datastreams/botocore.py
Labels: changelog/no-changelog

#9000 chore(iast): fix metrics log error format
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
Labels: changelog/no-changelog, ASM

#8707 fix(grpc): ensure interceptor args are correctly parsed
  ddtrace/contrib/grpc/aio_client_interceptor.py
  ddtrace/contrib/grpc/patch.py
  ddtrace/internal/utils/__init__.py
  releasenotes/notes/grpc-fix-interceptors-f596e028ef9dbcd5.yaml
  tests/contrib/grpc_aio/test_grpc_aio.py
Labels: backport 2.7

#8988 feat(llmobs): store function name for function call cases
  ddtrace/contrib/openai/utils.py
  ddtrace/llmobs/_integrations/openai.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog

#9001 chore(iast): fix metrics log error typo
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
Labels: changelog/no-changelog, ASM

#9011 chore(iast): validate iast_debug env var as bool
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/aspects/test_add_aspect.py
Labels: changelog/no-changelog, ASM

#8725 chore(di): use frame line on snapshot
  ddtrace/debugging/_exception/auto_instrument.py
  tests/debugging/exception/test_auto_instrument.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8974 chore(ci): update pytest 3.x dependencies for celery and flask_cache to 4.x
  .riot/requirements/10d81a7.txt
  .riot/requirements/118d2ec.txt
  .riot/requirements/11d2116.txt
  .riot/requirements/14a42dd.txt
  .riot/requirements/2ca9efa.txt
  .riot/requirements/a4ee05c.txt
  riotfile.py
Labels: changelog/no-changelog

#9022 fix(internal): handle missing lib_config entry
  ddtrace/settings/config.py
  releasenotes/notes/fix-missing-lib_config-f2c0a6a40f525bff.yaml
  tests/internal/test_settings.py
Labels: bug, backport 2.6, backport 2.7, backport 2.8

#9033 chore(asm): update libddwaf 1.17.0
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_exploit_prevention/stack_traces.py
  ddtrace/appsec/_processor.py
  setup.py
  tests/appsec/contrib_appsec/utils.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#8981 chore: update changelog for version 2.8.1
  CHANGELOG.md
Labels: changelog/no-changelog

#8946 fix(sampling): sample floats with zero decimal
  ddtrace/sampling_rule.py
  releasenotes/notes/fix-how-we-sample-on-floats-4c69b6286e86ba25.yaml
Labels: backport 2.8

#9034 chore(asm): add better support for recent versions of fastapi starlette httpx in unit tests
  tests/appsec/contrib_appsec/test_fastapi.py
Labels: changelog/no-changelog, ASM

#8982 chore: update changelog for version 2.7.8
  CHANGELOG.md
Labels: changelog/no-changelog

#9027 chore(serverless): add `CI_COMMIT_TAG` to be sent downstream
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog, serverless

#9032 fix(profiling): tag serialisation in HTTP exporter
  ddtrace/profiling/exporter/http.py
  releasenotes/notes/fix-profiling-exporter-tags-f19c6cf93cbe1502.yaml
Labels: backport 2.8

#8999 chore(ci_visibility): only import ddtrace when pytest ddtrace module is enabled
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/contrib/pytest/constants.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/contrib/pytest_bdd/_plugin.py
  ddtrace/contrib/pytest_bdd/plugin.py
  ddtrace/contrib/pytest_benchmark/_plugin.py
  ddtrace/contrib/pytest_benchmark/plugin.py
  tests/contrib/pytest_bdd/test_pytest_bdd.py
Labels: changelog/no-changelog

#8951 chore(ci): collect coverage data
  .circleci/config.templ.yml
  riotfile.py
  scripts/run-test-suite
Labels: changelog/no-changelog, CI

#9035 chore(iast): improve taint tracking logs II
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
Labels: changelog/no-changelog, ASM

#9002 chore(botocore): refactor sqs integration
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/sqs.py
Labels: changelog/no-changelog

#9005 chore(botocore): refactor stepfunctions integration
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/stepfunctions.py
Labels: changelog/no-changelog

#9044 chore: add pygoat tests
  .circleci/config.templ.yml
  .riot/requirements/106f2d7.txt
  .riot/requirements/15c5d22.txt
  .riot/requirements/1828aa7.txt
  .riot/requirements/19e4934.txt
  .riot/requirements/1ad3ffa.txt
  .riot/requirements/1bb4e1c.txt
  .riot/requirements/1d8f8a6.txt
  .riot/requirements/5798e05.txt
  .riot/requirements/9a8d5f9.txt
  .riot/requirements/aef16c8.txt
  .riot/requirements/d7bcb59.txt
  docker-compose.yml
  riotfile.py
  tests/appsec/integrations/pygoat_tests/Dockerfile.pygoat.2.0.1
  tests/appsec/integrations/pygoat_tests/__init__.py
  tests/appsec/integrations/pygoat_tests/fixtures/auth_user.json
  tests/appsec/integrations/pygoat_tests/fixtures/introduction_login.json
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: changelog/no-changelog, ASM, testing

#9062 chore: update changelog for version 2.8.2
  CHANGELOG.md
Labels: changelog/no-changelog

#9060 chore: update changelog for version 2.6.11
  CHANGELOG.md
Labels: changelog/no-changelog

#9057 chore(iast): improve taint tracking logs II
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
Labels: changelog/no-changelog, ASM

#9054 ci: avoid failure if there are no coverage files
  .circleci/config.templ.yml
Labels: changelog/no-changelog, CI

#9067 fix(iast): fix `api_set_ranges` return type
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
Labels: changelog/no-changelog, ASM

#8949 fix(logging): make get_log_correlation_context return 64-bit trace id
  ddtrace/_trace/context.py
  ddtrace/_trace/tracer.py
  releasenotes/notes/log_correlation_64_bit-a0a8f64116856534.yaml
  tests/tracer/test_correlation_log_context.py
Labels: backport 2.6, backport 2.7, backport 2.8

#9065 chore(iast): clean native code
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
Labels: changelog/no-changelog, ASM

#9061 chore: update changelog for version 2.7.9
  CHANGELOG.md
Labels: changelog/no-changelog

#9070 fix(iast): pybind11 flto option
  ddtrace/appsec/_iast/_taint_tracking/_vendor/pybind11/tools/pybind11Common.cmake
Labels: changelog/no-changelog, ASM

#9045 fix(tracer): fix raw uri report
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/wsgi/wsgi.py
  releasenotes/notes/raw_uri_for_wsgi-35328265e7a44028.yaml
  tests/appsec/contrib_appsec/utils.py
Labels: ASM, Tracing

#9039 ci: run ulimited -c unlimited right before scripts/run-test-suite
  .circleci/config.templ.yml
Labels: changelog/no-changelog, CI

#9050 ci: disable itr for appsec tests
  riotfile.py
Labels: changelog/no-changelog, ASM, CI

#9073 ci: ensure coverage cli doesn't exit with code 1
  .circleci/config.templ.yml
Labels: changelog/no-changelog, CI

#9072 fix(iast): fix `api_set_ranges` return type [backport 2.8]
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
Labels: changelog/no-changelog, ASM

#9008 chore(serverless): lazy load slow package ddtrace.internal.wrapping
  ddtrace/profiling/_threading.pyx
Labels: changelog/no-changelog

#9047 refactor: compress the packages index
  ddtrace/internal/packages.py
  tests/internal/test_packages.py
Labels: changelog/no-changelog

#8885 fix(profiling): fix deprecated ddtrace usage
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/event.py
  releasenotes/notes/profiling-fix-deprecated-span-usage-512723136f1682d2.yaml
  tests/profiling/test_profiler.py
Labels: backport 2.7, backport 2.8

#9063 feat(llmobs): introduce env var to avoid submitting APM traces
  ddtrace/llmobs/_trace_processor.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog

#9023 chore(botocore): refactor the bedrock integration
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/botocore/services/bedrock.py
  tests/contrib/botocore/test_bedrock.py
Labels: changelog/no-changelog

#9041 chore(opentelemetry): avoid unnecessary use of core API in opentelemetry module
  ddtrace/opentelemetry/_span.py
  tests/opentelemetry/test_span.py
Labels: changelog/no-changelog

#9009 feat(llmobs): modify LLMObs.annotate() to meet new span schema
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/openai.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/utils.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog

#8994 chore(serverless): lazy load slow package imports
  ddtrace/_logger.py
  ddtrace/internal/compat.py
  ddtrace/internal/utils/http.py
  tests/internal/test_serverless.py
Labels: changelog/no-changelog, serverless

#9036 chore(botocore): deduplicate botocore utility function calls
  ddtrace/_trace/trace_handlers.py
  ddtrace/_trace/utils.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/sqs.py
  ddtrace/contrib/botocore/services/stepfunctions.py
  ddtrace/contrib/botocore/utils.py
Labels: changelog/no-changelog

#9082 ci: add timeout to django framework tests [backport 2.6]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9085 feat: add os.path.join aspect
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOsPathJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOsPathJoin.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/_aspects_exports.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_ospathjoin_aspect.py
  tests/appsec/iast/aspects/test_ospathjoin_aspect_fixtures.py
  tests/appsec/iast/fixtures/aspects/module_functions.py
Labels: changelog/no-changelog, ASM

#9089 fix(telemetry): logs payload format
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry_metrics.py
Labels: changelog/no-changelog, backport 2.6, backport 2.7, backport 2.8

#9081 ci: add timeout to django framework tests [backport 2.8]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9084 ci: native arm64 build
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, CI, backport 2.6, backport 2.7, backport 2.8

#9031 chore(rcm): include more details with invalid payload
  ddtrace/internal/remoteconfig/client.py
  tests/internal/remoteconfig/test_remoteconfig.py
Labels: changelog/no-changelog, backport 2.8

#9051 test: lint produced deb and rpm packages
  .gitlab-ci.yml
Labels: changelog/no-changelog, mergequeue-status: rejected

#9106 fix(iast): fstring int formatting
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/fix-fstring-zeropadding-e8e463a4d8623040.yaml
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/fixtures/aspects/str_methods_py3.py
Labels: bug, ASM, backport 2.6, backport 2.7, backport 2.8

#9095 chore: add base split-to-ranges helper
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  scripts/cppcheck.sh
  tests/appsec/iast/aspects/test_aspect_helpers.py
Labels: changelog/no-changelog, ASM

#9109 fix(iast): fstring int formatting [backport 2.6]
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/fix-fstring-zeropadding-e8e463a4d8623040.yaml
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/fixtures/aspects/str_methods_py3.py
Labels: ASM

#9108 fix(iast): fstring int formatting [backport 2.7]
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/fix-fstring-zeropadding-e8e463a4d8623040.yaml
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/fixtures/aspects/str_methods_py3.py
Labels: ASM

#9107 fix(iast): fstring int formatting [backport 2.8]
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/fix-fstring-zeropadding-e8e463a4d8623040.yaml
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/fixtures/aspects/str_methods_py3.py
Labels: ASM

#9102 ci: native arm64 build [backport 2.6]
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, CI

#9076 refactor: compress the packages index [backport #9047 to 2.8]
  ddtrace/internal/packages.py
  tests/internal/test_packages.py
Labels: changelog/no-changelog, backport 2.8

#9110 ci: temporarily disable vertica test suite
  .circleci/config.templ.yml
  docker-compose.yml
Labels: changelog/no-changelog, backport 1.20, backport 2.6, backport 2.7, backport 2.8

#9116 ci: temporarily disable vertica test suite [backport 1.20]
  .circleci/config.templ.yml
  docker-compose.yml
Labels: changelog/no-changelog

#9118 ci: temporarily disable vertica test suite [backport 2.6]
  .circleci/config.templ.yml
  docker-compose.yml
Labels: changelog/no-changelog

#9119 ci: temporarily disable vertica test suite [backport 2.7]
  .circleci/config.templ.yml
  docker-compose.yml
Labels: changelog/no-changelog, CI

#9113 feat: add IAST propagation for string' split, rsplit and splitlines
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/_aspects_exports.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  tests/appsec/iast/aspects/test_aspect_helpers.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
Labels: changelog/no-changelog, ASM

#9115 feat(asm): env var and release note
  ddtrace/settings/asm.py
  releasenotes/notes/exploit_prevention_feature_LFI_SSRF-5be3b699341eadb1.yaml
Labels: ASM

#9111 fix(llmobs): catch errors when trying to create Messages
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/utils.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_utils.py
Labels: changelog/no-changelog

#9121 chore: update changelog for version 2.8.3
  CHANGELOG.md
Labels: changelog/no-changelog

#9125 chore: update changelog for version 2.7.10 via release script
  CHANGELOG.md
Labels: changelog/no-changelog

#9123 ci(ci-visibility): expect observed test result
  tests/integration/test_integration_civisibility.py
Labels: changelog/no-changelog

#9124 ci: update info output tests to be less brittle
  tests/commands/test_runner.py
Labels: changelog/no-changelog, backport 2.6, backport 2.7, backport 2.8

#9096 chore(redis): separate tracing and redis details in ddtrace._trace.utils_redis
  ddtrace/_trace/trace_handlers.py
  ddtrace/_trace/utils_redis.py
  ddtrace/contrib/aioredis/patch.py
  ddtrace/contrib/aredis/patch.py
  ddtrace/contrib/redis/asyncio_patch.py
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/redis_utils.py
  ddtrace/contrib/yaaredis/patch.py
  tests/.suitespec.json
Labels: changelog/no-changelog

#9120 chore: update changelog for version 2.6.12
  CHANGELOG.md
Labels: changelog/no-changelog

#9114 feat: add a bunch (but not all) of aspects for os.path
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOsPathJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOsPathJoin.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/_aspects_exports.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_ospath_aspects.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_ospathjoin_aspect.py
  tests/appsec/iast/aspects/test_ospathjoin_aspect_fixtures.py
  tests/appsec/iast/fixtures/aspects/module_functions.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
Labels: changelog/no-changelog, ASM

#9098 feat(llmobs): add eval metric writer class
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/_writer.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/langchain/conftest.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/openai/conftest.py
  tests/llmobs/conftest.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_eval_metric_writer.send_score_metric.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_eval_metric_writer.test_send_categorical_metric.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_eval_metric_writer.test_send_metric_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_eval_metric_writer.test_send_multiple_events.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_eval_metric_writer.test_send_numerical_metric.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_eval_metric_writer.test_send_score_metric.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_eval_metric_writer.test_send_timed_events.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_chat_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_multiple_events.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_timed_events.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_writer.test_send_on_exit.yaml
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_eval_metric_writer.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_span_writer.py
  tests/llmobs/test_llmobs_trace_processor.py
  tests/llmobs/test_llmobs_writer.py
Labels: changelog/no-changelog

#9127 chore: update apm-framework-integrations to apm-idm-python
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9104 chore: swap includes/excludes semantics in 3rd-party detection
  ddtrace/internal/packages.py
  ddtrace/settings/third_party.py
  tests/internal/test_packages.py
Labels: changelog/no-changelog
