Repository DataDog/dd-trace-py, pull requests merged in 2024-05, with the labels that each got.

#9099 feat(llmobs): support submitting LLMObs custom eval metrics
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  ddtrace/llmobs/utils.py
  tests/llmobs/_utils.py
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_eval_metric_writer.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_span_writer.py
Labels: changelog/no-changelog

#9013 chore: exclude non-user symbols from symbol DB
  ddtrace/internal/packages.py
  ddtrace/internal/symbol_db/symbols.py
  tests/internal/symbol_db/test_symbols.py
Labels: changelog/no-changelog

#9087 chore(botocore): abstract away propagation header extraction code
  ddtrace/_trace/trace_handlers.py
  ddtrace/_trace/utils.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/sqs.py
  ddtrace/contrib/botocore/services/stepfunctions.py
  ddtrace/contrib/botocore/utils.py
  ddtrace/internal/datastreams/botocore.py
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#9145 fix(redis): added back tracer_utils_redis with deprecation warn
  ddtrace/contrib/trace_utils_redis.py
  tests/.suitespec.json
Labels: changelog/no-changelog

#9146 chore: add memcheck tests for the new splitter aspects
  tests/appsec/iast/fixtures/propagation_path.py
Labels: changelog/no-changelog, ASM

#9144 ci: mark some flaky tests
  riotfile.py
  tests/contrib/celery/test_integration.py
  tests/internal/test_tracer_flare.py
Labels: changelog/no-changelog

#9052 chore(dbm): add peer service precursor tag to sql injection
  ddtrace/propagation/_database_monitoring.py
  tests/contrib/aiomysql/test_aiomysql.py
  tests/contrib/shared_tests.py
Labels: changelog/no-changelog

#9147 chore(asm): add support for blocking request in rasp flask
  .github/CODEOWNERS
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/internal/_exceptions.py
  tests/.suitespec.json
  tests/appsec/appsec/rules-rasp-blocking.json
  tests/appsec/appsec/test_asm_request_context.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/rules.py
Labels: changelog/no-changelog, ASM

#8783 chore(telemetry): add item for instrumentation config id
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#9134 feat(llmobs): add retrieval and embedding spans
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/decorators.py
  ddtrace/llmobs/utils.py
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_utils.py
Labels: changelog/no-changelog, MLObs

#8902 chore(ci): simplify the flask simple benchmark suite
  .gitlab/benchmarks.yml
  .gitlab/benchmarks/bp-runner.yml
  benchmarks/flask_simple/app.py
  benchmarks/flask_simple/gunicorn.conf.py
  benchmarks/flask_simple/requirements_scenario.txt
  benchmarks/flask_simple/scenario.py
  benchmarks/flask_simple/utils.py
Labels: changelog/no-changelog

#9155 fix: better None protection when tainting a grpc message
  ddtrace/contrib/grpc/client_interceptor.py
  releasenotes/notes/asm-gprc-not-none-788b4b435b931a11.yaml
Labels: ASM, backport 2.9

#9157 fix(grpc): resolve issue with incorrect gRPC response being returned
  ddtrace/appsec/_handlers.py
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/internal/core/event_hub.py
Labels: changelog/no-changelog, backport 2.9

#8932 chore(ci): add OCI packaging
  .gitlab-ci.yml
  .gitlab/build-oci.sh
Labels: changelog/no-changelog

#9160 fix(grpc): resolve issue with incorrect gRPC response being returned [backport 2.9]
  ddtrace/appsec/_handlers.py
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/internal/core/event_hub.py
Labels: changelog/no-changelog

#9138 chore(redis): loosen coupling between instrumentation and product
  ddtrace/_trace/trace_handlers.py
  ddtrace/_trace/utils_redis.py
  ddtrace/contrib/aioredis/patch.py
  ddtrace/contrib/aredis/patch.py
  ddtrace/contrib/redis/asyncio_patch.py
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/redis_utils.py
  ddtrace/contrib/rediscluster/patch.py
  ddtrace/contrib/yaaredis/patch.py
Labels: changelog/no-changelog

#9151 chore(asm): add support for content-length header with asm blocked response
  ddtrace/_trace/trace_handlers.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#9153 chore(iast): add SSRF support for urllib3
  .riot/requirements/18695ab.txt
  .riot/requirements/1aedbda.txt
  .riot/requirements/4628049.txt
  .riot/requirements/58881b9.txt
  .riot/requirements/63b44e2.txt
  .riot/requirements/aba89a0.txt
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/contrib/urllib3/patch.py
  riotfile.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
Labels: changelog/no-changelog, ASM

#9141 fix: pytest deadlock when using gevent
  .riot/requirements/17fe3fa.txt
  .riot/requirements/1b90fc9.txt
  .riot/requirements/1d12360.txt
  .riot/requirements/1d45085.txt
  .riot/requirements/1ea9ac5.txt
  .riot/requirements/27d0ff3.txt
  .riot/requirements/2d19e52.txt
  .riot/requirements/61891b4.txt
  .riot/requirements/d171c08.txt
  .riot/requirements/daaf281.txt
  .riot/requirements/de578a7.txt
  ddtrace/__init__.py
  ddtrace/bootstrap/preload.py
  ddtrace/internal/runtime/runtime_metrics.py
  releasenotes/notes/fix-telemetry-writer-initialization-163b1effc09d948f.yaml
  riotfile.py
  tests/ci_visibility/test_cli.py
  tests/telemetry/test_telemetry.py
Labels: backport 2.8, backport 2.9

#9170 ci: mark flaky tests in the profile suite
  tests/profiling/collector/test_memalloc.py
  tests/profiling/collector/test_threading.py
  tests/profiling/test_uwsgi.py
Labels: changelog/no-changelog

#9176 fix(iast): false positives outside client code
  ddtrace/appsec/_iast/taint_sinks/_base.py
Labels: changelog/no-changelog, ASM

#9142 chore(profiling): pin version of echion dependency
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
Labels: changelog/no-changelog, backport 2.7, backport 2.8, backport 2.9

#9181 chore(ci): fix benchmarks images
  .gitlab/benchmarks.yml
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog

#9187 ci(profile): update outdated test assumption
  tests/profiling/collector/test_threading.py
Labels: changelog/no-changelog

#9188 fix(iast): unexpected Import error catching
  ddtrace/appsec/_iast/_loader.py
  releasenotes/notes/iast-fix-iast-import-error-2eedea126bb9d92d.yaml
  tests/appsec/app.py
  tests/appsec/iast_packages/packages/pkg_beautifulsoup4.py
  tests/appsec/iast_packages/test_packages.py
  tests/appsec/integrations/module_with_import_errors.py
  tests/appsec/integrations/test_flask_iast_patching.py
Labels: ASM, backport 2.9

#9175 chore(codeowners): add new directory to profiling
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9191 ci(profiling): adjust expectation
  tests/profiling/collector/test_threading.py
Labels: changelog/no-changelog

#8778 docs: add falcon version support
  docs/index.rst
Labels: changelog/no-changelog

#9164 chore(telemetry): remove _trace_enabled config option
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  tests/integration/test_settings.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#9193 chore: shorten time to close stale issues and PRs
  .github/workflows/stale.yml
Labels: changelog/no-changelog

#9174 chore(distributed_tracing): ensure last datadog parent id tag is always set
  ddtrace/internal/constants.py
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#9199 chore: different lifetimes for PRs and issues
  .github/workflows/stale.yml
Labels: changelog/no-changelog

#9182 fix(grpc): disable aio support
  ddtrace/contrib/grpc/patch.py
  releasenotes/notes/disable-76545e225ff1b3f4.yaml
  riotfile.py
Labels: backport 2.8, backport 2.9

#9173 fix(botocore): add defaults for response types and exception handling for different model providers
  ddtrace/contrib/botocore/services/bedrock.py
  releasenotes/notes/bedrock-response-key-checking-845ef1f191fcc120.yaml
Labels: MLObs, backport 2.8

#9194 fix(llmobs): format langchain schema inputs and outputs
  ddtrace/llmobs/_integrations/langchain.py
  tests/contrib/langchain/cassettes/langchain/openai_chain_schema_io.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_schema_io.yaml
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
Labels: changelog/no-changelog, MLObs, backport 2.8

#9196 fix(remoteconfig): fix remoteconfig when flare data in payload
  ddtrace/settings/config.py
  releasenotes/notes/rc_payload_fix-a03a98dcad934658.yaml
  tests/internal/test_settings.py
Labels: backport 2.8, backport 2.9

#9184 chore(di): include globals in snapshots
  ddtrace/debugging/_safety.py
  ddtrace/debugging/_signal/snapshot.py
  tests/debugging/test_debugger.py
  tests/debugging/test_encoding.py
  tests/debugging/test_safety.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9015 chore: skip non-user frames in exception replay
  ddtrace/debugging/_exception/auto_instrument.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9208 chore: mark telemetry test as flaky
  tests/appsec/iast/test_telemetry.py
Labels: changelog/no-changelog, ASM

#9210 fix(iast): improve header injection patching
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
Labels: changelog/no-changelog, ASM

#9206 chore(internal): add ``time_window`` parameter to rate limiter
  ddtrace/internal/rate_limiter.py
  tests/tracer/test_rate_limiter.py
Labels: changelog/no-changelog, ASM

#9212 chore(iast): remove deprecated dependency
  .riot/requirements/1c9c221.txt
  hatch.toml
  pyproject.toml
  riotfile.py
Labels: changelog/no-changelog, ASM

#9217 chore(iast): type hinting
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_ast/__init__.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/_utils.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/_iast/taint_sinks/weak_hash.py
  tests/appsec/iast/iast_utils.py
Labels: changelog/no-changelog, ASM

#9215 fix(iast): avoid crashing grpc patch if MessageMapContainer import fails
  ddtrace/appsec/_handlers.py
  releasenotes/notes/asm-gprc-import-not-crash-e13c48dcbcc1985e.yaml
  tests/appsec/iast/test_grpc_iast.py
Labels: ASM, backport 2.9

#9220 chore: more robust telemetry tests, immune to some internal sink points side effects
  tests/appsec/iast/test_telemetry.py
Labels: changelog/no-changelog, ASM

#9207 chore(asm): add SSRF support for http.client
  ddtrace/contrib/httplib/patch.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
Labels: changelog/no-changelog, ASM

#9225 chore: remove release note
  releasenotes/notes/asm-gprc-import-not-crash-e13c48dcbcc1985e.yaml
Labels: changelog/no-changelog, backport 2.9

#9223 chore(ci): disable flaky benchmark test
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog, ASM

#9230 fix: revert #9113, #9114, #9085
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/_aspects_exports.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  tests/appsec/iast/aspects/test_aspect_helpers.py
  tests/appsec/iast/aspects/test_ospath_aspects.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/fixtures/aspects/module_functions.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
Labels: changelog/no-changelog

#9213 chore(iast): remove flaky telemetry tests
  tests/appsec/integrations/test_flask_telemetry.py
Labels: changelog/no-changelog, ASM

#9234 fix(asm): ensure new aspects does not raise exceptions if there is no context
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
Labels: changelog/no-changelog, ASM, backport 2.9

#9237 chore(asm): update libddwaf to 1.18.0
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  setup.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#9240 fix(asm): ensure new aspects does not raise exceptions if there is no context [backport 2.9]
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/_aspects_exports.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  tests/appsec/iast/aspects/test_aspect_helpers.py
  tests/appsec/iast/aspects/test_ospath_aspects.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/fixtures/aspects/module_functions.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
Labels: changelog/no-changelog, ASM

#9209 chore(asm): add SSRF support for webbrowser.open
  .github/CODEOWNERS
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/contrib/webbrowser/__init__.py
  ddtrace/contrib/webbrowser/patch.py
  tests/.suitespec.json
  tests/appsec/iast/taint_sinks/test_ssrf.py
Labels: changelog/no-changelog, ASM

#9241 chore(iast): sqli and ssrf instrumented sink metric
  ddtrace/contrib/mysql/patch.py
  ddtrace/contrib/mysqldb/patch.py
  ddtrace/contrib/requests/patch.py
  ddtrace/contrib/sqlalchemy/patch.py
  ddtrace/contrib/sqlite3/patch.py
  ddtrace/contrib/urllib3/patch.py
  tests/appsec/iast/test_telemetry.py
Labels: changelog/no-changelog, ASM

#9244 fix(iast): ensure no side-effects in IAST encode aspect
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/aspects/test_side_effects.py
  tests/appsec/iast/iast_utils_side_effects.py
Labels: changelog/no-changelog, ASM, backport 2.9

#9224 chore(asm): add SSRF support for urllib.request
  .github/CODEOWNERS
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/contrib/urllib/__init__.py
  ddtrace/contrib/urllib/patch.py
  releasenotes/notes/asm-ssrf-expanded-cc7d8abaa3f9c7dd.yaml
  tests/.suitespec.json
  tests/appsec/iast/taint_sinks/test_ssrf.py
Labels: ASM

#9236 chore(ci): convert serverless slow import test to a subprocess test
  tests/internal/test_serverless.py
Labels: changelog/no-changelog

#9247 fix(asm): workaround disabling builtins.open aspects
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/asm-open-disabled-090eefa08b8b69a4.yaml
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/test_iast_propagation_path.py
Labels: ASM, backport 2.8, backport 2.9

#9231 revert(distributed_tracing): ensure last datadog parent id tag is always set
  ddtrace/internal/constants.py
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#9251 fix(asm): workaround disabling builtins.open aspects [backport 2.9]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/asm-open-disabled-090eefa08b8b69a4.yaml
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/test_iast_propagation_path.py
Labels: ASM

#9246 feat(asm): enable exploit prevention
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
  ddtrace/settings/asm.py
  releasenotes/notes/exploit_prevention_enabled-ae26036621f6140c.yaml
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec_snapshots.py
Labels: ASM

#9242 feat(llmobs): allow users to toggle on/off sending llmobs data
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_utils.py
  ddtrace/llmobs/decorators.py
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog

#9253 chore(ci): convert flask_sqli benchmark to use Flask test client instead of gunicorn
  .gitlab/benchmarks.yml
  benchmarks/bm/flask_utils.py
  benchmarks/flask_simple/scenario.py
  benchmarks/flask_sqli/app.py
  benchmarks/flask_sqli/gunicorn.conf.py
  benchmarks/flask_sqli/requirements_scenario.txt
  benchmarks/flask_sqli/scenario.py
  benchmarks/flask_sqli/utils.py
Labels: changelog/no-changelog

#9250 fix(llmobs): format langchain schema inputs and outputs [backport #9194 to 2.9]
  ddtrace/llmobs/_integrations/langchain.py
  tests/contrib/langchain/cassettes/langchain/openai_chain_schema_io.yaml
  tests/contrib/langchain/cassettes/langchain_community/lcel_openai_chain_schema_io.yaml
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
Labels: changelog/no-changelog

#9243 feat(llmobs): expose force flush method for serverless
  ddtrace/llmobs/_llmobs.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog

#9256 fix(asm): fix format value using `str` instead of `format` to return a value without `format_spec`
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
Labels: changelog/no-changelog, ASM, backport 2.7, backport 2.8, backport 2.9

#9262 chore(asm): avoid importing when patching with import hook
  ddtrace/appsec/_common_module_patches.py
Labels: changelog/no-changelog, ASM, backport 2.9

#9195 fix(langchain): correctly identify inputs for batch lcel chain calls
  ddtrace/contrib/langchain/patch.py
  releasenotes/notes/langchain-inputs-checking-f295eefb7053fd47.yaml
  tests/contrib/langchain/test_langchain_community.py
Labels: MLObs, backport 2.9

#9016 fix(ci_visibility): use the default tracer when enabling CI Visibility
  .riot/requirements/10b8fc3.txt
  .riot/requirements/1163993.txt
  .riot/requirements/11bda89.txt
  .riot/requirements/1252d0f.txt
  .riot/requirements/144615f.txt
  .riot/requirements/14ca37f.txt
  .riot/requirements/17cf97e.txt
  .riot/requirements/18147c2.txt
  .riot/requirements/1b09cab.txt
  .riot/requirements/1becf29.txt
  .riot/requirements/1f42cb3.txt
  .riot/requirements/3af9e27.txt
  .riot/requirements/48eb599.txt
  .riot/requirements/7800b91.txt
  .riot/requirements/8fd4efc.txt
  .riot/requirements/91bec06.txt
  .riot/requirements/a0aa271.txt
  .riot/requirements/d03449e.txt
  ddtrace/internal/ci_visibility/filters.py
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/fix-ci_visibility-use_default_tracer-8523fd1859dea0da.yaml
  riotfile.py
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/pytest/test_pytest_snapshot.py
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot.test_pytest_with_ddtrace_patch_all.json
Labels: backport 2.7, backport 2.8, backport 2.9

#9264 ci(profiling): avoid testing fork method because it consistently times out in CI
  tests/profiling/test_main.py
Labels: changelog/no-changelog

#9162 chore(internal): fix CI Visibility usage of the core API
  ddtrace/ext/ci_visibility/api.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/api/test_ext_ci_visibility_api.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/util.py
Labels: changelog/no-changelog

#9279 fix(asm): fix string aspects potentially being called on module aspects
  ddtrace/appsec/_iast/_ast/visitor.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
Labels: changelog/no-changelog, ASM, backport 2.9

#9265 perf(iast): improve performance for patching decision
  ddtrace/appsec/_iast/_ast/ast_patching.py
  tests/appsec/iast/test_env_var.py
Labels: changelog/no-changelog, ASM, backport 2.8, backport 2.9

#9284 fix(asm): initializer rework and fix for segmentation faults
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  releasenotes/notes/iast-segfaults-fix-d25c5c132dd8482e.yaml
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
Labels: ASM, backport 2.7, backport 2.8, backport 2.9

#9288 fix(iast): empty insecure cookies
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM, backport 2.8, backport 2.9

#9289 fix(asm): initializer rework and fix for segmentation faults [backport 2.9]
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  releasenotes/notes/iast-segfaults-fix-d25c5c132dd8482e.yaml
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
Labels: ASM

#9292 perf(iast): improve performance for patching decision [backport 2.8]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  tests/appsec/iast/test_env_var.py
Labels: changelog/no-changelog, ASM

#9290 chore(tracer): hatch.toml as a guild file
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9291 perf(iast): improve performance for patching decision [backport 2.9]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  tests/appsec/iast/test_env_var.py
Labels: changelog/no-changelog, ASM

#9252 fix(asm): workaround disabling builtins.open aspects [backport 2.8]
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/asm-open-disabled-090eefa08b8b69a4.yaml
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/test_iast_propagation_path.py
Labels: ASM

#9255 chore(iast): enable iast in framework tests
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, ASM

#9268 chore(cassandra): refactor to separate cassandra logic from tracing logic
  ddtrace/contrib/cassandra/session.py
Labels: changelog/no-changelog

#9280 chore(asm): enable iast for threat tests
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_processor.py
  hatch.toml
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/test_django.py
  tests/appsec/contrib_appsec/test_fastapi.py
  tests/appsec/contrib_appsec/test_flask.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#9286 chore(iast): ast Visitor as singleton
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/visitor.py
Labels: changelog/no-changelog, ASM, backport 2.9

#9300 chore(asm): enable rasp with iast
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#9261 ci: add ITR unskippable marker if subprocess marker is used
  tests/conftest.py
Labels: changelog/no-changelog, backport 2.7, backport 2.8, backport 2.9

#9295 fix(iast): empty insecure cookies [backport 2.8]
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#9306 chore(asm): remove small flakyness in api security test
  tests/appsec/appsec/api_security/test_schema_fuzz.py
Labels: changelog/no-changelog, ASM

#9307 fix(asm): enabling builtins.open sink point
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/taint_sinks/__init__.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/iast/test_telemetry.py
Labels: changelog/no-changelog, ASM

#9172 feat(llmobs): support in-code config for llmobs
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/langchain/patch.py
  ddtrace/contrib/openai/patch.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_trace_processor.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/langchain/conftest.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/openai/conftest.py
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog

#9310 chore: update changelog for version 2.8.5
  CHANGELOG.md
Labels: changelog/no-changelog

#9297 fix(openai): handle explicit n=None case for chat completions
  ddtrace/contrib/openai/_endpoint_hooks.py
  releasenotes/notes/fix-openai-none-n-kwarg-04e0f81074a13191.yaml
  tests/contrib/openai/test_openai_v1.py
Labels: backport 2.8, backport 2.9

#9316 chore: native asm code linting
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/Source.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/Source.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/_taint_tracking.h
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintedOps/TaintedOps.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
Labels: changelog/no-changelog, ASM

#9314 fix(iast): fix threading import regression
  ddtrace/appsec/_iast/_overhead_control_engine.py
Labels: changelog/no-changelog, ASM

#9296 chore(ci): update GitHub Actions to latest version
  .github/workflows/apm-transport-stress-test.yml
  .github/workflows/build-and-publish-image.yml
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
  .github/workflows/lib-inject-publish.yml
  .github/workflows/lib-injection.yml
  .github/workflows/pr-name.yml
  .github/workflows/requirements-locks.yml
  .github/workflows/set-target-milestone.yml
  .github/workflows/system-tests.yml
  .github/workflows/test_frameworks.yml
  .github/workflows/upstream-issues.yml
Labels: changelog/no-changelog

#9299 fix: error parsing django cookies
  ddtrace/contrib/django/utils.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#9235 chore(ci): add rust toolchain to ci environments
  .circleci/config.templ.yml
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog

#9319 chore(ci): add custom pypa_musllinux_1_2_i686 image with Rust compiler
  .github/workflows/build-and-publish-image.yml
  .github/workflows/pypa_musllinux_1_2_i686.yml
  docker/Dockerfile.pypa_musllinux_1_2_i686
Labels: changelog/no-changelog

#9317 chore(di): fix infinite loop in exception replay
  ddtrace/debugging/_exception/auto_instrument.py
  tests/debugging/exception/test_auto_instrument.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9305 ci: grouped macrobenchmarks
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI

#9320 chore: ignore django test for patching
  ddtrace/appsec/_iast/_ast/ast_patching.py
Labels: changelog/no-changelog, ASM

#9222 chore(internal): bytecode wrapping context
  ddtrace/internal/assembly.py
  ddtrace/internal/wrapping/context.py
  tests/internal/test_wrapping.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9148 chore(debugger): consolidate pii redaction keys for all libraries
  ddtrace/debugging/_redaction.py
  tests/debugging/exception/test_auto_instrument.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9324 chore: exclude scripts folder in build package step
  setup.py
Labels: changelog/no-changelog

#9304 feat(asm): exploit prevention
  .github/CODEOWNERS
  .github/workflows/system-tests.yml
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
  ddtrace/contrib/asgi/middleware.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/internal/_exceptions.py
  ddtrace/settings/asm.py
  hatch.toml
  releasenotes/notes/exploit_prevention_enabled-ae26036621f6140c.yaml
  setup.py
  tests/.suitespec.json
  tests/appsec/appsec/rules-rasp-blocking.json
  tests/appsec/appsec/test_asm_request_context.py
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/test_django.py
  tests/appsec/contrib_appsec/test_fastapi.py
  tests/appsec/contrib_appsec/test_flask.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/rules.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: ASM

#9326 chore(asm): use unpatched open for asm
  .github/CODEOWNERS
  ddtrace/__init__.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_processor.py
  ddtrace/internal/_unpatched.py
  ddtrace/internal/utils/http.py
  ddtrace/profiling/_threading.pyx
  ddtrace/profiling/collector/stack.pyx
  tests/.suitespec.json
Labels: changelog/no-changelog, ASM, backport 2.9

#9327 chore: retrieve locals from function probes
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_function/store.py
  ddtrace/debugging/_signal/snapshot.py
  tests/debugging/function/test_store.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9322 fix(tracer): ensure all metadata and configs are checked for flare + correct config file
  ddtrace/internal/flare/_subscribers.py
  ddtrace/internal/flare/flare.py
  ddtrace/internal/flare/handler.py
  ddtrace/settings/config.py
  tests/internal/test_tracer_flare.py
Labels: changelog/no-changelog

#9272 fix(tracing): lazy importing asyncio should not reset existing trace context
  ddtrace/_trace/provider.py
  releasenotes/notes/fix-asyncio-context-reset-6283f01dc7d46dc4.yaml
  tests/conftest.py
  tests/contrib/asyncio/test_lazyimport.py
Labels: backport 2.7, backport 2.8, backport 2.9

#9315 ci: parametrized framework tests
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9331 fix(openai): remove patch code for removed API endpoints
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/contrib/openai/patch.py
  releasenotes/notes/fix-openai-remove-edit-fine-tunes-0fc21266ef1cddb0.yaml
  tests/contrib/openai/cassettes/v0/edit.yaml
  tests/contrib/openai/cassettes/v0/edit_async.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_cancel.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_cancel_async.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_create.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_create_async.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_list.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_list_async.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_list_events.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_retrieve.yaml
  tests/contrib/openai/cassettes/v0/fine_tune_retrieve_async.yaml
  tests/contrib/openai/cassettes/v1/edit.yaml
  tests/contrib/openai/cassettes/v1/edit_async.yaml
  tests/contrib/openai/cassettes/v1/fine_tune_cancel.yaml
  tests/contrib/openai/cassettes/v1/fine_tune_create.yaml
  tests/contrib/openai/cassettes/v1/fine_tune_list.yaml
  tests/contrib/openai/cassettes/v1/fine_tune_list_events.yaml
  tests/contrib/openai/cassettes/v1/fine_tune_retrieve.yaml
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/snapshots/tests.contrib.openai.test_openai.test_edit.json
  tests/snapshots/tests.contrib.openai.test_openai.test_fine_tune_cancel.json
  tests/snapshots/tests.contrib.openai.test_openai.test_fine_tune_create.json
  tests/snapshots/tests.contrib.openai.test_openai.test_fine_tune_list.json
  tests/snapshots/tests.contrib.openai.test_openai.test_fine_tune_list_events.json
  tests/snapshots/tests.contrib.openai.test_openai.test_fine_tune_retrieve.json
Labels: backport 2.8, backport 2.9

#9321 fix(openai): wrap streamed response
  .riot/requirements/14561ae.txt
  .riot/requirements/1642d4d.txt
  .riot/requirements/1666d46.txt
  .riot/requirements/169042d.txt
  .riot/requirements/17c49c8.txt
  .riot/requirements/185da79.txt
  .riot/requirements/194d473.txt
  .riot/requirements/1a8fb3e.txt
  .riot/requirements/1e5eb59.txt
  .riot/requirements/1e7ee60.txt
  .riot/requirements/607e841.txt
  .riot/requirements/6321007.txt
  .riot/requirements/9ad019f.txt
  .riot/requirements/d6cc29d.txt
  .riot/requirements/e877b9f.txt
  .riot/requirements/e9958eb.txt
  .riot/requirements/f5090e1.txt
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/contrib/openai/utils.py
  releasenotes/notes/fix-openai-streamed-responses-6db98c802c331b46.yaml
  riotfile.py
  tests/contrib/openai/test_openai_v1.py
Labels: backport 2.8, backport 2.9

#9329 chore(ci): update profiling overhead jobs
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
  scripts/profiles/django-simple/setup.sh
  scripts/profiles/encoders/setup.sh
Labels: changelog/no-changelog

#9328 chore(ci_visibility): revert default tracer change
  .riot/requirements/117f119.txt
  .riot/requirements/1254841.txt
  .riot/requirements/14d5757.txt
  .riot/requirements/17ecd2b.txt
  .riot/requirements/18cd4dd.txt
  .riot/requirements/1ceca0e.txt
  .riot/requirements/1e0c0d6.txt
  .riot/requirements/1e49987.txt
  .riot/requirements/1e67852.txt
  .riot/requirements/2a81450.txt
  .riot/requirements/32540b6.txt
  .riot/requirements/3e6ea76.txt
  .riot/requirements/6710b57.txt
  .riot/requirements/764e316.txt
  .riot/requirements/77724eb.txt
  .riot/requirements/b908e36.txt
  .riot/requirements/c426f16.txt
  .riot/requirements/cde42be.txt
  ddtrace/internal/ci_visibility/filters.py
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/fix-ci_visibility-use_default_tracer-8523fd1859dea0da.yaml
  riotfile.py
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/pytest/test_pytest_snapshot.py
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot.test_pytest_with_ddtrace_patch_all.json
Labels: changelog/no-changelog, backport 2.7, backport 2.8, backport 2.9

#9330 chore(asm): avoid terminate being called on native aspect
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/no-terminate-on-extend-join-aspects-0cf5ddcaaf836168.yaml
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_ospath_aspects.py
Labels: ASM, backport 2.8, backport 2.9

#8727 chore(ci_visibility): introduce experimental internal coverage collector
  .github/CODEOWNERS
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/internal/ci_visibility/coverage.py
  ddtrace/internal/coverage/__init__.py
  ddtrace/internal/coverage/_native.c
  ddtrace/internal/coverage/_native.pyi
  ddtrace/internal/coverage/code.py
  ddtrace/internal/coverage/instrumentation.py
  ddtrace/internal/coverage/report.py
  ddtrace/internal/coverage/util.py
  ddtrace/internal/module.py
  setup.py
  tests/.suitespec.json
Labels: changelog/no-changelog

#9347 fix(asm): avoid terminate being called on native aspect [backport 2.9]
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectExtend.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectJoin.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/no-terminate-on-extend-join-aspects-0cf5ddcaaf836168.yaml
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_ospath_aspects.py
Labels: ASM

#9343 chore(asm): use unpatched open for asm [backport 2.9]
  .github/CODEOWNERS
  ddtrace/__init__.py
  ddtrace/appsec/_processor.py
  ddtrace/internal/_unpatched.py
  ddtrace/internal/utils/http.py
  ddtrace/profiling/_threading.pyx
  ddtrace/profiling/collector/stack.pyx
  tests/.suitespec.json
Labels: changelog/no-changelog, ASM

#7659 refactor: implement native periodic thread
  ddtrace/internal/_threads.cpp
  ddtrace/internal/_threads.pyi
  ddtrace/internal/periodic.py
  ddtrace/profiling/_threading.pyx
  ddtrace/profiling/collector/stack.pyx
  setup.py
  tests/.suitespec.json
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/conftest.py
  tests/internal/test_forksafe.py
  tests/internal/test_periodic.py
  tests/opentracer/test_tracer_gevent.py
  tests/profiling/collector/test_stack.py
  tests/subprocesstest.py
Labels: changelog/no-changelog

#9333 feat(llmobs): improve langchain llmobs span names
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/_utils.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog

#9353 chore(flake): marking `test_service_name` as flaky
  tests/internal/service_name/test_extra_services_names.py
Labels: changelog/no-changelog

#9355 feat(otel): adds compatibility for trace metrics via otel spans
  ddtrace/opentelemetry/_span.py
  releasenotes/notes/otel-trace-metrics-compatability-f213b8aa2e90db22.yaml
  tests/opentelemetry/test_span.py
  tests/snapshots/tests.opentelemetry.test_span.test_otel_span_attributes_overrides[override5].json
Labels: backport 2.9

#9318 chore(iast): add local debug scripts to find leaks
  docker/Dockerfile_py311_debug_mode
  docker/Dockerfile_py312_debug_mode
  scripts/iast/.env
  scripts/iast/README
  scripts/iast/mod_leak_functions.py
  scripts/iast/requirements.txt
  scripts/iast/run_memory.sh
  scripts/iast/run_memray.sh
  scripts/iast/run_references.sh
  scripts/iast/test_leak_functions.py
  scripts/iast/test_references.py
  scripts/iast/valgrind-python.supp
Labels: changelog/no-changelog, ASM

#9344 chore(asm): avoid double calls on some aspect front-ends
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM

#9348 chore(iast): smoke tests importing the top 100 popular modules
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#9362 ci: upgrade pytest for requests framework test
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9372 chore(asm): add exploit prevention capabilities
  ddtrace/appsec/_capabilities.py
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM, backport 2.9

#9357 chore(internal): capture python config vars in telemetry data
  ddtrace/internal/telemetry/data.py
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#9375 chore(ci): fix up injection image prune job
  .github/workflows/lib-inject-prune.yml
Labels: changelog/no-changelog

#9273 ci: run dogfood tests on every pull request
  .gitlab-ci.yml
  .gitlab/dogfood.yml
Labels: changelog/no-changelog

#9371 chore(ci): bs4 & sanic framework test
  .github/workflows/test_frameworks.yml
  ddtrace/internal/compat.py
Labels: changelog/no-changelog, ASM, CI

#9380 feat(opentelemetry): add span events
  ddtrace/_trace/span.py
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/constants.py
  ddtrace/opentelemetry/_span.py
  releasenotes/notes/opentelemetry-support-span-events-66c79465a3f68180.yaml
  tests/opentelemetry/test_span.py
  tests/snapshots/tests.opentelemetry.test_span.test_otel_span_events.json
  tests/tracer/test_encoders.py
Labels: backport 2.9

#9112 fix(tracing): fix traceback max size for exceptions
  ddtrace/_trace/span.py
  releasenotes/notes/fix-tracing-traceback-size-for-exceptions-3739fa96d09290fd.yaml
  tests/tracer/test_span.py
Labels: backport 2.7, backport 2.8, backport 2.9

#9387 fix(llmobs): fix propagation memory usage
  ddtrace/propagation/http.py
Labels: changelog/no-changelog, backport 2.9

#9396 chore(asm): update list of headers to collect for ASM
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_trace_utils.py
  tests/appsec/appsec/test_appsec_trace_utils.py
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
Labels: changelog/no-changelog, ASM

#9399 fix(asm): fix actions processing from RC
  ddtrace/appsec/_remoteconfiguration.py
  releasenotes/notes/actions_from_RC-08744fc9e91a8c02.yaml
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: ASM, backport 2.6, backport 2.7, backport 2.8, backport 2.9

#9395 chore(iast): add local debug scripts to find segmentation faults
  .github/CODEOWNERS
  scripts/iast/README
Labels: changelog/no-changelog, ASM

#9393 fix(telemetry): logs payload format [backport 2.7]
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry_metrics.py
Labels: changelog/no-changelog

#9346 chore(ci_visibility): use absolute paths and use include path in ModuleCodeCollector
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/internal/coverage/code.py
  ddtrace/internal/coverage/instrumentation.py
  ddtrace/internal/coverage/report.py
Labels: changelog/no-changelog

#9374 ci: add benchmark for IAST AST patching
  benchmarks/bm/iast_utils/ast_patching.py
  benchmarks/iast_ast_patching/config.yaml
  benchmarks/iast_ast_patching/scenario.py
Labels: changelog/no-changelog, ASM, CI

#9398 feat(llmobs): modify integration patch behavior in llmobs.enable()
  ddtrace/llmobs/_llmobs.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/openai/conftest.py
  tests/contrib/openai/test_openai_v0.py
Labels: changelog/no-changelog

#9417 fix(llmobs): add parent ID handling for integration-generated spans
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/openai.py
  ddtrace/llmobs/_trace_processor.py
Labels: changelog/no-changelog, backport 2.9

#9409 ci: set ulimit inside the testrunner instance
  scripts/ddtest
Labels: changelog/no-changelog

#9424 fix(internal): writer recreate maintain extra headers
  ddtrace/internal/writer/writer.py
  tests/tracer/test_writer.py
Labels: bug, changelog/no-changelog, backport 2.7, backport 2.8, backport 2.9

#9432 feat(llmobs): submit tags for custom evaluation metrics
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog, mergequeue-status: waiting, backport 2.9

#9397 chore(llmobs): extract openai/llmobs tests to separate file
  tests/contrib/openai/test_openai_llmobs.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/contrib/openai/utils.py
Labels: changelog/no-changelog

#9438 chore(llmobs): increase default write timeout
  ddtrace/llmobs/_llmobs.py
Labels: changelog/no-changelog, backport 2.9

#9419 chore(ci): cleanup benchmarking scripts and add profiling capability
  benchmarks/Dockerfile
  benchmarks/README.rst
  benchmarks/base/requirements.txt
  benchmarks/base/run.py
  scripts/gen_circleci_config.py
  scripts/perf-run-scenario
Labels: changelog/no-changelog

#9407 chore(llmobs): extract and refactor langchain llmobs tests
  .riot/requirements/1084a71.txt
  .riot/requirements/17e8568.txt
  .riot/requirements/1ec5924.txt
  .riot/requirements/1f6f978.txt
  .riot/requirements/39161c9.txt
  .riot/requirements/76db01b.txt
  .riot/requirements/8297334.txt
  .riot/requirements/e17f33e.txt
  .riot/requirements/ee6f953.txt
  riotfile.py
  tests/contrib/langchain/cassettes/langchain/openai_completion_sync.yaml
  tests/contrib/langchain/conftest.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/langchain/test_langchain_llmobs.py
  tests/contrib/langchain/test_langchain_patch.py
  tests/contrib/langchain/utils.py
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_sequential_chain_with_multiple_llm_async.json
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_sequential_chain_with_multiple_llm_sync.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_integration.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[None-None].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[None-v0].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[None-v1].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[mysvc-None].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[mysvc-v0].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[mysvc-v1].json
Labels: changelog/no-changelog
