Repository DataDog/dd-trace-py, pull requests merged in 2024-06, with the labels that each got.

#9455 chore(ci): ensure we run tracer tests on llmobs changes
  tests/.suitespec.json
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#9458 chore(tracer): simplify llmobs injection assertion on tracer propagation tests
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#9459 chore(llmobs): deprecate name of ML app env var
  ddtrace/llmobs/_llmobs.py
  ddtrace/settings/config.py
  releasenotes/notes/llmobs-deprecate-ml-app-name-71c71132c700f3ac.yaml
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: backport 2.9

#9467 chore(ci): fix incorrect importlib_metadata name
  tests/internal/test_packages.py
Labels: changelog/no-changelog

#9211 feat(asm): standalone asm
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/tracer.py
  ddtrace/internal/writer/writer.py
  ddtrace/pin.py
  releasenotes/notes/feat-asm-standalone-07279cdb3e0fa9e0.yaml
  tests/appsec/appsec_utils.py
  tests/appsec/integrations/test_gunicorn_handlers.py
  tests/integration/test_trace_stats.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
Labels: ASM

#9470 chore: remove unneeded import from test_common_aspects
  tests/appsec/iast/aspects/test_common_aspects.py
Labels: changelog/no-changelog, ASM

#9425 chore: fix cformat.sh script and use hatch to ensure the same version
  .circleci/config.templ.yml
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/Source.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  ddtrace/profiling/collector/_utils.h
  hatch.toml
  scripts/cformat.sh
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog, CI

#9475 chore(ci): restore microbenchmarks runs
  .gitlab/benchmarks.yml
  benchmarks/Dockerfile
Labels: changelog/no-changelog

#9472 ci(tracer): limit time spent waiting for subprocesses to join in tracer tests
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#9473 ci: avoid running failing benchmark gitlab jobs on main branch
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#9410 chore(ci_visibility): add multiprocessing support to internal coverage collector
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/internal/coverage/code.py
  ddtrace/internal/coverage/installer.py
  ddtrace/internal/coverage/instrumentation.py
  ddtrace/internal/coverage/multiprocessing_coverage.py
  ddtrace/internal/coverage/report.py
Labels: changelog/no-changelog

#9426 chore(ci_visibility): add threading to internal coverage collector
  ddtrace/internal/coverage/code.py
  ddtrace/internal/coverage/installer.py
  ddtrace/internal/coverage/multiprocessing_coverage.py
  ddtrace/internal/coverage/threading_coverage.py
Labels: changelog/no-changelog

#9480 chore: recover, in an improved way, the user.exists field for failed Django logins
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/django/patch.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#9482 chore(asm): standalone asm propagation
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/propagation/http.py
  ddtrace/settings/asm.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog, ASM

#9490 ci: mark unreliable langchain_community tests
  tests/contrib/langchain/test_langchain_community.py
Labels: changelog/no-changelog

#9382 ci: mark some unreliable tests
  tests/contrib/langchain/test_langchain_community.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog

#9507 ci(appsec): skip pygoat tests because they are failing on main
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: changelog/no-changelog

#9464 ci: handle RemoteDisconnected in snapshot tests
  tests/contrib/django_celery/test_django_celery.py
  tests/debugging/test_debugger.py
  tests/utils.py
Labels: changelog/no-changelog

#9440 chore(Profiling): add infrastructure for supporting timeline, but timeline isn't supported yet
  ddtrace/internal/datadog/profiling/dd_wrapper/include/interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/profile.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample_manager.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample_manager.cpp
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/profiler.py
  ddtrace/settings/profiling.py
Labels: changelog/no-changelog

#9510 ci: force pyyaml reinstall in pygoat dockefile
  tests/appsec/integrations/pygoat_tests/Dockerfile.pygoat.2.0.1
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: changelog/no-changelog, ASM, CI

#9479 chore(ci_visibility): add threading and multiprocessing coverage tests
  .github/CODEOWNERS
  ddtrace/internal/coverage/code.py
  ddtrace/internal/coverage/instrumentation.py
  riotfile.py
  tests/.suitespec.json
  tests/coverage/excluded_path/excluded.py
  tests/coverage/included_path/callee.py
  tests/coverage/included_path/in_context_lib.py
  tests/coverage/included_path/lib.py
  tests/coverage/test_coverage_multiprocessing.py
  tests/coverage/test_coverage_threading.py
Labels: changelog/no-changelog

#9477 test(lib-injection): test telemetry
  .github/workflows/lib-injection.yml
  .gitlab/build-oci.sh
  lib-injection/Dockerfile
  lib-injection/copy-lib.sh
  lib-injection/docker-compose.yml
  lib-injection/sitecustomize.py
  lib-injection/telemetry-forwarder.sh
  tests/lib-injection/dd-lib-python-init-test-django-unsupported-package-force/Dockerfile
  tests/lib-injection/dd-lib-python-init-test-django-unsupported-package-force/validate_telemetry.py
  tests/lib-injection/dd-lib-python-init-test-django-unsupported-package/Dockerfile
  tests/lib-injection/dd-lib-python-init-test-django-unsupported-package/validate_telemetry.py
  tests/lib-injection/dd-lib-python-init-test-django-unsupported-python/Dockerfile
  tests/lib-injection/dd-lib-python-init-test-django-unsupported-python/validate_telemetry.py
  tests/lib-injection/dd-lib-python-init-test-django/Dockerfile
  tests/lib-injection/dd-lib-python-init-test-django/validate_telemetry.py
Labels: changelog/no-changelog

#9513 chore(asm): update security rules to 1.12.0
  ddtrace/appsec/rules.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#9496 chore: put ddtrace site-packages on the end of the pythonpath [APMS-12275]
  lib-injection/sitecustomize.py
Labels: changelog/no-changelog

#9506 docs: updated changelog to reflect changes in GH 2.9.0 release note
  CHANGELOG.md
Labels: changelog/no-changelog

#9489 chore(lib-injection): post-injection telemetry
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/config.py
  lib-injection/sitecustomize.py
  tests/lib-injection/dd-lib-python-init-test-django/Dockerfile
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#9503 docs: add release note for removal of sqlparse
  releasenotes/notes/doc-remove-sqlparse-9afa8b0ab3e510b3.yaml
Labels: backport 2.9

#9516 chore(anthropic): make team ml-obs as codeowners
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9517 ci: force pyyaml reinstall in pygoat dockefile [backport 2.9]
  tests/appsec/integrations/pygoat_tests/Dockerfile.pygoat.2.0.1
Labels: changelog/no-changelog, ASM, CI

#9518 chore(asm): add sqli capabilities to exploit prevention RC
  ddtrace/appsec/_capabilities.py
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM, backport 2.10

#9502 chore: add dogweb ci step
  scripts/release.py
Labels: changelog/no-changelog

#9521 chore(ci): ownership change
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9499 ci: fix django framework test with appsec
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, ASM, CI

#9454 chore(llmobs): improve type hints
  ddtrace/llmobs/_llmobs.py
Labels: changelog/no-changelog

#9524 chore: add library_entrypoint as arg for lib injection executable
  lib-injection/sitecustomize.py
Labels: changelog/no-changelog, backport 2.10

#9530 ci(lib-injection): fix lib injection telemetry tests
  lib-injection/docker-compose.yml
  tests/lib-injection/dd-lib-python-init-test-django/Dockerfile
Labels: changelog/no-changelog, backport 2.10

#9526 fix(asm): asm standalone http integrations with distributed tracing
  ddtrace/contrib/requests/connection.py
  releasenotes/notes/fix-requests-propagation-apm-opt-out-bee8409e28cbe48f.yaml
  tests/contrib/requests/test_requests_distributed.py
  tests/contrib/urllib3/test_urllib3.py
Labels: ASM, backport 2.10

#9539 chore(release notes): fix anthropic release note
  releasenotes/notes/add-anthropic-streaming-support-01937d2e524f1bd0.yaml
Labels: changelog/no-changelog, backport 2.10

#9350 fix(ci_visibility): use default tracer in CI Visibility (#9328)
  .riot/requirements/10b8fc3.txt
  .riot/requirements/1163993.txt
  .riot/requirements/11bda89.txt
  .riot/requirements/1252d0f.txt
  .riot/requirements/144615f.txt
  .riot/requirements/14ca37f.txt
  .riot/requirements/17cf97e.txt
  .riot/requirements/18147c2.txt
  .riot/requirements/1b09cab.txt
  .riot/requirements/1becf29.txt
  .riot/requirements/1f42cb3.txt
  .riot/requirements/3af9e27.txt
  .riot/requirements/48eb599.txt
  .riot/requirements/7800b91.txt
  .riot/requirements/8fd4efc.txt
  .riot/requirements/91bec06.txt
  .riot/requirements/a0aa271.txt
  .riot/requirements/d03449e.txt
  ddtrace/internal/ci_visibility/filters.py
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/fix-ci_visibility-use_default_tracer-8523fd1859dea0da.yaml
  riotfile.py
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/pytest/test_pytest_snapshot.py
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot.test_pytest_with_ddtrace_patch_all.json
Labels: backport 2.7, backport 2.8, backport 2.9, backport 2.10

#9529 chore(asm): new smoke + patch + e2e package tests
  .github/codeql-config.yml
  .github/workflows/codeql-analysis.yml
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast_packages/packages/pkg_aiohttp.py
  tests/appsec/iast_packages/packages/pkg_aiosignal.py
  tests/appsec/iast_packages/packages/pkg_annotated_types.py
  tests/appsec/iast_packages/packages/pkg_asn1crypto.py
  tests/appsec/iast_packages/packages/pkg_cachetools.py
  tests/appsec/iast_packages/packages/pkg_click.py
  tests/appsec/iast_packages/packages/pkg_decorator.py
  tests/appsec/iast_packages/packages/pkg_distlib.py
  tests/appsec/iast_packages/packages/pkg_docutils.py
  tests/appsec/iast_packages/packages/pkg_exceptiongroup.py
  tests/appsec/iast_packages/packages/pkg_filelock.py
  tests/appsec/iast_packages/packages/pkg_frozenlist.py
  tests/appsec/iast_packages/packages/pkg_importlib_resources.py
  tests/appsec/iast_packages/packages/pkg_iniconfig.py
  tests/appsec/iast_packages/packages/pkg_isodate.py
  tests/appsec/iast_packages/packages/pkg_itsdangerous.py
  tests/appsec/iast_packages/packages/pkg_jinja2.py
  tests/appsec/iast_packages/packages/pkg_lxml.py
  tests/appsec/iast_packages/packages/pkg_markupsafe.py
  tests/appsec/iast_packages/packages/pkg_more_itertools.py
  tests/appsec/iast_packages/packages/pkg_multidict.py
  tests/appsec/iast_packages/packages/pkg_oauthlib.py
  tests/appsec/iast_packages/packages/pkg_openpyxl.py
  tests/appsec/iast_packages/packages/pkg_pandas.py
  tests/appsec/iast_packages/packages/pkg_pillow.py
  tests/appsec/iast_packages/packages/pkg_platformdirs.py
  tests/appsec/iast_packages/packages/pkg_pluggy.py
  tests/appsec/iast_packages/packages/pkg_psutil.py
  tests/appsec/iast_packages/packages/pkg_pyarrow.py
  tests/appsec/iast_packages/packages/pkg_pydantic.py
  tests/appsec/iast_packages/packages/pkg_pygments.py
  tests/appsec/iast_packages/packages/pkg_pyjwt.py
  tests/appsec/iast_packages/packages/pkg_pynacl.py
  tests/appsec/iast_packages/packages/pkg_pyopenssl.py
  tests/appsec/iast_packages/packages/pkg_pyparsing.py
  tests/appsec/iast_packages/packages/pkg_pytz.py
  tests/appsec/iast_packages/packages/pkg_requests_toolbelt.py
  tests/appsec/iast_packages/packages/pkg_scipy.py
  tests/appsec/iast_packages/packages/pkg_soupsieve.py
  tests/appsec/iast_packages/packages/pkg_tomli.py
  tests/appsec/iast_packages/packages/pkg_tomlkit.py
  tests/appsec/iast_packages/packages/pkg_virtualenv.py
  tests/appsec/iast_packages/packages/pkg_werkzeug.py
  tests/appsec/iast_packages/packages/pkg_wrapt.py
  tests/appsec/iast_packages/packages/pkg_yarl.py
  tests/appsec/iast_packages/packages/pkg_zipp.py
  tests/appsec/iast_packages/test_packages.py
  tests/appsec/iast_tdd_propagation/test_flask.py
  tests/appsec/integrations/test_flask_iast_patching.py
  tests/appsec/integrations/test_flask_remoteconfig.py
  tests/appsec/integrations/test_flask_telemetry.py
  tests/appsec/integrations/test_gunicorn_handlers.py
Labels: changelog/no-changelog, ASM

#9545 chore: switch from error to error_type for lib injection tag
  lib-injection/sitecustomize.py
Labels: changelog/no-changelog, backport 2.10

#9563 ci: disable pyarrow iast package test
  .circleci/config.templ.yml
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM, CI, backport 2.10

#9558 ci: improve macrobenchmarks [backport 2.9]
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI

#9562 ci: add `importlib_metadata` to `test_get_distributions`
  tests/internal/test_packages.py
Labels: changelog/no-changelog, CI, backport 2.8, backport 2.9, backport 2.10

#9560 chore(asm): remove flask login partial instrumentation
  .github/CODEOWNERS
  .riot/requirements/140fecc.txt
  ddtrace/_monkey.py
  ddtrace/contrib/flask_login/__init__.py
  ddtrace/contrib/flask_login/patch.py
  docs/index.rst
  docs/integrations.rst
  releasenotes/notes/remove_flask_login_instrumentation-1ab257a3d0903862.yaml
  riotfile.py
  tests/.suitespec.json
  tests/contrib/flask_login/__init__.py
  tests/contrib/flask_login/test_flask_login_appsec.py
  tests/contrib/flask_login/test_flask_login_patch_generated.py
Labels: ASM

#9568 ci: add `importlib_metadata` to `test_get_distributions` [backport 2.8]
  tests/internal/test_packages.py
Labels: changelog/no-changelog, CI

#9567 ci: add macrobenchmarks retry option
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI, backport 2.8, backport 2.9, backport 2.10

#9546 chore(llmobs): migrate span payload structure to meet new evp updates
  ddtrace/llmobs/_writer.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_chat_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_multiple_events.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_timed_events.yaml
Labels: changelog/no-changelog

#9559 ci: improve macrobenchmarks [backport 2.8]
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI

#9569 ci: macrobenchmark use a better endpoint for iast worst case scenarios
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, ASM, CI

#9577 chore: add packages propagation tests
  tests/appsec/iast_packages/conftest.py
  tests/appsec/iast_packages/packages/pkg_attrs.py
  tests/appsec/iast_packages/packages/pkg_beautifulsoup4.py
  tests/appsec/iast_packages/packages/pkg_cachetools.py
  tests/appsec/iast_packages/packages/pkg_chartset_normalizer.py
  tests/appsec/iast_packages/packages/pkg_cryptography.py
  tests/appsec/iast_packages/packages/pkg_docutils.py
  tests/appsec/iast_packages/packages/pkg_exceptiongroup.py
  tests/appsec/iast_packages/packages/pkg_idna.py
  tests/appsec/iast_packages/packages/pkg_iniconfig.py
  tests/appsec/iast_packages/packages/pkg_jinja2.py
  tests/appsec/iast_packages/packages/pkg_lxml.py
  tests/appsec/iast_packages/packages/pkg_multidict.py
  tests/appsec/iast_packages/packages/pkg_platformdirs.py
  tests/appsec/iast_packages/packages/pkg_pyasn1.py
  tests/appsec/iast_packages/packages/pkg_pygments.py
  tests/appsec/iast_packages/packages/pkg_pynacl.py
  tests/appsec/iast_packages/packages/pkg_pyparsing.py
  tests/appsec/iast_packages/packages/pkg_pyyaml.py
  tests/appsec/iast_packages/packages/pkg_rsa.py
  tests/appsec/iast_packages/packages/pkg_soupsieve.py
  tests/appsec/iast_packages/packages/pkg_sqlalchemy.py
  tests/appsec/iast_packages/packages/pkg_tomli.py
  tests/appsec/iast_packages/packages/pkg_wrapt.py
  tests/appsec/iast_packages/packages/pkg_yarl.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#9570 chore(sampling): simplify rate limiting in datadog sampler
  ddtrace/internal/sampling.py
  ddtrace/sampler.py
Labels: changelog/no-changelog

#9573 ci: add macrobenchmarks retry option [backport 2.8]
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI

#9585 fix(celery): ensure error.message tag does not include stacktrace
  ddtrace/contrib/celery/signals.py
  releasenotes/notes/fix-celery-error-messages-to-not-include-traceback-98259864e85be54f.yaml
  tests/contrib/celery/test_integration.py
Labels: backport 2.9, backport 2.10

#9566 ci: add missing BP_ENDPOINT env var to macrobenchmarks baseline scenario
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI, backport 2.8, backport 2.9, backport 2.10

#9551 fix(profiling): fix type check for exception types using isinstance
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
Labels: changelog/no-changelog, mergequeue-status: waiting

#9169 chore(profiling): native extensions are no longer optional on supported platforms
  setup.py
Labels: changelog/no-changelog

#9599 chore: disable internal merge queue settings
  repository.datadog.yml
Labels: changelog/no-changelog

#9588 fix(futures): fix incorrect context propgation with ThreadPoolExecutor
  ddtrace/contrib/futures/threading.py
  releasenotes/notes/fix-futures-propagation-f5b33579e0fdafc3.yaml
  tests/contrib/futures/test_propagation.py
Labels: backport 2.9

#9598 feat(asm): add propagation for grpc server sources
  ddtrace/contrib/grpc/server_interceptor.py
  releasenotes/notes/asm-new-gprc-server-propagation-89812a5e161fe0f6.yaml
  tests/appsec/iast/test_grpc_iast.py
Labels: ASM

#9602 fix(llmobs): fix document typing
  ddtrace/llmobs/utils.py
  releasenotes/notes/fix-llmobs-document-typing-5ff08feef2659220.yaml
Labels: backport 2.9, backport 2.10

#9610 fix(profiling): capture lock usages with `with` statement context managers
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml
  tests/profiling/collector/test_threading.py
Labels: Profiling

#9614 chore(ci): remove @DataDog/apm-core-python from profiling paths
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9582 chore: run package tests on main only
  .circleci/config.templ.yml
Labels: changelog/no-changelog, ASM

#9553 ci: update legacy attrs version in tests
  .riot/requirements/94edf33.txt
  riotfile.py
Labels: changelog/no-changelog

#9619 ci: add `importlib_metadata` to `test_get_distributions` [backport 2.7]
  tests/internal/test_packages.py
Labels: changelog/no-changelog, CI

#9621 ci: remove wrongly backported pygoat in docker compose from 2.7
  docker-compose.yml
Labels: changelog/no-changelog, CI

#9629 chore(ci): hot fix for CI
  .circleci/config.templ.yml
  .riot/requirements/11d2116.txt
  .riot/requirements/126a701.txt
  .riot/requirements/1cb9194.txt
  .riot/requirements/1e147db.txt
  .riot/requirements/2ca9efa.txt
  .riot/requirements/54aeb0a.txt
  .riot/requirements/97ea583.txt
  .riot/requirements/b416620.txt
  .riot/requirements/ce9ed6d.txt
  .riot/requirements/d5bcdee.txt
  .riot/requirements/e0c0926.txt
  riotfile.py
Labels: changelog/no-changelog, CI

#9607 ci: add tracer only option to framework tests
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9593 chore(iast): fix propagation for `platformdirs`
  ddtrace/appsec/_iast/_ast/ast_patching.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast_packages/packages/pkg_iniconfig.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#9632 fix django/celery tests
  .riot/requirements/126a701.txt
  .riot/requirements/1292ba4.txt
  .riot/requirements/1e147db.txt
  .riot/requirements/4155e1d.txt
  .riot/requirements/503392f.txt
  .riot/requirements/54aeb0a.txt
  .riot/requirements/97ea583.txt
  .riot/requirements/b416620.txt
  .riot/requirements/ce9ed6d.txt
  .riot/requirements/d5bcdee.txt
  .riot/requirements/e0c0926.txt
  riotfile.py
Labels: changelog/no-changelog, CI

#9624 chore(ci): add script for checking for unreleased changes on release branches
  scripts/unreleased-changes
Labels: changelog/no-changelog

#9635 chore(ci): hot fix for CI [backport 2.9]
  .circleci/config.templ.yml
  .riot/requirements/11d2116.txt
  .riot/requirements/126a701.txt
  .riot/requirements/1cb9194.txt
  .riot/requirements/1e147db.txt
  .riot/requirements/2ca9efa.txt
  .riot/requirements/54aeb0a.txt
  .riot/requirements/97ea583.txt
  .riot/requirements/b416620.txt
  .riot/requirements/ce9ed6d.txt
  .riot/requirements/d5bcdee.txt
  .riot/requirements/e0c0926.txt
  riotfile.py
Labels: changelog/no-changelog

#9639 ci: downgrade pip to 24.0 for httpx
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI, backport 2.7, backport 2.8, backport 2.9, backport 2.10

#9636 chore(ci): hot fix for CI [backport 2.7]
  .circleci/config.templ.yml
  .riot/requirements/126a701.txt
  .riot/requirements/1292ba4.txt
  .riot/requirements/1e147db.txt
  .riot/requirements/4155e1d.txt
  .riot/requirements/503392f.txt
  .riot/requirements/54aeb0a.txt
  .riot/requirements/97ea583.txt
  .riot/requirements/b416620.txt
  .riot/requirements/ce9ed6d.txt
  .riot/requirements/d5bcdee.txt
  .riot/requirements/e0c0926.txt
  riotfile.py
Labels: changelog/no-changelog

#9637 chore(ci): hot fix for CI [backport 2.10]
  .circleci/config.templ.yml
  .riot/requirements/11d2116.txt
  .riot/requirements/126a701.txt
  .riot/requirements/1cb9194.txt
  .riot/requirements/1e147db.txt
  .riot/requirements/2ca9efa.txt
  .riot/requirements/54aeb0a.txt
  .riot/requirements/97ea583.txt
  .riot/requirements/b416620.txt
  .riot/requirements/ce9ed6d.txt
  .riot/requirements/d5bcdee.txt
  .riot/requirements/e0c0926.txt
  riotfile.py
Labels: changelog/no-changelog

#9586 fix(ci_visibility): properly resolve decorated functions for test source file information
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/internal/ci_visibility/utils.py
  releasenotes/notes/fix-ci_visibility-properly_unwrap_functions-7c631b68720adab2.yaml
  tests/contrib/pytest/test_pytest.py
Labels: backport 2.7, backport 2.8, backport 2.9, backport 2.10

#9616 chore(profiling): fixups for profiling cmake artifacts
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  setup.py
  tests/profiling/collector/test_threading.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog

#9620 ci: remove wrongly backported pygoat in docker compose from 2.8
  docker-compose.yml
Labels: changelog/no-changelog, CI

#9648 chore(ci_visibility): respect DD_CIVISIBILITY_AGENTLESS_URL when set
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog

#9647 ci: downgrade pip to 24.0 for httpx [backport 2.8]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9645 ci: downgrade pip to 24.0 for httpx [backport 2.10]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9654 chore(tornado): fix failing tornado test cases
  tests/contrib/tornado/test_executor_decorator.py
Labels: changelog/no-changelog

#9655 ci(telemetry): fix incorrect assertion in telemetry test
  tests/.suitespec.json
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#9656 ci(tornado): run the tornado suite when the futures contrib changes
  tests/.suitespec.json
Labels: changelog/no-changelog

#9641 chore(asm): add initial frame on top of traceback for lfi exploit prevention for regular exception
  ddtrace/appsec/_common_module_patches.py
  tests/appsec/appsec/test_exploit_prevention.py
Labels: changelog/no-changelog, ASM, backport 2.10

#9638 chore: restore module loader after import
  ddtrace/internal/module.py
Labels: changelog/no-changelog

#9662 chore(ci_visibility): bump minimum ITR-supported pytest
  ddtrace/contrib/pytest/constants.py
Labels: changelog/no-changelog

#9646 ci: downgrade pip to 24.0 for httpx [backport 2.9]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9649 ci: downgrade pip to 24.0 for httpx [backport 2.7]
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, CI

#9652 chore(ci): reduce build base venv job from 8 to 6
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#9664 chore(ci): increase cmake parallelization level
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#9605 chore(telemetry): decouple tests from implementation internals and fix flaky tests
  ddtrace/internal/telemetry/writer.py
  tests/conftest.py
  tests/integration/test_settings.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
  tests/telemetry/utils.py
  tests/utils.py
Labels: changelog/no-changelog

#9615 fix(profiling): export lock acquire/release call location and variable name
  ddtrace/profiling/collector/_lock.py
  ddtrace/settings/profiling.py
  tests/profiling/collector/global_locks.py
  tests/profiling/collector/test_asyncio.py
  tests/profiling/collector/test_threading.py
  tests/profiling/collector/test_threading_asyncio.py
  tests/profiling/simple_program_fork.py
Labels: changelog/no-changelog, Profiling

#9667 chore(codeowners): make @DataDog/profiling-python owners of ddtrace/settings/profiling.py
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9608 test(di): fix flaky tests
  tests/debugging/mocking.py
  tests/debugging/test_debugger.py
  tests/debugging/test_debugger_span_decoration.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9534 feat(asm): add new auto user event feature support
  ddtrace/appsec/_capabilities.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/utils.py
  ddtrace/settings/asm.py
  releasenotes/notes/ATO_auto_user_events_new_feature_version-449297c3de2815e2.yaml
  tests/appsec/appsec/test_appsec_trace_utils.py
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/appsec/test_tools.py
  tests/appsec/contrib_appsec/db.sqlite3
  tests/appsec/contrib_appsec/django_app/app/__init__.py
  tests/appsec/contrib_appsec/django_app/app/models.py
  tests/appsec/contrib_appsec/django_app/db_script.py
  tests/appsec/contrib_appsec/django_app/settings.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec.py
Labels: ASM

#9670 chore(asm): remove flaky decorator and add more waf timeout
  tests/appsec/appsec/test_processor.py
Labels: changelog/no-changelog, ASM

#9657 chore(llmobs): token metrics name changes
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/anthropic.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/openai.py
  tests/contrib/anthropic/test_anthropic_llmobs.py
  tests/contrib/botocore/test_bedrock_llmobs.py
  tests/contrib/openai/test_openai_llmobs.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_chat_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_multiple_events.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_timed_events.yaml
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_span_writer.py
Labels: changelog/no-changelog

#9650 ci(appsec): skip failing test
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog
