Repository DataDog/dd-trace-py, pull requests merged in 2024-12, with the labels that each got.

#11511 chore(langchain): delete flaky tests
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/langchain/test_langchain_llmobs.py
Labels: changelog/no-changelog

#11609 ci: add azure and chrome to testrunner image
  docker/Dockerfile
Labels: changelog/no-changelog

#11617 ci: update image and standardize to using both hash and sha256
  .circleci/config.templ.yml
  .github/workflows/requirements-locks.yml
  .gitlab/testrunner.yml
  .gitlab/tests.yml
  docker-compose.yml
Labels: changelog/no-changelog

#11620 chore(profiling): upgrade googletest
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt
Labels: changelog/no-changelog, Profiling

#11619 chore(profiling): use clang when --safety is set
  ddtrace/internal/datadog/profiling/build_standalone.sh
Labels: changelog/no-changelog, Profiling

#11621 chore(profiling): update agent url and port for native tests
  ddtrace/internal/datadog/profiling/dd_wrapper/test/test_api.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/test_forking.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/test_initialization.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/test_threading.cpp
Labels: changelog/no-changelog, Profiling

#11632 chore: use latest patched riot version in CI
  .circleci/config.templ.yml
  .circleci/config.yml
  .github/workflows/generate-package-versions.yml
  .github/workflows/requirements-locks.yml
  .gitlab-ci.yml
  .gitlab/tests.yml
  docs/contributing-testing.rst
  hatch.toml
  scripts/ddtest
Labels: changelog/no-changelog

#11406 chore(internal): avoid freezegun in ddtrace
  .github/CODEOWNERS
  ddtrace/_monkey.py
  ddtrace/contrib/freezegun/__init__.py
  ddtrace/contrib/internal/freezegun/patch.py
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/contrib/pytest/_plugin_v2.py
  hatch.toml
  tests/contrib/freezegun/test_freezegun.py
  tests/contrib/suitespec.yml
Labels: changelog/no-changelog

#11612 fix(profiling): get rid of leaky string table
  ddtrace/internal/datadog/profiling/dd_wrapper/include/profile.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
  releasenotes/notes/profiling-fix-unbounded-string-buffer-d18056263f3e4bdc.yaml
Labels: mergequeue-status: removed

#11641 chore(ci_visibility): update RUM flush env var release
  docs/configuration.rst
Labels: changelog/no-changelog

#11644 chore(profiling): simplify usage of cancellation token
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  tests/profiling_v2/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#11628 chore(profiling): update fork death native test
  ddtrace/internal/datadog/profiling/dd_wrapper/test/test_forking.cpp
Labels: changelog/no-changelog, Profiling

#9622 feat(origin detection): implement new spec
  ddtrace/debugging/_uploader.py
  ddtrace/internal/constants.py
  ddtrace/internal/processor/stats.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/runtime/container.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/profiling/exporter/http.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog, mergequeue-status: rejected

#11623 ci(profiling): gh action to run native tests with sanitizers
  .github/workflows/profiling-native.yml
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/test/TSan.supp
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
Labels: changelog/no-changelog, Profiling

#11547 fix(crashtracking): resolve issue with zombie processes being behind
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/libdatadog_checksums.txt
  releasenotes/notes/fix-crashtracking-zombie-aa81dc4efa96898d.yaml
  src/core/Cargo.lock
  src/core/Cargo.toml
Labels: backport 2.17

#11640 ci: do not persiste git credentials in GitHub Actions
  .github/workflows/build-and-publish-image.yml
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
  .github/workflows/changelog.yml
  .github/workflows/codeowners.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
  .github/workflows/generate-package-versions.yml
  .github/workflows/pr-name.yml
  .github/workflows/requirements-locks.yml
  .github/workflows/rust-ci.yml
  .github/workflows/set-target-milestone.yml
  .github/workflows/system-tests.yml
  .github/workflows/test_frameworks.yml
  .github/workflows/test_lib_injection.yml
  .github/workflows/unit_tests.yml
  .github/workflows/upstream-issues.yml
Labels: changelog/no-changelog

#11493 fix(profiling): `asyncio` task fixes for stack v2
  ddtrace/internal/datadog/profiling/stack_v2/include/stack_renderer.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  releasenotes/notes/profiling-stack-v2-task-names-1d566a1793280aa0.yaml
  tests/profiling_v2/collector/conftest.py
  tests/profiling_v2/collector/test_stack_asyncio.py
Labels: Profiling

#11634 chore(debugger): - update debugger system tests scenarios
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#11651 fix(setup): suppress int-ptr conversion errors for stack profiler v1
  releasenotes/notes/fix-profiler-int-ptr-conversion-4377fbd8724eeaec.yaml
  setup.py
Labels: mergequeue-status: in_progress, backport 2.15, backport 2.16, backport 2.17

#11642 feat(langchain): [MLOB-1972] update langchain to handle vertex and gemini llm calls
  ddtrace/llmobs/_integrations/langchain.py
Labels: changelog/no-changelog

#11645 chore(test): add a known new flaky test
  .gitlab-ci.yml
  .gitlab/dramatiq.yml
  tests/contrib/dramatiq/test_integration.py
Labels: changelog/no-changelog

#11596 refactor(debugger): use single dispatch on probes
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_encoding.py
  ddtrace/debugging/_expressions.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_signal/__init__.py
  ddtrace/debugging/_signal/collector.py
  ddtrace/debugging/_signal/log.py
  ddtrace/debugging/_signal/metric_sample.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_signal/snapshot.py
  ddtrace/debugging/_signal/tracing.py
  tests/debugging/signal/test_collector.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11577 chore(profile): more accurate code-provenance
  ddtrace/profiling/exporter/pprof.pyx
Labels: changelog/no-changelog, Profiling

#11667 chore(asm): libddwaf 1.22.0
  releasenotes/notes/waf_1.22.0-05b1dfbaa0d47059.yaml
  setup.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: ASM

#11650 refactor(asm): update package resolution
  ddtrace/internal/packages.py
  ddtrace/internal/telemetry/data.py
  ddtrace/internal/telemetry/modules.py
  ddtrace/internal/telemetry/writer.py
Labels: changelog/no-changelog, ASM

#11576 chore: clarify wrapping context behaviour
  ddtrace/internal/wrapping/context.py
Labels: changelog/no-changelog, mergequeue-status: removed

#11654 chore(profiling): revert simplify usage of cancellation token
  .github/workflows/system-tests.yml
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  tests/profiling_v2/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#11649 refactor: encapsulate container info
  ddtrace/debugging/_uploader.py
  ddtrace/internal/http.py
  ddtrace/internal/processor/stats.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/runtime/container.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/uds.py
  ddtrace/internal/utils/__init__.py
  ddtrace/internal/writer/writer.py
  ddtrace/profiling/exporter/http.py
  tests/tracer/runtime/test_container.py
Labels: changelog/no-changelog

#11643 chore: update formatters for native code
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt
  scripts/cformat.sh
  scripts/cmake-format.sh
Labels: changelog/no-changelog, mergequeue-status: removed

#11404 chore(symdb): upload compressed symbol payloads
  ddtrace/internal/symbol_db/symbols.py
  ddtrace/internal/utils/http.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11672 chore: fix cmake format
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
Labels: changelog/no-changelog, Profiling

#11661 chore(profiling): tweak lock collector impl for clarity
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/asyncio.py
  ddtrace/profiling/collector/threading.py
  tests/profiling/collector/test_threading.py
  tests/profiling_v2/collector/test_threading.py
Labels: changelog/no-changelog, Profiling, mergequeue-status: in_progress

#11652 fix(langchain): pydantic output parser tagging does not throw
  ddtrace/contrib/internal/langchain/patch.py
  releasenotes/notes/langchain-pydantic-output-parsers-19bc162212ec051e.yaml
Labels: backport 2.15, backport 2.16, backport 2.17

#11653 fix: kafka consumer parenting logic
  ddtrace/contrib/internal/kafka/patch.py
  releasenotes/notes/fix-kafka-consumer-parenting-29acfd08e05d2350.yaml
  tests/contrib/kafka/test_kafka.py
Labels: mergequeue-status: rejected

#11688 fix(asm): use unpatched json loads internally
  ddtrace/appsec/_utils.py
  ddtrace/internal/_unpatched.py
  releasenotes/notes/fix-appsec-use-unpatched-json-8d09aacad4808ef2.yaml
Labels: ASM, backport 2.11, backport 2.12, backport 2.13, backport 2.14, backport 2.15, backport 2.16, backport 2.17

#11696 chore(ci_visibility): make codeowners file relative to repo path
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/recorder.py
Labels: changelog/no-changelog

#11692 ci: use mocks for GitHub calls in needs_testrun.py tests
  .riot/requirements/151a249.txt
  .riot/requirements/196755b.txt
  .riot/requirements/4d1fa34.txt
  .riot/requirements/b2ac981.txt
  hatch.toml
  riotfile.py
  scripts/needs_testrun.py
  scripts/vcr/needs_testrun.yaml
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11695 chore(profiling): ddup.upload() optionally gets tracer object
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/profiling/profiler.py
  ddtrace/profiling/scheduler.py
  tests/profiling_v2/collector/test_asyncio.py
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#11690 ci: store fake DD_API_KEY as a secret
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11698 ci: fix flaky aiohttp test failure
  tests/contrib/aiohttp/test_request.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#11710 chore(ci): enable quality gates
  .gitlab-ci.yml
Labels: changelog/no-changelog

#11713 chore(docs): add vertexai docs
  docs/integrations.rst
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog

#11662 fix(llmobs): do not ignore global patch env vars
  ddtrace/llmobs/_llmobs.py
  releasenotes/notes/fix-llmobs-do-not-ignore-global-patch-configs-a2adc4803f55b142.yaml
  tests/llmobs/test_llmobs_service.py
Labels: backport 2.16, backport 2.17

#11543 chore(llmobs): use span store instead of temporary tags
  ddtrace/llmobs/_integrations/anthropic.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/gemini.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/openai.py
  ddtrace/llmobs/_integrations/vertexai.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/_utils.py
  ddtrace/llmobs/_writer.py
  ddtrace/llmobs/decorators.py
  tests/contrib/anthropic/test_anthropic_llmobs.py
  tests/contrib/openai/test_openai_llmobs.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_span_agentless_writer.py
  tests/llmobs/test_llmobs_span_encoder.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog, manual merge

#11720 chore(iast): move env var to config
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/settings/asm.py
  tests/appsec/iast/test_overhead_control_engine.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#11711 ci: fix needs_testrun tests. do not record all requests
  scripts/needs_testrun.py
Labels: changelog/no-changelog

#11709 ci: use hatch to execute needs_testrun.py
  hatch.toml
  scripts/needs_testrun.py
  scripts/run-test-suite
  scripts/run-test-suite-hatch
Labels: changelog/no-changelog

#11707 ci: wait for es server to be up before running tests
  tests/contrib/elasticsearch/test_elasticsearch.py
Labels: changelog/no-changelog

#11627 fix(lib-injection): fix SSI abort telemetry metrics
  lib-injection/sources/sitecustomize.py
  releasenotes/notes/fix-lib-injection-telemetry-4fbea5e41ee1ff3e.yaml
Labels: mergequeue-status: rejected

#11604 chore(iast): attach to root span if running inside pytest
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_pytest_plugin.py
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/iast/__init__.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/plugin.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
  tests/contrib/flask/app.py
  tests/contrib/flask/test_appsec_flask_pytest_iast_no_snapshot.py
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/contrib/flask/test_flask_pytest_iast.py
Labels: changelog/no-changelog, ASM

#11668 ci: pass correct suite names in CircleCI gen script
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#11607 chore(di): accurate function line mapping
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_function/discovery.py
  ddtrace/internal/utils/inspection.py
  tests/debugging/function/test_discovery.py
  tests/debugging/test_debugger.py
  tests/submod/custom_decorated_stuff.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11735 chore(ci): upgrade python for build action
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#11736 chore(ci_visibility): support pytest-benchmark plugin in v2 of pytest plugin
  .riot/requirements/498209d.txt
  .riot/requirements/e5cd460.txt
  ddtrace/contrib/pytest/_benchmark_utils.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest_benchmark/constants.py
  ddtrace/contrib/pytest_benchmark/plugin.py
  ddtrace/internal/ci_visibility/api/_base.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/test_visibility/_benchmark_mixin.py
  ddtrace/internal/test_visibility/api.py
  riotfile.py
  tests/contrib/pytest_benchmark/test_pytest_benchmark.py
Labels: changelog/no-changelog

#11574 feat(asm): add stack trace report for iast
  .circleci/config.templ.yml
  .gitlab/services.yml
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_exploit_prevention/stack_traces.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_processor.py
  docker-compose.yml
  releasenotes/notes/stack_traces_for_iast-cd2c008168f6181e.yaml
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
  tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
Labels: ASM

#11739 ci: wait longer for opensearch to start
  tests/contrib/elasticsearch/test_elasticsearch.py
Labels: changelog/no-changelog

#11721 chore: refactor the debugger for clarity
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_function/store.py
Labels: changelog/no-changelog

#11723 chore: use guess-next-dev instead of release-branch-semver [2.18]
  pyproject.toml
Labels: changelog/no-changelog

#11745 chore(llmobs): ensure propagated parent IDs are still using span tags
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_llmobs.py
Labels: changelog/no-changelog

#11712 ci: add clearer breakdown of test stages and dependencies between jobs
  .gitlab/tests.yml
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog

#11753 chore(ci_visibility): add support for pytest_bdd to v2 plugin
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_pytest_bdd_subplugin.py
  ddtrace/contrib/pytest_bdd/plugin.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/test_visibility/api.py
  riotfile.py
  tests/contrib/pytest_bdd/test_pytest_bdd.py
Labels: changelog/no-changelog

#11752 fix(iast): check context is enable in request and builtins patched funcions
  ddtrace/appsec/_common_module_patches.py
  releasenotes/notes/iast-fix-iast-propagation-error-2-ba4a998133269a7c.yaml
Labels: ASM, backport 2.14, backport 2.15, backport 2.16, backport 2.17, backport 2.18

#11647 fix(datastreams): botocore - log warning on kinesis stream metadata not found
  ddtrace/internal/datastreams/botocore.py
  releasenotes/notes/log-warning-on-kinesis-stream-metadata-not-found-a921cabed5d4397e.yaml
Labels: mergequeue-status: in_progress

#11757 chore(di): cache function code pair resolution
  ddtrace/debugging/_function/discovery.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11655 feat(asm): standalone sca billing
  ddtrace/_trace/tracer.py
  releasenotes/notes/feat-standalone-sca-billing-925c84d69fe061ce.yaml
  tests/appsec/appsec/test_asm_standalone.py
  tests/tracer/test_propagation.py
  tests/tracer/test_tracer.py
Labels: ASM

#11749 chore(ci): switch ubuntu runner image in generate package versions workflow
  .github/workflows/generate-package-versions.yml
Labels: changelog/no-changelog

#11501 ci(asm): appsec_integrations suite improvments [backport 2.16]
  .circleci/config.templ.yml
  tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
Labels: changelog/no-changelog, CI

#11601 refactor(iast): simplify ``__mod__`` aspect
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectModulo.cpp
Labels: changelog/no-changelog, ASM

#11741 ci(celery): increase amqp task timeout
  tests/contrib/celery/test_tagging.py
Labels: changelog/no-changelog

#11774 chore(profiling): remove unused mutex
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample_manager.hpp
Labels: changelog/no-changelog, Profiling

#11747 chore(profiling): refactor fetch libdatadog
  ddtrace/internal/datadog/profiling/build_standalone.sh
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/fetch_libdatadog.sh
  ddtrace/internal/datadog/profiling/cmake/tools/libdatadog_checksums.txt
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
Labels: changelog/no-changelog, Profiling, mergequeue-status: in_progress

#11769 ci: enable standalone sca system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, ASM, CI

#11737 chore(er): correct exception ID field name
  ddtrace/debugging/_exception/replay.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11789 ci: do not use datadog-ci binary
  .gitlab-ci.yml
Labels: changelog/no-changelog

#11771 chore(di): capture exception chain
  ddtrace/debugging/_signal/utils.py
  tests/debugging/exception/test_replay.py
  tests/debugging/test_debugger.py
  tests/debugging/test_encoding.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11772 chore(er): include exception hash
  ddtrace/debugging/_exception/replay.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11780 ci: wait for dependent services before running tests
  .gitlab/tests.yml
  .riot/requirements/151d7b0.txt
  .riot/requirements/1805689.txt
  hatch.toml
  riotfile.py
  scripts/gen_gitlab_config.py
  tests/suitespec.yml
  tests/wait-for-services.py
Labels: changelog/no-changelog

#11792 docs: add details to the release note about 3.13
  releasenotes/notes/threethirteen-d40d659d8939fe5e.yaml
Labels: changelog/no-changelog

#11759 fix(library): catch exceptions raised while enabling ddtrace integrations
  ddtrace/_monkey.py
  releasenotes/notes/refactor-patch-error-ssi-1a2e9fe206d6d6df.yaml
  tests/telemetry/test_telemetry.py
Labels: backport 2.18

#11784 chore(llmobs): refactor trace processor tests
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog

#11498 fix(celery): stop closing prerun_span too soon to account for Celery chains scenario
  ddtrace/contrib/internal/celery/app.py
  ddtrace/contrib/internal/celery/signals.py
  releasenotes/notes/fix-celery-closed-spans-34ff43868c1e33b8.yaml
  tests/contrib/celery/run_tasks.py
  tests/contrib/celery/tasks.py
  tests/contrib/celery/test_chained_task.py
Labels: mergequeue-status: removed, backport 2.16, backport 2.17, backport 2.18

#11372 chore: output supported versions of integrations
  .github/workflows/generate-supported-versions.yml
  scripts/freshvenvs.py
  scripts/generate_table.py
  scripts/regenerate-riot-latest.sh
Labels: changelog/no-changelog

#11763 chore: remove expired until from django snapshot test
  tests/contrib/django/test_django_snapshots.py
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_middleware_trace_partial_based_view.json
Labels: changelog/no-changelog

#11750 chore(profiling): native tests w/ valgrind
  .github/workflows/profiling-native.yml
  ddtrace/internal/datadog/profiling/build_standalone.sh
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/test/valgrind.supp
  ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/test/valgrind.supp
Labels: changelog/no-changelog

#11798 ci: optimize ci runtime
  .gitlab/package.yml
  .gitlab/tests.yml
  hatch.toml
  scripts/gen_gitlab_config.py
  tests/suitespec.yml
Labels: changelog/no-changelog

#11809 ci: cmake format fix
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#11765 docs: mandatory issue templates (AIDM-423)
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  SECURITY.md
Labels: changelog/no-changelog

#11807 ci: revert CI fix
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#11812 chore(ci): upgrade python for build action [backport 2.17]
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#11813 chore(ci): upgrade python for build action [backport 2.16]
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog

#11615 chore(ci_visibility): add quarantine support to pytest
  ddtrace/contrib/pytest/_atr_utils.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_retry_utils.py
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/api/_base.py
  ddtrace/internal/ci_visibility/api/_session.py
  ddtrace/internal/ci_visibility/api/_suite.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/telemetry/events.py
  ddtrace/internal/ci_visibility/telemetry/git.py
  ddtrace/internal/test_visibility/api.py
  tests/ci_visibility/api_client/_util.py
  tests/ci_visibility/test_encoder.py
  tests/ci_visibility/test_quarantine.py
  tests/contrib/pytest/test_pytest_atr.py
  tests/contrib/pytest/test_pytest_efd.py
  tests/contrib/pytest/test_pytest_quarantine.py
Labels: changelog/no-changelog

#11740 ci(gevent): improve ddtrace-run test assertion message
  tests/contrib/gevent/test_tracer.py
  tests/contrib/suitespec.yml
Labels: changelog/no-changelog

#11799 chore: remove time module functions from ddtrace.internal.compat
  benchmarks/rate_limiter/scenario.py
  ddtrace/_trace/span.py
  ddtrace/contrib/internal/botocore/services/kinesis.py
  ddtrace/contrib/internal/kafka/patch.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_origin/span.py
  ddtrace/internal/compat.py
  ddtrace/internal/opentelemetry/span.py
  ddtrace/internal/rate_limiter.py
  ddtrace/internal/utils/time.py
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/scheduler.py
  ddtrace/vendor/__init__.py
  ddtrace/vendor/monotonic/__init__.py
  tests/debugging/mocking.py
  tests/integration/test_sampling.py
  tests/profiling/exporter/test_http.py
  tests/profiling/test_accuracy.py
  tests/profiling/test_scheduler.py
  tests/submod/stuff.py
  tests/tracer/test_rate_limiter.py
Labels: changelog/no-changelog

#11815 chore: update changelog for version 2.18.1, 2.18.0, 2.17.3, 2.16.6
  CHANGELOG.md
Labels: changelog/no-changelog

#11795 chore(docs): remove `DD_TRACE_ENABLED` from configuration docs
  docs/configuration.rst
Labels: changelog/no-changelog

#11679 chore(profiling): more tests for libdd and stack_v2
  tests/profiling/collector/test_stack.py
  tests/profiling/test_accuracy.py
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/simple_program.py
  tests/profiling_v2/simple_program_fork.py
  tests/profiling_v2/simple_program_gevent.py
  tests/profiling_v2/test_accuracy.py
  tests/profiling_v2/test_main.py
  tests/profiling_v2/test_profiler.py
  tests/profiling_v2/test_scheduler.py
Labels: changelog/no-changelog, Profiling

#11816 docs: fix create issue screen: rename config.yaml -> yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: changelog/no-changelog

#11787 chore(iast): memory leak in aspect modulo
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectModulo.cpp
Labels: changelog/no-changelog, ASM

#11814 chore(tracing): move mini agent out of tracing
  ddtrace/__init__.py
  ddtrace/_trace/tracer.py
Labels: changelog/no-changelog

#11830 chore: use guess-next-dev instead of release-branch-semver [2.19]
  pyproject.toml
Labels: changelog/no-changelog

#11829 fix: error parsing response cookies in FastAPI and awsgi
  ddtrace/contrib/internal/asgi/middleware.py
  releasenotes/notes/iast-fix-awsgi-368c173e1f012400.yaml
  tests/contrib/asgi/test_asgi.py
Labels: ASM, backport 2.16, backport 2.17, backport 2.18, backport 2.19

#11828 chore(ci_visibility): add quarantine skipping mode for pytest
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/test_visibility/api.py
  docs/configuration.rst
  riotfile.py
  tests/contrib/pytest/test_pytest_quarantine.py
Labels: changelog/no-changelog

#11840 chore(docs): add vertexai, anthropic to integrations docs
  docs/index.rst
  docs/integrations.rst
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog
