Repository DataDog/dd-trace-py, pull requests merged in 2024-08, with the labels that each got.

#10014 fix(profiling): capture lock usages with `with` statement context manager [backport 2.9]
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml
  tests/profiling/collector/test_threading.py
Labels: Profiling

#10015 fix(profiling): capture lock usages with `with` statement context managers [backport 2.8]
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml
  tests/profiling/collector/test_threading.py
Labels: Profiling

#10016 fix(profiling): capture lock usages with `with` statement context managers [backport 2.7]
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml
  tests/profiling/collector/test_threading.py
Labels: Profiling

#10005 chore: create pygoat docker using local ddtrace repo, re-enable pygoat tests
  docker-compose.yml
  tests/appsec/integrations/pygoat_tests/Dockerfile.pygoat.2.0.1
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: changelog/no-changelog, ASM

#9989 fix(ci_visibility): don't rely on git in pytest plugin
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/ext/git.py
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci_visibility-fix-dont_make_pytest_contrib_depend_on_git-d922e9326c981f38.yaml
  tests/contrib/pytest/test_pytest.py
Labels: backport 2.7, backport 2.8, backport 2.9, backport 2.10

#9939 chore(ci_visibility): fix potential hang when waiting for multiprocessing children
  .github/CODEOWNERS
  ddtrace/internal/coverage/code.py
  ddtrace/internal/coverage/multiprocessing_coverage.py
  tests/coverage/test_coverage_multiprocessing.py
Labels: changelog/no-changelog

#9974 fix(opentelemetry): resolve lazy sampling + distributed tracing bug
  ddtrace/opentelemetry/_span.py
  releasenotes/notes/otel-ensure-sampling-decision-is-made-40ab760eada20b20.yaml
  tests/opentelemetry/test_trace.py
  tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_ddtrace_run].json
  tests/snapshots/tests.opentelemetry.test_trace.test_distributed_trace_with_flask_app[with_opentelemetry_instrument].json
Labels: backport 2.9, backport 2.10

#10027 docs: update the definition of internal
  docs/versioning.rst
Labels: changelog/no-changelog

#10040 chore(profiling): fix mypy typing in profiling
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack_event.py
  ddtrace/profiling/event.py
  ddtrace/profiling/scheduler.py
Labels: changelog/no-changelog, Profiling

#10043 chore: update release note wording for #9610
  releasenotes/notes/profiling-add-lock-with-f75908e35a70ab71.yaml
Labels: changelog/no-changelog, Profiling, backport 2.7, backport 2.8, backport 2.9, backport 2.10

#10038 docs(advanced_usage): clarify ddtrace-run info command
  docs/advanced_usage.rst
Labels: changelog/no-changelog

#10017 chore(integrations): move asyncio, aiohttp, aiohttp_jinja2, aiomysql, aiopg to internal
  ddtrace/contrib/aiobotocore/__init__.py
  ddtrace/contrib/aiobotocore/patch.py
  ddtrace/contrib/aiohttp/__init__.py
  ddtrace/contrib/aiohttp/middlewares.py
  ddtrace/contrib/aiohttp/patch.py
  ddtrace/contrib/aiohttp_jinja2/__init__.py
  ddtrace/contrib/aiohttp_jinja2/patch.py
  ddtrace/contrib/aiomysql/__init__.py
  ddtrace/contrib/aiomysql/patch.py
  ddtrace/contrib/aiopg/__init__.py
  ddtrace/contrib/aiopg/connection.py
  ddtrace/contrib/aiopg/patch.py
  ddtrace/contrib/asyncio/__init__.py
  ddtrace/contrib/asyncio/compat.py
  ddtrace/contrib/asyncio/helpers.py
  ddtrace/contrib/asyncio/patch.py
  ddtrace/contrib/asyncio/provider.py
  ddtrace/contrib/asyncio/wrappers.py
  ddtrace/contrib/internal/__init__.py
  ddtrace/contrib/internal/aiobotocore/patch.py
  ddtrace/contrib/internal/aiohttp/middlewares.py
  ddtrace/contrib/internal/aiohttp/patch.py
  ddtrace/contrib/internal/aiohttp_jinja2/patch.py
  ddtrace/contrib/internal/aiomysql/patch.py
  ddtrace/contrib/internal/aiopg/connection.py
  ddtrace/contrib/internal/aiopg/patch.py
  ddtrace/contrib/internal/asyncio/compat.py
  ddtrace/contrib/internal/asyncio/helpers.py
  ddtrace/contrib/internal/asyncio/patch.py
  ddtrace/contrib/internal/asyncio/provider.py
  ddtrace/contrib/internal/asyncio/wrappers.py
  tests/.suitespec.json
Labels: changelog/no-changelog

#10042 chore: update changelog for version 2.10.2
  CHANGELOG.md
Labels: changelog/no-changelog

#10030 fix(asm): switch back to default if remote config stop sending the security rule file
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_remoteconfiguration.py
  releasenotes/notes/fix_rc_asm_dd_no_file-37e6f733583e334c.yaml
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: bug, ASM, backport 2.9, backport 2.10

#10021 fix(internal): fix telemetry URL for EU
  ddtrace/internal/telemetry/writer.py
  releasenotes/notes/ci_visibility-fix-update_eu_telemetry_url-0642a6f665c75a0f.yaml
  tests/telemetry/test_writer.py
Labels: backport 2.8, backport 2.9, backport 2.10

#10052 fix(asm): switch back to default if remote config stop sending the security rule file [backport 2.10]
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_remoteconfiguration.py
  releasenotes/notes/fix_rc_asm_dd_no_file-37e6f733583e334c.yaml
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: bug, ASM, backport 2.9

#10056 chore(asm): add test for immutability of static rules in appsec processor
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#9951 chore(iast): tests for tracer.configure over env var
  tests/appsec/iast/fixtures/integration/main_configure.py
  tests/appsec/iast/fixtures/integration/main_configure_right.py
  tests/appsec/iast/fixtures/integration/main_configure_wrong.py
  tests/appsec/iast/test_env_var.py
Labels: changelog/no-changelog, ASM

#10031 fix(profiling): export lock acquire/release call location and variable name [backport 2.10]
  ddtrace/profiling/collector/_lock.py
  ddtrace/settings/profiling.py
  tests/profiling/collector/global_locks.py
  tests/profiling/collector/test_asyncio.py
  tests/profiling/collector/test_threading.py
  tests/profiling/collector/test_threading_asyncio.py
  tests/profiling/simple_program_fork.py
Labels: changelog/no-changelog, Profiling

#10058 chore: add setuptools for the cffi package test
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#9743 chore(internal): update cache max size to for module/package/file
  ddtrace/internal/packages.py
Labels: changelog/no-changelog

#10019 fix: use zip instead of tar for the tracer flare
  ddtrace/internal/flare/flare.py
Labels: changelog/no-changelog, backport 2.10

#10069 chore: update changelog for version 2.8.6
  CHANGELOG.md
Labels: changelog/no-changelog

#10037 ci: update some rotted framework tests
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog, backport 2.8, backport 2.9, backport 2.10

#10070 chore: update changelog for version 2.9.5
  CHANGELOG.md
Labels: changelog/no-changelog

#10071 chore: update changelog for version 2.10.3
  CHANGELOG.md
Labels: changelog/no-changelog

#9952 chore(iast): debug propagation tool
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/appsec_utils.py
  tests/appsec/integrations/test_flask_iast_patching.py
Labels: changelog/no-changelog, ASM

#10067 chore(internal): improve generate OCI package size
  .gitlab/prepare-oci-package.sh
  lib-injection/dedupe.py
Labels: changelog/no-changelog

#10073 feat(asm): add command injection support for exploit prevention
  ddtrace/appsec/_capabilities.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_processor.py
  releasenotes/notes/rasp_command_inject_os_system-ec5c2193bd451264.yaml
  tests/appsec/appsec/rules-rasp-blocking.json
  tests/appsec/appsec/rules-rasp-disabled.json
  tests/appsec/appsec/rules-rasp.json
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec_iast.py
Labels: ASM

#10086 chore(ci): run build_deploy on release branches and build_deploy* branches
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog, CI

#10082 chore(profiling): fix errors with type.py
  ddtrace/internal/datadog/profiling/_types.py
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyi
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyx
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/internal/datadog/profiling/util.py
Labels: changelog/no-changelog

#10065 fix(profiling): add debug asserts for our stack assumptions (#9689) [backport-2.10]
  ddtrace/profiling/collector/_lock.py
  ddtrace/settings/profiling.py
  riotfile.py
Labels: changelog/no-changelog, Profiling

#10061 chore(lib-injection): don't allow any uncaught exceptions originating in ddtrace
  ddtrace/commands/ddtrace_run.py
  lib-injection/sitecustomize.py
  tests/commands/test_runner.py
Labels: changelog/no-changelog

#10041 chore: add `docs/` to `apm-python` code ownership
  .github/CODEOWNERS
Labels: changelog/no-changelog, backport 2.9, backport 2.10

#10085 chore(w3c): do not set _dd.parent_id to 16 zeros
  ddtrace/internal/constants.py
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#10084 fix(llmobs): do not emit integration metrics in agentless mode
  ddtrace/llmobs/_integrations/base.py
  releasenotes/notes/fix-llmobs-agentless-openai-metrics-cfeb4458555d51be.yaml
  tests/contrib/openai/conftest.py
  tests/contrib/openai/test_openai_llmobs.py
Labels: backport 2.11

#10090 chore: add docs/ to apm-python code ownership [backport 2.9]
  .github/CODEOWNERS
Labels: changelog/no-changelog

#10049 chore(profiling): fix flaky tests
  tests/profiling/collector/test_memalloc.py
  tests/profiling/collector/test_stack.py
  tests/profiling/collector/test_threading.py
  tests/profiling/collector/utils.py
  tests/profiling/test_main.py
  tests/profiling/test_uwsgi.py
Labels: changelog/no-changelog

#10036 chore(opentelemetry): move _span.py and _trace.py to internal package
  ddtrace/internal/opentelemetry/context.py
  ddtrace/internal/opentelemetry/span.py
  ddtrace/internal/opentelemetry/trace.py
  ddtrace/opentelemetry/__init__.py
  tests/opentelemetry/test_span.py
Labels: changelog/no-changelog

#10092 chore(profiling): use libdatadog version v12.0.0
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/libdatadog_checksums.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/receiver_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
Labels: changelog/no-changelog, Profiling

#9972 chore(di): report correlation IDs as strings
  ddtrace/debugging/_encoding.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#10057 chore(ci_visibility): introduce pytest test visibility plugin v2 using external API
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/contrib/pytest/utils.py
  ddtrace/internal/ci_visibility/api/ci_base.py
  ddtrace/internal/ci_visibility/api/ci_module.py
  ddtrace/internal/ci_visibility/api/ci_session.py
  ddtrace/internal/ci_visibility/api/ci_suite.py
  ddtrace/internal/ci_visibility/recorder.py
Labels: changelog/no-changelog

#10098 chore(asm): improve patching mechanism
  ddtrace/appsec/_common_module_patches.py
  tests/appsec/appsec/test_exploit_prevention.py
Labels: changelog/no-changelog, ASM, backport 2.11

#10099 chore(asm): improve patching mechanism (#10098) [backport 2.11]
  ddtrace/appsec/_common_module_patches.py
  tests/appsec/appsec/test_exploit_prevention.py
Labels: changelog/no-changelog, ASM

#10089 chore(openai): avoid test skipping
  tests/contrib/openai/test_openai_llmobs.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog

#9806 chore(internal): use `lru_cache` instead of custom cache implementation in packages module
  ddtrace/internal/packages.py
Labels: changelog/no-changelog

#10066 fix(profiling): stack_v2 properly tracks Threading
  ddtrace/internal/datadog/profiling/stack_v2/include/sampler.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/collector/threading.py
Labels: changelog/no-changelog, Profiling

#10059 chore(integrations): move asyncpg,aws_lambda,boto,botocore,bottle to internal
  ddtrace/contrib/asyncpg/__init__.py
  ddtrace/contrib/asyncpg/patch.py
  ddtrace/contrib/aws_lambda/__init__.py
  ddtrace/contrib/aws_lambda/_cold_start.py
  ddtrace/contrib/aws_lambda/patch.py
  ddtrace/contrib/boto/__init__.py
  ddtrace/contrib/boto/patch.py
  ddtrace/contrib/botocore/__init__.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/bedrock.py
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/sqs.py
  ddtrace/contrib/botocore/services/stepfunctions.py
  ddtrace/contrib/botocore/utils.py
  ddtrace/contrib/bottle/__init__.py
  ddtrace/contrib/bottle/patch.py
  ddtrace/contrib/bottle/trace.py
  ddtrace/contrib/internal/asyncpg/patch.py
  ddtrace/contrib/internal/aws_lambda/_cold_start.py
  ddtrace/contrib/internal/aws_lambda/patch.py
  ddtrace/contrib/internal/boto/patch.py
  ddtrace/contrib/internal/botocore/patch.py
  ddtrace/contrib/internal/botocore/services/bedrock.py
  ddtrace/contrib/internal/botocore/services/kinesis.py
  ddtrace/contrib/internal/botocore/services/sqs.py
  ddtrace/contrib/internal/botocore/services/stepfunctions.py
  ddtrace/contrib/internal/botocore/utils.py
  ddtrace/contrib/internal/bottle/patch.py
  ddtrace/contrib/internal/bottle/trace.py
  releasenotes/notes/move-integrations-to-internal-asyncpg-ab44088ac137baa6.yaml
  tests/contrib/botocore/test.py
  tests/contrib/botocore/test_bedrock.py
Labels: changelog/no-changelog

#9837 fix(profiling): use octet-stream as code provenance content type
  ddtrace/profiling/exporter/http.py
Labels: changelog/no-changelog

#10032 chore(internal): make regex range explict
  ddtrace/internal/debug.py
Labels: changelog/no-changelog

#10113 chore(profiling): remove unnecessary add_tag for runtime_id
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
Labels: changelog/no-changelog, Profiling

#10111 chore(langchain): mark batch snapshot test as flaky
  tests/contrib/langchain/test_langchain_community.py
Labels: changelog/no-changelog

#10121 chore(profiling): set runtime_id for crashtracker
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp
Labels: changelog/no-changelog, Profiling

#10129 chore(ci): properly set CMAKE_BUILD_PARALLEL_LEVEL for cibuildwheel
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog

#10026 chore(ci_visibility): do not send empty events when there are no traces
  ddtrace/internal/ci_visibility/encoder.py
  tests/ci_visibility/test_encoder.py
Labels: changelog/no-changelog

#10131 fix: add nullptr checks for new_pyobject_id
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  releasenotes/notes/iast-new-pyobject-check-6aecf9c4f22e2ae9.yaml
Labels: ASM, backport 2.9, backport 2.10, backport 2.11

#10125 fix(tornado): fix set_tag_str type error when http.route is none
  ddtrace/contrib/tornado/handlers.py
Labels: changelog/no-changelog, backport 2.10, backport 2.11

#10146 docs: fix 2.9 release note
  releasenotes/notes/fix-ssi-permissions-647693af3d5ce49d.yaml
Labels: changelog/no-changelog

#10150 ci(tracer): fix test_flush_queue_raise
  tests/tracer/test_writer.py
Labels: changelog/no-changelog

#9767 chore(telemetry): queue app-started on first sent payload
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/profiling/scheduler.py
  tests/integration/test_settings.py
  tests/telemetry/app.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#9942 chore(hatch): adds lint:checks script
  hatch.toml
Labels: changelog/no-changelog

#10151 chore(asnm): less flakyness in threat tests
  tests/appsec/contrib_appsec/conftest.py
Labels: changelog/no-changelog, ASM

#10135 fix: add nullptr checks for new_pyobject_id [backport 2.9]
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  releasenotes/notes/iast-new-pyobject-check-6aecf9c4f22e2ae9.yaml
Labels: ASM

#10116 ci: macrobenchmarks with profiling enabled
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI

#10153 ci: fix iast_memcheck flakyness
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM, CI, backport 2.9, backport 2.10, backport 2.11

#10152 ci(tracer): make tracer suite depend on ci_visibility
  tests/.suitespec.json
Labels: changelog/no-changelog

#10158 chore(asm): fix for threats test
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM, backport 2.9, backport 2.10, backport 2.11

#10159 chore(asm): import gc in unpatched
  ddtrace/appsec/_common_module_patches.py
  ddtrace/internal/_unpatched.py
Labels: changelog/no-changelog, ASM

#10142 chore: update changelog for version 2.10.4
  CHANGELOG.md
Labels: changelog/no-changelog

#10122 chore: remove py2.7 compatibility code
  ddtrace/internal/packages.py
Labels: changelog/no-changelog

#10161 ci: mark flaky test
  tests/tracer/runtime/test_runtime_metrics.py
Labels: changelog/no-changelog

#10110 chore(integrations): move django, dogpile_cache,dramtiq,elasticsearch,falcon to internal
  ddtrace/contrib/django/__init__.py
  ddtrace/contrib/django/_asgi.py
  ddtrace/contrib/django/compat.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/django/restframework.py
  ddtrace/contrib/django/utils.py
  ddtrace/contrib/dogpile_cache/__init__.py
  ddtrace/contrib/dogpile_cache/lock.py
  ddtrace/contrib/dogpile_cache/patch.py
  ddtrace/contrib/dogpile_cache/region.py
  ddtrace/contrib/dramatiq/__init__.py
  ddtrace/contrib/dramatiq/patch.py
  ddtrace/contrib/elasticsearch/__init__.py
  ddtrace/contrib/elasticsearch/patch.py
  ddtrace/contrib/elasticsearch/quantize.py
  ddtrace/contrib/falcon/__init__.py
  ddtrace/contrib/falcon/middleware.py
  ddtrace/contrib/falcon/patch.py
  ddtrace/contrib/internal/django/_asgi.py
  ddtrace/contrib/internal/django/compat.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/django/restframework.py
  ddtrace/contrib/internal/django/utils.py
  ddtrace/contrib/internal/dogpile_cache/lock.py
  ddtrace/contrib/internal/dogpile_cache/patch.py
  ddtrace/contrib/internal/dogpile_cache/region.py
  ddtrace/contrib/internal/dramatiq/patch.py
  ddtrace/contrib/internal/elasticsearch/patch.py
  ddtrace/contrib/internal/elasticsearch/quantize.py
  ddtrace/contrib/internal/falcon/middleware.py
  ddtrace/contrib/internal/falcon/patch.py
  releasenotes/notes/move-integrations-to-internal-django-1554664491477408.yaml
  tests/contrib/django/test_django_utils.py
Labels: changelog/no-changelog

#10127 chore(integrations): move fastapi,flask,flask_cache,futures to internal
  ddtrace/contrib/fastapi/__init__.py
  ddtrace/contrib/fastapi/patch.py
  ddtrace/contrib/flask/__init__.py
  ddtrace/contrib/flask/patch.py
  ddtrace/contrib/flask/wrappers.py
  ddtrace/contrib/flask_cache/__init__.py
  ddtrace/contrib/flask_cache/tracers.py
  ddtrace/contrib/flask_cache/utils.py
  ddtrace/contrib/futures/__init__.py
  ddtrace/contrib/futures/patch.py
  ddtrace/contrib/futures/threading.py
  ddtrace/contrib/internal/fastapi/patch.py
  ddtrace/contrib/internal/flask/patch.py
  ddtrace/contrib/internal/flask/wrappers.py
  ddtrace/contrib/internal/flask_cache/tracers.py
  ddtrace/contrib/internal/flask_cache/utils.py
  ddtrace/contrib/internal/futures/patch.py
  ddtrace/contrib/internal/futures/threading.py
  releasenotes/notes/move-integrations-to-internal-fastapi-348259e3fe88465e.yaml
  tests/contrib/flask/test_idempotency.py
  tests/contrib/flask_cache/test_utils.py
Labels: changelog/no-changelog

#10164 ci: mark flaky test
  tests/tracer/test_memory_leak.py
Labels: changelog/no-changelog

#10162 ci: mark flaky test
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog

#9872 chore: iast aspects microbenchmarks
  .github/CODEOWNERS
  .gitlab/benchmarks.yml
  benchmarks/appsec_iast_aspects/config.yaml
  benchmarks/appsec_iast_aspects/scenario.py
  benchmarks/bm/_scenario.py
  benchmarks/bm/iast_fixtures/module_functions.py
  benchmarks/bm/iast_fixtures/str_methods.py
  benchmarks/bm/iast_fixtures/str_methods_py3.py
  benchmarks/bm/iast_utils/aspects_benchmarks_generate.py
  tests/appsec/iast/aspects/aspect_utils.py
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_common_replace_aspects.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_format_map_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_modulo_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_other_patching.py
  tests/appsec/iast/aspects/test_side_effects.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/test_telemetry.py
Labels: changelog/no-changelog, manual merge, ASM

#10172 fix(telemetry): fix integration name telemetry after refactoring to internal
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog, CI

#10124 chore(profiling): use lock-free queue to manage samples to avoid frequent alloc/free
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/constants.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/ddup_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample_manager.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/synchronized_sample_pool.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample_manager.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/synchronized_sample_pool.cpp
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/profiling/profiler.py
  ddtrace/settings/profiling.py
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog, Profiling

#10176 fix(internal): hold rate limiter native implementation in a mutex
  releasenotes/notes/fix-rate-limiter-borrow-263dedb6e46ba74e.yaml
  src/core/rate_limiter.rs
Labels: backport 2.10, backport 2.11

#10182 chore(profiling): set libdd_required when timeline_enabled
  ddtrace/settings/profiling.py
Labels: changelog/no-changelog, Profiling

#10188 chore(profiling): improve native module loading [backport-2.10]
  ddtrace/internal/datadog/profiling/ddup/__init__.py
  ddtrace/internal/datadog/profiling/stack_v2/__init__.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/profiler.py
  ddtrace/settings/profiling.py
Labels: changelog/no-changelog, Profiling

#10107 chore(profiling): output pprof file with `DD_PROFILING_{EXPORT_LIBDD_ENABLED, OUTPUT_PPROF}`
  ddtrace/internal/datadog/profiling/dd_wrapper/include/ddup_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader_builder.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader_builder.cpp
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/profiling/profiler.py
Labels: changelog/no-changelog, Profiling

#10190 chore(ci): update contrib suitespec
  tests/.suitespec.json
Labels: changelog/no-changelog, CI

#10104 chore(ci_visibility): add ITR support to v2 pytest plugin
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_utils.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/ext/ci_visibility/api.py
  ddtrace/internal/ci_visibility/api/ci_base.py
  ddtrace/internal/ci_visibility/api/ci_suite.py
  ddtrace/internal/ci_visibility/recorder.py
  riotfile.py
  tests/ci_visibility/api/test_internal_ci_visibility_api.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_skip.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_pass.json
Labels: changelog/no-changelog

#10112 fix(redis): define result in _run_redis_command
  ddtrace/contrib/redis/patch.py
Labels: changelog/no-changelog

#10168 chore(integrations): move langchain,logbook,logging,loguru to internal
  ddtrace/contrib/internal/langchain/constants.py
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/contrib/internal/logbook/patch.py
  ddtrace/contrib/internal/logging/constants.py
  ddtrace/contrib/internal/logging/patch.py
  ddtrace/contrib/internal/loguru/patch.py
  ddtrace/contrib/langchain/__init__.py
  ddtrace/contrib/langchain/constants.py
  ddtrace/contrib/langchain/patch.py
  ddtrace/contrib/logbook/__init__.py
  ddtrace/contrib/logbook/patch.py
  ddtrace/contrib/logging/__init__.py
  ddtrace/contrib/logging/constants.py
  ddtrace/contrib/logging/patch.py
  ddtrace/contrib/loguru/__init__.py
  ddtrace/contrib/loguru/patch.py
  releasenotes/notes/move-integrations-to-internal-langchain-2cd7ff9a1362182d.yaml
Labels: changelog/no-changelog

#10060 ci(lib-injection): set injection vars in riot tests
  ddtrace/settings/profiling.py
  riotfile.py
  tests/profiling/test_gunicorn.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#10192 fix(profiling): add missing release note for #10182
  releasenotes/notes/profiling-libdd-required-685835434cda9968.yaml
Labels: Profiling

#10197 chore(ci): update contrib suitespec
  tests/.suitespec.json
Labels: changelog/no-changelog, CI

#10193 fix(ci): fix tracer log correlation tests
  .riot/requirements/1949e9a.txt
  riotfile.py
  tests/tracer/test_correlation_log_context.py
Labels: changelog/no-changelog

#10137 fix(django): recreate response stream to prevent reading from empty response body
  .riot/requirements/11065bb.txt
  .riot/requirements/16ae097.txt
  .riot/requirements/1d3001d.txt
  .riot/requirements/1ef9f39.txt
  .riot/requirements/1fe2c8e.txt
  .riot/requirements/2848d2c.txt
  .riot/requirements/cbc433f.txt
  .riot/requirements/d57247c.txt
  .riot/requirements/d5fcd88.txt
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/django/utils.py
  releasenotes/notes/fix-django-stream-body-exhausted-by-ddtrace-eb25702730c20e5e.yaml
  riotfile.py
  tests/contrib/django/soap/__init__.py
  tests/contrib/django/soap/apps.py
  tests/contrib/django/soap/models.py
  tests/contrib/django/soap/services.py
  tests/contrib/django/test_django_wsgi.py
  tests/contrib/django/utils.py
Labels: backport 2.10, backport 2.11

#10202 chore(profiling): update native tests
  ddtrace/internal/datadog/profiling/dd_wrapper/test/initialization.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/test_utils.hpp
Labels: changelog/no-changelog, Profiling

#10145 chore(integrations): move gevent,graphql,grpc to internal
  ddtrace/contrib/gevent/__init__.py
  ddtrace/contrib/gevent/greenlet.py
  ddtrace/contrib/gevent/patch.py
  ddtrace/contrib/gevent/provider.py
  ddtrace/contrib/graphql/__init__.py
  ddtrace/contrib/graphql/patch.py
  ddtrace/contrib/grpc/__init__.py
  ddtrace/contrib/grpc/aio_client_interceptor.py
  ddtrace/contrib/grpc/aio_server_interceptor.py
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/contrib/grpc/constants.py
  ddtrace/contrib/grpc/patch.py
  ddtrace/contrib/grpc/server_interceptor.py
  ddtrace/contrib/grpc/utils.py
  ddtrace/contrib/internal/gevent/greenlet.py
  ddtrace/contrib/internal/gevent/patch.py
  ddtrace/contrib/internal/gevent/provider.py
  ddtrace/contrib/internal/graphql/patch.py
  ddtrace/contrib/internal/grpc/aio_client_interceptor.py
  ddtrace/contrib/internal/grpc/aio_server_interceptor.py
  ddtrace/contrib/internal/grpc/client_interceptor.py
  ddtrace/contrib/internal/grpc/constants.py
  ddtrace/contrib/internal/grpc/patch.py
  ddtrace/contrib/internal/grpc/server_interceptor.py
  ddtrace/contrib/internal/grpc/utils.py
  releasenotes/notes/move-integrations-to-internal-gevent-0502e072141b1758.yaml
  tests/.suitespec.json
  tests/contrib/graphql/test_graphql.py
  tests/contrib/grpc/test_grpc.py
  tests/contrib/grpc/test_grpc_utils.py
  tests/contrib/grpc_aio/test_grpc_aio.py
Labels: changelog/no-changelog

#10166 chore(integrations): move httplib,httpx,jinja2,kafka,kombu to internal
  ddtrace/contrib/httplib/__init__.py
  ddtrace/contrib/httplib/patch.py
  ddtrace/contrib/httpx/__init__.py
  ddtrace/contrib/httpx/patch.py
  ddtrace/contrib/internal/httplib/patch.py
  ddtrace/contrib/internal/httpx/patch.py
  ddtrace/contrib/internal/jinja2/constants.py
  ddtrace/contrib/internal/jinja2/patch.py
  ddtrace/contrib/internal/kafka/patch.py
  ddtrace/contrib/internal/kombu/constants.py
  ddtrace/contrib/internal/kombu/patch.py
  ddtrace/contrib/internal/kombu/utils.py
  ddtrace/contrib/jinja2/__init__.py
  ddtrace/contrib/jinja2/constants.py
  ddtrace/contrib/jinja2/patch.py
  ddtrace/contrib/kafka/__init__.py
  ddtrace/contrib/kafka/patch.py
  ddtrace/contrib/kombu/__init__.py
  ddtrace/contrib/kombu/constants.py
  ddtrace/contrib/kombu/patch.py
  ddtrace/contrib/kombu/utils.py
  releasenotes/notes/move-integrations-to-internal-httplib-475d071a277b18cf.yaml
  tests/.suitespec.json
Labels: changelog/no-changelog

#10213 chore(flask): fix test_extract_redis_connection_metadata expected meta
  tests/.suitespec.json
  tests/contrib/flask_cache/test_utils.py
Labels: changelog/no-changelog

#10174 perf(iast): add `sqlalchemy.orm.interfaces` to iast denylist
  ddtrace/appsec/_iast/_ast/ast_patching.py
Labels: changelog/no-changelog, ASM

#10179 perf(iast): add ``sqlalchemy.sql.compiler:_requires_quotes`` to fine-grained ast exclusion list
  ddtrace/appsec/_iast/_ast/visitor.py
Labels: changelog/no-changelog, ASM

#10221 chore: update changelog for version 2.8.7
  CHANGELOG.md
Labels: changelog/no-changelog

#10198 chore(iast): add aspect for `re.sub`
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/app.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast/fixtures/non_re_module.py
  tests/appsec/integrations/test_flask_iast_patching.py
Labels: changelog/no-changelog, ASM

#10211 chore(ci): use sccache for base venv builds
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#10222 chore(ci): set 5m no output timeout for riot run steps
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#10225 fix(internal): revert rust rate limiter
  ddtrace/internal/core/__init__.py
  ddtrace/internal/core/_core.pyi
  ddtrace/internal/rate_limiter.py
  releasenotes/notes/fix-revert-rust-rate-limiter-e61ca589aa24105b.yaml
  src/core/lib.rs
  src/core/rate_limiter.rs
Labels: backport 2.10, backport 2.11

#10219 fix(profiling): use consistent environment variables for crashtracking
  ddtrace/settings/crashtracker.py
  releasenotes/notes/profiling-fix-crashtracking-envvars-f1914fe54b5283ea.yaml
  tests/internal/crashtracker/test_crashtracker.py
Labels: backport 2.11

#10199 chore(crashtracker): add required backend tags
  ddtrace/internal/datadog/profiling/dd_wrapper/include/constants.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/libdatadog_helpers.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp
  tests/internal/crashtracker/test_crashtracker.py
Labels: changelog/no-changelog, backport 2.11

#10170 chore(integrations): move mako,mariadb,molten,mongoengine,mysql,mysqldb to internal
  ddtrace/contrib/internal/mako/constants.py
  ddtrace/contrib/internal/mako/patch.py
  ddtrace/contrib/internal/mariadb/patch.py
  ddtrace/contrib/internal/molten/patch.py
  ddtrace/contrib/internal/molten/wrappers.py
  ddtrace/contrib/internal/mongoengine/patch.py
  ddtrace/contrib/internal/mongoengine/trace.py
  ddtrace/contrib/internal/mysql/patch.py
  ddtrace/contrib/internal/mysqldb/patch.py
  ddtrace/contrib/mako/__init__.py
  ddtrace/contrib/mako/constants.py
  ddtrace/contrib/mako/patch.py
  ddtrace/contrib/mariadb/__init__.py
  ddtrace/contrib/mariadb/patch.py
  ddtrace/contrib/molten/__init__.py
  ddtrace/contrib/molten/patch.py
  ddtrace/contrib/molten/wrappers.py
  ddtrace/contrib/mongoengine/__init__.py
  ddtrace/contrib/mongoengine/patch.py
  ddtrace/contrib/mongoengine/trace.py
  ddtrace/contrib/mysql/__init__.py
  ddtrace/contrib/mysql/patch.py
  ddtrace/contrib/mysqldb/__init__.py
  ddtrace/contrib/mysqldb/patch.py
  releasenotes/notes/move-integrations-to-internal-mako-e8684d5a46d60bb8.yaml
  tests/.suitespec.json
Labels: changelog/no-changelog

#10242 chore: update changelog for version 2.10.6
  CHANGELOG.md
Labels: changelog/no-changelog

#10240 chore(ci): add logging when pytest raised OSError on shutdown
  tests/conftest.py
Labels: changelog/no-changelog

#10126 chore(sampling): remove crash-by-design behaviors from sampling-related code
  ddtrace/internal/sampling.py
  ddtrace/sampler.py
  ddtrace/sampling_rule.py
  tests/telemetry/test_telemetry.py
  tests/tracer/test_sampler.py
  tests/tracer/test_single_span_sampling_rules.py
Labels: changelog/no-changelog

#10204 chore(integrations): move pynamodb,pyodbc,pyramid,redis,rediscluster,requests to internal
  ddtrace/contrib/internal/pynamodb/patch.py
  ddtrace/contrib/internal/pyodbc/patch.py
  ddtrace/contrib/internal/pyramid/constants.py
  ddtrace/contrib/internal/pyramid/patch.py
  ddtrace/contrib/internal/pyramid/trace.py
  ddtrace/contrib/internal/redis/asyncio_patch.py
  ddtrace/contrib/internal/redis/patch.py
  ddtrace/contrib/internal/rediscluster/patch.py
  ddtrace/contrib/internal/requests/connection.py
  ddtrace/contrib/internal/requests/constants.py
  ddtrace/contrib/internal/requests/patch.py
  ddtrace/contrib/internal/requests/session.py
  ddtrace/contrib/pynamodb/__init__.py
  ddtrace/contrib/pynamodb/patch.py
  ddtrace/contrib/pyodbc/__init__.py
  ddtrace/contrib/pyodbc/patch.py
  ddtrace/contrib/pyramid/__init__.py
  ddtrace/contrib/pyramid/constants.py
  ddtrace/contrib/pyramid/patch.py
  ddtrace/contrib/pyramid/trace.py
  ddtrace/contrib/redis/__init__.py
  ddtrace/contrib/redis/asyncio_patch.py
  ddtrace/contrib/redis/patch.py
  ddtrace/contrib/rediscluster/__init__.py
  ddtrace/contrib/rediscluster/patch.py
  ddtrace/contrib/requests/__init__.py
  ddtrace/contrib/requests/connection.py
  ddtrace/contrib/requests/constants.py
  ddtrace/contrib/requests/patch.py
  ddtrace/contrib/requests/session.py
  releasenotes/notes/move-integrations-to-internal-requests-951f55b729dd221c.yaml
  tests/.suitespec.json
  tests/contrib/pyramid/utils.py
  tests/contrib/requests/test_requests.py
Labels: changelog/no-changelog

#10088 chore(integrations): move cassandra,celery,cherrypy,consul,coverage to internal
  ddtrace/contrib/cassandra/__init__.py
  ddtrace/contrib/cassandra/patch.py
  ddtrace/contrib/cassandra/session.py
  ddtrace/contrib/celery/__init__.py
  ddtrace/contrib/celery/app.py
  ddtrace/contrib/celery/constants.py
  ddtrace/contrib/celery/patch.py
  ddtrace/contrib/celery/signals.py
  ddtrace/contrib/celery/utils.py
  ddtrace/contrib/cherrypy/__init__.py
  ddtrace/contrib/cherrypy/middleware.py
  ddtrace/contrib/consul/__init__.py
  ddtrace/contrib/consul/patch.py
  ddtrace/contrib/coverage/__init__.py
  ddtrace/contrib/coverage/constants.py
  ddtrace/contrib/coverage/patch.py
  ddtrace/contrib/internal/cassandra/patch.py
  ddtrace/contrib/internal/cassandra/session.py
  ddtrace/contrib/internal/celery/app.py
  ddtrace/contrib/internal/celery/constants.py
  ddtrace/contrib/internal/celery/patch.py
  ddtrace/contrib/internal/celery/signals.py
  ddtrace/contrib/internal/celery/utils.py
  ddtrace/contrib/internal/cherrypy/middleware.py
  ddtrace/contrib/internal/consul/patch.py
  ddtrace/contrib/internal/coverage/constants.py
  ddtrace/contrib/internal/coverage/patch.py
  ddtrace/contrib/internal/openai/_endpoint_hooks.py
  ddtrace/contrib/internal/openai/patch.py
  ddtrace/contrib/internal/openai/utils.py
  releasenotes/notes/move-integrations-to-internal-cassandra-c81f9627c3c7ed2c.yaml
  tests/.suitespec.json
Labels: changelog/no-changelog

#10244 feat(llmobs): do not tag IO dropping, instead add as top-level field
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_writer.py
  releasenotes/notes/truncate-oversized-llmobs-span-events-6e8a54015739ba82.yaml
  tests/llmobs/test_llmobs_span_truncation.py
Labels: changelog/no-changelog

#10186 chore(integrations): move openai,psycopg,pylibmc,pymemcache,pymongo,pymysql to internal
  ddtrace/contrib/internal/aiopg/patch.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/psycopg/async_connection.py
  ddtrace/contrib/internal/psycopg/async_cursor.py
  ddtrace/contrib/internal/psycopg/connection.py
  ddtrace/contrib/internal/psycopg/cursor.py
  ddtrace/contrib/internal/psycopg/extensions.py
  ddtrace/contrib/internal/psycopg/patch.py
  ddtrace/contrib/internal/pylibmc/addrs.py
  ddtrace/contrib/internal/pylibmc/client.py
  ddtrace/contrib/internal/pylibmc/patch.py
  ddtrace/contrib/internal/pymemcache/client.py
  ddtrace/contrib/internal/pymemcache/patch.py
  ddtrace/contrib/internal/pymongo/client.py
  ddtrace/contrib/internal/pymongo/parse.py
  ddtrace/contrib/internal/pymongo/patch.py
  ddtrace/contrib/internal/pymysql/patch.py
  ddtrace/contrib/openai/__init__.py
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/contrib/openai/patch.py
  ddtrace/contrib/openai/utils.py
  ddtrace/contrib/psycopg/__init__.py
  ddtrace/contrib/psycopg/async_connection.py
  ddtrace/contrib/psycopg/async_cursor.py
  ddtrace/contrib/psycopg/connection.py
  ddtrace/contrib/psycopg/cursor.py
  ddtrace/contrib/psycopg/extensions.py
  ddtrace/contrib/psycopg/patch.py
  ddtrace/contrib/pylibmc/__init__.py
  ddtrace/contrib/pylibmc/addrs.py
  ddtrace/contrib/pylibmc/client.py
  ddtrace/contrib/pylibmc/patch.py
  ddtrace/contrib/pymemcache/__init__.py
  ddtrace/contrib/pymemcache/client.py
  ddtrace/contrib/pymemcache/patch.py
  ddtrace/contrib/pymongo/__init__.py
  ddtrace/contrib/pymongo/client.py
  ddtrace/contrib/pymongo/parse.py
  ddtrace/contrib/pymongo/patch.py
  ddtrace/contrib/pymysql/__init__.py
  ddtrace/contrib/pymysql/patch.py
  releasenotes/notes/move-integrations-to-internal-openai-0d4ab4241552ff94.yaml
  tests/.suitespec.json
  tests/contrib/openai/test_openai_llmobs.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/contrib/pymongo/test.py
Labels: changelog/no-changelog

#10246 fix(profiling): fix endpoint profiling for stack v2
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  releasenotes/notes/profiling-fix-endpoint-v2-a6ca2ebbc9701fe5.yaml
Labels: Profiling

#10234 chore: remove some crash-by-design behaviors from internal/module.py
  ddtrace/internal/module.py
  tests/internal/test_module.py
Labels: changelog/no-changelog

#10196 chore(ci_visibility): revert sub-plugin strategy and move v2 functions to try-except blocks
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/plugin.py
Labels: changelog/no-changelog

#10266 chore(internal): revert "view snapshots"
  hatch.toml
  scripts/ci_visibility/view_snapshot.py
Labels: changelog/no-changelog

#10261 chore(ci_visibility): remove CISession API session ID
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_utils.py
  ddtrace/ext/ci_visibility/_ci_visibility_base.py
  ddtrace/ext/ci_visibility/_utils.py
  ddtrace/ext/ci_visibility/api.py
  ddtrace/ext/ci_visibility/util.py
  ddtrace/internal/ci_visibility/api/ci_base.py
  ddtrace/internal/ci_visibility/api/ci_module.py
  ddtrace/internal/ci_visibility/api/ci_session.py
  ddtrace/internal/ci_visibility/api/ci_suite.py
  ddtrace/internal/ci_visibility/api/ci_test.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/api/fake_runner_all_fail.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_suite_level.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_test_level.py
  tests/ci_visibility/api/fake_runner_all_pass.py
  tests/ci_visibility/api/fake_runner_all_skip.py
  tests/ci_visibility/api/fake_runner_mix_fail.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_suite_level.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_test_level.py
  tests/ci_visibility/api/fake_runner_mix_pass.py
  tests/ci_visibility/api/test_ext_ci_visibility_api.py
  tests/ci_visibility/api/test_internal_ci_visibility_api.py
  tests/ci_visibility/test_ci_visibility.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_skip.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_pass.json
Labels: changelog/no-changelog

#10209 chore(integrations): tornado,unittest,urllib,urllib3,vertica,webbrowser,wsgi,yaaredis to internal
  ddtrace/contrib/internal/tornado/application.py
  ddtrace/contrib/internal/tornado/constants.py
  ddtrace/contrib/internal/tornado/decorators.py
  ddtrace/contrib/internal/tornado/handlers.py
  ddtrace/contrib/internal/tornado/patch.py
  ddtrace/contrib/internal/tornado/stack_context.py
  ddtrace/contrib/internal/tornado/template.py
  ddtrace/contrib/internal/urllib/patch.py
  ddtrace/contrib/internal/urllib3/patch.py
  ddtrace/contrib/internal/vertica/patch.py
  ddtrace/contrib/internal/webbrowser/patch.py
  ddtrace/contrib/internal/wsgi/wsgi.py
  ddtrace/contrib/internal/yaaredis/patch.py
  ddtrace/contrib/tornado/__init__.py
  ddtrace/contrib/tornado/application.py
  ddtrace/contrib/tornado/constants.py
  ddtrace/contrib/tornado/decorators.py
  ddtrace/contrib/tornado/handlers.py
  ddtrace/contrib/tornado/patch.py
  ddtrace/contrib/tornado/stack_context.py
  ddtrace/contrib/tornado/template.py
  ddtrace/contrib/urllib/__init__.py
  ddtrace/contrib/urllib/patch.py
  ddtrace/contrib/urllib3/__init__.py
  ddtrace/contrib/urllib3/patch.py
  ddtrace/contrib/vertica/__init__.py
  ddtrace/contrib/vertica/patch.py
  ddtrace/contrib/webbrowser/__init__.py
  ddtrace/contrib/webbrowser/patch.py
  ddtrace/contrib/wsgi/__init__.py
  ddtrace/contrib/wsgi/wsgi.py
  ddtrace/contrib/yaaredis/__init__.py
  ddtrace/contrib/yaaredis/patch.py
  releasenotes/notes/move-integrations-to-internal-yaaredis-c553283b77c3b9e8.yaml
  tests/.suitespec.json
Labels: changelog/no-changelog

#10205 chore(integrations): move sanic,snowflake,sqlalchemy,sqlite3,starlette,structlog... to internal
  ddtrace/contrib/internal/fastapi/patch.py
  ddtrace/contrib/internal/sanic/patch.py
  ddtrace/contrib/internal/snowflake/patch.py
  ddtrace/contrib/internal/sqlalchemy/engine.py
  ddtrace/contrib/internal/sqlalchemy/patch.py
  ddtrace/contrib/internal/sqlite3/patch.py
  ddtrace/contrib/internal/starlette/patch.py
  ddtrace/contrib/internal/structlog/patch.py
  ddtrace/contrib/internal/subprocess/constants.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/contrib/sanic/__init__.py
  ddtrace/contrib/sanic/patch.py
  ddtrace/contrib/snowflake/__init__.py
  ddtrace/contrib/snowflake/patch.py
  ddtrace/contrib/sqlalchemy/__init__.py
  ddtrace/contrib/sqlalchemy/engine.py
  ddtrace/contrib/sqlalchemy/patch.py
  ddtrace/contrib/sqlite3/__init__.py
  ddtrace/contrib/sqlite3/patch.py
  ddtrace/contrib/starlette/__init__.py
  ddtrace/contrib/starlette/patch.py
  ddtrace/contrib/structlog/__init__.py
  ddtrace/contrib/structlog/patch.py
  ddtrace/contrib/subprocess/__init__.py
  ddtrace/contrib/subprocess/constants.py
  ddtrace/contrib/subprocess/patch.py
  releasenotes/notes/move-integrations-to-internal-sanic-f255102899fc7c99.yaml
  tests/.suitespec.json
Labels: changelog/no-changelog

#10274 chore(ci): refactor gitlab benchmarks stage
  .gitlab-ci.yml
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#10259 chore(ci): setup build_base_venv job in GitLab
  .gitlab-ci.yml
  .gitlab/package.yml
Labels: changelog/no-changelog

#10277 chore(ci): ensure 'fix' PRs include a release note
  scripts/check-releasenotes
Labels: changelog/no-changelog

#10265 fix(openai): propagate `asyncio.TimeoutError`s correctly when openai operation canceled
  ddtrace/contrib/internal/openai/patch.py
  releasenotes/notes/openai-async-timeout-errors-f9ccc1adbe4ed14e.yaml
  tests/contrib/openai/test_openai_v1.py
Labels: backport 2.10, backport 2.11, backport 2.12

#10272 chore: add .worktrees directory to .gitignore
  .gitignore
Labels: changelog/no-changelog

#10218 chore(iast): re.subn and re.split aspects
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/app.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast/fixtures/non_re_module.py
  tests/appsec/integrations/test_flask_iast_patching.py
Labels: changelog/no-changelog, ASM

#10283 chore(ci): migrate appsec_threats_* jobs to gitlab
  .circleci/config.templ.yml
  .github/CODEOWNERS
  .gitlab-ci.yml
  .gitlab/ci-split-input.sh
  .gitlab/package.yml
  .gitlab/tests.yml
  .gitlab/tests/appsec.yml
Labels: changelog/no-changelog

#10268 chore(ci_visibility): install coverage collector during pytest plugin v2 startup
  ddtrace/contrib/pytest/_plugin_v1.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_utils.py
  ddtrace/contrib/pytest/plugin.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/contrib/pytest/test_coverage_per_suite.py
Labels: changelog/no-changelog

#10289 fix(internal): handle native module specs
  ddtrace/internal/module.py
  releasenotes/notes/fix-module-callback-type-error-ba5583fa8e2cf0fc.yaml
Labels: backport 2.11, backport 2.12

#10293 ci: enable onboarding_tests_installer tests
  .gitlab-ci.yml
Labels: changelog/no-changelog, backport 2.11, backport 2.12

#10294 fix: fix ddtrace file attributes being stripped when repairing linux wheels
  releasenotes/notes/fix-wheel-file-permissions-59b497ed8163e885.yaml
  scripts/zip_filter.py
Labels: backport 2.11, backport 2.12

#10094 chore: remove crash-by-design behaviors
  ddtrace/_trace/_span_link.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/span.py
  ddtrace/contrib/internal/aws_lambda/patch.py
  ddtrace/contrib/internal/pymongo/parse.py
  ddtrace/contrib/pymongo/parse.py
  ddtrace/internal/codeowners.py
  ddtrace/internal/remoteconfig/_publishers.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/safety.py
  ddtrace/internal/service.py
  ddtrace/internal/sma.py
  ddtrace/internal/tracemethods.py
  ddtrace/internal/utils/__init__.py
  ddtrace/internal/utils/http.py
  ddtrace/internal/utils/time.py
  ddtrace/internal/uwsgi.py
  ddtrace/internal/writer/writer.py
  ddtrace/opentracer/tracer.py
  ddtrace/settings/config.py
  tests/integration/test_tracemethods.py
  tests/tracer/test_settings.py
  tests/tracer/test_sma.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog, backport 2.12

#10217 chore: avoid using deprecated attributes in integrations
  ddtrace/contrib/internal/aiopg/patch.py
  ddtrace/contrib/internal/anthropic/_streaming.py
  ddtrace/contrib/internal/asyncio/compat.py
  ddtrace/contrib/internal/asyncio/helpers.py
  ddtrace/contrib/internal/asyncio/provider.py
  ddtrace/contrib/internal/boto/patch.py
  ddtrace/contrib/internal/django/_asgi.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/django/utils.py
  ddtrace/contrib/internal/fastapi/patch.py
  ddtrace/contrib/internal/flask/patch.py
  ddtrace/contrib/internal/flask_cache/utils.py
  ddtrace/contrib/internal/mongoengine/trace.py
Labels: changelog/no-changelog

#10275 chore(rc): register restart on fork
  ddtrace/internal/remoteconfig/worker.py
Labels: changelog/no-changelog

#10280 chore: update changelog for version 2.11.0
  CHANGELOG.md
Labels: changelog/no-changelog

#10290 chore(iast): `re.findall` aspect
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/app.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast/fixtures/non_re_module.py
  tests/appsec/integrations/test_flask_iast_patching.py
Labels: changelog/no-changelog, ASM

#10301 ci: download all GitHub Actions artifacts
  .gitlab-ci.yml
  .gitlab/download-wheels-from-gh-actions.sh
  .gitlab/package.yml
Labels: changelog/no-changelog, backport 2.11, backport 2.12

#10309 chore: update changelog for version 2.11.1
  CHANGELOG.md
Labels: changelog/no-changelog

#10216 chore: add native utility functions to help migrate more aspects to native and migrate add aspect
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/_taint_tracking/clean.sh
Labels: changelog/no-changelog, ASM

#10220 chore(debugger): guard inline wrapping operations
  ddtrace/debugging/_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#10215 chore(debugger): ensure default limits are used when not set
  ddtrace/debugging/_probe/remoteconfig.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#10194 chore(debugger): align snapshot field encoding
  ddtrace/debugging/_encoding.py
  tests/debugging/test_debugger.py
  tests/debugging/test_encoding.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#10306 fix(tracer): small fix for db instrumentation
  ddtrace/contrib/internal/django/patch.py
  releasenotes/notes/fix_django_db_connection_instrumentation-c23defb666caff3c.yaml
Labels: bug, backport 2.10, backport 2.11, backport 2.12

#9877 chore(symdb): match includes regex only if variable set
  ddtrace/internal/symbol_db/symbols.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#10214 chore(debugger): include locals/globals in evals
  ddtrace/debugging/_signal/metric_sample.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_signal/snapshot.py
  ddtrace/debugging/_signal/tracing.py
  tests/debugging/signal/test_model.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#10312 chore: update iast codeowner
  .github/CODEOWNERS
Labels: changelog/no-changelog, ASM

#10258 chore(iast): move index_aspect to native only
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.h
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
Labels: changelog/no-changelog, ASM

#10316 fix: prevent module import callback side-effects
  ddtrace/internal/module.py
  releasenotes/notes/fix-module-callback-no-side-effects-df422ae52b87772d.yaml
  tests/internal/side_effect_module.py
  tests/internal/test_module.py
Labels: backport 2.11, backport 2.12

#10311 chore(iast): inplace add aspect
  benchmarks/bm/iast_fixtures/str_methods.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectOperatorAdd.h
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_add_inplace_aspect.py
  tests/appsec/iast/aspects/test_add_inplace_aspect_fixtures.py
  tests/appsec/iast/aspects/test_other_patching.py
  tests/appsec/iast/fixtures/ast/add_operator/inplace.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#10326 fix(profiling): propagate tags when using libdatadog exporter
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/profiler.py
  ddtrace/settings/profiling.py
  releasenotes/notes/profiling-fix-tags-libdd-5aba4fd5ceb63539.yaml
  tests/profiling/exporter/test_ddup.py
  tests/profiling/exporter/test_http.py
Labels: Profiling

#10302 chore(iast): `re.match` and `re.Match.groups` aspects
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/app.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast/fixtures/non_re_module.py
  tests/appsec/integrations/test_flask_iast_patching.py
Labels: changelog/no-changelog, ASM
