Repository DataDog/dd-trace-py, pull requests merged in 2024-02, with the labels that each got.

#8230 chore(rc): do not attempt to read empty payloads
  ddtrace/internal/remoteconfig/client.py
Labels: changelog/no-changelog

#8205 chore(profiling): better configuration tracking
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/profiler.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#8255 docs: fix hyperlink typo for `advanced_usage.rst`
  docs/advanced_usage.rst
Labels: changelog/no-changelog

#8253 fix(asm): fastapi, fix redirect actions
  ddtrace/contrib/asgi/middleware.py
  releasenotes/notes/fastapi_fix_redirect_actions-862691cea6074678.yaml
  tests/appsec/contrib_appsec/test_fastapi.py
  tests/appsec/contrib_appsec/utils.py
Labels: bug, ASM

#8201 chore(iast): aspect replace
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_replace_aspect.py
Labels: changelog/no-changelog, ASM

#8019 chore(internal): module type annotation
  ddtrace/internal/module.py
Labels: changelog/no-changelog

#8256 chore(asm): add ip validation in asgi
  ddtrace/contrib/asgi/middleware.py
  ddtrace/internal/compat.py
Labels: changelog/no-changelog, ASM

#8265 fix: only use first message context for trace propagation in aws messaging
  ddtrace/contrib/botocore/utils.py
Labels: changelog/no-changelog

#8264 fix(iast): bug where `str` aspect doesn't honor args and kwargs
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/iast-fix-str-aspect-4c8ccb47fcc8b6cc.yaml
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: ASM, backport 2.3, backport 2.4, backport 2.5

#8273 ci(redis): unpatch after patching to avoid corrupting later test results
  tests/contrib/redis/test_redis_asyncio.py
  tests/contrib/redis/test_redis_cluster_asyncio.py
Labels: changelog/no-changelog

#8029 feat(asm): lazy load appsec.iast._ast.ast_patching
  tests/internal/test_serverless.py
Labels: changelog/no-changelog, ASM

#8267 fix(asm): manage client_ip_header correctly for lowercase headers
  ddtrace/contrib/trace_utils.py
  releasenotes/notes/fix_client_ip_header_with_case_insensitive_headers-6b70d45d0a541c23.yaml
Labels: bug, ASM

#8234 chore(trace): add internal trace sub-package
  ddtrace/_trace/__init__.py
  ddtrace/_trace/_limits.py
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/contrib/elasticsearch/patch.py
Labels: changelog/no-changelog

#8289 ci(serverless): clean up sys.modules after test that modifies it to avoid polluting other tests
  tests/internal/test_serverless.py
Labels: changelog/no-changelog

#8266 docs: document workaround for duplicate log entries [APMS-11072]
  docs/advanced_usage.rst
  docs/spelling_wordlist.txt
Labels: changelog/no-changelog

#8288 fix(asm): remove early block in fastapi
  ddtrace/contrib/asgi/middleware.py
  releasenotes/notes/fastapi_block_too_early-f46b1dfa2d3565b5.yaml
Labels: bug, ASM, backport 2.5

#8278 chore(kombu): fix distributed tracing regression
  ddtrace/contrib/kombu/patch.py
  tests/contrib/kombu/test.py
Labels: changelog/no-changelog

#8197 chore(serverless): benchmark on AWS Lambda
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#8295 ci(django): regenerate django appsec snapshots
  tests/.suitespec.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
Labels: changelog/no-changelog

#8257 chore(asm): improve hatch threat tests part 2
  ddtrace/appsec/_asm_request_context.py
  tests/appsec/appsec/rules-good.json
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/test_django.py
  tests/appsec/contrib_appsec/test_fastapi.py
  tests/appsec/contrib_appsec/test_flask.py
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_appsec_api_security.py
  tests/contrib/fastapi/test_fastapi_appsec.py
  tests/contrib/fastapi/test_fastapi_appsec_api_security.py
  tests/contrib/flask/test_appsec_api_security.py
  tests/contrib/flask/test_flask_appsec.py
Labels: changelog/no-changelog, ASM, CI

#8287 fix(iast): improve `repr` aspect
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_str_aspect.py
Labels: changelog/no-changelog, ASM

#8298 ci(elasticsearch): set parallelism to a divisor of the number of riot envs (102)
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#8302 ci: increase parallelism for a few longrunning suites
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#8250 chore(trace): move trace processor module
  ddtrace/_trace/processor/__init__.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_processor.py
  ddtrace/debugging/_exception/auto_instrument.py
  ddtrace/filters.py
  ddtrace/internal/peer_service/processor.py
  ddtrace/internal/processor/__init__.py
  ddtrace/internal/processor/endpoint_call_counter.py
  ddtrace/internal/processor/stats.py
  ddtrace/internal/schema/processor.py
  ddtrace/tracer.py
  tests/integration/test_integration.py
  tests/internal/peer_service/test_processor.py
  tests/internal/service_name/test_processor.py
  tests/telemetry/test_telemetry.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog

#8307 fix(botocore): bug with empty_poll_enabled config check for botocore sqs and kinesis
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/sqs.py
Labels: changelog/no-changelog

#8313 ci(release): set tag name correctly for release candidates
  scripts/release.py
Labels: changelog/no-changelog

#8299 ci(aiobotocore): remove unreliable error output assertion
  tests/contrib/aiobotocore/test.py
Labels: changelog/no-changelog

#6920 chore(internal): symbol inference
  .github/CODEOWNERS
  ddtrace/bootstrap/preload.py
  ddtrace/internal/compat.py
  ddtrace/internal/forksafe.py
  ddtrace/internal/packages.py
  ddtrace/internal/symbol_db/__init__.py
  ddtrace/internal/symbol_db/remoteconfig.py
  ddtrace/internal/symbol_db/symbols.py
  ddtrace/internal/utils/inspection.py
  ddtrace/settings/symbol_db.py
  tests/debugging/exploration/debugger.py
  tests/internal/symbol_db/__init__.py
  tests/internal/symbol_db/test_config.py
  tests/internal/symbol_db/test_symbols.py
  tests/internal/test_packages.py
Labels: changelog/no-changelog

#8315 chore(asm): update libddwaf to 1.16.0
  setup.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#8251 chore(trace): move context and provider modules
  benchmarks/http_propagation_inject/scenario.py
  ddtrace/_trace/context.py
  ddtrace/_trace/provider.py
  ddtrace/context.py
  ddtrace/contrib/asyncio/__init__.py
  ddtrace/contrib/asyncio/provider.py
  ddtrace/contrib/gevent/patch.py
  ddtrace/contrib/gevent/provider.py
  ddtrace/contrib/tornado/stack_context.py
  ddtrace/debugging/_signal/model.py
  ddtrace/internal/ci_visibility/context.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/sampling.py
  ddtrace/opentelemetry/_context.py
  ddtrace/opentracer/span.py
  ddtrace/opentracer/span_context.py
  ddtrace/opentracer/tracer.py
  ddtrace/opentracer/utils.py
  ddtrace/propagation/http.py
  ddtrace/provider.py
  ddtrace/span.py
  ddtrace/tracer.py
  tests/contrib/aiohttp/test_request_safety.py
  tests/contrib/asyncio/test_helpers.py
  tests/contrib/asyncio/test_propagation.py
  tests/contrib/asyncio/test_tracer_safety.py
  tests/contrib/celery/test_integration.py
  tests/contrib/gevent/test_tracer.py
  tests/contrib/tornado/test_stack_context.py
  tests/opentracer/core/test_utils.py
  tests/tracer/test_context.py
  tests/tracer/test_correlation_log_context.py
  tests/tracer/test_encoders.py
  tests/tracer/test_processors.py
  tests/tracer/test_propagation.py
  tests/tracer/test_sampler.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
  tests/tracer/test_utils.py
  tests/webclient.py
Labels: changelog/no-changelog

#8213 chore: use the SQLi redaction suite and improve the parsing
  .riot/requirements/1580f89.txt
  ddtrace/appsec/_iast/_utils.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/sql_injection.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/settings/asm.py
  hatch.toml
  pyproject.toml
  riotfile.py
  setup.py
  tests/appsec/iast/taint_sinks/redaction_fixtures/evidence-redaction-suite.json
  tests/appsec/iast/taint_sinks/test_sql_injection.py
  tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_taint_sinks_utils.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#8323 refactor(profiling): variable name if arguments available
  ddtrace/profiling/collector/_traceback.pyx
Labels: changelog/no-changelog, Profiling

#8327 ci: xfail instead of fail when testagent becomes unreachable
  tests/conftest.py
Labels: changelog/no-changelog

#8314 chore: add a dry run mode for the release script to facilitate testing
  scripts/release.py
Labels: changelog/no-changelog

#8332 ci(telemetry): loosen an assertion that can sometimes fail
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#8326 ci: turn off coverage for a few suites where it recently failed
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#8321 ci: xfail "unmatched traces" error in snapshot tests
  tests/.suitespec.json
  tests/suitespec.py
  tests/utils.py
Labels: changelog/no-changelog, backport 2.4, backport 2.5, backport 2.6

#8334 ci(tracing): loosen an assertion that can sometimes fail
  tests/tracer/test_logger.py
Labels: changelog/no-changelog

#8330 ci(aws_lambda): make envier dependency explicit in aws_lambda environment
  .riot/requirements/1057ff6.txt
  .riot/requirements/10af9e2.txt
  .riot/requirements/3ff4221.txt
  .riot/requirements/41ddab5.txt
  .riot/requirements/67afac8.txt
  .riot/requirements/cc1a9bf.txt
  riotfile.py
Labels: changelog/no-changelog

#8328 fix(civisibility): catch runtime error that can sometimes happen between tests with coverage enabled
  ddtrace/internal/ci_visibility/coverage.py
  docs/spelling_wordlist.txt
  releasenotes/notes/cov-crash-e1ab3aff6f8aa3e0.yaml
Labels: backport 2.4, backport 2.5, backport 2.6

#8325 chore(symdb): skip bad modules only
  ddtrace/internal/symbol_db/symbols.py
Labels: changelog/no-changelog

#8324 chore(asm): use sampling_priority for api security
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_processor.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
Labels: enhancement, changelog/no-changelog, ASM

#8354 ci(grpc_aio): expect observed test result
  tests/contrib/grpc_aio/test_grpc_aio.py
Labels: changelog/no-changelog

#8353 ci: fix some ephemeral failures
  tests/conftest.py
Labels: changelog/no-changelog

#8320 feat(llmobs): create LLMObs service
  .circleci/config.templ.yml
  .github/CODEOWNERS
  .riot/requirements/105602c.txt
  .riot/requirements/112818b.txt
  .riot/requirements/1130e9d.txt
  .riot/requirements/1388f2d.txt
  .riot/requirements/151fa3d.txt
  .riot/requirements/153fdb0.txt
  .riot/requirements/1902e9f.txt
  .riot/requirements/1ace2ad.txt
  .riot/requirements/4cba75c.txt
  .riot/requirements/6fdb03a.txt
  .riot/requirements/99214a1.txt
  .riot/requirements/b1a336f.txt
  ddtrace/bootstrap/preload.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/bedrock.py
  ddtrace/contrib/langchain/patch.py
  ddtrace/contrib/openai/patch.py
  ddtrace/internal/llmobs/__init__.py
  ddtrace/llmobs/__init__.py
  ddtrace/llmobs/_integrations/__init__.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/openai.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_log_writer.py
  ddtrace/llmobs/_writer.py
  riotfile.py
  tests/.suitespec.json
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/openai/conftest.py
  tests/llmobs/__init__.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_writer.test_send_chat_completion.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_writer.test_send_completion.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_writer.test_send_completion_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_writer.test_send_completion_bad_app_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_writer.test_send_on_exit.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_writer.test_send_timed_records.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_logger.test_send_log.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_logger.test_send_log_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_logger.test_send_on_exit.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_logger.test_send_timed.yaml
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_writer.py
  tests/llmobs/test_logger.py
Labels: changelog/no-changelog, MLObs

#8347 ci: don't run PR name check GitHub action on backport branches
  .github/workflows/pr-name.yml
Labels: changelog/no-changelog

#8349 ci: fix missing paths in suitespec for CI Visibility-related jobs
  tests/.suitespec.json
Labels: changelog/no-changelog, backport 1.20, backport 2.4, backport 2.5, backport 2.6

#8365 fix: dont patch BytesIO since we dont have any aspects for it
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/do-not-patch-bytesio-b16ccc16f36e8b67.yaml
Labels: backport 2.5, backport 2.6

#8338 chore(serverless): report status of benchmark
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#8376 fix(iast): add support for patching code with type annotations
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_utils.py
  releasenotes/notes/iast-fix-type-hint-patching-f13fbde78d71bd53.yaml
  tests/appsec/iast/_ast/fixtures/annotated_code.py
  tests/appsec/iast/_ast/fixtures/annotated_code37.py
  tests/appsec/iast/_ast/test_ast_patching_type_hints.py
  tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
Labels: ASM, backport 2.4, backport 2.5, backport 2.6

#8389 chore(asm): activate tests for lowercase transformer
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#8358 ci: do not fail the step when subprocess snapshot test results in xfail
  tests/subprocesstest.py
Labels: changelog/no-changelog

#8395 Revert "ci(django): regenerate django appsec snapshots [backport 2.4]"
  tests/.suitespec.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
Labels: changelog/no-changelog, ASM

#8385 fix(tracing): return trace regardless of sampling decision unless stats comp enabled
  ddtrace/_trace/processor/__init__.py
  releasenotes/notes/always_send_trace_to_agent-f5dad70a40aa92a9.yaml
  tests/tracer/test_sampler.py
  tests/tracer/test_tracer.py
Labels: backport 2.5, backport 2.6

#8391 fix(botocore): fix bug causing no response to be returned from SQS and Kinesis when config.botocore.empty_poll_enabled is false
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/sqs.py
  releasenotes/notes/fix-botocore-bug-when-empty-poll-disabled-config-set-033d13dee074ec23.yaml
  tests/contrib/botocore/test.py
Labels: backport 2.6

#8400 ci: add missing sampling snapshot test
  tests/snapshots/test_sampling_with_rate_sampler_with_tiny_rate.json
Labels: changelog/no-changelog

#8203 chore(profiling): convert libdatadog build apparatus to cmake
  ddtrace/internal/datadog/profiling/CMakeLists.txt
  ddtrace/internal/datadog/profiling/_ddup.pyx
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/fetch_libdatadog.sh
  ddtrace/internal/datadog/profiling/cmake/tools/libdatadog_checksums.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/exporter.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/exporter.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/interface.cpp
  ddtrace/internal/datadog/profiling/ddup.py
  pyproject.toml
  setup.py
Labels: changelog/no-changelog, Profiling

#8404 fix: Revert #8387
  ddtrace/sampling_rule.py
  releasenotes/notes/service_name_and_resource_glob_matching-6cb980871e78b27c.yaml
  tests/integration/test_debug.py
  tests/integration/test_sampling.py
  tests/snapshots/test_extended_sampling_tags_and_name_glob.json
  tests/snapshots/test_extended_sampling_tags_and_resource_glob.json
  tests/snapshots/test_extended_sampling_tags_and_service_glob.json
Labels: changelog/no-changelog

#8374 ci: don't run PR name linter on pull requests targeting release branches
  .github/workflows/pr-name.yml
Labels: changelog/no-changelog

#8379 ci: fix missing paths in suitespec for CI Visibility-related jobs [backport 2.4]
  tests/.suitespec.json
Labels: changelog/no-changelog

#8377 ci: fix missing paths in suitespec for CI Visibility-related jobs [backport 2.6]
  tests/.suitespec.json
Labels: changelog/no-changelog, CI

#8375 fix(tracing): resolves telemetry import error raised when queuing span metrics
  ddtrace/_trace/processor/__init__.py
  ddtrace/appsec/_metrics.py
  ddtrace/internal/writer/writer.py
  ddtrace/tracer.py
  releasenotes/notes/fix-telemetry-import-error-336544027399603d.yaml
  tests/telemetry/test_telemetry.py
  tests/tracer/test_processors.py
Labels: backport 2.6

#8408 ci: get latest commit message to look for itr:noskip
  scripts/needs_testrun.py
Labels: changelog/no-changelog, CI, backport 2.4, backport 2.5, backport 2.6

#8378 ci: fix missing paths in suitespec for CI Visibility-related jobs [backport 2.5]
  tests/.suitespec.json
Labels: changelog/no-changelog

#8372 ci(telemetry): fix some flaky tests
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog

#8333 ci: do not run benchmarks-pr-comment on main
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#8403 chore(sampling): remove exec info from log
  ddtrace/internal/sampling.py
Labels: changelog/no-changelog

#8386 feat(tracing): send entity_id regardless of container_id availability [AIT-9282]
  ddtrace/internal/processor/stats.py
  ddtrace/internal/runtime/container.py
  ddtrace/internal/telemetry/writer.py
  tests/tracer/runtime/test_container.py
Labels: changelog/no-changelog

#8425 fix(asm): update required address when new rules are updated [backport 1.20]
  ddtrace/appsec/processor.py
  releasenotes/notes/fix_required_waf_addresses-6c51ddbcaca95129.yaml
  tests/appsec/test_processor.py
Labels: bug, ASM

#8426 ci: mark flaky telemetry test
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog

#8428 ci: add missing sampling snapshot test [backport 2.5]
  tests/snapshots/test_sampling_with_rate_sampler_with_tiny_rate.json
Labels: changelog/no-changelog

#8381 docs: document runtime metrics
  docs/configuration.rst
Labels: changelog/no-changelog

#8348 chore(suitespec): check for unmatched patterns
  scripts/check_suitespec_coverage.py
Labels: changelog/no-changelog

#8434 fix(ci_visibility): catch socket.timeouterrors in API requests generated by python<3.10
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci_visibility-fix-socket-timeout-exception-fabf40a398249c26.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: backport 2.4, backport 2.5, backport 2.6

#8439 ci: fix if rule for benchmark pr comments gitlab job
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog, CI

#8276 chore(trace): move tracer module
  benchmarks/threading/scenario.py
  ddtrace/__init__.py
  ddtrace/_trace/tracer.py
  ddtrace/debugging/_debugger.py
  ddtrace/internal/debug.py
  ddtrace/opentracer/span.py
  ddtrace/tracer.py
  pyproject.toml
  tests/commands/ddtrace_run_debug.py
  tests/commands/ddtrace_run_no_debug.py
  tests/contrib/flask_cache/test_utils.py
  tests/contrib/tornado/test_config.py
  tests/integration/test_integration_civisibility.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#8448 chore: fix release note spelling
  releasenotes/notes/ci_visibility-fix-socket-timeout-exception-fabf40a398249c26.yaml
Labels: changelog/no-changelog

#8431 feat(llmobs): set parent ID as the nearest LLMObs span in ancestor tree
  ddtrace/llmobs/_llmobs.py
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_trace_processor.py
  tests/llmobs/test_llmobs_writer.py
  tests/llmobs/test_logger.py
  tests/llmobs/utils.py
Labels: changelog/no-changelog, MLObs

#8416 chore(profiling): improve safety of ddup with respect to state-tearing after fork()
  ddtrace/internal/datadog/profiling/CMakeLists.txt
  ddtrace/internal/datadog/profiling/_ddup.pyi
  ddtrace/internal/datadog/profiling/_ddup.pyx
  ddtrace/internal/datadog/profiling/cmake/FindCppcheck.cmake
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/cmake/tools/fetch_libdatadog.sh
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/dd_wrapper.md
  ddtrace/internal/datadog/profiling/dd_wrapper/include/constants.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/exporter.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/libdatadog_helpers.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/profile.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample_manager.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/types.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader_builder.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/runner.sh
  ddtrace/internal/datadog/profiling/dd_wrapper/setup_custom.sh
  ddtrace/internal/datadog/profiling/dd_wrapper/src/exporter.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample_manager.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader_builder.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/test/api.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/forking.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/initialization.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/test_utils.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/test/threading.cpp
  ddtrace/internal/datadog/profiling/ddup.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  mypy.ini
Labels: changelog/no-changelog, Profiling

#8443 fix(ci_visibility): catch socket.timeouterrors [...] generated by python<3.10 [backport 2.4]
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci_visibility-fix-socket-timeout-exception-fabf40a398249c26.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: CI App

#8444 fix(ci_visibility): catch socket.timeouterrors [...] generated by python<3.10 [backport 2.5]
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci_visibility-fix-socket-timeout-exception-fabf40a398249c26.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: CI App

#8223 fix(profiling): handle exceptions in class name extraction
  ddtrace/profiling/collector/_traceback.pyx
  releasenotes/notes/fix-profiling-class-name-exceptions-6538651a21ca00d6.yaml
Labels: Profiling, backport 2.4, backport 2.5, backport 2.6

#8441 chore(tracer): add meta_struct support using msgpack for asm
  ddtrace/_trace/span.py
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/writer/writer.py
  ddtrace/settings/asm.py
  docs/spelling_wordlist.txt
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog, ASM

#8454 chore(rc): add skip shutdown option
  ddtrace/internal/packages.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
Labels: changelog/no-changelog

#8464 ci: add _trace to tracing suitespec
  tests/.suitespec.json
  tests/suitespec.py
Labels: changelog/no-changelog

#8462 fix(asm): remove unneeded call to set waf metrics
  ddtrace/appsec/_processor.py
Labels: changelog/no-changelog, ASM

#8413 chore(tracing): consolidate tracing/ and _trace/ subdirectories
  ddtrace/_trace/_span_link.py
  ddtrace/_trace/context.py
  ddtrace/_trace/span.py
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/__init__.py
  ddtrace/propagation/http.py
  ddtrace/tracing/__init__.py
  tests/.suitespec.json
  tests/suitespec.py
  tests/tracer/test_context.py
  tests/tracer/test_encoders.py
  tests/tracer/test_propagation.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#8469 fix(internal): ignore non-standard modules [backport #7732 to 1.20]
  ddtrace/internal/module.py
  releasenotes/notes/fix-ignore-non-standard-modules-318862ee5c68be0f.yaml
  tests/internal/test_module.py
Labels: Dynamic Instrumentation, backport 1.20, backport 2.3

#8468 ci(di): remove automatic deploy to di backend
  .gitlab-ci.yml
Labels: changelog/no-changelog, Dynamic Instrumentation

#8473 chore(di): remove formatting dead code
  ddtrace/debugging/_signal/snapshot.py
  tests/debugging/test_encoding.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8421 chore(di): set dynamic span origin
  ddtrace/debugging/_signal/tracing.py
  tests/debugging/test_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8460 ci: remove ddagent5 from tests
  docker-compose.yml
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#8470 fix: fix decode empty ranges
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/asm-fix-empty-ranges-decode-38aa73230a0e2a19.yaml
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
Labels: backport 2.4, backport 2.5, backport 2.6

#8455 chore: fixes for 1.20 build
  .github/workflows/build_python_3.yml
  .gitlab/benchmarks.yml
  setup.py
Labels: changelog/no-changelog

#8352 ci(suitespec): finer-grained internal component
  ddtrace/internal/buff_converter.h
  tests/.suitespec.json
  tests/suitespec.py
Labels: changelog/no-changelog, CI

#8486 chore: dont hide IAST logs
  ddtrace/appsec/_iast/_metrics.py
Labels: changelog/no-changelog, ASM

#8350 ci(iast): remove unmatched pattern from suitespec
  tests/.suitespec.json
Labels: changelog/no-changelog, ASM, CI, backport 1.20, backport 2.4, backport 2.5, backport 2.6

#8452 fix(iast): improve overhead control logic
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  releasenotes/notes/iast-fix-oce-logic-4369ebeed72759fc.yaml
  tests/appsec/iast/conftest.py
  tests/appsec/iast/test_overhead_control_engine.py
Labels: bug, ASM, backport 2.4, backport 2.5, backport 2.6

#8491 chore: ignore embedded doc sources in suitespec check
  scripts/check_suitespec_coverage.py
Labels: changelog/no-changelog

#8495 fix(iast): improve overhead control logic (#8452)
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  releasenotes/notes/iast-fix-oce-logic-4369ebeed72759fc.yaml
  tests/appsec/iast/conftest.py
  tests/appsec/iast/test_overhead_control_engine.py
Labels: ASM

#8453 ci: restore uploading of results from main branch to BP UI
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#8487 chore: remove unused test_module2
  tests/.suitespec.json
  tests/test_module2/__init__.py
Labels: changelog/no-changelog

#8494 fix(iast): improve overhead control logic (#8452)
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  releasenotes/notes/iast-fix-oce-logic-4369ebeed72759fc.yaml
  tests/appsec/iast/conftest.py
  tests/appsec/iast/test_overhead_control_engine.py
Labels: ASM

#8465 chore(propagation): default sampling priority when datadog headers don't provide it
  ddtrace/propagation/http.py
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_distributed_tracing_nested.json
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#8498 ci: update suitespec coverage
  scripts/check_suitespec_coverage.py
  tests/.suitespec.json
  tests/suitespec.py
Labels: changelog/no-changelog

#8492 chore: add code owners to suitespec check
  scripts/check_suitespec_coverage.py
Labels: changelog/no-changelog

#8502 ci: add suitespec coverage check
  hatch.toml
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#8505 chore(internal): do not let package file mapping warning be an error
  ddtrace/internal/packages.py
Labels: changelog/no-changelog

#8447 docs: clear up wording of support levels
  docs/versioning.rst
Labels: changelog/no-changelog

#8507 docs: update changelog with all x.x.0 releases
  CHANGELOG.md
Labels: changelog/no-changelog

#8499 chore(tracing): improve trace/RUM correlation when w3c tracestate headers are in use
  ddtrace/propagation/http.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#8297 chore(w3c): add last parent id to tracestate
  ddtrace/propagation/http.py
  tests/contrib/urllib3/test_urllib3.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#8497 ci(flask): upgrade tests to support v3 of flask
  .riot/requirements/10b89f6.txt
  .riot/requirements/1282516.txt
  .riot/requirements/12893ac.txt
  .riot/requirements/128ac84.txt
  .riot/requirements/131ac8b.txt
  .riot/requirements/1373dbd.txt
  .riot/requirements/139048e.txt
  .riot/requirements/13e6e97.txt
  .riot/requirements/140ec91.txt
  .riot/requirements/140fecc.txt
  .riot/requirements/1436100.txt
  .riot/requirements/14685d1.txt
  .riot/requirements/15beeb8.txt
  .riot/requirements/18b992e.txt
  .riot/requirements/191bffe.txt
  .riot/requirements/1949639.txt
  .riot/requirements/1aef832.txt
  .riot/requirements/1b22123.txt
  .riot/requirements/1b6cdc1.txt
  .riot/requirements/1b6da7f.txt
  .riot/requirements/1bbc5e0.txt
  .riot/requirements/1bccebd.txt
  .riot/requirements/1c4d7e9.txt
  .riot/requirements/1c6a57b.txt
  .riot/requirements/1d10c25.txt
  .riot/requirements/1ecbb51.txt
  .riot/requirements/1f0ee7f.txt
  .riot/requirements/1f66fe3.txt
  .riot/requirements/1f6b2bd.txt
  .riot/requirements/30b65e2.txt
  .riot/requirements/629f3d6.txt
  .riot/requirements/65cdef7.txt
  .riot/requirements/66fcd0b.txt
  .riot/requirements/724adbd.txt
  .riot/requirements/75dda93.txt
  .riot/requirements/8145a13.txt
  .riot/requirements/8654a9e.txt
  .riot/requirements/8830759.txt
  .riot/requirements/91629cd.txt
  .riot/requirements/b39e5f7.txt
  .riot/requirements/b669824.txt
  .riot/requirements/b9c205c.txt
  .riot/requirements/ba767f0.txt
  .riot/requirements/bc1efaa.txt
  .riot/requirements/c46d031.txt
  .riot/requirements/d165a69.txt
  .riot/requirements/e5e2721.txt
  .riot/requirements/ece9fb0.txt
  .riot/requirements/ef257ac.txt
  .riot/requirements/f111af5.txt
  .riot/requirements/f66dc0b.txt
  .riot/requirements/f7b33fd.txt
  riotfile.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog

#8445 ci(telemetry): fix a telemetry test agent event count assertion
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog

#8512 ci: ignore ``meta._dd.parent_id`` at snapshot tests
  docker-compose.yml
Labels: changelog/no-changelog, CI

#8451 ci: use sha256 method for specifying testrunner in docker-compose.yml
  docker-compose.yml
Labels: changelog/no-changelog, CI, backport 2.1, backport 2.2, backport 2.3, backport 2.4, backport 2.5, backport 2.6

#8477 chore(trace): handle import of ddtrace.tracer
  ddtrace/__init__.py
  ddtrace/tracer.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#8500 ci(botocore): upgrade tests to support latest versions of botocore
  .riot/requirements/1070785.txt
  .riot/requirements/10e6eb3.txt
  .riot/requirements/11971ed.txt
  .riot/requirements/15d4403.txt
  .riot/requirements/16d03fb.txt
  .riot/requirements/1a79d00.txt
  .riot/requirements/7669807.txt
  .riot/requirements/9c53429.txt
  .riot/requirements/9ca8b2a.txt
  riotfile.py
Labels: changelog/no-changelog

#8503 fix(asm): ensure remote config keys deleted are updated as expected
  ddtrace/internal/remoteconfig/_publishers.py
  ddtrace/internal/remoteconfig/client.py
  releasenotes/notes/fix_rule_override_in_rc-ca88baccda452486.yaml
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: bug, ASM, backport 1.20, backport 2.4, backport 2.5, backport 2.6

#8472 test(di): add custom object redaction test case
  tests/debugging/test_debugger.py
  tests/submod/stuff.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#8528 ci: pin commitlint versions to <1.19.0 to fix error
  .github/workflows/pr-name.yml
Labels: changelog/no-changelog

#8513 ci: add docker-compose.yml to $harness suite
  tests/.suitespec.json
  tests/suitespec.py
Labels: changelog/no-changelog, CI

#8526 ci: simplify suitespec doctest
  tests/suitespec.py
Labels: changelog/no-changelog

#8461 chore: make span.sampled reference span.context.sampling_priority and deprecate it
  ddtrace/_trace/span.py
  ddtrace/_trace/tracer.py
  ddtrace/contrib/algoliasearch/patch.py
  ddtrace/contrib/elasticsearch/patch.py
  ddtrace/contrib/psycopg/extensions.py
  ddtrace/internal/sampling.py
  ddtrace/llmobs/_integrations/base.py
  tests/tracer/test_sampler.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#8476 feat(llmobs): inline annotations for LLMObs spans
  ddtrace/llmobs/__init__.py
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/openai.py
  ddtrace/llmobs/_llmobs.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/contrib/openai/utils.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: changelog/no-changelog, MLObs

#8530 feat(llmobs): add ml_app tag to LLMObs spans
  ddtrace/llmobs/_llmobs.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/openai/utils.py
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_service.py
  tests/utils.py
Labels: changelog/no-changelog

#8536 fix(iast): avoid ast patch subscript if in store context
  ddtrace/appsec/_iast/_ast/visitor.py
  releasenotes/notes/iast-fix-patching-subscript-store-6baf9627164eeec6.yaml
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/fixtures/ast/subscript/store_context.py
Labels: bug, ASM, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8541 ci: pin commitlint versions to <1.19.0 to fix error [backport 1.20]
  .github/workflows/pr-name.yml
Labels: changelog/no-changelog, CI

#8542 ci: pin commitlint versions to <1.19.0 to fix error [backport 2.4]
  .github/workflows/pr-name.yml
Labels: changelog/no-changelog, CI

#8544 ci: pin commitlint versions to <1.19.0 to fix error [backport 2.6]
  .github/workflows/pr-name.yml
Labels: changelog/no-changelog, CI

#8543 ci: pin commitlint versions to <1.19.0 to fix error [backport 2.5]
  .github/workflows/pr-name.yml
Labels: changelog/no-changelog, CI

#8529 chore: update codeowners for integrations
  .github/CODEOWNERS
Labels: changelog/no-changelog

#8474 chore(asm): move asm waf triggers from meta to meta_struct
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_utils.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/contrib/djangorestframework/test_appsec.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/contrib/flask/test_flask_appsec_telemetry.py
Labels: changelog/no-changelog, ASM

#8450 ci(spellcheck): make ci and commit hooks consistent
  hatch.toml
  hooks/scripts/run-codespell.sh
Labels: changelog/no-changelog

#8549 fix(iast): avoid reporting line number 0
  ddtrace/appsec/_iast/_stacktrace.c
  ddtrace/appsec/_iast/taint_sinks/_base.py
  releasenotes/notes/iast-fix-report-line-number-0-c951395b4e5d6dc4.yaml
  tests/appsec/iast/fixtures/taint_sinks/weak_algorithms.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/taint_sinks/test_weak_hash.py
Labels: bug, ASM, backport 2.4, backport 2.5, backport 2.6, backport 2.7

#8550 fix(propagation): don't override sampling decisionmaker tag when present in propagation headers
  ddtrace/propagation/http.py
Labels: changelog/no-changelog

#8558 fix(setup): re-introduce tiktoken optional dependency
  setup.py
Labels: changelog/no-changelog

#8556 ci: work around a bunch of unreliable test failures
  riotfile.py
  tests/profiling/collector/test_memalloc.py
  tests/tracer/runtime/test_container.py
  tests/utils.py
Labels: changelog/no-changelog

#8557 feat(openai): use tiktoken to calculate streamed completion tokens
  ddtrace/contrib/openai/_endpoint_hooks.py
  ddtrace/contrib/openai/utils.py
  ddtrace/llmobs/_integrations/openai.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog

#8532 ci(sqlite3): upgrade tests to support latest versions of sqlite3
  .riot/requirements/1544815.txt
  .riot/requirements/16eb426.txt
  .riot/requirements/1c64cfc.txt
  .riot/requirements/1d73048.txt
  .riot/requirements/1e311f5.txt
  .riot/requirements/1fc50b1.txt
  riotfile.py
  tests/contrib/sqlite3/test_sqlite3.py
  tests/contrib/sqlite3/test_sqlite3_patch.py
Labels: changelog/no-changelog

#8560 ci: fix more instances of telemetry test writer flakiness
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#8561 ci: honor xfails that happen in subprocess snapshot tests
  tests/conftest.py
Labels: changelog/no-changelog
