Repository DataDog/dd-trace-py, pull requests merged in 2024-07, with the labels that each got.

#9697 chore(ci): deal with missing zip dependency
  .github/workflows/build_python_3.yml
  scripts/zip_filter.py
Labels: changelog/no-changelog

#9681 docs: explicitly say in lib-injection docs that it doesnt require ddtrace-run
  lib-injection/README.md
Labels: changelog/no-changelog

#9679 chore(asm): migrate hatch threat tests to 3.12
  hatch.toml
  tests/appsec/contrib_appsec/db.sqlite3
Labels: changelog/no-changelog, ASM

#9592 chore(symdb): handle potential import race on enable
  ddtrace/internal/symbol_db/remoteconfig.py
  ddtrace/internal/symbol_db/symbols.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9661 chore(tracer): span exception core event
  ddtrace/_trace/span.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#9578 chore(di): remove generic sensitive identifiers
  ddtrace/debugging/_redaction.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9689 chore(profiling): add debug asserts for our stack assumptions
  ddtrace/profiling/collector/_lock.py
  ddtrace/settings/profiling.py
  riotfile.py
Labels: changelog/no-changelog, Profiling

#9692 fix(profiling): show lock init location and hide internal frame
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-timeline-lock-init-loc-and-frames-39a43f924bde88d2.yaml
  tests/profiling/collector/test_asyncio.py
  tests/profiling/collector/test_threading.py
  tests/profiling/collector/test_threading_asyncio.py
  tests/profiling/simple_program_fork.py
Labels: Profiling

#9680 chore(telemetry): improve the maintainability of the telemetry writer
  ddtrace/__init__.py
  ddtrace/_monkey.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
  ddtrace/bootstrap/preload.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/internal/telemetry/__init__.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  tests/integration/test_settings.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#9704 docs(tracing): document HTTPPropagator in distributed tracing section
  ddtrace/propagation/http.py
  docs/advanced_usage.rst
Labels: changelog/no-changelog

#9688 chore(profiling): add tests for wrapt disable extensions
  .riot/requirements/1b559c7.txt
  .riot/requirements/1c31b2e.txt
  .riot/requirements/1e81c99.txt
  .riot/requirements/1ef847d.txt
  .riot/requirements/1fa5bd6.txt
  .riot/requirements/d6b8465.txt
  riotfile.py
  tests/profiling/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#9701 chore(tracer): use simple queue file for extra service names instead of multiprocessing
  .github/CODEOWNERS
  .github/workflows/unit_tests.yml
  ddtrace/internal/_file_queue.py
  ddtrace/settings/config.py
  hatch.toml
  tests/.suitespec.json
  tests/internal/service_name/test_extra_services_names.py
Labels: changelog/no-changelog

#9709 chore(setup): early check for valid Rust toolchain
  setup.py
Labels: changelog/no-changelog, mergequeue-status: queued

#9715 chore(tracer): remove attr and cattr from remoteconfig
  ddtrace/internal/remoteconfig/_publishers.py
  ddtrace/internal/remoteconfig/client.py
  pyproject.toml
Labels: changelog/no-changelog

#9720 fix(internal): catch pathlib OSError in packages.py
  ddtrace/internal/packages.py
  releasenotes/notes/fix_packages_oserror-b8da190cea6997de.yaml
  tests/internal/test_packages.py
Labels: backport 2.9, backport 2.10

#9658 fix(llmobs): deprecate and convert numerical metrics to score type
  ddtrace/llmobs/_llmobs.py
  releasenotes/notes/clarify-numeric-llmobs-metric-type-unsupported-9f3fb2caa0366b95.yaml
  tests/llmobs/test_llmobs_service.py
Labels: backport 2.9, backport 2.10

#9710 chore(ci): parallelize build wheels
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, CI

#9501 fix(profiling): fix encoding-related issues in stack v2
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/include/stack_renderer.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  releasenotes/notes/fix-stack-v2-task-encoding-447f39478749027c.yaml
Labels: backport 2.8, backport 2.9, backport 2.10

#9735 chore(ci): deal with missing zip dependency [backport 2.10]
  .github/workflows/build_python_3.yml
  scripts/zip_filter.py
Labels: changelog/no-changelog

#9733 chore(ci): deal with missing zip dependency [backport 2.9]
  .github/workflows/build_python_3.yml
  scripts/zip_filter.py
Labels: changelog/no-changelog

#9734 chore(ci): deal with missing zip dependency [backport 2.8]
  .github/workflows/build_python_3.yml
  scripts/zip_filter.py
Labels: changelog/no-changelog

#9740 chore(asm): replace dependency with updated one
  hatch.toml
Labels: changelog/no-changelog, ASM, CI

#9724 chore: update the envier dependency
  .riot/requirements/1057ff6.txt
  .riot/requirements/10af9e2.txt
  .riot/requirements/16af7e0.txt
  .riot/requirements/1aaf6f6.txt
  .riot/requirements/1fa807e.txt
  .riot/requirements/67afac8.txt
  .riot/requirements/cc1a9bf.txt
  .riot/requirements/d0d958a.txt
  .riot/requirements/dd525d9.txt
  .riot/requirements/e39f833.txt
  .riot/requirements/edb39c1.txt
  hatch.toml
  lib-injection/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
Labels: changelog/no-changelog

#9555 fix(flask): fix crashes with flask-like frameworks
  .riot/requirements/128ac84.txt
  .riot/requirements/139048e.txt
  .riot/requirements/13e6e97.txt
  .riot/requirements/1415ef8.txt
  .riot/requirements/14685d1.txt
  .riot/requirements/1634f79.txt
  .riot/requirements/179337c.txt
  .riot/requirements/19f3b8d.txt
  .riot/requirements/1b1c34d.txt
  .riot/requirements/1b22123.txt
  .riot/requirements/1b6da7f.txt
  .riot/requirements/1c53a7f.txt
  .riot/requirements/1c6c710.txt
  .riot/requirements/1e93f9f.txt
  .riot/requirements/1ecbb51.txt
  .riot/requirements/1f0ee7f.txt
  .riot/requirements/2be57d3.txt
  .riot/requirements/3cbe634.txt
  .riot/requirements/629f3d6.txt
  .riot/requirements/65cdef7.txt
  .riot/requirements/8145a13.txt
  .riot/requirements/8654a9e.txt
  .riot/requirements/89d7a5f.txt
  .riot/requirements/976376a.txt
  .riot/requirements/a3c3dfa.txt
  .riot/requirements/b669824.txt
  .riot/requirements/b9c205c.txt
  .riot/requirements/c384590.txt
  .riot/requirements/c3912b5.txt
  .riot/requirements/c46d031.txt
  .riot/requirements/d165a69.txt
  .riot/requirements/d1dd9c4.txt
  .riot/requirements/df69ea1.txt
  .riot/requirements/e5e2721.txt
  .riot/requirements/e9e35ef.txt
  .riot/requirements/ece9fb0.txt
  .riot/requirements/f3bee4b.txt
  .riot/requirements/f408d1f.txt
  .riot/requirements/f7b33fd.txt
  .riot/requirements/fcfaa6e.txt
  .riot/requirements/ff0c51d.txt
  ddtrace/contrib/flask/patch.py
  releasenotes/notes/flask-fix-crashes-with-add-url-rule-536f1d1194182bf6.yaml
  riotfile.py
  tests/contrib/flask/test_flask_openapi3.py
Labels: backport 2.8, backport 2.9

#9747 fix(langchain): tag non-dict inputs appropriately
  ddtrace/contrib/langchain/patch.py
  releasenotes/notes/langchain-non-dict-inputs-310427c510acf1e5.yaml
  tests/contrib/langchain/test_langchain_community.py
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcecl_chain_non_dict_input.json
Labels: backport 2.8, backport 2.9, backport 2.10

#9742 chore(asm): update obfuscation regexes
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_processor.py
Labels: changelog/no-changelog, ASM

#9705 feat(asm): grpc threats support
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_processor.py
  ddtrace/contrib/grpc/client_interceptor.py
  ddtrace/contrib/grpc/server_interceptor.py
  releasenotes/notes/asm-grpc-treats-support-025582704f96dc7d.yaml
  tests/appsec/iast/test_grpc_iast.py
Labels: ASM

#9741 ci: switch system-tests to python 3.12
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI, backport 2.7, backport 2.8, backport 2.9, backport 2.10

#9494 fix(azure_functions): run the mini agent regardless of azure hosting plan
  ddtrace/_trace/tracer.py
  ddtrace/internal/serverless/__init__.py
  ddtrace/internal/serverless/mini_agent.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/config.py
  releasenotes/notes/allow-mini-agent-to-run-on-all-hosting-plans-5e8df7330c108d71.yaml
  tests/internal/test_serverless.py
Labels: backport 2.10

#9763 chore(asm): use minify version of default blocking payload
  ddtrace/internal/constants.py
  tests/appsec/integrations/test_flask_remoteconfig.py
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#9766 ci: switch system-tests to python 3.12 [backport 2.7]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#9775 chore(ci): use python 3.12 for parametric tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI, backport 2.7, backport 2.8, backport 2.9, backport 2.10

#9780 chore(ci): use python 3.12 for parametric tests (#9775) [backport 2.9]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#9779 chore(ci): use python 3.12 for parametric tests (#9775) [backport 2.8]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#9778 chore(ci): use python 3.12 for parametric tests (#9775) [backport 2.7]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#9745 chore(tracing): improve the detection of unfinished spans
  ddtrace/_trace/processor/__init__.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#9756 fix(llmobs): only set temperature/max_tokens if provided
  ddtrace/llmobs/_integrations/anthropic.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/openai.py
  releasenotes/notes/fix-llmobs-openai-temperature-b939df0fb6ac2958.yaml
  tests/contrib/anthropic/test_anthropic_llmobs.py
  tests/contrib/openai/test_openai_llmobs.py
Labels: backport 2.9, backport 2.10

#9776 chore(asm): improve accept header management for threats
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/django/patch.py
  ddtrace/contrib/flask/patch.py
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/flask/test_flask_appsec.py
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#9746 chore: remove `attrs` from benchmarks
  benchmarks/README.rst
  benchmarks/appsec_iast_propagation/scenario.py
  benchmarks/bm/__init__.py
  benchmarks/bm/_scenario.py
  benchmarks/bm/_to_bool.py
  benchmarks/bm/flask_utils.py
  benchmarks/core_api/scenario.py
  benchmarks/ddtrace_run/scenario.py
  benchmarks/django_simple/scenario.py
  benchmarks/encoder/scenario.py
  benchmarks/flask_simple/scenario.py
  benchmarks/flask_sqli/scenario.py
  benchmarks/http_propagation_extract/config.yaml
  benchmarks/http_propagation_extract/scenario.py
  benchmarks/http_propagation_inject/scenario.py
  benchmarks/iast_ast_patching/scenario.py
  benchmarks/otel_span/scenario.py
  benchmarks/rate_limiter/scenario.py
  benchmarks/sampling_rule_matches/scenario.py
  benchmarks/set_http_meta/scenario.py
  benchmarks/span/scenario.py
  benchmarks/startup/scenario.py
  benchmarks/threading/scenario.py
  benchmarks/tracer/scenario.py
Labels: changelog/no-changelog

#9784 chore: add moto to IAST denylist
  ddtrace/appsec/_iast/_ast/ast_patching.py
Labels: changelog/no-changelog, ASM, backport 2.7, backport 2.8, backport 2.9

#9765 ci: switch system-tests to python 3.12 [backport 2.8]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#9764 ci: switch system-tests to python 3.12 [backport 2.9]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#9511 fix(redis): handle rowcount when BaseException is raised
  ddtrace/contrib/redis_utils.py
  releasenotes/notes/fix-redis-catch-cancelled-error-c39431f98276a0b0.yaml
  tests/contrib/redis/test_redis_asyncio.py
Labels: backport 2.10

#9790 chore(lib-injection): publish additional docker tags for lib injection image [backport 2.9]
  .gitlab-ci.yml
  .gitlab/build-lib-init.sh
Labels: changelog/no-changelog

#9713 chore: simplify checklists in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog/no-changelog

#9793 chore: add moto and other modules to IAST denylist [backport 2.8]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/asm-boto-denylist-9ea0dee3a33fff7c.yaml
Labels: ASM

#9785 chore: add changelog for #9784
  releasenotes/notes/asm-boto-denylist-9ea0dee3a33fff7c.yaml
Labels: ASM

#9792 chore: add moto and other modules to IAST denylist [backport 2.9]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/asm-boto-denylist-9ea0dee3a33fff7c.yaml
Labels: ASM

#9794 chore: add moto and other modules to IAST denylist [backport 2.7]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/asm-boto-denylist-9ea0dee3a33fff7c.yaml
Labels: ASM

#9797 chore: add moto to IAST denylist [backport 2.10]
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/asm-boto-denylist-9ea0dee3a33fff7c.yaml
Labels: ASM

#9795 ci(internal): ensure subprocess tests finish spans
  tests/internal/test_database_monitoring.py
Labels: changelog/no-changelog

#9802 chore(ci): add OCI packaging [backport 2.9]
  .gitlab/build-oci.sh
Labels: changelog/no-changelog

#9799 chore: added `@tracing` to the internal block for suitespec
  tests/.suitespec.json
Labels: changelog/no-changelog

#9505 chore: update changelog for version 2.9.0
  CHANGELOG.md
Labels: changelog/no-changelog

#9721 refactor(debugger): make uploader independent
  ddtrace/bootstrap/preload.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_exception/auto_instrument.py
  ddtrace/debugging/_uploader.py
  tests/debugging/exception/test_auto_instrument.py
  tests/debugging/exploration/debugger.py
  tests/debugging/exploration/test_bootstrap.py
  tests/debugging/mocking.py
  tests/debugging/test_uploader.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#9725 chore: partially remove attrs
  ddtrace/appsec/_iast/processor.py
  ddtrace/contrib/subprocess/patch.py
  ddtrace/internal/processor/endpoint_call_counter.py
  ddtrace/internal/rate_limiter.py
Labels: changelog/no-changelog, ASM

#9783 chore: add package test for moto
  ddtrace/appsec/_iast/_ast/ast_patching.py
  tests/appsec/app.py
  tests/appsec/iast_packages/packages/pkg_moto.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#9668 chore(ci_visibility): performance improvements for internal coverage collector
  .circleci/config.templ.yml
  ddtrace/internal/coverage/code.py
  ddtrace/internal/coverage/instrumentation.py
  ddtrace/internal/coverage/instrumentation_py3_10.py
  ddtrace/internal/coverage/instrumentation_py3_11.py
  ddtrace/internal/coverage/instrumentation_py3_12.py
  ddtrace/internal/coverage/instrumentation_py3_8.py
  ddtrace/internal/coverage/instrumentation_py3_9.py
  ddtrace/internal/coverage/instrumentation_py3_fallback.py
  ddtrace/internal/module.py
  hatch.toml
  pyproject.toml
  tests/.suitespec.json
Labels: changelog/no-changelog

#9388 chore(ci): delay dogfood stage until after benchmarks
  .gitlab-ci.yml
Labels: changelog/no-changelog

#9804 chore(ci): added quotes to fix the `--omit` flag for coverage report
  .circleci/config.templ.yml
Labels: changelog/no-changelog

#9811 ci(fastapi): updating test requirements for fastapi
  .riot/requirements/121f3e0.txt
  .riot/requirements/1483567.txt
  .riot/requirements/148692c.txt
  .riot/requirements/15aa558.txt
  .riot/requirements/1683094.txt
  .riot/requirements/171b20f.txt
  .riot/requirements/1b3efb5.txt
  .riot/requirements/1ca5ab3.txt
  .riot/requirements/35e4d8d.txt
  .riot/requirements/45b92b9.txt
  .riot/requirements/51442dd.txt
  .riot/requirements/7faa8e0.txt
  .riot/requirements/958996c.txt
  .riot/requirements/a7d2dc1.txt
  .riot/requirements/dcf90ee.txt
  .riot/requirements/eb3b2f1.txt
Labels: changelog/no-changelog

#9665 chore(ci): upgrade pyenv, upgrade python versions, add 3.13-dev
  docker/.python-version
  docker/Dockerfile
Labels: changelog/no-changelog

#9807 chore(llmobs): backport token metric key name changes to 2.9
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/openai.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_chat_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_multiple_events.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_timed_events.yaml
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_span_writer.py
Labels: changelog/no-changelog

#9817 chore(docs): install rust for .readthedocs.yml
  .readthedocs.yml
Labels: changelog/no-changelog

#9808 chore(llmobs): backport token metric key name changes to 2.10
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/anthropic.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/openai.py
  tests/contrib/anthropic/test_anthropic_llmobs.py
  tests/contrib/botocore/test_bedrock_llmobs.py
  tests/contrib/openai/test_openai_llmobs.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_chat_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_completion_event.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_multiple_events.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_writer.test_send_timed_events.yaml
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_span_writer.py
Labels: changelog/no-changelog

#9824 chore(profiling): enable test
  tests/commands/test_runner.py
Labels: changelog/no-changelog

#9819 chore: added missing tests/contrib/botocore/test_bedrock_llmobs.py
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9812 chore(internal): update vendored debtcollector to 2.5.0
  ddtrace/vendor/__init__.py
  ddtrace/vendor/debtcollector/__init__.py
  ddtrace/vendor/debtcollector/_utils.py
  ddtrace/vendor/debtcollector/moves.py
  ddtrace/vendor/debtcollector/removals.py
  ddtrace/vendor/debtcollector/renames.py
  ddtrace/vendor/debtcollector/updating.py
Labels: changelog/no-changelog

#9788 fix(wsgi): don't report stopiteration errors
  ddtrace/contrib/wsgi/wsgi.py
  releasenotes/notes/ignore_stopiteration_exception-43806201b7fc8005.yaml
  tests/contrib/wsgi/test_wsgi.py
  tests/snapshots/tests.contrib.wsgi.test_wsgi.test_stop_iteration_in_wsgi_app_py3.json
Labels: backport 2.8, backport 2.9, backport 2.10

#9684 ci: mypy lint against the oldest supported py version
  mypy.ini
Labels: changelog/no-changelog

#9816 docs: small changes to quickstart to use placeholder values, minor wording
  docs/installation_quickstart.rst
Labels: changelog/no-changelog

#9832 ci: revert mypy lint against the oldest supported py version (#9684)
  mypy.ini
Labels: changelog/no-changelog

#9827 chore: remove type comments from benchmarks/
  benchmarks/appsec_iast_propagation/scenario.py
  benchmarks/threading/scenario.py
Labels: changelog/no-changelog

#9833 chore(ci): trigger `riot run lint:typing` for `mypy.ini` changes
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#9821 chore(profiling): use `__slots__` instead of `attr.s(slots=True)` for Event classes
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/asyncio.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack_event.py
  ddtrace/profiling/collector/threading.py
  ddtrace/profiling/event.py
Labels: changelog/no-changelog, Profiling

#9822 chore(profiling): remove attrs from profiling/exporter/
  ddtrace/profiling/exporter/__init__.py
  ddtrace/profiling/exporter/file.py
  ddtrace/profiling/exporter/http.py
  ddtrace/profiling/exporter/pprof.pyx
Labels: changelog/no-changelog, Profiling

#9826 fix(iast): solve memleaks with Python 3.11 and 3.22
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectFormat.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/Source.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  releasenotes/notes/asm-memleaks-0bd0a25284dd1b9b.yaml
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: ASM

#9845 fix(ci): fix incorrect format for multi-line github action codeowners comment
  .github/workflows/codeowners.yml
Labels: changelog/no-changelog

#9847 chore: update guild code ownership
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9825 chore(profiling): remove `@attr.s` from `_Thread*Link` classes
  ddtrace/profiling/_threading.pyx
  ddtrace/profiling/collector/stack.pyx
Labels: changelog/no-changelog

#9838 ci(iast): change logic for fixme_propagation_fails
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM, CI

#9834 chore(framework tests): bump `sanic` version in framework test
  .github/workflows/test_frameworks.yml
Labels: changelog/no-changelog

#9854 chore: added entire `ddtrace/internal/*` to internal test suite
  tests/.suitespec.json
Labels: changelog/no-changelog

#9853 chore(profiling): fix CI issues from crashtracker update
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker_interface.cpp
Labels: changelog/no-changelog

#9843 chore: remove attrs from hooks
  ddtrace/_hooks.py
Labels: changelog/no-changelog

#9805 chore(iast): add test for google-auth
  tests/appsec/app.py
  tests/appsec/iast_packages/packages/pkg_google_auth.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#9841 chore: remove attrs from logging patch
  ddtrace/contrib/logging/patch.py
Labels: changelog/no-changelog

#9842 chore: remove attrs from runtime container
  ddtrace/internal/runtime/container.py
Labels: changelog/no-changelog

#9844 chore: fix memtest taint count test
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#9786 fix(redis): define result for try/catch
  ddtrace/contrib/redis_utils.py
  releasenotes/notes/redis-utils-fix-undefined-variable-6c7d2d5ffcd01b41.yaml
Labels: backport 2.10

#9859 ci: fix by unsetting `test_import` to `google-auth` package
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM, CI

#9855 chore: update CODEOWNERS for suitespec files
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9809 chore(internal): avoid re-wrapping get_code() in calls of module exec
  ddtrace/internal/module.py
  tests/internal/test_module.py
Labels: changelog/no-changelog, backport 2.10

#9796 chore(profiling): remove attrs from ddtrace/profiling
  ddtrace/internal/_threads.pyi
  ddtrace/internal/periodic.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/internal/service.py
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/asyncio.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/collector/threading.py
  ddtrace/profiling/profiler.py
  ddtrace/profiling/recorder.py
  ddtrace/profiling/scheduler.py
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog, mergequeue-status: rejected

#9857 chore: remove attrs from trace processor
  ddtrace/_trace/processor/__init__.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog

#9863 fix(ci): fix failing telemetry test_app_started_error_handled_exception
  tests/.suitespec.json
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog

#9815 chore: remove six as package dependency
  .riot/requirements/1b2734d.txt
  .riot/requirements/1db4b5f.txt
  .riot/requirements/681161c.txt
  .riot/requirements/e65fa97.txt
  benchmarks/bm/utils.py
  ddtrace/profiling/_threading.pyx
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/exporter/pprof.pyx
  docker/Dockerfile_py311_debug_mode
  docker/Dockerfile_py312_debug_mode
  hatch.toml
  lib-injection/min_compatible_versions.csv
  min_compatible_versions.csv
  pyproject.toml
  riotfile.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/iast/fixtures/aspects/str_methods.py
  tests/commands/test_runner.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/elasticsearch/test_async.py
  tests/contrib/elasticsearch/test_elasticsearch_multi.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
  tests/contrib/grpc/test_grpc.py
  tests/contrib/httpx/test_httpx.py
  tests/contrib/httpx/test_httpx_pre_0_11.py
  tests/contrib/kafka/test_kafka.py
  tests/contrib/logging/test_logging.py
  tests/contrib/requests/test_requests.py
  tests/contrib/wsgi/test_wsgi.py
  tests/debugging/function/test_discovery.py
  tests/integration/test_integration.py
  tests/internal/test_packages.py
  tests/profiling/collector/test_asyncio.py
  tests/profiling/collector/test_stack.py
  tests/profiling/collector/test_threading.py
  tests/profiling/exporter/test_http.py
  tests/profiling/exporter/test_pprof.py
  tests/submod/absstuff.py
  tests/tracer/test_compat.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
  tests/webclient.py
Labels: changelog/no-changelog

#9852 chore(profiling): fix crashtracker and ddup interfaces
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyi
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyx
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/constants.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/ddup_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader_builder.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader_builder.cpp
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  tests/internal/crashtracker/test_crashtracker.py
  tests/internal/crashtracker/utils.py
Labels: changelog/no-changelog

#9831 chore: remove type comments from ddtrace/_trace/
  ddtrace/_trace/context.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/provider.py
  ddtrace/_trace/span.py
  ddtrace/_trace/tracer.py
  ddtrace/_trace/types.py
  ddtrace/debugging/_signal/tracing.py
  ddtrace/internal/encoding.py
Labels: changelog/no-changelog

#9851 chore(internal): remove ddsketch Python dependency
  .riot/requirements/f20bd15.txt
  ddtrace/internal/core/__init__.py
  ddtrace/internal/core/_core.pyi
  ddtrace/internal/datastreams/processor.py
  ddtrace/internal/processor/stats.py
  docker/Dockerfile_py311_debug_mode
  docker/Dockerfile_py312_debug_mode
  hatch.toml
  lib-injection/min_compatible_versions.csv
  min_compatible_versions.csv
  pyproject.toml
  riotfile.py
  src/core/Cargo.lock
  src/core/Cargo.toml
  src/core/ddsketch.rs
  src/core/lib.rs
  tests/contrib/botocore/test.py
  tests/contrib/kafka/test_kafka.py
  tests/contrib/kombu/test.py
  tests/datastreams/test_processor.py
Labels: changelog/no-changelog

#9840 chore: update returned line number in test
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#9860 chore(iast): remove attrs from iast reporter
  ddtrace/appsec/_iast/reporter.py
  tests/appsec/iast/taint_sinks/test_insecure_cookie.py
Labels: changelog/no-changelog, ASM

#9866 ci(iast): avoid out of range list access
  tests/appsec/iast_packages/inside_env_runner.py
Labels: changelog/no-changelog, ASM, CI

#9871 fix(ci): add workaround for `importlib-resources` name discrepancies
  tests/internal/test_packages.py
Labels: changelog/no-changelog

#9867 chore: remove attrs from _trace/_span_link.py
  ddtrace/_trace/_span_link.py
Labels: changelog/no-changelog

#9759 fix(langchain): use correct class names for pinecone vectorstore check
  .riot/requirements/150eea5.txt
  .riot/requirements/1598e9b.txt
  .riot/requirements/1810353.txt
  .riot/requirements/1dca1e6.txt
  .riot/requirements/7aeeb05.txt
  .riot/requirements/8fdfb07.txt
  .riot/requirements/9946322.txt
  .riot/requirements/9b67887.txt
  .riot/requirements/b26ea62.txt
  .riot/requirements/b5852df.txt
  .riot/requirements/ccc7691.txt
  .riot/requirements/fd7ae89.txt
  ddtrace/contrib/langchain/patch.py
  releasenotes/notes/fix-langchain-pinecone-vectorstore-082c023ccae268e1.yaml
  riotfile.py
  tests/contrib/langchain/cassettes/langchain_community/openai_retrieval_embedding.yaml
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/langchain/test_langchain_llmobs.py
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_faiss_vectorstore_retrieval.json
Labels: backport 2.9, backport 2.10

#9868 chore: remove attrs from dd-trace-py
  .riot/requirements/50d0377.txt
  docker/Dockerfile_py311_debug_mode
  docker/Dockerfile_py312_debug_mode
  hatch.toml
  lib-injection/min_compatible_versions.csv
  min_compatible_versions.csv
  pyproject.toml
  riotfile.py
  tests/utils.py
Labels: changelog/no-changelog

#9879 fix(ci): add workaround for `importlib-resources` name discrepancies [backport 2.9]
  tests/internal/test_packages.py
Labels: changelog/no-changelog

#9830 fix: telemetry exception hooks
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry.py
Labels: changelog/no-changelog, backport 2.10

#9814 docs: update contributing snapshot tests for clarity and style
  docs/contributing-integrations.rst
Labels: changelog/no-changelog

#9865 chore(internal): start crashtracker when enabled
  ddtrace/bootstrap/preload.py
  ddtrace/internal/core/crashtracking.py
  ddtrace/internal/datadog/profiling/crashtracker/__init__.py
  ddtrace/internal/runtime/__init__.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/crashtracker.py
  tests/internal/crashtracker/test_crashtracker.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#9876 chore(llmobs): extract and refactor langchain llmobs tests [backport 2.9]
  .riot/requirements/1084a71.txt
  .riot/requirements/17e8568.txt
  .riot/requirements/1ec5924.txt
  .riot/requirements/1f6f978.txt
  .riot/requirements/39161c9.txt
  .riot/requirements/76db01b.txt
  .riot/requirements/8297334.txt
  .riot/requirements/e17f33e.txt
  .riot/requirements/ee6f953.txt
  riotfile.py
  tests/contrib/langchain/cassettes/langchain/openai_completion_sync.yaml
  tests/contrib/langchain/conftest.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/langchain/test_langchain_llmobs.py
  tests/contrib/langchain/test_langchain_patch.py
  tests/contrib/langchain/utils.py
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_sequential_chain_with_multiple_llm_async.json
  tests/snapshots/tests.contrib.langchain.test_langchain.test_openai_sequential_chain_with_multiple_llm_sync.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_integration.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[None-None].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[None-v0].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[None-v1].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[mysvc-None].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[mysvc-v0].json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_openai_service_name[mysvc-v1].json
Labels: changelog/no-changelog

#9839 ci: don't let ruff fix unused imports (rule F401)
  pyproject.toml
Labels: changelog/no-changelog

#9520 chore(telemetry): use enum for telemetry log levels
  ddtrace/_trace/processor/__init__.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_metrics.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_telemetry_metrics.py
Labels: changelog/no-changelog

#9873 fix: add encodings.idna to the denylist
  ddtrace/appsec/_iast/_ast/ast_patching.py
  releasenotes/notes/asm-avoid-idna-d724dce73afafa93.yaml
Labels: ASM, backport 2.9, backport 2.10

#9708 refactor: rename exception replay enablement variable
  ddtrace/bootstrap/preload.py
  ddtrace/debugging/_config.py
  ddtrace/debugging/_debugger.py
  ddtrace/debugging/_exception/replay.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/exception_replay.py
  docs/configuration.rst
  releasenotes/notes/refactor-di-er-enablement-env-var-12056782561eecc6.yaml
  tests/.suitespec.json
  tests/debugging/exception/test_replay.py
  tests/debugging/mocking.py
  tests/telemetry/test_writer.py
Labels: Dynamic Instrumentation

#9882 chore: add `@DataDog/apm-sdk-api-python` to CODEOWNERS
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9856 feat(botocore): add override service name to botocore integration
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/botocore/services/bedrock.py
  ddtrace/contrib/botocore/services/kinesis.py
  ddtrace/contrib/botocore/services/sqs.py
  ddtrace/contrib/botocore/services/stepfunctions.py
  docs/configuration.rst
  releasenotes/notes/add-c0f1d24cf11f23b7.yaml
  tests/contrib/botocore/test.py
Labels: backport 2.10

#9889 chore: add `CODEOWNERS.md` and `README.md` to apm-python team
  .github/CODEOWNERS
Labels: changelog/no-changelog

#9896 chore: add `benchmarks/appsec*` for ASM approval
  .github/CODEOWNERS
Labels: changelog/no-changelog, backport 2.10

#9883 chore: adding type Literal to constants for db monitoring and http
  ddtrace/propagation/_database_monitoring.py
  ddtrace/propagation/http.py
Labels: changelog/no-changelog

#9892 chore(profiling): add interface for crashtracker tags
  ddtrace/internal/core/crashtracking.py
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyi
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyx
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker_interface.cpp
  ddtrace/settings/crashtracker.py
  tests/internal/crashtracker/test_crashtracker.py
Labels: changelog/no-changelog

#9906 chore(asm): update libddwaf to 1.19.0
  setup.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM, backport 2.10

#9870 chore: remove another temporal in the propagation test
  tests/appsec/iast/fixtures/propagation_path.py
Labels: changelog/no-changelog, ASM

#9891 chore: adding type Literal to constants for files in appsec
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
Labels: changelog/no-changelog

#9902 chore(langchain): update latest langchain test version
  .riot/requirements/118ee67.txt
  .riot/requirements/12e6c9b.txt
  .riot/requirements/19a938f.txt
  .riot/requirements/1bb07e0.txt
  .riot/requirements/1e57344.txt
  .riot/requirements/5425133.txt
  .riot/requirements/8dd750a.txt
  .riot/requirements/b5df1ff.txt
  .riot/requirements/c06d6c9.txt
  riotfile.py
  tests/contrib/langchain/test_langchain_community.py
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_lcel_chain_non_dict_input.json
Labels: changelog/no-changelog, backport 2.9, backport 2.10

#9910 chore(tracer): use simple queue file for extra service names instead of multiprocessing [backport 2.10]
  .github/CODEOWNERS
  .github/workflows/unit_tests.yml
  ddtrace/internal/_file_queue.py
  ddtrace/settings/config.py
  hatch.toml
  tests/.suitespec.json
  tests/internal/service_name/test_extra_services_names.py
Labels: changelog/no-changelog

#9920 chore(asm): update security rules to 1.13.0
  ddtrace/appsec/rules.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM, backport 2.10

#9913 chore(langchain): update latest langchain test version [backport #9902 to 2.9]
  .riot/requirements/1708d3c.txt
  .riot/requirements/177d27b.txt
  .riot/requirements/8e6b762.txt
  .riot/requirements/e17f33e.txt
  .riot/requirements/ee6f953.txt
  riotfile.py
  tests/contrib/langchain/test_langchain_community.py
Labels: changelog/no-changelog

#9921 fix(internal): set net.git-fetch-with-cli=true for core rust extension
  .gitlab/benchmarks.yml
  src/core/Cargo.toml
Labels: changelog/no-changelog

#9923 chore(core): crashtracker should resolve stacks by default
  ddtrace/settings/crashtracker.py
  tests/internal/crashtracker/test_crashtracker.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#9905 fix: disable the iast enabled check from native code
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  releasenotes/notes/iast-dont-throw-native-a1d1adcf209dc529.yaml
  tests/appsec/iast/test_env_var.py
  tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
  tests/smoke_test.py
Labels: ASM, backport 2.9, backport 2.10

#9914 chore(langchain): update latest langchain test version [backport #9902 to 2.10]
  .riot/requirements/1930a28.txt
  .riot/requirements/45c150f.txt
  .riot/requirements/b6ac170.txt
  riotfile.py
  tests/contrib/langchain/test_langchain_community.py
Labels: changelog/no-changelog

#9932 ci(opentelemetry): pin opentelemetry-api version to unblock tests
  .riot/requirements/12974a3.txt
  .riot/requirements/1677649.txt
  .riot/requirements/17c4377.txt
  .riot/requirements/18589ec.txt
  .riot/requirements/1a14242.txt
  .riot/requirements/5c0475c.txt
  riotfile.py
Labels: changelog/no-changelog, backport 2.8, backport 2.9, backport 2.10

#9915 chore: privatize public functions in consul and botocore patch.py
  ddtrace/contrib/botocore/patch.py
  ddtrace/contrib/consul/patch.py
  releasenotes/notes/deprecate-patch-py-methods-consul-botocore-da36c9501c7fc279.yaml
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#9929 fix(opentelemetry): resolve circular imports
  .github/CODEOWNERS
  .riot/requirements/1029814.txt
  .riot/requirements/104cf8b.txt
  .riot/requirements/10f03b7.txt
  .riot/requirements/11f3313.txt
  .riot/requirements/11f8ba6.txt
  .riot/requirements/13538ad.txt
  .riot/requirements/14a0494.txt
  .riot/requirements/1634a62.txt
  .riot/requirements/17515f6.txt
  .riot/requirements/1797885.txt
  .riot/requirements/1891232.txt
  .riot/requirements/1a30edd.txt
  .riot/requirements/1c4ed0a.txt
  .riot/requirements/1cd9272.txt
  .riot/requirements/1d3d6ad.txt
  .riot/requirements/1f35619.txt
  .riot/requirements/3e7be37.txt
  .riot/requirements/4bacb9c.txt
  .riot/requirements/4de07e7.txt
  .riot/requirements/515d65f.txt
  .riot/requirements/59f93d3.txt
  .riot/requirements/5d17c94.txt
  .riot/requirements/622ac33.txt
  .riot/requirements/6450b7c.txt
  .riot/requirements/82d4fd1.txt
  .riot/requirements/a16e5c1.txt
  .riot/requirements/a367077.txt
  .riot/requirements/a3e6122.txt
  .riot/requirements/a4a20ae.txt
  .riot/requirements/aab3556.txt
  .riot/requirements/ca367e6.txt
  .riot/requirements/ddd1e3f.txt
  .riot/requirements/ea8be54.txt
  .riot/requirements/efe1fdc.txt
  .riot/requirements/fd63264.txt
  ddtrace/internal/opentelemetry/context.py
  pyproject.toml
  releasenotes/notes/fix-otel-circular-imports-66f6c926d8626751.yaml
  riotfile.py
  tests/.suitespec.json
  tests/opentelemetry/conftest.py
Labels: backport 2.9, backport 2.10

#9935 fix: disable the iast enabled check from native code [backport 2.9]
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  releasenotes/notes/iast-dont-throw-native-a1d1adcf209dc529.yaml
  tests/appsec/iast/test_env_var.py
  tests/appsec/integrations/test_flask_entrypoint_iast_patches.py
  tests/smoke_test.py
Labels: ASM

#9924 chore(tracer): fix version computation for 2.10 for system tests backports
  pyproject.toml
Labels: changelog/no-changelog

#9930 chore(ci): use unified Gitlab pipeline for APM libraries
  .github/workflows/build_deploy.yml
  .github/workflows/lib-inject-publish.yml
  .github/workflows/lib-injection.yml
  .gitlab-ci.yml
  .gitlab/build-deb-rpm.sh
  .gitlab/build-lib-init.sh
  .gitlab/build-oci.sh
  .gitlab/download-dependency-wheels.sh
  .gitlab/download-wheels-from-gh-actions.sh
  .gitlab/prepare-oci-package.sh
  lib-injection/Dockerfile
  lib-injection/copy-lib.sh
  lib-injection/dl_wheels.py
Labels: changelog/no-changelog, CI

#9918 chore: use HTTP policy with multipart uploads
  ddtrace/internal/utils/http.py
Labels: changelog/no-changelog

#9954 chore(asm): improve rasp call mechanism
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
  releasenotes/notes/rasp_conditional_call-f700a122b82b4c4f.yaml
  tests/appsec/appsec/rules-rasp-disabled.json
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/rules.py
Labels: enhancement, changelog/no-changelog, ASM

#9953 ci: add macrobenchmarks scenarios with profiling enabled
  .gitlab/macrobenchmarks.yml
Labels: changelog/no-changelog, CI

#9874 fix(asm): one click remote config fix
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/remoteconfig/_publishers.py
  ddtrace/internal/remoteconfig/client.py
  releasenotes/notes/rc_asm_features_fix-56fb35d0ca6c5d69.yaml
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
Labels: bug, ASM, backport 2.8, backport 2.9, backport 2.10

#9944 chore: privatizing methods psycopg,pylibmc,pymemcache,pymongo,pymysql,pynamodb,pyodbc,pyramid
  ddtrace/contrib/psycopg/patch.py
  ddtrace/contrib/pylibmc/patch.py
  ddtrace/contrib/pymemcache/patch.py
  ddtrace/contrib/pymongo/patch.py
  ddtrace/contrib/pymysql/patch.py
  ddtrace/contrib/pynamodb/patch.py
  ddtrace/contrib/pyodbc/patch.py
  ddtrace/contrib/pyramid/patch.py
  releasenotes/notes/deprecate-patch-py-methods-psycopg-pylibmc-pymemcache-pymongo-pymysql-pynamodb-pyodbc-pyramid-df1d8182d30d1950.yaml
  tests/contrib/pyramid/utils.py
Labels: changelog/no-changelog

#9956 chore: cleanup redundant psycopg async methods
  ddtrace/contrib/psycopg/async_cursor.py
Labels: changelog/no-changelog

#9965 chore: update changelog for version 2.9.4
  CHANGELOG.md
Labels: changelog/no-changelog

#9975 chore: update 2.9.4 CHANGELOG to match GitHub release note
  CHANGELOG.md
Labels: changelog/no-changelog

#9978 chore: update changelog for version 2.10.1
  CHANGELOG.md
Labels: changelog/no-changelog

#9976 chore: update changelog for version 2.10.0
  CHANGELOG.md
Labels: changelog/no-changelog

#9977 chore(release-script): add ability to promote release candidates
  scripts/release.py
Labels: changelog/no-changelog
