Repository DataDog/dd-trace-py, pull requests merged in 2024-09, with the labels that each got.

#10474 chore(iast): testing fastapi and sqli
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#10456 chore(iast): more native utils and split aspects moved to fully native
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSplit.h
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/iast/aspects/test_split_aspect.py
Labels: changelog/no-changelog, ASM

#10481 chore(iast): fix memleak on process_flag_added_args
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
Labels: changelog/no-changelog, ASM

#10472 ci: move more appsec suites to GitLab
  .circleci/config.templ.yml
  .gitlab/tests.yml
  .gitlab/tests/appsec.yml
  tests/appsec/iast/fixtures/taint_sinks/sql_injection_psycopg2.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/appsec/iast_tdd_propagation/test_flask.py
Labels: changelog/no-changelog

#10483 chore(CI): starlette tests
  .github/workflows/test_frameworks.yml
  ddtrace/appsec/_handlers.py
Labels: changelog/no-changelog, ASM, CI

#10487 ci: move some misc non-contrib suites to gitlab
  .circleci/config.templ.yml
  .gitlab/tests/core.yml
Labels: changelog/no-changelog

#10468 ci: migrate elasticsearch suite to GitLab
  .circleci/config.templ.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog

#10491 ci: remove slotscheck and conftests from circleci
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog, CI

#10490 chore(iast): further optimize the modulo operator aspect (2/3)
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectModulo.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
Labels: changelog/no-changelog, ASM

#10454 chore(ci_visibility): fix line numbers in Python 3.10 bytecode
  ddtrace/internal/coverage/instrumentation_py3_10.py
Labels: changelog/no-changelog

#10461 chore: MQ TEST udpate flare.py
  ddtrace/internal/flare/flare.py
Labels: changelog/no-changelog

#10502 ci: move contrib jobs to GitLab
  .circleci/config.templ.yml
  .gitlab/tests/contrib.yml
  tests/contrib/grpc/test_grpc.py
Labels: changelog/no-changelog

#10460 fix(ci_visibility): handle errors while fetching skippable test data
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci-visibility-handle-exception-in-tests-to-skip-675db3b857f8e232.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: backport 2.9, backport 2.10, backport 2.11, backport 2.12

#10494 ci: use mirrors testrunner and ddapm-test-agent
  .gitlab-ci.yml
  .gitlab/services.yml
Labels: changelog/no-changelog

#10506 chore(docs): update the contributing testing instructions for specific tests
  docs/contributing-testing.rst
Labels: changelog/no-changelog

#10507 fix(asm): improve fingerprinting stability
  releasenotes/notes/fingerprinting_stability-cfe856d1e09b6a20.yaml
Labels: bug, ASM

#10496 chore(profiling): test when WRAPT_DISABLED_EXTENSIONS is set
  .riot/requirements/1b559c7.txt
  .riot/requirements/1c31b2e.txt
  .riot/requirements/1e81c99.txt
  .riot/requirements/1ef847d.txt
  .riot/requirements/1fa5bd6.txt
  .riot/requirements/d6b8465.txt
  riotfile.py
  tests/profiling/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#10508 ci: revert "ci: migrate elasticsearch suite to GitLab (#10468)"
  .circleci/config.templ.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog, CI

#10499 chore(profiling): use ddtrace config instead of reading os.environ
  ddtrace/profiling/profiler.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog, Profiling

#10486 chore(iast): clean the code
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  tests/appsec/iast/aspects/test_split_aspect.py
Labels: changelog/no-changelog, ASM

#10493 fix(llmobs): keep custom trace filters in child processes
  ddtrace/llmobs/_llmobs.py
  releasenotes/notes/fix-llmobs-fork-custom-filters-5ba642f9395a0ddd.yaml
  tests/llmobs/test_llmobs_service.py
Labels: backport 2.11, backport 2.12

#10424 chore: update changelog for version 2.11.2
  CHANGELOG.md
Labels: changelog/no-changelog

#10489 ci: fix permissions for generate package versions action
  .github/workflows/generate-package-versions.yml
Labels: changelog/no-changelog, mergequeue-status: removed

#10484 chore(iast): fastapi path source
  ddtrace/appsec/_iast/_patch.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#10505 chore(iast): report instrumented metric for flask
  ddtrace/appsec/_handlers.py
  tests/appsec/integrations/test_flask_telemetry.py
Labels: changelog/no-changelog, ASM

#10523 chore(profiling): set libdd_required when timeline_enabled (#10182) [backport-2.11]
  ddtrace/settings/profiling.py
Labels: changelog/no-changelog, Profiling

#10495 ci: move some redis suites to gitlab
  .circleci/config.templ.yml
  .gitlab/services.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog

#10488 ci: move some snapshot suites to gitlab
  .circleci/config.templ.yml
  .gitlab/services.yml
  .gitlab/tests/contrib.yml
  riotfile.py
  tests/contrib/config.py
  tests/contrib/kafka/test_kafka.py
  tests/contrib/urllib3/test_urllib3.py
Labels: changelog/no-changelog

#10252 chore(telemetry): enablement refactor
  ddtrace/internal/telemetry/data.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/profiling/scheduler.py
  tests/integration/test_settings.py
  tests/telemetry/app.py
  tests/telemetry/test_data.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#10492 ci: add version to package update PRs
  .github/workflows/generate-package-versions.yml
  scripts/get_latest_version.py
Labels: changelog/no-changelog

#10541 ci: make pypi test upload actually upload [backport 2.12] (#10449)
  .gitlab/release.yml
Labels: changelog/no-changelog

#10527 chore(grpc): remove config for enabling grpcaio support
  .riot/requirements/10bb064.txt
  .riot/requirements/111ed90.txt
  .riot/requirements/12bf701.txt
  .riot/requirements/12d5b48.txt
  .riot/requirements/13d8f2b.txt
  .riot/requirements/15ba505.txt
  .riot/requirements/18f859e.txt
  .riot/requirements/1bbf463.txt
  .riot/requirements/1bcefe4.txt
  .riot/requirements/1cef696.txt
  .riot/requirements/1d8a1bf.txt
  .riot/requirements/1f238e9.txt
  .riot/requirements/1f8f136.txt
  .riot/requirements/1feb806.txt
  .riot/requirements/3d84480.txt
  .riot/requirements/51c004c.txt
  .riot/requirements/5a0532b.txt
  .riot/requirements/5b82761.txt
  .riot/requirements/9a13b9a.txt
  .riot/requirements/a42e1fb.txt
  .riot/requirements/d68f919.txt
  .riot/requirements/f73b199.txt
  ddtrace/contrib/internal/grpc/patch.py
Labels: changelog/no-changelog

#10538 chore(profiling): venvs to test profiler v2
  .github/CODEOWNERS
  .gitlab/tests/profiling.yml
  .riot/requirements/11f3e97.txt
  .riot/requirements/131588c.txt
  .riot/requirements/14135e2.txt
  .riot/requirements/146c75e.txt
  .riot/requirements/14aae80.txt
  .riot/requirements/14c79d8.txt
  .riot/requirements/15103d9.txt
  .riot/requirements/16795af.txt
  .riot/requirements/1812397.txt
  .riot/requirements/1a66299.txt
  .riot/requirements/1f31244.txt
  .riot/requirements/3725aba.txt
  .riot/requirements/4b27be0.txt
  .riot/requirements/4ee9c38.txt
  .riot/requirements/5965bcc.txt
  .riot/requirements/7c55cd2.txt
  .riot/requirements/908fc42.txt
  .riot/requirements/aef0d14.txt
  .riot/requirements/c6a8c83.txt
  .riot/requirements/f16d548.txt
  riotfile.py
  tests/.suitespec.json
  tests/profiling-v2/__init__.py
  tests/profiling-v2/exporter/__init__.py
  tests/profiling-v2/exporter/test_ddup.py
  tests/profiling/test_profiler.py
Labels: changelog/no-changelog, Profiling

#10542 ci: update required backport workflow permissions
  .github/workflows/backport.yml
Labels: changelog/no-changelog

#10513 ci: moved unittest config to Gitlab
  .circleci/config.templ.yml
  .gitlab/tests/contrib.yml
  riotfile.py
  tests/contrib/unittest/test_unittest_snapshot.py
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly_with_skipped.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_source_file_data.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_multiple_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_custom_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_lines_pct.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped_multiple.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_skip_invalid_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_skip_unskippable_test_if_skip_decorator.json
Labels: changelog/no-changelog

#10425 chore(test_visibility): rename and privatize CI Visibility API to Test Visibility
  .github/CODEOWNERS
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_utils.py
  ddtrace/ext/ci_visibility/__init__.py
  ddtrace/ext/ci_visibility/_utils.py
  ddtrace/ext/ci_visibility/api.py
  ddtrace/ext/test_visibility/__init__.py
  ddtrace/ext/test_visibility/_item_ids.py
  ddtrace/ext/test_visibility/_test_visibility_base.py
  ddtrace/ext/test_visibility/_utils.py
  ddtrace/ext/test_visibility/api.py
  ddtrace/internal/ci_visibility/__init__.py
  ddtrace/internal/ci_visibility/api/__init__.py
  ddtrace/internal/ci_visibility/api/_base.py
  ddtrace/internal/ci_visibility/api/_coverage_data.py
  ddtrace/internal/ci_visibility/api/_module.py
  ddtrace/internal/ci_visibility/api/_session.py
  ddtrace/internal/ci_visibility/api/_suite.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/coverage/code.py
  ddtrace/internal/coverage/instrumentation_py3_10.py
  ddtrace/internal/coverage/instrumentation_py3_11.py
  ddtrace/internal/coverage/instrumentation_py3_12.py
  ddtrace/internal/coverage/instrumentation_py3_7.py
  ddtrace/internal/coverage/instrumentation_py3_8.py
  ddtrace/internal/coverage/multiprocessing_coverage.py
  ddtrace/internal/test_visibility/_utils.py
  ddtrace/internal/test_visibility/api.py
  ddtrace/internal/test_visibility/coverage_lines.py
  tests/.suitespec.json
  tests/ci_visibility/api/fake_runner_all_fail.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_suite_level.py
  tests/ci_visibility/api/fake_runner_all_itr_skip_test_level.py
  tests/ci_visibility/api/fake_runner_all_pass.py
  tests/ci_visibility/api/fake_runner_all_skip.py
  tests/ci_visibility/api/fake_runner_mix_fail.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_suite_level.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_test_level.py
  tests/ci_visibility/api/fake_runner_mix_pass.py
  tests/ci_visibility/api/test_ext_ci_visibility_api.py
  tests/ci_visibility/api/test_ext_test_visibility_api.py
  tests/ci_visibility/api/test_internal_ci_visibility_api.py
  tests/ci_visibility/api/test_internal_test_visibility_api.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/util.py
  tests/contrib/pytest/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_skip.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_pass.json
Labels: changelog/no-changelog

#10526 ci: add permissions to auto-generate pr workflow
  .github/workflows/generate-package-versions.yml
Labels: changelog/no-changelog

#10537 ci: move many suites with no service dependencies to gitlab from circleci
  .circleci/config.templ.yml
  .gitlab/tests.yml
  .gitlab/tests/contrib.yml
  .gitlab/tests/debugging.yml
Labels: changelog/no-changelog

#10427 ci: set build parallel level for hatch based tests
  hatch.toml
Labels: changelog/no-changelog

#10332 fix(llmobs): don't default session id to trace id for llm obs span events
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_trace_processor.py
  ddtrace/llmobs/_utils.py
  releasenotes/notes/llmobs-stop-defaulting-session-id-55c0dfaf1fe5448b.yaml
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_llmobs_trace_processor.py
Labels: backport 2.11, backport 2.12

#10539 ci: moved pymongo from circleci to gitlab
  .circleci/config.templ.yml
  .gitlab/services.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog

#10501 docs: update contributing-integrations.rst
  docs/contributing-integrations.rst
Labels: changelog/no-changelog

#10547 ci: update codeowners for gitlab suites
  .github/CODEOWNERS
  .gitlab/tests.yml
  .gitlab/tests/contrib.yml
  .gitlab/tests/llmobs.yml
Labels: changelog/no-changelog

#10543 chore(telemetry): implement app-product-change event
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/debugging/_debugger.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/profiling/profiler.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#10553 chore(ci_visibility): add get_path_codeowners event handler
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/test_visibility/api.py
Labels: changelog/no-changelog

#10556 fix(ci_visibility): properly strip .git from repo URL when getting repo name
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci_visibility-fix_properly_strip_dotgit_from_repo_url-523a908075aea559.yaml
  tests/ci_visibility/test_ci_visibility.py
Labels: backport 2.9, backport 2.10, backport 2.11, backport 2.12

#10551 chore(ci_visibility): pytest set parameters during runtest_protocol
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/contrib/pytest/_utils.py
  ddtrace/ext/test_visibility/api.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/api/fake_runner_mix_pass.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_pass.json
Labels: changelog/no-changelog

#10552 chore(ci_visibility): add percent-line-covered event to internal test API
  ddtrace/contrib/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/api/_session.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/test_visibility/api.py
  tests/ci_visibility/api/fake_runner_mix_fail_itr_suite_level.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_suite_level.json
Labels: changelog/no-changelog

#10534 chore(ci): use unified Gitlab pipeline for APM libraries [backport 2.12]
  .github/workflows/build_deploy.yml
  .gitlab-ci.yml
Labels: changelog/no-changelog

#10546 ci: migrate elasticsearch suite to GitLab
  .circleci/config.templ.yml
  .gitlab/services.yml
  .gitlab/tests/contrib.yml
  tests/contrib/config.py
  tests/contrib/elasticsearch/test_async.py
  tests/contrib/elasticsearch/test_elasticsearch.py
  tests/contrib/elasticsearch/test_elasticsearch_multi.py
  tests/contrib/elasticsearch/test_opensearch.py
Labels: changelog/no-changelog

#10441 chore(asm): use byte pointer instead of c_char_p (#10428)
  ddtrace/appsec/_ddwaf/ddwaf_types.py
Labels: enhancement, changelog/no-changelog, ASM

#10532 chore(ci): use unified Gitlab pipeline for APM libraries [backport 2.10]
  .github/workflows/build_deploy.yml
  .github/workflows/lib-inject-publish.yml
  .github/workflows/lib-injection.yml
  .gitlab-ci.yml
  .gitlab/build-deb-rpm.sh
  .gitlab/build-lib-init.sh
  .gitlab/build-oci.sh
  .gitlab/download-dependency-wheels.sh
  .gitlab/download-wheels-from-gh-actions.sh
  .gitlab/prepare-oci-package.sh
  lib-injection/Dockerfile
  lib-injection/copy-lib.sh
  lib-injection/dl_wheels.py
Labels: changelog/no-changelog

#10529 chore(ci): use unified Gitlab pipeline for APM libraries [backport 2.9]
  .github/workflows/build_deploy.yml
  .github/workflows/lib-inject-publish.yml
  .github/workflows/lib-injection.yml
  .gitlab-ci.yml
  .gitlab/build-deb-rpm.sh
  .gitlab/build-lib-init.sh
  .gitlab/build-oci.sh
  .gitlab/download-dependency-wheels.sh
  .gitlab/download-wheels-from-gh-actions.sh
  .gitlab/prepare-oci-package.sh
  lib-injection/Dockerfile
  lib-injection/copy-lib.sh
  lib-injection/dl_wheels.py
Labels: changelog/no-changelog

#10533 chore(ci): use unified Gitlab pipeline for APM libraries [backport 2.11]
  .github/workflows/build_deploy.yml
  .gitlab-ci.yml
Labels: changelog/no-changelog

#10524 ci: stop xfailing "did not receive expected traces" errors from testagent
  tests/contrib/asyncpg/test_asyncpg.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/django/test_django_snapshots.py
  tests/integration/test_integration_snapshots.py
  tests/utils.py
Labels: changelog/no-changelog

#10575 fix(profiling): stack_v2 properly tracks Threading [backport-2.10]
  ddtrace/internal/datadog/profiling/stack_v2/include/sampler.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/collector/threading.py
Labels: changelog/no-changelog, Profiling

#10573 Revert "feat(openai): add `model` tag for openai metrics for consistency with openai saas integration [backport 2.11]"
  ddtrace/llmobs/_integrations/openai.py
  releasenotes/notes/openai-model-tag-2482b3d5b2905db9.yaml
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog

#10572 Revert "feat(openai): add `model` tag for openai metrics for consistency with openai saas integration [backport 2.10]"
  ddtrace/llmobs/_integrations/openai.py
  releasenotes/notes/openai-model-tag-2482b3d5b2905db9.yaml
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: changelog/no-changelog

#10509 chore: update changelog for version 2.11.3
  CHANGELOG.md
Labels: changelog/no-changelog

#10568 chore: update changelog for version 2.12.0
  CHANGELOG.md
Labels: changelog/no-changelog

#10577 chore: update changelog for version 2.11.4
  CHANGELOG.md
Labels: changelog/no-changelog

#10531 chore: add retry for appsec, profiling, and tracer gitlab jobs
  .gitlab/tests/appsec.yml
  .gitlab/tests/profiling.yml
  .gitlab/tests/tracer.yml
Labels: changelog/no-changelog

#10336 ci: system-tests not stopping on failure
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI, backport 2.10, backport 2.11, backport 2.12

#10586 fix(iast): avoid potencial attribute error raise errors
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  releasenotes/notes/iast-fix-iast-import-error-f26e1451571ecbae.yaml
  tests/contrib/django/test_django_appsec_snapshots.py
Labels: ASM, backport 2.10, backport 2.11, backport 2.12

#10459 chore(cicd): update django requirements files
  .riot/requirements/11065bb.txt
  .riot/requirements/16ae097.txt
  .riot/requirements/1d3001d.txt
  .riot/requirements/1ef9f39.txt
  .riot/requirements/1f8ac1c.txt
  .riot/requirements/1fe2c8e.txt
  .riot/requirements/26ee64c.txt
  .riot/requirements/2848d2c.txt
  .riot/requirements/adb0290.txt
  .riot/requirements/bbb3af0.txt
  .riot/requirements/cbc433f.txt
  .riot/requirements/ce6cd33.txt
  .riot/requirements/d57247c.txt
  .riot/requirements/d5fcd88.txt
Labels: changelog/no-changelog

#10583 chore(telemetry): force agentless telemetry client for llmobs
  ddtrace/llmobs/_llmobs.py
Labels: changelog/no-changelog

#10576 ci: ensure suite names match venvs
  .circleci/config.templ.yml
  .gitlab/tests.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog

#10230 chore(profiling): tests libdatadog exporter for lock collector
  .riot/requirements/12526ba.txt
  .riot/requirements/13e7fea.txt
  .riot/requirements/162ded5.txt
  .riot/requirements/167dd48.txt
  .riot/requirements/1744bab.txt
  .riot/requirements/18598d3.txt
  .riot/requirements/18d2618.txt
  .riot/requirements/19c7eaf.txt
  .riot/requirements/1aecc60.txt
  .riot/requirements/1e17619.txt
  .riot/requirements/1e185ef.txt
  .riot/requirements/1f484c3.txt
  .riot/requirements/5286dd4.txt
  .riot/requirements/7f8c636.txt
  .riot/requirements/8a0f886.txt
  .riot/requirements/ab034bd.txt
  .riot/requirements/ac92a08.txt
  .riot/requirements/c214c08.txt
  .riot/requirements/d6c4509.txt
  .riot/requirements/d79db4d.txt
  riotfile.py
  tests/profiling-v2/collector/test_threading.py
  tests/profiling-v2/collector/test_threading_asyncio.py
  tests/profiling/collector/global_locks.py
  tests/profiling/collector/lock_utils.py
  tests/profiling/collector/pprof_utils.py
  tests/profiling/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#10596 chore(asm): use parameternamelength for libddwaf interface
  ddtrace/appsec/_ddwaf/ddwaf_types.py
Labels: enhancement, changelog/no-changelog, ASM, backport 2.11, backport 2.12

#10588 fix(oci): include deny_executables.txt source into oci package
  .gitlab/prepare-oci-package.sh
  lib-injection/sources/denied_executables.txt
  lib-injection/sources/min_compatible_versions.csv
  lib-injection/sources/sitecustomize.py
  lib-injection/sources/telemetry-forwarder.sh
  releasenotes/notes/fix-oci-denylist-080592ca52e45681.yaml
Labels: backport 2.11, backport 2.12

#10581 ci: move sourcecode tests to gitlab
  .circleci/config.templ.yml
  .gitlab/tests/contrib.yml
  tests/sourcecode/test_source_code_link.py
Labels: changelog/no-changelog

#10602 ci: move suites that use memcached to gitlab
  .circleci/config.templ.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog

#10536 ci: modify logic for updating packages
  scripts/freshvenvs.py
Labels: changelog/no-changelog

#10582 chore(profiling): asyncio lock collector tests with libdatadog exporter
  tests/profiling-v2/collector/test_asyncio.py
  tests/profiling/collector/pprof_utils.py
Labels: changelog/no-changelog, Profiling

#10616 chore: alphabetize .gitlab/tests/contrib.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog

#10622 feat(profiling): captures `asyncio.Lock` usages with `with` context managers
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-asyncio-lock-with-ef209edcdd346093.yaml
  tests/profiling-v2/collector/test_asyncio.py
  tests/profiling/collector/test_asyncio.py
Labels: Profiling

#10615 ci: fix release publish step missing aws command
  .gitlab/release.yml
Labels: changelog/no-changelog, backport 2.12

#10590 fix(iast): avoid potencial attribute error raise errors [backport 2.11]
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  releasenotes/notes/iast-fix-iast-import-error-f26e1451571ecbae.yaml
  tests/contrib/django/test_django_appsec_snapshots.py
Labels: ASM

#10591 fix(iast): avoid potencial attribute error raise errors [backport 2.10]
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  releasenotes/notes/iast-fix-iast-import-error-f26e1451571ecbae.yaml
  tests/contrib/django/test_django_appsec_snapshots.py
Labels: ASM

#10592 fix(iast): avoid potencial attribute error raise errors [backport 2.9]
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  releasenotes/notes/iast-fix-iast-import-error-f26e1451571ecbae.yaml
  tests/contrib/django/test_django_appsec_snapshots.py
Labels: ASM

#10614 ci: update parallelism for ddtracerun job
  .gitlab/tests/core.yml
Labels: changelog/no-changelog

#10611 ci: move django tests from CircleCI to GitLab
  .gitlab/services.yml
  .gitlab/tests/appsec.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog

#10629 fix(lib-injection): ignore attrs in min versions
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  releasenotes/notes/attrs-libinject-ec10d2e8ad9ef34b.yaml
  scripts/min_compatible_versions.py
Labels: backport 2.11, backport 2.12, backport 2.13

#10636 chore(profiling): fix a flaky test
  tests/profiling-v2/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#10515 chore: enable `merge_group` trigger for status checks required in merge queue
  .github/workflows/build_python_3.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
  .github/workflows/pypa_musllinux_1_2_i686.yml
  .github/workflows/requirements-locks.yml
  .github/workflows/rust-ci.yml
  .github/workflows/system-tests.yml
  .github/workflows/test_frameworks.yml
  .github/workflows/testrunner.yml
  .github/workflows/unit_tests.yml
Labels: changelog/no-changelog

#10635 chore: update changelog for version 2.11.6
  CHANGELOG.md
Labels: changelog/no-changelog

#10601 ci: move suites that use httpbin_local to gitlab from circleci
  .circleci/config.templ.yml
  .gitlab/tests/contrib.yml
  tests/contrib/aiohttp/test_aiohttp_client.py
  tests/contrib/requests/test_requests.py
Labels: changelog/no-changelog

#10503 feat(gemini): trace google gemini Integration
  .github/CODEOWNERS
  .gitlab/tests/llmobs.yml
  .riot/requirements/1e15a25.txt
  .riot/requirements/1f54e6b.txt
  .riot/requirements/e8247d6.txt
  .riot/requirements/ebe4ea5.txt
  ddtrace/_monkey.py
  ddtrace/contrib/google_generativeai/__init__.py
  ddtrace/contrib/internal/anthropic/_streaming.py
  ddtrace/contrib/internal/anthropic/patch.py
  ddtrace/contrib/internal/anthropic/utils.py
  ddtrace/contrib/internal/google_generativeai/_utils.py
  ddtrace/contrib/internal/google_generativeai/patch.py
  ddtrace/llmobs/_integrations/__init__.py
  ddtrace/llmobs/_integrations/anthropic.py
  ddtrace/llmobs/_integrations/gemini.py
  ddtrace/llmobs/_utils.py
  docs/index.rst
  docs/integrations.rst
  docs/spelling_wordlist.txt
  releasenotes/notes/feat-google-gemini-d5ee30b1d711bc08.yaml
  riotfile.py
  tests/.suitespec.json
  tests/contrib/google_generativeai/__init__.py
  tests/contrib/google_generativeai/conftest.py
  tests/contrib/google_generativeai/test_data/apple.jpg
  tests/contrib/google_generativeai/test_google_generativeai.py
  tests/contrib/google_generativeai/test_google_generativeai_patch.py
  tests/contrib/google_generativeai/utils.py
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_error.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_image.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_multiple_messages.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_stream.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_system_prompt.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_tool_stream.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_tool_chat_completion.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_tool_completion.json
Labels: backport 2.13

#10619 feat(llmobs): submit llmobs payloads from gemini integration
  ddtrace/contrib/google_generativeai/__init__.py
  ddtrace/contrib/internal/google_generativeai/_utils.py
  ddtrace/contrib/internal/google_generativeai/patch.py
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/gemini.py
  ddtrace/llmobs/_utils.py
  releasenotes/notes/feat-llmobs-gemini-b65c714ceef9eb12.yaml
  tests/contrib/google_generativeai/conftest.py
  tests/contrib/google_generativeai/test_google_generativeai_llmobs.py
  tests/llmobs/_utils.py
Labels: backport 2.13

#10631 chore(ci_visibility): fix unittest tests
  tests/ci_visibility/util.py
  tests/contrib/unittest/test_unittest_snapshot.py
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly_with_skipped.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_source_file_data.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_multiple_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_custom_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_lines_pct.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped_multiple.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_skip_invalid_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_skip_unskippable_test_if_skip_decorator.json
  tests/utils.py
Labels: changelog/no-changelog, CI App, CI

#10594 chore: [SVLS-5261] change Span._links to a list
  ddtrace/_trace/span.py
  ddtrace/internal/_encoding.pyx
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/starlette/test_starlette.py
  tests/opentelemetry/test_trace.py
  tests/tracer/test_encoders.py
  tests/tracer/test_propagation.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#10646 chore(iast): fix `tomli` iast propagation
  ddtrace/appsec/_iast/_ast/ast_patching.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#10540 chore(iast): ast deny list
  ddtrace/appsec/_iast/_ast/ast_patching.py
Labels: changelog/no-changelog, ASM

#10564 ci: move ci visibility tests to GitLab
  .circleci/config.templ.yml
  .gitlab/tests.yml
  .gitlab/tests/ci_visibility.yml
  .gitlab/tests/contrib.yml
  ddtrace/ext/test_visibility/_test_visibility_base.py
  ddtrace/ext/test_visibility/api.py
  ddtrace/internal/ci_visibility/api/_base.py
  ddtrace/internal/ci_visibility/api/_coverage_data.py
  ddtrace/internal/ci_visibility/git_client.py
  tests/ci_visibility/api/test_api_fake_runners.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/util.py
  tests/contrib/pytest/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest/test_pytest_snapshot.py
  tests/contrib/pytest/test_pytest_snapshot_v2.py
  tests/contrib/unittest/test_unittest_snapshot.py
  tests/integration/test_integration_civisibility.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_skip.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_test_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_pass.json
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot.test_pytest_will_include_lines_pct.json
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot.test_pytest_with_ddtrace_patch_all.json
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot.test_pytest_wont_include_lines_pct_if_report_empty.json
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot_v2.test_pytest_will_include_lines_pct.json
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot_v2.test_pytest_with_ddtrace_patch_all.json
  tests/snapshots/tests.contrib.pytest.test_pytest_snapshot_v2.test_pytest_wont_include_lines_pct_if_report_empty.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_coverage_correctly_with_skipped.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_generates_source_file_data.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_multiple_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_custom_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_include_lines_pct.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_report_coverage_by_test_with_itr_skipped_multiple.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_skip_invalid_unskippable_tests.json
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_skip_unskippable_test_if_skip_decorator.json
  tests/utils.py
Labels: changelog/no-changelog

#10651 chore(iast): improve check of module names for deny and allow lists
  ddtrace/appsec/_iast/_ast/ast_patching.py
Labels: changelog/no-changelog, ASM

#10600 chore(iast): add google testing for the native IAST module
  .gitlab/tests/appsec.yml
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/clean.sh
  ddtrace/appsec/_iast/_taint_tracking/tests/CMakeLists.txt
  ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_stringutils.cpp
  hatch.toml
  tests/.suitespec.json
  tests/appsec/iast/aspects/test_aspect_helpers.py
Labels: changelog/no-changelog, ASM

#10465 chore(iast): add more leak testing to CI
  .gitlab/tests/appsec.yml
  hatch.toml
  scripts/iast/mod_leak_functions.py
  scripts/iast/test_leak_functions.py
  tests/appsec/iast_aggregated_memcheck/__init__.py
  tests/appsec/iast_aggregated_memcheck/test_aggregated_memleaks.py
Labels: changelog/no-changelog, ASM

#10653 chore(iast): fastapi body
  ddtrace/appsec/_iast/_patch.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#10610 chore: update changelog for version 2.11.5
  CHANGELOG.md
Labels: changelog/no-changelog

#10658 fix(postgres): remove require modules to resolve circular imports
  ddtrace/contrib/psycopg/__init__.py
  releasenotes/notes/fix-postgres-circular-req-0904bf22c32c785d.yaml
Labels: backport 2.12, backport 2.13

#10621 feat(tracer): [SVLS-5261] private Span Pointers
  ddtrace/_trace/_span_link.py
  ddtrace/_trace/span.py
  tests/tracer/test_encoders.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#10680 chore: easier memleak testing so gitlab does not timeout
  .gitlab/tests/appsec.yml
  hatch.toml
  scripts/iast/test_leak_functions.py
  tests/appsec/iast_aggregated_memcheck/test_aggregated_memleaks.py
Labels: changelog/no-changelog, ASM

#10640 ci: move suites that use rabbitmq from circleci to gitlab
  .circleci/config.templ.yml
  .gitlab/services.yml
  .gitlab/tests/contrib.yml
Labels: changelog/no-changelog

#10659 fix(anthropic): safely json dump unserializable objects
  ddtrace/contrib/internal/anthropic/patch.py
  ddtrace/contrib/internal/anthropic/utils.py
  releasenotes/notes/fix-anthroipc-json-serializable-99af0985bd967e5d.yaml
  tests/contrib/anthropic/test_anthropic.py
  tests/snapshots/tests.contrib.anthropic.test_anthropic.test_anthropic_llm_unserializable_arg.json
Labels: backport 2.10, backport 2.11, backport 2.12, backport 2.13

#10682 chore: prefer `docker compose` instead of older `docker-compose`
  docs/contributing-integrations.rst
  docs/contributing-testing.rst
  docs/contributing.rst
  lib-injection/README.md
  scripts/ddtest
Labels: changelog/no-changelog

#10679 chore(asm): small rasp test improvement
  hatch.toml
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#10695 chore(tracer): fix version computation for 2.13 for system tests
  pyproject.toml
Labels: changelog/no-changelog

#10696 chore(tracer): fix version computation for 2.12 for system tests
  pyproject.toml
Labels: changelog/no-changelog

#10697 chore(tracer): fix version computation for 2.11 for system tests
  pyproject.toml
Labels: changelog/no-changelog

#10668 chore(iast): python debug dockerfile update
  docker/Dockerfile_py311_debug_mode
  scripts/iast/.env
  scripts/iast/run_memory.sh
  scripts/iast/run_memray.sh
  scripts/iast/run_references.sh
  scripts/iast/test_references.py
Labels: changelog/no-changelog, ASM

#10681 chore(llmobs): add language tag to span events
  ddtrace/llmobs/_trace_processor.py
  tests/llmobs/_utils.py
Labels: changelog/no-changelog, backport 2.9, backport 2.10, backport 2.11, backport 2.12, backport 2.13

#10667 chore(iast): update appsec_iast_memcheck tests
  .gitlab/tests/appsec.yml
  .riot/requirements/13a28e1.txt
  .riot/requirements/1463f80.txt
  .riot/requirements/1548fc3.txt
  .riot/requirements/16ae641.txt
  .riot/requirements/17a7e5e.txt
  .riot/requirements/185c81b.txt
  .riot/requirements/1bbfc54.txt
  .riot/requirements/5aff90d.txt
  .riot/requirements/d0652fb.txt
  hatch.toml
  riotfile.py
Labels: changelog/no-changelog, ASM

#10674 ci: add test visibility instrumentation to GitLab with pytest plugin
  .circleci/config.templ.yml
  .github/workflows/testrunner.yml
  .gitlab-ci.yml
  .gitlab/tests.yml
  ddtrace/internal/agent.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/writer.py
  docker/Dockerfile
  riotfile.py
  tests/ci_visibility/test_ci_visibility.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog, CI App, CI, curse

#10707 feat(llmobs): make model_provider client-specific for the OpenAI integration
  ddtrace/llmobs/_integrations/openai.py
  releasenotes/notes/feat-openai-azure-23cf45cfa854a5e5.yaml
  tests/contrib/openai/test_openai_llmobs.py
Labels: changelog/no-changelog

#10698 chore(iast): add some re functions to leak tests
  scripts/iast/mod_leak_functions.py
  scripts/iast/test_leak_functions.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#10683 chore(profiling): rename profiling-v2 to profiling_v2
  .github/CODEOWNERS
  riotfile.py
  tests/.suitespec.json
  tests/profiling_v2/__init__.py
  tests/profiling_v2/collector/test_asyncio.py
  tests/profiling_v2/collector/test_threading.py
  tests/profiling_v2/collector/test_threading_asyncio.py
  tests/profiling_v2/exporter/__init__.py
  tests/profiling_v2/exporter/test_ddup.py
Labels: changelog/no-changelog, Profiling

#10717 feat(tracer): [SVLS-5262] private Span Pointer Description
  ddtrace/_trace/_span_pointer.py
Labels: changelog/no-changelog

#10687 chore: [SVLS-5262] Span Pointer standard hashing
  ddtrace/_trace/_span_pointer.py
  tests/tracer/test_span_pointers.py
Labels: changelog/no-changelog

#10694 fix(llmobs): safely handle non-json serializable arguments
  ddtrace/contrib/internal/anthropic/utils.py
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/llmobs/_integrations/anthropic.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/gemini.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/openai.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_utils.py
  releasenotes/notes/fix-llmobs-safe-json-4aee3aacf05fd69f.yaml
  tests/contrib/anthropic/test_anthropic.py
  tests/contrib/anthropic/test_anthropic_llmobs.py
  tests/contrib/langchain/test_langchain_community.py
  tests/contrib/openai/test_openai_llmobs.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_utils.py
  tests/snapshots/tests.contrib.anthropic.test_anthropic.test_anthropic_llm_unserializable_arg.json
  tests/snapshots/tests.contrib.langchain.test_langchain_community.test_base_tool_invoke_non_json_serializable_config.json
Labels: backport 2.12, backport 2.13

#10712 fix(llmobs): ensure integration metrics are disabled in agentless mode
  ddtrace/llmobs/_integrations/base.py
  releasenotes/notes/fix-llm-integrations-metrics-default-bc597eb5a5218b32.yaml
  tests/llmobs/test_llmobs_integrations.py
Labels: backport 2.11, backport 2.12, backport 2.13

#10720 chore(crashtracking): add python version to crashtracker tags
  ddtrace/internal/core/crashtracking.py
Labels: changelog/no-changelog, backport 2.11, backport 2.12, backport 2.13

#10724 ci: skip profiling test_memalloc_no_init_error_on_fork in GitLab
  tests/profiling/test_main.py
Labels: changelog/no-changelog

#10689 chore: [SVLS-5262] AWS S3 PutObject pointer calc
  ddtrace/_trace/utils_botocore/__init__.py
  ddtrace/_trace/utils_botocore/span_pointers.py
  tests/tracer/utils_botocore/__init__.py
  tests/tracer/utils_botocore/test_span_pointers.py
Labels: changelog/no-changelog

#10699 ci: add system-tests finished job
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#10715 chore: lower the cmake paralellism level for build_base_venvs
  .gitlab/package.yml
Labels: changelog/no-changelog, ASM

#10706 chore(iast): native module safety improvements
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectsOsPath.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/CMakeLists.txt
  ddtrace/appsec/_iast/_taint_tracking/tests/test_common.hpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_stringutils.cpp
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
Labels: changelog/no-changelog, ASM

#10593 chore(iast): re.match getitem aspect
  benchmarks/appsec_iast_aspects/config.yaml
  benchmarks/bm/iast_fixtures/str_methods.py
  benchmarks/bm/iast_utils/aspects_benchmarks_generate.py
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  scripts/iast/mod_leak_functions.py
  scripts/iast/test_leak_functions.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#10736 fix(iast): backport fix from 10706 to 2.12
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  releasenotes/notes/initializer-atexit-6f9a025488fe14b4.yaml
Labels: ASM

#10738 fix(iast): backport fix from 10706 to 2.10
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  releasenotes/notes/initializer-atexit-b353744cf1af7917.yaml
Labels: ASM

#10739 fix(iast): backport fix from 10706 to 2.9
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  releasenotes/notes/initializer-atexit-a04b2c908d3e8eeb.yaml
Labels: ASM

#10737 fix(iast): backport fix from 10706 to 2.11
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
  releasenotes/notes/initializer-atexit-4c10671e585ac3e7.yaml
Labels: ASM

#10670 chore: system-tests integrations and messaging tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#10760 ci: move PyPI artifact uploading to GitLab
  .github/workflows/build_deploy.yml
  .gitlab/release.yml
Labels: changelog/no-changelog

#10718 feat(pymongo): add support for v4.9
  .riot/requirements/10a00e7.txt
  .riot/requirements/1424e42.txt
  .riot/requirements/14e85f3.txt
  .riot/requirements/16cae33.txt
  .riot/requirements/1ce9a99.txt
  .riot/requirements/1ed6ce0.txt
  .riot/requirements/328b28c.txt
  .riot/requirements/ad40916.txt
  .riot/requirements/b089663.txt
  .riot/requirements/b344fed.txt
  .riot/requirements/de53117.txt
  .riot/requirements/f9d0e8e.txt
  ddtrace/contrib/internal/pymongo/patch.py
  releasenotes/notes/pymong-4-9-support-83f7c613e5e009e6.yaml
  riotfile.py
Labels: changelog/no-changelog

#10742 chore(iast): add re.match with an index to the leak testing script
  scripts/iast/mod_leak_functions.py
Labels: changelog/no-changelog, ASM

#10710 fix(llmobs): recreate eval metric writer on fork
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  releasenotes/notes/fix-llmobs-forked-eval-metric-writer-55d50d1ed8fc10ea.yaml
  tests/llmobs/test_llmobs_service.py
Labels: backport 2.12, backport 2.13, backport 2.14

#10745 chore(pymongo): add testing to pymongo patch
  tests/contrib/patch.py
  tests/contrib/pymongo/test.py
  tests/contrib/pymongo/test_pymongo_patch.py
Labels: changelog/no-changelog

#10713 fix(llmobs): avoid raising errors during llmobs integration span processing
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/anthropic/_streaming.py
  ddtrace/contrib/internal/anthropic/patch.py
  ddtrace/contrib/internal/google_generativeai/_utils.py
  ddtrace/contrib/internal/google_generativeai/patch.py
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/contrib/internal/openai/_endpoint_hooks.py
  ddtrace/contrib/internal/openai/utils.py
  ddtrace/llmobs/_integrations/anthropic.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/gemini.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/openai.py
  releasenotes/notes/fix-llmobs-integrations-safe-tagging-5e170868e5758510.yaml
  tests/llmobs/test_llmobs_integrations.py
Labels: backport 2.11, backport 2.12, backport 2.13

#10612 ci: update which packages to select for update
  scripts/freshvenvs.py
Labels: changelog/no-changelog

#10755 chore(iast): create a context guard for pausing Python errors
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.h
  ddtrace/appsec/_iast/_taint_tracking/Utils/PythonErrorGuard.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/PythonErrorGuard.h
  ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
Labels: changelog/no-changelog, ASM

#10753 chore(iast): missing iast microbenchmarks
  benchmarks/appsec_iast_aspects/config.yaml
Labels: changelog/no-changelog, ASM

#10770 chore(iast): fix C format
  ddtrace/appsec/_iast/_taint_tracking/Utils/PythonErrorGuard.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/PythonErrorGuard.h
  ddtrace/appsec/_iast/_taint_tracking/tests/test_helpers.cpp
Labels: changelog/no-changelog, ASM

#10686 chore(iast): bytesio, stringio and read aspects
  benchmarks/appsec_iast_aspects/config.yaml
  benchmarks/bm/iast_fixtures/str_methods.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/StringUtils.h
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/app.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/fixtures/ast/io/function_bytesio.py
  tests/appsec/iast/fixtures/ast/io/function_stringio.py
  tests/appsec/iast/fixtures/ast/io/module_bytesio.py
  tests/appsec/iast/fixtures/ast/io/module_read.py
  tests/appsec/iast/fixtures/ast/io/module_stringio.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
  tests/appsec/integrations/test_flask_iast_patching.py
Labels: changelog/no-changelog, ASM

#10669 chore(ci_visibility): use two-pass procedure for code instrumentation in Python 3.10
  ddtrace/internal/coverage/instrumentation_py3_10.py
Labels: changelog/no-changelog

#10649 fix(profiling): enable endpoint profiling using libdatadog exporter
  ddtrace/internal/datadog/profiling/dd_wrapper/include/ddup_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/libdatadog_helpers.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyi
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/internal/datadog/profiling/ddup/test/interface.py
  ddtrace/internal/processor/endpoint_call_counter.py
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/stack.pyx
  ddtrace/profiling/exporter/http.py
  releasenotes/notes/profiling-libdatadog-endpoint-b4dd576009754cbd.yaml
  tests/profiling/collector/pprof_utils.py
  tests/profiling_v2/collector/test_asyncio.py
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/collector/test_threading.py
  tests/tracer/test_processors.py
Labels: Profiling, backport 2.10, backport 2.11, backport 2.12, backport 2.13

#10773 ci: build wheels continue-on-error
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, CI

#10780 chore(llmobs): fix omitted test assertion from backport #10694 to 2.13
  tests/contrib/openai/test_openai_llmobs.py
Labels: changelog/no-changelog

#10782 chore: run clang-format for 2.10 branch
  ddtrace/appsec/_iast/_taint_tracking/_native.cpp
Labels: changelog/no-changelog

#10716 chore(tracer): core additions
  ddtrace/_trace/trace_handlers.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/internal/core/__init__.py
  tests/internal/test_context_events_api.py
Labels: enhancement, changelog/no-changelog

#10775 chore(iast): fastapi body [backport 2.13]
  .riot/requirements/108f9cf.txt
  .riot/requirements/1322180.txt
  .riot/requirements/134c543.txt
  .riot/requirements/13f7667.txt
  .riot/requirements/16759fe.txt
  .riot/requirements/1912989.txt
  .riot/requirements/1b7df87.txt
  .riot/requirements/1d3d3db.txt
  .riot/requirements/22fdd8b.txt
  .riot/requirements/41b3223.txt
  .riot/requirements/5a5524a.txt
  .riot/requirements/71adece.txt
  .riot/requirements/ee3bb72.txt
  .riot/requirements/f709b80.txt
  .riot/requirements/f823b38.txt
  .riot/requirements/fa3a84d.txt
  ddtrace/appsec/_iast/_patch.py
  riotfile.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM
