Repository DataDog/dd-trace-py, pull requests merged in 2025-09, with the labels that each got.

#14447 ci: use prebuilt wheels in system-tests
  .github/workflows/system-tests.yml
  .gitlab-ci.yml
Labels: changelog/no-changelog

#14461 chore(ci): fixing ci by updating system tests version
  .github/workflows/system-tests.yml
  .gitlab-ci.yml
Labels: changelog/no-changelog

#14348 chore(ci_visibility): replace weak dicts with regular dicts
  ddtrace/contrib/internal/pytest/_utils.py
Labels: changelog/no-changelog

#14480 ci(llmobs): skip flaky tests hitting faulty endpoint
  tests/llmobs/test_llmobs_eval_metric_agentless_writer.py
  tests/llmobs/test_llmobs_evaluator_runner.py
Labels: changelog/no-changelog, backport 3.10, backport 3.11, backport 3.12

#14466 chore(iast): context refactor, context-array + contextvar indexing
  .gitignore
  ddtrace/appsec/_iast/_iast_request_context_base.py
  ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects_base.py
  ddtrace/appsec/_iast/_taint_tracking/clean.sh
  ddtrace/appsec/_iast/_taint_tracking/context/_application_context.h
  ddtrace/appsec/_iast/_taint_tracking/context/application_context.cpp
  ddtrace/appsec/_iast/_taint_tracking/context/application_context.h
  ddtrace/appsec/_iast/_taint_tracking/initializer/initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/initializer/initializer.h
  ddtrace/appsec/_iast/_taint_tracking/native.cpp
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/taint_range.cpp
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/taint_range.h
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/taint_tracking.h
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/tainted_object.cpp
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/tainted_object.h
  ddtrace/appsec/_iast/_taint_tracking/tainted_ops/tainted_ops.cpp
  ddtrace/appsec/_iast/_taint_tracking/tainted_ops/tainted_ops.h
  ddtrace/appsec/_iast/_taint_tracking/tests/test_application_context.cpp
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: changelog/no-changelog, ASM

#14455 chore(benchmarks): add native writer macro benchmarks
  .gitlab/benchmarks/macrobenchmarks.yml
Labels: changelog/no-changelog

#14471 chore(llmobs): [MLOB-3622] pop tool calls to reduce noisy span links
  ddtrace/llmobs/_utils.py
  tests/contrib/openai_agents/test_openai_agents_llmobs.py
Labels: changelog/no-changelog

#14485 fix(profiling): re-accept interval for memory profile collector [backport 3.12]
  releasenotes/notes/profiling-fix-memalloc-collector-spin-regression-97b4b8093a89c54f.yaml
Labels: Profiling

#14494 chore(llmobs): add extend method to accept a list of records to dataset
  ddtrace/llmobs/_experiment.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_0db64595-86bd-4c4d-aca7-00a13885b5a5_batch_update_post_6f95ccf3.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_0db64595-86bd-4c4d-aca7-00a13885b5a5_batch_update_post_e366d882.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_0db64595-86bd-4c4d-aca7-00a13885b5a5_records_get_8bb921e8.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_900b7824.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-test_dataset_extend_test_dataset_records0__get_d3d212ba.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_8ba3f242.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14476 fix(profiling): upgrades echion to pick up critical bug fixes and performance improvements
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  releasenotes/notes/profiling-echion-bug-8ec66d6559cb5e7b.yaml
Labels: Profiling

#14473 chore(llmobs): use upload endpoint for CSV's and large pushes
  ddtrace/llmobs/_experiment.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_7ebcf701-2bd3-42d4-9dbd-01bb1169e66f_records_upload_post_36936c02.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_0134f05d.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_e03e6dcc-1a71-49ed-82b0-0042d0f7e117_records_upload_post_1d3054f1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_e03e6dcc-1a71-49ed-82b0-0042d0f7e117_records_upload_post_ca121309.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_ee7fe7e8-e947-4d0e-be54-be22314ca561_records_upload_post_6b357ece.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_fd975cd7.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14286 chore(build, crashtracker): build w/ debug symbols
  .github/workflows/build_python_3.yml
  .gitignore
  .gitlab/download-wheels-from-gh-actions.sh
  ddtrace/appsec/_iast/_taint_tracking/native.cpp
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
  docs/debug_symbols.rst
  docs/index.rst
  docs/spelling_wordlist.txt
  scripts/extract_debug_symbols.py
  setup.py
  src/native/Cargo.toml
Labels: changelog/no-changelog

#14507 ci(llmobs): start to replace some api calls in tests with testagent vcr proxy calls instead
  ddtrace/llmobs/_writer.py
  tests/llmobs/conftest.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_intake_llm-obs_v2_eval-metric_post_1218a393.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_intake_llm-obs_v2_eval-metric_post_2d529580.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_intake_llm-obs_v2_eval-metric_post_3ef3a86e.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_intake_llm-obs_v2_eval-metric_post_42090a9a.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_intake_llm-obs_v2_eval-metric_post_9ef24d1e.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_intake_llm-obs_v2_eval-metric_post_ca2bfa88.yaml
  tests/llmobs/test_llmobs_eval_metric_agent_writer.py
  tests/llmobs/test_llmobs_eval_metric_agentless_writer.py
  tests/llmobs/test_llmobs_evaluator_runner.py
Labels: changelog/no-changelog

#14525 ci: update system-tests commit
  .github/workflows/system-tests.yml
  .gitlab-ci.yml
Labels: changelog/no-changelog

#14512 fix(django): support async_only_middleware
  ddtrace/contrib/internal/django/middleware.py
  releasenotes/notes/fix-django-async-only-middleware-245d231d8a2384c5.yaml
  tests/contrib/django/django_app/settings.py
  tests/contrib/django/middleware.py
  tests/contrib/django/test_django_snapshots.py
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_asgi_200_3x.json
Labels: backport 3.13

#14539 fix(tracing): span pointer __repr__
  ddtrace/_trace/_span_pointer.py
  releasenotes/notes/fix-spanpointer-repr-565ebb8e6679ebde.yaml
  tests/tracer/test_span.py
Labels: backport 3.12, backport 3.13

#14304 fix(er): start capturing from the leaf frame
  .github/workflows/system-tests.yml
  .gitlab-ci.yml
  ddtrace/debugging/_exception/replay.py
  releasenotes/notes/fix-er-reverse-tracebacks-44a52d4f1601ca1f.yaml
  tests/debugging/exception/test_replay.py
Labels: Dynamic Instrumentation

#14562 chore(iast): context refactor II
  benchmarks/appsec_iast_aspects/scenario.py
  benchmarks/appsec_iast_aspects_ospath/scenario.py
  benchmarks/appsec_iast_aspects_re_module/scenario.py
  benchmarks/appsec_iast_aspects_split/scenario.py
  benchmarks/appsec_iast_propagation/scenario.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_iast_request_context_base.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_tracking/context/taint_engine_context.cpp
  ddtrace/appsec/_iast/_taint_tracking/context/taint_engine_context.h
  ddtrace/appsec/_iast/sampling/vulnerability_detection.py
  ddtrace/appsec/_iast/sources/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
  scripts/iast/leak_functions.py
  tests/appsec/iast/_ast/conftest.py
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_modulo_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_replace_aspect.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/fixtures/entrypoint/views.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/secure_marks/conftest.py
  tests/appsec/iast/taint_sinks/_taint_sinks_utils.py
  tests/appsec/iast/taint_sinks/test_insecure_cookie.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_sql_injection_dbapi.py
  tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_stacktrace_leak.py
  tests/appsec/iast/taint_sinks/test_unvalidated_redirect_redacted.py
  tests/appsec/iast/taint_sinks/test_vulnerability_detection.py
  tests/appsec/iast/taint_tracking/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range_gevent_fork.py
  tests/appsec/iast/test_processor.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/test_iast_django.py
  tests/appsec/integrations/packages_tests/conftest.py
Labels: changelog/no-changelog, ASM

#14553 chore(appsec): remove extra waf.config_errors reporting
  ddtrace/appsec/_metrics.py
Labels: changelog/no-changelog, ASM

#14193 ci: refactor gen_ext_cache_scripts.py
  .gitlab/templates/build-base-venvs.yml
  .gitlab/templates/cached-testrunner.yml
  scripts/ext_cache.py
  scripts/gen_ext_cache_scripts.py
Labels: changelog/no-changelog, CI

#14582 ci: remove Service Bus Trigger tests for Azure Functions
  .riot/requirements/1337ee3.txt
  .riot/requirements/145ed9e.txt
  .riot/requirements/14b54db.txt
  .riot/requirements/1e60e3c.txt
  .riot/requirements/1e62aea.txt
  .riot/requirements/44abb4f.txt
  .riot/requirements/6da0824.txt
  .riot/requirements/c2420c2.txt
  riotfile.py
  tests/contrib/azure_functions/azure_function_app/function_app.py
  tests/contrib/azure_functions/test_azure_functions_snapshot.py
  tests/contrib/config.py
  tests/contrib/suitespec.yml
  tests/snapshots/tests.contrib.azure_functions.test_azure_functions_snapshot.test_service_bus_consume_diff_context[many].json
  tests/snapshots/tests.contrib.azure_functions.test_azure_functions_snapshot.test_service_bus_consume_same_context[many].json
  tests/snapshots/tests.contrib.azure_functions.test_azure_functions_snapshot.test_service_bus_distributed_tracing[disabled].json
  tests/snapshots/tests.contrib.azure_functions.test_azure_functions_snapshot.test_service_bus_distributed_tracing[enabled].json
  tests/wait-for-services.py
Labels: changelog/no-changelog

#14567 chore: add scripts/run-tests helper command
  docs/contributing-testing.rst
  scripts/run-tests
Labels: changelog/no-changelog

#14550 fix(profiling): avoid use-after-free when profiling realloc
  ddtrace/profiling/collector/_memalloc_heap.c
  ddtrace/profiling/collector/_pymacro.h
  releasenotes/notes/profiling-fix-memalloc-realloc-use-after-free-6f3ec672315ac5f0.yaml
Labels: Profiling

#14598 ci: add azure sql edge and azurite service checks
  .riot/requirements/151d7b0.txt
  .riot/requirements/1eb3af5.txt
  riotfile.py
  tests/contrib/config.py
  tests/contrib/suitespec.yml
  tests/wait-for-services.py
Labels: changelog/no-changelog

#14607 ci(llmobs): skip flaky test again
  tests/llmobs/test_llmobs_evaluator_runner.py
Labels: changelog/no-changelog, backport 3.14

#14596 chore: bump `libdatadog` version to 21.0.0
  src/native/Cargo.lock
  src/native/Cargo.toml
  src/native/data_pipeline/exceptions.rs
  src/native/library_config.rs
  tests/internal/crashtracker/utils.py
Labels: changelog/no-changelog

#14616 chore(testing): fix update manager to delete necessary files / venvs each run
  tests/contrib/integration_registry/registry_update_helpers/integration_update_orchestrator.py
Labels: changelog/no-changelog

#14609 chore(appsec): add action tag on waf.config_errors
  ddtrace/appsec/_ddwaf/waf.py
  ddtrace/appsec/_metrics.py
Labels: changelog/no-changelog, ASM

#14622 test: add APPSEC_STANDALONE_RASP to the scenario list
  .github/workflows/system-tests.yml
  .gitlab-ci.yml
Labels: changelog/no-changelog

#14633 ci: use larger wheel building runners
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog

#14595 ci: pre-compute library version for build steps
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
  .gitlab/download-library-version-from-gh-actions.sh
  .gitlab/download-wheels-from-gh-actions.sh
  .gitlab/gha-utils.sh
  .gitlab/package.yml
Labels: changelog/no-changelog

#14635 chore(debugger): fix issue with re-initializing uploader tracks
  ddtrace/debugging/_uploader.py
  tests/debugging/test_uploader.py
Labels: changelog/no-changelog

#14630 fix(profiling): upgrade echion to fix segfaults from services with many ``asyncio.Task``s
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  releasenotes/notes/profiling-echion-upgrade-04aa2bb0bdf4882d.yaml
Labels: Profiling

#14629 feat(llmobs): add summary evaluator functionality for datasets & experiments
  ddtrace/llmobs/_experiment.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_9e046fc7-cf3f-4f01-b5ed-e5e7746fefa8_events_post_1edd9d51.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_9e046fc7-cf3f-4f01-b5ed-e5e7746fefa8_events_post_977047ce.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_9e046fc7-cf3f-4f01-b5ed-e5e7746fefa8_events_post_ac74921f.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_9e046fc7-cf3f-4f01-b5ed-e5e7746fefa8_events_post_e476f464.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14655 chore(debugger): rate-limit agent warning logs to once an hour
  ddtrace/debugging/_uploader.py
Labels: changelog/no-changelog

#14645 fix: allow libinjection denylist to deny python module executions
  lib-injection/sources/denied_executable_modules.txt
  lib-injection/sources/denied_executables.txt
  lib-injection/sources/sitecustomize.py
  releasenotes/notes/libinjection-denytlist-modules-a5e0407ed6b8166a.yaml
  riotfile.py
  tests/lib_injection/test_denylist.py
Labels: backport 3.12, backport 3.13, backport 3.14

#14654 chore(crashtracking): fix flaky test around receiving crash messages
  tests/internal/crashtracker/test_crashtracker.py
  tests/internal/crashtracker/utils.py
  tests/utils.py
Labels: changelog/no-changelog

#14677 chore: avoid building profiling extension under 3.14
  .github/workflows/requirements-locks.yml
  .gitlab/templates/cached-testrunner.yml
  .gitlab/testrunner.yml
  setup.py
Labels: changelog/no-changelog

#14540 chore(mlobs): infer the name of the job from the submission ID
  ddtrace/contrib/internal/ray/constants.py
  ddtrace/contrib/internal/ray/patch.py
  ddtrace/contrib/internal/ray/utils.py
  tests/contrib/ray/test_ray.py
  tests/contrib/ray/test_ray_utils.py
  tests/snapshots/tests.contrib.ray.test_ray.error_in_task.json
  tests/snapshots/tests.contrib.ray.test_ray.test_actor_and_task.json
  tests/snapshots/tests.contrib.ray.test_ray.test_actor_interactions.json
  tests/snapshots/tests.contrib.ray.test_ray.test_nested_tasks.json
  tests/snapshots/tests.contrib.ray.test_ray.test_simple_actor.json
  tests/snapshots/tests.contrib.ray.test_ray.test_simple_task.json
  tests/snapshots/tests.contrib.ray.test_ray.test_simple_wait.json
Labels: changelog/no-changelog

#14690 chore(ci): removes APPSEC_BLOCKING from system-tests
  .github/workflows/system-tests.yml
  .gitlab-ci.yml
Labels: changelog/no-changelog

#14691 fix(aap): fix flask patch for none methods
  ddtrace/contrib/internal/flask/patch.py
  releasenotes/notes/flask_endpoint_discovery_fix-7f98200c2fa342c4.yaml
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
Labels: bug, ASM, backport 3.14

#14695 ci: fix valgrind profiling native test
  .github/workflows/profiling-native.yml
Labels: changelog/no-changelog

#14681 fix(ci_visibility): itr skipped counts suites or tests
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/api/_suite.py
  ddtrace/internal/ci_visibility/api/_test.py
  releasenotes/notes/ci_visibility_fix_itr_count-7f4c5da42df18aea.yaml
  tests/ci_visibility/api/fake_runner_mix_fail_itr_suite_level.py
  tests/ci_visibility/api/test_api_fake_runners.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest/test_pytest_xdist_itr.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_all_itr_skip_suite_level.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_runner_mix_fail_itr_suite_level.json
Labels: CI App, backport 3.12, backport 3.13, backport 3.14

#14668 chore: update bytecode support for python 3.14
  ddtrace/debugging/_expressions.py
  ddtrace/internal/assembly.py
  ddtrace/internal/bytecode_injection/__init__.py
  ddtrace/internal/symbol_db/symbols.py
  ddtrace/internal/wrapping/asyncs.py
  ddtrace/internal/wrapping/context.py
  ddtrace/internal/wrapping/generators.py
Labels: changelog/no-changelog

#14700 fix(aap): fixing asyncio error for asgi
  ddtrace/appsec/_handlers.py
  releasenotes/notes/asyncio_fix-d279a20c05a2bf24.yaml
Labels: bug, ASM, backport 3.14

#14527 chore(profiling): small typing improvements
  ddtrace/internal/datadog/profiling/stack_v2/__init__.pyi
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/asyncio.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyi
  ddtrace/profiling/collector/threading.py
Labels: changelog/no-changelog

#14708 chore(codeowners): update codeowners to rename apm-sdk-api to apm-sdk-capabilities
  .github/CODEOWNERS
Labels: changelog/no-changelog

#14711 ci: actually validate the ast-grep rules against the repo
  .gitlab-ci.yml
  ddtrace/contrib/internal/django/database.py
Labels: changelog/no-changelog

#14703 chore: remove unused core.on_all function
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
  benchmarks/core_api/config.yaml
  benchmarks/core_api/scenario.py
  ddtrace/internal/core/event_hub.py
  tests/internal/test_context_events_api.py
Labels: changelog/no-changelog

#14671 chore(llmobs): add multi message prompt templates support for langchain
  ddtrace/llmobs/_integrations/langchain.py
  tests/contrib/langchain/test_langchain_llmobs.py
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_2eb535d8.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_448095a4.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_5244958a.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_8fdba4e4.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_ad7e4955.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_fd55b179.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_0fdd1e55.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_b77fd180.yaml
Labels: changelog/no-changelog

#14689 chore(iast): split subprocess and urllib-family patch
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/_ast/iastpatch.c
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/main.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/internal/httplib/patch.py
  ddtrace/contrib/internal/requests/patch.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/contrib/internal/urllib/patch.py
  ddtrace/contrib/internal/urllib3/patch.py
  ddtrace/contrib/internal/webbrowser/patch.py
  ddtrace/settings/asm.py
  riotfile.py
  tests/appsec/app.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/fixtures/taint_sinks/command_injection.py
  tests/appsec/iast/fixtures/taint_sinks/ssrf.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/appsec/iast/taint_sinks/test_text_type_validation.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/flask_tests/test_appsec_flask.py
  tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
  tests/appsec/integrations/langchain_tests/test_iast_langchain.py
  tests/contrib/subprocess/test_subprocess.py
Labels: changelog/no-changelog, ASM

#14709 test: update and skip tests to work with pytest-asyncio version 1.x and python 3.14
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/aiohttp/test_request.py
  tests/contrib/aiohttp/test_request_safety.py
  tests/contrib/aiohttp_jinja2/test_aiohttp_jinja2.py
  tests/contrib/asyncio/utils.py
  tests/contrib/unittest/test_unittest_snapshot.py
  tests/integration/test_integration_snapshots.py
  tests/internal/crashtracker/test_crashtracker.py
  tests/internal/test_tracer_flare.py
  tests/internal/test_utils_http.py
  tests/smoke_test.py
  tests/snapshots/tests.contrib.unittest.test_unittest_snapshot.test_unittest_will_force_run_multiple_unskippable_tests.json
  tests/suitespec.yml
  tests/telemetry/test_telemetry_metrics_e2e.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#14710 test: re-add checks for no error logs from many tests
  tests/contrib/aiohttp/test_aiohttp_client.py
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/aiomysql/test_aiomysql.py
  tests/contrib/aredis/test_aredis.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/asyncio/test_lazyimport.py
  tests/contrib/asyncpg/test_asyncpg.py
  tests/contrib/azure_servicebus/test_azure_servicebus_snapshot.py
  tests/contrib/dogpile_cache/test_tracing.py
  tests/contrib/elasticsearch/test_async.py
Labels: changelog/no-changelog

#14721 chore(otel): remove useless metric
  ddtrace/internal/opentelemetry/logs.py
Labels: changelog/no-changelog

#14716 ci(iast): add more iast testagent tests
  .riot/requirements/1021fa1.txt
  .riot/requirements/1554154.txt
  .riot/requirements/1828fcc.txt
  .riot/requirements/19df299.txt
  .riot/requirements/19fed8a.txt
  .riot/requirements/1c28390.txt
  .riot/requirements/1eb3af5.txt
  .riot/requirements/1ef982c.txt
  .riot/requirements/1fbd93b.txt
  .riot/requirements/38066f4.txt
  .riot/requirements/5368b32.txt
  .riot/requirements/68a2945.txt
  .riot/requirements/a0d16bc.txt
  .riot/requirements/e05f887.txt
  .riot/requirements/e8dd8b5.txt
  ddtrace/appsec/_iast/_taint_tracking/utils/generic_utils.cpp
  riotfile.py
  tests/appsec/integrations/conftest.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_iast_django_testagent.py
  tests/appsec/integrations/fastapi_tests/app.py
  tests/appsec/integrations/fastapi_tests/test_iast_fastapi_testagent.py
  tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM
