Repository DataDog/dd-trace-py, pull requests merged in 2025-08, with the labels that each got.

#14166 chore(ci_visibility): fix coverage collection at per-test level skipping
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  tests/contrib/pytest/test_coverage_per_suite.py
  tests/contrib/pytest/test_pytest.py
  tests/contrib/pytest/test_pytest_coverage_edge_cases.py
  tests/contrib/pytest/utils.py
Labels: changelog/no-changelog, CI App

#14205 chore(profiler): remove remaining max_events config stuff
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc.pyi
  ddtrace/profiling/collector/memalloc.py
  ddtrace/settings/profiling.py
  tests/profiling/collector/test_memalloc.py
  tests/profiling_v2/collector/test_memalloc.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#14214 chore(bench): fix build baseline for microbenchmarks
  .gitlab/benchmarks/steps/build-baseline.sh
Labels: changelog/no-changelog

#12690 refactor(crashtracker): use PyO3 for crashtracker module and crashtracker_exe
  .gitignore
  .gitlab/templates/build-base-venvs.yml
  build_libnative.py
  ddtrace/commands/_dd_crashtracker_receiver.py
  ddtrace/internal/core/crashtracking.py
  ddtrace/internal/datadog/profiling/build_standalone.sh
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/crashtracker/__init__.py
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyi
  ddtrace/internal/datadog/profiling/crashtracker/_crashtracker.pyx
  ddtrace/internal/datadog/profiling/crashtracker/python_runtime_stub.c
  ddtrace/internal/datadog/profiling/crashtracker/src/crashtracker.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/constants.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/crashtracker_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/receiver_interface.h
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/crashtracker_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/receiver_interface.cpp
  ddtrace/internal/datadog/profiling/util.py
  ddtrace/internal/native/_native.pyi
  ddtrace/settings/crashtracker.py
  lib-injection/sources/denied_executables.txt
  pyproject.toml
  setup.py
  src/native/Cargo.lock
  src/native/Cargo.toml
  src/native/crashtracker.rs
  src/native/lib.rs
  tests/internal/crashtracker/test_crashtracker.py
  tests/internal/crashtracker/utils.py
Labels: changelog/no-changelog

#14212 chore(llmobs): improve llmobs debug logs
  ddtrace/llmobs/_llmobs.py
Labels: changelog/no-changelog

#14213 fix(sampling): always use root span for sampling decision on partial flushes
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
  ddtrace/_trace/processor/__init__.py
  releasenotes/notes/partial-flush-sampling-fix-e34a7c2dd47ae82a.yaml
  tests/tracer/test_sampler.py
Labels: backport 3.10, backport 3.11

#14215 chore(appsec): update libddwaf and speed up default ruleset loading
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_ddwaf/waf.py
  ddtrace/appsec/_ddwaf/waf_stubs.py
  ddtrace/appsec/_processor.py
  setup.py
  tests/appsec/appsec/api_security/test_schema_fuzz.py
  tests/appsec/appsec/test_processor.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#14216 chore(ci): update st
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#14143 fix(tracer): early start for rc layer
  .github/workflows/import-analysis.yml
  ddtrace/internal/_threads.cpp
  ddtrace/internal/_threads.pyi
  ddtrace/internal/periodic.py
  ddtrace/internal/remoteconfig/_connectors.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
  releasenotes/notes/remote_config_threads_improvements-b048d409a93e4086.yaml
Labels: backport 3.11

#14231 chore(ci): unlock 3.11 ci
  .github/workflows/system-tests.yml
  pyproject.toml
Labels: changelog/no-changelog, CI

#14220 ci(botocore): skip flaky s3 test case
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#14233 chore(ci): do not use a API KEY in system-tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#14242 chore(aap): improvement to avoid warnings for typing and lint
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_utils.py
  ddtrace/settings/asm.py
Labels: changelog/no-changelog

#14209 chore(ci_visibility): xdist parallelization level sets itr suite mode
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/_xdist.py
  tests/contrib/pytest/test_pytest_xdist_itr.py
Labels: changelog/no-changelog, CI App

#14237 chore(llmobs): change result type to str
  ddtrace/llmobs/utils.py
Labels: changelog/no-changelog

#14176 test: re-enable gunicorn forksafe test for 3.13
  tests/internal/test_forksafe.py
Labels: changelog/no-changelog

#13562 chore: configurable logger levels
  ddtrace/internal/logger.py
  docs/contributing-testing.rst
  tests/tracer/test_logger.py
Labels: changelog/no-changelog

#14252 chore: ensure lib-injection telemetry forwarder uses bash process
  tests/lib_injection/conftest.py
  tests/lib_injection/test_guardrails.py
Labels: changelog/no-changelog

#14251 chore(sampling): log error when sampling rules are not applied
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
  ddtrace/_trace/sampler.py
  tests/tracer/test_sampler.py
Labels: changelog/no-changelog

#14249 chore: stricter wrapping context wrap check
  ddtrace/internal/wrapping/context.py
Labels: changelog/no-changelog

#14248 ci: bump azure-functions-core-tools to 4.1.0
  docker/Dockerfile
Labels: changelog/no-changelog

#13071 feat(writer): implement native writer [APMSP-1875]
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
  .riot/requirements/1550212.txt
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/tracer.py
  ddtrace/internal/native/__init__.py
  ddtrace/internal/native/_native.pyi
  ddtrace/internal/writer/__init__.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/_config.py
  riotfile.py
  src/native/Cargo.lock
  src/native/Cargo.toml
  src/native/data_pipeline/exceptions.rs
  src/native/data_pipeline/mod.rs
  src/native/lib.rs
  tests/contrib/kafka/test_kafka.py
  tests/integration/test_debug.py
  tests/integration/test_integration.py
  tests/integration/test_integration_snapshots.py
  tests/integration/test_priority_sampling.py
  tests/integration/test_trace_stats.py
  tests/integration/utils.py
  tests/suitespec.yml
  tests/telemetry/test_writer.py
  tests/tracer/test_processors.py
  tests/tracer/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog

#13809 chore: remove logic that uses import importlib_metadata
  ddtrace/contrib/internal/elasticsearch/patch.py
  ddtrace/contrib/internal/pyramid/patch.py
  ddtrace/contrib/internal/pytest_bdd/patch.py
  ddtrace/internal/gitmetadata.py
  ddtrace/internal/packages.py
  ddtrace/internal/products.py
  lib-injection/sources/requirements.csv
  pyproject.toml
  requirements.csv
  tests/appsec/integrations/flask_tests/utils.py
  tests/contrib/integration_registry/registry_update_helpers/integration_registry_manager.py
  tests/utils.py
Labels: changelog/no-changelog

#14253 chore(docs): fix readthedocs build
  .readthedocs.yml
Labels: changelog/no-changelog

#14271 chore(ci): update system tests version on 3.11
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#14255 chore(llmobs): fix deletion conflicts with insertions
  ddtrace/llmobs/_experiment.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_cfdb514f-92b0-404f-9b3f-020f82b0cd51_batch_update_post_01ab4862.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_cfdb514f-92b0-404f-9b3f-020f82b0cd51_batch_update_post_a50f2e77.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_cfdb514f-92b0-404f-9b3f-020f82b0cd51_records_get_8c03b3af.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_19f1f445.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-test_dataset_delete_after_append_test_dataset_records0__get_7ff2210e.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_f9798e4e.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14227 fix(sampling): always use root span for sampling decision on partial flushes (backport #14213 to 3.11)
  ddtrace/_trace/processor/__init__.py
  releasenotes/notes/partial-flush-sampling-fix-e34a7c2dd47ae82a.yaml
  tests/tracer/test_sampler.py
Labels: backport 2.21

#14276 chore(profiling): re-accept interval for memory profile collector
  ddtrace/profiling/collector/memalloc.py
Labels: changelog/no-changelog

#14170 chore(telemetry): report telemetry for all config sources
  ddtrace/internal/telemetry/__init__.py
  ddtrace/settings/_core.py
  ddtrace/settings/_otel_remapper.py
  tests/conftest.py
  tests/opentelemetry/test_config.py
  tests/telemetry/test_telemetry.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#14291 chore: add the traceback to the integration failed to enable errors
  ddtrace/_monkey.py
Labels: changelog/no-changelog

#14293 chore(django): remove django.process_exception event/handler
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/django/patch.py
Labels: changelog/no-changelog

#14295 chore(internal): add is_wrapped and is_wrapped_with helpers
  ddtrace/internal/wrapping/__init__.py
  tests/internal/test_wrapping.py
Labels: changelog/no-changelog

#14298 ci: pin system-tests ref in one-pipeline
  .github/workflows/system-tests.yml
  .gitlab-ci.yml
  scripts/update-system-tests-version.py
Labels: changelog/no-changelog

#14300 chore(django): move template wrapping away from wrapping context
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/django/templates.py
  tests/contrib/django/conftest.py
  tests/contrib/django/test_django_patch.py
Labels: changelog/no-changelog

#14210 fix(appsec): report all tags on the service entry span instead of the local root span
  .github/codeql-config.yml
  ddtrace/_trace/span.py
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_exploit_prevention/stack_traces.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_iast_request_context_base.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/track_user_sdk.py
  ddtrace/settings/asm.py
  releasenotes/notes/appsec-report-tags-on-entry-span-7b43ae9779d05d17.yaml
  tests/appsec/appsec/api_security/test_api_security_manager.py
  tests/appsec/appsec/test_appsec_trace_utils.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/django_app/app/middlewares.py
  tests/appsec/contrib_appsec/django_app/settings.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/telemetry/test_writer.py
  tests/tracer/test_span.py
Labels: ASM

#14315 chore(llmobs): add url origin env var
  ddtrace/llmobs/_writer.py
  releasenotes/notes/llmobs-url-override-5d791534021f66a9.yaml
Labels: backport 3.12

#14323 perf(starlette): avoid unnecessary version comparison
  ddtrace/contrib/internal/starlette/patch.py
Labels: changelog/no-changelog

#14107 feat(llmobs): langchain integration prompt template tracking
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/utils.py
  ddtrace/llmobs/_llmobs.py
  tests/contrib/langchain/test_langchain_llmobs.py
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_68f561a6.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_fcae7ba6.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_2dbdd8b1.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_4527033c.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_46579144.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_68f85366.yaml
Labels: changelog/no-changelog, mergequeue-status: in_progress

#14344 chore(ci_visibility): ensure exception dictionary is cleared after each test
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog, backport 3.11, backport 3.12

#14353 chore: add traceback info to the failed to send message [backport 3.10]
  ddtrace/internal/writer/writer.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#14319 chore(llmobs): include stack trace and error type if possible when raising error
  ddtrace/llmobs/_experiment.py
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14355 chore: add traceback info to the failed to send message (#14299) [backport 3.11]
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
  ddtrace/internal/writer/writer.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog

#13736 chore(llmobs): [MLOB-3112] make shared base classes for llmobs traced streams
  ddtrace/contrib/internal/anthropic/_streaming.py
  ddtrace/contrib/internal/botocore/services/bedrock.py
  ddtrace/contrib/internal/google_genai/_utils.py
  ddtrace/contrib/internal/google_genai/patch.py
  ddtrace/contrib/internal/google_generativeai/_utils.py
  ddtrace/contrib/internal/google_generativeai/patch.py
  ddtrace/contrib/internal/langchain/utils.py
  ddtrace/contrib/internal/litellm/patch.py
  ddtrace/contrib/internal/litellm/utils.py
  ddtrace/contrib/internal/openai/_endpoint_hooks.py
  ddtrace/contrib/internal/openai/utils.py
  ddtrace/contrib/internal/vertexai/_utils.py
  ddtrace/contrib/internal/vertexai/patch.py
  ddtrace/llmobs/_integrations/base_stream_handler.py
  tests/contrib/anthropic/test_anthropic_llmobs.py
  tests/contrib/google_genai/test_google_genai_llmobs.py
  tests/contrib/langchain/test_langchain_llmobs.py
  tests/contrib/litellm/test_litellm_llmobs.py
  tests/contrib/litellm/utils.py
  tests/contrib/openai/test_openai_llmobs.py
  tests/contrib/vertexai/test_vertexai_llmobs.py
  tests/llmobs/_utils.py
Labels: changelog/no-changelog

#14314 chore: add debug log for when tracing is disabled due to app key and DD_TRACE_ENABLED
  ddtrace/llmobs/_llmobs.py
Labels: changelog/no-changelog

#14365 chore(benchmarks): give telemetry add metric slos more headroom
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
Labels: changelog/no-changelog

#14341 chore(redis): use the core API in redis instrumentations
  ddtrace/_trace/trace_handlers.py
  ddtrace/_trace/utils_redis.py
  ddtrace/contrib/internal/aioredis/patch.py
  ddtrace/contrib/internal/aredis/patch.py
  ddtrace/contrib/internal/flask_cache/utils.py
  ddtrace/contrib/internal/redis/asyncio_patch.py
  ddtrace/contrib/internal/redis/patch.py
  ddtrace/contrib/internal/redis_utils.py
  ddtrace/contrib/internal/yaaredis/patch.py
  tests/contrib/suitespec.yml
Labels: changelog/no-changelog

#14387 chore(internal): remove span attributes from the core api
  ddtrace/internal/core/__init__.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#14369 chore(tracing): remove usage of Pin._get_config
  ddtrace/_trace/pin.py
  ddtrace/contrib/internal/httplib/patch.py
  ddtrace/contrib/internal/requests/connection.py
  tests/contrib/httplib/test_httplib_distributed.py
  tests/contrib/jinja2/test_jinja2.py
  tests/contrib/requests/test_requests.py
  tests/contrib/requests/test_requests_distributed.py
  tests/tracer/test_instance_config.py
Labels: changelog/no-changelog

#14370 chore(django): refactor cache wrapping
  benchmarks/django_simple/scenario.py
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/django/cache.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/django/utils.py
  tests/contrib/django/conftest.py
Labels: changelog/no-changelog

#14377 chore(molten): use the core api in the molten integration
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/molten/patch.py
  ddtrace/contrib/internal/molten/wrappers.py
  ddtrace/internal/core/__init__.py
  tests/contrib/molten/test_molten.py
Labels: changelog/no-changelog

#14330 chore: enable telemetry only on Linux platforms
  ddtrace/internal/writer/writer.py
  tests/tracer/test_writer.py
Labels: changelog/no-changelog, mergequeue-status: waiting

#14395 fix: use default trace agent url for tracer flare
  ddtrace/internal/remoteconfig/products/client.py
  releasenotes/notes/fix-tracer-flare-default-url-fc1232a153f60b45.yaml
Labels: backport 3.12

#14147 perf(tracing): optimize span aggregator performance
  ddtrace/_trace/processor/__init__.py
Labels: changelog/no-changelog

#14404 perf(tracing): use get_local_item instead of get_item
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/botocore/patch.py
  ddtrace/internal/core/__init__.py
Labels: changelog/no-changelog

#14413 ci: upgrade bandit version
  hatch.toml
Labels: changelog/no-changelog, backport 3.11, backport 3.12

#14422 chore(build): stop setting universal for bdist_wheel
  setup.cfg
Labels: changelog/no-changelog

#14416 chore(core): rename and document core APIs for clarity
  benchmarks/core_api/scenario.py
  ddtrace/_trace/trace_handlers.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_env.py
  ddtrace/appsec/_processor.py
  ddtrace/contrib/internal/botocore/services/bedrock.py
  ddtrace/contrib/internal/botocore/services/stepfunctions.py
  ddtrace/contrib/internal/celery/app.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/contrib/internal/trace_utils.py
  ddtrace/contrib/internal/wsgi/wsgi.py
  ddtrace/internal/core/__init__.py
  ddtrace/internal/datastreams/kafka.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_processor.py
  tests/contrib/subprocess/test_subprocess.py
  tests/internal/test_context_events_api.py
Labels: changelog/no-changelog, mergequeue-status: removed

#14442 chore(profiling): remove unused traceback file and test
  ddtrace/profiling/_traceback.py
  tests/profiling/test_traceback.py
Labels: changelog/no-changelog, mergequeue-status: waiting

#14434 chore(profiling): remove unused utils code
  ddtrace/profiling/utils.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#14445 ci: removes upstream-issues.yml workflow
  .github/workflows/upstream-issues.yml
Labels: changelog/no-changelog

#14423 chore(flare): log tracer flares logs as json structured data
  ddtrace/_logger.py
  ddtrace/internal/flare/flare.py
  ddtrace/internal/flare/json_formatter.py
  tests/internal/test_tracer_flare.py
Labels: changelog/no-changelog

#14448 chore: remove dupe `from json import dumps as json_dumps` from encoding file
  ddtrace/internal/_encoding.pyx
Labels: changelog/no-changelog
