Repository DataDog/dd-trace-py, pull requests merged in 2025-07, with the labels that each got.

#13833 chore(ci): riotize appsec_integrations_flask
  .riot/requirements/16d69d5.txt
  .riot/requirements/176c4e4.txt
  .riot/requirements/188ce67.txt
  .riot/requirements/19498a9.txt
  .riot/requirements/19babc6.txt
  .riot/requirements/1ab97dd.txt
  .riot/requirements/1b1249c.txt
  .riot/requirements/1c15175.txt
  .riot/requirements/1f4ed67.txt
  .riot/requirements/1f7d94e.txt
  .riot/requirements/31bdefd.txt
  .riot/requirements/9cd36b5.txt
  .riot/requirements/a669651.txt
  .riot/requirements/a96d894.txt
  .riot/requirements/b0f4d8a.txt
  .riot/requirements/bb60b77.txt
  .riot/requirements/d548d24.txt
  hatch.toml
  riotfile.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog

#13837 docs: update release pandoc script
  docs/contributing-release.rst
Labels: changelog/no-changelog

#13846 ci: fix macrobenchmark trigger to run on rc releases
  .gitlab-ci.yml
Labels: changelog/no-changelog

#13797 ci(internal): make flaky wrapping test a subprocess test
  tests/internal/test_wrapping.py
Labels: changelog/no-changelog

#13752 ci: ignore pr name linting in all-green check
  .github/workflows/all-green.yml
Labels: changelog/no-changelog, backport 2.21

#13783 ci: move DI exploration tests to GitLab
  .github/workflows/test_frameworks.yml
  .gitlab/templates/debugging/exploration.yml
  .gitlab/tests.yml
  scripts/gen_gitlab_config.py
  tests/debugging/exploration/_config.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
  tests/debugging/exploration/pytest/exploration.py
  tests/debugging/exploration/test_bootstrap.py
  tests/debugging/exploration/utils.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#13374 chore(ci): iast_defaults test from hatch to riot
  .riot/requirements/1403768.txt
  .riot/requirements/17ae74f.txt
  .riot/requirements/1a81d2a.txt
  .riot/requirements/31639df.txt
  .riot/requirements/7b9a280.txt
  .riot/requirements/f2b3dd3.txt
  hatch.toml
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, CI

#13859 ci(benchmarks): skip django startup benchmarks
  .gitlab/benchmarks/microbenchmarks.yml
Labels: changelog/no-changelog

#13851 chore(llmobs): apply llmobs sample filter in base integration class
  ddtrace/contrib/internal/litellm/patch.py
  ddtrace/contrib/internal/litellm/utils.py
  ddtrace/contrib/internal/vertexai/_utils.py
  ddtrace/contrib/internal/vertexai/patch.py
  ddtrace/llmobs/_integrations/base.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#13866 ci(iast): fix flaky and slow tests
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/test_env_var.py
Labels: changelog/no-changelog, ASM

#13865 chore(ci): fix missing dependency on appsec_iast_defaults
  .riot/requirements/109d1ad.txt
  .riot/requirements/1421f4d.txt
  .riot/requirements/19a745b.txt
  .riot/requirements/1c51432.txt
  .riot/requirements/1d81907.txt
  .riot/requirements/551fe5d.txt
  riotfile.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#13861 ci: add TestAgentClient to SnapshotTest
  tests/utils.py
Labels: changelog/no-changelog

#13854 fix(ci_visibility): improve compatibility with external retry plugins
  .github/CODEOWNERS
  .riot/requirements/10f023c.txt
  .riot/requirements/131a701.txt
  .riot/requirements/60dc244.txt
  .riot/requirements/98ec6ba.txt
  .riot/requirements/c826075.txt
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/_utils.py
  ddtrace/internal/ci_visibility/constants.py
  releasenotes/notes/ci_visibility-fix-pytest-retry-plugins-compat-7ae7c8dc81676195.yaml
  riotfile.py
  tests/ci_visibility/suitespec.yml
  tests/contrib/pytest_flaky/__init__.py
  tests/contrib/pytest_flaky/test_pytest_flaky.py
Labels: backport 3.10

#13855 feat(appsec): add metric for unsupported lambda event types
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/utils.py
Labels: changelog/no-changelog, ASM

#13890 ci: include stage in GitLab job name
  .gitlab/templates/debugging/exploration.yml
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog, backport 2.21

#13747 feat(DI): add config to create probes through a file
  ddtrace/debugging/_debugger.py
  ddtrace/settings/dynamic_instrumentation.py
  tests/debugging/test_debugger.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#13901 chore(llmobs): shutdown tracer after test case
  tests/llmobs/conftest.py
Labels: changelog/no-changelog

#13823 ci: introduce SLO based microbenchmark checks
  .gitlab/benchmarks/bp-runner.macrobenchmarks.fail-on-breach.yml
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
  .gitlab/benchmarks/macrobenchmarks.yml
  .gitlab/benchmarks/microbenchmarks.yml
Labels: changelog/no-changelog

#13916 chore: fix cargo clippy issues with new versions of rust
  src/native/library_config.rs
Labels: changelog/no-changelog

#13879 chore: fix spelling mistakes in codebase
  ddtrace/_trace/span.py
  ddtrace/llmobs/_integrations/langchain.py
  hatch.toml
  releasenotes/notes/add-sqs-lambda-context-support-5062a60d81055ed7.yaml
  releasenotes/notes/ci-vis-gzip-payload-a93c4b5d4687f1c4.yaml
  releasenotes/notes/ci-vis-gzip-payload-evp-8269d43f2721afa1.yaml
  tests/contrib/logging/test_logging.py
  tests/lib_injection/conftest.py
  tests/tracer/test_correlation_log_context.py
  tests/tracer/test_settings.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#13908 ci: migrate crash tracking tests to the test agent
  riotfile.py
  tests/internal/crashtracker/test_crashtracker.py
  tests/internal/crashtracker/utils.py
  tests/utils.py
Labels: changelog/no-changelog

#13852 chore(llmobs): add base datasets for experiments
  .gitlab/services.yml
  ddtrace/llmobs/__init__.py
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_experiment.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  docker-compose.yml
  tests/llmobs/_utils.py
  tests/llmobs/conftest.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_0e577f3f.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_15fc0d15.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_e3608c37-7422-4a91-8897-9dc6097e86b4_records_get_ce4912d9.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-non-existent_get_ceb7b7a1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset_get_3012b2d9.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_3335cc3f.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_816b83e0.yaml
  tests/llmobs/suitespec.yml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#13903 ci(benchmark): add tracer and span slos
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
Labels: changelog/no-changelog

#13876 chore(tracer): add abstract base class for AgentWriterInterface
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/tracer.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/debug.py
  ddtrace/internal/writer/__init__.py
  ddtrace/internal/writer/writer.py
  ddtrace/opentracer/tracer.py
  tests/appsec/integrations/utils_testagent.py
  tests/commands/ddtrace_run_hostname.py
  tests/integration/test_debug.py
  tests/integration/test_integration.py
  tests/integration/test_integration_snapshots.py
  tests/tracer/test_tracer.py
  tests/tracer/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog

#13921 fix(aap): properly manage large async request bodies
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
  ddtrace/appsec/_handlers.py
  ddtrace/settings/asm.py
  releasenotes/notes/fastapi_body_extraction_for_aap-b6f53b4f03015319.yaml
  tests/telemetry/test_writer.py
Labels: bug, ASM

#13937 chore(ci): update st
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#13945 chore(ci): remove errortracking from hatch since it's already on riot
  hatch.toml
Labels: changelog/no-changelog, CI, backport 2.21

#13896 chore(tracer): adding additional validation for jsonpath syntax for aws payload tagging
  ddtrace/_trace/utils_botocore/aws_payload_tagging.py
  tests/contrib/botocore/test.py
  tests/snapshots/tests.contrib.botocore.test.BotocoreTest.test_aws_payload_tagging_sqs_invalid_config.json
Labels: changelog/no-changelog

#13934 ci: add gitlab.github-access.read octo-sts policy
  .github/chainguard/gitlab.github-access.read.sts.yaml
Labels: changelog/no-changelog

#13864 feat: set span resource name on 404 status code
  ddtrace/contrib/_fastapi.py
  ddtrace/contrib/_starlette.py
  ddtrace/contrib/asgi.py
  ddtrace/contrib/internal/asgi/middleware.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/fastapi/patch.py
  ddtrace/contrib/internal/starlette/patch.py
  releasenotes/notes/asgi-resource-obfuscation-404-d77e8abd660c8132.yaml
  tests/contrib/fastapi/test_fastapi.py
  tests/snapshots/tests.contrib.fastapi.test_fastapi.test_invalid_path_with_obfuscation_enabled.json
Labels: mergequeue-status: removed

#13953 ci(profiling): split v1 and v2 profiling gitlab jobs
  tests/profiling/suitespec.yml
Labels: changelog/no-changelog

#13918 chore(rc): centralize tracing logic, improve debug logging, improve perf
  ddtrace/_trace/product.py
  ddtrace/settings/_config.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/test_settings.py
Labels: changelog/no-changelog

#13949 ci: fix subject pattern for dd-octo-sts chainguard
  .github/chainguard/gitlab.github-access.read.sts.yaml
Labels: changelog/no-changelog

#13954 ci(benchmarks): increase otelspan-start-finish-telemetry slo threshold
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
Labels: changelog/no-changelog

#13939 chore(ci): riotize-threats-fastapi
  .riot/requirements/13b7789.txt
  .riot/requirements/184912e.txt
  .riot/requirements/19024d0.txt
  .riot/requirements/1b02ea2.txt
  .riot/requirements/206be6b.txt
  .riot/requirements/40adc31.txt
  .riot/requirements/410afd4.txt
  .riot/requirements/820f02e.txt
  .riot/requirements/bf3c54f.txt
  hatch.toml
  riotfile.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM, CI

#13961 ci(benchmarks): bump lower bounds for max_rss_usage SLOs
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
Labels: changelog/no-changelog

#13927 ci: re-enable pytest output capture
  .gitlab/tests.yml
Labels: changelog/no-changelog

#13944 chore(profiling): de-flake test_accuracy_stack_v2
  tests/profiling_v2/test_accuracy.py
Labels: changelog/no-changelog

#13745 chore(tracing): avoid resetting Tracer.enabled in Tracer._recreate
  ddtrace/_trace/tracer.py
  ddtrace/internal/ci_visibility/recorder.py
Labels: changelog/no-changelog

#13968 chore(llmobs): add internal support for creating/getting projects
  ddtrace/llmobs/_experiment.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/conftest.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_filter_name__test-project_get_068dd9a1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_post_954d8c3a.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#13906 fix(tracing): ensure tracer.wrap preserves decorated function’s type
  ddtrace/_trace/tracer.py
  releasenotes/notes/fix-tracer-wrap-return-type-c9436d6861451dab.yaml
Labels: backport 3.10

#13989 ci: update system-tests GitHub Actions ref
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#13874 chore(llmobs): dac strip io from gemini
  ddtrace/contrib/internal/google_generativeai/_utils.py
  ddtrace/contrib/internal/google_generativeai/patch.py
  ddtrace/llmobs/_integrations/gemini.py
  ddtrace/llmobs/_integrations/utils.py
  releasenotes/notes/remove-io-data-from-span-gemini-integration-743cc458841345b4.yaml
  tests/contrib/google_generativeai/test_google_generativeai.py
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_error.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_image.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_multiple_messages.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_stream.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_system_prompt.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_completion_tool_stream.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_tool_chat_completion.json
  tests/snapshots/tests.contrib.google_generativeai.test_google_generativeai.test_gemini_tool_completion.json
Labels: mergequeue-status: in_progress

#13970 chore(llmobs): support running experiment tasks
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_experiment.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_3bf4897d-e6aa-43a3-8d9c-5097b1f85177_batch_update_post_2d58a82a.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_67c7b6cc-ce98-481e-ab9b-e4925564826c_batch_update_post_a1f44751.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_264c9f32.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_d28fa230.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_35e295b1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_3f098e52.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#13995 chore(llmobs): reuse same test dataset when possible for tests
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_c612a61a-5767-4648-98c5-fb8104410ab0_batch_update_post_1623236d.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_c612a61a-5767-4648-98c5-fb8104410ab0_records_get_222449ee.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_15d029c8.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_2de64e8d.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_65ce9d57.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_7447d90e.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_78173c17.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_b1f2156a.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_b982c657.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_d0a96dc4.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_e1a74b2a.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_e6cafdd3.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_df56b404-42a2-4a55-aaec-702c83a152f3_records_get_30014a3a.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-123_get_cc52ad7e.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-non-existent_get_ceb7b7a1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-test_dataset_pull_exists_but_no_records_test_dataset_records0__get_03cb6caa.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-test_dataset_pull_exists_with_record_test_dataset_records0__get_d73f7f37.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_01805683.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_16472f5b.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_1fb5a6c8.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_2e28c7aa.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_816b83e0.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_8c9a6c97.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_b608e082.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_c0b85115.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_d4d46ca3.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_post_1491c356.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_post_a0c42048.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_filter_name__test-project_get_068dd9a1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_post_954d8c3a.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#13974 chore(ci): remove unused integration_test from hatch
  hatch.toml
Labels: changelog/no-changelog, CI

#13964 chore(profiling): remove unneeded variable and clean up related code
  ddtrace/internal/datadog/profiling/dd_wrapper/include/profile.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
  tests/profiling_v2/collector/test_threading.py
  tests/profiling_v2/test_main.py
Labels: changelog/no-changelog

#13975 chore(ci): riotize appsec_integrations_packages
  .riot/requirements/13b38fc.txt
  .riot/requirements/72029dd.txt
  .riot/requirements/8f3133c.txt
  .riot/requirements/eca9f2c.txt
  .riot/requirements/f16bd61.txt
  .riot/requirements/fa40758.txt
  hatch.toml
  riotfile.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM, CI

#14010 chore(llmobs): remove unnecessary dne cassettes
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_4698b07a-7bf6-4f65-9690-6bd481718459_batch_update_post_30b0318a.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_757f4529-ce99-4c10-ab9c-4c389b47839c_batch_update_post_2364f6ec.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_757f4529-ce99-4c10-ab9c-4c389b47839c_records_get_0e905550.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_95bfb2a6-377e-4a79-83ef-487f335aa3f6_records_get_06efe1ce.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_54bdcde9.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_6f8ca929.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_d0a96dc4.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_d930d168.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_e1a74b2a.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_delete_post_f256ad79.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-123_get_cc52ad7e.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-non-existent_get_ceb7b7a1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_filter_name__test-dataset-test_dataset_pull_exists_but_no_records_test_dataset_records0__get_03cb6caa.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_01805683.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_16472f5b.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_35e295b1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_datasets_post_816b83e0.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_post_1491c356.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_experiments_post_6e439ce3.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_filter_name__test-project_get_068dd9a1.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_post_954d8c3a.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14005 ci: bump otelspan start-finish rss slo
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
Labels: changelog/no-changelog

#13894 chore: refactor SpanAggregator <> TraceWriter interface
  ddtrace/_trace/processor/__init__.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/writer/__init__.py
  ddtrace/internal/writer/writer.py
  tests/utils.py
Labels: changelog/no-changelog

#14009 chore(internal): add after_in_parent forksafe hook
  ddtrace/internal/forksafe.py
  tests/internal/test_forksafe.py
Labels: changelog/no-changelog

#14016 chore(profiling): sort pprof files using creation timestamp
  tests/profiling/collector/pprof_utils.py
  tests/profiling/collector/test_stack.py
  tests/profiling/collector/test_stack_asyncio.py
  tests/profiling/test_main.py
  tests/profiling/utils.py
  tests/profiling_v2/collector/test_asyncio.py
  tests/profiling_v2/collector/test_memalloc.py
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/collector/test_stack_asyncio.py
  tests/profiling_v2/collector/test_threading.py
  tests/profiling_v2/collector/test_threading_asyncio.py
  tests/profiling_v2/test_accuracy.py
  tests/profiling_v2/test_gunicorn.py
  tests/profiling_v2/test_main.py
  tests/profiling_v2/test_pytorch.py
  tests/profiling_v2/test_uwsgi.py
Labels: changelog/no-changelog, Profiling

#13649 fix(profiling): make explicitly marked main packages "my code"
  ddtrace/internal/datadog/profiling/code_provenance.py
  releasenotes/notes/profiling-main-package-my-code-f650101b736c412e.yaml
  tests/profiling_v2/test_code_provenance.py
Labels: backport 3.10

#14015 chore: refactor scripts/perf-run-scenario
  scripts/perf-run-scenario
Labels: changelog/no-changelog

#14003 chore(ci): riotize pytest_plugin_v2
  .riot/requirements/10fafcd.txt
  .riot/requirements/12cf79a.txt
  .riot/requirements/12d9f7a.txt
  .riot/requirements/157020e.txt
  .riot/requirements/180a759.txt
  .riot/requirements/19de119.txt
  .riot/requirements/3895842.txt
  .riot/requirements/5d311fc.txt
  .riot/requirements/db4e80f.txt
  hatch.toml
  lib-injection/sources/requirements.csv
  riotfile.py
  tests/ci_visibility/suitespec.yml
Labels: changelog/no-changelog, CI

#14043 chore(aap): change default appsec priority for standalone
  ddtrace/_trace/sampler.py
  ddtrace/internal/constants.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog, ASM

#14012 chore(profiling): upgrade profile-v2 suite deps
  .riot/requirements/10ba61c.txt
  .riot/requirements/137ea60.txt
  .riot/requirements/1387420.txt
  .riot/requirements/17d21ee.txt
  .riot/requirements/187c22a.txt
  .riot/requirements/1cc2767.txt
  .riot/requirements/1eded52.txt
  .riot/requirements/1f567de.txt
  .riot/requirements/3a2a320.txt
  .riot/requirements/4cb36fa.txt
  .riot/requirements/777f0da.txt
  .riot/requirements/8986269.txt
  .riot/requirements/8dbdfca.txt
  .riot/requirements/9bb19fe.txt
  .riot/requirements/b830c42.txt
  .riot/requirements/d667cb4.txt
  .riot/requirements/e576139.txt
  .riot/requirements/ee8eca7.txt
  .riot/requirements/fe18dc8.txt
Labels: changelog/no-changelog

#14031 fix(docs): update log injection support
  ddtrace/contrib/_logging.py
  docs/configuration.rst
  releasenotes/notes/feat-log-injection-enabled-by-default-395259b0419c7a5f.yaml
Labels: backport 3.10

#14058 perf: avoid unncessary calls to Span.finished in _update_active
  ddtrace/_trace/provider.py
Labels: changelog/no-changelog

#14056 chore(llmobs): submit experiment spans to experiment scope
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_experiment.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#13091 chore(tracing): break circular imports and remove python2 types
  ddtrace/_hooks.py
  ddtrace/_trace/context.py
  ddtrace/_trace/filters.py
  ddtrace/_trace/pin.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/sampling_rule.py
  ddtrace/_trace/span.py
  ddtrace/_trace/trace_handlers.py
  ddtrace/_trace/tracer.py
  ddtrace/internal/sampling.py
  tests/tracer/test_sampler.py
Labels: changelog/no-changelog

#14064 docs: make code origin configuration recursive
  docs/configuration.rst
Labels: changelog/no-changelog, Dynamic Instrumentation

#14078 docs: fix release note formatting
  releasenotes/notes/profiling-main-package-my-code-f650101b736c412e.yaml
Labels: changelog/no-changelog

#13488 chore(lib): reduce noise in debug logs
  ddtrace/_logger.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/tracer.py
  ddtrace/bootstrap/preload.py
  ddtrace/internal/debug.py
  ddtrace/internal/gitmetadata.py
  ddtrace/internal/remoteconfig/_subscribers.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/endpoint_config.py
  tests/commands/test_runner.py
  tests/integration/test_debug.py
  tests/integration/test_integration.py
  tests/tracer/test_gitmetadata.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog

#14051 chore: update 2.21s system-tests version
  .github/workflows/system-tests.yml
  .gitlab-ci.yml
  .gitlab/one-pipeline.locked.yml
Labels: changelog/no-changelog

#14034 perf: cache trace_id_64bits when encoding
  ddtrace/internal/_encoding.pyx
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog

#14093 chore(llmobs): replace project get with project create
  ddtrace/llmobs/_experiment.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_post_954d8c3a.yaml
  tests/llmobs/llmobs_cassettes/datadog/datadog_api_unstable_llm-obs_v1_projects_post_ddce0a64.yaml
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14089 chore(ci_visibility): change unexpected coverage format error logging
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  tests/contrib/pytest/test_pytest.py
Labels: changelog/no-changelog, CI App

#14042 refactor: `encoder.encode()` to return a list of tuples
  ddtrace/internal/_encoding.pyi
  ddtrace/internal/_encoding.pyx
  ddtrace/internal/ci_visibility/encoder.py
  ddtrace/internal/writer/writer.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/test_encoder.py
  tests/ci_visibility/test_is_user_provided_service.py
  tests/contrib/pytest/test_pytest.py
  tests/integration/test_integration.py
  tests/integration/utils.py
  tests/tracer/test_encoders.py
  tests/tracer/test_writer.py
  tests/tracer/test_writer_encoder_multiple_payloads.py
  tests/utils.py
Labels: changelog/no-changelog

#13826 chore(rc): avoid expires parsing [backport 2.21]
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/utils/time.py
  tests/internal/test_utils_time.py
Labels: changelog/no-changelog

#14101 chore(profiling): remove _force_legacy_exporter code
  ddtrace/settings/profiling.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#14087 ci: update system-tests ref [backport 3.10]
  .github/workflows/system-tests.yml
  pyproject.toml
Labels: changelog/no-changelog

#14032 chore(logging): make log injection config a boolean
  .github/workflows/system-tests.yml
  ddtrace/_logger.py
  ddtrace/_trace/product.py
  ddtrace/contrib/internal/logbook/patch.py
  ddtrace/contrib/internal/logging/patch.py
  ddtrace/contrib/internal/loguru/patch.py
  ddtrace/contrib/internal/structlog/patch.py
  ddtrace/settings/_config.py
  tests/commands/test_runner.py
  tests/contrib/logging/test_logging.py
  tests/contrib/logging/test_tracer_logging.py
  tests/contrib/starlette/test_starlette.py
  tests/integration/test_debug.py
  tests/integration/test_settings.py
  tests/internal/test_settings.py
  tests/telemetry/test_writer.py
  tests/tracer/test_settings.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#14116 ci: re-enable mutli-os-tests for windows + Python 3.13
  .github/workflows/unit_tests.yml
Labels: changelog/no-changelog

#14106 chore: update testrunner image to use non-root user
  docker/Dockerfile
Labels: changelog/no-changelog

#14120 ci: disable itr on sensitive jobs
  riotfile.py
Labels: changelog/no-changelog, CI

#14118 feat(appsec): enable api security for lambda
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_processor.py
  ddtrace/settings/asm.py
Labels: changelog/no-changelog, ASM

#14065 chore(ci_visibility): proper payload split by size
  ddtrace/internal/ci_visibility/encoder.py
  tests/ci_visibility/test_encoder.py
Labels: changelog/no-changelog, CI App

#14128 chore: enable build speed-ups by default
  .gitlab/templates/cached-testrunner.yml
  docker-compose.yml
  docs/build_system.rst
  scripts/perf-run-scenario
  setup.py
Labels: changelog/no-changelog

#14134 chore(llmobs): add experiment url
  ddtrace/llmobs/_experiment.py
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14131 chore(aap): vendorising xmltodict
  .github/workflows/system-tests.yml
  .riot/requirements/10bbdbd.txt
  .riot/requirements/1264aaa.txt
  .riot/requirements/12e46bc.txt
  .riot/requirements/13c252f.txt
  .riot/requirements/173d987.txt
  .riot/requirements/5aa84db.txt
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_http_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/internal/django/utils.py
  ddtrace/internal/utils/http.py
  ddtrace/vendor/__init__.py
  ddtrace/vendor/xmltodict.py
  lib-injection/sources/requirements.csv
  pyproject.toml
  requirements.csv
  riotfile.py
  tests/appsec/appsec/test_ddwaf_fuzz.py
Labels: changelog/no-changelog, ASM

#14142 chore: fix testrunner datadog-ci install + add uv + python 3.14
  docker/.python-version
  docker/Dockerfile
Labels: changelog/no-changelog

#14138 chore(llmobs): add tool datatypes
  ddtrace/llmobs/_utils.py
  ddtrace/llmobs/utils.py
Labels: changelog/no-changelog

#14140 chore(profiling): drop windows support
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/profiling/bootstrap/sitecustomize.py
  releasenotes/notes/profiling-windows-421799a33aec60eb.yaml
  setup.py
  tests/smoke_test.py
Labels: Profiling

#14129 perf(django): reduce number of config.django getattr lookups
  ddtrace/contrib/internal/django/patch.py
Labels: changelog/no-changelog

#14155 docs: fix failing doc builds
  docs/conf.py
Labels: changelog/no-changelog, backport 3.11

#14145 fix(ddtrace_api): avoid clobbering ddtrace_api's stored tracer instance
  ddtrace/contrib/internal/ddtrace_api/patch.py
  releasenotes/notes/ddtraceapi-clobber-809a4d88df9a29dc.yaml
Labels: backport 3.11

#14117 chore: clean up ssi telemetry metrics
  lib-injection/sources/sitecustomize.py
  tests/lib_injection/conftest.py
  tests/lib_injection/test_guardrails.py
Labels: changelog/no-changelog, mergequeue-status: in_progress

#14158 ci: install libenchant in base image
  docker/Dockerfile
Labels: changelog/no-changelog

#14159 chore(llmobs): add underlying support for tool definitions
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_llmobs.py
  tests/llmobs/_utils.py
Labels: changelog/no-changelog

#14157 chore(docs): update opentelemetry doc for span events support
  ddtrace/opentelemetry/__init__.py
Labels: changelog/no-changelog

#14146 perf(span): deprecate Span._pprint, use repr and fstrings instead
  ddtrace/_trace/_span_link.py
  ddtrace/_trace/_span_pointer.py
  ddtrace/_trace/context.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/sampling_rule.py
  ddtrace/_trace/span.py
  ddtrace/_trace/tracer.py
  ddtrace/contrib/internal/celery/app.py
  ddtrace/internal/glob_matching.py
  ddtrace/internal/rate_limiter.py
  tests/integration/test_debug.py
  tests/tracer/test_encoders.py
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#14181 chore(ci): building base images
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#14182 fix(langgraph): properly support `langgraph>=0.6.0` to avoid `ModuleNotFoundError` when patching
  .riot/requirements/11029c2.txt
  .riot/requirements/125dc45.txt
  .riot/requirements/158a309.txt
  .riot/requirements/1775c38.txt
  .riot/requirements/18eaa2d.txt
  .riot/requirements/1d59ef9.txt
  .riot/requirements/1d7357f.txt
  .riot/requirements/1ea3336.txt
  .riot/requirements/1f9e62b.txt
  .riot/requirements/351e483.txt
  .riot/requirements/91c9dfa.txt
  .riot/requirements/a331a88.txt
  .riot/requirements/a950a7b.txt
  .riot/requirements/aa478d5.txt
  .riot/requirements/d65ebe1.txt
  .riot/requirements/e5ffdaa.txt
  .riot/requirements/f1266b6.txt
  .riot/requirements/f25aee2.txt
  .riot/requirements/f46c97a.txt
  .riot/requirements/f535f64.txt
  ddtrace/contrib/internal/langgraph/patch.py
  releasenotes/notes/langgraph-0.6.0-support-46c6ac5fcf810105.yaml
  tests/contrib/langgraph/test_langgraph_patch.py
Labels: backport 3.11

#13935 chore(llmobs/langchain): stop using in-process vcr
  tests/contrib/langchain/cassettes/lcel_openai_chain_call.yaml
  tests/contrib/langchain/cassettes/lcel_openai_chain_nested.yaml
  tests/contrib/langchain/cassettes/lcel_openai_chain_schema_io.yaml
  tests/contrib/langchain/cassettes/openai_completion_non_ascii.yaml
  tests/contrib/langchain/conftest.py
  tests/contrib/langchain/test_langchain.py
  tests/contrib/langchain/test_langchain_llmobs.py
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_3c0e4b6c.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_5db41b2a.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_930afee9.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_a1bd9cc3.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_b979ad33.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_chat_completions_post_e16811d2.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_09f7a946.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_585b2ba8.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_7b116e69.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_8706eb93.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_8899bb88.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_8b80b4c0.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_a23a180e.yaml
  tests/llmobs/llmobs_cassettes/openai/openai_completions_post_b2bf069e.yaml
Labels: changelog/no-changelog

#14156 chore: update codeowners
  .github/CODEOWNERS
Labels: changelog/no-changelog

#14152 ci: update testrunner and use dd-octo-sts everywhere
  .coveragerc
  .github/workflows/requirements-locks.yml
  .gitlab-ci.yml
  .gitlab/benchmarks/microbenchmarks.yml
  .gitlab/templates/build-base-venvs.yml
  .gitlab/templates/cached-testrunner.yml
  .gitlab/testrunner.yml
  .gitlab/tests.yml
  .riot/requirements/1336cbd.txt
  .riot/requirements/192e4d0.txt
  .riot/requirements/1e70094.txt
  .riot/requirements/26b7f73.txt
  .riot/requirements/3348fe3.txt
  .riot/requirements/95aa957.txt
  .riot/requirements/97d2271.txt
  .riot/requirements/b436a4c.txt
  .riot/requirements/b56d9af.txt
  .riot/requirements/d7f052d.txt
  docker-compose.yml
  scripts/ddtest
  scripts/docs/install.sh
  scripts/gen_gitlab_config.py
  scripts/needs_testrun.py
  tests/ci_visibility/util.py
  tests/contrib/mariadb/test_mariadb.py
Labels: changelog/no-changelog

#14196 chore(llmobs): support other sites when printing url
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_experiment.py
  tests/llmobs/test_experiments.py
Labels: changelog/no-changelog

#14137 chore(tracer): enhanced debug logging for sampling and span processing
  .gitlab/benchmarks/bp-runner.microbenchmarks.fail-on-breach.yml
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/sampler.py
  ddtrace/internal/writer/writer.py
  tests/integration/test_integration.py
Labels: changelog/no-changelog
