Repository DataDog/dd-trace-py, pull requests merged in 2025-02, with the labels that each got.

#12127 feat(iast): add support for pymysql, mysqldb integrations
  .gitlab/services.yml
  .riot/requirements/106990f.txt
  .riot/requirements/1140d28.txt
  .riot/requirements/1568a2f.txt
  .riot/requirements/16a770c.txt
  .riot/requirements/18c560e.txt
  .riot/requirements/1aedbda.txt
  .riot/requirements/4628049.txt
  .riot/requirements/58881b9.txt
  .riot/requirements/63b44e2.txt
  .riot/requirements/8fd54b8.txt
  .riot/requirements/aba89a0.txt
  ddtrace/appsec/_iast/_evidence_redaction/sql_sensitive_analyzer.py
  ddtrace/appsec/_iast/constants.py
  releasenotes/notes/feat-iast-pymysql-support-d7f79f0355bb85d1.yaml
  riotfile.py
  tests/appsec/iast/fixtures/taint_sinks/sql_injection_mysqldb.py
  tests/appsec/iast/fixtures/taint_sinks/sql_injection_pymysql.py
  tests/appsec/iast/taint_sinks/test_sql_injection.py
  tests/appsec/suitespec.yml
Labels: ASM

#12194 ci: skip current flaky tests
  tests/contrib/langchain/test_langchain.py
Labels: changelog/no-changelog, CI

#12184 chore(asm): don't load appsec modules (iast) if disabled
  ddtrace/_monkey.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_loader.py
  ddtrace/appsec/_iast/_pytest_plugin.py
  ddtrace/appsec/_iast/_utils.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/dbapi_async/__init__.py
  ddtrace/contrib/internal/fastapi/patch.py
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/contrib/internal/pytest/plugin.py
  ddtrace/contrib/internal/starlette/patch.py
  ddtrace/internal/iast/product.py
  ddtrace/settings/asm.py
  tests/appsec/iast/fixtures/integration/main_configure.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/contrib/dbapi/test_dbapi_appsec.py
Labels: changelog/no-changelog, ASM

#12198 fix(asm): make sure iast is not loaded by exploit prevention if disabled
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/_iast_request_context.py
  releasenotes/notes/no_IAST_unguarded_loading_in_common_module_patches-123cf6d3f8844823.yaml
Labels: ASM

#12206 ci(langchain): mark all llm cassette tests as flaky
  tests/contrib/langchain/cassettes/openai_embedding_query.yaml
  tests/contrib/langchain/test_langchain.py
Labels: changelog/no-changelog

#12116 feat(iast): xss vulnerability for django applications
  ddtrace/appsec/_iast/_evidence_redaction/_sensitive_handler.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/taint_sinks/xss.py
  docker-compose.yml
  releasenotes/notes/iast-feat-xss-django-6781a8b9a4092832.yaml
  tests/appsec/iast/taint_sinks/_taint_sinks_utils.py
  tests/appsec/iast/taint_sinks/test_xss_redacted.py
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/django_app/settings.py
  tests/appsec/integrations/django_tests/django_app/templates/index.html
  tests/appsec/integrations/django_tests/django_app/templates/index_autoescape.html
  tests/appsec/integrations/django_tests/django_app/templates/index_safe.html
  tests/appsec/integrations/django_tests/django_app/urls.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: ASM

#12196 chore(ci): migrate Appsec fastapi tests
  hatch.toml
  tests/appsec/integrations/fastapi_tests/__init__.py
  tests/appsec/integrations/fastapi_tests/app.py
  tests/appsec/integrations/fastapi_tests/conftest.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#12217 ci(benchmarks): fix failing microbenchmarks
  benchmarks/bm/utils.py
  benchmarks/rate_limiter/scenario.py
Labels: changelog/no-changelog

#12218 chore(openai): remove remaining v0 snapshot files
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[None-None].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[None-v0].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[None-v1].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[mysvc-None].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[mysvc-v0].json
  tests/snapshots/tests.contrib.openai.test_openai_v0.test_integration_service_name[mysvc-v1].json
Labels: changelog/no-changelog

#12183 chore(iast): xss vulnerability for jinja2 template engine
  ddtrace/appsec/_iast/taint_sinks/xss.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/contrib/flask/test_templates/test_insecure.html
Labels: changelog/no-changelog, ASM

#12221 chore: remove more 3.7 related code
  .github/workflows/build_deploy.yml
  ddtrace/appsec/_python_info/stdlib/__init__.py
  ddtrace/internal/wrapping/asyncs.py
  ddtrace/internal/wrapping/context.py
  ddtrace/internal/wrapping/generators.py
  lib-injection/sources/sitecustomize.py
  tests/appsec/iast_packages/test_packages.py
  tests/integration/test_debug.py
Labels: changelog/no-changelog

#12213 chore(iast): header source in werkzeug 3.1
  ddtrace/appsec/_iast/_handlers.py
  hatch.toml
  tests/appsec/integrations/flask_tests/test_iast_flask.py
Labels: changelog/no-changelog, ASM

#12223 chore(llmobs): [MLOB-1944] generalize helper for extracting token metrics
  ddtrace/llmobs/_integrations/anthropic.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/gemini.py
  ddtrace/llmobs/_integrations/openai.py
  ddtrace/llmobs/_integrations/utils.py
  ddtrace/llmobs/_integrations/vertexai.py
Labels: changelog/no-changelog

#12228 chore(iast): update xss release note
  releasenotes/notes/iast-feat-xss-django-6781a8b9a4092832.yaml
Labels: changelog/no-changelog, ASM

#12232 ci(fix): fix failing pre-check and broken tracing test
  ddtrace/_trace/tracer.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#12244 chore: update `3.x-staging` with `main`
  .gitlab/prepare-oci-package.sh
Labels: changelog/no-changelog

#12212 fix(asm): decouple appsec
  ddtrace/appsec/__init__.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/internal/httplib/patch.py
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/contrib/internal/mysql/patch.py
  ddtrace/contrib/internal/mysqldb/patch.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/plugin.py
  ddtrace/contrib/internal/requests/patch.py
  ddtrace/contrib/internal/sqlalchemy/patch.py
  ddtrace/contrib/internal/sqlite3/patch.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/contrib/internal/urllib/patch.py
  ddtrace/contrib/internal/urllib3/patch.py
  ddtrace/contrib/internal/webbrowser/patch.py
  ddtrace/internal/appsec/product.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/asm.py
  hatch.toml
  releasenotes/notes/ensure_no_appsec_loading-8ce46c58d6ecf81f.yaml
  tests/appsec/integrations/flask_tests/mini.py
  tests/appsec/integrations/flask_tests/test_appsec_loading_modules.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/contrib/subprocess/test_subprocess.py
  tests/contrib/subprocess/test_subprocess_patch.py
  tests/utils.py
Labels: ASM, backport 3.0

#12235 ci(tracer): avoids shutting down the global tracer in the main process
  tests/tracer/test_propagation.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog, backport 3.0

#12242 chore(iast): more sqli redaction tests
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/django_app/urls.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#12238 chore(iast): xss vulnerability for jinja2
  ddtrace/appsec/_iast/taint_sinks/xss.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
Labels: changelog/no-changelog, ASM

#12247 chore: use guess-next-dev instead of release-branch-semver [3.0]
  pyproject.toml
Labels: changelog/no-changelog

#12028 chore(di): add @key and @value to collection expressions
  ddtrace/debugging/_expressions.py
  tests/debugging/test_expressions.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12231 feat(symdb): enable by default
  ddtrace/settings/symbol_db.py
  releasenotes/notes/feat-symdb-enabled-by-default-25eebb43fc8c5a0d.yaml
  tests/telemetry/test_writer.py
Labels: Dynamic Instrumentation

#12245 chore(integrations): remove deprecated internal modules [asyncio,gevent]
  ddtrace/contrib/internal/asyncio/compat.py
  ddtrace/contrib/internal/asyncio/helpers.py
  ddtrace/contrib/internal/asyncio/provider.py
  ddtrace/contrib/internal/asyncio/wrappers.py
  ddtrace/contrib/internal/gevent/provider.py
  tests/contrib/asyncio/test_tracer.py
Labels: changelog/no-changelog

#12162 chore(rc): clean up sources
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
Labels: changelog/no-changelog

#12275 Revert "fix(internal): move logging rate limiter to log filter"
  ddtrace/internal/logger.py
  releasenotes/notes/fix-internal-logging-init-6058c02b527cdf77.yaml
  tests/tracer/test_logger.py
Labels: changelog/no-changelog, backport 2.20, backport 2.21

#12053 feat(tracing): add support for inferred proxy spans to support aws api gateway tracing
  ddtrace/_trace/_inferred_proxy.py
  ddtrace/_trace/span.py
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/asgi/middleware.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/molten/wrappers.py
  ddtrace/contrib/internal/tornado/handlers.py
  ddtrace/ext/__init__.py
  ddtrace/settings/_config.py
  releasenotes/notes/add-aws-api-gateway-dabfeee3decdfd89.yaml
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/bottle/test.py
  tests/contrib/bottle/test_distributed.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/django/test_django.py
  tests/contrib/djangorestframework/test_djangorestframework.py
  tests/contrib/falcon/test_distributed_tracing.py
  tests/contrib/falcon/test_suite.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/flask/test_request.py
  tests/contrib/molten/test_molten.py
  tests/contrib/pyramid/test_pyramid.py
  tests/contrib/sanic/test_sanic.py
  tests/contrib/starlette/test_starlette.py
  tests/contrib/tornado/test_tornado_web.py
  tests/telemetry/test_writer.py
  tests/tracer/utils_inferred_spans/__init__.py
  tests/tracer/utils_inferred_spans/test_helpers.py
  tests/utils.py
Labels: mergequeue-status: removed

#12273 ci: remove benchmark-serverless-trigger check job
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#12180 fix(configurations): correctly parse `payload_tagging_services`
  ddtrace/contrib/internal/botocore/patch.py
  releasenotes/notes/correctly-parse-payload_tagging_services-794cdf0f340975e6.yaml
  tests/contrib/botocore/test.py
  tests/snapshots/tests.contrib.botocore.test.BotocoreTest.test_dynamodb_payload_tagging.json
Labels: apm:ecosystems, mergequeue-status: in_progress

#12249 chore(valkey): replace valkey/__init__.py with valkey.py
  ddtrace/contrib/valkey.py
  tests/internal/test_module.py
Labels: changelog/no-changelog

#12279 chore(tracing): remove unused imports
  ddtrace/__init__.py
  ddtrace/trace/__init__.py
Labels: changelog/no-changelog

#12277 ci: fix ci_visibility riotfile definition
  .riot/requirements/1d4e95e.txt
  riotfile.py
Labels: changelog/no-changelog

#11517 chore(ci): don't allow `main` or release branches to be interruptible
  .gitlab-ci.yml
  .gitlab/testrunner.yml
Labels: changelog/no-changelog

#12290 Revert "chore(ci): don't allow `main` or release branches to be interruptible"
  .gitlab-ci.yml
  .gitlab/testrunner.yml
Labels: changelog/no-changelog

#12291 ci: prevent segfaults in ci_visibility Python 3.8 tests
  riotfile.py
Labels: changelog/no-changelog

#12286 fix(profiling): fix crash in heap profiler due to unsigned integer wraparound
  ddtrace/profiling/collector/_memalloc_tb.h
  ddtrace/profiling/collector/_utils.h
  releasenotes/notes/fix-memalloc-traceback-array-index-wraparound-f12e4da5a7de32f2.yaml
Labels: Profiling

#10942 chore(di): trigger probes
  ddtrace/_trace/context.py
  ddtrace/contrib/internal/trace_utils.py
  ddtrace/debugging/_exception/replay.py
  ddtrace/debugging/_live.py
  ddtrace/debugging/_origin/span.py
  ddtrace/debugging/_probe/model.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/debugging/_products/live_debugger.py
  ddtrace/debugging/_session.py
  ddtrace/debugging/_signal/__init__.py
  ddtrace/debugging/_signal/collector.py
  ddtrace/debugging/_signal/model.py
  ddtrace/debugging/_signal/trigger.py
  ddtrace/debugging/_uploader.py
  ddtrace/propagation/http.py
  ddtrace/settings/live_debugging.py
  docs/configuration.rst
  pyproject.toml
  tests/debugging/conftest.py
  tests/debugging/live/__init__.py
  tests/debugging/live/test_live_debugger.py
  tests/debugging/mocking.py
  tests/debugging/origin/test_span.py
  tests/debugging/signal/test_collector.py
  tests/debugging/test_debugger_span_decoration.py
  tests/debugging/test_session.py
  tests/debugging/utils.py
  tests/submod/traced_stuff.py
  tests/tracer/test_context.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12303 fix(profiling): reduce log spam from lock collector
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/lock-log-df92d0fddb165ebe.yaml
Labels: Profiling

#12208 chore(langchain): auto-instrument with langgraph
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/contrib/internal/langgraph/patch.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/langgraph.py
Labels: changelog/no-changelog

#12148 chore: update changelog for version 2.19.3
  CHANGELOG.md
Labels: changelog/no-changelog

#12308 fix(tracer): ensure ot-baggage headers are propagated in wsgi apps
  ddtrace/propagation/http.py
  releasenotes/notes/opentracer-baggage-prefix-fix-909cd6f665eb2c84.yaml
  tests/tracer/test_propagation.py
Labels: backport 2.20, backport 3.0

#12236 feat(llmobs): llmobs-specific context manager
  ddtrace/contrib/internal/trace_utils.py
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_context.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_integrations/langgraph.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_utils.py
  ddtrace/llmobs/_writer.py
  releasenotes/notes/feat-llmobs-context-e4adabcb6894e4d8.yaml
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_propagation.py
Labels: mergequeue-status: in_progress

#12315 chore(llmobs): enable langgraph for enabled integrations
  ddtrace/llmobs/_llmobs.py
Labels: changelog/no-changelog

#11911 chore: hide chained loader methods from tracebacks
  ddtrace/internal/module.py
  tests/internal/test_module.py
  tests/submod/import_test.py
Labels: changelog/no-changelog

#12298 chore(asm): don't load appsec modules (iast)... [backport 2.20]
  ddtrace/_monkey.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_loader.py
  ddtrace/appsec/_iast/_pytest_plugin.py
  ddtrace/appsec/_iast/_utils.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/dbapi_async/__init__.py
  ddtrace/contrib/internal/fastapi/patch.py
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/contrib/internal/pytest/plugin.py
  ddtrace/contrib/internal/starlette/patch.py
  ddtrace/internal/iast/product.py
  ddtrace/settings/asm.py
  tests/appsec/iast/fixtures/integration/main_configure.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#12260 feat(config): support libdatadog's library_config for config through file
  ddtrace/__init__.py
  ddtrace/internal/native/__init__.py
  ddtrace/internal/native/_native.pyi
  src/native/Cargo.lock
  src/native/Cargo.toml
  src/native/lib.rs
  src/native/library_config.rs
  tests/internal/test_native.py
Labels: changelog/no-changelog

#12318 ci: add benchmark for ddtrace.internal.packages.update_imported_dependencies
  benchmarks/base/requirements.txt
  benchmarks/packages_update_imported_dependencies/config.yaml
  benchmarks/packages_update_imported_dependencies/requirements_scenario.txt
  benchmarks/packages_update_imported_dependencies/scenario.py
Labels: changelog/no-changelog

#12314 ci: cache build_base_venvs job
  .gitlab-ci.yml
  .gitlab/tests.yml
  scripts/gen_gitlab_config.py
  scripts/get-native-sources-hash.sh
Labels: changelog/no-changelog

#12301 ci: collapse unit/integration test jobs into a single stage
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12296 chore(ci_visibility): allow quarantining and disabling tests individually
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/api/_base.py
  ddtrace/internal/ci_visibility/api/_session.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/telemetry/events.py
  ddtrace/internal/ci_visibility/telemetry/git.py
  ddtrace/internal/ci_visibility/telemetry/test_management.py
  ddtrace/internal/test_visibility/_internal_item_ids.py
  ddtrace/internal/test_visibility/api.py
  tests/ci_visibility/api_client/_util.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client_test_management_responses.py
  tests/ci_visibility/test_quarantine.py
  tests/contrib/pytest/test_pytest_disabling.py
  tests/contrib/pytest/test_pytest_quarantine.py
Labels: changelog/no-changelog

#12300 ci: automate min_compatible_versions updates
  .github/workflows/requirements-locks.yml
  .riot/requirements/1d21cf3.txt
  .riot/requirements/4e93dc8.txt
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
  scripts/min_compatible_versions.py
Labels: changelog/no-changelog

#12293 fix(internal): move logging rate limiter to log filter
  ddtrace/internal/logger.py
  releasenotes/notes/fix-internal-logging-init-6058c02b527cdf77.yaml
  tests/tracer/test_logger.py
  tests/vendor/test_dogstatsd.py
Labels: backport 2.21

#12334 ci(flaky): mark `tests/internal/test_auto.py` with flaky for 30 days
  tests/internal/test_auto.py
Labels: changelog/no-changelog

#12332 docs: correct default value for DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED
  docs/configuration.rst
Labels: changelog/no-changelog

#12239 chore(di): ensure signals in wrapping context
  ddtrace/debugging/_debugger.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12319 fix(asm): decouple appsec [backport 2.20]
  ddtrace/appsec/__init__.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/internal/httplib/patch.py
  ddtrace/contrib/internal/mysql/patch.py
  ddtrace/contrib/internal/mysqldb/patch.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/plugin.py
  ddtrace/contrib/internal/requests/patch.py
  ddtrace/contrib/internal/sqlalchemy/patch.py
  ddtrace/contrib/internal/sqlite3/patch.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/contrib/internal/urllib/patch.py
  ddtrace/contrib/internal/urllib3/patch.py
  ddtrace/contrib/internal/webbrowser/patch.py
  ddtrace/internal/appsec/product.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/asm.py
  hatch.toml
  releasenotes/notes/ensure_no_appsec_loading-8ce46c58d6ecf81f.yaml
  tests/appsec/integrations/flask_tests/mini.py
  tests/appsec/integrations/flask_tests/test_appsec_loading_modules.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/contrib/subprocess/test_subprocess.py
  tests/contrib/subprocess/test_subprocess_patch.py
  tests/utils.py
Labels: ASM

#12317 chore(iast): relase note of #12298 [backport 2.20]
  releasenotes/notes/fix-iast-avoid-native-import-6cef954e3c98c9e8.yaml
Labels: ASM

#12304 chore(profiling): 3.13 support for v1
  .riot/requirements/1993410.txt
  .riot/requirements/1ccff62.txt
  .riot/requirements/518c01e.txt
  ddtrace/profiling/collector/stack.pyx
  riotfile.py
Labels: changelog/no-changelog

#12351 fix(asm): decouple appsec and iast [backport 2.21]
  .github/CODEOWNERS
  ddtrace/_monkey.py
  ddtrace/appsec/__init__.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_loader.py
  ddtrace/appsec/_iast/_pytest_plugin.py
  ddtrace/appsec/_iast/_utils.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/appsec/_utils.py
  ddtrace/bootstrap/preload.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/dbapi_async/__init__.py
  ddtrace/contrib/internal/fastapi/patch.py
  ddtrace/contrib/internal/httplib/patch.py
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/contrib/internal/mysql/patch.py
  ddtrace/contrib/internal/mysqldb/patch.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/plugin.py
  ddtrace/contrib/internal/requests/patch.py
  ddtrace/contrib/internal/sqlalchemy/patch.py
  ddtrace/contrib/internal/sqlite3/patch.py
  ddtrace/contrib/internal/starlette/patch.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/contrib/internal/urllib/patch.py
  ddtrace/contrib/internal/urllib3/patch.py
  ddtrace/contrib/internal/webbrowser/patch.py
  ddtrace/internal/appsec/product.py
  ddtrace/internal/iast/product.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/asm.py
  hatch.toml
  pyproject.toml
  releasenotes/notes/ensure_no_appsec_loading-8ce46c58d6ecf81f.yaml
  releasenotes/notes/fix-iast-avoid-native-import-6cef954e3c98c9e8.yaml
  releasenotes/notes/no_IAST_unguarded_loading_in_common_module_patches-123cf6d3f8844823.yaml
  tests/appsec/iast/fixtures/integration/main_configure.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/flask_tests/mini.py
  tests/appsec/integrations/flask_tests/test_appsec_loading_modules.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/contrib/subprocess/test_subprocess.py
  tests/contrib/subprocess/test_subprocess_patch.py
  tests/utils.py
Labels: ASM

#12323 chore(iast): fix IAST imports when under pytest
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/code_injection.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/appsec/_iast/taint_sinks/xss.py
  ddtrace/settings/asm.py
Labels: changelog/no-changelog, ASM

#12305 fix(ssi): do not include boto3 in min versions listing
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  releasenotes/notes/boto3-min-d282e4795f1f1631.yaml
  scripts/min_compatible_versions.py
Labels: backport 2.21

#12328 chore(tracing): refactor inferred proxy spans to not require all headers and remove span.kind
  ddtrace/_trace/_inferred_proxy.py
  tests/contrib/aiohttp/test_middleware.py
  tests/contrib/asgi/test_asgi.py
  tests/contrib/bottle/test.py
  tests/contrib/bottle/test_distributed.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/django/test_django.py
  tests/contrib/djangorestframework/test_djangorestframework.py
  tests/contrib/falcon/test_distributed_tracing.py
  tests/contrib/falcon/test_suite.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/flask/test_request.py
  tests/contrib/molten/test_molten.py
  tests/contrib/pyramid/test_pyramid.py
  tests/contrib/sanic/test_sanic.py
  tests/contrib/starlette/test_starlette.py
  tests/contrib/tornado/test_tornado_web.py
  tests/tracer/utils_inferred_spans/test_helpers.py
Labels: changelog/no-changelog

#12353 chore(ci): set name for system-tests finished job
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#12327 fix(internal): improve performance of package resolution
  .gitlab/benchmarks.yml
  ddtrace/internal/packages.py
  releasenotes/notes/fix-internal-packages-perf-c270b1ff7e68b46a.yaml
Labels: backport 3.0

#12352 fix(asm): make sure iast is not loaded by exploit prevention if disabled [backport 2.19]
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_patch.py
  releasenotes/notes/no_IAST_unguarded_loading_in_common_module_patches-123cf6d3f8844823.yaml
Labels: ASM

#12168 ci(serverless): tests for all binaries removed in sls builds.
  tests/internal/test_serverless.py
Labels: changelog/no-changelog

#12339 chore(configuration): use get_config to parse all envars used in ddtrace.config
  ddtrace/settings/_config.py
  ddtrace/settings/_core.py
  ddtrace/settings/_otel_remapper.py
  tests/opentelemetry/test_config.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#12278 fix(configuration): raises an AttributeError on undefined configs
  ddtrace/settings/_config.py
  releasenotes/notes/fix-baggage-and-config-908e08e1521cdaa3.yaml
  tests/tracer/test_global_config.py
  tests/tracer/test_trace_utils.py
  tests/utils.py
Labels: backport 3.0

#12356 ci: fix download artifacts from gh job
  .gitlab/download-wheels-from-gh-actions.sh
  .gitlab/package.yml
Labels: changelog/no-changelog

#12333 chore(pymongo): add additional asserts on resource names and mongodb.query span tag
  tests/contrib/pymongo/test.py
Labels: changelog/no-changelog

#12344 chore(ci): fix update package version workflow
  scripts/freshvenvs.py
Labels: changelog/no-changelog

#11822 ci: dump debug data about builds in CI
  .gitignore
  hatch.toml
  riotfile.py
  scripts/docs/build.sh
  setup.py
Labels: changelog/no-changelog

#12309 ci: mark existing flakes with `@flaky` and add decorator usage reporting script
  .github/workflows/report-skipped-flaky.yml
  scripts/report_skipped_flaky.py
  scripts/restructure_flaky_report.py
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
  tests/contrib/aiomysql/test_aiomysql.py
  tests/contrib/aws_lambda/test_aws_lambda.py
  tests/contrib/botocore/test.py
  tests/contrib/botocore/test_bedrock.py
  tests/contrib/mariadb/test_mariadb.py
  tests/opentelemetry/test_span.py
  tests/utils.py
Labels: changelog/no-changelog, backport 3.0

#12371 test(ci): disabling non passing tests on gitlab
  tests/profiling/collector/test_threading.py
  tests/profiling/test_main.py
Labels: changelog/no-changelog

#12269 chore(iast): update flask integration documentation
  ddtrace/appsec/_iast/__init__.py
  ddtrace/contrib/_flask.py
Labels: changelog/no-changelog, ASM

#12348 chore(asm): rename and add finished job for multiple os tests
  .github/workflows/unit_tests.yml
  hatch.toml
Labels: changelog/no-changelog, ASM, CI

#12325 chore(iast): add function and class name to vulnerability location
  ddtrace/appsec/_iast/_stacktrace.c
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/taint_sinks/test_header_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_path_traversal_redacted.py
  tests/appsec/iast/taint_sinks/test_sql_injection.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/appsec/iast/taint_sinks/test_weak_hash.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/iast_memcheck/_stacktrace_py.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/appsec/integrations/flask_tests/test_iast_langchain.py
  tests/conftest.py
Labels: changelog/no-changelog, ASM

#12379 chore(ci): increase parallelism for integrations tests
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM, CI

#12297 chore(internal): lazy module decorator
  ddtrace/internal/module.py
  tests/internal/lazy.py
  tests/internal/lazy.pyi
  tests/internal/test_module.py
Labels: changelog/no-changelog

#12382 ci(iast): enable fastapi integrations tests
  hatch.toml
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12359 chore(ci_visibility): fix debug logs for ci_visibility telemetry
  ddtrace/internal/ci_visibility/telemetry/events.py
  ddtrace/internal/ci_visibility/telemetry/git.py
Labels: changelog/no-changelog

#12329 fix(bedrock): [MLOB-2181] fix bedrock token metrics
  ddtrace/_trace/trace_handlers.py
  ddtrace/llmobs/_integrations/utils.py
  releasenotes/notes/fix-bedrock-token-location-36c21044eecce688.yaml
  tests/contrib/botocore/test_bedrock_llmobs.py
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_ai21_invoke.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_amazon_embedding.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_amazon_invoke.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_amazon_invoke_stream.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_anthropic_invoke.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_anthropic_invoke_stream.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_anthropic_message_invoke.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_anthropic_message_invoke_stream.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_cohere_embedding.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_cohere_invoke_multi_output.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_cohere_invoke_single_output.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_cohere_invoke_stream_multi_output.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_cohere_invoke_stream_single_output.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_invoke_model_using_aws_arn_model_id.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_meta_invoke.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_meta_invoke_stream.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_read_error.json
  tests/snapshots/tests.contrib.botocore.test_bedrock.test_readlines_error.json
Labels: mergequeue-status: removed

#12336 chore(ci): isolate reliability-env deploys from flakiness
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12330 fix(llmobs): [MLOB-1915] tag streamed response for errored spans
  ddtrace/contrib/internal/google_generativeai/_utils.py
  ddtrace/contrib/internal/vertexai/_utils.py
  ddtrace/llmobs/_integrations/gemini.py
  ddtrace/llmobs/_integrations/vertexai.py
  releasenotes/notes/fix-google-streamed-response-submission-94072cb2804458bf.yaml
Labels: mergequeue-status: in_progress

#12310 ci: add `retry: 2` to the `.testrunner` definition so everything inherits it
  .gitlab/testrunner.yml
  .gitlab/tests.yml
Labels: changelog/no-changelog

#12378 chore(asm): add collection mode tag for set_user sdk
  ddtrace/appsec/_trace_utils.py
  ddtrace/contrib/internal/trace_utils.py
  tests/appsec/appsec/test_appsec_trace_utils.py
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#12364 ci: add specific code owners for tests/internal/test_serverless.py
  .github/CODEOWNERS
Labels: changelog/no-changelog

#12400 chore(langgraph): update tracer.current_span with llmobs context manager check
  ddtrace/llmobs/_integrations/langgraph.py
Labels: changelog/no-changelog

#12405 chore(iast): remove print
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
Labels: changelog/no-changelog, ASM

#12390 ci(benchmarks): group benchmarks into parent-child pipelines to ease retrigerring
  .gitlab-ci.yml
  .gitlab/benchmarks/macrobenchmarks.yml
  .gitlab/benchmarks/microbenchmarks.yml
  .gitlab/benchmarks/serverless.yml
Labels: changelog/no-changelog

#12347 chore(stable_configs): refactor + collect instrumentation telemetry
  ddtrace/__init__.py
  ddtrace/internal/native/__init__.py
  ddtrace/settings/_core.py
  ddtrace/settings/_otel_remapper.py
  tests/internal/test_native.py
  tests/utils.py
Labels: changelog/no-changelog

#12411 chore: update changelog for version 2.20.2
  CHANGELOG.md
Labels: changelog/no-changelog

#12386 chore(llmobs): better span linking logic for langchain integration
  ddtrace/llmobs/_integrations/langchain.py
Labels: changelog/no-changelog

#12391 chore: update changelog for version 2.19.4, 2.20.0, 2.20.1, 2.21.0, 2.21.1
  CHANGELOG.md
Labels: changelog/no-changelog

#12413 fix(asm): improve BlockingException catch for fastapi
  ddtrace/contrib/internal/asgi/middleware.py
  releasenotes/notes/fix_blocking_on_fastapi_with_middleware-08ac58a6b112e29f.yaml
Labels: ASM, backport 2.20, backport 3.0, backport 2.21

#12421 chore(llmobs): remove integration logs and metrics functionality
  ddtrace/contrib/internal/langchain/utils.py
  ddtrace/contrib/internal/openai/utils.py
  ddtrace/llmobs/_integrations/base.py
  tests/llmobs/test_llmobs_integrations.py
Labels: changelog/no-changelog

#12387 ci(iast): migrate appsec_iast_memcheck and appsec_iast to gitlab/hatch
  .riot/requirements/106990f.txt
  .riot/requirements/1140d28.txt
  .riot/requirements/1374394.txt
  .riot/requirements/13a28e1.txt
  .riot/requirements/13f2bea.txt
  .riot/requirements/1548fc3.txt
  .riot/requirements/1568a2f.txt
  .riot/requirements/16a770c.txt
  .riot/requirements/1bbfc54.txt
  .riot/requirements/1cc4eb6.txt
  .riot/requirements/1ef581b.txt
  .riot/requirements/66c248d.txt
  .riot/requirements/8fd54b8.txt
  .riot/requirements/d0652fb.txt
  .riot/requirements/eb40d16.txt
  hatch.toml
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_replace_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_command_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_header_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_path_traversal_redacted.py
  tests/appsec/iast/taint_sinks/test_weak_hash.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/iast/test_grpc_iast.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/iast/test_loader.py
  tests/appsec/iast/test_taint_utils.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12415 fix(llmobs): fix trace id generation for llm obs for proper links to apm spans
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/langgraph.py
  ddtrace/llmobs/_llmobs.py
  releasenotes/notes/fix-llmobs-apm-link-52431ae69f9a4623.yaml
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_service.py
Labels: backport 2.20, backport 2.21

#12383 chore(internal): normalise product telemetry names
  ddtrace/internal/products.py
Labels: changelog/no-changelog

#12229 ci: enable a profiling onboarding test scenario
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12398 chore(llmobs): improve disabled log message
  ddtrace/llmobs/_constants.py
Labels: changelog/no-changelog

#12354 fix(integrations): updates error raised when ddtrace.patch(...) is called with invalid args
  ddtrace/_monkey.py
  releasenotes/notes/update-monkey-patching-error-log-91e5eb3326da2f4b.yaml
  tests/tracer/test_monkey.py
Labels: backport 2.20, backport 3.0, backport 2.21

#12437 test: include products.py in core component
  tests/suitespec.yml
Labels: changelog/no-changelog

#12401 chore: fix incorrect test name issue in flaky test script
  scripts/report_skipped_flaky.py
Labels: changelog/no-changelog, backport 3.0

#12433 chore(profiling): use unordered_map instead of map
  ddtrace/internal/datadog/profiling/dd_wrapper/include/ddup_interface.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
Labels: changelog/no-changelog, Profiling

#12384 fix(iast): cookie vulnerability cardinality issues
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_listener.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  docker-compose.yml
  releasenotes/notes/iast-fix-cookies-cardinality-f1fd2eb17f36e730.yaml
  tests/appsec/iast/taint_sinks/test_insecure_cookie.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: ASM

#12420 chore: update changelog for version 3.0.0, 2.20.2
  CHANGELOG.md
Labels: changelog/no-changelog

#12392 chore(configuration): use `get_config` to access telemetry and logging configurations
  ddtrace/__init__.py
  ddtrace/_logger.py
  ddtrace/_monkey.py
  ddtrace/_trace/sampler.py
  ddtrace/_trace/tracer.py
  ddtrace/internal/remoteconfig/worker.py
  ddtrace/internal/sampling.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/propagation/_database_monitoring.py
  ddtrace/settings/__init__.py
  ddtrace/settings/_config.py
  ddtrace/settings/_core.py
  ddtrace/settings/_otel_remapper.py
  ddtrace/settings/_telemetry.py
  ddtrace/settings/asm.py
  ddtrace/settings/crashtracker.py
  ddtrace/settings/dynamic_instrumentation.py
  ddtrace/settings/exception_replay.py
  ddtrace/settings/peer_service.py
  ddtrace/settings/profiling.py
  ddtrace/settings/symbol_db.py
  tests/contrib/logging/test_tracer_logging.py
  tests/opentelemetry/test_config.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#12434 chore(profiling): unordered_set instead of set
  ddtrace/internal/datadog/profiling/dd_wrapper/include/code_provenance.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/code_provenance.cpp
Labels: changelog/no-changelog, Profiling

#12463 fix(internal): improve performance of package resolution [backport #12327 to 2.19]
  .gitlab/benchmarks.yml
  ddtrace/internal/packages.py
  releasenotes/notes/fix-internal-packages-perf-c270b1ff7e68b46a.yaml
Labels: backport 2.19, backport 2.20, backport 3.0, backport 2.21

#12453 chore: ignore useless conversion lint warning from pyo3 (#12450)
  src/core/lib.rs
Labels: changelog/no-changelog

#12396 ci(flaky): mark tests as flaky for 30 days
  tests/contrib/asyncpg/test_asyncpg.py
  tests/contrib/botocore/test_bedrock.py
Labels: changelog/no-changelog, backport 3.0

#12466 chore: ignore useless conversion lint warning from pyo3 [#12450]
  src/native/lib.rs
Labels: changelog/no-changelog

#12459 test(httpx): fix expired httpx flaky as of Feb 2024
  tests/contrib/httpx/test_httpx.py
  tests/snapshots/tests.contrib.httpx.test_httpx.test_schematized_unspecified_service_name_env_default.json
  tests/snapshots/tests.contrib.httpx.test_httpx.test_schematized_unspecified_service_name_env_v0.json
Labels: changelog/no-changelog

#12472 ci: fix flaky script report test names being off by one
  scripts/report_skipped_flaky.py
Labels: changelog/no-changelog

#12474 test(django): update some stale skipped tests in the django suite
  tests/contrib/django/test_django.py
  tests/contrib/django/test_django_snapshots.py
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_psycopg2_query_default.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_psycopg3_query_default.json
  tests/snapshots/tests.contrib.django.test_django_snapshots.test_urlpatterns_include.json
Labels: changelog/no-changelog

#12456 test(botocore): remove flaky decorator from botocore test
  tests/contrib/botocore/test.py
Labels: changelog/no-changelog

#12479 ci(cassandra): move cassandra suite from circleci to gitlab
  .circleci/config.templ.yml
  .gitlab/services.yml
  tests/contrib/suitespec.yml
Labels: changelog/no-changelog

#12461 chore(ci): extend timestamp on flaky test decorator for grpc
  tests/contrib/grpc/test_grpc.py
Labels: changelog/no-changelog

#12011 fix(asyncio): avoid overwriting coroutine names
  ddtrace/contrib/internal/asyncio/patch.py
  releasenotes/notes/avoid-overriding-couroutine-names-0852ea19200feb74.yaml
  tests/contrib/asyncio/test_tracer.py
Labels: backport 3.0, backport 2.21

#12483 refactor(profiling): document heap profile sampling
  ddtrace/profiling/collector/_memalloc_heap.c
Labels: changelog/no-changelog

#12484 ci: circleci->gitlab for suites that use the mysql and postgres images
  .circleci/config.templ.yml
  tests/contrib/suitespec.yml
Labels: changelog/no-changelog

#12493 ci: store junit xml results to GitLab job
  .gitlab/testrunner.yml
Labels: changelog/no-changelog

#12057 feat: integration with dd-trace-api
  .riot/requirements/10e65d1.txt
  .riot/requirements/1261872.txt
  .riot/requirements/14d1688.txt
  .riot/requirements/668f2f5.txt
  .riot/requirements/d5f777e.txt
  .riot/requirements/e49670c.txt
  ddtrace/_monkey.py
  ddtrace/contrib/internal/dd_trace_api/__init__.py
  ddtrace/contrib/internal/dd_trace_api/patch.py
  riotfile.py
  scripts/min_compatible_versions.py
  tests/contrib/dd_trace_api/__init__.py
  tests/contrib/dd_trace_api/test_dd_trace_api_patch.py
  tests/contrib/dd_trace_api/test_integration.py
  tests/contrib/suitespec.yml
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_current_root_span.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_current_span.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_exc_info_caught.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_set_exc_info.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_set_tags.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_set_traceback.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_span_finish.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_span_finish_with_ancestors.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_start_span.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_trace.json
  tests/snapshots/tests.contrib.dd_trace_api.test_integration.DDTraceAPITestCase.test_wrap.json
Labels: changelog/no-changelog

#12490 chore: do not return default service if config.service was user set and equals inferred service
  ddtrace/settings/_config.py
  tests/internal/service_name/test_inferred_base_service.py
Labels: changelog/no-changelog

#12488 chore(ci): add package resolution test
  hatch.toml
  tests/appsec/architectures/mini.py
  tests/appsec/architectures/test_appsec_loading_modules.py
Labels: changelog/no-changelog, ASM

#12432 feat(asm): asm standalone v2
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/propagation/http.py
  ddtrace/settings/asm.py
  releasenotes/notes/asm-standalone-v2-upgrade.yaml
  tests/appsec/appsec/test_asm_standalone.py
  tests/appsec/appsec_utils.py
  tests/appsec/integrations/flask_tests/test_gunicorn_handlers.py
  tests/contrib/requests/test_requests_distributed.py
  tests/contrib/urllib3/test_urllib3.py
  tests/integration/test_trace_stats.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/telemetry/test_writer.py
  tests/tracer/test_propagation.py
  tests/tracer/test_tracer.py
Labels: ASM

#12426 chore(ci): add notification channel for build pipeline
  .gitlab-ci.yml
Labels: changelog/no-changelog, CI, backport 2.19, backport 2.20, backport 3.0, backport 2.21

#12503 chore(docs): update docs to reflect changes in tracer.configure()
  ddtrace/_trace/tracer.py
Labels: changelog/no-changelog

#11115 chore(telemetry): configuration telemetry reporting
  .riot/requirements/1215c62.txt
  .riot/requirements/16af7e0.txt
  .riot/requirements/17cd03c.txt
  .riot/requirements/1842297.txt
  .riot/requirements/19a8ed0.txt
  .riot/requirements/1c89113.txt
  .riot/requirements/1dcfbb2.txt
  .riot/requirements/1f27343.txt
  .riot/requirements/1f3d2c7.txt
  .riot/requirements/1f540f4.txt
  .riot/requirements/22104c1.txt
  .riot/requirements/46e7fca.txt
  .riot/requirements/4ef6c1c.txt
  .riot/requirements/5b09682.txt
  .riot/requirements/a031170.txt
  .riot/requirements/bd5e098.txt
  .riot/requirements/d825572.txt
  .riot/requirements/e1faa28.txt
  ddtrace/settings/_telemetry.py
  ddtrace/settings/peer_service.py
  hatch.toml
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  pyproject.toml
  riotfile.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, backport 2.20, backport 3.0, backport 2.21, backport 3.1

#12510 chore: update changelog for version 2.21.3
  CHANGELOG.md
Labels: changelog/no-changelog

#12521 chore(telemetry): configuration telemetry reporting (backport #11115 to 3.1)
  .riot/requirements/1215c62.txt
  .riot/requirements/16af7e0.txt
  .riot/requirements/17cd03c.txt
  .riot/requirements/1842297.txt
  .riot/requirements/19a8ed0.txt
  .riot/requirements/1c89113.txt
  .riot/requirements/1dcfbb2.txt
  .riot/requirements/1f27343.txt
  .riot/requirements/1f3d2c7.txt
  .riot/requirements/1f540f4.txt
  .riot/requirements/22104c1.txt
  .riot/requirements/46e7fca.txt
  .riot/requirements/4ef6c1c.txt
  .riot/requirements/5b09682.txt
  .riot/requirements/a031170.txt
  .riot/requirements/bd5e098.txt
  .riot/requirements/d825572.txt
  .riot/requirements/e1faa28.txt
  ddtrace/settings/_telemetry.py
  ddtrace/settings/peer_service.py
  hatch.toml
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  pyproject.toml
  riotfile.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#12515 chore(runtime metrics): fix telemetry reporting
  .github/CODEOWNERS
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/runtime/__init__.py
  tests/runtime/test_runtime_metrics_api.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, backport 3.1

#12465 ci(iast): enable iast propagation tests
  .riot/requirements/107c269.txt
  .riot/requirements/1215c62.txt
  .riot/requirements/15efbfc.txt
  .riot/requirements/401494c.txt
  .riot/requirements/5e31227.txt
  .riot/requirements/b0c2747.txt
  .riot/requirements/bd5e098.txt
  hatch.toml
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
  tests/appsec/iast_tdd_propagation/test_flask.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12414 refactor(rc): accept capabilities on product registration
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
  ddtrace/settings/_config.py
  tests/appsec/architectures/test_appsec_loading_modules.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
Labels: changelog/no-changelog

#12505 fix: the name of the span events in record_exception should be exception
  ddtrace/_trace/span.py
  releasenotes/notes/fix-exception-events-name-34fcaa4d49987935.yaml
Labels: backport 3.1

#12377 refactor(trace): generic byte code injection for Python 3.10, 3.11 (AIDM-380)
  .github/workflows/test_frameworks.yml
  ddtrace/debugging/_function/store.py
  ddtrace/internal/bytecode_injection/__init__.py
  ddtrace/internal/bytecode_injection/core.py
  ddtrace/internal/coverage/instrumentation_py3_10.py
  ddtrace/internal/coverage/instrumentation_py3_11.py
  ddtrace/internal/coverage/instrumentation_py3_12.py
  ddtrace/internal/coverage/instrumentation_py3_13.py
  ddtrace/internal/coverage/instrumentation_py3_8.py
  tests/debugging/exploration/_coverage.py
  tests/debugging/exploration/_profiler.py
  tests/debugging/exploration/debugger.py
  tests/debugging/exploration/utils.py
  tests/internal/bytecode_injection/framework_injection/__init__.py
  tests/internal/bytecode_injection/framework_injection/_bytecode_injection.py
  tests/internal/bytecode_injection/framework_injection/_config.py
  tests/internal/bytecode_injection/framework_injection/output.py
  tests/internal/bytecode_injection/framework_injection/preload.py
  tests/internal/bytecode_injection/framework_injection/sitecustomize.py
  tests/internal/bytecode_injection/framework_injection/test_bootstrap.py
  tests/internal/bytecode_injection/framework_injection/utils.py
  tests/internal/bytecode_injection/test_core.py
  tests/internal/bytecode_injection/test_injection.py
  tests/suitespec.yml
Labels: changelog/no-changelog

#12516 ci: move consul, mariadb, mongoengine suites to gitlab
  .circleci/config.templ.yml
  .gitlab/services.yml
  tests/contrib/consul/test.py
  tests/contrib/suitespec.yml
Labels: changelog/no-changelog, CI

#12536 chore(iast): fix wheel build error on macOS
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  setup.py
  tests/smoke_test.py
Labels: changelog/no-changelog, ASM, backport 2.19, backport 2.20, backport 3.0, backport 2.21, backport 3.1

#12509 feat: fast build environment variables
  .circleci/config.templ.yml
  .gitlab/tests.yml
  ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/tests/CMakeLists.txt
  hatch.toml
  scripts/gen_gitlab_config.py
  setup.py
Labels: changelog/no-changelog

#12531 ci: move build_docs to gitlab
  .circleci/config.templ.yml
  .gitignore
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog

#12518 ci: move aws_lambda, datastreams, and opentelemetry suites to gitlab
  .circleci/config.templ.yml
  .gitlab/services.yml
Labels: changelog/no-changelog

#12538 chore: run the smoke test at the end of build_base_venvs
  .riot/requirements/10e0b19.txt
  .riot/requirements/164d1f0.txt
  .riot/requirements/2377901.txt
  .riot/requirements/7ffd29a.txt
  .riot/requirements/872f397.txt
  .riot/requirements/fc72580.txt
  riotfile.py
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog, ASM, backport 2.19, backport 2.20, backport 3.0, backport 2.21, backport 3.1

#12498 ci: move botocore suite to gitlab
  .circleci/config.templ.yml
  .gitlab/services.yml
  tests/contrib/suitespec.yml
Labels: changelog/no-changelog

#11888 ci(serverless): force reimport of modules during serverless test
  tests/internal/test_serverless.py
Labels: changelog/no-changelog

#12548 chore(config): remove unused configurations
  ddtrace/settings/_config.py
Labels: changelog/no-changelog

#12542 chore(iast): fix wheel build error on macOS [backport 2.21]
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  setup.py
  tests/smoke_test.py
Labels: changelog/no-changelog, ASM

#12544 chore(iast): fix wheel build error on macOS [backport 2.19]
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  setup.py
  tests/smoke_test.py
Labels: changelog/no-changelog, ASM

#12543 chore(iast): fix wheel build error on macOS [backport 2.20]
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  setup.py
  tests/smoke_test.py
Labels: changelog/no-changelog, ASM

#12486 ci(pyramid): fix flaky test for pyramid as of Feb 2025
  tests/contrib/pyramid/pserve_app/development.ini
  tests/contrib/pyramid/test_pyramid.py
  tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint[ddtrace-run_pserve_tests_contrib_pyramid_pserve_app_development.ini].json
  tests/snapshots/tests.contrib.pyramid.test_pyramid.test_simple_pyramid_app_endpoint[ddtrace-run_python_tests_contrib_pyramid_app_app.py].json
Labels: changelog/no-changelog
