Repository DataDog/dd-trace-py, pull requests merged in 2025-03, with the labels that each got.

#12508 chore(iast): fix stacktrace leak in flask
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_taint_tracking/_errors.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/taint_sinks/stacktrace_leak.py
  ddtrace/contrib/internal/flask/patch.py
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast/taint_sinks/test_stacktrace_leak.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
  tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
Labels: changelog/no-changelog, ASM

#12590 chore: run the smoke test at the end of build_base_venvs [backport 3.0]
  .gitlab/tests.yml
  .riot/requirements/10e0b19.txt
  .riot/requirements/164d1f0.txt
  .riot/requirements/2377901.txt
  .riot/requirements/7ffd29a.txt
  .riot/requirements/872f397.txt
  .riot/requirements/fc72580.txt
  riotfile.py
Labels: changelog/no-changelog

#12599 ci(fix): manually install `libatomic.i686` before `rustup` script
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, backport 3.0, backport 2.21, backport 3.1

#12554 ci(aiohttp): remove all flaky decorators from aiohttp test middleware
  tests/contrib/aiohttp/test_middleware.py
Labels: changelog/no-changelog

#12575 ci(flaky): bump `@flaky` timestamp by 1, 2, or 3 weeks to jitter expirations
  tests/appsec/integrations/flask_tests/test_flask_remoteconfig.py
  tests/contrib/asyncpg/test_asyncpg.py
  tests/contrib/aws_lambda/test_aws_lambda.py
  tests/contrib/celery/test_integration.py
  tests/contrib/django/test_django_snapshots.py
  tests/contrib/fastapi/test_fastapi.py
  tests/contrib/flask/test_flask_snapshot.py
  tests/contrib/vertica/test_vertica.py
  tests/profiling/test_main.py
  tests/profiling_v2/test_main.py
  tests/tracer/runtime/test_metric_collectors.py
  tests/tracer/runtime/test_runtime_metrics.py
Labels: changelog/no-changelog

#12602 ci(flaky): mark `test_accuracy` as flaky for 30 days
  tests/profiling/test_accuracy.py
Labels: changelog/no-changelog

#11274 chore: set the default of _should_skip to false
  tests/utils.py
Labels: changelog/no-changelog

#12393 perf(serverless): import ddtrace.internal._file_queue only when needed
  ddtrace/settings/_config.py
  tests/internal/test_serverless.py
Labels: changelog/no-changelog

#12591 chore: improve release script docs and error handling
  scripts/release.py
Labels: changelog/no-changelog

#12563 ci(benchmarks): add/enable startup benchmark to run in ci
  benchmarks/startup/config.yaml
  benchmarks/startup/requirements_scenario.txt
  benchmarks/startup/scenario.py
Labels: changelog/no-changelog

#12380 chore: add bump ddtrace script
  scripts/bump_ddtrace.py
Labels: changelog/no-changelog

#12610 chore(ci): remove flask flaky decorator
  tests/contrib/flask/test_flask_snapshot.py
Labels: changelog/no-changelog

#12592 feat(asm): report truncation with span metrics and telemetry
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_utils.py
  releasenotes/notes/truncation_metrics-70574b018370e8c7.yaml
  tests/appsec/appsec/test_ddwaf_fuzz.py
  tests/appsec/contrib_appsec/utils.py
Labels: ASM

#12623 ci(benchmarks): enable the startup benchmark scenario
  .gitlab/benchmarks/microbenchmarks.yml
Labels: changelog/no-changelog

#12607 chore(ci): remove flaky decorator from fastapi
  tests/contrib/fastapi/test_fastapi.py
Labels: changelog/no-changelog

#12603 chore(asyncpg): remove flaky from asyncpg
  tests/contrib/asyncpg/test_asyncpg.py
Labels: changelog/no-changelog

#12621 perf(internal): avoid early compat loading
  ddtrace/internal/wrapping/__init__.py
  ddtrace/internal/wrapping/asyncs.py
  ddtrace/internal/wrapping/generators.py
Labels: changelog/no-changelog

#12394 refactor(profiling): add accuracy tests for heap profiling
  ddtrace/profiling/collector/_memalloc.c
  tests/profiling_v2/collector/test_memalloc.py
Labels: changelog/no-changelog

#12608 chore(django): remove flaky for test_asgi_200_simple_app
  tests/contrib/django/test_django_snapshots.py
Labels: changelog/no-changelog

#12627 ci: prevent git fatal warning in download artifacts job
  .gitlab/package.yml
Labels: changelog/no-changelog

#12628 chore: fix vertica patching
  ddtrace/contrib/internal/vertica/patch.py
Labels: changelog/no-changelog

#12636 chore(ci): remove flaky decorator from mariadb test
  tests/contrib/mariadb/test_mariadb.py
Labels: changelog/no-changelog

#12632 chore(botocore): remove flaky from botocore
  tests/contrib/botocore/test_bedrock.py
Labels: changelog/no-changelog

#12605 chore(celery): update celery flaky tests
  tests/contrib/celery/test_integration.py
Labels: changelog/no-changelog

#12634 chore(ci): remove flaky decorator from aiomysql
  tests/contrib/aiomysql/test_aiomysql.py
  tests/snapshots/tests.contrib.aiomysql.test_aiomysql.test_pin_override.json
Labels: changelog/no-changelog

#12581 chore(sampling): simplify sampling
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/sampler.py
  ddtrace/_trace/tracer.py
  ddtrace/internal/constants.py
  ddtrace/internal/debug.py
  ddtrace/internal/sampling.py
  ddtrace/propagation/http.py
  tests/integration/test_debug.py
  tests/integration/test_sampling.py
  tests/tracer/test_sampler.py
Labels: changelog/no-changelog

#12615 chore(llmobs): refactor llmobs ctx activation to on_span_start
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/bedrock.py
  ddtrace/llmobs/_llmobs.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog

#12629 chore: add build system docs
  docs/build_system.rst
  docs/configuration.rst
  docs/index.rst
Labels: changelog/no-changelog

#12625 chore(asm): more timeout span tags and update telemetry tags for rasp
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_metrics.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#12630 chore(iast): revert #12508
  ddtrace/appsec/_iast/processor.py
  tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
Labels: changelog/no-changelog, ASM

#12641 chore(internal): prevent import of importlib.abc
  ddtrace/internal/module.py
Labels: changelog/no-changelog

#12638 refactor(dogstatsd): make imports lazy
  ddtrace/internal/writer/writer.py
  ddtrace/vendor/__init__.py
Labels: changelog/no-changelog

#12633 chore(llmobs): remove reliance on span tags for bedrock llm integration
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/botocore/services/bedrock.py
  ddtrace/llmobs/_integrations/bedrock.py
Labels: changelog/no-changelog

#12604 chore(llmobs): add telemetry for init/enable
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_telemetry.py
Labels: changelog/no-changelog

#12624 chore(ci): modify vertica flaky test
  tests/contrib/vertica/test_vertica.py
Labels: changelog/no-changelog

#12640 feat(SCA): extended-heartbeat for dependencies
  ddtrace/internal/telemetry/data.py
  ddtrace/internal/telemetry/modules.py
  ddtrace/internal/telemetry/writer.py
  releasenotes/notes/extended-heartbeat-acc361de5bdbb872.yaml
Labels: ASM

#12495 ci(benchmarks): refactor microbenchmark jobs
  .gitlab-ci.yml
  .gitlab/benchmarks/bp-runner.yml
  .gitlab/benchmarks/microbenchmarks.yml
  .gitlab/benchmarks/steps/build-baseline.sh
  .gitlab/benchmarks/steps/detect-baseline.sh
Labels: changelog/no-changelog

#12654 chore: use guess-next-dev instead of release-branch-semver [3.2]
  pyproject.toml
Labels: changelog/no-changelog

#12655 chore: update changelog for version 3.2.0
  CHANGELOG.md
Labels: changelog/no-changelog

#12667 ci(release): ensure promote-oci-* jobs have necessary artifacts (#12659)
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12666 ci(release): ensure promote-oci-* jobs have necessary artifacts (#12659)
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12673 ci(release): fix publish-lib-init-pinned-tags job dependencies
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12670 ci(release): fix publish-lib-init-pinned-tags job dependencies
  .gitlab-ci.yml
Labels: changelog/no-changelog, backport 3.0, backport 3.1, backport 3.2

#12614 chore(llmobs): add span.finished telemetry metric
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_telemetry.py
  ddtrace/llmobs/decorators.py
Labels: changelog/no-changelog

#12681 ci(release): fix publish-lib-init-pinned-tags job dependencies [backport 3.2]
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12647 chore(docs): replace testing guidelines link in contributing.rst
  docs/contributing.rst
Labels: changelog/no-changelog

#12685 chore(testopt): add provider name and auto_injected to telemetry
  ddtrace/internal/ci_visibility/api/_base.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/telemetry/events.py
Labels: changelog/no-changelog, CI App

#12674 chore(asm): add client id span tag
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#12650 fix(dd_tags): ensure ddtags are parsed in a manner consistent with the agent
  ddtrace/internal/debug.py
  ddtrace/internal/utils/formats.py
  ddtrace/settings/_config.py
  docs/configuration.rst
  releasenotes/notes/add-ddtags-experimental-support-15c9e66c94870be2.yaml
  tests/tracer/test_trace_utils.py
  tests/tracer/test_utils.py
Labels: backport 2.21

#12644 chore(llmobs): add telemetry on span event size/truncation
  ddtrace/llmobs/_telemetry.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_span_agent_writer.py
  tests/llmobs/test_llmobs_span_agentless_writer.py
Labels: changelog/no-changelog

#12662 chore(agent): move agent configs to envier
  ddtrace/internal/agent.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/writer/writer.py
  ddtrace/settings/_config.py
  releasenotes/notes/update-agent-tags-200920a48913617c.yaml
  tests/telemetry/test_writer.py
  tests/tracer/test_agent.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#12689 chore(llmobs): telemetry metrics for LLMObs API usage
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_telemetry.py
Labels: changelog/no-changelog

#12682 chore: replaced os.env with _get_config in rq integration
  ddtrace/contrib/internal/rq/patch.py
Labels: changelog/no-changelog

#12699 chore(llmobs): add telemetry for dropped spans/evals
  ddtrace/llmobs/_telemetry.py
  ddtrace/llmobs/_writer.py
Labels: changelog/no-changelog

#12700 chore(ci): update test agent versions
  .circleci/config.templ.yml
  .gitlab/services.yml
  docker-compose.yml
  lib-injection/docker-compose.yml
Labels: changelog/no-changelog

#12702 chore: remove redundant type aliases from compat
  ddtrace/_trace/sampling_rule.py
  ddtrace/internal/compat.py
  tests/profiling/collector/test_task.py
Labels: changelog/no-changelog

#12695 ci: pin GHA actions by sha for security
  .github/workflows/report-skipped-flaky.yml
Labels: changelog/no-changelog

#12693 chore(tracer): remove support for Python 2 int
  ddtrace/internal/_encoding.pyx
Labels: changelog/no-changelog, Tracing

#12709 ci: remove the static analysis file locally to store in UI instead
  static-analysis.datadog.yml
Labels: changelog/no-changelog

#12675 ci(iast): make the iast packages tests faster
  .gitlab/tests.yml
  hatch.toml
  scripts/gen_gitlab_config.py
  tests/appsec/iast_packages/test_packages.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12708 chore(asm): add success tags to waf telemetry init and update
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
  tests/appsec/appsec/test_telemetry.py
Labels: changelog/no-changelog, ASM

#12712 chore: add DD_BUILD_EXT_INCLUDES and DD_BUILD_EXT_EXCLUDES to setup.py
  docs/build_system.rst
  setup.py
Labels: changelog/no-changelog

#12717 ci: disable VPA for child jobs of benchmarks
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12718 ci(benchmarks): refactor telemetry_add_metric benchmark scenario
  benchmarks/telemetry_add_metric/config.yaml
  benchmarks/telemetry_add_metric/scenario.py
Labels: changelog/no-changelog

#12714 docs: removes sampling docs
  docs/api.rst
Labels: changelog/no-changelog

#12706 chore(iast): split wrapped_view hook
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_listener.py
  ddtrace/contrib/internal/flask/wrappers.py
  tests/appsec/iast/conftest.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
Labels: changelog/no-changelog, ASM, backport 2.21, backport 3.2

#12719 chore(asm): remove asm_request_context initialisation for iast
  ddtrace/appsec/_asm_request_context.py
Labels: changelog/no-changelog, ASM

#12671 chore(ci_visibility): add attempt-to-fix flow for quarantined/disabled tests
  ddtrace/contrib/internal/pytest/_attempt_to_fix.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/_utils.py
  ddtrace/contrib/internal/pytest/constants.py
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/api/_session.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/telemetry/events.py
  ddtrace/internal/test_visibility/_attempt_to_fix_mixins.py
  ddtrace/internal/test_visibility/api.py
  tests/contrib/pytest/test_pytest_attempt_to_fix.py
  tests/contrib/pytest/test_pytest_disabling.py
  tests/contrib/pytest/test_pytest_quarantine.py
  tests/contrib/pytest/utils.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_atr_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_atr_mix_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_all_pass.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_mix_fail.json
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_mix_pass.json
Labels: changelog/no-changelog

#12711 chore(iast): fix circular imports with importlib_metadata
  ddtrace/appsec/_iast/__init__.py
Labels: changelog/no-changelog, ASM, backport 3.0, backport 2.21, backport 3.1, backport 3.2

#12589 chore: run the smoke test at the end of build_base_venvs [backport 2.21]
  .gitlab/tests.yml
  .riot/requirements/10e0b19.txt
  .riot/requirements/164d1f0.txt
  .riot/requirements/2377901.txt
  .riot/requirements/271643d.txt
  .riot/requirements/7ffd29a.txt
  .riot/requirements/872f397.txt
  .riot/requirements/fc72580.txt
  riotfile.py
Labels: changelog/no-changelog

#12668 chore(ci): ssi tests onepipeline
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12735 ci(fix): manually install libatomic.i686 before rustup script [backport 2.21]
  .github/workflows/build_python_3.yml
  pyproject.toml
Labels: changelog/no-changelog

#12731 chore(asm): add api security telemetry metrics
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_metrics.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/contrib_appsec/conftest.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#12704 ci: add bootstrap import analysis
  .github/workflows/import-analysis.yml
  scripts/import-analysis/import_analysis.py
  scripts/import-analysis/requirements.txt
Labels: changelog/no-changelog

#12743 chore: increase packages timeout
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog, CI

#12716 chore(iast): improve iast logs
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_loader.py
  ddtrace/appsec/_iast/_logs.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/_errors.py
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/stacktrace_leak.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_replace_aspect.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask_patching.py
Labels: changelog/no-changelog, ASM, backport 2.21, backport 3.2

#12745 chore(ci_visibility): change CODEOWNERS for internal Test Optimization contribs
  .github/CODEOWNERS
Labels: changelog/no-changelog

#12736 chore: fast build environment variables [backport 2.21]
  .circleci/config.templ.yml
  .gitlab/tests.yml
  .riot/requirements/1fe8dd2.txt
  .riot/requirements/6bec1ec.txt
  ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/tests/CMakeLists.txt
  hatch.toml
  riotfile.py
  setup.py
Labels: changelog/no-changelog, ASM

#12726 chore(iast): split wrapped_view hook [backport 2.21]
  .gitlab/tests.yml
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_listener.py
  ddtrace/contrib/internal/flask/wrappers.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/iast/conftest.py
  tests/appsec/integrations/flask_tests/test_appsec_flask.py
  tests/appsec/integrations/flask_tests/test_appsec_flask_telemetry.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
Labels: changelog/no-changelog, ASM

#12747 chore(iast): improve iast logs [backport 2.21]
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_loader.py
  ddtrace/appsec/_iast/_logs.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_replace_aspect.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/integrations/flask_tests/test_iast_flask_patching.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#12742 chore(ci_visibility): add library capabilities to test tags
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/test_visibility/_library_capabilities.py
  ddtrace/internal/test_visibility/api.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog

#12759 ci: pin all GitHub Actions by SHA and update via dependabot (#12189) [backport 2.21]
  .github/dependabot.yml
  .github/workflows/backport.yml
  .github/workflows/build-and-publish-image.yml
  .github/workflows/build_deploy.yml
  .github/workflows/build_python_3.yml
  .github/workflows/changelog.yml
  .github/workflows/check_old_target_branch.yml
  .github/workflows/codeowners.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/django-overhead-profile.yml
  .github/workflows/encoders-profile.yml
  .github/workflows/flask-overhead-profile.yml
  .github/workflows/generate-package-versions.yml
  .github/workflows/generate-supported-versions.yml
  .github/workflows/pr-name.yml
  .github/workflows/profiling-native.yml
  .github/workflows/prune_workflow.yml
  .github/workflows/pytorch_gpu_tests.yml
  .github/workflows/require-checklist.yaml
  .github/workflows/requirements-locks.yml
  .github/workflows/rust-ci.yml
  .github/workflows/set-target-milestone.yml
  .github/workflows/stale.yml
  .github/workflows/system-tests.yml
  .github/workflows/test_frameworks.yml
  .github/workflows/test_lib_injection.yml
  .github/workflows/unit_tests.yml
  .github/workflows/upstream-issues.yml
Labels: changelog/no-changelog

#12705 fix: use negative limit for ``traceback.print_exception()``
  ddtrace/_trace/span.py
  releasenotes/notes/fix-traceback-in-span-a9481b15907d9887.yaml
  tests/tracer/test_span.py
Labels: bug

#12763 chore: switch warning to debug for dynamo span pointers
  ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py
  tests/tracer/utils_botocore/test_span_pointers.py
Labels: changelog/no-changelog

#12770 ci(flaky): bump flaky timestamp for test_auto
  tests/internal/test_auto.py
Labels: changelog/no-changelog

#12757 chore(iast): refactor open/read wrapping
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/sources/__init__.py
  ddtrace/appsec/_iast/sources/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  hatch.toml
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_io_aspects.py
  tests/appsec/iast/fixtures/taint_sinks/path_traversal.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/flask_tests/test_iast_flask_patching.py
Labels: changelog/no-changelog, ASM, backport 2.21, backport 3.2

#12758 ci(iast): migrate appsec_iast_memcheck and appsec_iast to gitlab/hatch [backport 2.21]
  .riot/requirements/1374394.txt
  .riot/requirements/13a28e1.txt
  .riot/requirements/13f2bea.txt
  .riot/requirements/1548fc3.txt
  .riot/requirements/18695ab.txt
  .riot/requirements/1aedbda.txt
  .riot/requirements/1bbfc54.txt
  .riot/requirements/1cc4eb6.txt
  .riot/requirements/1ef581b.txt
  .riot/requirements/4628049.txt
  .riot/requirements/58881b9.txt
  .riot/requirements/63b44e2.txt
  .riot/requirements/66c248d.txt
  .riot/requirements/aba89a0.txt
  .riot/requirements/d0652fb.txt
  .riot/requirements/eb40d16.txt
  hatch.toml
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_replace_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_command_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_header_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_path_traversal_redacted.py
  tests/appsec/iast/taint_sinks/test_weak_hash.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/iast/test_grpc_iast.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/iast/test_loader.py
  tests/appsec/iast/test_taint_utils.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12748 ci(iast): update hatch iast envs configuration [backport 2.21]
  hatch.toml
  scripts/gen_gitlab_config.py
  tests/appsec/integrations/flask_tests/test_flask_remoteconfig.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12750 chore(iast): improve iast logs [backport 3.2]
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_loader.py
  ddtrace/appsec/_iast/_logs.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_overhead_control_engine.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/Utils/GenericUtils.cpp
  ddtrace/appsec/_iast/_taint_tracking/_errors.py
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/stacktrace_leak.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_replace_aspect.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_split_aspect.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask_patching.py
Labels: changelog/no-changelog, ASM

#12776 chore(iast): refactor open/read wrapping [backport 2.21]
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/sources/__init__.py
  ddtrace/appsec/_iast/sources/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/aspects/test_io_aspects.py
  tests/appsec/iast/fixtures/taint_sinks/path_traversal.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/flask_tests/test_iast_flask_patching.py
Labels: changelog/no-changelog, ASM

#12656 ci(benchmarks): use django test client in django_simple benchmark
  .gitlab/benchmarks/microbenchmarks.yml
  benchmarks/django_simple/gunicorn.conf.py
  benchmarks/django_simple/scenario.py
  benchmarks/django_simple/utils.py
Labels: changelog/no-changelog

#12800 ci: skip serverless benchmark failures to unblock CI
  .gitlab/benchmarks/serverless.yml
Labels: changelog/no-changelog

#12639 ci(iast): startup microbenchmark
  .gitlab/benchmarks/microbenchmarks.yml
  benchmarks/appsec_iast_django_startup/config.yaml
  benchmarks/appsec_iast_django_startup/install.sh
  benchmarks/appsec_iast_django_startup/manage.py
  benchmarks/appsec_iast_django_startup/requirements.in
  benchmarks/appsec_iast_django_startup/requirements_scenario.txt
  benchmarks/appsec_iast_django_startup/scenario.py
  benchmarks/appsec_iast_django_startup/settings.py
  benchmarks/appsec_iast_django_startup/urls.py
  benchmarks/appsec_iast_django_startup/views.py
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_handlers.py
Labels: changelog/no-changelog, ASM

#12765 fix: gevent compatibility with typing module
  ddtrace/bootstrap/sitecustomize.py
  releasenotes/notes/fix-gevent-support-_operator-163719336cc8980a.yaml
Labels: backport 3.2

#12791 chore(er): ensure max frame per trace
  ddtrace/debugging/_exception/replay.py
  tests/debugging/exception/test_replay.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12784 docs(debugging): add architecture overview
  .github/workflows/build_python_3.yml
  ddtrace/debugging/README.md
Labels: changelog/no-changelog, Dynamic Instrumentation

#12316 refactor(internal): lazy ModuleWatchdog install
  ddtrace/__init__.py
  ddtrace/internal/module.py
  tests/appsec/integrations/flask_tests/test_iast_flask_entrypoint_iast_patches.py
  tests/internal/test_module.py
Labels: changelog/no-changelog

#12795 chore(ci_visibility): type hinting
  ddtrace/internal/ci_visibility/recorder.py
Labels: changelog/no-changelog, CI App

#12715 chore(configuration): replace instances of os.environ
  ddtrace/contrib/internal/aws_lambda/patch.py
Labels: changelog/no-changelog

#12805 ci: skip serverless benchmark failures to unblock CI (#12800) [backport 2.21]
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#12772 chore(asm): report unknown version for telemetry
  ddtrace/appsec/_metrics.py
Labels: changelog/no-changelog, ASM

#12793 chore: update changelog for version 2.21.4
  CHANGELOG.md
Labels: changelog/no-changelog

#12720 chore(ci): upgrade test runner image
  .circleci/config.templ.yml
  .github/workflows/requirements-locks.yml
  .gitlab/testrunner.yml
  docker-compose.yml
Labels: changelog/no-changelog

#12780 chore(ci_visibility): remove vestigial early return now ITR is GA
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App

#12788 chore(llmobs): fix span.size telemetry metric
  ddtrace/llmobs/_telemetry.py
  ddtrace/llmobs/_writer.py
Labels: changelog/no-changelog

#12812 test(di): avoid pytest loader when importing modules
  tests/debugging/function/test_discovery.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12823 ci(release): ensure promote-oci-* jobs have necessary artifacts [backport 2.21]
  .gitlab-ci.yml
Labels: changelog/no-changelog

#12517 refactor(profiling): use upstream echion
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/include/stack_renderer.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  releasenotes/notes/profiling-update-echion-d2ff9f14c9279d4a.yaml
  tests/profiling_v2/collector/test_stack.py
Labels: Profiling

#12764 chore(ci_visibility): support attempt-to-fix v2 API
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/git_data.py
  tests/ci_visibility/api_client/_util.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client.py
Labels: changelog/no-changelog

#12817 chore(ci_visibility): support Attempt-to-Fix active tests
  ddtrace/contrib/internal/pytest/_attempt_to_fix.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/constants.py
  ddtrace/internal/ci_visibility/api/_session.py
  ddtrace/internal/ci_visibility/api/_test.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/test_visibility/_attempt_to_fix_mixins.py
  tests/contrib/pytest/test_pytest_attempt_to_fix.py
Labels: changelog/no-changelog

#12798 chore(ci_visibility): remove code
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/util.py
Labels: changelog/no-changelog, CI App

#12819 docs: add readme pointer to versioning documentation
  README.md
Labels: changelog/no-changelog

#12672 feat(profiling): stack_v2 supports CPython 3.13
  .github/workflows/profiling-native.yml
  .riot/requirements/955b213.txt
  .riot/requirements/cb9a5da.txt
  .riot/requirements/d449a90.txt
  releasenotes/notes/profiling-3.13-e62c18bff5de1218.yaml
  riotfile.py
  setup.py
  tests/profiling_v2/collector/test_memalloc.py
Labels: Profiling

#12833 fix(profiling): wrap del with try/except
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-self-acquired-at-963cadba71ac62b8.yaml
Labels: Profiling

#12855 ci(appsec): update flaky test
  tests/appsec/integrations/flask_tests/test_flask_remoteconfig.py
Labels: changelog/no-changelog, ASM

#12811 ci(iast): make the iast packages tests faster (#12675) [backport 2.21]
  .gitlab/tests.yml
  scripts/gen_gitlab_config.py
  tests/appsec/iast_packages/test_packages.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12774 chore(iast): optimize iast by migrating should_iast_patch function to c
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_ast/CMakeLists.txt
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/iastpatch.c
  ddtrace/appsec/_iast/_ast/iastpatch.pyi
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_loader.py
  ddtrace/appsec/_iast/_logs.py
  ddtrace/appsec/_iast/_stacktrace.pyi
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_python_info/stdlib/__init__.py
  ddtrace/appsec/_python_info/stdlib/module_names_py310.py
  ddtrace/appsec/_python_info/stdlib/module_names_py311.py
  ddtrace/appsec/_python_info/stdlib/module_names_py312.py
  ddtrace/appsec/_python_info/stdlib/module_names_py36.py
  ddtrace/appsec/_python_info/stdlib/module_names_py37.py
  ddtrace/appsec/_python_info/stdlib/module_names_py38.py
  ddtrace/appsec/_python_info/stdlib/module_names_py39.py
  setup.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/_ast/test_ast_patching_type_hints.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/iast/test_loader.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM, backport 2.21

#12829 chore: add envvar option to bump_ddtrace script
  .github/CODEOWNERS
  scripts/bump_ddtrace.py
Labels: changelog/no-changelog

#12847 chore(ci): update codeowners and bump timestamp for expired aws-lambda tests
  .github/CODEOWNERS
  tests/contrib/aws_lambda/test_aws_lambda.py
Labels: changelog/no-changelog

#12859 chore(debugging): guard against race on emitting status
  ddtrace/debugging/_probe/registry.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12796 chore(runtime_metrics): fix typo in config
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/settings/_config.py
Labels: changelog/no-changelog

#12857 chore(iast): optimize iast by migrating should_iast_patch function to c [backport 2.21]
  ddtrace/appsec/_iast/__init__.py
  ddtrace/appsec/_iast/_ast/CMakeLists.txt
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_iast/_ast/iastpatch.c
  ddtrace/appsec/_iast/_ast/iastpatch.pyi
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_loader.py
  ddtrace/appsec/_iast/_logs.py
  ddtrace/appsec/_iast/_stacktrace.pyi
  ddtrace/appsec/_iast/_taint_tracking/Constants.h
  ddtrace/appsec/_python_info/stdlib/__init__.py
  ddtrace/appsec/_python_info/stdlib/module_names_py310.py
  ddtrace/appsec/_python_info/stdlib/module_names_py311.py
  ddtrace/appsec/_python_info/stdlib/module_names_py312.py
  ddtrace/appsec/_python_info/stdlib/module_names_py36.py
  ddtrace/appsec/_python_info/stdlib/module_names_py37.py
  ddtrace/appsec/_python_info/stdlib/module_names_py38.py
  ddtrace/appsec/_python_info/stdlib/module_names_py39.py
  setup.py
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/_ast/test_ast_patching_type_hints.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/iast/test_loader.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#12851 chore(profiling): remove flaky marker
  tests/profiling/test_main.py
  tests/profiling_v2/test_main.py
Labels: changelog/no-changelog, Profiling

#12821 chore(tracer): remove init args
  ddtrace/_trace/tracer.py
  ddtrace/internal/ci_visibility/recorder.py
Labels: changelog/no-changelog

#12818 chore(tracer): remove unused method and constant
  ddtrace/_trace/tracer.py
Labels: changelog/no-changelog

#12853 chore: remove dead code
  ddtrace/_trace/utils_botocore/span_pointers/dynamodb.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_utils.py
  ddtrace/internal/coverage/instrumentation_py3_8.py
  ddtrace/internal/runtime/container.py
  ddtrace/propagation/_database_monitoring.py
  ddtrace/propagation/http.py
  ddtrace/settings/_config.py
  lib-injection/sources/sitecustomize.py
  setup.py
  tests/appsec/iast/aspects/test_side_effects.py
  tests/contrib/botocore/test.py
  tests/contrib/grpc_aio/test_grpc_aio.py
  tests/internal/crashtracker/test_crashtracker.py
  tests/profiling/collector/_asyncio_compat.py
  tests/profiling/collector/test_stack_asyncio.py
  tests/profiling/collector/test_threading_asyncio.py
  tests/profiling_v2/collector/test_stack_asyncio.py
  tests/profiling_v2/collector/test_threading_asyncio.py
  tests/tracer/test_version.py
Labels: changelog/no-changelog

#12852 feat(profiling): enable native extensions for x86_64 macOS
  releasenotes/notes/profiling-macos-x86-64-0b89414501e91446.yaml
  setup.py
  tests/smoke_test.py
Labels: Profiling

#12773 chore(asm): upgrade libddwaf to 1.24.0 & remote config changes
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_ddwaf/waf.py
  ddtrace/appsec/_ddwaf/waf_mock.py
  ddtrace/appsec/_ddwaf/waf_stubs.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/debugging/_probe/remoteconfig.py
  ddtrace/internal/flare/_subscribers.py
  ddtrace/internal/remoteconfig/__init__.py
  ddtrace/internal/remoteconfig/_connectors.py
  ddtrace/internal/remoteconfig/_publishers.py
  ddtrace/internal/remoteconfig/_pubsub.py
  ddtrace/internal/remoteconfig/_subscribers.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/remoteconfig/worker.py
  ddtrace/settings/_config.py
  setup.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/utils.py
  tests/debugging/probe/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/remoteconfig/test_remoteconfig_client.py
  tests/internal/remoteconfig/test_remoteconfig_client_e2e.py
  tests/internal/remoteconfig/test_remoteconfig_connector.py
  tests/internal/remoteconfig/test_remoteconfig_publisher.py
  tests/internal/remoteconfig/test_remoteconfig_subscriber.py
  tests/internal/remoteconfig/utils.py
  tests/internal/test_settings.py
  tests/internal/test_tracer_flare.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/utils.py
Labels: changelog/no-changelog, ASM

#12875 fix(sca): fix sbom dependency name report
  ddtrace/internal/packages.py
  releasenotes/notes/fix_sbom_package_name-7b340f4b3fcda0f7.yaml
  tests/telemetry/test_data.py
Labels: ASM, backport 3.1, backport 3.2, backport 3.3

#12830 perf(serverless): lazy import botocore code
  ddtrace/_trace/trace_handlers.py
  tests/internal/test_serverless.py
Labels: changelog/no-changelog

#12810 chore(configuration): replace instances of os.environ
  ddtrace/contrib/internal/coverage/utils.py
Labels: changelog/no-changelog

#12820 refactor: resolve config-telemetry circular reference
  ddtrace/_logger.py
  ddtrace/_trace/tracer.py
  ddtrace/contrib/internal/aiohttp/patch.py
  ddtrace/contrib/internal/wsgi/wsgi.py
  ddtrace/debugging/_products/exception_replay.py
  ddtrace/internal/README.md
  ddtrace/internal/agent.py
  ddtrace/internal/appsec/product.py
  ddtrace/internal/products.py
  ddtrace/internal/telemetry/__init__.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/settings/__init__.py
  ddtrace/settings/_agent.py
  ddtrace/settings/_config.py
  ddtrace/settings/_core.py
  ddtrace/settings/_telemetry.py
  ddtrace/settings/asm.py
  ddtrace/settings/crashtracker.py
  ddtrace/settings/dynamic_instrumentation.py
  ddtrace/settings/errortracking.py
  ddtrace/settings/exception_replay.py
  ddtrace/settings/peer_service.py
  ddtrace/settings/profiling.py
  ddtrace/settings/symbol_db.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/util.py
  tests/contrib/dbapi/test_dbapi.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/dbapi_async/test_dbapi_async.py
  tests/debugging/test_config.py
  tests/internal/test_settings.py
  tests/telemetry/test_writer.py
  tests/tracer/test_agent.py
  tests/tracer/test_global_config.py
  tests/tracer/test_settings.py
  tests/tracer/test_trace_utils.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#12862 fix(ci_visibility): count failed/skipped tests in JUnit XML when retries are enabled
  ddtrace/contrib/internal/pytest/_atr_utils.py
  ddtrace/contrib/internal/pytest/_attempt_to_fix.py
  ddtrace/contrib/internal/pytest/_efd_utils.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/_retry_utils.py
  releasenotes/notes/ci_visibility-fix-junit-xml-retry-count-65de6ad6b9bb35d2.yaml
  tests/contrib/pytest/test_pytest_atr.py
  tests/contrib/pytest/test_pytest_attempt_to_fix.py
  tests/contrib/pytest/test_pytest_efd.py
Labels: backport 3.1, backport 3.2, backport 3.3

#12896 chore(symdb): adapt to new RC refactor
  .github/workflows/system-tests.yml
  ddtrace/internal/symbol_db/remoteconfig.py
Labels: changelog/no-changelog

#12876 ci: add pip cache to CI jobs
  .gitlab/scripts/get-riot-hashes.sh
  .gitlab/scripts/get-riot-pip-cache-key.sh
  .gitlab/tests.yml
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog

#12889 fix(llmobs): llmobs can be re-enabled on fork with agentless enabled
  ddtrace/llmobs/_writer.py
  releasenotes/notes/llmobs-agentless-writer-on-fork-fix-d43c50cbf3d86297.yaml
  tests/llmobs/test_llmobs_service.py
Labels: backport 3.0, backport 2.21, backport 3.1, backport 3.2

#12910 chore(asm): make sure removal are first on waf updates
  ddtrace/appsec/_ddwaf/waf.py
  ddtrace/appsec/_ddwaf/waf_mock.py
  ddtrace/appsec/_ddwaf/waf_stubs.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_remoteconfiguration.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_telemetry.py
Labels: changelog/no-changelog, ASM

#12919 chore: add .cursor/ directory to .gitignore
  .gitignore
Labels: changelog/no-changelog

#12902 chore(iast): add secure_marks to TaintRange for vulnerability tracking
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectIndex.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/AspectSlice.cpp
  ddtrace/appsec/_iast/_taint_tracking/Aspects/Helpers.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.cpp
  ddtrace/appsec/_iast/_taint_tracking/Initializer/Initializer.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.cpp
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintRange.h
  ddtrace/appsec/_iast/_taint_tracking/TaintTracking/TaintedObject.cpp
  ddtrace/appsec/_iast/_taint_tracking/__init__.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  tests/appsec/app.py
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
Labels: changelog/no-changelog, ASM

#12920 chore(rc): migrate to type hints in subscribers
  ddtrace/internal/remoteconfig/_subscribers.py
  ddtrace/internal/remoteconfig/utils.py
  ddtrace/internal/remoteconfig/worker.py
Labels: changelog/no-changelog

#12893 chore: improve uWSGI error on missing import option
  ddtrace/internal/uwsgi.py
Labels: changelog/no-changelog

#12883 chore(profiling): compress code-provenance file when exporting
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
Labels: changelog/no-changelog

#12913 chore(profiling): mark test xfail
  tests/profiling_v2/collector/test_stack.py
Labels: changelog/no-changelog

#12894 chore: add missing _DD_CIVISIBILITY env var to gen_appsec_iast_packages
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog, CI

#12922 refactor: move RC registration logic to RC product
  ddtrace/internal/remoteconfig/product.py
  ddtrace/settings/_config.py
Labels: changelog/no-changelog

#12888 ci: update CI job parallelism
  tests/appsec/suitespec.yml
  tests/ci_visibility/suitespec.yml
  tests/contrib/suitespec.yml
  tests/debugging/suitespec.yml
  tests/errortracking/suitespec.yml
  tests/llmobs/suitespec.yml
  tests/suitespec.yml
Labels: changelog/no-changelog

#12713 chore(agent): replace agent_url functions with envier config
  ddtrace/_trace/tracer.py
  ddtrace/internal/agent.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/writer.py
  ddtrace/internal/core/crashtracking.py
  ddtrace/internal/datadog/profiling/ddup/_ddup.pyx
  ddtrace/internal/datastreams/__init__.py
  ddtrace/internal/debug.py
  ddtrace/internal/metrics.py
  ddtrace/internal/remoteconfig/client.py
  ddtrace/internal/runtime/runtime_metrics.py
  ddtrace/internal/symbol_db/symbols.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/internal/writer/writer.py
  ddtrace/llmobs/_writer.py
  ddtrace/profiling/utils.py
  ddtrace/settings/dynamic_instrumentation.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client.py
  tests/ci_visibility/test_ci_visibility.py
  tests/debugging/test_config.py
  tests/integration/test_integration.py
  tests/integration/test_integration_civisibility.py
  tests/llmobs/test_llmobs_span_agent_writer.py
  tests/tracer/test_agent.py
  tests/utils.py
Labels: changelog/no-changelog

#12939 ci(iast): update google tests
  ddtrace/appsec/_iast/_taint_tracking/tests/CMakeLists.txt
Labels: changelog/no-changelog, ASM

#12927 ci: add circular import detection
  .github/workflows/import-analysis.yml
  scripts/import-analysis/cycles.py
  scripts/import-analysis/requirements-cycles.txt
Labels: changelog/no-changelog

#12921 refactor: logs injection configuration
  ddtrace/_logger.py
  ddtrace/bootstrap/sitecustomize.py
Labels: changelog/no-changelog
