Repository DataDog/dd-trace-py, pull requests merged in 2025-04, with the labels that each got.

#12981 chore(asm): add waf and rasp errors span tags
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/appsec/test_telemetry.py
Labels: changelog/no-changelog, ASM

#12969 refactor(tracing): remove span-context interdependency
  ddtrace/_trace/context.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/sampler.py
  ddtrace/_trace/span.py
  tests/datastreams/test_public_api.py
Labels: changelog/no-changelog, Tracing

#12965 ci: migrate from CircleCI to GitLab [backport 2.21]
  .circleci/config.templ.yml
  .gitignore
  .gitlab/services.yml
  docker-compose.yml
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  tests/contrib/aiobotocore/test.py
  tests/contrib/aiobotocore/utils.py
  tests/contrib/config.py
  tests/contrib/consul/test.py
  tests/contrib/suitespec.yml
  tests/wait-for-services.py
Labels: changelog/no-changelog

#12073 feat(profiling): builds libdatadog for windows
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
  ddtrace/internal/datadog/profiling/cmake/FindLibdatadog.cmake
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  releasenotes/notes/profiling-libdd-windows-0e80f0facac09221.yaml
  setup.py
  tests/smoke_test.py
Labels: Profiling

#12955 fix(asm): implement __deepcopy__ for wrapped builtin functions in ASM/IAST [backport 3.1]
  ddtrace/appsec/_common_module_patches.py
  releasenotes/notes/appsec-deepcopy-error-0f898629251881d2.yaml
  tests/appsec/app.py
  tests/appsec/appsec/test_common_modules.py
  tests/appsec/integrations/flask_tests/test_appsec_flask.py
Labels: ASM

#13009 ci(iast): move iast_patched_module to utils instead of conftest
  benchmarks/bm/iast_utils/aspects_benchmarks_generate.py
  tests/appsec/iast/_ast/test_proper_patching.py
  tests/appsec/iast/aspects/aspect_utils.py
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast/aspects/test_add_aspect_fixtures.py
  tests/appsec/iast/aspects/test_add_inplace_aspect_fixtures.py
  tests/appsec/iast/aspects/test_asyncio.py
  tests/appsec/iast/aspects/test_bytearray_extend_aspect.py
  tests/appsec/iast/aspects/test_common_aspects.py
  tests/appsec/iast/aspects/test_common_aspects_generator.py
  tests/appsec/iast/aspects/test_common_replace_aspects.py
  tests/appsec/iast/aspects/test_empty_arg_aspects.py
  tests/appsec/iast/aspects/test_encode_decode_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_format_map_aspect_fixtures.py
  tests/appsec/iast/aspects/test_index_aspect_fixtures.py
  tests/appsec/iast/aspects/test_join_aspect_fixtures.py
  tests/appsec/iast/aspects/test_modulo_aspect_fixtures.py
  tests/appsec/iast/aspects/test_ospath_aspects_fixtures.py
  tests/appsec/iast/aspects/test_other_patching.py
  tests/appsec/iast/aspects/test_re_aspects.py
  tests/appsec/iast/aspects/test_side_effects.py
  tests/appsec/iast/aspects/test_slice_aspect_fixtures.py
  tests/appsec/iast/aspects/test_str_aspect.py
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/taint_sinks/test_code_injection.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_sql_injection.py
  tests/appsec/iast/taint_sinks/test_weak_randomness.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
  tests/appsec/integrations/flask_tests/test_iast_langchain.py
Labels: changelog/no-changelog, ASM

#13020 chore: prevent subprocess force-import
  ddtrace/appsec/_common_module_patches.py
  ddtrace/contrib/internal/subprocess/patch.py
  tests/internal/test_auto.py
Labels: changelog/no-changelog

#13005 chore(asm): more tags for appsec telemetry
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_ddwaf/__init__.py
  ddtrace/appsec/_ddwaf/waf_stubs.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_utils.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#12975 chore(asm): update security rules
  ddtrace/appsec/rules.json
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec_snapshots.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
Labels: changelog/no-changelog, ASM

#11980 chore: introduce APM_TRACING RC product
  ddtrace/_trace/product.py
  ddtrace/internal/README.md
  ddtrace/internal/remoteconfig/products/__init__.py
  ddtrace/internal/remoteconfig/products/apm_tracing.py
  ddtrace/internal/remoteconfig/products/client.py
  ddtrace/settings/_config.py
  pyproject.toml
  riotfile.py
  tests/integration/test_settings.py
  tests/internal/test_settings.py
Labels: changelog/no-changelog

#13023 ci: :fire: remove circleci configuration and related scripts :fire:
  .circleci/config.templ.yml
  .circleci/config.yml
  .riot/requirements/4d1fa34.txt
  riotfile.py
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  tests/suitespec.yml
Labels: changelog/no-changelog, backport 2.21, backport 3.3

#13016 chore(otel): make snapshots less flaky
  tests/opentelemetry/test_context.py
  tests/opentelemetry/test_span.py
  tests/opentelemetry/test_trace.py
Labels: changelog/no-changelog

#12967 chore: auto opt in all PRs to backport to 2.21
  .github/workflows/add-2x-backport-tag.yml
Labels: changelog/no-changelog

#13026 refactor(profiling): add memalloc race regression test
  tests/profiling_v2/collector/test_memalloc.py
Labels: changelog/no-changelog, Profiling

#12997 chore: update logbook latest version to 1.8.1 [recreated]
  .riot/requirements/104f450.txt
  .riot/requirements/12b4a54.txt
  .riot/requirements/12bb48f.txt
  .riot/requirements/151e533.txt
  .riot/requirements/178f7d5.txt
  .riot/requirements/187df5b.txt
  .riot/requirements/1a8b5b1.txt
  .riot/requirements/1d45d3e.txt
  .riot/requirements/1e5b9c4.txt
  .riot/requirements/98b02a4.txt
  .riot/requirements/d0116c6.txt
  .riot/requirements/f027911.txt
Labels: changelog/no-changelog

#13033 ci: :fire: remove circleci configuration and related scripts :fire: [backport 3.3]
  .circleci/config.templ.yml
  .circleci/config.yml
  .riot/requirements/4d1fa34.txt
  riotfile.py
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  tests/suitespec.yml
Labels: changelog/no-changelog

#12916 chore: update changelog for version 3.1.1, 3.2.2
  CHANGELOG.md
Labels: changelog/no-changelog

#13034 ci: :fire: remove circleci configuration and related scripts :fire: [backport 3.2]
  .circleci/config.templ.yml
  .circleci/config.yml
  .riot/requirements/4d1fa34.txt
  riotfile.py
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  tests/suitespec.yml
Labels: changelog/no-changelog

#13035 ci: :fire: remove circleci configuration and related scripts :fire: [backport 2.21]
  .circleci/config.yml
  .riot/requirements/4d1fa34.txt
  riotfile.py
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  tests/suitespec.yml
Labels: changelog/no-changelog

#12928 chore(asm): improve logs for appsec
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_metrics.py
  ddtrace/internal/logger.py
  tests/appsec/appsec/test_asm_request_context.py
  tests/tracer/test_logger.py
Labels: changelog/no-changelog, ASM

#13021 chore(iast): improve ast patching allowlist
  ddtrace/appsec/_iast/_ast/iastpatch.c
  ddtrace/appsec/_iast/_taint_tracking/tests/test_secure_marks.cpp
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM, backport 2.21, backport 3.2, backport 3.3

#13018 chore: avoid false product circular dependency reporting
  ddtrace/internal/products.py
  tests/internal/test_products.py
Labels: changelog/no-changelog

#13043 chore(iast): improve ast patching allowlist [backport 2.21]
  ddtrace/appsec/_iast/_ast/iastpatch.c
  tests/appsec/iast/_ast/test_ast_patching.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/test_env_var.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#13036 ci: :fire: remove circleci configuration and related scripts :fire: [backport 3.1]
  .circleci/config.templ.yml
  .circleci/config.yml
  .riot/requirements/4d1fa34.txt
  riotfile.py
  scripts/gen_circleci_config.py
  scripts/gen_gitlab_config.py
  tests/suitespec.yml
Labels: changelog/no-changelog

#12991 refactor: configuration instance [recreated]
  ddtrace/__init__.py
  ddtrace/_monkey.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/provider.py
  ddtrace/_trace/sampler.py
  ddtrace/_trace/span.py
  ddtrace/_trace/tracer.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/contrib/internal/trace_utils.py
  ddtrace/internal/core/event_hub.py
  ddtrace/internal/datastreams/processor.py
  ddtrace/internal/processor/stats.py
  ddtrace/internal/sampling.py
  ddtrace/internal/schema/processor.py
  ddtrace/propagation/http.py
  ddtrace/settings/_config.py
  ddtrace/settings/asm.py
Labels: changelog/no-changelog

#13041 ci: fix comment action parameters
  .github/workflows/codeowners.yml
  .github/workflows/import-analysis.yml
Labels: changelog/no-changelog

#13047 chore(docs): update docs on gcc version
  docs/build_system.rst
Labels: changelog/no-changelog

#13040 chore: adds AGENT_SUPPORTING_SPAN_EVENTS scenario in system-tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog, CI

#13046 refactor(iast): move sql injection logic to iast folder
  ddtrace/appsec/_iast/_taint_utils.py
  ddtrace/appsec/_iast/taint_sinks/sql_injection.py
  ddtrace/contrib/dbapi.py
  ddtrace/contrib/dbapi_async.py
  tests/appsec/iast/test_taint_utils.py
Labels: changelog/no-changelog, ASM

#12930 docs: reduce backport volume promised in docs
  docs/versioning.rst
Labels: changelog/no-changelog

#13050 chore(llmobs): correct codeowner file names
  .github/CODEOWNERS
Labels: changelog/no-changelog

#13048 chore(asm): add support for error.type or error.message private span tags
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_constants.py
  tests/appsec/appsec/test_asm_request_context.py
Labels: changelog/no-changelog, ASM

#13017 feat(iast): add secure marks core and sanitize command injection
  ddtrace/appsec/_iast/_ast/iastpatch.c
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/taint_range.cpp
  ddtrace/appsec/_iast/_taint_tracking/tests/test_secure_marks.cpp
  ddtrace/appsec/_iast/secure_marks/__init__.py
  ddtrace/appsec/_iast/secure_marks/sanitizers.py
  ddtrace/appsec/_iast/secure_marks/validators.py
  tests/appsec/iast/db_utils.py
  tests/appsec/iast/fixtures/secure_marks/__init__.py
  tests/appsec/iast/fixtures/secure_marks/sanitizers.py
  tests/appsec/iast/fixtures/taint_sinks/sql_injection_psycopg2.py
  tests/appsec/iast/secure_marks/conftest.py
  tests/appsec/iast/secure_marks/test_sanitizers.py
  tests/appsec/iast/secure_marks/test_validators.py
  tests/appsec/iast/test_iast_psycopg2.py
  tests/appsec/integrations/fixtures/patch_psycopg2.py
  tests/appsec/integrations/flask_tests/test_iast_psycopg2.py
Labels: changelog/no-changelog, ASM

#13030 fix(ci_visibility): set up Test Optimization logging before pytest log capture
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/utils.py
  releasenotes/notes/ci_visibility-fix-io-operation-closed-file-1e1089eabd5296ce.yaml
Labels: backport 3.1, backport 3.2, backport 3.3

#12618 docs: troubleshooting note about missing dependencies
  docs/troubleshooting.rst
Labels: changelog/no-changelog

#13067 chore(asm): add several metrics and tags
  ddtrace/appsec/_api_security/api_manager.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_ddwaf/waf.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_utils.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog, ASM

#12949 chore: telemetry for ddtrace-api integration
  ddtrace/contrib/internal/ddtrace_api/patch.py
  ddtrace/internal/telemetry/constants.py
Labels: changelog/no-changelog

#13080 chore(llmobs): revert "feat(llmobs): openai agents sdk integration"
  .riot/requirements/14e7a10.txt
  .riot/requirements/1538bcb.txt
  .riot/requirements/1f24364.txt
  .riot/requirements/213dcfe.txt
  .riot/requirements/55abc5e.txt
  ddtrace/_monkey.py
  ddtrace/contrib/_openai_agents.py
  ddtrace/contrib/internal/openai_agents/patch.py
  ddtrace/contrib/internal/openai_agents/processor.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/openai_agents.py
  ddtrace/llmobs/_integrations/utils.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/settings/_config.py
  docs/index.rst
  docs/integrations.rst
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  releasenotes/notes/openai-agents-sdk-9a251c2a812a6353.yaml
  riotfile.py
  tests/contrib/openai_agents/__init__.py
  tests/contrib/openai_agents/cassettes/test_agent_with_tool_errors.yaml
  tests/contrib/openai_agents/cassettes/test_multiple_agent_handoffs.yaml
  tests/contrib/openai_agents/cassettes/test_simple_agent.yaml
  tests/contrib/openai_agents/cassettes/test_simple_agent_streamed.yaml
  tests/contrib/openai_agents/cassettes/test_single_agent_with_tool_calls.yaml
  tests/contrib/openai_agents/conftest.py
  tests/contrib/openai_agents/test_openai_agents.py
  tests/contrib/openai_agents/test_openai_agents_llmobs.py
  tests/contrib/openai_agents/test_openai_agents_patch.py
  tests/llmobs/suitespec.yml
  tests/llmobs/test_llmobs_evaluator_runner.py
  tests/snapshots/tests.contrib.openai_agents.test_openai_agents.test_openai_agents.json
  tests/snapshots/tests.contrib.openai_agents.test_openai_agents.test_openai_agents_streaming.json
  tests/snapshots/tests.contrib.openai_agents.test_openai_agents.test_openai_agents_sync.json
  tests/snapshots/tests.contrib.openai_agents.test_openai_agents.test_openai_agents_with_tool_error.json
Labels: changelog/no-changelog

#13076 chore(ci): add allow failure feature to jobspec class
  .gitlab/tests.yml
  scripts/gen_gitlab_config.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, CI

#13083 chore(asm): waf upgrade to 1.24.1
  setup.py
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_body_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_cookies_no_collection_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot.json
  tests/snapshots/tests.appsec.appsec.test_processor.test_appsec_span_tags_snapshot_with_errors.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_appsec_enabled_attack.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_match_403_json.json
  tests/snapshots/tests.contrib.django.test_django_appsec_snapshots.test_request_ipblock_nomatch_200.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_ipblock_match_403_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_osspawn[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_ossystem[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicatenoshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_processexec_subprocesscommunicateshell[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_200_json[flask_appsec_good_rules_env]_220.json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env].json
  tests/snapshots/tests.contrib.flask.test_appsec_flask_snapshot.test_flask_userblock_match_403_json[flask_appsec_good_rules_env]_220.json
Labels: changelog/no-changelog, ASM

#13073 ci: use 3-sigma-rule in import time analysis
  scripts/import-analysis/import_analysis.py
Labels: changelog/no-changelog

#13070 ci: fail when new import cycles detected
  .github/workflows/import-analysis.yml
  scripts/import-analysis/cycles.py
Labels: changelog/no-changelog

#13075 chore(iast): fix iast span metrics
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/code_injection.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/sql_injection.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/_iast/taint_sinks/weak_hash.py
  ddtrace/appsec/_iast/taint_sinks/xss.py
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM, backport 2.21, backport 3.2, backport 3.3

#13084 chore(ci_visibility): decouple EFD faulty session from is_new
  ddtrace/internal/ci_visibility/api/_test.py
  tests/snapshots/test_api_fake_runners.test_manual_api_fake_efd_faulty_session.json
Labels: changelog/no-changelog, CI App

#12738 chore(perf): improve performance of creating telemetry metrics
  .gitignore
  benchmarks/telemetry_add_metric/config.yaml
  benchmarks/telemetry_add_metric/scenario.py
  ddtrace/internal/telemetry/metrics.py
  ddtrace/internal/telemetry/metrics_namespaces.py
  ddtrace/internal/telemetry/metrics_namespaces.pyi
  ddtrace/internal/telemetry/metrics_namespaces.pyx
  ddtrace/internal/telemetry/writer.py
  pyproject.toml
  setup.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/flask_tests/test_appsec_flask_telemetry.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
  tests/telemetry/conftest.py
Labels: changelog/no-changelog

#13078 chore(docs): updating DD_TRACE_PROPAGATION_STYLE to include baggage
  docs/configuration.rst
Labels: changelog/no-changelog

#13039 chore(serverless): remove flaky mark from two serverless tests
  tests/contrib/aws_lambda/test_aws_lambda.py
Labels: changelog/no-changelog

#13077 chore(llmobs): remove beta auto span linking flag, decorator linking
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/decorators.py
  ddtrace/settings/_config.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_decorators.py
  tests/telemetry/test_writer.py
  tests/utils.py
Labels: changelog/no-changelog

#13085 fix(iast): resolve PosixPath error in os.path patching
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/iast-posixpath-error-d186b1596893098f.yaml
  tests/appsec/iast/aspects/test_ospath_aspects.py
Labels: ASM, backport 2.21, backport 3.2, backport 3.3

#13090 fix(graphql): change error location parsing to support older graphql-core
  ddtrace/contrib/internal/graphql/patch.py
  releasenotes/notes/graphql-location-parsing-8df82593800e2aa2.yaml
  tests/contrib/graphql/test_graphql.py
  tests/snapshots/tests.contrib.graphql.test_graphql.test_graphql_fail_2.x.json
Labels: backport 2.21, backport 3.2

#13102 chore(iast): bump absl version
  ddtrace/appsec/_iast/_taint_tracking/CMakeLists.txt
Labels: changelog/no-changelog, ASM

#12680 feat: support dbm full and service mode propagation for pymongo
  ddtrace/contrib/internal/pymongo/client.py
  ddtrace/contrib/internal/pymongo/patch.py
  ddtrace/propagation/_database_monitoring.py
  ddtrace/vendor/sqlcommenter/__init__.py
  docker-compose.yml
  releasenotes/notes/add-mongodb-dbm-propagation-support-3ff0f1423cafda8a.yaml
  tests/contrib/pymongo/test.py
Labels: mergequeue-status: in_progress

#13093 docs: remove outdated information from contribution testing docs
  docs/contributing-testing.rst
  tests/README.md
Labels: changelog/no-changelog

#13118 chore(llmobs): fix flaky evaluator runner log test
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_evaluator_runner.py
Labels: changelog/no-changelog

#13087 chore(iast): fix iast span metrics [backport 2.21]
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py
  ddtrace/appsec/_iast/_taint_utils.py
  ddtrace/appsec/_iast/taint_sinks/ast_taint.py
  ddtrace/appsec/_iast/taint_sinks/code_injection.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/path_traversal.py
  ddtrace/appsec/_iast/taint_sinks/sql_injection.py
  ddtrace/appsec/_iast/taint_sinks/ssrf.py
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/_iast/taint_sinks/weak_hash.py
  ddtrace/contrib/dbapi/__init__.py
  ddtrace/contrib/dbapi_async/__init__.py
  tests/appsec/iast/test_taint_utils.py
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#13127 chore(serverless): remove flaky mark from two serverless tests [backport 3.2]
  tests/contrib/aws_lambda/test_aws_lambda.py
Labels: changelog/no-changelog

#13109 chore(tracing): get config from pin
  ddtrace/_trace/pin.py
  ddtrace/contrib/internal/httplib/patch.py
  ddtrace/contrib/internal/requests/connection.py
  ddtrace/settings/_config.py
  tests/contrib/httplib/test_httplib_distributed.py
  tests/contrib/jinja2/test_jinja2.py
  tests/contrib/requests/test_requests.py
  tests/contrib/requests/test_requests_distributed.py
  tests/tracer/test_instance_config.py
Labels: changelog/no-changelog

#13059 chore: update supported versions workflow
  scripts/freshvenvs.py
  supported_versions_output.json
  supported_versions_table.csv
Labels: changelog/no-changelog

#13135 ci: don't fail with perf regressions on releases
  .gitlab/benchmarks/microbenchmarks.yml
Labels: changelog/no-changelog, backport 2.21, backport 3.1, backport 3.2, backport 3.3, backport 3.4

#13141 ci: update regression check rules for release tags
  .gitlab/benchmarks/microbenchmarks.yml
Labels: changelog/no-changelog, backport 2.21, backport 3.2, backport 3.3, backport 3.4

#13146 chore(profiling): remove flaky marker on test_accuracy
  tests/profiling/test_accuracy.py
Labels: changelog/no-changelog

#13132 chore(iast): add more iast tests types
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_patches/json_tainting.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_iast/_taint_utils.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  tests/appsec/iast/aspects/aspect_utils.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_common_aspects.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/taint_sinks/test_sql_injection.py
  tests/appsec/integrations/django_tests/django_app/settings.py
  tests/appsec/integrations/django_tests/django_app/urls.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#13166 chore(llmobs): add codeowner entries for oai_agents integration
  .github/CODEOWNERS
Labels: changelog/no-changelog

#13154 chore(asm): remove static cycles
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_ddwaf/waf.py
  ddtrace/appsec/_ddwaf/waf_mock.py
  ddtrace/appsec/_ddwaf/waf_stubs.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_utils.py
  tests/appsec/appsec/api_security/test_schema_fuzz.py
  tests/appsec/appsec/test_processor.py
Labels: changelog/no-changelog, ASM

#13156 fix(iast): invalid f-string type conversions exception in format_value_aspect
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  releasenotes/notes/iast-fstring-exception-d460a37b6e44f972.yaml
  tests/appsec/iast/aspects/test_str_py3.py
Labels: ASM, backport 2.21, backport 3.3, backport 3.4

#13175 chore(iast): update gitignore
  .gitignore
Labels: changelog/no-changelog, ASM

#13177 chore(tracer): remove http dependency to trace
  ddtrace/propagation/http.py
Labels: changelog/no-changelog, Tracing

#13170 chore: use `functools.wraps` in `callonce` decorator
  ddtrace/internal/utils/cache.py
Labels: changelog/no-changelog

#13155 chore(iast): add more iast tests types
  benchmarks/bm/iast_fixtures/str_methods_py3.py
  ddtrace/appsec/_iast/_logs.py
  tests/appsec/iast/aspects/test_add_aspect.py
  tests/appsec/iast/aspects/test_add_inplace_aspect.py
  tests/appsec/iast/aspects/test_format_aspect_fixtures.py
  tests/appsec/iast/aspects/test_fstrings.py
  tests/appsec/iast/aspects/test_str_py3.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/taint_tracking/test_taint_tracking.py
Labels: changelog/no-changelog, ASM

#13167 perf: avoid repeated access to `dist.files` to reduce overhead
  .gitlab/benchmarks/microbenchmarks.yml
  benchmarks/packages_package_for_root_module_mapping/config.yaml
  benchmarks/packages_package_for_root_module_mapping/requirements_scenario.txt
  benchmarks/packages_package_for_root_module_mapping/scenario.py
  ddtrace/internal/packages.py
Labels: changelog/no-changelog

#13180 chore(tracer): upgrade mypy to last version
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_taint_tracking/_taint_objects.py
  ddtrace/appsec/_processor.py
  ddtrace/internal/ci_visibility/git_client.py
  ddtrace/internal/compat.py
  ddtrace/internal/core/__init__.py
  ddtrace/internal/gitmetadata.py
  ddtrace/internal/periodic.py
  ddtrace/internal/utils/time.py
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/pytorch.py
  ddtrace/profiling/collector/threading.py
  ddtrace/profiling/recorder.py
  hatch.toml
Labels: changelog/no-changelog

#13183 chore(llmobs): handle pydantic validation for adding datadog spans to langchain instances
  ddtrace/llmobs/_integrations/langchain.py
Labels: changelog/no-changelog

#13162 chore(filters): remove unused code
  ddtrace/_trace/filters.py
  tests/tracer/test_filters.py
Labels: changelog/no-changelog

#13169 chore(asm): remove threat import cycles
  ddtrace/_monkey.py
  ddtrace/appsec/__init__.py
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_listeners.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_remoteconfiguration.py
Labels: changelog/no-changelog, ASM

#13178 chore(asm): dropping tracer requirement from user event functions
  ddtrace/appsec/_trace_utils.py
  ddtrace/contrib/internal/trace_utils.py
  tests/appsec/integrations/django_tests/conftest.py
Labels: changelog/no-changelog, ASM

#13186 fix(subprocess): simplify subprocess debug logging messages
  ddtrace/contrib/internal/subprocess/patch.py
  releasenotes/notes/fix-subprocess-debug-logging-d6eb35359abdbda5.yaml
Labels: backport 2.21, backport 3.4

#13192 chore: fix malformed release note blocking release script
  releasenotes/notes/referrer-hostname-8aa6dc6edb9d53b1.yaml
Labels: changelog/no-changelog

#13195 ci: correctly identify base branch for microbenchmarks
  .gitlab/benchmarks/microbenchmarks.yml
  .gitlab/benchmarks/steps/detect-baseline.sh
Labels: changelog/no-changelog, backport 2.21, backport 3.3, backport 3.4

#13204 refactor: remove cycle in processor stats
  ddtrace/internal/processor/stats.py
Labels: changelog/no-changelog

#13096 chore: update changelog for version 2.21.5, 3.2.1, 3.3.1, 3.3.2, 3.4.0, 3.4.1
  CHANGELOG.md
Labels: changelog/no-changelog

#13218 chore(profiling): explicitly set or clear NDEBUG for memalloc extension
  setup.py
Labels: changelog/no-changelog

#12749 chore(tracing): simplify trace sampling and span aggregation
  benchmarks/appsec_iast_django_startup/views.py
  benchmarks/bm/utils.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/tracer.py
  ddtrace/contrib/internal/tornado/application.py
  ddtrace/internal/ci_visibility/filters.py
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/datastreams/__init__.py
  ddtrace/internal/datastreams/processor.py
  ddtrace/internal/debug.py
  ddtrace/internal/processor/stats.py
  ddtrace/opentracer/tracer.py
  ddtrace/settings/_config.py
  tests/appsec/app.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/integrations/flask_tests/test_flask_remoteconfig.py
  tests/appsec/utils.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client.py
  tests/ci_visibility/test_ci_visibility.py
  tests/ci_visibility/test_is_user_provided_service.py
  tests/commands/ddtrace_run_dogstatsd.py
  tests/commands/ddtrace_run_hostname.py
  tests/commands/ddtrace_run_integration.py
  tests/contrib/asynctest/test_asynctest.py
  tests/contrib/falcon/test_suite.py
  tests/contrib/grpc_aio/test_grpc_aio.py
  tests/contrib/kafka/test_kafka.py
  tests/contrib/redis/test_redis.py
  tests/contrib/requests/test_requests.py
  tests/contrib/urllib3/test_urllib3.py
  tests/integration/test_debug.py
  tests/integration/test_integration.py
  tests/integration/test_integration_civisibility.py
  tests/integration/test_integration_snapshots.py
  tests/integration/test_priority_sampling.py
  tests/integration/test_trace_stats.py
  tests/integration/utils.py
  tests/llmobs/test_llmobs_service.py
  tests/opentelemetry/test_config.py
  tests/tracer/test_encoders.py
  tests/tracer/test_processors.py
  tests/tracer/test_tracer.py
  tests/utils.py
Labels: changelog/no-changelog

#13220 fix(llmobs): set session ID on span if annotated as a tag
  ddtrace/llmobs/_llmobs.py
  releasenotes/notes/fix-llmobs-session-id-via-tags-6f6b0f7fca47e516.yaml
  tests/llmobs/test_llmobs_service.py
Labels: backport 2.21

#13213 chore: bump python version in benchmark dockerfile
  benchmarks/Dockerfile
Labels: changelog/no-changelog

#13212 chore: skip None line numbers in inspection
  ddtrace/internal/utils/inspection.py
  tests/internal/symbol_db/test_symbols.py
Labels: changelog/no-changelog

#13223 fix(profiling): update echion to pick up a potential undefined behavior fix
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  releasenotes/notes/profiling-update-echion-queue-ub-fix-b14e8c603f2e115f.yaml
Labels: backport 2.21

#13222 ci: add manual break glass options for tests and benchmarks
  .gitlab-ci.yml
  .gitlab/benchmarks/serverless.yml
Labels: changelog/no-changelog, backport 2.21

#13226 ci: allow flaky benchmarks to fail
  .gitlab/benchmarks/microbenchmarks.yml
Labels: changelog/no-changelog, backport 2.21

#13185 refactor(profiling): pool memalloc traceback scratch buffers
  ddtrace/profiling/collector/_memalloc_tb.c
Labels: changelog/no-changelog, Profiling

#13110 perf(profiling): stack-v2 adaptive sampling
  ddtrace/internal/datadog/profiling/stack_v2/include/constants.hpp
  ddtrace/internal/datadog/profiling/stack_v2/include/sampler.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_v2.cpp
  ddtrace/profiling/collector/stack.pyx
  ddtrace/settings/profiling.py
  releasenotes/notes/prf-stack-v2-adaptive-sampling-38cd6af0882fc36b.yaml
  tests/profiling_v2/test_accuracy.py
  tests/profiling_v2/test_gunicorn.py
Labels: Profiling

#13232 ci: restructure gitlab tests child pipeline
  .gitlab/tests.yml
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog

#13227 ci: lower benchmark job timeouts to 30m
  .gitlab/benchmarks/microbenchmarks.yml
Labels: changelog/no-changelog, backport 2.21

#13234 chore(llmobs): cleanup endpoint constants for agentless writers
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_writer.py
  tests/llmobs/test_llmobs_eval_metric_agent_writer.py
  tests/llmobs/test_llmobs_span_agent_writer.py
  tests/llmobs/test_llmobs_span_agentless_writer.py
Labels: changelog/no-changelog

#13191 chore(asm): remove circular dependencies
  benchmarks/appsec_iast_aspects/scenario.py
  benchmarks/appsec_iast_aspects_ospath/scenario.py
  benchmarks/appsec_iast_aspects_re_module/scenario.py
  benchmarks/appsec_iast_aspects_split/scenario.py
  benchmarks/appsec_iast_propagation/scenario.py
  ddtrace/appsec/_handlers.py
  ddtrace/appsec/_iast/_evidence_redaction/__init__.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_env.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_iast_request_context_base.py
  ddtrace/appsec/_iast/processor.py
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_iast/taint_sinks/stacktrace_leak.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/_utils.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/contrib/internal/trace_utils.py
  ddtrace/contrib/internal/trace_utils_base.py
  scripts/iast/leak_functions.py
  tests/appsec/appsec/test_tools.py
  tests/appsec/iast/conftest.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/utils.py
Labels: changelog/no-changelog, ASM

#13054 perf(profiling): remove utf8 check
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/include/vendored/utf8_validate.hpp
  ddtrace/internal/datadog/profiling/stack_v2/src/stack_renderer.cpp
  releasenotes/notes/prof-perf-utf8-c3e0ea98c4a17e11.yaml
Labels: changelog/no-changelog, Profiling

#13124 chore: update changelog for version 2.21.6, 3.2.3, 3.3.3
  CHANGELOG.md
Labels: changelog/no-changelog

#13122 chore: replaced with _get_config for pyramid integration
  ddtrace/contrib/internal/pyramid/patch.py
Labels: changelog/no-changelog

#13217 chore: add a job that check that all other jobs are green on PR
  .github/workflows/all-green.yml
Labels: changelog/no-changelog

#13246 chore: remove obsolete version field in docker-compose.yml
  docker-compose.yml
Labels: changelog/no-changelog, testing

#13241 chore(telemetry): remove redundant lib_language tag in telemetry
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_metrics.py
  ddtrace/internal/telemetry/logging.py
Labels: changelog/no-changelog, ASM

#13245 fix(sampling): ensure sampling rules can be unset via remote config
  ddtrace/settings/_config.py
  releasenotes/notes/fix-empty-remote-sampling-rules-417c6032875171b9.yaml
  tests/internal/test_settings.py
Labels: backport 2.21

#13243 chore(iast): normalize iast logs
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
Labels: changelog/no-changelog, ASM

#13240 chore(iast): restructure functions
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context_base.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/appsec/_iast/_span_metrics.py
  ddtrace/appsec/_iast/_taint_utils.py
  ddtrace/appsec/_iast/_utils.py
Labels: changelog/no-changelog, ASM

#13252 chore(iast): avoid hardcoding array sizes
  ddtrace/appsec/_iast/_ast/iastpatch.c
Labels: changelog/no-changelog, ASM

#13239 chore(iast): check secure marks for SQLi
  ddtrace/appsec/_iast/_ast/iastpatch.c
  ddtrace/appsec/_iast/_patch_modules.py
  hatch.toml
  tests/appsec/iast/db_utils.py
  tests/appsec/iast/fixtures/taint_sinks/sql_injection_psycopg2.py
  tests/appsec/iast/fixtures/taint_sinks/sql_injection_pymysql.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/iast/test_iast_dbs.py
  tests/appsec/iast/test_iast_psycopg2.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/fixtures/patch_dbs.py
  tests/appsec/integrations/fixtures/patch_psycopg2.py
Labels: changelog/no-changelog, ASM

#13242 chore(iast): check secure marks for path traversal
  ddtrace/appsec/_iast/_patch_modules.py
  tests/appsec/iast/test_iast_dbs.py
  tests/appsec/integrations/fixtures/patch_file_paths.py
  tests/appsec/integrations/flask_tests/test_sanitizers.py
Labels: changelog/no-changelog, ASM

#13181 chore(llmobs): re-enable langchain llmobs tests
  tests/contrib/langchain/cassettes/anthropic_chat_completion_sync.yaml
  tests/contrib/langchain/cassettes/bedrock_amazon_chat_invoke.yaml
  tests/contrib/langchain/cassettes/bedrock_amazon_invoke.yaml
  tests/contrib/langchain/cassettes/cohere_completion_sync.yaml
  tests/contrib/langchain/cassettes/lcel_openai_chain_call.yaml
  tests/contrib/langchain/cassettes/lcel_openai_chain_schema_io.yaml
  tests/contrib/langchain/cassettes/lcel_with_tools_openai.yaml
  tests/contrib/langchain/cassettes/openai_chat_completion_sync_call.yaml
  tests/contrib/langchain/cassettes/openai_completion_non_ascii.yaml
  tests/contrib/langchain/cassettes/openai_completion_sync.yaml
  tests/contrib/langchain/cassettes/openai_embedding_query_integration.yaml
  tests/contrib/langchain/conftest.py
  tests/contrib/langchain/test_langchain_llmobs.py
  tests/contrib/langchain/utils.py
Labels: changelog/no-changelog

#13236 docs: kafka message header limitation
  ddtrace/contrib/_kafka.py
Labels: changelog/no-changelog

#13261 chore(iast): check secure marks for xss
  ddtrace/appsec/_iast/_ast/iastpatch.c
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/secure_marks/sanitizers.py
  hatch.toml
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_sql_injection.py
  tests/appsec/iast/test_iast_dbs.py
  tests/appsec/iast/test_telemetry.py
  tests/appsec/integrations/django_tests/django_app/urls.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/fixtures/__init__.py
  tests/appsec/integrations/fixtures/patch_file_paths.py
  tests/appsec/integrations/fixtures/patch_psycopg2.py
  tests/appsec/integrations/fixtures/patch_sanitizers.py
  tests/appsec/integrations/fixtures/sql_injection_mysqldb.py
  tests/appsec/integrations/fixtures/sql_injection_psycopg2.py
  tests/appsec/integrations/fixtures/sql_injection_pymysql.py
  tests/appsec/integrations/fixtures/sql_injection_sqlalchemy.py
  tests/appsec/integrations/fixtures/sql_injection_sqlite3.py
  tests/appsec/integrations/flask_tests/test_sanitizers.py
  tests/appsec/integrations/packages_tests/__init__.py
  tests/appsec/integrations/packages_tests/conftest.py
  tests/appsec/integrations/packages_tests/db_utils.py
  tests/appsec/integrations/packages_tests/test_iast_psycopg2_extensions.py
  tests/appsec/integrations/packages_tests/test_iast_sanitizers.py
  tests/appsec/integrations/packages_tests/test_iast_sql_injection.py
  tests/appsec/integrations/packages_tests/test_iast_telemetry.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12363 perf(serverless): create noop telemetry writer when telemetry disabled
  ddtrace/internal/telemetry/__init__.py
  ddtrace/internal/telemetry/noop_writer.py
  tests/internal/test_serverless.py
Labels: changelog/no-changelog

#13194 chore: fix stale PR closing workflow
  .github/workflows/stale.yml
Labels: changelog/no-changelog

#13258 perf(iast): make benchmarks more stable
  benchmarks/appsec_iast_aspects/scenario.py
Labels: changelog/no-changelog, ASM

#13274 chore(asm): remove dead code for headers and improve warning logs
  ddtrace/appsec/_api_security/api_manager.py
Labels: changelog/no-changelog, ASM

#13250 chore(rc): use dummy array when shared memory not available
  ddtrace/internal/remoteconfig/_connectors.py
Labels: changelog/no-changelog

#13276 chore: handle products that fail to load
  ddtrace/internal/products.py
  tests/internal/test_products.py
Labels: bug, changelog/no-changelog

#13176 ci(iast): remove allow failure from pygoat test
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#13100 fix(tracing): do not incorrectly match on None with ?*
  ddtrace/_trace/sampling_rule.py
  releasenotes/notes/fix_incorrect_sampler_match_on_none-c6e04cc4dfdf9007.yaml
  tests/tracer/test_sampler.py
Labels: backport 2.21

#13281 chore(build): remove unused build-dist* files
  scripts/build-dist
  scripts/build-dist-cp27
  scripts/gen_gitlab_config.py
  scripts/mkwheelhouse
Labels: changelog/no-changelog

#13284 ci: update arm64 runners to arm-4core-linux-ubuntu24.04
  .github/workflows/build_python_3.yml
Labels: changelog/no-changelog, CI, backport 2.21

#13291 chore(iast): test vulnerability locations in pygoat
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: changelog/no-changelog, ASM

#13266 chore(iast): strip, rstrip, lstrip aspects
  benchmarks/appsec_iast_aspects/config.yaml
  benchmarks/appsec_iast_aspects/functions.py
  ddtrace/appsec/_iast/_ast/visitor.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  scripts/iast/mod_leak_functions.py
  tests/appsec/iast/aspects/test_strip_aspect.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/integrations/packages_tests/test_iast_sanitizers.py
Labels: changelog/no-changelog, ASM

#13251 feat(asm): new user event sdk
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/track_user_sdk.py
  releasenotes/notes/ato_sdk_v2-35c17dc258c5b690.yaml
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
Labels: ASM

#13302 chore(ci): do not run all-green job on pushes on main
  .github/workflows/all-green.yml
Labels: changelog/no-changelog

#13269 docs: update versioning docs
  docs/contributing.rst
  docs/releasenotes.rst
  docs/versioning.rst
Labels: changelog/no-changelog
