Repository DataDog/dd-trace-py, pull requests merged in 2025-05, with the labels that each got.

#13303 fix(kafka): allow producer/consumer initialized with unpacked config [APMS-15618]
  ddtrace/contrib/internal/kafka/patch.py
  releasenotes/notes/fix-consumer-producer-config-initialize-6f17da8b3a806b7e.yaml
  tests/contrib/kafka/test_kafka.py
Labels: backport 2.21

#13309 fix(debugging): make probe instances hashable
  ddtrace/debugging/_probe/model.py
  releasenotes/notes/fix-debugger-hashable-probes-4a9ae0b7f1d40791.yaml
  tests/debugging/probe/test_model.py
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation, backport 2.21

#13306 chore: removing python2 types in compat.py
  ddtrace/internal/compat.py
Labels: changelog/no-changelog

#13247 chore(stable_config): collect debug logs when DD_TRACE_DEBUG is True
  ddtrace/internal/native/__init__.py
  tests/internal/test_native.py
Labels: changelog/no-changelog

#13249 chore(ssi): improve telemetry submitted for ssi configurations
  ddtrace/bootstrap/sitecustomize.py
  ddtrace/settings/_config.py
  lib-injection/sources/sitecustomize.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog

#13168 fix(futures): ensure child spans are correctly parented in Threadpools
  ddtrace/_trace/context.py
  ddtrace/_trace/provider.py
  ddtrace/_trace/span.py
  ddtrace/_trace/tracer.py
  ddtrace/contrib/internal/futures/threading.py
  releasenotes/notes/fix-futures-parenting-3a53b94ee05dff93.yaml
  tests/contrib/futures/test_propagation.py
  tests/tracer/test_tracer.py
Labels: backport 2.21

#13297 ci(iast): fix postgres connexion in integrations_packages
  hatch.toml
  tests/appsec/integrations/fixtures/sql_injection_mysqldb.py
  tests/appsec/integrations/fixtures/sql_injection_psycopg2.py
  tests/appsec/integrations/fixtures/sql_injection_sqlalchemy.py
  tests/appsec/integrations/packages_tests/db_utils.py
Labels: changelog/no-changelog, ASM

#13299 fix(iast): incorrectly named as class_name
  ddtrace/appsec/_iast/reporter.py
  releasenotes/notes/iast-vulnerability-report-wrong-key-4940989d2328512d.yaml
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/taint_sinks/test_header_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_path_traversal_redacted.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/appsec/integrations/flask_tests/test_iast_langchain.py
  tests/appsec/integrations/packages_tests/test_iast_sql_injection.py
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: ASM

#13300 chore(iast): improve iast report performance
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/reporter.py
Labels: changelog/no-changelog, ASM

#13329 chore(tracer): handle None in activate_distributed_headers
  ddtrace/contrib/internal/trace_utils.py
  tests/tracer/test_trace_utils.py
Labels: changelog/no-changelog

#12687 chore(symdb): include SHA1 of module sources
  .riot/requirements/1ae8364.txt
  .riot/requirements/2b85fce.txt
  .riot/requirements/84112c9.txt
  .riot/requirements/c9a1437.txt
  .riot/requirements/cfa931e.txt
  .riot/requirements/ed1ebcd.txt
  ddtrace/internal/symbol_db/symbols.py
  riotfile.py
  tests/internal/symbol_db/test_symbols.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#13320 chore(ci): upload bench results to bench API on main
  .gitlab/benchmarks/microbenchmarks.yml
Labels: changelog/no-changelog

#13272 fix(iast): avoid excessive filtering of stacktrace locations
  ddtrace/appsec/_iast/_stacktrace.c
  ddtrace/appsec/_iast/_stacktrace.pyi
  ddtrace/appsec/_iast/taint_sinks/_base.py
  releasenotes/notes/fix-iast-stacktrace-filter-6afd6a9568f36d99.yaml
  tests/appsec/iast/taint_sinks/test_weak_hash.py
  tests/appsec/iast_memcheck/_stacktrace_py.py
  tests/appsec/iast_memcheck/fixtures/stacktrace.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: ASM, backport 2.21

#13337 ci: pin system-tests commit hash
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#13319 fix(debugging): make probe instances hashable [backport #13309 to 2.21]
  ddtrace/debugging/_probe/model.py
  releasenotes/notes/fix-debugger-hashable-probes-4a9ae0b7f1d40791.yaml
  tests/debugging/probe/test_model.py
  tests/debugging/test_debugger.py
Labels: Dynamic Instrumentation, backport 2.21

#13334 chore(ci-visibility): use v4 evp proxy endpoint if available
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/constants.py
  ddtrace/internal/ci_visibility/recorder.py
  tests/ci_visibility/api_client/_util.py
  tests/ci_visibility/api_client/test_ci_visibility_api_client.py
  tests/ci_visibility/test_ci_visibility.py
Labels: changelog/no-changelog, CI App

#13317 perf(profiling): improve scaling of memory profiler for large heaps
  ddtrace/profiling/collector/_memalloc_heap.c
  ddtrace/profiling/collector/_memalloc_heap_map.c
  ddtrace/profiling/collector/_memalloc_heap_map.h
  ddtrace/profiling/collector/vendor/cwisstable.h
  releasenotes/notes/profiling-memalloc-faster-heap-map-470b7f3980135e8a.yaml
  setup.py
Labels: backport 2.21

#13339 fix(llmobs): reuse shared conn
  ddtrace/llmobs/_writer.py
  releasenotes/notes/fix-llmobs-unix-agent-2b959d436e6474c3.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_eval_metric_agentless_writer.test_send_metric_bad_api_key.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_evaluator_runner.send_score_metric.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_span_agentless_writer.test_send_completion_bad_api_key.yaml
  tests/llmobs/test_llmobs_eval_metric_agent_writer.py
  tests/llmobs/test_llmobs_eval_metric_agentless_writer.py
  tests/llmobs/test_llmobs_evaluator_runner.py
  tests/llmobs/test_llmobs_span_agent_writer.py
  tests/llmobs/test_llmobs_span_agentless_writer.py
Labels: backport 2.21

#13344 chore(iast): improve detection of ddtrace frames
  ddtrace/appsec/_iast/_stacktrace.c
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: changelog/no-changelog, ASM, backport 2.21

#13340 ci: reduce build_base_venvs verbosity
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog

#13353 refactor(profiler): clear frozen map instead of using invalid iterator
  ddtrace/profiling/collector/_memalloc_heap_map.c
Labels: changelog/no-changelog

#13349 ci: add manual break glass options for tests and benchmarks (#13222)
  .gitlab-ci.yml
Labels: changelog/no-changelog

#13330 feat(ci-visibility): evp proxy gzip payload support
  ddtrace/internal/ci_visibility/recorder.py
  ddtrace/internal/ci_visibility/writer.py
  releasenotes/notes/ci-vis-gzip-payload-evp-8269d43f2721afa1.yaml
  tests/ci_visibility/test_ci_visibility.py
  tests/integration/test_integration_civisibility.py
Labels: CI App

#13333 chore(iast): do not serialize empty strings in location fields
  ddtrace/appsec/_iast/reporter.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  tests/appsec/iast/fixtures/taint_sinks/path_traversal.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
  tests/appsec/iast/taint_sinks/test_header_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_path_traversal.py
  tests/appsec/iast/taint_sinks/test_path_traversal_redacted.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/appsec/iast/test_iast_propagation_path.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/appsec/integrations/flask_tests/test_iast_langchain.py
  tests/appsec/integrations/packages_tests/test_iast_sql_injection.py
  tests/appsec/integrations/pygoat_tests/test_pygoat.py
Labels: changelog/no-changelog, ASM

#13358 chore(iast): stackId should report inside vulnerability location
  ddtrace/appsec/_iast/_stacktrace.c
  ddtrace/appsec/_iast/reporter.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#13355 ci(tracing): fix flaky span event encoding test
  tests/tracer/test_encoders.py
Labels: changelog/no-changelog

#13342 chore(ssi): track ssi source across subprocesses
  ddtrace/bootstrap/sitecustomize.py
  lib-injection/sources/sitecustomize.py
Labels: changelog/no-changelog

#13364 ci: fix docs build [backport 2.21]
  scripts/docs/build.sh
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog

#13368 chore(build): fix windows build errors from ddup
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
Labels: changelog/no-changelog

#13367 ci: add missing parts to the ci_visibility suitespec
  tests/ci_visibility/suitespec.yml
Labels: changelog/no-changelog, CI, backport 2.21

#13345 fix(iast): avoid excessive filtering of stacktrace locations [2.21]
  ddtrace/appsec/_iast/_stacktrace.c
  ddtrace/appsec/_iast/_stacktrace.pyi
  ddtrace/appsec/_iast/taint_sinks/_base.py
  releasenotes/notes/fix-iast-stacktrace-filter-6afd6a9568f36d99.yaml
  tests/appsec/iast/taint_sinks/test_weak_hash.py
  tests/appsec/iast_memcheck/_stacktrace_py.py
  tests/appsec/iast_memcheck/fixtures/stacktrace.py
  tests/appsec/iast_memcheck/test_iast_mem_check.py
Labels: ASM

#13373 chore(build): disable VPA
  .gitlab-ci.yml
Labels: changelog/no-changelog

#13356 chore(configuration): replace instances of os.environ
  ddtrace/contrib/internal/pytest/_plugin_v1.py
  ddtrace/contrib/internal/pytest/_utils.py
Labels: changelog/no-changelog

#13288 fix(ci-visibility): pytest-xdist atr compatibility
  .riot/requirements/10b8fc3.txt
  .riot/requirements/1161c0d.txt
  .riot/requirements/1163993.txt
  .riot/requirements/1188714.txt
  .riot/requirements/1252d0f.txt
  .riot/requirements/144615f.txt
  .riot/requirements/14ca37f.txt
  .riot/requirements/14f833a.txt
  .riot/requirements/16c7da9.txt
  .riot/requirements/171ef0d.txt
  .riot/requirements/17cf97e.txt
  .riot/requirements/18147c2.txt
  .riot/requirements/1a479eb.txt
  .riot/requirements/1b09cab.txt
  .riot/requirements/1b81f78.txt
  .riot/requirements/1becf29.txt
  .riot/requirements/1cb8d25.txt
  .riot/requirements/1f42cb3.txt
  .riot/requirements/3ae0efb.txt
  .riot/requirements/3af9e27.txt
  .riot/requirements/45d6b64.txt
  .riot/requirements/48eb599.txt
  .riot/requirements/535e315.txt
  .riot/requirements/8fd4efc.txt
  .riot/requirements/91bec06.txt
  .riot/requirements/95e6f73.txt
  .riot/requirements/a61cb6c.txt
  .riot/requirements/abd1978.txt
  .riot/requirements/d03449e.txt
  .riot/requirements/e623dde.txt
  ddtrace/contrib/internal/pytest/_atr_utils.py
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  releasenotes/notes/ci-vis-atr-xdist-b358a3f9039dd67d.yaml
  riotfile.py
  tests/contrib/pytest/test_pytest_atr.py
  tests/contrib/pytest/test_pytest_xdist_atr.py
Labels: CI App

#13357 fix(di): prevent exception when removing unresolved probe
  ddtrace/debugging/_probe/registry.py
  releasenotes/notes/fix-unresolved-pending-probe-removal-80fbf85a9c068122.yaml
  tests/debugging/probe/test_registry.py
Labels: Dynamic Instrumentation, backport 2.21

#13304 feat(openai): [MLOB-2680] support responses endpoint
  ddtrace/contrib/internal/openai/_endpoint_hooks.py
  ddtrace/contrib/internal/openai/patch.py
  ddtrace/contrib/internal/openai/utils.py
  ddtrace/llmobs/_integrations/openai.py
  releasenotes/notes/openai-responses-apm-e20c66473f3da435.yaml
  tests/contrib/openai/cassettes/v1/response.yaml
  tests/contrib/openai/cassettes/v1/response_create_error.yaml
  tests/contrib/openai/cassettes/v1/response_stream.yaml
  tests/contrib/openai/cassettes/v1/response_tools.yaml
  tests/contrib/openai/cassettes/v1/response_tools_stream.yaml
  tests/contrib/openai/test_openai_v1.py
  tests/snapshots/tests.contrib.openai.test_openai.test_response.json
  tests/snapshots/tests.contrib.openai.test_openai.test_response_error.json
  tests/snapshots/tests.contrib.openai.test_openai.test_response_stream.json
  tests/snapshots/tests.contrib.openai.test_openai.test_response_tools.json
  tests/snapshots/tests.contrib.openai.test_openai.test_response_tools_stream.json
Labels: mergequeue-status: removed

#13348 chore(iast): avoid exception when no relevant frame is found [2.21]
  ddtrace/appsec/_iast/_stacktrace.c
  ddtrace/appsec/_iast/taint_sinks/_base.py
  tests/appsec/iast/test_stacktrace.py
Labels: changelog/no-changelog, ASM

#13381 chore(iast): add route to starlette wrapper function
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_patch.py
  ddtrace/contrib/internal/starlette/patch.py
Labels: changelog/no-changelog, ASM

#13365 chore(ci): iast_packages tests from hatch to riot
  .riot/requirements/1069d84.txt
  .riot/requirements/10802a6.txt
  .riot/requirements/5e15510.txt
  .riot/requirements/77db507.txt
  .riot/requirements/ab9099f.txt
  hatch.toml
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
  scripts/gen_gitlab_config.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM, CI

#13388 chore(CI): move iast memcheck to riot
  .riot/requirements/1024326.txt
  .riot/requirements/109346f.txt
  .riot/requirements/10e2a10.txt
  .riot/requirements/19220a6.txt
  .riot/requirements/5e5ef4e.txt
  .riot/requirements/9829428.txt
  hatch.toml
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM, backport 2.21

#13383 chore(iast): header injection sanitizers
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/secure_marks/sanitizers.py
  static-analysis.datadog.yml
  tests/appsec/app.py
  tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
Labels: changelog/no-changelog, ASM

#13387 chore: fix benchmak dependencies
  benchmarks/appsec_iast_django_startup/requirements.in
  benchmarks/appsec_iast_django_startup/requirements_scenario.txt
  benchmarks/django_simple/requirements_scenario.txt
  benchmarks/errortracking_django_simple/requirements_scenario.txt
Labels: changelog/no-changelog, ASM

#13370 fix(profiling): crash with `synchronized_sample_pool` on uWSGI shutdown
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/constants.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample_manager.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/static_sample_pool.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/synchronized_sample_pool.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample_manager.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/static_sample_pool.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/synchronized_sample_pool.cpp
  releasenotes/notes/fix-crash-in-uwsgi-94d23690d85b2981.yaml
Labels: bug, Profiling, backport 2.21

#13393 perf: improve performance of code-to-function lookups
  ddtrace/internal/utils/inspection.py
  releasenotes/notes/prf-functions_for_code-9634ef79190978cf.yaml
Labels: backport 2.21

#13399 test(profiling): skip flaky gevent tests on 3.8
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog, Profiling

#12957 chore(symdb): add shallow mode
  ddtrace/debugging/_debugger.py
  ddtrace/internal/products.py
  ddtrace/internal/symbol_db/__init__.py
  ddtrace/internal/symbol_db/remoteconfig.py
  ddtrace/internal/symbol_db/symbols.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#13392 ci(docs): clean up docs job and set static title
  docs/conf.py
  hatch.toml
Labels: changelog/no-changelog

#13325 chore(llmobs): default role if not provided on the message
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_utils.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog

#13408 chore(profiling): log when importing memalloc fails
  ddtrace/profiling/collector/memalloc.py
Labels: changelog/no-changelog

#13402 ci: fix build_docs artifacts
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog

#13376 chore(ci_visibility): move retry logic to pytest_runtest_protocol
  ddtrace/contrib/internal/pytest/_atr_utils.py
  ddtrace/contrib/internal/pytest/_attempt_to_fix.py
  ddtrace/contrib/internal/pytest/_efd_utils.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/_retry_utils.py
  ddtrace/contrib/internal/pytest/_utils.py
  ddtrace/contrib/internal/pytest/plugin.py
Labels: changelog/no-changelog, CI App

#13412 chore(et): improve error_tracking documentation
  docs/basic_usage.rst
Labels: changelog/no-changelog

#13414 fix(ci-visibility): proper test suite status with xdist
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/api/_base.py
  releasenotes/notes/ci-vis-xdist-suite-failing-3a0c20b8379f10e4.yaml
  tests/contrib/pytest/test_pytest_xdist_snapshot.py
  tests/snapshots/tests.contrib.pytest.test_pytest_xdist_snapshot.test_pytest_xdist_will_include_lines_pct.json
  tests/snapshots/tests.contrib.pytest.test_pytest_xdist_snapshot.test_pytest_xdist_with_ddtrace_patch_all.json
  tests/snapshots/tests.contrib.pytest.test_pytest_xdist_snapshot.test_pytest_xdist_wont_include_lines_pct_if_report_empty.json
Labels: backport 2.21

#13416 Revert "chore(ci_visibility): move retry logic to pytest_runtest_protocol (#13376)"
  ddtrace/contrib/internal/pytest/_atr_utils.py
  ddtrace/contrib/internal/pytest/_attempt_to_fix.py
  ddtrace/contrib/internal/pytest/_efd_utils.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/_retry_utils.py
  ddtrace/contrib/internal/pytest/_utils.py
  ddtrace/contrib/internal/pytest/plugin.py
Labels: changelog/no-changelog, CI App

#13256 feat(iast): add support for langchain v0.1.0+
  ddtrace/appsec/_iast/_ast/iastpatch.c
  ddtrace/appsec/_iast/_langchain.py
  ddtrace/appsec/_iast/_listener.py
  ddtrace/contrib/internal/langchain/constants.py
  ddtrace/contrib/internal/langchain/patch.py
  ddtrace/contrib/internal/langchain/utils.py
  hatch.toml
  releasenotes/notes/iast-langchain-0.1.0-e437ea90fe66ad31.yaml
  tests/appsec/iast/conftest.py
  tests/appsec/iast/iast_utils.py
  tests/appsec/integrations/fixtures/patch_langchain.py
  tests/appsec/integrations/flask_tests/test_iast_langchain.py
  tests/appsec/integrations/langchain_tests/conftest.py
  tests/appsec/integrations/langchain_tests/test_iast_langchain.py
  tests/appsec/suitespec.yml
Labels: ASM

#13429 chore(ci): use datadog/ensure-ci-success instead of wechuli/allcheckspassed
  .github/workflows/all-green.yml
Labels: changelog/no-changelog, backport 2.21

#13434 chore: update changelog for version 2.21.8
  CHANGELOG.md
Labels: changelog/no-changelog

#13415 chore(ci_visibility): support Attempt-to-Fix v4
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/internal/ci_visibility/_api_client.py
  ddtrace/internal/ci_visibility/api/_test.py
  tests/contrib/pytest/test_pytest_attempt_to_fix.py
Labels: changelog/no-changelog, CI App

#13435 ci(appsec): add flaky decorator to failing langchain tests
  tests/appsec/integrations/langchain_tests/test_iast_langchain.py
Labels: changelog/no-changelog

#13436 ci: pin system-tests version [3.7]
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#13440 ci: ignore devflow/* jobs for all-green status
  .github/workflows/all-green.yml
Labels: changelog/no-changelog

#13398 ci: pin one-pipeline version
  .gitlab-ci.yml
  .gitlab/one-pipeline.locked.yml
Labels: changelog/no-changelog, mergequeue-status: waiting

#13410 chore(iast): removing redundant operations
  ddtrace/appsec/_deduplications.py
  ddtrace/appsec/_iast/_iast_request_context_base.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/code_injection.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/insecure_cookie.py
  ddtrace/appsec/_iast/taint_sinks/sql_injection.py
  ddtrace/appsec/_iast/taint_sinks/weak_cipher.py
  ddtrace/appsec/_iast/taint_sinks/weak_hash.py
  tests/appsec/iast/test_processor.py
  tests/appsec/iast/test_telemetry.py
Labels: changelog/no-changelog, ASM

#13444 chore(iast): fix taint tracking in langchain 0.3.60
  ddtrace/appsec/_iast/_langchain.py
  tests/appsec/integrations/langchain_tests/test_iast_langchain.py
Labels: changelog/no-changelog, ASM

#13448 chore(ci_visibility): move retry logic to pytest_runtest_protocol
  ddtrace/contrib/internal/pytest/_atr_utils.py
  ddtrace/contrib/internal/pytest/_attempt_to_fix.py
  ddtrace/contrib/internal/pytest/_efd_utils.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/pytest/_retry_utils.py
  ddtrace/contrib/internal/pytest/_utils.py
  ddtrace/contrib/internal/pytest/plugin.py
Labels: changelog/no-changelog, CI App

#13401 fix(profiling): crash with `synchronized_sample_pool` on uWSGI shutdown [backport 2.21]
  ddtrace/internal/datadog/profiling/dd_wrapper/CMakeLists.txt
  ddtrace/internal/datadog/profiling/dd_wrapper/include/constants.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/sample_manager.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/static_sample_pool.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/include/synchronized_sample_pool.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/sample_manager.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/static_sample_pool.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/synchronized_sample_pool.cpp
  releasenotes/notes/fix-crash-in-uwsgi-94d23690d85b2981.yaml
Labels: Profiling

#13450 chore(llmobs): add additional typing
  ddtrace/llmobs/_evaluators/ragas/base.py
  ddtrace/llmobs/_evaluators/runner.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_writer.py
Labels: changelog/no-changelog

#13446 chore: update changelog for version 3.7.1
  CHANGELOG.md
Labels: changelog/no-changelog

#13391 chore(benchmarks): combine ddtrace-run and startup benchmarks
  .gitlab/benchmarks/microbenchmarks.yml
  benchmarks/ddtrace_run/config.yaml
  benchmarks/ddtrace_run/scenario.py
  benchmarks/startup/config.yaml
  benchmarks/startup/scenario.py
Labels: changelog/no-changelog

#13456 ci: upgrade pytest version used in tests
  .riot/requirements/1f5205e.txt
  .riot/requirements/f903257.txt
  lib-injection/sources/min_compatible_versions.csv
  min_compatible_versions.csv
  riotfile.py
Labels: changelog/no-changelog, backport 2.21

#13452 fix(ci_visibility): honor the DD_CIVISIBILITY_ITR_ENABLED env var
  ddtrace/internal/ci_visibility/recorder.py
  releasenotes/notes/ci-vis-itr-enabled-env-var-db5bf0cd6bbe8821.yaml
Labels: CI App, backport 2.21, backport 3.7

#13468 fix(ci_visibility): use git tag as branch name if no branch name available
  ddtrace/internal/ci_visibility/git_data.py
  releasenotes/notes/ci_visibility-fix-use-git-tag-as-branch-971227009e6496a6.yaml
  tests/ci_visibility/test_git_data.py
Labels: CI App, backport 2.21

#13465 chore(iast): fix api version to send metastruct data if appsec is disabled
  ddtrace/appsec/_iast/taint_sinks/code_injection.py
  ddtrace/internal/writer/writer.py
  tests/appsec/app.py
  tests/appsec/appsec_utils.py
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
Labels: changelog/no-changelog, ASM

#13184 docs: fix command to ID deprecated 2.0 env vars
  docs/upgrading.rst
Labels: changelog/no-changelog

#13473 ci: all tests are run if anything changes in pytest integration
  scripts/gen_gitlab_config.py
Labels: changelog/no-changelog, CI App, CI

#13475 fix(tracing): handle unicode when truncating long span attributes
  ddtrace/internal/_encoding.pyx
  releasenotes/notes/truncate-long-span-attributes-unicode-6bb71d739f989051.yaml
  tests/integration/test_integration_snapshots.py
  tests/snapshots/tests.integration.test_integration_snapshots.test_encode_span_with_large_unicode_string_attributes[v0.4].json
  tests/snapshots/tests.integration.test_integration_snapshots.test_encode_span_with_large_unicode_string_attributes[v0.5].json
Labels: backport 3.7

#13472 chore(iast): check ranges sources
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/taint_range.cpp
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/taint_range.h
  ddtrace/appsec/_iast/_taint_tracking/tests/test_taintrange_origin.cpp
  tests/appsec/iast/taint_tracking/test_native_taint_range.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
Labels: changelog/no-changelog, ASM

#13490 chore: format cpp files and block ci iff there's format diff
  ddtrace/internal/datadog/profiling/dd_wrapper/include/static_sample_pool.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/static_sample_pool.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  scripts/cformat.sh
Labels: changelog/no-changelog, Profiling

#13489 chore: update changelog for version 3.7.2
  CHANGELOG.md
Labels: changelog/no-changelog

#13493 chore: update changelog for version 3.8.0
  CHANGELOG.md
Labels: changelog/no-changelog

#13418 chore(profiling): enable memalloc large heap test
  tests/profiling_v2/collector/test_memalloc.py
Labels: changelog/no-changelog, Profiling

#13498 chore(profiling): make recorder an optional parameter for collectors
  ddtrace/profiling/collector/__init__.py
  ddtrace/profiling/collector/_lock.py
  ddtrace/profiling/collector/memalloc.py
  ddtrace/profiling/collector/stack.pyx
  tests/profiling_v2/collector/test_asyncio.py
  tests/profiling_v2/collector/test_memalloc.py
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/collector/test_threading.py
Labels: changelog/no-changelog, Profiling

#13501 chore(asm): remove unnecessary byref in waf interface
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_ddwaf/waf.py
Labels: changelog/no-changelog, ASM

#13507 chore(ci_visibility): remove RetryTestReport, clean up Attempt-to-Fix
  ddtrace/contrib/internal/pytest/_atr_utils.py
  ddtrace/contrib/internal/pytest/_attempt_to_fix.py
  ddtrace/contrib/internal/pytest/_efd_utils.py
  ddtrace/contrib/internal/pytest/_retry_utils.py
  ddtrace/contrib/internal/pytest/_utils.py
  tests/contrib/pytest/test_pytest_attempt_to_fix.py
Labels: changelog/no-changelog, CI App

#13481 feat(iast): unvalidated redirect vulnerability
  ddtrace/appsec/_iast/_evidence_redaction/_sensitive_handler.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/taint_range.cpp
  ddtrace/appsec/_iast/_taint_tracking/taint_tracking/taint_range.h
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/secure_marks/validators.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  ddtrace/appsec/_iast/taint_sinks/unvalidated_redirect.py
  releasenotes/notes/iast-feat-unvalidated-redirect-7d1fcbe25889589a.yaml
  tests/appsec/iast/taint_sinks/test_unvalidated_redirect_redacted.py
  tests/appsec/integrations/django_tests/django_app/urls.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/fastapi_tests/test_fastapi_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
Labels: ASM

#13474 feat(packages): symlinked .runfile pkgs should not be usercode
  ddtrace/internal/packages.py
  tests/debugging/origin/test_span.py
  tests/internal/test_packages.py
Labels: changelog/no-changelog, backport 2.21

#13519 ci(iast): microbenchmark flakiness
  benchmarks/appsec_iast_aspects/scenario.py
  benchmarks/appsec_iast_aspects_ospath/config.yaml
  benchmarks/appsec_iast_aspects_ospath/scenario.py
  benchmarks/appsec_iast_aspects_split/scenario.py
Labels: changelog/no-changelog, ASM

#13514 chore: upgrade ruff
  benchmarks/appsec_iast_aspects/functions.py
  benchmarks/appsec_iast_aspects_ospath/functions.py
  benchmarks/appsec_iast_aspects_re_module/functions.py
  benchmarks/appsec_iast_aspects_split/functions.py
  benchmarks/bm/iast_fixtures/str_methods.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_taint_tracking/aspects.py
  ddtrace/appsec/_processor.py
  ddtrace/contrib/internal/algoliasearch/patch.py
  ddtrace/internal/utils/http.py
  hatch.toml
  pyproject.toml
  tests/appsec/appsec_utils.py
  tests/appsec/iast/aspects/test_asyncio.py
  tests/appsec/iast/fixtures/propagation_path.py
  tests/appsec/iast/taint_sinks/test_ssrf.py
  tests/appsec/integrations/flask_tests/test_gunicorn_handlers.py
  tests/contrib/flask_cache/test_wrapper_safety.py
Labels: changelog/no-changelog

#13485 ci: migrate rust ci from GitHub Actions to GitLab
  .github/workflows/rust-ci.yml
  .gitlab-ci.yml
  .gitlab/native.yml
Labels: changelog/no-changelog

#13529 chore: updated development guide anchor link
  docs/shared.rst
Labels: changelog/no-changelog

#13512 test: fix silently broken uses of parametrize_with_all_encodings
  ddtrace/internal/runtime/container.py
  tests/integration/test_integration.py
  tests/integration/test_integration_snapshots.py
  tests/integration/test_priority_sampling.py
  tests/integration/utils.py
Labels: changelog/no-changelog

#13533 ci: pin system-tests version
  .github/workflows/system-tests.yml
  scripts/update-system-tests-version.py
Labels: changelog/no-changelog

#13526 feat(dsm): context support for sqs -> lambda
  ddtrace/internal/datastreams/botocore.py
  releasenotes/notes/add-sqs-lambda-context-support-5062a60d81055ed7.yaml
  tests/datastreams/test_botocore.py
Labels: mergequeue-status: removed

#13480 chore: remove make_async_decorator from compat.py
  ddtrace/_trace/tracer.py
  ddtrace/internal/compat.py
Labels: changelog/no-changelog

#13542 chore(iast): reorganize tests
  tests/appsec/integrations/django_tests/test_appsec_django.py
  tests/appsec/integrations/django_tests/test_iast_django.py
  tests/appsec/integrations/flask_tests/test_iast_flask_testagent.py
  tests/appsec/integrations/utils_testagent.py
Labels: changelog/no-changelog, ASM

#13527 fix(sampling): fix agent sampling when tracer.configure is used
  ddtrace/_trace/tracer.py
  ddtrace/internal/writer/writer.py
  releasenotes/notes/fix-agent-sampling-processor-5298a70d9b2154e6.yaml
  tests/integration/test_priority_sampling.py
  tests/tracer/test_writer.py
Labels: backport 2.21

#13518 chore(ci_visibility): remove special handling of exit status for failed retries
  ddtrace/contrib/internal/pytest/_plugin_v2.py
Labels: changelog/no-changelog, CI App

#13201 chore(tracing): add deprecation warning for DD_TRACE_GLOBAL_TAGS
  ddtrace/_trace/product.py
  releasenotes/notes/deprecate-dd_trace_global_tags-b3d29bddc3dffe0c.yaml
  tests/commands/test_runner.py
Labels: changelog/no-changelog

#13466 chore(llmobs): tli add apm trace
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_llmobs.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_propagation.py
Labels: changelog/no-changelog
