Repository DataDog/dd-trace-py, pull requests merged in 2025-01, with the labels that each got.

#11791 chore(tracer): remove asm properties from the tracer class
  ddtrace/_trace/tracer.py
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/contrib/internal/requests/connection.py
  ddtrace/pin.py
  ddtrace/settings/asm.py
  tests/appsec/appsec/test_asm_standalone.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/utils.py
  tests/contrib/django/test_django_appsec.py
  tests/contrib/django/test_django_appsec_iast.py
  tests/contrib/djangorestframework/test_appsec.py
  tests/contrib/fastapi/test_fastapi_appsec.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
  tests/contrib/flask/test_flask_appsec.py
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_telemetry.py
  tests/contrib/requests/test_requests_distributed.py
  tests/contrib/urllib3/test_urllib3.py
  tests/tracer/test_tracer.py
Labels: changelog/no-changelog

#11848 fix(profiling): remove slow getpid call from memalloc path
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_heap.c
  ddtrace/profiling/collector/_memalloc_reentrant.h
  releasenotes/notes/profiling-remove-getpid-from-memalloc-74f54043accdfc9e.yaml
Labels: backport 2.17, backport 2.18, backport 2.19

#11857 chore(otel): supress unessesary warning
  ddtrace/internal/opentelemetry/span.py
  tests/opentelemetry/test_span.py
Labels: changelog/no-changelog

#11864 chore(ci): exclude pinned packages from auto-updating requirements
  scripts/freshvenvs.py
Labels: changelog/no-changelog

#11860 refactor(profiling): add debug check that the GIL is held to memalloc
  ddtrace/profiling/collector/_memalloc.c
  ddtrace/profiling/collector/_memalloc_debug.h
  ddtrace/profiling/collector/_memalloc_heap.c
Labels: changelog/no-changelog, Profiling

#11858 ci: fix flaky test_custom_traceback_size_with_error on Python 3.13
  tests/tracer/test_span.py
Labels: changelog/no-changelog

#11760 feat(iast): header injection for fastapi
  ddtrace/appsec/_iast/taint_sinks/header_injection.py
  releasenotes/notes/iast-fastapi-header-injection-ce4805c91e87ebe2.yaml
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: ASM

#11869 test(er): fix broken exception ID asserts
  tests/debugging/exception/test_replay.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#11853 chore(telemetry): make logs less noisy and more clear
  ddtrace/internal/telemetry/writer.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, backport 2.19

#11861 chore: skip failing urlib3 ASM test
  tests/contrib/urllib3/test_urllib3.py
Labels: changelog/no-changelog

#11877 ci: fix flaky es search query
  tests/contrib/elasticsearch/test_elasticsearch.py
Labels: changelog/no-changelog

#11764 chore: clarify usage and wording for current_root_span
  ddtrace/_trace/tracer.py
Labels: changelog/no-changelog, mergequeue-status: removed

#11873 ci: fix CircleCI dynamic job selection
  scripts/gen_circleci_config.py
Labels: changelog/no-changelog

#11870 feat(asm): cmdi patch refactor + rasp support
  .github/CODEOWNERS
  ddtrace/appsec/_capabilities.py
  ddtrace/appsec/_common_module_patches.py
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_iast/_pytest_plugin.py
  ddtrace/appsec/_iast/taint_sinks/command_injection.py
  ddtrace/appsec/_metrics.py
  ddtrace/appsec/_processor.py
  ddtrace/contrib/internal/subprocess/patch.py
  releasenotes/notes/rasp_cmdi-3c7819ee9e33e447.yaml
  tests/appsec/appsec/rules-rasp-blocking.json
  tests/appsec/appsec/rules-rasp-disabled.json
  tests/appsec/appsec/rules-rasp-redirecting.json
  tests/appsec/appsec/rules-rasp.json
  tests/appsec/appsec/test_remoteconfiguration.py
  tests/appsec/contrib_appsec/django_app/urls.py
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/iast/taint_sinks/test_command_injection.py
Labels: ASM

#11850 chore: swap out deprecated datetime's utcnow and utcfromtimestamp
  ddtrace/internal/debug.py
  ddtrace/profiling/exporter/http.py
  tests/appsec/iast_packages/packages/pkg_pyjwt.py
Labels: changelog/no-changelog

#11856 chore(llmobs): assert using span events instead of mocks
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_decorators.py
  tests/llmobs/test_llmobs_evaluator_runner.py
  tests/llmobs/test_llmobs_ragas_faithfulness_evaluator.py
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_propagation.py
Labels: changelog/no-changelog

#11881 fix(profiling): access lock acquired time only when the lock is held
  ddtrace/profiling/collector/_lock.py
  releasenotes/notes/profiling-lock-acquired-at-e308547cffdca9f7.yaml
Labels: Profiling

#11885 chore(iast): optimize _should_iast_patch
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/appsec/_python_info/stdlib/__init__.py
  tests/appsec/iast/_ast/test_ast_patching.py
Labels: changelog/no-changelog, ASM

#11893 chore(asm): update python version for threats tests
  hatch.toml
Labels: changelog/no-changelog, ASM

#11846 chore(llmobs): refactor out ragas base evaluator
  ddtrace/llmobs/_evaluators/ragas/base.py
  ddtrace/llmobs/_evaluators/ragas/faithfulness.py
  ddtrace/llmobs/_evaluators/runner.py
  tests/llmobs/_utils.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_evaluators.emits_traces_and_evaluations_on_exit.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_evaluators.test_ragas_faithfulness_emits_traces.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_evaluators.test_ragas_faithfulness_submits_evaluation.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_evaluators.test_ragas_faithfulness_submits_evaluation_on_span_with_custom_keys.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_evaluators.test_ragas_faithfulness_submits_evaluation_on_span_with_question_in_messages.yaml
  tests/llmobs/test_llmobs_evaluator_runner.py
  tests/llmobs/test_llmobs_ragas_evaluators.py
Labels: changelog/no-changelog

#11894 fix(er): include nonlocals in snapshots
  ddtrace/debugging/_safety.py
  releasenotes/notes/fix-er-include-nonlocals-bbeecfbbbde35496.yaml
  tests/debugging/exception/test_replay.py
  tests/debugging/test_safety.py
Labels: Dynamic Instrumentation, backport 2.16, backport 2.17, backport 2.18, backport 2.19

#11868 docs(tracing): remove patch_all from basic usage docs [3.0]
  ddtrace/_monkey.py
  docs/basic_usage.rst
  docs/index.rst
  docs/installation_quickstart.rst
Labels: changelog/no-changelog

#11827 chore(iast): migrate test packages to gitlab
  .circleci/config.templ.yml
  hatch.toml
  scripts/gen_gitlab_config.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#11883 chore(iast): taint flask request args and form
  ddtrace/appsec/_asm_request_context.py
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_listener.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: changelog/no-changelog, ASM

#11842 feat(iast): code injection
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/taint_sinks/code_injection.py
  releasenotes/notes/iast-feat-code-injection-0213a27bc3340505.yaml
  tests/appsec/iast/conftest.py
  tests/appsec/iast/fixtures/taint_sinks/code_injection.py
  tests/appsec/iast/taint_sinks/test_code_injection.py
  tests/appsec/iast/test_telemetry.py
Labels: ASM

#11811 chore: remove vendored contextvars module
  ddtrace/internal/compat.py
  ddtrace/internal/coverage/code.py
  ddtrace/vendor/__init__.py
  ddtrace/vendor/contextvars/__init__.py
  tests/vendor/test_contextvars.py
Labels: changelog/no-changelog

#11903 chore(profiling): increase error margin for flaky tests
  tests/profiling/test_accuracy.py
  tests/profiling_v2/test_accuracy.py
Labels: changelog/no-changelog, Profiling

#11914 chore(iast): skip package tests for denylist packages
  ddtrace/appsec/_iast/_ast/ast_patching.py
  tests/appsec/iast_packages/test_packages.py
Labels: changelog/no-changelog, ASM

#11797 chore(llmobs): make tests runnable outside riot
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs_eval_metric_writer.py
  tests/llmobs/test_llmobs_evaluator_runner.py
  tests/llmobs/test_llmobs_ragas_evaluators.py
  tests/llmobs/test_llmobs_span_agentless_writer.py
Labels: changelog/no-changelog

#11810 chore(profiling): update flaky marker
  tests/profiling/collector/test_stack.py
Labels: changelog/no-changelog, Profiling

#11904 fix: resolve asyncio event loop bug when gevent is installed
  .github/workflows/test_frameworks.yml
  ddtrace/internal/compat.py
  releasenotes/notes/resolves-gevent-asyncio-incompatiblities-246028676b10bea9.yaml
  tests/contrib/asyncio/test_lazyimport.py
Labels: backport 2.19

#11930 chore: enable iast packages
  tests/appsec/iast_packages/test_packages.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#11917 feat(profiling): enable stack v2 by default
  ddtrace/settings/profiling.py
  releasenotes/notes/profiling-stack-v2-default-ecd535ccf0c73ce0.yaml
  riotfile.py
  tests/internal/crashtracker/test_crashtracker.py
  tests/profiling_v2/collector/test_stack.py
  tests/telemetry/test_writer.py
Labels: Profiling

#11934 chore(ci): add python3.13 weblog in system tests
  .github/workflows/system-tests.yml
Labels: changelog/no-changelog

#11891 chore: clean up snowflake instructions
  ddtrace/contrib/snowflake/__init__.py
Labels: changelog/no-changelog

#11564 chore(telemetry): improves typing for telemetry metric namespaces
  ddtrace/_monkey.py
  ddtrace/_trace/processor/__init__.py
  ddtrace/_trace/telemetry.py
  ddtrace/appsec/_iast/_metrics.py
  ddtrace/appsec/_metrics.py
  ddtrace/internal/ci_visibility/telemetry/api_request.py
  ddtrace/internal/ci_visibility/telemetry/constants.py
  ddtrace/internal/ci_visibility/telemetry/coverage.py
  ddtrace/internal/ci_visibility/telemetry/early_flake_detection.py
  ddtrace/internal/ci_visibility/telemetry/events.py
  ddtrace/internal/ci_visibility/telemetry/git.py
  ddtrace/internal/ci_visibility/telemetry/itr.py
  ddtrace/internal/ci_visibility/telemetry/payload.py
  ddtrace/internal/telemetry/constants.py
  ddtrace/internal/telemetry/metrics_namespaces.py
  ddtrace/internal/telemetry/writer.py
  ddtrace/llmobs/_evaluators/ragas/base.py
  ddtrace/llmobs/_evaluators/runner.py
  ddtrace/llmobs/_evaluators/sampler.py
  ddtrace/settings/_otel_remapper.py
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/contrib_appsec/utils.py
  tests/appsec/iast/test_telemetry.py
  tests/telemetry/app.py
  tests/telemetry/test_telemetry_metrics.py
  tests/tracer/test_processors.py
Labels: changelog/no-changelog

#11929 ci: add healthcheck while setting up test http server process
  tests/appsec/iast/conftest.py
Labels: changelog/no-changelog, ASM, CI

#11953 chore(ci): pin `greenlet` version to 3.1.0 for 3.8
  .riot/requirements/1d4e95e.txt
  .riot/requirements/2d19e52.txt
  .riot/requirements/6bec1ec.txt
  riotfile.py
Labels: changelog/no-changelog, backport 2.19

#11948 chore(ci): new testrunner for check_new_flaky_tests [2.18]
  .gitlab-ci.yml
  .gitlab/testrunner.yml
  .gitlab/tests.yml
Labels: changelog/no-changelog, apm:ecosystems

#11716 chore(llmobs): implement ragas context precision
  ddtrace/llmobs/_evaluators/ragas/base.py
  ddtrace/llmobs/_evaluators/ragas/context_precision.py
  ddtrace/llmobs/_evaluators/ragas/models.py
  ddtrace/llmobs/_evaluators/runner.py
  tests/llmobs/_utils.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_evaluators.test_ragas_context_precision_multiple_context.yaml
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_evaluators.test_ragas_context_precision_single_context.yaml
  tests/llmobs/test_llmobs_ragas_evaluators.py
Labels: changelog/no-changelog

#11915 chore(llmobs): implement answer relevancy ragas metric
  ddtrace/llmobs/_evaluators/ragas/answer_relevancy.py
  ddtrace/llmobs/_evaluators/ragas/base.py
  ddtrace/llmobs/_evaluators/ragas/models.py
  ddtrace/llmobs/_evaluators/runner.py
  tests/llmobs/_utils.py
  tests/llmobs/conftest.py
  tests/llmobs/llmobs_cassettes/tests.llmobs.test_llmobs_ragas_evaluators.answer_relevancy_inference.yaml
  tests/llmobs/test_llmobs_ragas_evaluators.py
Labels: changelog/no-changelog

#11947 chore(ci): new testrunner for check_new_flaky_tests [2.17]
  .gitlab-ci.yml
  .gitlab/testrunner.yml
  .gitlab/tests.yml
Labels: changelog/no-changelog, ASM

#11932 feat(asm): update the ATO support with the new specifications
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_trace_utils.py
  releasenotes/notes/ATO_V3-e7f73ecf00d1474b.yaml
  tests/appsec/contrib_appsec/fastapi_app/app.py
  tests/appsec/contrib_appsec/flask_app/app.py
  tests/appsec/contrib_appsec/utils.py
Labels: changelog/no-changelog

#11931 chore(appsec): migrate test integrations to gitlab
  .circleci/config.templ.yml
  .riot/requirements/1147cef.txt
  .riot/requirements/1221a04.txt
  .riot/requirements/131666a.txt
  .riot/requirements/16ed652.txt
  .riot/requirements/173e759.txt
  .riot/requirements/17b5eda.txt
  .riot/requirements/1a1ddb4.txt
  .riot/requirements/1b0d603.txt
  .riot/requirements/1e2d655.txt
  .riot/requirements/1e81527.txt
  .riot/requirements/1fb9968.txt
  .riot/requirements/2b94418.txt
  .riot/requirements/5e31227.txt
  .riot/requirements/628e8fe.txt
  .riot/requirements/8dd53b1.txt
  .riot/requirements/968fdc9.txt
  .riot/requirements/e53ccba.txt
  hatch.toml
  riotfile.py
  tests/appsec/app.py
  tests/appsec/integrations/django_tests/__init__.py
  tests/appsec/integrations/flask_tests/__init__.py
  tests/appsec/integrations/flask_tests/module_with_import_errors.py
  tests/appsec/integrations/flask_tests/test_flask_remoteconfig.py
  tests/appsec/integrations/flask_tests/test_gunicorn_handlers.py
  tests/appsec/integrations/flask_tests/test_iast_flask_entrypoint_iast_patches.py
  tests/appsec/integrations/flask_tests/test_iast_flask_patching.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
  tests/appsec/integrations/flask_tests/test_iast_langchain.py
  tests/appsec/integrations/flask_tests/test_iast_psycopg2.py
  tests/appsec/integrations/flask_tests/utils.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#11945 chore(iast): taint get and post http parameter name in django
  ddtrace/appsec/_iast/_handlers.py
  tests/contrib/django/django_app/appsec_urls.py
  tests/contrib/django/test_django_appsec_iast.py
Labels: changelog/no-changelog, ASM

#11981 chore(asm): addendum to ATO V3
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_processor.py
  ddtrace/appsec/_trace_utils.py
  tests/appsec/appsec/test_processor.py
  tests/appsec/contrib_appsec/utils.py
  tests/contrib/django/test_django_appsec.py
Labels: changelog/no-changelog, ASM

#11982 chore(pin): remove all deprecated references [3.0]
  ddtrace/__init__.py
  ddtrace/contrib/aredis/__init__.py
  ddtrace/contrib/httpx/__init__.py
  ddtrace/contrib/internal/mongoengine/trace.py
  ddtrace/contrib/internal/pylibmc/client.py
  ddtrace/contrib/internal/pymongo/client.py
  ddtrace/contrib/internal/tornado/application.py
  ddtrace/contrib/redis/__init__.py
  ddtrace/contrib/yaaredis/__init__.py
  docs/api.rst
Labels: changelog/no-changelog

#11937 ci: optimize ci runtime [backport 2.19]
  .gitlab/package.yml
  .gitlab/tests.yml
  hatch.toml
  scripts/gen_gitlab_config.py
  tests/suitespec.yml
Labels: changelog/no-changelog

#11950 fix(lib-injection): fix incorrect telemetry data payload format
  lib-injection/sources/sitecustomize.py
  releasenotes/notes/fix-ssi-telemetry-events-a0a01ad0b6ef63b5.yaml
Labels: backport 2.18, backport 2.19

#11989 chore(profiling): print gunicorn worker startup times in test
  tests/profiling_v2/gunicorn.conf.py
  tests/profiling_v2/test_gunicorn.py
Labels: changelog/no-changelog, Profiling

#11941 chore(tracing): expose Span, Tracer, and tracer in ddtrac.trace
  ddtrace/__init__.py
  ddtrace/_trace/tracer.py
  ddtrace/trace/__init__.py
Labels: changelog/no-changelog

#11925 chore(tracer): early exit on none value for propagation inject and extract
  ddtrace/propagation/http.py
  ddtrace/settings/config.py
  tests/tracer/test_propagation.py
Labels: changelog/no-changelog

#11979 chore: migrate django appsec tests to appsec integration
  .github/CODEOWNERS
  hatch.toml
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/django_app/__init__.py
  tests/appsec/integrations/django_tests/django_app/settings.py
  tests/appsec/integrations/django_tests/django_app/urls.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_django_appsec.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_flask_remoteconfig.py
  tests/appsec/integrations/flask_tests/test_iast_flask_entrypoint_iast_patches.py
  tests/appsec/suitespec.yml
  tests/contrib/django/django_app/urls.py
Labels: changelog/no-changelog, ASM

#11996 chore(iast): iast code injection error with locals and globals
  ddtrace/appsec/_iast/taint_sinks/code_injection.py
  tests/appsec/iast/fixtures/taint_sinks/code_injection.py
  tests/appsec/iast/taint_sinks/test_code_injection.py
Labels: changelog/no-changelog, ASM

#11991 fix(profiling): reset all profiling c++ mutexes on fork [backport 2.17]
  ddtrace/internal/datadog/profiling/dd_wrapper/include/uploader_builder.hpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/code_provenance.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/ddup_interface.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/profile.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader.cpp
  ddtrace/internal/datadog/profiling/dd_wrapper/src/uploader_builder.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/sampler.cpp
  ddtrace/internal/datadog/profiling/stack_v2/src/thread_span_links.cpp
  releasenotes/notes/fix-profiling-native-mutices-62440b5a3d9d6c4b.yaml
Labels: Profiling

#11986 chore(llmobs): fix behavior for running multiple evaluators
  ddtrace/llmobs/_evaluators/runner.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_evaluator_runner.py
Labels: changelog/no-changelog

#12000 refactor(profiling): add more GIL assertions to memalloc
  ddtrace/profiling/collector/_memalloc.c
Labels: changelog/no-changelog

#11730 feat(langgraph): submit spans from langgraph to APM and LLMObs
  .github/CODEOWNERS
  .riot/requirements/115283d.txt
  .riot/requirements/18551a1.txt
  .riot/requirements/2bd0151.txt
  .riot/requirements/2e4fbd3.txt
  .riot/requirements/7dd4bcd.txt
  ddtrace/_monkey.py
  ddtrace/contrib/internal/langgraph/patch.py
  ddtrace/contrib/langgraph/__init__.py
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_integrations/langchain.py
  ddtrace/llmobs/_integrations/langgraph.py
  ddtrace/llmobs/_integrations/utils.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_utils.py
  riotfile.py
  tests/contrib/langgraph/__init__.py
  tests/contrib/langgraph/conftest.py
  tests/contrib/langgraph/test_langgraph.py
  tests/contrib/langgraph/test_langgraph_llmobs.py
  tests/contrib/langgraph/test_langgraph_patch.py
  tests/llmobs/suitespec.yml
Labels: changelog/no-changelog

#11977 chore: update changelog for version 2.19.1, 2.19.0, 2.18.2, 2.17.5, 2.17.4
  CHANGELOG.md
Labels: changelog/no-changelog

#11951 chore(di): don't redact env tokens from probe snapshots
  ddtrace/debugging/_redaction.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12008 Revert "fix(tracing): only extract distributed headers if a trace is not already started"
  ddtrace/contrib/trace_utils.py
  ddtrace/settings/config.py
  releasenotes/notes/fix-unncessary-header-extraction-c1facf2b30331afb.yaml
  tests/contrib/wsgi/test_wsgi.py
  tests/utils.py
Labels: changelog/no-changelog

#11882 chore(cos): include module and function on exit
  ddtrace/debugging/_function/discovery.py
  ddtrace/debugging/_origin/span.py
  ddtrace/internal/utils/inspection.py
  tests/debugging/conftest.py
  tests/debugging/test_debugger.py
  tests/debugging/test_debugger_span_decoration.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12012 ci: add missing permissions to publish musl i686 image
  .github/workflows/pypa_musllinux_1_2_i686.yml
Labels: changelog/no-changelog

#11997 chore(llmobs): remove public notice of `submit_evaluation_for`
  ddtrace/llmobs/_llmobs.py
  releasenotes/notes/submit-evaluation-for-01096d803d969e3e.yaml
Labels: changelog/no-changelog

#11961 fix(llmobs): encode llm objects in utf-8 before sending
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_utils.py
  ddtrace/llmobs/_writer.py
  releasenotes/notes/fix-llmobs-json-encoding-ascii-f8da77867a910de1.yaml
  tests/contrib/langgraph/conftest.py
  tests/llmobs/conftest.py
  tests/llmobs/test_llmobs.py
  tests/llmobs/test_llmobs_span_agent_writer.py
  tests/llmobs/test_llmobs_span_agentless_writer.py
Labels: backport 2.18, backport 2.19

#12015 chore: use guess-next-dev instead of release-branch-semver [2.20]
  pyproject.toml
Labels: changelog/no-changelog

#11952 chore(llmobs): update ragas trace ml app
  ddtrace/llmobs/_constants.py
  ddtrace/llmobs/_evaluators/ragas/answer_relevancy.py
  ddtrace/llmobs/_evaluators/ragas/base.py
  ddtrace/llmobs/_evaluators/ragas/context_precision.py
  ddtrace/llmobs/_evaluators/ragas/faithfulness.py
  ddtrace/llmobs/_llmobs.py
  ddtrace/llmobs/_utils.py
  tests/llmobs/_utils.py
  tests/llmobs/test_llmobs_service.py
Labels: changelog/no-changelog

#12005 ci(iast): enable iast_aggregated_leak_testing tests
  hatch.toml
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#11985 ci(appsec): connect testagent service to tests
  hatch.toml
  scripts/gen_gitlab_config.py
  tests/appsec/integrations/flask_tests/test_flask_remoteconfig.py
  tests/appsec/suitespec.yml
Labels: changelog/no-changelog, ASM

#12009 chore(iast): taint parameter name and header name in fastapi
  ddtrace/appsec/_iast/_handlers.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#12019 ci: add missing permissions to publish misl i686 image on child job
  .github/workflows/build-and-publish-image.yml
Labels: changelog/no-changelog

#12024 ci(langgraph): fix flaky test
  tests/contrib/langgraph/test_langgraph.py
  tests/contrib/langgraph/test_langgraph_llmobs.py
Labels: changelog/no-changelog

#12038 chore(iast): taint parameter name in post requests in fastapi
  ddtrace/appsec/_iast/_handlers.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#12030 fix(ci_visibility): handle pytest ATR retry failures in unittest classes
  ddtrace/contrib/internal/pytest/_retry_utils.py
  releasenotes/notes/ci_visibility-fix-pytest-classes-b54582b09727fdc1.yaml
  tests/contrib/pytest/test_pytest_atr.py
Labels: backport 2.18, backport 2.19, backport 2.20

#12044 chore(profiling): remove `stack_v2_enabled=False` tests
  tests/profiling_v2/collector/test_stack.py
  tests/profiling_v2/collector/test_stack_asyncio.py
  tests/profiling_v2/test_accuracy.py
  tests/profiling_v2/test_gunicorn.py
  tests/profiling_v2/test_main.py
Labels: changelog/no-changelog, Profiling

#12027 ci: check for benchmark regressions on PRs
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#12045 ci(profiling): ignore deprecated function `tp_print` warning
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
Labels: changelog/no-changelog, Profiling

#12034 fix(llmobs): fix content arg extraction for vertex ai integration
  ddtrace/contrib/internal/vertexai/_utils.py
  ddtrace/contrib/internal/vertexai/patch.py
  ddtrace/llmobs/_integrations/vertexai.py
  releasenotes/notes/fix-vertexai-content-extraction-b216207bd8192e5f.yaml
  tests/contrib/vertexai/test_vertexai.py
  tests/contrib/vertexai/test_vertexai_llmobs.py
Labels: backport 2.19

#12022 chore(iast): "deduplication enabled" environment variable
  ddtrace/appsec/_deduplications.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/settings/asm.py
  docker-compose.yml
  docs/configuration.rst
  hatch.toml
  riotfile.py
  scripts/iast/.env
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast/_ast/conftest.py
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py
  tests/appsec/iast/taint_tracking/conftest.py
  tests/appsec/iast/test_processor.py
  tests/appsec/iast_aggregated_memcheck/test_aggregated_memleaks.py
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_psycopg2.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#12041 chore(iast): taint parameter name and header name in fastapi
  ddtrace/appsec/_iast/_handlers.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
Labels: changelog/no-changelog, ASM

#12039 chore(iast): add django to the allowlist
  ddtrace/appsec/_iast/_ast/ast_patching.py
Labels: changelog/no-changelog, ASM

#12007 feat(iast): implement the stacktrace leak vulnerability
  ddtrace/appsec/_iast/_handlers.py
  ddtrace/appsec/_iast/_iast_request_context.py
  ddtrace/appsec/_iast/_listener.py
  ddtrace/appsec/_iast/constants.py
  ddtrace/appsec/_iast/taint_sinks/stacktrace_leak.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/flask/patch.py
  hatch.toml
  releasenotes/notes/stacktrace-leak-d6840ab48b29af99.yaml
  tests/appsec/iast/fixtures/django_debug_page.html
  tests/appsec/iast/fixtures/plain_stacktrace.txt
  tests/appsec/iast/taint_sinks/test_stacktrace_leak.py
  tests/appsec/integrations/django_tests/django_app/urls.py
  tests/appsec/integrations/django_tests/django_app/views.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/conftest.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
Labels: ASM

#12062 chore(iast): "deduplication enabled" environment variable [backport 2.20]
  ddtrace/appsec/_deduplications.py
  ddtrace/appsec/_iast/taint_sinks/_base.py
  ddtrace/settings/asm.py
  docker-compose.yml
  docs/configuration.rst
  hatch.toml
  riotfile.py
  scripts/iast/.env
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/appsec_utils.py
  tests/appsec/iast/_ast/conftest.py
  tests/appsec/iast/aspects/conftest.py
  tests/appsec/iast/conftest.py
  tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py
  tests/appsec/iast/taint_tracking/conftest.py
  tests/appsec/iast/test_processor.py
  tests/appsec/iast_aggregated_memcheck/test_aggregated_memleaks.py
  tests/appsec/integrations/django_tests/conftest.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_psycopg2.py
  tests/contrib/dbapi/test_dbapi_appsec.py
  tests/contrib/fastapi/test_fastapi_appsec_iast.py
  tests/contrib/flask/test_flask_appsec_iast.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, ASM

#11851 chore(er): max frame setting
  ddtrace/debugging/_exception/replay.py
  ddtrace/settings/exception_replay.py
  tests/telemetry/test_writer.py
Labels: changelog/no-changelog, Dynamic Instrumentation

#12068 chore(iast): refactor django handlers and tests
  ddtrace/appsec/_iast/_handlers.py
  tests/appsec/integrations/django_tests/test_django_appsec_iast.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
Labels: changelog/no-changelog, ASM

#12049 ci: fix bm test to reflect behavior of config for propagation
  benchmarks/http_propagation_extract/scenario.py
  ddtrace/settings/config.py
Labels: changelog/no-changelog

#12025 refactor(asm): appsec and iast with product plugin interface
  .github/CODEOWNERS
  ddtrace/appsec/_remoteconfiguration.py
  ddtrace/bootstrap/preload.py
  ddtrace/internal/appsec/product.py
  ddtrace/internal/iast/product.py
  pyproject.toml
Labels: changelog/no-changelog, ASM

#12065 refactor(core): move src/core to src/native
  .github/workflows/rust-ci.yml
  ddtrace/internal/core/__init__.py
  ddtrace/internal/datastreams/processor.py
  ddtrace/internal/native/__init__.py
  ddtrace/internal/native/_native.pyi
  ddtrace/internal/processor/stats.py
  setup.py
  src/native/Cargo.lock
  src/native/Cargo.toml
  src/native/ddsketch.rs
  src/native/lib.rs
  tests/suitespec.yml
Labels: changelog/no-changelog

#12014 fix(openai): support Python 3.12, 3.13
  .riot/requirements/107d8f2.txt
  .riot/requirements/130158f.txt
  .riot/requirements/13804af.txt
  .riot/requirements/13fec34.txt
  .riot/requirements/181216c.txt
  .riot/requirements/1825740.txt
  .riot/requirements/18de44f.txt
  .riot/requirements/1ad89c5.txt
  .riot/requirements/1db5311.txt
  .riot/requirements/1e6bd37.txt
  .riot/requirements/1ec15f5.txt
  .riot/requirements/1ee49b9.txt
  .riot/requirements/2634bf7.txt
  .riot/requirements/35ce786.txt
  .riot/requirements/4a85f6d.txt
  .riot/requirements/4d27459.txt
  .riot/requirements/530c983.txt
  .riot/requirements/5da4fd8.txt
  .riot/requirements/87a1fff.txt
  .riot/requirements/b5d5a35.txt
  .riot/requirements/c74f6e0.txt
  .riot/requirements/cd2e4ea.txt
  .riot/requirements/df60af6.txt
  .riot/requirements/f1c37b1.txt
  ddtrace/contrib/internal/openai/_endpoint_hooks.py
  ddtrace/contrib/internal/openai/patch.py
  ddtrace/contrib/openai/__init__.py
  releasenotes/notes/fix-openai-313-29ec43cbf2f35947.yaml
  riotfile.py
  tests/contrib/openai/cassettes/v1/completion_stream_wrong_api_key.yaml
  tests/contrib/openai/test_openai_llmobs.py
  tests/contrib/openai/test_openai_patch.py
  tests/contrib/openai/test_openai_v0.py
  tests/contrib/openai/test_openai_v1.py
Labels: backport 2.19, backport 2.20

#11983 chore(llmobs): [MLOB-2064] add telemetry for custom vs. autoinstrumented span creation
  ddtrace/llmobs/_integrations/base.py
  ddtrace/llmobs/_llmobs.py
Labels: changelog/no-changelog

#12080 ci: move pr/regression check to benchmarks-report stage
  .gitlab-ci.yml
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog

#12055 chore(configs): internalize global config module and ddtrace.config's rc and http attributes [3.0]
  ddtrace/__init__.py
  ddtrace/_monkey.py
  ddtrace/_trace/sampler.py
  ddtrace/contrib/flask/__init__.py
  ddtrace/contrib/httplib/__init__.py
  ddtrace/contrib/internal/aiohttp/middlewares.py
  ddtrace/contrib/internal/botocore/patch.py
  ddtrace/contrib/internal/dramatiq/patch.py
  ddtrace/contrib/internal/httplib/patch.py
  ddtrace/contrib/internal/requests/connection.py
  ddtrace/contrib/internal/sanic/patch.py
  ddtrace/contrib/internal/tornado/handlers.py
  ddtrace/contrib/internal/trace_utils.py
  ddtrace/contrib/jinja2/__init__.py
  ddtrace/contrib/requests/__init__.py
  ddtrace/internal/remoteconfig/worker.py
  ddtrace/internal/sampling.py
  ddtrace/internal/writer/writer.py
  ddtrace/propagation/_database_monitoring.py
  ddtrace/settings/__init__.py
  ddtrace/settings/_config.py
  ddtrace/settings/config.py
  ddtrace/settings/dynamic_instrumentation.py
  ddtrace/settings/integration.py
  docs/advanced_usage.rst
  releasenotes/notes/munir-deprecate-rc-http-configs-206f6c60ff383c05.yaml
  tests/ci_visibility/test_ci_visibility.py
  tests/contrib/httplib/test_httplib_distributed.py
  tests/contrib/jinja2/test_jinja2.py
  tests/contrib/requests/test_requests.py
  tests/contrib/requests/test_requests_distributed.py
  tests/contrib/tornado/test_tornado_web.py
  tests/contrib/vertica/test_vertica.py
  tests/internal/remoteconfig/test_remoteconfig.py
  tests/internal/test_settings.py
  tests/telemetry/test_writer.py
  tests/tracer/test_env_vars.py
  tests/tracer/test_global_config.py
  tests/tracer/test_instance_config.py
  tests/tracer/test_settings.py
  tests/tracer/test_trace_utils.py
Labels: backport 2.20

#12078 chore(ci): increase profiling native test timeout
  .github/workflows/profiling-native.yml
Labels: changelog/no-changelog

#12013 ci(appsec): fix ddwaf circular import
  ddtrace/appsec/_metrics.py
Labels: changelog/no-changelog

#12070 fix(llmobs): fix token extraction for chat completion streams
  ddtrace/contrib/internal/openai/utils.py
  releasenotes/notes/fix-token-extraction-0133808742374ef4.yaml
Labels: backport 2.20

#12029 fix(ci, profiling): build native macos arm64 wheel
  .github/workflows/build_python_3.yml
  ddtrace/internal/datadog/profiling/cmake/AnalysisFunc.cmake
  ddtrace/internal/datadog/profiling/crashtracker/CMakeLists.txt
  ddtrace/internal/datadog/profiling/ddup/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/CMakeLists.txt
  ddtrace/internal/datadog/profiling/stack_v2/test/CMakeLists.txt
  pyproject.toml
  releasenotes/notes/ci-mac-build-37f7e55c8289de61.yaml
Labels: Profiling

#12093 ci: add GHA job to check if `main` can be merged to 3.x branches
  .github/workflows/check_safe_main_merge.yml
Labels: changelog/no-changelog

#12088 chore: update changelog for version 2.19.2
  CHANGELOG.md
Labels: changelog/no-changelog

#12075 fix(profiling): fix SystemError when collecting memory profiler events
  ddtrace/profiling/collector/_memalloc.c
  releasenotes/notes/profiling-memalloc-iter-events-null-780fd50bbebbf616.yaml
Labels: backport 2.18, backport 2.19, backport 2.20

#12122 ci(tracer): make serverless test unrequired
  .gitlab/benchmarks.yml
Labels: changelog/no-changelog, CI

#12117 feat(asm): meta struct enable by default for 3.0
  ddtrace/settings/asm.py
  releasenotes/notes/msgpack_for_appsec-e09c17e9cb568379.yaml
Labels: ASM

#12102 chore(asm): clean libddwaf loading
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_processor.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/settings/asm.py
Labels: changelog/no-changelog, ASM

#12120 chore(asm): remove deprecated env var
  ddtrace/appsec/_constants.py
  ddtrace/settings/asm.py
  releasenotes/notes/removal_of_DD_APPSEC_AUTOMATED_USER_EVENTS_TRACKING-c1b4d2141ee92add.yaml
  tests/telemetry/test_writer.py
Labels: ASM

#12095 fix(iast): fix import loop
  ddtrace/appsec/_iast/_ast/ast_patching.py
  ddtrace/internal/packages.py
  releasenotes/notes/fix-asm-package-distributions-import-loop-11693f2a26032774.yaml
Labels: ASM, backport 2.20

#12089 fix(llmobs): propagate distributed headers via signal dispatching, not config
  ddtrace/llmobs/_llmobs.py
  ddtrace/propagation/http.py
  releasenotes/notes/fix-llmobs-enable-updates-config-45379a7a30e2e0e3.yaml
  tests/llmobs/test_llmobs_service.py
  tests/llmobs/test_propagation.py
  tests/tracer/test_propagation.py
Labels: manual merge, backport 2.19, backport 2.20

#12135 feat(provider): expose context provider in ddtrace.trace
  .github/CODEOWNERS
  ddtrace/provider.py
  ddtrace/trace/__init__.py
  docs/advanced_usage.rst
  releasenotes/notes/feat-expose-base-context-provider-530ebec2225f6c8d.yaml
Labels: backport 2.20

#12147 docs: update trace filter docs
  docs/advanced_usage.rst
  docs/troubleshooting.rst
Labels: changelog/no-changelog, backport 2.20

#12107 chore(integrations): avoids using deprecated apis in ``ddtrace.patch(....)`` [3.0]
  ddtrace/_monkey.py
  ddtrace/appsec/_iast/_patch_modules.py
  ddtrace/contrib/cherrypy/__init__.py
  ddtrace/contrib/flask_cache/__init__.py
  ddtrace/contrib/internal/aioredis/patch.py
  ddtrace/contrib/internal/cassandra/patch.py
  ddtrace/contrib/internal/cherrypy/patch.py
  ddtrace/contrib/internal/fastapi/patch.py
  ddtrace/contrib/internal/flask_cache/patch.py
  ddtrace/contrib/internal/pytest/_plugin_v2.py
  ddtrace/contrib/internal/redis/patch.py
  ddtrace/llmobs/_llmobs.py
  docs/contributing-integrations.rst
  releasenotes/notes/ensure-all-integrations-have-patch-module-ef2ced613d1f777a.yaml
  tests/contrib/asyncio/test_tracer.py
  tests/contrib/cherrypy/test_middleware.py
  tests/contrib/flask_cache/test.py
  tests/contrib/flask_cache/test_utils.py
  tests/contrib/flask_cache/test_wrapper_safety.py
  tests/contrib/langgraph/test_langgraph_patch.py
  tests/tracer/test_monkey.py
Labels: backport 2.20

#12145 chore(asm): clean libddwaf loading [forwardport 3.x]
  ddtrace/appsec/_ddwaf/ddwaf_types.py
  ddtrace/appsec/_processor.py
  ddtrace/contrib/internal/subprocess/patch.py
  ddtrace/settings/asm.py
Labels: changelog/no-changelog, ASM

#12036 chore(ci): skip non-linux OCI package creation
  .gitlab/prepare-oci-package.sh
Labels: changelog/no-changelog, CI, backport 2.15, backport 2.16, backport 2.17, backport 2.18, backport 2.19, backport 2.20

#12139 chore: update changelog for version 2.19.2 [forwardport 3.x]
  CHANGELOG.md
Labels: changelog/no-changelog

#12128 ci(profiling): run smoke test with built wheels
  .github/workflows/build_python_3.yml
  tests/smoke_test.py
Labels: changelog/no-changelog, Profiling, backport main

#12171 chore: remove `check_safe_main_merge` workflow
  .github/workflows/check_safe_main_merge.yml
Labels: changelog/no-changelog

#12150 fix(llmobs): don't enqueue spans to an inactive evaluator runner
  ddtrace/llmobs/_evaluators/runner.py
  releasenotes/notes/fix-evaluator-runner-log-fcd0aa18602d4252.yaml
  tests/llmobs/test_llmobs_evaluator_runner.py
  tests/llmobs/test_llmobs_service.py
Labels: backport 2.16, backport 2.17, backport 2.18, backport 2.19, backport 2.20

#12132 chore(llmobs): [MLOB-2089] remove python 3.7 tests from test suite
  .riot/requirements/16562eb.txt
  .riot/requirements/df60af6.txt
  riotfile.py
Labels: changelog/no-changelog

#12069 chore(asm): improve user blocking for django (auth middleware)
  ddtrace/appsec/_constants.py
  ddtrace/appsec/_trace_utils.py
  ddtrace/appsec/trace_utils/__init__.py
  ddtrace/contrib/internal/django/patch.py
  ddtrace/contrib/internal/trace_utils.py
Labels: changelog/no-changelog, ASM

#12164 chore(tracing): refactor web server integrations to use the core module [forwardport 3.x]
  ddtrace/_trace/trace_handlers.py
  ddtrace/contrib/internal/aiohttp/middlewares.py
  ddtrace/contrib/internal/bottle/trace.py
  ddtrace/contrib/internal/cherrypy/patch.py
  ddtrace/contrib/internal/falcon/middleware.py
  ddtrace/contrib/internal/molten/patch.py
  ddtrace/contrib/internal/pyramid/trace.py
  ddtrace/contrib/internal/sanic/patch.py
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_child.json
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_error.json
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_fatal.json
  tests/snapshots/tests.contrib.cherrypy.test_middleware.test_success.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_multiple_requests_sanic_http_pre_21.9.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors.json
  tests/snapshots/tests.contrib.sanic.test_sanic_server.test_sanic_errors_pre_21.9.json
Labels: changelog/no-changelog

#12114 chore(iast): update evidence redaction suite tests
  ddtrace/appsec/_iast/_evidence_redaction/_sensitive_handler.py
  ddtrace/appsec/_iast/_evidence_redaction/default_sensitive_analyzer.py
  ddtrace/appsec/_iast/_handlers.py
  tests/appsec/iast/taint_sinks/_taint_sinks_utils.py
  tests/appsec/iast/taint_sinks/redaction_fixtures/evidence-redaction-suite.json
  tests/appsec/iast/taint_sinks/test_code_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_command_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_header_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_path_traversal_redacted.py
  tests/appsec/iast/taint_sinks/test_sql_injection_redacted.py
  tests/appsec/iast/taint_sinks/test_ssrf_redacted.py
Labels: changelog/no-changelog, ASM

#12115 ci(appsec): move Flask (appsec and iast) tests
  tests/appsec/appsec/test_telemetry.py
  tests/appsec/integrations/flask_tests/test_appsec_flask.py
  tests/appsec/integrations/flask_tests/test_appsec_flask_telemetry.py
  tests/appsec/integrations/flask_tests/test_iast_flask.py
  tests/appsec/integrations/flask_tests/test_iast_flask_telemetry.py
  tests/contrib/flask/test_appsec_flask_snapshot.py
Labels: changelog/no-changelog, ASM

#12192 ci: add `3.x-staging` to the build job trigger branches
  .github/workflows/build_deploy.yml
Labels: changelog/no-changelog
